### ISSUE TITLE
More UV-coords

### ISSUE THREAD

**Issue by VladimirPobedinskiy** [urho3d/Urho3D#1001]
Now mdl format support 2 UV sets of UV-coords. In some cases need more UV-coords, max 4 - typical scenario: RGB-masking (RGB mask, R-channel texture, G-channel texture, B-channel texture,), (may be more - 8).
Need change format of mdl to support more UV coords, change asset importers code to support this feature and write converter to new mdl format.

**Comment by cadaver** [comment]
This is covered by issue 707: https://github.com/urho3d/Urho3D/issues/707
