### ISSUE TITLE
RenderPath strange behaviour

### ISSUE THREAD

**Issue by MonkeyFirst** [urho3d/Urho3D#1002]
As i mentioned, in my topic - Render Path have a wierd behavior (by executing command path)
http://urho3d.prophpbb.com/topic1514.html

I made video to demonstrate this issue. 
https://www.youtube.com/watch?v=oyJ9SvOrwh8

In video i open scene, editor by default have DoF render path.
But it wierd looks. Like as some of commands of render path are missing.
I guessing because not all commands apply to renderer by some issue, or maybe (other my guessing) what the XMLParser have some problems with parsing.

And if i several times do selecting other RP and then try to choice the RP what i needed - it works as expected. This is not only editor problem I have a same behavior in my compiled project.

Also I do debug trace of my project. I look into (DoF) RP-commands one by one.
and find what the  command->outputs_ vector are always empty,  even if I have custom or "viewport" output RT for quad command. Is this normal ? maybe this "outputs_" only for MRT rendering?

**Comment by cadaver** [comment]
There may be a bug in your shaders. I observe a dependency of the blurring on camera angle. Maybe you're not reading the depth from the correct position in the depth texture? (Do some debug renders to determine this)

Also, you're using undefined uniforms. If you have a rendertarget called "blurredFrameV" then the inverse size uniform you should be using in your shader should be cblurredFrameVInvSize.

There's a mismatch of conventions that Bloom shader uses rendertargets HBlur and VBlur, while the blur shader uses BlurH and BlurV. I'll unify that.

**Comment by MonkeyFirst** [comment]
Thanks Lasse for clarify.
Yes. now i found this uniform naming place. 
In View.cpp -> RenderQuad
        String invSizeName = rtInfo.name_ + "InvSize";
        String offsetsName = rtInfo.name_ + "Offsets";


>then the inverse size uniform you should be using in your shader should be cblurredFrameVInvSize

Is it case sensive?
I guessing what this must to be documented about - naming of InvSize and Offsets.

just for clarify if we have such RP path:
![123](https://cloud.githubusercontent.com/assets/9577466/10882239/3195d1a2-8193-11e5-9dda-205d2d80409f.png)
we got all uniforms of those RTs in shader

vec2 cViewportInvSize
vec2 cBlurVInvSize
vec2 cStoredInvSize

or only for outputs RT -

vec2 cViewportInvSize ?

**Comment by cadaver** [comment]
This is documented in http://urho3d.github.io/documentation/HEAD/_render_paths.html

The uniform names are case insensitive. Yes, the quad rendering will try to apply all those InvSize uniforms for all rendertargets defined in the renderpath, also those that are not used in the current command. If the uniform is not actually defined in the shader, then no harm done, and it should early-exit fairly fast.

cViewportInvSize uniform doesn't exist, rather it's historically called cGBufferInvSize, as it was originally needed for deferred rendering.

**Comment by MonkeyFirst** [comment]
Thanks.
And last question: 
Is XML have a strong style formatting? 
I mean if I write an empty line between other command of RenderPath is this fatal for parsing?

**Comment by cadaver** [comment]
Extra lines and whitespace are allowed. You will know when XML parsing fails, because you get a resource load error.
