### ISSUE TITLE
Renderer2D draw order

### ISSUE THREAD

**Issue by cosmy1** [urho3d/Urho3D#1003]
There is a bug related to layers if camera is non ortographic.
Basically if a sprite is under another one their Z is ignored.
Would be nice to keep layers when camera is ortographic and Z when is not.

![1](https://cloud.githubusercontent.com/assets/1329119/10873127/ab9a6c80-810f-11e5-9437-0066be0e40c8.png)
![2](https://cloud.githubusercontent.com/assets/1329119/10873128/acaa174c-810f-11e5-880f-cd1397de80db.png)

**Comment by cadaver** [comment]
I see that the SourceBatch2D drawOrder_ is an integer so it's not easy to add distance ordering without adding another member variable, which needs to be updated every frame. @aster2013 Do you plan to look into this before release? Either way is fine for me, it looks like that currently the 2D rendering purposefully disregards Z or distance.

**Comment by aster2013** [comment]
Draw order and Z is difference in Urho2D. Draw order is controlled by layer and order in layer, basically Urho2D only use draw order to sort batches.

**Comment by cosmy1** [comment]
But there are cases when you want 2D elements using a perspective camera. i.e. just think how easier would be to achieve parallx scrolling. As we can put 2D elements in the 3D world would be nice to have a flag which allow ignoring layers and consider Z.

Something like
```c++
void SetLayeringEnabled(bool enable);
bool IsLayeringEnabled() const;
```
In this case we keep both ways without breaking anything.

**Comment by aster2013** [comment]
if (camera->IsOrthographic())
    Sort by Draw order
else
    Sort by Z value

It is OK for you?

**Comment by cosmy1** [comment]
For me is fine as is more automatic and everything is handled internally.

**Comment by aster2013** [comment]
@cosmy1 , I have added distance for 2d objects, please check it.

**Comment by cosmy1** [comment]
Ok, problem solved.
