### ISSUE TITLE
spine animation not properly report memory usage

### ISSUE THREAD

**Issue by yushli** [urho3d/Urho3D#1009]
using sample 33's c++ source code. and change line 86 into
AnimationSet2D* spriterAnimationSet = cache->GetResource("Urho2D/imp/spineboy.json");

spineboy.json is from
https://github.com/EsotericSoftware/spine-runtimes/tree/master/spine-c/data

If press F3 to report memory usage, Sprite2D and AnimationSet2D are both zero.

**Comment by yushli** [comment]
Also some of the memory usage is just the static resource file size. Is it viable to report accurate memory usage?

**Comment by cadaver** [comment]
It's a guideline, but not completely viable. Some resources like Material try to account for the size of internal structures, but generally writing this code is a pain in the ass, and it's especially cumbersome to reflect runtime resource manipulation in the memory use. Probably the most important is that large resources like meshes and textures are reported as accurately as possible; that is probably where one would enable memory budgeting at first, if needed.
