### ISSUE TITLE
HoverBegin HoverEnd Bug

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1010]
Events HoverBegin and HoverEnd do not call when mouse cursor is hiding after click

Example:
https://drive.google.com/open?id=0B_XuF2wRVpw4X0xENUM4blAwNms

1) Run Game.exe. When mouse is hover texts, their color is changes.
2) Click "New Game"
3) Press Esc on keyboard.
4) When mouse hover "New Game", its color is changes, but when hover "Exit", its color is not changes.

I think it is related with DragNDropTest.

**Comment by cadaver** [comment]
The bug comes from manipulating cursor visibility during the click event handling.
