### ISSUE TITLE
Camera farClip on Android

### ISSUE THREAD

**Issue by Mike3D** [urho3d/Urho3D#1011]
I'm experimenting an issue with camera farClip on Android.

For example in sample 11_Physics, if I set Z position for the cubes above 130 then the pyramid doesn't show up (farClip is set to 500 in this sample).

As discussed in the forum (http://urho3d.prophpbb.com/post8938.html#p8938), I've tried to add some depth bits setting for the OpenGL ES depth buffer, but to no avail.

**Comment by cadaver** [comment]
Managed to reproduce this now. It's not related to farclip as such. It's the skybox rendering itself too close and obscuring everything else behind it.

**Comment by Mike3D** [comment]
A big thank for this one, it was really annoying :+1:
