### ISSUE TITLE
the UI style cannot change the text font

### ISSUE THREAD

**Issue by souxiaosou** [urho3d/Urho3D#1013]
UIelement had.been missing some.function

**Comment by cadaver** [comment]
No idea what this is about. We do have UI style controlling text font successfully, e.g. in DefaultStyle.xml
```
    <element type="Text">
        <attribute name="Font" value="Font;Fonts/Anonymous Pro.ttf" />
        <attribute name="Font Size" value="11" />
        <attribute name="Color" value="0.85 0.85 0.85" />
    </element>
```
If necessary, please reopen with a clear explanation of what the actual problem is. Otherwise we are unable to help.
