### ISSUE TITLE
Model from Resource Browser without materials

### ISSUE THREAD

**Issue by VladimirPobedinskiy** [urho3d/Urho3D#1018]
If I drag model from Resource Browser windows to node - model placed without materials.

**Comment by JSandusky** [comment]
Model resources and their contained geometries do not contain materials.

If you drag a prefab object (such as Ninja.xml) that contains a model component with materials then those materials are loaded.

**Comment by VladimirPobedinskiy** [comment]
Sandusky, yes, by logic this right. But when I create component Model and pick mdl-file, editor reads txt file with materials and applies them (only if specified in the settings). I think this one operation by logic - pick model by selecting file in model propeties or drag and drop model from resource browser.

**Comment by cadaver** [comment]
This is missing a call to ApplyMaterialList(), which the other code paths do.

**Comment by JSandusky** [comment]
My bad, I wasn't aware of that functionality.
