### ISSUE TITLE
[Feature] Add Node->Remove(TimeToDelete) & Scene->InstantiateXML(... lifeTime)

### ISSUE THREAD

**Issue by MonkeyFirst** [urho3d/Urho3D#1026]
It very handy for objects with short life time, like bullets, missle... ect

**Comment by cadaver** [comment]
IMO any time of lifetime counting is not a part of the core scene graph, but should be implemented with a logic component that does the time counting, similar to the GameObject base class in NinjaSnowWar.

You may disagree, and in a game engine with another kind of design it might be desirable, however in Urho3D additional behavior is supposed to be in components as much as possible.

**Comment by MonkeyFirst** [comment]
Yes i disagree. Logic component is "huge thing" for this little ability.
