### ISSUE TITLE
[DX11] FillMode Point == Line

### ISSUE THREAD

**Issue by MonkeyFirst** [urho3d/Urho3D#1028]
if you try to change fill mode to point fill it will be a same as line fill.

**Comment by cadaver** [comment]
Point mode is not supported directly by D3D11, so it would have to do an emulation (point sprites?)

**Comment by MonkeyFirst** [comment]
i'm do not know much about dx11, but this flag do not set points?
D3D11_PRIMITIVE_TOPOLOGY_POINTLIST

**Comment by cadaver** [comment]
That is used when the mesh or drawcall itself defines that you want to render points, not in fill mode. However we could try to redefine the drawcall during runtime to use that if the point fill mode is active.
