### ISSUE TITLE
[DX11] constant bias + slope bias 

### ISSUE THREAD

**Issue by MonkeyFirst** [urho3d/Urho3D#1029]
In DX9 I remember if I change one of them to -1 or 1 then object that will have this material will be always on top of then screen (always visible even if it far away from camera and occluded by others objects )(by Z-order). But if I change this values on DX11 no any changes.

**Comment by cadaver** [comment]
It looks like D3D11 cannot tolerate "ridiculously" large constant depth bias values. -1 would actually mean taking a pixel from the far clip plane and transporting it all the way to the near clip plane. I observed something like -0.3 still working, while testing with the UrhoDecal material. Usually workable values are rather small, like -0.0001 or something.

**Comment by MonkeyFirst** [comment]
Oh, thanks for note. I tried this, and yes it working in -0.3f
