### ISSUE TITLE
[Feature] Add cached Scene.GetNodesByTags( tag ) and Node tags

### ISSUE THREAD

**Issue by MonkeyFirst** [urho3d/Urho3D#1030]
I found that @svifilabs realize this cool stuff.
https://github.com/svifylabs/Urho3D/commit/fbd6831cbd81ca3a382ec9033b292dff1c13f260

it's cool because it do caching all scene's nodes into vectors by tags and keep it in actual view. In this case it have a fastest way to get all scenes nodes marked with tags as: "enemy", "trigger", "npc" and so on...

**Comment by cadaver** [comment]
Looks good, and straightforward.
