### ISSUE TITLE
Process doesn't end on Windows because of UAC virtualization

### ISSUE THREAD

**Issue by Enhex** [urho3d/Urho3D#1031]
urho application's process may not end for some users on Windows if they don't have write permission.
That happens because of UAC virtualization:
https://decibel.ni.com/content/groups/windows-7/blog/2009/10/02/uac-virtualization-and-how-it-affects-your-installers

If Urho is trying to write something to Urho3D.log on shutdown and doesn't quit until that happens that could be the reason for the process not ending.

**Comment by cadaver** [comment]
The log location is configurable, for example Urho3DPlayer redirects it to a user writable directory. Though the engine default is to write into the current directory.

**Comment by Enhex** [comment]
How to set that option?
I'm using a slightly modified Urho3DPlayer to extend the scripting API and it still happens.

**Comment by friesencr** [comment]
Application takes parameters from the system:
https://github.com/urho3d/Urho3D/blob/master/Source/Urho3D/Engine/Application.cpp#L54

Engine parses parameters:
https://github.com/urho3d/Urho3D/blob/master/Source/Urho3D/Engine/Engine.cpp#L183

In your case you will use "LogName"

**Comment by Enhex** [comment]
I was missing the line:
```C++
engineParameters_["LogName"] = GetSubsystem<FileSystem>()->GetAppPreferencesDir("urho3d", "logs") + GetTypeName() + ".log";
```
