### ISSUE TITLE
Unresolved external symbol

### ISSUE THREAD

**Issue by ToxikCoder** [urho3d/Urho3D#1039]
I builded and compiled 1.5 version with URHO3D_D3D11 set to 1, fixed everything that was needed fixing according to IntelliSense. But now I have unresolved external symbols. Those are: D3D11CreateDevice(), __IID_IDXGIAdapter, __IID_IDXGIFactory, __IID_IDXGIDevice, __IID_IDXGIDevice1, __IID_ID3D11Texture2D, __IID_ID3D11ShaderReflection.
I suspect that I am missing some DX11 libraries, but I'm not sure.
Please, help me, if you can.

**Comment by Sasha7b9** [comment]
Property project -> Configuration Properties -> Linker -> Input -> Additional Dependicies ;
kernel32.lib
user32.lib
gdi32.lib
winspool.lib
shell32.lib
ole32.lib
oleaut32.lib
uuid.lib
comdlg32.lib
advapi32.lib
winmm.lib
imm32.lib
version.lib
ws2_32.lib
dbghelp.lib
d3d11.lib
d3dcompiler.lib
dxgi.lib
dxguid.lib

It is also possible to look properties samples.
Is question for forum : http://urho3d.prophpbb.com/

**Comment by ToxikCoder** [comment]
Thanks, adding d3d11.lib, d3dcompiler.lib, dxgi.lib, dxguid.lib helped

**Comment by rasteron** [comment]
Hi, I encountered the same errors on a recent build with **VS2008** and **D3D11** as an option. For some reason, adding only `dxguid.lib` just works. I'm not sure if this is the right way but it works for me. Found the solution [here](http://stackoverflow.com/a/5966485/4397269) prior seeing this conversation. 

I have to mention that those needed libs were not included in the generated solution files by CMake where it should be in the first place. 

Thanks.

**Comment by weitjong** [comment]
Are you using the latest master branch? From what I understand the VS2008 will be using DirectX SDK instead of Windows SDK. If the dxgui is not found then the whole FindDirect3D would fail as a whole. So, I don't understand why you could get your project configured but yet missing the dxgui library.

**Comment by rasteron** [comment]
Yes, as I have mentioned above I'm using the latest master branch. I did find out earlier that I also have VS2005 installed which also has dxguid.lib, so this was probably the reason why it is getting configured. BTW, June2010 DirectX SDK also has the dxguid.lib, d3d11.lib, etc.. if it makes any difference.

`cmake_vs2008 ./dx11 -DURHO3D_D3D11=1`
...
...
`-- Found Direct3D: C:/Program Files (x86)/Microsoft DirectX SDK (June 2010)/Lib/x86/d3d11.lib;C:/Program Files (x86)/Microsoft DirectX SDK (June 2010)
/Lib/x86/d3dcompiler.lib;C:/Program Files (x86)/Microsoft DirectX SDK (June 2010)/Lib/x86/dxgi.lib;C:/Program Files (x86)/Microsoft Visual Studio/VC98/Lib/DXGUID.LIB
`

Thanks for the info and confirmation.

**Comment by ToxikCoder** [comment]
I used VS2013 on Windows 8.1 x64 if you're still interested
