### ISSUE TITLE
A node twitches when rotation.x > 95

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1040]
1. Open editor.
2. Add any object to scene.
3. Increase the rotation of using slider
   ![2](https://cloud.githubusercontent.com/assets/13021826/11158984/678727bc-8a75-11e5-961c-983b0e591d57.jpg)

**Comment by MonkeyFirst** [comment]
strange, but if you rotate object by gizmo there is no twitches.

**Comment by cadaver** [comment]
The gizmo does pure quaternion math for rotation. Editing the rotation attribute performs repeated quat -> euler -> quat conversions, which may be ambiguous and that results in visual twitching.
