### ISSUE TITLE
Crash with URHO3D_SSE=1 on VS2010 in release mode

### ISSUE THREAD

**Issue by cadaver** [urho3d/Urho3D#1044]
Application crashes to null pointer references after SSE optimized math operations (e.g. Matrix3x4 multiply) when compiled with Visual Studio 2010 release mode.

Possibly a compiler bug. If no other solution is readily possible, SSE could be disabled by default on VS2010 (URHO3D_SSE=0)

**Comment by juj** [comment]
Thanks, I'll give this a peek. In MathGeoLib I do recall problems with VS2010 and some of the code paths there are gated on `_MSC_VER >= 1700` (>= VS2012).

**Comment by juj** [comment]
Hmm, indeed, this is a Visual Studio 2010 issue. In VS2010 32-bit RelWithDebInfo build with SSE enabled, I am seeing a crash at

    Matrix3x4 Camera::GetEffectiveWorldTransform() const
    {
        Matrix3x4 worldTransform = node_ ? Matrix3x4(node_->GetWorldPosition(), node_->GetWorldRotation(), 1.0f) : Matrix3x4::IDENTITY;
        return useReflection_ ? reflectionMatrix_ * worldTransform : worldTransform;
    }

where the local variable `worldTransform` ends up being aligned to 8 bytes (fine, we never specified alignment to the compiler for the `Matrix3x4` type), but looking at the code that VS2010 generates for the ternary statement looks like this:

	    return useReflection_ ? reflectionMatrix_ * worldTransform : worldTransform;
	00A133EB  cmp         byte ptr [edi+266h],0  
	00A133F2  lea         eax,[ebp-40h]  
	00A133F5  movups      xmm0,xmmword ptr [eax]  
	00A133F8  movups      xmm1,xmmword ptr [eax+10h]  
	00A133FC  movups      xmm2,xmmword ptr [eax+20h]  
	00A13400  movups      xmm0,xmm0  
	00A13403  movups      xmm1,xmm1  
	00A13406  movups      xmm2,xmm2  
	00A13409  movaps      xmmword ptr [worldTransform],xmm0 (*)
	00A1340D  movaps      xmmword ptr [ebp-60h],xmm1  
	00A13411  movaps      xmmword ptr [ebp-50h],xmm2  

with a crash at the line marked with a star, on `Access violation reading location 0xffffffff.`, which is the CPU's way of saying that an alignment fault occurred. The `movaps` instruction requires its memory store operand to be aligned to 16 bytes, but `worldTransform` was only aligned to 8 bytes. The copy constructor and assignment operators for `Matrix3x4` both read

        _mm_storeu_ps(&m00_, _mm_loadu_ps(&matrix.m00_));
        _mm_storeu_ps(&m10_, _mm_loadu_ps(&matrix.m10_));
        _mm_storeu_ps(&m20_, _mm_loadu_ps(&matrix.m20_));

and with the "u" variants, these are explicitly saying that the compiler should perform unaligned copies, but for some reason VS2010 has decided to elevate these from the unaligned `movups` instructions to aligned `movaps` instructions, even though it failed to provide the proper alignment for the stack variable `worldTransform`. Oops.

**Comment by juj** [comment]
Posted a workaround in that PR.

Tried to be minimal with the amount of SSE code disabled for VS2010, but it's possible that other copy ctors/assignment ops may exhibit the same VS2010 miscompilation. Given that it the problem always occurs clear crash (and not e.g. a silent failure or something other insidious), probably better to add workarounds on a case-by-case basis as they arise to keep the amount of SSE code disabled on VS2010 to a minimum.
