### ISSUE TITLE
D3D11 shader interpolator order bug when using point lights and VCol techniques

### ISSUE THREAD

**Issue by cadaver** [urho3d/Urho3D#1048]
Shader compiler messes up the interpolator order; needs tweaking of the LitSolid shader source to make sure the order is kept.

**Comment by MonkeyFirst** [comment]
Using structs for input and output. 
Like in turso3d https://github.com/cadaver/turso3d/blob/master/Bin/Data/Diffuse.vs
Maybe solve this problem?

**Comment by cadaver** [comment]
Maybe. Though the same shader code needs to work on D3D9, which may have some difficulty in handling the mandatory semantics (basically, position.)

**Comment by MonkeyFirst** [comment]
Is this normal behavior for NoTexVColLit ? (this one mesh, and it's painted with fully white color in Blender )
[url=http://savepic.su/6546097.htm][img]http://savepic.su/6546097m.png[/img][/url]
Actually at first time a got a strange behavior of lightning even with Structs in shaders. But then I trying to upper the "float4 iColor : COLOR0;" and place it exactly under float4 iWorldPos in both shaders VS/PS
http://pastebin.com/HSP7Z6Ew

**Comment by cadaver** [comment]
Yes the image looks OK. I believe our problem is the point light optional mask vector; the engine is lax in setting correct defines for VS/PS (because on D3D9 and OpenGL it doesn't matter) and by moving the color we are hiding the error.
