### ISSUE TITLE
Add RemoveViewport() to RenderSurface

### ISSUE THREAD

**Issue by Enhex** [urho3d/Urho3D#1049]
While using SetViewport() with nullptr should remove the SharedPtr ref count (does it? std::shared_ptr does), it requires the user to inspect the implementation to make sure how memory is going to be managed.

Having a RemoveViewport(index) would abstract away memory management questions like "Does it store raw or shared pointers to the viewports?" and "If I set it to nullptr, would the ref count go down?".

**Comment by cadaver** [comment]
We have several similar cases, for example SetMaterial with null ptr unassigns a material from a Drawable. Adding a corresponding Remove..() function to each of these would be a lot of API clutter, considering the Set...() function works just fine. Rather the user should be able to trust Urho's general memory management principles.

**Comment by Enhex** [comment]
It isn't about trust, it's about abstraction.
How would a single function of a missing abstraction would clutter the API?
Wouldn't adding a comment that says "oh don't worry you can set to null to properly remove" would be just as cluttering and much less expressive and explicit?

Also compared to Set...(index, pointer), Remove...(index) only has one parameter, so it isn't a "renamed" set.
