### ISSUE TITLE
Render to a texture with antialiasing

### ISSUE THREAD

**Issue by t-artikov** [urho3d/Urho3D#1050]
Add the ability to render to a texture(RenderSurface) with multisample antialiasing, please.
I know there is the FXAA filter, but it does not always provide an acceptable quality.

**Comment by cadaver** [comment]
Doable, but fairly significant work as antialiased rendertargets are usually created with a different API function and are not directly readable as textures, rather need to be resolved to a texture first, so one is actually keeping both a multisampled rendertarget, and the standard texture in GPU memory.

**Comment by OldSnake22** [comment]
Would be nice to have for defered rendering based games !

**Comment by cadaver** [comment]
This would also be beneficial for better quality VSM shadows. I may work on this in the somewhat near future.

**Comment by cadaver** [comment]
Now being worked on. The aim is to implement two kinds of multisampled textures: those that resolve automatically into single-sample after rendering, and those that remain multisampled for reading per sample in a specialized shader. The latter will not be supported on Direct3D9.

Note that this certainly will not be a turn-key solution for deferred MSAA, for that one needs to implement own renderpath and custom lighting shaders that are aware of the multiple G-buffer samples. There are some non-trivial issues to take care for correctness and good performance, like referred to in http://www.crytek.com/cryengine/presentations/the-rendering-technologies-of-crysis-3

I don't think I will be writing a default implementation for this in Urho.

**Comment by OldSnake22** [comment]
So if i understand right we can't do anti-aliasing in deferred rendering with this feature ?

**Comment by cadaver** [comment]
It should gives you all the engine-level building blocks that are needed (the rest is just shader code, and the feature should be completable without further engine changes), but it isn't a complete solution in itself.

**Comment by OldSnake22** [comment]
Alright :) Is it possible for you to add super sampling anti aliasing directly in engine API (that give a very nice quality boost and it is not so expensive in terms of performances) ? I know it is possible to do it by modifying the deferred renderpath like this (added SSAA rendertarget): 

`<renderpath>

	
    <rendertarget name="albedo" sizemultiplier="1.0 1.0" format="rgba16f" />
    <rendertarget name="normal" sizemultiplier="1.0 1.0" format="rgba16f" />
    <rendertarget name="depth" sizemultiplier="1.0 1.0" format="lineardepth" />
    <rendertarget name="SSAA" sizemultiplier="1.5 1.5" format="rgba16f" filter="true" />

	<rendertarget name="RefractColorRT" sizemultiplier="1.0 1.0" format="rgba16f" filter="true" />
	
	
    <command type="clear" color="fog" depth="1.0" stencil="0" output="SSAA" />
	<command type="clear" color="0 0 0 0" output="depth" /> 
	
	
    <command type="scenepass" pass="deferred" marktostencil="true" vertexlights="true" metadata="gbuffer">
        <output index="0" name="SSAA" />
        <output index="1" name="albedo" />
        <output index="2" name="normal" />
        <output index="3" name="depth" />
    </command>
	
	
	
    <command type="lightvolumes" vs="DeferredLight" ps="DeferredLight" output="SSAA">
        <texture unit="albedo" name="albedo" />
        <texture unit="normal" name="normal" />
        <texture unit="depth" name="depth" />
    </command>
	
	
	
    <command type="scenepass" pass="postopaque" output="SSAA" />
	
	
	
	<command type="quad" vs="CopyFramebuffer" ps="CopyFramebuffer" output="RefractColorRT">
        <texture unit="diffuse" name="SSAA" />
    </command>
	
	<command type="scenepass" pass="refract" output="SSAA">
        <texture unit="environment" name="RefractColorRT" />
    </command>
	
	
    <command type="scenepass" pass="alpha" vertexlights="true" sort="backtofront" metadata="alpha" output="SSAA" />
    <command type="scenepass" pass="postalpha" sort="backtofront" output="SSAA" />
	
    <command type="quad" vs="CopyFramebuffer" ps="CopyFramebuffer" output="viewport">
        <texture unit="diffuse" name="SSAA" />
    </command>

</renderpath>
`

But i can't see how to modify the PBRDeferred renderpath to do the same thing. So a "in engine" solution to do this would be nice.

**Comment by cadaver** [comment]
The way to do it is exactly with the renderpath, there is no special "in engine" solution that should be done. Of course if there are any bugs that would prevent bigger-than-viewport textures working properly, those should be taken care of.

**Comment by OldSnake22** [comment]
Here is the PBR renderpath: 

```
<renderpath>
    <rendertarget name="specular" sizedivisor="1 1" format="rgba16f" />
    <rendertarget name="albedo" sizedivisor="1 1" format="rgba16f" />
    <rendertarget name="normal" sizedivisor="1 1" format="rgba16f" />
    <rendertarget name="depth" sizedivisor="1 1" format="lineardepth" />
    <command type="clear" color="0 0 0 0" depth="1.0" stencil="0" />
    <command type="clear" color="0 0 0 0" output="albedo" />
    <command type="clear" color="0 0 0 0" output="specular" />
    <command type="clear" color="0 0 0 0" output="normal" />
    <command type="clear" color="0 0 0 0" depth="1.0" output="depth" />
    <command type="scenepass" pass="base" vertexlights="true" metadata="base" />
    <command type="scenepass" pass="deferred" marktostencil="true" vertexlights="true" metadata="gbuffer">
        <output index="0" name="specular" />
        <output index="1" name="albedo" />
        <output index="2" name="normal" />
        <output index="3" name="depth" />
    </command>
    <command type="lightvolumes" vs="PBRDeferred" ps="PBRDeferred" psdefines="PBRDEFERRED PBR" vsdefines="PBR" output="viewport">
        <texture unit="specular" name="specular" />
        <texture unit="albedo" name="albedo" />
        <texture unit="normal" name="normal" />
        <texture unit="depth" name="depth" />
    </command>
    <command type="scenepass" pass="postopaque" />
    <command type="scenepass" pass="refract">
        <texture unit="environment" name="viewport" />
    </command>
    <command type="scenepass" pass="alpha" vertexlights="true" sort="backtofront" metadata="alpha" />
    <command type="scenepass" pass="postalpha" sort="backtofront" />
</renderpath>
```

I am confused on how to add SSAA inside it as the simple deferred renderpath is different here: 

Deferred: 

```
<output index="0" name="viewport" />
<output index="1" name="albedo" />
<output index="2" name="normal" />
<output index="3" name="depth" />
```

PBR deffered:

```
<output index="0" name="specular" />
<output index="1" name="albedo" />
<output index="2" name="normal" />
<output index="3" name="depth" />
```

Can you help here ? :)

**Comment by cadaver** [comment]
Looks like the PBR G-buffer pass doesn't touch the final output (viewport) at all, so you need 5 SSAA sized buffers. It's actually the base pass that will add the initial viewport contribution of objects (such as IBL lighting) @dragonCASTjosh should be more familiar with the operation of that renderpath, I haven't studied it in depth.

**Comment by dragonCASTjosh** [comment]
The deferred render path renders out to the viewport whilst doing the the lightvolumes



    <command type="lightvolumes" vs="PBRDeferred" ps="PBRDeferred" psdefines="PBRDEFERRED PBR" vsdefines="PBR" output="viewport">
      <texture unit="specular" name="specular" />
      <texture unit="albedo" name="albedo" />
      <texture unit="normal" name="normal" />
      <texture unit="depth" name="depth" />
    </command>


And then things such as IBL and emmisive values are applied on top of that

**Comment by dragonCASTjosh** [comment]
To add onto this i want to look into doing TAA at some point soon that should be able to apply to all aspects of rendering for example the output of SSR will have a TAA pass to smooth the edges.

**Comment by t-artikov** [comment]
Great! Thank you.
I will check it in near future.
