### ISSUE TITLE
MushroomWind.xml don't render shadows 

### ISSUE THREAD

**Issue by MonkeyFirst** [urho3d/Urho3D#1052]
http://savepic.su/6526568.png
At first I thought it's a bug because I rewrote part of the shader to using structures, but then I decided to check out the latest master and there are also shadows do not work properly
renderer on  DX11

I tried to change the order of incoming attributes but it did not solve this

**Comment by cadaver** [comment]
In this case the interpolators between two shaders (Vegetation & Shadow) need to match on D3D11, which obviously seems to be not so.

**Comment by MonkeyFirst** [comment]
Thanks, I will try use this fixed version and rewrite it for my brunch with structs using.
