### ISSUE TITLE
Quaternion::operator== SSE implementation bugged

### ISSUE THREAD

**Issue by Enhex** [urho3d/Urho3D#1053]
CPU: Intel Core i5-2400

It seems Quaternion::operator== SSE implementation is bugged and always(?) returns false.

This test returns true for me:
```C++
if (Quaternion::IDENTITY != Quaternion::IDENTITY)
{
    // we have a bug
}
```

Operator != is just:
```C++
return !(*this == rhs);
```

or
```C++
if (!(Quaternion::IDENTITY == Quaternion::IDENTITY))
{
    // we have a bug
}
```
Also maybe unit tests should be considered? It can help catch such bugs.

**Comment by cosmy1** [comment]
Having unit tests is a good idea. I've used GoogleTest in the past and I liked it. Also is licensed under BSD which is compatible with Urho3D.

BTW, for me these conditions never happens (I have a i7-4780S).

**Comment by Enhex** [comment]
Any idea what may cause it?
Perhaps there are open source SIMD libs that know how to deal with what causes the problem?

**Comment by cadaver** [comment]
Couldn't reproduce on an Intel i7 and VS2013.

What compiler and build type are you using?

**Comment by cosmy1** [comment]
Have you tried with URHO3D_SSE off?

**Comment by Enhex** [comment]
VS2015, 32 bit build, both release & debug.

My current workaround it to manually use the non-SSE code (just comparing the components).

**Comment by cadaver** [comment]
Reproduced on VS2015, used processor doesn't matter.

**Comment by juj** [comment]
Debugging this, it looks like a Visual Studio 2015 compiler regression bug, where the compiler incorrectly inserts the `cmovbe` instruction when a `cmovae` instruction should have been generated. Reported this at https://connect.microsoft.com/VisualStudio/feedback/details/2053175 (click on the `DETAILS` button at the bottom of that page to see the page content) and posted the pull request #1056 as a workaround.

**Comment by juj** [comment]
Regarding unit tests - the SIMD code added to Urho3D is generally taken from my MathGeoLib project (http://clb.demon.fi/MathGeoLib/nightly/), and all the SIMD constructs are unit tested there (http://clb.demon.fi:8113/waterfall). It looks like the reason why this particular compiler regression was not caught is that  the combination of targeting SSE1 with VS2015 specifically does not exist there, but VS2015 targets SSE4.1 and AVX, and an older compiler is used to test older SSE targets.
