### ISSUE TITLE
Not able to run tests on AppVeyor

### ISSUE THREAD

**Issue by weitjong** [urho3d/Urho3D#1055]
This is a follow up from #1047.

Cause: Although AppVeyor VM image has been setup with a "display" on session 1 but that display is not "attached to desktop", so SDL library terminates the app with this error log entry ```No displays available``` in a dialog box causing CTest to wait indefinitely.

When using RDP to remotely login into the VM while it is running, the login session (session 1) would get a desktop and consequently causing the display on session 1 to attach to desktop as well. So, when CTest is invoked later, all the tests could complete successfully. However, we could not run the tests in this way as there is no easy way to automatic another process to perform the remote login via RDP.

**Comment by weitjong** [comment]
Probably need help from Windows users. I have totally no idea how to fix this.

**Comment by ilya-murzinov** [comment]
+1
Any ideas?

**Comment by weitjong** [comment]
The maintainer of AppVeyor has provided a PowerShell script which would automatically initiate an RDP session into the worker VM itself. This is a workaround rather than a proper solution, it works nevertheless. Basically just add this line into the AppVeyor yml file.
```
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-desktop.ps1'))
```

**Comment by ilya-murzinov** [comment]
Hacky workaround, but works! :)
