### ISSUE TITLE
SpriteSheet2D alpha channel issue

### ISSUE THREAD

**Issue by cosmy1** [urho3d/Urho3D#1062]
Hello,

I noticed when using a sprite near an alpha one and you try to tile it, you get a space between.
![tiling](https://cloud.githubusercontent.com/assets/1329119/11449733/3b8a35a2-9581-11e5-8229-580bd81d00e8.jpg)

And instead, using one with no alpha sprites around it, works more or less but there is still a small background artifact.
![tiling2](https://cloud.githubusercontent.com/assets/1329119/11449737/717987da-9581-11e5-9d0d-fb4f0cac1cd3.jpg)

If using a single sprite works correctly. (Sprite2D)
![tiling3](https://cloud.githubusercontent.com/assets/1329119/11449743/bf092df2-9581-11e5-8ef2-6d0a7b14222e.jpg)

Noticed that in TmxFile2D too.

Here are testing sprites
https://www.dropbox.com/s/iy3xqbixhga9xu7/testing.zip?dl=0

Code
```cpp
Node@ spriteNode = scene_.CreateChild("StaticSprite2D");
spriteNode.position = Vector3(i * 32.0f * PIXEL_SIZE, 0.0f, 0.0f);
StaticSprite2D@ staticSprite = spriteNode.CreateComponent("StaticSprite2D");
staticSprite.sprite = sprite.GetSprite("box0");
```

**Comment by cosmy1** [comment]
This looks like a GFX card issue... Someone else have this?
I tried it under Win10 with OpenGL.

**Comment by MonkeyFirst** [comment]
maybe you need use this for textures
```
<texture>
    <address coord="u|v|w" mode="wrap|mirror|clamp|border" />
    <border color="r g b a" />
    <filter mode="nearest|bilinear|trilinear|anisotropic|default" />
    <mipmap enable="false|true" />
    <quality low="x" medium="y" high="z" />
    <srgb enable="false|true" />
</texture>

```
i mean what you need to try - set address coord as "clamp" or "border"

**Comment by cosmy1** [comment]
Sorry for the late response, I'm closing this as I solved it.
I don't remember what I did exactly but the texture definition XML was already correctly set.
