### ISSUE TITLE
crash after calling engine.Exit() if BackgroundLoader is loading resources

### ISSUE THREAD

**Issue by 299299** [urho3d/Urho3D#1063]
how to reproduce:

  1. modify the example script 38_SceneAndUILoad.as, change scene LoadXML to LoadAsyncXML
  2. when the example windows shows up, quickly press ESC key.
  
  BTW: since the example scene "SceneLoadExample.xml" is not too resource heavy, you have to modify it a bit.

**Comment by cadaver** [comment]
Will probably need to add even more resources, since initially I didn't manage to reproduce. However, on what platform and compiler do you experience this?

**Comment by cadaver** [comment]
Nice! Now managed to reproduce in a debug build. I added some builtin resources and models and put the following line to autoexit the engine once the resource loader has been stressed enough:

    if (cache.numBackgroundLoadResources > 10)
        engine.Exit();

**Comment by 299299** [comment]
glad you can find it!
 my urho3dplayer is 32 bit build with vs2008, did not modify any source code, just the head version in master branch.
