### ISSUE TITLE
Built-in 2d objects

### ISSUE THREAD

**Issue by xotonic** [urho3d/Urho3D#1069]
I am missing for creating some primitive 2d figures in editor and programmically. Such as ellipse, rectangle, line etc.
Are you planning to add this feature?

**Comment by ToxikCoder** [comment]
That would be nice thing to add. Miss that feature too

**Comment by cadaver** [comment]
New 2D-like prefab models are certainly possible. Then there is the DebugRenderer component which allows to draw debug information such as lines, bounding boxes etc.

However, programmatic high quality geometric primitives that require the generation of vertices (such as defining an ellipse in code with n vertices, and it would fill the vertex buffer for you) are not planned into the engine itself, you can generate these yourself if you want.
