### ISSUE TITLE
Can't get DropDownList::SetPlaceholderText() function working

### ISSUE THREAD

**Issue by OldSnake22** [urho3d/Urho3D#1071]
Hello, i can't get DropDownList::SetPlaceholderText() function working. When i call it it seem to have no effect.

Maybe im using it in the wrong way... :)

**Comment by cadaver** [comment]
There was an unnoticed bug which would not hide the placeholder text, so it has to be a very little used feature. :)

The key points are to have a valid style configured on the text, and to set the list selection to none (-1). The following AS snippet demonstrates this:

´´´
    ui.root.defaultStyle = cache.GetResource("XMLFile", "UI/DefaultStyle.xml");
    DropDownList@ ddl = ui.root.CreateChild("DropDownList");
    ddl.size = IntVector2(200,25);
    ddl.position = IntVector2(100,100);
    ddl.SetStyleAuto();
    ddl.placeholderText = "PLACEHOLDER";

    for (int i = 0; i < 3 ; ++i)
    {
        Text@ item = ui.root.CreateChild("Text");
        item.text = "Item" + i;
        item.SetFont(cache.GetResource("Font", "Fonts/Anonymous Pro.ttf"), 15);
        item.hoverColor = Color(0.5,0.5,0,0.5);
        item.selectionColor = Color(1,1,0,0.75);
        ddl.AddItem(item);
    }
    
    // Show the placeholder text when no item selected
    ddl.selection = -1;

    input.mouseVisible = true;
´´´

**Comment by OldSnake22** [comment]
Thank you, everything is working and clear now !
