### ISSUE TITLE
Incorrect DDS cubemap loading

### ISSUE THREAD

**Issue by t-artikov** [urho3d/Urho3D#1072]
To reproduce:

Create a DDS cubemap from face images (I use [DirectXTex](https://github.com/Microsoft/DirectXTex) for that):
```
Urho3D_Data/Textures> texassemble.exe -cube -f R8G8B8A8_UNORM -o BrightDay1.dds BrightDay1_PosX.dds BrightDay1_NegX.dds BrightDay1_PosY.dds BrightDay1_NegY.dds BrightDay1_PosZ.dds BrightDay1_NegZ.dds
```
Urho3D_Data/Textures/Skybox.xml:
```
<cubemap>
    <image name="BrightDay1.dds" />
</cubemap>
```
Run a sample, which uses this cubemap (23_Water, for example).
The cubemap is displayed incorrectly.
![urho_cubemap](https://cloud.githubusercontent.com/assets/1927992/11612126/6a26d70c-9c17-11e5-93a4-80d4f8261c0e.png)

**Comment by MonkeyFirst** [comment]
did you trying use layouts? http://urho3d.github.io/documentation/HEAD/_materials.html
```
<cubemap>
    <image name="TextureName" layout="horizontal|horizontalnvidia|horizontalcross|verticalcross|blender" />
</cubemap>

```

**Comment by t-artikov** [comment]
I believe layouts are needed to split a 2D image into cubemap faces, which is not my case. Anyway, it does not change anything.

**Comment by MonkeyFirst** [comment]
I use only nvdxt.exe for joining textures into one cubemap, try to use it
