### ISSUE TITLE
Rendering artefacts when RenderPath = ForwardDepth

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1073]
(I tested only OpenGL build)

1) Start Editor
2) Editor settings
3) Render Path = RenderPaths/ForwardDepth.xml
4) Scene must be empty!
5) Some time move within the scene

![bug](https://cloud.githubusercontent.com/assets/13021826/11612515/03c1a1dc-9c16-11e5-8db8-0e0336c2dfb1.png)

**Comment by 1vanK** [comment]
ForwardHWDepth works normally

**Comment by cadaver** [comment]
This is the renderpath trying to be too clever and not clearing the depth for the proper scene pass. This isn't guaranteed to work on OpenGL, as the depth buffer can be different.
