### ISSUE TITLE
GetRigidbodies doesn't work on static objects

### ISSUE THREAD

**Issue by hjmediastudios** [urho3d/Urho3D#1075]
As the title says; calling `GetRigidBodies` either directly through the `PhysicsWorld` component or indirectly through `RigidBody::GetCollidingBodies` does not return static rigidbodies. I'm attempting to get the rigidbodies in contact with a given `RigidBody` component set to be a trigger, and it only returns dynamic rigidbodies, not the static ground collider that I'm trying to detect. I know it is not a problem with my collision layers, masks, etc. as calling `GetRigidBodies` on the `PhysicsWorld` component with a sphere or box query returns the expected appropriate results.

**Comment by hjmediastudios** [comment]
This can be resolved by checking the physics objects with an instantaneous check in the manner of the box and sphere queries; I've added a `PhysicsWorld::GetRigidBodiesInstantaneous` function in [this](https://github.com/urho3d/Urho3D/pull/1077#partial-pull-merging) pull request to address this.

**Comment by cadaver** [comment]
Adapted your PR to make PhysicsWorld::GetRigidBodies() do the instantaneous check, similar to other overloads. GetCollidingBodies() still works as before.

**Comment by hjmediastudios** [comment]
Good to go; thanks!
