### ISSUE TITLE
Lights does not working in DeferredHWDepth (DX11)

### ISSUE THREAD

**Issue by MonkeyFirst** [urho3d/Urho3D#1076]
![123](https://cloud.githubusercontent.com/assets/9577466/11626739/4aa5cc14-9d0f-11e5-9ff9-e497394b0f2c.png)

Yesterdays master DX11 renderer, std scene with cubes. Light's affects are not presented at all

**Comment by cadaver** [comment]
Good catch. May be a problem either with the light shader or with the setup of the readable depth stencil.
