### ISSUE TITLE
The uniforms PSP_NEARCLIP and PSP_FARCLIP not sended properly into constant buffer (DX11)

### ISSUE THREAD

**Issue by MonkeyFirst** [urho3d/Urho3D#1087]
I trying add SoftParticels into DX11 shaders. 
and until this time I do not figure out - why SP works fine on GL shaders and not do not worked with same code algorithm on DX11.
and today I found this problem:

this works fine -> float diffZ = (depth - particleDepth) * (1000 - 0.1); // 1000 = far  0.1 near from editor settings 
this not work -> float diffZ = (depth - particleDepth) * (cFarClipPS - cNearClipPS);

I guessing something broken in sending uniforms
~~~
void View::SetCameraShaderParameters(Camera* camera, bool setProjection)
{
....
    graphics_->SetShaderParameter(VSP_NEARCLIP, nearClip);
    graphics_->SetShaderParameter(VSP_FARCLIP, farClip);
    graphics_->SetShaderParameter(PSP_NEARCLIP, nearClip); //<-This
    graphics_->SetShaderParameter(PSP_FARCLIP, farClip); // < and this
~~~

**Comment by MonkeyFirst** [comment]
I think this need to be fixed
graphics_->SetShaderParameter(PSP_GBUFFERINVSIZE, Vector4(invSizeX, invSizeY, 0.0f, 0.0f));
to this
graphics_->SetShaderParameter(PSP_GBUFFERINVSIZE, Vector2(invSizeX, invSizeY));
because cbuffer struct have only float2 cGBufferInvSize and in case using vector4 we got and overridden cNearClipPS and cFarClipPS both with zeros  
```
cbuffer CameraPS : register(b1)
{
    float3 cCameraPosPS;
    float4 cDepthReconstruct;
    float2 cGBufferInvSize;
    float cNearClipPS;
    float cFarClipPS;
}
```
also I check SP how it works fine with using cNearClipPS and cFarClipPS in pixel shader.

**Comment by cadaver** [comment]
Thanks for the find, this is no doubt legacy from D3D9 times, when all uniforms were strictly speaking Vector4's.
