### ISSUE TITLE
Reordering UIElements in editor

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1088]
I have created a window in the editor and I needed to change the order of items, when layout is enabled. I looked into the source code and I found two places where it is forbidden to deliberately.

In engine:
```
void UIElement::SortChildren()
{
    if (sortChildren_ && sortOrderDirty_)
    {
        // Only sort when there is no layout
        /// \todo Order is not stable when children have same priorities
        if (layoutMode_ == LM_FREE)
            Sort(children_.Begin(), children_.End(), CompareUIElements);
        sortOrderDirty_ = false;
    }
}
```

In editor:
```
        // Do not allow UI subsystem to reorder children while editing the element in the editor
        element.sortChildren = false;
```

I would like to remove these restrictions, but I'm afraid disrupt engine. What is their purpose?

**Comment by weitjong** [comment]
It has been a while but if I recall correctly the reason for this line in the editor was/is the same as the "todo" remark entered by Lasse just recently. When sorting is enabled while editing the UI elements in Editor, the order of elements may change from one way to the other after a save/load operations.

**Comment by 1vanK** [comment]
>> the order of elements may change from one way to the other after a save/load operations
It will not be because I'm using layout

**Comment by 1vanK** [comment]
It is not simple way :)
I just need insert a button in the middle 
1) set priority for all elements
2) disable layout
3) save UI
4) close UI
5) open UI
6) enable layout

**Comment by weitjong** [comment]
Yes, the UI Editor still has a lot of shortcomings. It is much easier to save temporarily, reorder the layout file manually, and then reload it back :smiley:

**Comment by 1vanK** [comment]
I found another method :)
1. Create temp ui element
2. Drag all of the elements in it as a children
3. Drag all elements back with the correct order
