### ISSUE TITLE
Models disappear when using game recording software

### ISSUE THREAD

**Issue by Enhex** [urho3d/Urho3D#1089]
I'm using Urho with OpenGL.
When turning on recording software that seems to use ogl/d3d API directly to minimize performing impact, models seems to disappear (UI, skybox and particle effects still visible).
This problem doesn't happen when using -gl2 command.

Example for software that causes this problem:
MSI Afterburner (rivatuner on-screen-display overlay)
LoiLo Game Recorder
Google Hangout (only with Windows 10?)

Example when using MSI Afterburner:
http://i.imgur.com/J2BPRBn.jpg
with gl2:
http://i.imgur.com/9QWevP5.jpg

(didn't test if it happens with Direct3D build)

**Comment by cadaver** [comment]
Urho will naturally make no concessions for another program modifying the GL state behind its back and not restoring it properly, so this sounds like a problem with the recording program. I wouldn't be surprised if its OpenGL2 path is more robust, since there's less moving parts to take care of (e.g. no VAO)

**Comment by cadaver** [comment]
I'm able to reproduce this with MSI Afterburner. Seems depth test or culling related. If this is something trivial like depth test state being different than expected in the beginning of frame, then a concession can be made.

**Comment by Enhex** [comment]
It happens again. Maybe it's related to some change that was done since it was first fixed?

Also I forgot to mention that it's quite critical, because if a user has such program open and he tries to play Urho app that uses OGL3 the app will be unusable. Also critical if someone tries to record the game. That means that OGL3 isn't an option for production software, only GL2 (and maybe D3D).
