### ISSUE TITLE
D3D functions should use HRESULT to determine success

### ISSUE THREAD

**Issue by bvanevery** [urho3d/Urho3D#1092]
Urho Sample Platformer has recently been trying to add D3D support.  https://github.com/gawag/Urho-Sample-Platformer/issues/15  Previously it only had OpenGL support.  Currently USP gets numerous log errors in D3D11Texture2D.cpp, with the following LOGERROR:
```
        // Create also a read-only version of the view for simultaneous depth testing and sampling in shader
        depthStencilViewDesc.Flags = D3D11_DSV_READ_ONLY_DEPTH;
        graphics_->GetImpl()->GetDevice()->CreateDepthStencilView((ID3D11Resource*)object_, &depthStencilViewDesc,
            (ID3D11DepthStencilView**)&renderSurface_->readOnlyView_);

        if (!renderSurface_->readOnlyView_)
        {
            URHO3D_LOGERROR("Failed to create read-only depth-stencil view for texture");
            return false;
        }
```
CreateDepthStencilView, like most D3D functions, returns a HRESULT with some info on the nature of the failure.  It would be good to have this info incorporated into all the LOGERRORs.  Failing that, it would be good to have the function store the HRESULT in a variable, so it can be easily inspected with a debugger.  When someone is writing new code downstream of Urho3D, they have no idea if they did something wrong in their own code, or if something is broken in Urho3D itself.  Getting as much debug info as easily and readily available as possible, without having to manually edit the sources, helps diagnosis.

It might even make sense to create a type specific URHO3D_D3D_LOGERROR(hresult, "string") so as to uniformly enforce the convention and its implementation.

I have verified that with the code as written, Visual Studio 2015 will not show the return value of CreateDepthStencilView in the debugger.  It shows all sorts of other intermediate return values, but the common denominator of those is, someone wants them for something else.

**Comment by cadaver** [comment]
This could be added, but the typical HRESULT that will be returned is "invalid arguments" since the others have to do with resource exhaustion, which is less typical.

In this case (depth-stencil view) Urho should do checking beforehand that the user is not passing illegal combination of parameters, for example creating a color format texture to use as depth stencil.

**Comment by cadaver** [comment]
I couldn't reproduce this issue in a D3D11 build of the sample platformer. Which GPU are you running on?

**Comment by bvanevery** [comment]
Please let's not complicate this issue with the read-only depth stencil stuff.  The USP behavior was present when I pulled Urho3D 2 days ago.  1 day ago, I pulled Urho3D and then USP errors went away.  I see you've got a potentially relevant commit even since then.  https://github.com/gawag/UrhoSampleProject was able to demonstrate read-only depth stencil errors this morning, where USP did not.  When I pull again I bet it changes again, so let's not try to keep up with that.  This is not a bug about read-only depth stencil stuff.  I would file a bug about that if I could just figure out what's really going on there.

The issue is that anyone on DirectX faced with a "head scratcher" needs to be able to debug what's going on.  At a minimum, "HRESULT hr=" is needed.  Maybe it'll say "invalid arguments" most of the time, but that's important to know.  Whether it's a small mistake or a more strange one.

**Comment by bvanevery** [comment]
Just realized that testing the side effect of a D3D function to determine its success or failure is wrong.  Yes, if you get back a null, it's a fail.  But if you get back non-null, that doesn't mean you succeeded!  I guarantee you there's some driver out there "in the wild" whose behavior is undefined in that circumstance.  D3D functions should all be reading the HRESULT and making sure it's S_OK.

**Comment by cadaver** [comment]
Yes, the proper way would be to release the object (if it was created in some zombie state) if the HRESULT indicates failure. This will be a rather mechanical change. In practice I suspect the D3D runtime shields the user from these cases (and will not actually return an object) even if the driver did something strange, but it's good to be sure.

**Comment by bvanevery** [comment]
Microsoft doesn't have any better a track record for not producing catastrophic bugs than any driver writer in industry.  So I wouldn't count on them.
