### ISSUE TITLE
The function Start() is irreversibly changing a scene each time you press Play in the Editor

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1095]
0) Open the editor
1) Create Node
2) Add ScriptInstance

```
class Bug : ScriptObject
{
    void Start()
    {    
            Node@ boxNode = node.scene.CreateChild("MyBox");
    }
}
```

Node MyBox will be created immediately
3) Run play
4) Run Stop
It will create a second instance of MyBox 

I think the problem here:

```
void ScriptInstance::CreateObject()
{
...
if (methods_[METHOD_START])
            scriptFile_->Execute(scriptObject_, methods_[METHOD_START]);
}
```

but I did not come up with a simple way, to work around this. Maybe just add to the documentation information,  that the modification of the scene should be done only in the function DelayedStart

**Comment by 1vanK** [comment]
Maybe create a flag "initialized" and check it before calling METHOD_START

**Comment by cadaver** [comment]
Urho is not Unity; in this case we must remember that the editor is just a script application that manipulates a scene through attributes. The play button does not trigger additional logic (a real Start signal that would be recognized by the engine) but just starts running scene updates.

We must be wary of adding additional logic that may misbehave in other cases.

However you should be able to work around this particular case by putting any child node creation in DelayedStart() function instead, and ensuring you have the "Revert on pause" button (third from left) enabled.
