### ISSUE TITLE
color bleeding in texture

### ISSUE THREAD

**Issue by yushli** [urho3d/Urho3D#1096]
If I use the following image as a static sprite 2d, seems like there is color bleeding in the edge. Please see the attached screeshot:
the image:
![earth](https://cloud.githubusercontent.com/assets/1681453/11843551/29a388de-a445-11e5-8445-61246290ee6c.png)

The screen shot:
![Uploading Screenshot_2015-12-16-22-27-49.png…]()

**Comment by yushli** [comment]
![screenshot_2015-12-16-22-27-49](https://cloud.githubusercontent.com/assets/1681453/11843660/b6241710-a445-11e5-86ab-0bbc303115f3.png)

**Comment by OldSnake22** [comment]
I think that Sprite (UI Sprite) class may suffer from the same issue. I have this bleeding issue with UI sprites.
