### ISSUE TITLE
object becomes completely black at a slightly moved angle

### ISSUE THREAD

**Issue by yushli** [urho3d/Urho3D#1097]
In a scene with a terrain, if the camera moves slightly, the terrain becomes completely black. If move the camera a little bit, the original texture shows up. Not sure what parameters to look at. There is a directional light at direction(0,-1,0) so at least there should be some light there.

![screenshot from 2015-12-17 22 01 58](https://cloud.githubusercontent.com/assets/1681453/11871581/8274777c-a50b-11e5-9f9b-b39940cff30d.png)
![screenshot from 2015-12-17 22 02 56](https://cloud.githubusercontent.com/assets/1681453/11871587/87ac2b2c-a50b-11e5-8ccc-1881020fa515.png)

**Comment by cadaver** [comment]
Is this a Terrain component, or a StaticModel?
Are you using a normalmapped material? Does it work with a diffuse only material?

**Comment by yushli** [comment]
Thanks for the quick response! 
It is a static model. And if I use the -t in AssetImporter to generate tangent, looks like the problem is gone. :) 
A lot to learn about in Urho3D...
