### ISSUE TITLE
Linking CXX executable error

### ISSUE THREAD

**Issue by LL2** [urho3d/Urho3D#1101]
Hi all.

I think i'm getting problems linking but I have no idea how to solve it.

I'm using cmake to generate the Code::Blocks project file, but when I try to compile from Code::Blocks, I get these errors:
>recipe for target 'bin/test2' failed
recipe for target 'CMakeFiles/test2.dir/all' failed
recipe for target 'all' failed

If I try to compile from the terminal('make' command):
>Linking CXX executable bin/test2
`.text._ZN6Urho3D12MemoryBufferD2Ev' referenced in section `.text._ZN6Urho3D12MemoryBufferD1Ev[_ZN6Urho3D12MemoryBufferD1Ev]' de /usr/local/lib/Urho3D/libUrho3D.a(Node.cpp.o): defined in discarded section `.text._ZN6Urho3D12MemoryBufferD2Ev[_ZN6Urho3D12MemoryBufferD5Ev]' de /usr/local/lib/Urho3D/libUrho3D.a(Node.cpp.o)
collect2: error: ld returned 1 exit status
CMakeFiles/test2.dir/build.make:136: recipe for target 'bin/test2' failed
make[2]: *** [bin/test2] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/test2.dir/all' failed
make[1]: *** [CMakeFiles/test2.dir/all] Error 2
Makefile:75: recipe for target 'all' failed
make: *** [all] Error 2

I tried reinstalling Urho but the problem persist.

Ubuntu MATE 15.10 (x86_64)
Installed from Urho3D-1.5-Linux-64bit-STATIC.deb

**Comment by weitjong** [comment]
The purpose of our build artifacts are to let our new users to try out the demo samples app quickly. The library itself though may or may not work as it is in user's host systems. Most Linux builds are generated using GCC 4.6, with the exception of 64bit STATIC lib which uses GCC 4.9. Your 15.10 uses GCC 5. Now i am not sure that is your problem but I suggest you rebuild the library from source using GCC 5 and then install it using ```make install``` as per usual.

**Comment by LL2** [comment]
works like a charm

thanks @weitjong

**Comment by henriquelalves** [comment]
Hey, newbie question (and kind of resurrecting a thread), but how do rebuild from source using GCC 5? I thought this would be simply a matter of changing on cmake which GCC to use, but the same problem persists.
