### ISSUE TITLE
DefaultStyle for UIElements not connected to uiRoot

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1103]
```
Button* Game::CreateLevelButton(String str)
{
    auto button = new Button(context_);
    button->SetStyleAuto();
    button->SetName(str);
    button->SetMinSize(100, 100);

    auto text = button->CreateChild<Text>();
    text->SetStyleAuto();
    text->SetText(str);
    text->SetAlignment(HA_CENTER, VA_CENTER);

    return button;
}

GetSubsystem<UI>()->GetRoot()->AddChild(CreateLevelButton("1"));
```
![2](https://cloud.githubusercontent.com/assets/13021826/11913149/6a5335d4-a673-11e5-8014-9fbde2057af8.png)

```
Button* Game::CreateLevelButton(String str)
{
    auto button = new Button(context_);

    // ADDED
    auto cache = GetSubsystem<ResourceCache>();
    auto xmlFile = cache->GetResource<XMLFile>("UI/DefaultStyle.xml");
    button->SetDefaultStyle(xmlFile);
    // END
        
    button->SetStyleAuto();
    button->SetName(str);
    button->SetMinSize(100, 100);

    auto text = button->CreateChild<Text>();
    text->SetStyleAuto();
    text->SetText(str);
    text->SetAlignment(HA_CENTER, VA_CENTER);

    return button;
}

GetSubsystem<UI>()->GetRoot()->AddChild(CreateLevelButton("1"));
```

![1](https://cloud.githubusercontent.com/assets/13021826/11913178/b6927bc0-a674-11e5-887c-4657cfc771c9.png)

Maybe a better way is using of internal flag
```
bool useDefaultStyle_
```
and update style for entire hierarchy of child elements after connection it?

**Comment by cadaver** [comment]
You could have the style applied automatically on connecting to hierarchy if you have specified its name by yourself, e.g. SetStyle("Button"); I will check if changing SetStyleAuto() to do the same has destructive side-effects (UI element editor has to be checked also)

Another way is to use uiElement->CreateChild<Type>(), that way the parent chain style is connected from the start. In this case you could supply the parent as a function parameter.

**Comment by cadaver** [comment]
The problem is that currently applying the style happens only for 1 level of hierarchy. I'll see if it can be made to go all the way.
