### ISSUE TITLE
pressedOffset and oldUI

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1106]
I'm planning to add a disabled state for the button.

At the same time I would change two things.

1) Currently, pressedOffset calculated relative hoverOffset, but not base ImageRect. It is very confused for me. Are there reasons that made it so?

2)  As I understand it, OldUI is not compatible with today's feature set. Should we keep it?

**Comment by cadaver** [comment]
It treats pressed and hovered as separate states, so the offsets can "add up" to provide 4 different images already. However I agree that it's confusing and un-hovered and pressed isn't really possible. I don't have strong opposition to changing it, of course any custom layouts people have made could become incompatible.

Old UI style is OK to remove.

**Comment by 1vanK** [comment]
We often do break the compatibility changes :)

If we maintain the current method of offset, relative to what is necessary to calculate the offset for disabled state?

**Comment by cadaver** [comment]
Yes, I wouldn't treat the breaking of compatibility as a serious thing. Could well just have normal, pressed, hovered and disabled.

Disabled can't really be hovered or pressed, no? Therefore it could be calculated relative to the base image.

**Comment by 1vanK** [comment]
> Disabled can't really be hovered or pressed, no?

Yes, just gray inactive element

**Comment by 1vanK** [comment]
I think I found the reason. ChekedBox can be checked hovered, checked unhovered, unchecked hovered, unchecked unhovered. For uniformity of approach the same is done for the buttons.

**Comment by 1vanK** [comment]
Also button can be toggled (pressed without hover)
