### ISSUE TITLE
Optional index vertex attribute

### ISSUE THREAD

**Issue by sabotage3d** [urho3d/Urho3D#1108]
Is it possible to request an optional integer index vertex attribute. Currently I am using UV2 first component and casting it to integer inside the shader. I am working on a custom mobile batching that needs indexing vertex attribute.  That would make it more mainstream.

**Comment by cadaver** [comment]
Sure, until we get proper freeform vertex attributes. Should it be just a 32bit integer?

**Comment by sabotage3d** [comment]
I think the lower the storage the better, it could be unsigned 16bit integer. I don't think the GLSL arrays size could be anything bigger.

**Comment by cadaver** [comment]
OK, I'll test if it can be made that way on both D3D & OpenGL. I'm not going to add things that would only be possible on one API so in case it fails, you'll have to just make an engine customization.

**Comment by sabotage3d** [comment]
It makes sense. Thanks a lot for looking into it.

**Comment by cadaver** [comment]
It seems that D3D9 is a no-go, but that shouldn't prevent it working on GL & D3D11.

**Comment by cadaver** [comment]
Note: this may be unlikely to work on GLES2 mobiles since the 8 vertex attribute limit is already exhausted. I'll add it nevertheless, but it may be that in practice you need to abuse some existing attribute, for example blend indices (these are 8-bit, so need a bit of reconstruction math in the VS)

**Comment by cadaver** [comment]
Made it a 32bit integer in the end for most compatibility, and to not break the 32bit alignment of other vertex elements. In GLSL it needed to be declared as a float attribute to work properly (?), but you can cast to int in the shader code if necessary.

**Comment by sabotage3d** [comment]
Thanks a lot :+1:
