### ISSUE TITLE
time step smoothing improvement

### ISSUE THREAD

**Issue by yushli** [urho3d/Urho3D#1109]
Engine.cpp uses the following code to do the time step smoothing:
 lastTimeSteps_.Push(elapsed / 1000000.0f);
    if (lastTimeSteps_.Size() > timeStepSmoothing_)
    {
        // If the smoothing configuration was changed, ensure correct amount of samples
        lastTimeSteps_.Erase(0, lastTimeSteps_.Size() - timeStepSmoothing_);
...
if timeStepSmoothing_ is bigger than 2, say 20, then everytime it will cause lastTimeSteps_.Erase() to execute , which in turn need to memmove 20 floats.  In stead of moving these floats ,we can use the PODVector as a circular buffer,  and use a formula to calculate the current time step:
timeStep_ = (timeStep_ * timeStepSmoothing_ - lastTimeSteps_[currentIdx] + elapsed / 1000000.0L)
lastTimeSteps_[(++currentIdx)%timeStepSmoothing_] = elapsed/100000.0L;
Do you think this change is desirable?

**Comment by cadaver** [comment]
Moving 20 floats per frame is completely minuscule on any platform that can run Urho properly, so in this case I wouldn't change the code to more complex.
