### ISSUE TITLE
AssetImporter cannot import DAE file with skeleton animation

### ISSUE THREAD

**Issue by yushli** [urho3d/Urho3D#1118]
I use AssetImporter to import a DAE scene with character that contains skeleton animation as a node. The character cannot show up in the engine. I open the node.xml and change the component type to StaticModel then the character shows up. Is this a know issue or Am I missing something? Is the animation information already embedded in the node.xml or the mdl?
If I use AssetImporter to import the single character with skeleton animation as model, then both the character.mdl and character.ani are created and loaded successfully in the engine. 
And what is the recommended way to import the scene and the animated character into Urho3D? 
The DAE file is a little big. I can attach it if needed.

**Comment by yushli** [comment]
The problem can be narrowed down to the following two models. One is generated by AssetImporter when importing DAE file with the animated character. One is the model generated by importing the fbx of a single character and saved as a model. These two models both load successfully in the engine. But one is shown and the other is not. 
[Models.zip](https://github.com/urho3d/Urho3D/files/72164/Models.zip)

The following is the animation file generated when importing the model. 

[Object01_Take 001_show.ani.zip](https://github.com/urho3d/Urho3D/files/72165/Object01_Take.001_show.ani.zip)

**Comment by cadaver** [comment]
Right now it's recommended to import animating models using the Model option of AssetImporter, and the Scene mode only for static objects or whole (static) scenes. It can potentially be a trivial problem to fix, though.

Please attach the DAE file for troubleshooting, the converted models tell little.

**Comment by yushli** [comment]
[youguge.dae.zip](https://github.com/urho3d/Urho3D/files/72421/youguge.dae.zip)

**Comment by yushli** [comment]
Thank you for looking into this issue!

**Comment by yushli** [comment]
Also attach the texture images if needed.
[Textures.zip](https://github.com/urho3d/Urho3D/files/72423/Textures.zip)

**Comment by cadaver** [comment]
There's something odd with the DAE file provided. The model & its bones are concentrated on so small area of space that it doesn't show anything. I also tried viewing it with Assimp's open3mod viewer, which also didn't show anything.

Presently I don't have an idea what AssetImporter should do to it to fix it.

**Comment by kimkulling** [comment]
You can try to open an issue report on Asset Importer Lib. Hopefully we can give it a try to help you guys here!

**Comment by yushli** [comment]
The odd thing is that the output node xml file contains an AnimatedModel component. If I change the AnimatedModel type to StaticModel, then the model shows up. They are using the same mdl file. So the possible issue is that the mdl file contains the wrong animation information thus makes the static model disappear.

**Comment by kimkulling** [comment]
Thanks for the issue!

**Comment by yushli** [comment]
Thank you all for looking into that! Hope to find a solution soon.

**Comment by yushli** [comment]
Just as stated before, the model generated by importing dae can be successfully shown if set the type to StaticModel. So there should be errors inside the skeleton part. I wrote a small util to dump the mdl as plain text. It shows that the offsetMatrix of each bone is pretty big ,like 
{
            "name": "Bip01_x0020_Spine",
            "parentIndex": 3,
            "initialPosition": [0.14604699611663818, 0.0053820000030100346, -0.000018000000636675395],
            "initialRotation": [0.9979892373085022, 0.06218252331018448, 0.011717814020812511, -0.0036811514291912317],
            "initialScale": [0.9999997019767761, 1.0000004768371582, 0.9999998807907104],
            "offsetMatrix": [58196376, 58196376, -58196376, 58196376, 76122608, 76122608, -76122608, 76122608, 73262576, 73262576, -73262576, 73262576],
            "collisionMask": 3,
            "collision_sphere_radius": 410201216,
            "collision_box": [0, 0, 0, 197914752, 258878448, 249152032]
        }

Is it possible that some overflow/underflow happens when calculating the offsetMatrix?

[Models_plainText.zip](https://github.com/urho3d/Urho3D/files/73092/Models_plainText.zip)

**Comment by cadaver** [comment]
Yes, I'd suspect that because the raw mesh geometry is OK, it renders OK as a StaticModel, but an AnimatedModel always tries to apply skinning via its bones, and in this case either the bones' offset matrices (inverse bind pose) or bone transforms have some funny data.

**Comment by kimkulling** [comment]
I tried to look onto the dae-model with blender and even blender is not able to visualize anything useful. Are you sure that the model is not broken?

**Comment by 1vanK** [comment]
May be blender currently is broken? (https://developer.blender.org/T47018) Try old version of blender

**Comment by yushli** [comment]
The exported static model from this dae-file can be successfully shown in urho3D, though need to scale to (0.01,0.01, 0.01).

**Comment by Kiraffi** [comment]
I tried to open this dae-file on blender 2.76 and 2.69. It didn't even show the model on them. I happen to have some older versions on my computer, so I tried it on 2.63, which is 3 years old version, and on that one I was able to open the model. I suggest that you either update your dae exporter skript to new one, or update the blender if you are using old version of blender.

**Comment by kimkulling** [comment]
I do agree. It would be useful to be able to view the model with the latest version of blender. Then we can try to load it with Asset-Importer-Lib as well.
