### ISSUE TITLE
require from .lua file on android platform

### ISSUE THREAD

**Issue by genehsun** [urho3d/Urho3D#1130]
how can i require a lua file on android platform?

**Comment by weitjong** [comment]
Just use "require" function followed by a relative path to the Lua file resource that you want to include as you normally would for other platforms. There is no difference for Android platform. Our LuaScript subsystem has registered a custom "package.loaders" which in turn would call our internal loader implementation which uses our "ResourceCache" subsystem. The latter knows how to acquire file resources from any of the target platforms supported by Urho3D, including Android.
