### ISSUE TITLE
Runtime error in 19_VehicleDemo with macosx

### ISSUE THREAD

**Issue by l19g2004** [urho3d/Urho3D#1132]
I get an error while running the vehicle demo under Mac OSX Yosemite and Xcode 6.4. Probably caused by the bullet lib in linearmath\btVector3.h:300. ... !fuzzyZero() ...
I solved it with the newest sources from the official bullet repo -> https://github.com/bulletphysics/bullet3

**Comment by cadaver** [comment]
Reproduced.
