### ISSUE TITLE
Bullet Physics issues

### ISSUE THREAD

**Issue by hjmediastudios** [urho3d/Urho3D#1134]
After updating Urho3D to the latest version from trunk, a whole slew of Bullet physics-related issues have emerged without changing my own code, including:

- Can no longer apply forces to RigidBody components
- Collisions aren't detected properly using `GetRigidBodies`

Most tellingly, this is clearly a problem with the Bullet libraries or their integration, not just the Urho3D code that wraps them. One of my classes relies on a custom collision-detection setup, and even creating raw btCollisionShapes for that fails. Creating a `btBoxShape` using the following code: 

```
            btCylinderShape* cyl = new btCylinderShape(ToBtVector3(size_ * 0.5f));
            URHO3D_LOGERROR("Cylinder: " + String(size_ * 0.5f) + " -> " + String(ToVector3(cyl->getHalfExtentsWithoutMargin())) + " / " + String(ToVector3(cyl->getHalfExtentsWithMargin())));
            cyl->setLocalScaling(ToBtVector3(newWorldScale));
```

The `size_` variable is correct, but the returned half extents are both `-inf, 0, 0`. This was working perfectly until my latest pull. This combined with other people noting Bullet-related issues recently leads me to believe there's a big bug(s) that just popped up with Urho3D's use of Bullet.

**Comment by hjmediastudios** [comment]
Further info: Reverting back to commit `f4edf3f` for Urho3D but changing *nothing* about my own code immediately fixes the problem; whatever changed in the library to cause these issues happened after this commit.

**Comment by cadaver** [comment]
Is this related to the build options autodiscovery? Maybe wrong state of URHO3D_SSE?

**Comment by weitjong** [comment]
That's easy to verify. Open up either the generated ```Urho3D.h``` file or the ```CMakeCache.txt``` file in the build tree. In the file you should see URHO3D_SSE set or not set.

**Comment by weitjong** [comment]
Note that after the auto-discovery feature, there is no way for user to override and contradict, i.e. when the lib is built with SSE enabled then downstream will always get SSE enabled also even when user naively reset the flag via command line parameter or via cmake-gui.

**Comment by hjmediastudios** [comment]
When it's working, I see URHO3D_SSE is set. This seems to be the same when it's not working.

**Comment by cadaver** [comment]
If not SSE flag, then this seems like some other ABI incompatibility issue. What compiler and build type are you using?

**Comment by hjmediastudios** [comment]
GCC, static library build- issue is present with debug, release, and release with debug info builds. If it helps, I'm running Ubuntu 15.10 64-bit.

**Comment by cadaver** [comment]
Possibly fixed by disabling Bullet aligned structs in the user-visible API. Please reopen if still persists.
