### ISSUE TITLE
In AnimatedModel, bone nodes are saved 

### ISSUE THREAD

**Issue by darwikey** [urho3d/Urho3D#1135]
Hello,
I created an AnimatedModel, I disabled the save for this component, and I assigned a skeleton :
`AnimatedModel* model = node_->CreateComponent<AnimatedModel>();`
`model->SetTemporary(true);`
`model->SetModel(...);`

But when the scene is saved, the bone nodes are saved too. It's quite annoying because it spams the save file with useless nodes.

I don't know if it's a bug, but a solution to solve this can be to add:
`boneNode->SetTemporary(true);`
 after the line 738 in AnimatedModel.cpp :

**Comment by cadaver** [comment]
We cannot make that exact change generally, as the usual case is that we do want to persist the bones in the exact positions, when the scene is saved. 

However we could make the model copy its own temp status to the bones.

Another solution is to make the whole node temporary, not just the component. In that case the save never recurses to the components and the bone children.
