### ISSUE TITLE
undefined references to Variant::Get<type> (shared linking)

### ISSUE THREAD

**Issue by carnalis** [urho3d/Urho3D#1138]
```In function `Urho3D::AttributeAccessorImpl<TailGenerator, bool, Urho3D::AttributeTrait<bool> >::Set(Urho3D::Serializable*, Urho3D::Variant const&)':
urho/build/include/urho3d/scene/serializable.h:258: undefined reference to `bool Urho3D::Variant::Get<bool>() const'```

These are occuring for bool, float, unsigned int, Color, ResourceRef..
It's possible I've missed something... advice welcome, and thanks.

**Comment by cadaver** [comment]
Reproduced. Likely missing export define.
