### ISSUE TITLE
Cannot create a new project for MSVC using CMake WITH STATIC RUNTIME (another problem)

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1140]
Cmake 3.3 + debug + static lib + static rutime

When compiling CheckUrho3DLibrary.cpp it used default dynamic runtime
```
CMAKE_CXX_FLAGS_DEBUG /MDd
```
When Urho compiled with static runtime we hawe error when link this test program

```
 ClCompile:


    D:\Programs\Microsoft Visual Studio 14.0\VC\bin\CL.exe /c /Id:\MyGames\Urho3D\Build\include /Zi /W3 /WX- /Od /Ob0 /Oy- /D WIN32 /D _WINDOWS /D _DEBUG /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_7edff.dir\Debug\\" /Fd"cmTC_7edff.dir\Debug\vc140.pdb" /Gd /TP /analyze- /errorReport:queue d:\MyGames\MiniGame\Src\CMake\Modules\CheckUrho3DLibrary.cpp
```

```
Link:


    D:\Programs\Microsoft Visual Studio 14.0\VC\bin\link.exe /ERRORREPORT:QUEUE /OUT:"D:\MyGames\MiniGame\Build\CMakeFiles\CMakeTmp\Debug\cmTC_7edff.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib d:\MyGames\Urho3D\Build\lib\Urho3D_d.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /Debug /PDB:"D:/MyGames/MiniGame/Build/CMakeFiles/CMakeTmp/Debug/cmTC_7edff.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/MyGames/MiniGame/Build/CMakeFiles/CMakeTmp/Debug/cmTC_7edff.lib" /MACHINE:X86 /SAFESEH  /machine:X86 /debug cmTC_7edff.dir\Debug\CheckUrho3DLibrary.obj


  Urho3D_d.lib(LibraryInfo.obj) : error LNK2038: ���������� ��������������
  ��� "RuntimeLibrary": �������� "MTd_StaticDebug" �� ������������� ��������
  "MDd_DynamicDebug" � CheckUrho3DLibrary.obj
  [D:\MyGames\MiniGame\Build\CMakeFiles\CMakeTmp\cmTC_7edff.vcxproj]
```

**Comment by weitjong** [comment]
Before fixing this with yet another bake-in define in the export header, I want to double check with those who are familiar with VS. Can we take a shortcut by forcing this URHO3D_STATIC_RUNTIME to on when and only when URHO3D_LIB_TYPE=STATIC and VS generator is being used. In other words,  URHO3D_STATIC_RUNTIME is not an option at all. i.e. Can the corresponding compiler flags MT/MTd vs MD/MDd are decided based on the URHO3D_LIB_TYPE build option alone? Is there a use case STATIC lib type but built with dynamic runtime, or that static runtime is preferred alwasys?

**Comment by cadaver** [comment]
Dynamic vs static runtime should be the developer's choice; static Urho and dynamic runtime is a valid combination. Only dynamic Urho and static runtime is a bad idea, as objects can be allocated in different heaps and therefore crash if freed in wrong place.

**Comment by weitjong** [comment]
Ok, got it. No shortcut then. It means the URHO3D_STATIC_RUNTIME has to be somehow baked into the export header similar to URHO3D_STATIC_DEFINE. When the lib uses static runtime then the app **must** use static runtime too, and vice versa.

**Comment by cadaver** [comment]
Since dynamic runtime is the default and static requires the developer explicit action, I wouldn't consider it unreasonable that the developer must configure Urho and application similarly (both use static). But if this can be automated, of course it's nice.

**Comment by 1vanK** [comment]
I do not quite understand. If runtime lib is linked in urho lib, what for repeat to link same to the user application? I'm sorry if my question is stupid

**Comment by cadaver** [comment]
Every library or executable must link to some MS runtime for the standard functions like printf & fopen, and the types need to match when static libs are being linked to an executable, otherwise there'll be duplicate symbol etc. trouble.

**Comment by 1vanK** [comment]
If MS runatime is linked to Urho3d.lib and Urho3d.lib is linked to application, Is the application does not have access to this functions?

**Comment by weitjong** [comment]
Not sure for MSVC but for GCC there are differences between how STATIC and SHARED libs are being generated. STATIC is just an archive of object files from the compilation units produced by ar tool, it does not contains objects or symbols from other runtime libraries. SHARED on the other hand is produced by a linker tool which links all the required objects or symbols together including those from other runtime libraries. Thus, when the app try to use URHO3D STATIC lib then the build system still needs to be told where to get the other runtime symbols from. This is not required when try to use SHARED lib of course.

**Comment by weitjong** [comment]
In the end I did not bake this build option into our export header because it has no corresponding compiler define in the first place. Anyway, as 1vanK has shown, there is actually already a very reliable way to determine whether the library uses static or dynamic runtime. We just have to call try_run() twice in the worse case for MSVC to detect which is which and then use that information as necessary.
