### ISSUE TITLE
Cannot compile because of #include <codecvt>?

### ISSUE THREAD

**Issue by vivienneanthony** [urho3d/Urho3D#1141]
Hello

I had this issue before  with the previous version when trying to compile. I get this error. I am trying to compile ODBC support.

I've updated my computer and running Ubuntu 14.04 and using the source from Version 1.5.  If I remember right I had to remove or build nanodbc with older code, and make a different FindODBC.cmake, FindMySql  file to get it to work.

Does anyone have the same problem?

Vivienne

// gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

///$ g++ --version
g++ (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

///$ cmake --version
cmake version 2.8.12.2

///$ sudo apt-get install libstdc++-4.8-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libstdc++-4.8-dev is already the newest version.
The following packages were automatically installed and are no longer required:
  linux-headers-3.19.0-42 linux-headers-3.19.0-42-generic
  linux-image-3.19.0-42-generic linux-image-extra-3.19.0-42-generic
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by weitjong** [comment]
I am not absolutely if this is the root cause of your issue but according to the GCC documentation [here](https://gcc.gnu.org/projects/cxx0x.html), the GCC support for C++11 standard was experimental prior to version 5.1 and the nanodbc requires C++11 standard. I think you need a more recent GCC to compile this sub-library.
