### ISSUE TITLE
Negative Component ID's problem

### ISSUE THREAD

**Issue by vivienneanthony** [urho3d/Urho3D#1150]
Hello,

I was experiencing problems with saved XML'S have negative id's for components. After troubleshooting I made a minor editor to the SaveXML in component.cpp.. I'm not sure if it's a bug or issue but it was my fix.

If anything I can Fork Urho3D and make a pull request for the minor fix. (If it is) Just need to the steps to do so.

Vivienne

     bool Component::SaveXML(XMLElement& dest) const
      {
         // Write type and ID
          if (!dest.SetString("type", GetTypeName()))
           return false;
          if (!dest.SetInt("id", id_))
           return false;
   
       // Write attributes
       return Animatable::SaveXML(dest);
      }

Changed to

      bool Component::SaveXML(XMLElement& dest) const
      {
       // Write type and ID
          if (!dest.SetString("type", GetTypeName()))
              return false;
          if (!dest.SetUInt("id", id_))
              return false;
   
       // Write attributes
       return Animatable::SaveXML(dest);
      }

**Comment by cadaver** [comment]
Thanks. That should be more correct. No need to make PR specifically for this, I can apply and credit you.
