### ISSUE TITLE
Camera rotation issue in Urho3D samples.

### ISSUE THREAD

**Issue by itisscan** [urho3d/Urho3D#1151]
I found one problem in samples when window is minimized and then restored. So after window's minimizing camera start wrong behave. (Very fast rotate) 

I have captured this moment. 

https://www.youtube.com/watch?v=trORkNlIyyQ

Code that is responsible for camera rotation is following - 

    IntVector2 mouseMove = input->GetMouseMove();
    yaw_ += MOUSE_SENSITIVITY * mouseMove.x_;
    pitch_ += MOUSE_SENSITIVITY * mouseMove.y_;
    pitch_ = Clamp(pitch_, -90.0f, 90.0f);

It seems that input_->GetMouseMove() returns incorrect value after window's minimizing.

I use Urho3D 1.5 release version.
It compiled under Visual Studio 2013 (Win7 64bit)

**Comment by cadaver** [comment]
Thanks for the report. For me, this happens only on non-Aero Windows theme.

**Comment by itisscan** [comment]
I have tried to switch Windows theme to Aero, basically I set only visual styles on windows and buttons,(http://imgur.com/FtMXuuf) and then problem has been solved.

**Comment by cadaver** [comment]
This sounds like a bug in SDL when reporting back the OS cursor position (which is used to measure delta from window center). Nevertheless it should be nice to fix because it might affect also legacy Windows versions with no Aero.
