### ISSUE TITLE
Failed to create texture HRESULT 80070057 in TEXTURE_DYNAMIC usage mode

### ISSUE THREAD

**Issue by OldSnake22** [urho3d/Urho3D#1153]
I get that failed to create texture error when i simply do this:

m_pLerpBoxTexture = new Texture2D(context_);
m_pLerpBoxTexture->SetSize(512,512,Renderer::GetRGBFormat(),TextureUsage::TEXTURE_DYNAMIC);

However my texture IS STILL CORRECTLY CREATED and i can display it normally...
This error does not happen in TEXTURE_STATIC mode.

Im using DirectX 11 renderer.

**Comment by cadaver** [comment]
Interesting. Will investigate.
