### ISSUE TITLE
Add CodeLite CMake generator

### ISSUE THREAD

**Issue by thebluefish** [urho3d/Urho3D#1158]
CMake provides a generator for CodeLite project files. I cannot make a PR currently due to security settings on my system that prevents Git access, and the web interface sucks.

cmake_codelite.bat:
> @"%~dp0cmake_generic.bat" %* -G "CodeLite - MinGW Makefiles"

cmake_codelite.sh:
> $(dirname $0)/cmake_generic.sh "$@" -G "CodeLite - Unix Makefiles"

**Comment by thebluefish** [comment]
It should be worth noting that CMake's generator likes to add '-j 0' to the build, clean, and rebuild commands. This will cause a compilation error. However removing '-j 0' from these commands allows for a successful build with CodeLite.

**Comment by weitjong** [comment]
I guess the more the merrier.

**Comment by cadaver** [comment]
Yes, should not hurt. Can create those files.
