### ISSUE TITLE
the text in most of the samples doesn't show fully

### ISSUE THREAD

**Issue by chinaliye** [urho3d/Urho3D#1164]
![zbk5wxer9n6i hvz8fwhy p](https://cloud.githubusercontent.com/assets/16770928/12530020/53aa73b2-c20a-11e5-85ac-c40497921f60.png)

**Comment by cadaver** [comment]
Need more information, as I can't reproduce with a typical build. OS, compiler, build type, render API (d3d9/d3d11/gl) being used?
