### ISSUE TITLE
Paint Select in Editor [Feature Request]

### ISSUE THREAD

**Issue by practicing01** [urho3d/Urho3D#1165]
Selecting objects by holding the left mouse button, deselect with middle mouse button, quit selecting with right mouse button.  Like how blender does it.

**Comment by MonkeyFirst** [comment]
It's little strange because I guess this is not std Blender keys mode, you are using custom keys mapping?
Std mode this is it:
right mouse - to select
right mouse + shift - add to selection / exclude from selection
left mouse - move 3d cursor
middle - do nothing

**Comment by practicing01** [comment]
First you have to press C to go into paint select mode.

**Comment by MonkeyFirst** [comment]
Оh, sorry I thought about the simple selection

**Comment by MonkeyFirst** [comment]
Now you may try this brunch it's support this feature: https://github.com/MonkeyFirst/Urho3D/tree/PaintSelection
