### ISSUE TITLE
AnimatedModel::OnWorldBoundingBoxUpdate() doesn't update boneBoundingBox_

### ISSUE THREAD

**Issue by Enhex** [urho3d/Urho3D#1168]
AnimatedModel's bounding box gets updated by the render process. Since it only gets updated by the render process that means the bone bounding box is always a frame behind.

In my case I need the AnimatedModel bounding box to be correct before any rendering happens.

A quick solution is making UpdateBoneBoundingBox() public so the user can do it if needed.

But in general for correct result at all times the bone bounding box should be updated in OnWorldBoundingBoxUpdate(). For some reason there's a comment in that code that says "Note: do not update bone bounding box here, instead do it in either of the threaded updates". If it's done for performance reasons and in the general case the bone bounding box needs to update for rendering, then just exposing UpdateBoneBoundingBox() should be sufficient.

**Comment by cadaver** [comment]
In general Urho's intention is that various Get...() related to scene graph and bounds always returns correct data, and it's calculated if necessary, so this is an exception and you're right that it would certainly be preferable to be up-to-date.

Will do some quick performance profiling.

**Comment by cadaver** [comment]
Performance drop when not threading the bone bounding box update could be substantial with a large number of models. Therefore I followed your suggestion of making the function public. Additionally made it not mark the bone bounding box dirty when only the base scene node moves, since that's redundant.
