### ISSUE TITLE
Rakefile error in windows

### ISSUE THREAD

**Issue by yiown** [urho3d/Urho3D#1174]
this line:
abs_path = (ENV['OS'] ? ENV['dir'][1, 1] == ':' : ENV['dir'][0, 1] == '/') ? ENV['dir'] : "#{Dir.pwd}/#{ENV['dir']}"

produces:
rake aborted!
can't modify frozen string

fix: add the dup:
abs_path = (ENV['OS'] ? ENV['dir'][1, 1] == ':' : ENV['dir'][0, 1] == '/') ? ENV['dir'].dup : "#{Dir.pwd}/#{ENV['dir']}"

Regards.

**Comment by weitjong** [comment]
Thanks for the report. Interesting find. I wonder which version of Rake you are using. So far we have no issue yet with our Rakefile running in AppVeyor CI server using Windows Server 2012 R2. I reckon your Rake has a much newer version.

**Comment by friesencr** [comment]
Ruby 2.3 has a flag for frozen strings.  Env is part of ruby and I doubt rake is monkey patching env.

**Comment by weitjong** [comment]
Nevermind that. I think the reason why we have no issue so far in AppVeyor CI is because of our CI test coverage. At the moment we have two scaffolding tests but both of them are using relative path.
