### ISSUE TITLE
Texture->getHeight() return 0 allways

### ISSUE THREAD

**Issue by kanfor** [urho3d/Urho3D#1178]
When I create a texture and get the height return 0.
If I get the level height in cero with GetLevelHeight(0) return the right value.

texture = cache->GetResource<Texture2D("Urho2D/mario.png");
int H = texture.GetHeight();
int W = texture.GetWidth();

In this example H return 0, and W return the height ????

I use Linux

**Comment by cadaver** [comment]
This sounds like you don't have the define URHO3D_OPENGL in your application project, which leads into D3D9 headers of the graphics classes getting included, and as the class memory layouts are different, you get wrong results. I wouldn't be surprised to see a crash in that case.

**Comment by cadaver** [comment]
Closing this, as it shouldn't happen if the application build is properly configured, and there hasn't been further communication.
