### ISSUE TITLE
It seems than bounding box is incorrect fot node with multiple AnimanedModels

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1179]
My model is composed from of few parts

```
    playerNode_ = scene_->CreateChild("Hero");
    playerNode_->SetPosition(Vector3(0.0f, 0.0f, 0.0f));
    auto headObject = playerNode_->CreateComponent<AnimatedModel>();
    headObject->SetModel(cache->GetResource<Model>("Models/HeroHead.mdl"));
    headObject->ApplyMaterialList();
    headObject->SetCastShadows(true);
    auto bodyObject = playerNode_->CreateComponent<AnimatedModel>();
    bodyObject->SetModel(cache->GetResource<Model>("Models/HeroBody.mdl"));
    bodyObject->ApplyMaterialList();
    bodyObject->SetCastShadows(true);
    auto legLObject = playerNode_->CreateComponent<AnimatedModel>();
    legLObject->SetModel(cache->GetResource<Model>("Models/HeroLegL.mdl"));
    legLObject->ApplyMaterialList();
    legLObject->SetCastShadows(true);
    auto legRObject = playerNode_->CreateComponent<AnimatedModel>();
    legRObject->SetModel(cache->GetResource<Model>("Models/HeroLegR.mdl"));
    legRObject->ApplyMaterialList();
    legRObject->SetCastShadows(true);
    auto handLObject = playerNode_->CreateComponent<AnimatedModel>();
    handLObject->SetModel(cache->GetResource<Model>("Models/HeroHandL.mdl"));
    handLObject->ApplyMaterialList();
    handLObject->SetCastShadows(true);
    auto handRObject = playerNode_->CreateComponent<AnimatedModel>();
    handRObject->SetModel(cache->GetResource<Model>("Models/HeroHandR.mdl"));
    handRObject->ApplyMaterialList();
    handRObject->SetCastShadows(true);
```

When head is outside the screen all object is hiden

**Comment by cadaver** [comment]
When you instantiate multiple AnimatedModels into the same node, this enables the master/slave animation sharing system, where the first one should have the full skeleton and its bones & bounding box are used by the rest. This means that the first model should typically be the whole body (even if it doesn't contain actual full geometry).

**Comment by 1vanK** [comment]
I need replace parts of hero in game process. Every part has full skeleton, and single AnimationController for node works perfect. It is necessary to create a bunch of nodes with parts with many animations controllers?

**Comment by cadaver** [comment]
The method you're using (single animation control) is better, we just have to get the bounding box handling right. I wouldn't be surprised if there are culling issues when a part model doesn't contain all the geometry. Can you share the models, or provide some stand-in models that highlight the same issue?

**Comment by 1vanK** [comment]
https://github.com/1vanK/MyFiles/raw/master/Temp/ModelFromParts.zip

**Comment by cadaver** [comment]
Thanks!

**Comment by 1vanK** [comment]
Thank you!
