### ISSUE TITLE
Readline library compile issues

### ISSUE THREAD

**Issue by rasteron** [urho3d/Urho3D#1180]
I'm currently having problems getting the latest to build in Windows. I got the packages here: http://gnuwin32.sourceforge.net/packages/readline.htm. I got passed through CMAKE setting the paths but still getting path errors.

Perhaps include this to ThirdParty folder/libraries?

**Comment by weitjong** [comment]
I am a little bit confused here. The Readline library is only being search for for non-Win32 platform. It should only be required for Linux/OSX/RPI desktop platforms. We should have tighten the control to exclude iOS/Web/Android platforms. Will do that now while we are at it. As for Windows, I am seriously not sure that library will work there without also pulling in the other GnuWin32 stuffs, which I don't have any experience with. If you have modified our build system to use GNU/Readline on Windows/MinGW than you are on your own.

> Perhaps include this to ThirdParty folder/libraries?

Surely not. It is GPL last time I check. To dynamically link to it is one thing and is OK (similar to how we link to dl, pthread, etc). To have the library in its source form in our library is totally another, I am afraid.

**Comment by rasteron** [comment]
> The Readline library is only being search for for non-Win32 platform. It should only be required for Linux/OSX/RPI desktop platforms. We should have tighten the control to exclude iOS/Web/Android platforms. 

Ok thanks, maybe this is the case..

> Surely not. It is GPL last time I check. To dynamically link to it is one thing and is OK (similar to how we link to dl, pthread, etc). To have the library in its source form in our library is totally another, I am afraid.

I did not notice that but thanks for the heads up. Please disregard, cheers.
