### ISSUE TITLE
[2D][Physics] Body position not updated correctly

### ISSUE THREAD

**Issue by Batanick** [urho3d/Urho3D#1183]
If we have a parent node + child node - both with RigidBody component, then the position of the child node is not updated correctly. Initial idea was to create a jump detector for so, I am using a child body as a collision detector, but right now the box2D position for a child node is not updated, due to optimization in the RigidBody.cpp file:
```
void RigidBody2D::OnMarkedDirty(Node* node)
{
    if (physicsWorld_ && physicsWorld_->IsApplyingTransforms())
        return;
...
}
```

Patch with a way to reproduce must be attached to this issue
[RigidBody_position_bug.patch.txt](https://github.com/urho3d/Urho3D/files/114853/RigidBody_position_bug.patch.txt)

PS can also be relevant to 3D physics

**Comment by Batanick** [comment]
Can be fixed by creation of the special flag for these types of objects, or removing of the optimization code

**Comment by cadaver** [comment]
Will test the PR you included. A possibly cleaner fix would be to apply the transforms from Box2D in parent-child order, like the 3D physics already do.

**Comment by Batanick** [comment]
Not sure if this will helps in this case since in my example we are initially processing parent node and then - child node. The flow that leads to the current behavior is:

1. We updating the parent position. PhysicsWorld#applyWorldTransform = true
2. During the processing of the parent node, we marking child position as dirty 
3. RigidBody#body position for child during this process is not updated becouse of applyWorldTransform == true.
4. Another component of the child node calling GetPosition\Rotation during his OnMarkedDirty execution. Child#dirty = false
5. During RigidBody#ApplyWorldTransform for child we overring the world position of child with the position from the rigid body
