### ISSUE TITLE
Documentation Examples

### ISSUE THREAD

**Issue by hdunderscore** [urho3d/Urho3D#1185]
Here is something I have been looking at briefly -- using the existing samples and engine source (and adding some doxygen snippet markup), including example code for C++/Angelscript/Lua (where applicable) for each class:

https://github.com/hdunderscore/Urho3D/commit/096a99b38153637b7b009a4713f6c5b8c6a63f0f

Screenshots:
![Eg 1](https://94e12c83a0cb2933f1c8b3baf4d7663c110f7d53.googledrive.com/host/0B8btTTaJ0buXVnFCUVNkODJXdms/eg1.png)
![Eg 2](https://94e12c83a0cb2933f1c8b3baf4d7663c110f7d53.googledrive.com/host/0B8btTTaJ0buXVnFCUVNkODJXdms/eg2.png)

At this stage I'm only looking at class level examples, not member/method examples. Yay or nay?

**Comment by weitjong** [comment]
Yay! I particularly like how the annotation is being utilized here. Brilliant.

Fruit for thought.

1. Cross reference the anchors generated by ExamplesGen.dox in our existing class reference document.
2. We need two stylesheets. One default stylesheet as you have now for normal user and another one matching the orderedlist/minimal theme used by our online documentation.

**Comment by hdunderscore** [comment]
Thanks for taking a look !

I was thinking that when I get closer to a PR, I'll clean up and revert the changes to style and only make minimal changes to the Doxyfile.in -- those can be handled in another PR.

**Comment by cadaver** [comment]
Excellent minimal work approach, thanks for this!

I think for starters the top level (class) examples are sufficient, method examples can be added when there's some particularly complex method.

**Comment by bmcorser** [comment]
Interested in helping out here as a way to learn Urho ... anything I can do?

**Comment by hdunderscore** [comment]
@bmcorser: Definitely, searching for suitable example code and providing the annotation is quite time consuming at the moment-- you could help with that. I'm going down the doxygen 'Class' list in alphabetical order.

-----

Before you dive into that, it helps to be able to generate the docs quickly to test the output (eventually it should be part of the normal cmake process..):

1. If you are on windows and you have g++ installed, running the examplegen.bat should be enough to generate the ExamplesGen.dox file. You'll need to do this each time you add new annotations to the source/samples.
2. Run doxygen to generate the docs -- You could use the standard way (I might have broken the doxyfile atm ?) or use doxygen or doxywizard directly. I'm using doxywizard, just loading in the Doxyfile.in and running it.

----

Once you have that going, pick a letter of the alphabet, or pick your favorite Urho3D classes, and start working on those class examples.

1. Check the Source/Samples,  bin/Scripts and bin/LuaScript for examples of usage, if it's an internal class you can search the engine source for significant usage. Sometimes I have run into classes that maybe I didn't find a good example for, I just write that down in a todo file and move on.
2. Examples from the samples are best, but if it's an internal class then I look for examples of their initialisation and usage (ie, I don't annotate their constructors, but instead find some other class that is using them). Maybe later we will decide that annotating the engine source is messy or confusing and remove it-- but it's still a good way to learn !

Right now I've changed the annotation style:
```
// Begin [Example SomeClassName]
...
source
...
// End [Example SomeClassName]
```

Sometimes I think more than one class can benefit from the same example (although ideally unique examples are probably better), then you can do:
```
// Begin [Example SomeClassName] [Example SomeOtherClass]
... 
source
...
// End [Example SomeClassName] [Example SomeOtherClass]
```

What doxygen is looking for when picking out snippets is simply two matching ```[snippet ids]```, the rest of the annotation style isn't required by doxygen itself. It does help to have a consistent, human-readable annotation style though (which also makes it easier for examplegen.cpp to find annotations and generate ExamplesGen.dox). However, the format of using ```// Begin [Example ClassName]``` produces a simple limitation, if you want to have two examples for one class in the same file, then you need to do something like this:

```
// Begin [Example SomeClassName 1]
...
source for example 1
...
// End [Example SomeClassName 1]

// Begin [Example SomeClassName 2]
...
source for example 2
...
// End [Example SomeClassName 2]
```

Or instead of numbers, you'll see I put something more useful like ```// Begin [Example SomeClassName Initialization]```

You can see examples from my git commits-- but if I wasn't clear, let me know !

**Comment by bmcorser** [comment]
This is great, but I got really put off by the slow build time with Doxygen:

`doxygen Doxyfile.in  24.34s user 1.41s system 94% cpu 27.115 total`

Is there a way to limit what Doxygen builds so I can iterate faster?
