### ISSUE TITLE
"Could not save scene successfully!" but it saves anyway

### ISSUE THREAD

**Issue by TheComet93** [urho3d/Urho3D#1189]
This used to work fine, I'm not sure when it broke. 

![](http://i.imgur.com/W7RTyNZ.jpg)

This message shows up every time I save. There's nothing to be found in the log, and the XML file is save successfully anyway.

**Comment by cadaver** [comment]
I haven't seen this, at least when I use a "development" directory where I have full permissions. It's unlikely anything has changed in Urho related to file IO recently. Can you provide details of your build (platform, build type, compiler etc.)

**Comment by TheComet93** [comment]
**Platform**
```
$ uname -a
Linux twilight 4.1.15-gentoo-r1 #1 SMP Tue Jan 26 22:45:39 CET 2016 x86_64 AMD Phenom(tm) II X6 1090T Processor AuthenticAMD GNU/Linux
```

**Compiler/Tools**
```
$ cmake --version
cmake version 3.0.2

$ make --version
GNU Make 4.1
Built for x86_64-pc-linux-gnu

$ gcc --version
gcc (Gentoo 4.9.3 p1.2, pie-0.6.3) 4.9.3
```

**Urho3D Build (current HEAD)**
```
CMAKE_BUILD_TYPE:STRING=Debug
CMAKE_INSTALL_PREFIX:PATH=/usr/urho3d
URHO3D_64BIT:BOOL=ON
URHO3D_ANGELSCRIPT:BOOL=ON
URHO3D_DATABASE_ODBC:BOOL=OFF
URHO3D_DATABASE_SQLITE:BOOL=OFF
URHO3D_DEPLOYMENT_TARGET:STRING=native
URHO3D_DOCS:BOOL=OFF
URHO3D_DOCS_QUIET:BOOL=OFF
URHO3D_EXTRAS:BOOL=OFF
URHO3D_FILEWATCHER:BOOL=ON
URHO3D_LIB_TYPE:STRING=STATIC
URHO3D_LOGGING:BOOL=ON
URHO3D_LUA:BOOL=ON
URHO3D_LUAJIT:BOOL=ON
URHO3D_LUAJIT_AMALG:BOOL=OFF
URHO3D_LUA_RAW_SCRIPT_LOADER:BOOL=OFF
URHO3D_NAVIGATION:BOOL=ON
URHO3D_NETWORK:BOOL=ON
URHO3D_PACKAGING:BOOL=OFF
URHO3D_PCH:BOOL=ON
URHO3D_PHYSICS:BOOL=ON
URHO3D_PROFILING:BOOL=ON
URHO3D_SAFE_LUA:BOOL=OFF
URHO3D_SAMPLES:BOOL=OFF
URHO3D_SSE:BOOL=ON
URHO3D_TESTING:BOOL=OFF
URHO3D_THREADING:BOOL=ON
URHO3D_TOOLS:BOOL=ON
URHO3D_URHO2D:BOOL=ON
```

I'm running the editor from ```/usr/urho3d/bin/Editor.sh```.

**Comment by 1vanK** [comment]
Same problem (win7 + full access dir) when used File->Save scene
Ctrl+s works perfect

**Comment by cadaver** [comment]
Yes, reproduced now. I was always doing Save As.. which didn't produce the issue.
