### ISSUE TITLE
Urho2D Culling issue with camera rotation

### ISSUE THREAD

**Issue by OvermindDL1** [urho3d/Urho3D#1191]
I am attempting to use Urho2D, however anytime the camera node is rotated (say, with rotate2d), the clipping bounds of the Urho2D nodes appear to be getting constrained on the left/right axis. Easiest way to reproduce it, just open the sample of 24_Urho2DSprite, at the end of the HandleUpdate method just add:
```
cameraNode_->Rotate2D(timeStep*10.0f);
```
Then run it and watch what happens. I am trying to have a follow camera above the 2D player that rotates as the player rotates, however that appears difficult to do when everything becomes invisible at about 45 degrees and on...

It also happens on the 36_Urho2DTileMap sample by adding the same code at the same place, you can watch the tiles vanish at the edges on in.

EDIT:  Putting everything in the world 'but' the players unit and rotating it has no issue other than adding another transformation frame to everything, only rotating the node with the camera causes an issue.

**Comment by cadaver** [comment]
Looks like a misguided optimization. I'll just change the code to use the camera's frustum always.
