### ISSUE TITLE
bug in Terrain::WorldToHeightMap(): 1) rounding error and 2) index offset error

### ISSUE THREAD

**Issue by Lumak** [urho3d/Urho3D#1195]
// verified that the below changes fixes them
IntVector2 Terrain::WorldToHeightMap(const Vector3& worldPosition) const
{
    if (!node_)
        return IntVector2::ZERO;

    Vector3 position = node_->GetWorldTransform().Inverse() * worldPosition;
    int xPos = (int)((position.x_ - patchWorldOrigin_.x_ + 0.5f) / spacing_.x_);
    int zPos = (int)((position.z_ - patchWorldOrigin_.y_ + 0.5f) / spacing_.z_);
    Clamp(xPos, 0, numVertices_.x_-1);
    Clamp(zPos, 0, numVertices_.y_-1);

    return IntVector2(xPos, numVertices_.y_ - 1 - zPos);
}

**Comment by cadaver** [comment]
Thanks for the initial work, I believe the rounding needs to be done last, after applying spacing, and the clamping isn't being applied back (just like it was before). Will make those changes.

**Comment by cadaver** [comment]
Merged with changes.

**Comment by Lumak** [comment]
I agree with the rounding being done last, and I can't believe I also missed the clamp assignments. I made the changes in my code as well.  Thanks.
