### ISSUE TITLE
FileWatcher blocks indefinitely on Linux

### ISSUE THREAD

**Issue by TheComet93** [urho3d/Urho3D#1196]
I've noticed the Urho3D editor never properly shuts down and exits on my linux machine. It appears there are multiple threads stuck in ```read()``` after closing the editor window.

```
while (shouldRun_)
{
    int i = 0;
    int length = (int)read(watchHandle_, buffer, sizeof(buffer)); // Gets stuck here on shutdown

    // (snip)
}
```

**Comment by weitjong** [comment]
Thanks for your issue and PR.

Long ago I remember there was a time when Urho3D apps (including Editor) has a problem not exiting gracefully whenever they are launched from a path which user does not have write permission, e.g. /usr/local/bin. But that has been fixed, I am not able to reproduce your issue on my Linux box now. Have you tried to launch the Editor using Urho3D's build tree? Alternatively, can you tell me the exact steps to reproduce the issue.

**Comment by TheComet93** [comment]
It seems you are right. The issue is permission related. Here's what I did:
```
$ git clone git://github.com/urho3d/urho3d
$ cd urho3d && mkdir build && cd build
$ cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$(pwd)/dist -DURHO3D_SAMPLES=OFF ..
$ make -j7
$ make install
```

And now for the commands that reproduce the bug:
```
$ sudo chown -R root:root dist
$ dist/bin/Editor.sh
```
Close the editor and it will not exit. This is very likely because of this hack here, FileWatcher.cpp:197
```
        // Create and delete a dummy file to make sure the watcher loop terminates
        String dummyFileName = path_ + "dummy.tmp";
        File file(context_, dummyFileName, FILE_WRITE);
        file.Close();
        if (fileSystem_)
            fileSystem_->Delete(dummyFileName);
```

The editor is watching ```dist/share/Urho3D/Resources/Data/``` and ```share/Urho3D/Resources/CoreData/``` but those directories can't be written to.

This could potentially still be an issue on Mac (and Windows, if windows even has permissions. I'm not a Windows person so forgive me).

This pull request fixes the issue on Linux.

**Comment by weitjong** [comment]
I am able to reproduce it now. Thanks.
Yes, I agree that most likely the highlighted code is the culprit.
