### ISSUE TITLE
Spritesheet has no obvious way to set texture programmatically

### ISSUE THREAD

**Issue by OvermindDL1** [urho3d/Urho3D#1202]
I am dynamically generating a texture at runtime and am trying to figure out how to assign it to a Spritesheet, however it has no method to set its internal private `texture_` field, only a getter.  The only way to define the texture it seems is via manually crafting a Deserializer to feed it in data for whatever reason, and that only after having created the texture2d and stuffed it into the resource system.  Was there a reason for this being so roundabout or is it missing have a setter for the `texture_` for a reason that I am missing?

**Comment by cadaver** [comment]
For an answer that's not a guess we'd need to raise @aster2013 who is the original author. There's been quite notable periods of inactivity so the Urho2D part is in danger of falling unmaintained.

However the basic principle in Urho is that resources should be able to be fully programmatically defined. Going in a roundabout way with Serializer / Deserializer is backwards.

**Comment by OvermindDL1** [comment]
That was my thought, it would be fairly trivial to add a setter for it, there is already a getter.  Overall it seems that a *LOT* of things in Urho2D are missing setters, especially in the tilemap system as well.

**Comment by OvermindDL1** [comment]
Hmm, I was making a new branch to fix a lot of Urho2D things, and I was working on the TileMap class, but it needs to be trashed and have a major overhaul done on it as it is geared specifically toward TMX files and is lacking a lot of power because of that (consequently TMX files can be loaded into a better designed TileMap class with ease, so should I get around to writing that then it will work).

So a question, if I rewrite the TileMap class then should I do it under a new class name, keeping the old around for compatibility, or rewrite it entirely, breaking compat (fixing samples of course)?

**Comment by OvermindDL1** [comment]
I also exceptionally hate how Urho2D works based on pixels instead of 0.0->1.0 mappings, it makes it irritatingly difficult to have dynamic texturepacks without a lot of extra and needless bookkeeping.  Why was this style chosen as well?
