### ISSUE TITLE
Tiled map bug

### ISSUE THREAD

**Issue by CaptainCN** [urho3d/Urho3D#1205]
In demo 36_Urho2DTileMap, zoom in camera.
In urho3d 
![1](https://cloud.githubusercontent.com/assets/6292878/13197063/cf8a2446-d81c-11e5-92da-269956d91aef.png)
In Tiled Editor.
![2](https://cloud.githubusercontent.com/assets/6292878/13197064/d016bdb6-d81c-11e5-9eb9-0b559dae7a10.png)

**Comment by MonkeyFirst** [comment]
Hi, probably you need use texture's setting XML file. 
Try to create textureName.xml with this code:
~~~
<texture>
    <address coord="u" mode="clamp" />
    <address coord="v" mode="clamp" />
    <filter mode="nearest" />
    <mipmap enable="false" />
</texture>

~~~

**Comment by CaptainCN** [comment]
It‘s works.Thanks.
