### ISSUE TITLE
CMake Error (tolua++) Android

### ISSUE THREAD

**Issue by rasteron** [urho3d/Urho3D#1213]
When building for android and cloning the latest version, I get this error:

```
[ 55%] Creating directories for 'tolua++'
CMake Error: cmake version 2.8.12.2
Usage: c:\Program Files (x86)\CMake 2.8\bin\cmake.exe -E [command] [arguments ...]
Available commands:
  chdir dir cmd [args]...   - run command in a given directory
  compare_files file1 file2 - check if file1 is same as file2
  copy file destination     - copy file to destination (either file or directory)
  copy_directory source destination   - copy directory 'source' content to directory 'destination'
  copy_if_different in-file out-file  - copy file if input has changed
  echo [string]...          - displays arguments as text
  echo_append [string]...   - displays arguments as text but no new line
  environment               - display the current environment
  make_directory dir        - create a directory
  md5sum file1 [...]        - compute md5sum of files
  remove [-f] file1 file2 ... - remove the file(s), use -f to force it
  remove_directory dir      - remove a directory and its contents
  rename oldname newname    - rename a file or directory (on one volume)
  tar [cxt][vfz][cvfj] file.tar [file/dir1 file/dir2 ...]
                            - create or extract a tar or zip archive
  time command [args] ...   - run command and return elapsed time
  touch file                - touch a file.
  touch_nocreate file       - touch a file but do not create it.
Available on Windows only:
  comspec                   - on windows 9x use this for RunCommand
  delete_regv key           - delete registry value
  env_vs8_wince sdkname     - displays a batch file which sets the environment for the provided Windows CE SDK installed
 in VS2005
  env_vs9_wince sdkname     - displays a batch file which sets the environment for the provided Windows CE SDK installed
 in VS2008
  write_regv key value      - write registry value

Source/Urho3D/CMakeFiles/tolua++.dir/build.make:74: recipe for target 'Source/Urho3D/tolua++-prefix/src/tolua++-stamp/to
lua++-mkdir' failed
mingw32-make[2]: *** [Source/Urho3D/tolua++-prefix/src/tolua++-stamp/tolua++-mkdir] Error 1
CMakeFiles/Makefile2:1236: recipe for target 'Source/Urho3D/CMakeFiles/tolua++.dir/all' failed
mingw32-make[1]: *** [Source/Urho3D/CMakeFiles/tolua++.dir/all] Error 2
Makefile:136: recipe for target 'all' failed
mingw32-make: *** [all] Error 2
```

**Comment by weitjong** [comment]
Has it been successful for you before? If yes, which is the last known good commit that works for you? Or since which commit it breaks for your?

This part of the build system has not been changed lately, except that now when doing a cross-compiling build such as Android build, tolua++ (host tool target) always use Lua library internally, regardless of whether Urho3D uses Lua or LuaJIT. In order to build the host tool target correctly, you need to have a working MinGW compiler toolchain in your host system. That is, you need to have both Android NDK and MinGW setup in your PATH.

Personally I only do Android build on Linux host system, so what I need is a plain vanilla GCC instead of MinGW for the host tool building. And I don't have any issues with this setup, JIT or not JIT. I used to have Android build environment on my Win7 VM but not anymore due to space constraint, so I could not help you more to reproduce the issue with the latest HEAD version. Therefore, your answers to my questions above would help in the investigation.

**Comment by rasteron** [comment]
Thanks and yes, the last working commit for me was around my related issue/question here: https://github.com/urho3d/Urho3D/issues/1124

I already have my Android and MinGW setup paths correctly, as this works for the 1.5 release and the commit during my MinGW 5.x upgrade issue.

**Comment by weitjong** [comment]
You have to do better than that I am afraid. Do you know how to do ```git bisect```? If you know the exact commit that breaks your build then that would be really helpful. Otherwise you will have to wait until I have more free time to look at your issue closely.

**Comment by weitjong** [comment]
```git log Source/ThirdParty/toluapp/src/bin```

```
commit 1e311acb6aa2184e022f07a2b9476acc90a74332
Author: Yao Wei Tjong 姚伟忠 <weitjong@gmail.com>
Date:   Tue Feb 2 22:19:57 2016 +0800

    Speed up build for Debug configuration by building only active arch.

commit c4f6f315ff5b6ea992340780521d3e5f2e668b11
Author: urho3d-travis-ci <urho3d.travis.ci@gmail.com>
Date:   Tue Jan 26 13:55:03 2016 +0000

    Travis CI: bump copyright to 2016.
    [ccache clear]

commit 44e7322e4e24ce0b02a92c81a55f6232b7347164
Author: Yao Wei Tjong 姚伟忠 <weitjong@gmail.com>
Date:   Wed Jan 13 17:26:53 2016 +0800

    Enable LuaJIT universal binary build on OSX platform.
    Enable universal binary executables by default when targeting 64-bit OSX platform.

commit 21b01fcd5bef50934d63ad4eba2028c0ad254bbe
Author: Yao Wei Tjong 姚伟忠 <weitjong@gmail.com>
Date:   Wed Jan 6 15:00:43 2016 +0800

    Refactor how the EXE and SHARED linker flags are being setup.

commit 1cd242273e415416787bc544765345c0138a3e01
Author: Yao Wei Tjong 姚伟忠 <weitjong@gmail.com>
Date:   Mon Dec 14 22:39:53 2015 +0800

    Verify found Urho3D library has matching ABI with the chosen compiler.
    Check the CMake minimum version before setting project name as recommended by CMake.
    Minor documentation update on how to setup downstream projects using Urho3D library as external library.
    For AppVeyor - attempt to add scaffolding test using Urho3D SDK.

commit 55286eb820213f25314d1dc2feb89302493f1d60
Author: Yao Wei Tjong 姚伟忠 <weitjong@gmail.com>
Date:   Sun Dec 13 17:43:54 2015 +0800

    Fix host-tool building.
    [skip appveyor]

commit d7eee3b1349fc9416e6c2140958dca87bbd62830
Author: Yao Wei Tjong 姚伟忠 <weitjong@gmail.com>
Date:   Sun Oct 18 14:27:06 2015 +0800

    Only update the toluabind.c back to source tree when it is opted.
```

My hunch is on the last two in the above shortlisted change log. But why it hit you on Android/MinGW, I have no idea yet until I have time look close to into it. Actually it should not be difficult to troubleshoot yourself since you have the environment ready. Do that and I will you kudos if you can figure out the bug yourself and submit a PR for the fix :) .

**Comment by rasteron** [comment]
Thanks, I'll see what I can find and continue some build testing.

**Comment by weitjong** [comment]
I did another bug caused by external project setup when building tolua++. This bug does not explain why you had your build error, however. My suggestion is to upgrade your CMake version.

**Comment by weitjong** [comment]
Feel free to reopen this issue again if after upgrading the CMake you still have this problem.

**Comment by rasteron** [comment]
Hey @weitjong It's been a while but I finally got back into testing and resolved this issue and the upgrade to CMake fixed this problem. Thanks! :+1:

**Comment by weitjong** [comment]
Glad to hear that.
