### ISSUE TITLE
Buildsystem does not automatically copy the shared lib(s) to the tool directory causing AssetImporter hangs when processing the following fbx

### ISSUE THREAD

**Issue by yushli** [urho3d/Urho3D#1214]
using the following command (both in ubuntu and windows) 
AssetImporter.exe model bieshu_still.FBX bieshu.mdl -t -l -h
will hang forever. 
The fbx file is pretty big and cannot attach here. the following is the download link:
http://zuoyouxi.gamemei.com/liyusheng/bieshu_still.zip
Thanks for looking into this.

**Comment by cadaver** [comment]
I could not reproduce the hang on a 32bit VS2013 build, both debug and release. A 4MB model file was produced but I didn't verify if it actually contained correct content. Can you supply details of your build (OS, 32/64bit, debug/release, compiler used)?

**Comment by yushli** [comment]
Latest master branch, Windows 10, 64bit, debug build, Vs2015.  I also run it in Ubuntu 12.04, 32bit, release build ,gcc and it also hangs. 
in Vs2015 I tracked into the code and it hangs when leaving the function 
void BuildAndSaveModel(OutModel& model);(line 1030)
That is, when releasing the reference of  SharedPtr<Model> outModel(new Model(context_)); (line 799) when in turn calls into SharedPtr destructor. If I change the code to outModel = new Model(context_) instead of using sharedptr, it successfully exits this function, but throw exception in line 464 when releasing HashSet<String> usedTextures;

**Comment by yushli** [comment]
The precise line where hangs is Container/Ptr.h line 209
void ReleaseRef()
    {
        if (ptr_)
        {
            ptr_->ReleaseRef(); (line 209)
            ptr_ = 0;
        }
    }
when releaseing SharedPtr outModel and trace to this line of code, vs2015 just cannot trace into the function call and hangs for ever.

**Comment by yushli** [comment]
I checked in windows 10 32bit , vs2013 debug build and actually it runs successfully. Maybe some issue related to 64bit?

**Comment by yushli** [comment]
Hi, any progress on this one?

**Comment by cadaver** [comment]
Can't reproduce the hang so far, so you will have to keep digging yourself. I'm quite sure there's a legit bug, could be a memory overwrite, but the place where it hangs possibly has little to do where the actual bug happens.

**Comment by yushli** [comment]
I double checked and find that it is VS2015 32bit debug build on 64bit machine,linking type is Shared. Sorry for that mistake. Vs2015 64bit build on 64bit machine is fine. I cleaned the whole solution and rebuild the 32bit and the error is the same.

**Comment by yushli** [comment]
I attached the CMakeCache.txt if that can help.
[CMakeCache.txt](https://github.com/urho3d/Urho3D/files/150886/CMakeCache.txt)

**Comment by yushli** [comment]
VS2015 32bit release build (linking type: shared) on 64bit machine crashes when processing the fbx. 64bit release build runs fine.

**Comment by yushli** [comment]
@cadaver Do you have time to investigate this issue a little more? I can use the 64bit release build but the hang/crash in 32bit build gets me a bit anxious to find where really goes wrong...

**Comment by weitjong** [comment]
@yushli If I am allowed to speak for Lasse, I think he already made it clear that you are on your own on this one.

**Comment by yushli** [comment]
@cadaver  Can your confirm that the vs2015 32bit build in your 64bit machine doesn't contain this error? If so then I will have to investigate by myself. It is hard to debug a memory corruption without knowing the details of the engine. But if you cannot reproduce this error then I will be on my own to figure that out.

**Comment by cadaver** [comment]
I have tested so far on a Windows 7 machine, on which I believe I have tested all combinations of VS2015 shared/static, and release/debug. No crash there. Next I will move to Windows 10 to see if the execution environment is somehow different which brings out the bug.

**Comment by yushli** [comment]
Thank you for looking into this. I think I find the problem. when using shared link, the tool folder doesn't contain Urho3D_d.dll, I have to copy it over(including copying ove d3dcompiler_47). Then I may make some changes to the code and rebuild urho3d, but this dll doesn't update automatically.

**Comment by yushli** [comment]
I found that out by downloading the latest github branch, generate the solution by running cmake_vs2015.bat ..\Urho3D_build -DURHO3D_LIB_TYPE=Shared, then build the solution in vs2015. When I try to run bin\tool\assetimporter.exe then it reports Urho3D_d.dll is missing. 
Thank you for looking into this issue. Urho3D rules!

**Comment by yushli** [comment]
Side Note: Is it possible to add cmake script to symlink urho3d.dll to the tool folder during build process?

**Comment by cadaver** [comment]
One easy way would be to just get rid of the tool subdirectory (like it originally was) and push all binaries to the Bin folder.

**Comment by weitjong** [comment]
The separation of the binaries into tool subdir was driven by the fact that those binaries are meant for host instead of target platform. This distinction is clearer in a cross-compiling build. I could not remember for sure now without looking at the code, but I think there is a benefit in doing so or otherwise we/I would not have done it in the first place. In fact I actually recall that I have verified that the DLLs (Urho3D.dll/Urho3D_D.dll and d3dcompiler_47) are automatically copied to the tool subdir. Probably there is a regression afterward or that I have not verified for all the cases. Should not be difficult to fix when I have time. I will be focusing on SDL-2.0.4-upgrade this weekend though.

**Comment by cadaver** [comment]
Ah, naturally.
