### ISSUE TITLE
Color.FromHSV(...) write same values (from HSV) for rgba representation of color

### ISSUE THREAD

**Issue by MonkeyFirst** [urho3d/Urho3D#1215]
This is my code *.AS
~~~
        procSkyLightNode = procSkyNode.CreateChild("ProcSkyLightNode");
        if (procSkyLight is null || newOpenedScene) 
        {
            procSkyLight = procSkyLightNode.CreateComponent("Light");
            procSkyLight.lightType = LIGHT_DIRECTIONAL;
            procSkyLightColor.Clip(true);
            procSkyLightColor.FromHSV(57.0f, 9.9f, 73.0f , 1.0);
            procSkyLight.color = procSkyLightColor;
        } 
~~~

this inspector values:
![123](https://cloud.githubusercontent.com/assets/9577466/13357911/e371a7c2-dcd6-11e5-990d-f883c32c78f5.png)

I guess this is wrong,
Clip() do not help with clipping color into range [0..1]

**Comment by cadaver** [comment]
These were contributed so I'm not intimately familiar, but FromHSV() should take values in 0-1 range, not 0-255. The values inside the function is not checked, so it operates on garbage in -> garbage out principle. Clip() only clips the current rgba values, not future values you're going to set.

**Comment by MonkeyFirst** [comment]
So, if I try normalize these value this should work, I suppose.
