### ISSUE TITLE
Urho3D doesn't build with physics turned off

### ISSUE THREAD

**Issue by damu** [urho3d/Urho3D#1216]
Someone reported build errors which look like a bug: http://urho3d.prophpbb.com/topic1896.html
I just found that and forwarded it to here. I tested disabling physics and it aborted at AngelScript in my test: http://pastebin.com/wamJG8cN
Tested on Windows 7 with Urho3D 1.5 and these options: http://i.imgur.com/Kqv1njz.jpg

If AngelScript or something else needs physics, could there be a better error? Maybe during CMake generation? I don't know CMake good enough.

**Comment by Enhex** [comment]
In my case I disabled physics, navigation, Lua.
Enabled OpenGL.
Full build options: http://i.imgur.com/9Bq28L3.png

Getting these errors:
```
identifier "FixedUpdate" is undefined	LogicComponent.cpp	209	
identifier "FixedPostUpdate" is undefined	LogicComponent.cpp	217	
class "Urho3D::LogicComponent" has no member "HandlePhysicsPreStep"	LogicComponent.cpp	148	
class "Urho3D::LogicComponent" has no member "HandlePhysicsPreStep"	LogicComponent.cpp	204	
class "Urho3D::LogicComponent" has no member "HandlePhysicsPostStep" LogicComponent.cpp	160	
class "Urho3D::LogicComponent" has no member "HandlePhysicsPostStep" LogicComponent.cpp	212	
```
FixedUpdate and FixedPostUpdate are defined inside:
```
#if defined(URHO3D_PHYSICS) || defined(URHO3D_URHO2D)
```

And declared inside:
```
#ifdef URHO3D_PHYSICS
```

**Comment by damu** [comment]
Do some components really rely on or need the physics component or should that be (more) optional?

**Comment by cadaver** [comment]
This is a bug. There's insufficient #ifdef testing. Of course, when physics are disabled, you can't use FixedUpdate events, since they're tied to the simulation stepping.
