### ISSUE TITLE
Skeleton with multiple root nodes is not supported in AssetImporter

### ISSUE THREAD

**Issue by yushli** [urho3d/Urho3D#1221]
Is it a hard limit in Urho3D or this feature is just not implemented yet? If the latter, what parts need to change to support this feature? Thanks.

**Comment by cadaver** [comment]
I would say that it's questionable if the asset has multiple root nodes. You should be able to create a new root node "above" them. The scene node of the AnimatedModel is a single implicit "extra" root bone in any case.

**Comment by yushli** [comment]
Please see the attached fbx. It can be successfully imported into Unity. But AssetImporter reports ErrorExit("Skeleton with multiple root nodes found, not supported"); (AssetImporter.cpp line 628). 
[T.zip](https://github.com/urho3d/Urho3D/files/156812/T.zip)

Also one related issue: in Unity, it supports use a T-bone model, then save only the animation data in separate fbxs. In current AssetImporter, it doesn't support animation only data. 
ErrorExit("No geometries found starting from node " + rootNodeName); (line 795)

Please see the attached animation fbxs. That way the animation files can be quite small (several hundred KBs vs ten megabites)
Is it possible to support that in Urho3D as well?

[Run.zip](https://github.com/urho3d/Urho3D/files/156816/Run.zip)

**Comment by cadaver** [comment]
We interact through Assimp, so it remains to be seen exactly what is possible, but I wouldn't suppose  either of these would be impossible to fix. For example for the multiple root nodes issue, it's possibly a misinterpretation of the original model either by assimp or by AssetImporter code, and one solution would be to forcibly add a root node at the top level. Another matter is when anyone has time to actually implement these fixes.

**Comment by yushli** [comment]
The original model is like containing a human body  skeleton and the skeleton for clothes, like a skirt. Thus there are multiple root bones since the skirt skeleton isn't parented to the human body. I can try to implement the fixes but not know much about how animations and bones are implemented, thus may need to know at least that can be doable in Urho3D, given the current data architecture and node hierarchy of uhro3d animations. From my understanding, all animations are converted into urho3d nodes manipulations over time. Maybe you can shed some light on where to start to implement that? Thank you.

**Comment by cadaver** [comment]
I looked at the model in the open3mod viewer and there seemed to be just a single-rooted hierarchy, so for this case I believe it's just an AssetImporter bug, unless the open3mod viewer is disregarding the other roots.

I don't recommend trying to get actual multiple-root support into Urho3D, because like I said the AnimatedModel scene node acts as a single root in any case. So IMO the best that can be done (for cases where there are legitimately many roots) is to automatically insert a top-level root node and maybe issue a warning to the user.

**Comment by yushli** [comment]
Would you like to fix that if it is an AssetImporter bug? 

Inserting a top-level root node to support legitimate many roots would be good enough as you explained. Thank you for your kind help. Hope to see that coming soon.
Urho3D rules! That is an excellent engine. Hope to see more and more games using this engine in future.

**Comment by cadaver** [comment]
Yes, legit bugs should be fixed, given time. The AssetImporter logic to determine the root bone is somewhat complex and errorprone, and this is an interesting test case, so thanks for it.

**Comment by yushli** [comment]
You are welcome. And thank you for all the efforts!

**Comment by yushli** [comment]
The mdl and ani files can be processed successfully. But the model in the generated file has some position problem. Please see the attached pictures: If the generated mdl file is used as StaticModel, the model is correct. But if it is used as AnimatedModel, the hair and the sward are placed at the wrong place. 

	Node* tNode = scene_->CreateChild("tnode");
	StaticModel* tModel = tNode->CreateComponent<StaticModel>(); //using as StaticModel is correct
	tModel->SetModel(cache_->GetResource<Model>("tmod.mdl"));
	tModel->ApplyMaterialList();

<img width="960" alt="staticmodel_correct" src="https://cloud.githubusercontent.com/assets/1681453/13560985/d7da2d98-e461-11e5-9454-2220dc69e5b2.png">

	Node* tNode = scene_->CreateChild("tnode");
	AnimatedModel* tModel = tNode->CreateComponent<AnimatedModel>(); //using as AnimatedModel is wrong
	tModel->SetModel(cache_->GetResource<Model>("tmod.mdl"));
	tModel->ApplyMaterialList();

<img width="960" alt="animatedmodel_incorrect" src="https://cloud.githubusercontent.com/assets/1681453/13561007/321bc6ae-e462-11e5-878c-540217843f8b.png">
