### ISSUE TITLE
Deferred/Forward differ alpha pass with same techniques/material 

### ISSUE THREAD

**Issue by MonkeyFirst** [urho3d/Urho3D#1222]
Just two screenshots for demonstrate this issue, all things the same, only RenderPath are different
forward
![123](https://cloud.githubusercontent.com/assets/9577466/13509141/36ba3412-e1b4-11e5-81df-6c7d3ada27b3.png)

deferred
![222](https://cloud.githubusercontent.com/assets/9577466/13509151/41c0ca06-e1b4-11e5-9bcc-f9b5c35e3634.png)

Technique
~~~
<technique vs="GridShader" ps="GridShader" vsdefines="VERTEXCOLOR NOUV" psdefines="VERTEXCOLOR">
    <pass name="alpha" depthwrite="false" blend="alpha" />
    <pass name="prepass" psdefines="PREPASS" />
    <pass name="material" />
    <pass name="deferred" psdefines="DEFERRED" />
</technique>
~~~

What is wrong with Deferred ? mb need additional settings for it somewhere?

**Comment by 1vanK** [comment]
Если сетка использует альфу, то она использует forward метод при рендеринге, разве нет? Deffered с прозрачностями не может работать как бы

**Comment by 1vanK** [comment]
посмотри любую технику с альфой. тебе нужно оставить только первую строку с пассом alpha

**Comment by MonkeyFirst** [comment]
Точно, спасибо.
~~~
<technique vs="GridShader" ps="GridShader" vsdefines="VERTEXCOLOR NOUV" psdefines="VERTEXCOLOR">
    <pass name="alpha" depthwrite="false" blend="alpha" />
</technique>
~~~

**Comment by weitjong** [comment]
Guys, should I label this issue as invalid or something else. Could not understand what you were saying?

**Comment by 1vanK** [comment]
Sorry. Yes, it is invalid.
