### ISSUE TITLE
Invalid 16bit Terrain data calculation

### ISSUE THREAD

**Issue by horvatha4** [urho3d/Urho3D#1223]
Hi guys! I think in the function: Terrain::CreateGeometry,  the 16bit data calculation is not correct.
Line 823:
![terrain_cpp](https://cloud.githubusercontent.com/assets/17128334/13534337/f5015d58-e234-11e5-8fca-008703cd21e1.png)
And the result:
![terrain_shot](https://cloud.githubusercontent.com/assets/17128334/13534377/18b4a912-e235-11e5-9651-cf18d31256ca.png)

**Comment by horvatha4** [comment]
So, I changed the "/ 256.0f" to "* 256.0f" and is now correct!
![terrain_ok_shot](https://cloud.githubusercontent.com/assets/17128334/13534791/34bfebf6-e237-11e5-9827-6148c2a92502.png)

**Comment by cadaver** [comment]
The documentation for SetHeightMap says

/// Set heightmap image. Dimensions should be a power of two + 1. Uses 8-bit grayscale, or optionally red as MSB and green as LSB for 16-bit accuracy. Return true if successful.

In other words, it's a low-endian convention, where the green channel doesn't bring more height range, but more accuracy instead. You seem to have used green as the most significant channel.

**Comment by horvatha4** [comment]
Oh I see! I misunderstand that! Code reverted.
Thanks!
