### ISSUE TITLE
wrong positions when loading AnimatedModel from AssetsImporter generated mdl

### ISSUE THREAD

**Issue by yushli** [urho3d/Urho3D#1227]
Referring to https://github.com/urho3d/Urho3D/issues/1221 last comment.
The generated mdl file cannot be corrected loaded as AnimatedModel. I create this new issue since i cannot reopen the old one.

**Comment by cadaver** [comment]
Thanks for reporting. It seems the case of multiple geometries in different positions of the hierarchy aren't handled properly, or rather, the geometries get a wrong baking transform or offset matrix. Requires investigation.

**Comment by yushli** [comment]
Thank you for looking into it.

**Comment by cadaver** [comment]
This should be solvable. Almost got it but still have some weird distortion to sort out. The basic point is that your model contains non-skinned parts, and Urho doesn't like AnimatedModel to have them, as it assumes the whole model is skinned. So AssetImporter has to "invent" rigid skinning data (based on the node they're attached to) for the non-skinned parts.

**Comment by yushli** [comment]
Thank you for all the efforts! Looking forward to the final solution.

**Comment by yushli** [comment]
That is fabulous! Thank you for your great work!
Maybe it also fixes issue 1118 (https://github.com/urho3d/Urho3D/issues/1118)
I will go and verify if 1118 is also fixed.

**Comment by yushli** [comment]
1118 is not fixed by this change.
