### ISSUE TITLE
Virtual Texturing

### ISSUE THREAD

**Issue by boberfly** [urho3d/Urho3D#1230]
One of these days I'd like to implement virtual texturing. If Cadaver remembers I wanted to make this aaaages ago when I was first asking how the threading system worked, and now there's some great building blocks already to implement this well like streaming off another thread + GetTempResource to chew it down the WorkQueue via Intel's very fast ISPC GPU texture encoders, if transcoding is needed from a compressed format as one example.

**What is it?**
A way to stream in very large textures from storage and not have it all residing in memory.

**Why is it cool?**
Games demand very high quality and very high res textures these days, and look unique and render fast without being too fillrate-heavy. Virtual Texturing allows this, and it can reduce state changes dramatically as the texture units don't need to be changed as you're accessing the same texture unit for each opaque drawable which uses the virtual texture.

**What is needed/how would it be implemented?**
- I'd imagine a VirtualTexture class would be made which is API-agnostic, and the Image and API-specific Texture classes would be extended to support efficient texture uploads using the most optimal way per-API eg. PBOs on OpenGL, or just use what they have as-is and see if it's fast enough. An LRU list would be made to determine what texture tiles/mips are in-use and free up ones which are not being used, so that new ones can stream in.
- Support GL 4.x/DX11 sparse/tileable textures (if it makes sense and there's a speed-up). If you only target these GPUs which support this extension and not DX9, you could remove the requirement of borders around the tiles.
- To determine which texture tiles are needed for a frame, there are a few ways to detect this. The most common way is to render the whole scene to a small render buffer with a special shader and let the CPU read it back to determine which tile/mip texture is needed. Commonly the UVs and mip-map are rendered, and the CPU would then use this as a hash to pick up the right tile and load it in asynchronously from disk, with the option to transcode it to a GPU compressed format before uploading to the GPU. This can cause bad stalls so I'd like to investigate if something along the lines of the software occlusion query rasterizer could also do UV+mip detection, but perhaps it might not be too bad in practice (as the software solution can be very limited to only the occluder objects having a virtual texture). Modern APIs can have accurate sync points to hide the stalls, or not cause stalls at all with correct pipelining.
- This involves a toolset to easily convert assets into tileable texture resources and UV offsetting. This is very important because an artist will not sit there stitching their asset textures and re-arranging all their asset UVs to cater virtual texturing. Also a way to set tile size and border size which is optimal for the platform (4x4 border for desktop DXT1/DXT5-compressed textures, or 8x8 if using ASTC on mobile, for example).
- The existing packing system could be used (or extended) also to store these large textures, but instead of strings for filenames it could be hashes for the UV+mip for fast lookups and keeping offset+size info in memory for all the tiles. The files inside could be multiple PBR texture layers.

**Virtual Texturing sucks, look at the game Rage's streaming issues and large storage costs**
- In some cases it can, but I believe it can have huge wins for some requirements. For example, large terrain which defers the splat sample mixing commonly done on large terrains to smaller tiles asynchronously to reduce fill-rate instead of doing the splat sample mixing per-frame directly onto the terrain which is traditionally done. It also allows a lot more splat layers. Doing procedural textures could be elegantly realised using virtual textures efficiently also.
- The streaming issue could be fixed with later APIs and being smarter about the older ones where possible, or simply having clever fade-in shaders to go between the mip levels.

Thoughts? No idea when I can get around to this, just throwing it out there as a cool feature to have... :)

**Comment by cadaver** [comment]
If you can do this without detriment to non-virtual texture uses (e.g. "pay only for what you use") then it will be awesome. The toolset part I'd assume to be challenging.

**Comment by boberfly** [comment]
Yeah I'm debating on how to approach the asset pipeline side of things, whether or not it should use Urho3D itself.

I've been using things like Gaffer which makes these kinds of things a little more straightforward (it's a nice framework for building stuff with nodes for 2D compositing to 3D scenegraph manipulation, but it's generic enough to be used as a general-purpose DAG processing framework to do almost any processing you can think of).

For instance, if you've got a _huge_ asset library, you could make things entirely procedural where all shader/geo/etc. processing can go through a node network to do boring tasks like normal-map baking, UV offsetting, to deploying compressed formats for different targets, or building shader/material/technique combinations offline, or even just updating some component data attributes in a non-destructive way.

For virtual texturing, you could make a scenegraph which contains _all_ the assets of your game and what textures it contains, and have some C++ or python code or some logic expression which stiches UVs together or bakes all the textures to one fat texture, and have this processing automatically be threaded to an extent and/or throw it on a render farm as the Qt UI is decoupled from the processing. Most everything stays out of core as much as possible, so all the assets wouldn't be loaded in at once.

This brings a huge dependency cost as well and I wouldn't dream of having this in the runtime, but some command-line utilites could be made for some things which only contain Urho libs.

**Comment by r-ku** [comment]
Looks like blender can be used to create megatextured assets. I found [this](http://holger.dammertz.org/stuff/notes_VirtualTexturing.html) article which has [sample scene](https://dl.dropbox.com/u/6738543/data/scene_greencave.blend) made in blender. That will probably be useful for you @boberfly.

Also one more point why virtual textures rock is that decals can be implemented cheaply and they do not suffer from z-fighting issues.

**Comment by boberfly** [comment]
@r-ku Yeah for forward-rendering decals implemented this way makes sense to reduce overdraw too, similar to what I suggested with terrain splats. For deferred you'd just implement it by writing to the gbuffer like lights before lighting though.

Yep I've toyed around with that scene before, from memory I think it texture bakes with a python script, pretty handy. I prototyped something similar in Nuke, but I was going to implement it with [Gaffer](http://imageengine.github.io/gaffer/) which makes pipeline/TD work very enjoyable, writing I/O ops for geometry and images that can run headless and can run out of core (great if you've got terabytes of assets which need to be cooked and distributed to a farm in one go).

**Comment by HeadClot** [comment]
Hey @boberfly 

I would not use Urho3D for the packing of Textures and the like. This could slow things down when working with the Urho3D editor. 

Instead I would make a 3rd party application similar to what [Granite](http://graphinesoftware.com/granite-unreal-video-tutorials) does with their Unreal 4 branch of their software that packs existing textures to an atlas of combined textures via a plugin for Urho.

Either way my 2 cents.

**Comment by boberfly** [comment]
@HeadClot 
Yes and no, if you're doing procedural-generation from a set of tiling textures/splats or noise algorithms, this would be processed in worker threads in Urho3D itself, or on the GPU. This isn't too expensive as the processing is asynchronous over many frames, and only the tiles (128x128 or 256x256) which need updating are processed, instead of doing all the texture mixing in the full scene render. This is very scalable which can be tweaked to your hardware, so slower hardware would just have more stream pop-in. Any sync points would be texture uploads, and limiting it to like 1 tile per frame would keep the sync point small, but if your mixing is done on the GPU then that removes the CPU/GPU sync point entirely. :)

The baking stage if you were to store raw pre-rendered texture data this should be a separate process for sure, hence why I was suggesting the use of Gaffer to do this, and possibly combine light-map baking there as well. The editor integration would possibly be just using the FileWatcher for intermediate WIP updates, but the final run-time would just compact it into a big fat package file + a page file that stores the hashes/offsets in a quadtree (which I think is how ID Tech 5 & probably 6 do things). The worker threads after the file is loaded would transcode on-the-fly to some GPU compression format (one of my branches integrates the ISPC texture compressor from Intel) or on mobile, the transcode would possibly be using straight ASTC wrapped in LZ4 compression to keep processing costs down.
