### ISSUE TITLE
Rename Model to Mesh

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1233]
Currently completely different types have similar names. Beginners can assume that StaticModel and AnimatedModel is childs of Model class. Class "Model" has no information about materials, so we can rename it to "Mesh" to clarify, that is different types. At the same time we can rename StaticModel to Model, because AnimatedModel is child StaticModel

```
    auto node1 = scene_->CreateChild();
    auto model1 = node_->CreateComponent<Model>();
    model1->SetMesh(cache->GetResource<Mesh>("Meshes/Mesh1.msh"));
    model1->SetMaterial(...);

    auto node2 = scene_->CreateChild();
    auto model2 = node_->CreateComponent<AnimatedModel>();
    model2->SetMesh(cache->GetResource<Mesh>("Meshes/Mesh2.msh"));
    model2->SetMaterial(...);
```

Of course it absolutely broken backward compatibility, but if the idea makes sense better to do it when community are still little

**Comment by cadaver** [comment]
To be honest, the Model / StaticModel / AnimatedModel terminology has felt somewhat shaky from as far back as it was first taken into use.

However I'm not sure if that rename would be the best way to go about it. 

Though there is no material information in the Model resource, it still contains information like the skeleton, bounds etc. which makes it more than just raw 3D geometry, which would typically called a Mesh. In some other engines a Model might consist from multiple Meshes, which are the renderables that each generate a draw call (Geometry in Urho terminology)

Renaming is certainly a possibility, but we just have to make sure we make the right rename :) Any other opinions?

**Comment by 1vanK** [comment]
It might be worth a look at the terminology used in other engines

**Comment by 1vanK** [comment]
Also, i think, we can rename AnimatedModel to SkinnedModel

**Comment by 1vanK** [comment]
AnimatedModel may contains Morph. I never used it earlier. Can the model be animated without bones?

**Comment by cadaver** [comment]
Yes, it's valid to point AnimatedModel to a model resource without bones and use e.g. only the morph feature. So in this sense AnimatedModel is more correct than SkinnedModel.

**Comment by JoshEngebretson** [comment]
I agree that Model(Resource) and StaticModel(Drawable) and AnimatedModel(Drawable) feel shaky to new users.  Though, renaming core classes shouldn't be taken lightly at this point, it affects more than the Urho3D repo and samples.  There are 311 forks!, language bindings, tools, games, scripts, etc that are affected by name changes.  This is different than prepending URHO3D_ on the front of macros for example.
  
I've been noodling on an alternative naming and haven't come up with anything better that describes their relationship, other than maybe qualifying Model as ModelResource, as this clearly defines that it isn't a base class of StaticModel/AnimationModel and would potentially allow the dropping of "Static" off StaticModel, which feels a bit weird:  Model, AnimatedModel, ModelResource

Though, this would wreck havoc with downstream projects again :)

**Comment by boberfly** [comment]
My take on it is that for things like skin and morph/blendshapes, these should go into their own thing like a deformer/modifier stack. Now I'm not sure if this should be perhaps a separate component or perhaps just a composition of the Model class itself (it just holds the deformer class or something). That way more than just morph/blend and skinning can be applied.

Now the next issue is composing this deformer/modifier stack into different backends, like for CPU, GPU (and if it's compute-based or XFB or just a standard vertex shader) and to make sure only CPU stuff is layered first and GPU stuff second for the most efficient pipelining (like the current CPUmorphtarget-to-GPUskin). This does have implications on the renderer code paths that kind of 'expect' skinned stuff to work in a certain way, and perhaps another reason to upgrade the vertex declaration code from a fixed layout (or leave as-is, as GPU compute or XFB deformation would just be updating a vertex buffer before it goes through the standard render pipe, pretending it's a 'static' mesh).

This was yet another pet project of mine for the backburner...

**Comment by 1vanK** [comment]
> ModelRes

I like this variant :)

**Comment by damu** [comment]
Good idea. StaticModel does also sound like a model that can't be moved. Like those static objects in physic engines. That was weird for me at first. Ogre uses the term Entity, which sounds pretty general (like "Thing"). ModelRes sounds like some kind of raw, internal ressource. What about BasicModel or SimpleModel or something like that?
Also there could be an alias (typedef) for backwards compatibility.
Model sounds like the base class of all models, changing that name would be good too.
Oh maybe Model -> ModelRes and StaticModel -> Model?

**Comment by MonkeyFirst** [comment]
Current names of components fine for me. 
I just curious what name need for StaticModel with ObjectIndex attr within vertexes data ? InstancedMeshes ?

>Model -> ModelRes
longest name - bad case) I think better just Model -> Mesh

**Comment by cadaver** [comment]
My view is that Model is a good and concise name, and describes the resource accurately. Changing it to Mesh while the drawable components retain the word Model doesn't help much.

One way would be to retain Model, and have the drawable components be e.g. ModelInstance, and AnimatedModelInstance, which describes that they're a rendered copy or instance of the model in the world. Though those are already longer to type than StaticModel & AnimatedModel.

**Comment by 1vanK** [comment]
I think that Model and ModelInstance correlated as Class and ClassInstance (unique object with type Class)

**Comment by damu** [comment]
Ah I see.
Instance is a bit weird for a class name and also kinda long.
What about StaticModel -> DrawableModel?
That also suggests that Model can't be drawn. AnimatedModel could keep like that as a non drawable but animated doesn't make much sense, same for Skybox.
Would also be aliasable without any pain.

**Comment by cadaver** [comment]
Yes, that's one option, though repeating the base class name seems a bit funny. Another possibility would be the Unity terminology e.g. ModelRenderer.

So far I'm a bit in the same boat as @JoshEngebretson, none of the options are so immediately appealing that I'd go for a rename right now, especially considering that it'd be a major compatibility break for downstream. But keep the options coming in case there are more :)

**Comment by damu** [comment]
Oh didn't think of Drawable, indeed kinda odd. ModelRenderer is flipped compared to other names, what about RenderedModel or SceneModel?
When doing a typedef StaticModel=Newname or vice versa there shouldn't be any compatibility break. The old name could get removed somewhere in the future.

**Comment by cadaver** [comment]
Typedef doesn't work for script where a string name is used to e.g. instantiate component. Same for serialization, so it would need inserting special-case code to handle the both names for a transition period.

**Comment by 1vanK** [comment]
what about

Model -> GeometryData
StaticModel -> Model

```
auto node = scene_->CreateChild();
auto model = node_->CreateComponent<Model>();
model->SetGeometryData(cache->GetResource<GeometryData>("Models/Model1.mdl"));
model->SetMaterial(...);
```

**Comment by 1vanK** [comment]
oh no, I forgot that there is a class Geometry

**Comment by damu** [comment]
Oh didn't think about scripting.
Angelscript seems to have typedefs too: http://www.angelcode.com/angelscript/sdk/docs/manual/doc_global_typedef.html
Couldn't find something about Lua. Would a "special code" be complicated or have disadvantages or would it be just like one line to define an alternate name?

Model could be also MeshData or something but the problem with StaticModel->Model is the big API change and meaning change for.Model.
StaticModel->VisualModel is also an option

**Comment by 1vanK** [comment]
ModelRenderer very good varian and corresponds to the component functions

**Comment by cadaver** [comment]
Yes, it may be the best option. Only downside is that it would be an exception in component naming, as for example BillboardSet isn't named BillboardRenderer. Well, if we seriously start renaming, that could be renamed too :)

**Comment by 1vanK** [comment]
I started renaming. What name to use? BillboardRenderer or BillboardSetRenderer ?

**Comment by 1vanK** [comment]
@damu, your opinion? )

**Comment by damu** [comment]
I think cadaver didn't actually suggest renaming BillboardSet now. Just that there are several names that could be better. The StaticModel and Model naming is actually confusing. BillboardSet is not that confusing but just possible inconsistent if there would be a ModelRenderer.
Just renaming one would be even more confusing. Also if those renamings are done, they would break all using code and require it to be updated, unless there would be aliases.
I think it would be best to collect all good renaming ideas and schedule them to bundle them with some other major update that requires the user to update their code anyway.

Is ModelRenderer generally the prefered name? What about SceneModel, RenderedModel, VisualModel, ...? ModelRenderer is confusing with the Renderer and does sound like a renderer for a model and not a renderable model.

**Comment by 1vanK** [comment]
In any case, the last word should be for Cadaver. So we can just close this issue if renaming brings more disadvantages than benefits :)

**Comment by cadaver** [comment]
I don't recommend acting on this just now or making a PR. So far it's been a rather small group of people discussing this, and it would be a rather major change to the API. We don't need to close this, but can keep this on a backburner and see if there's more input from others.

**Comment by 1vanK** [comment]
As practice shows, people are starting to take an interest and to criticize after the work is done :)

**Comment by rikorin** [comment]
I'm totally fine with the current names.

**Comment by 1vanK** [comment]
What about ModelComponent ?

**Comment by cadaver** [comment]
It's one more option, though it feels somewhat redundant to have Component in the class name, and unless other drawable classes would also get renamed, it would again stand out as an exception. The Unreal Engine does use xxxComponent in the drawable class names (for example LightComponent)

**Comment by 1vanK** [comment]
Or we can can use some short preffix for all components (like T for types in delphy): CmptModel

**Comment by weitjong** [comment]
Although I like all the Borland products (especially Turbo Pascal), I do not like its naming convention. I think I have seen enough of T-thingy in a life time. Although I must admit it will bring some sweet memory back too. Any good/decent IDE nowadays should be able to perform auto-complete and the really good one can even narrow down the possible choice based on the context of the code. So, typing a 'T' may already be already enough to find the class I want to use.

**Comment by rikorin** [comment]
Being an incredible perfectionist, hating things just because I don't like the way they look ( I hate Python just for the fact that I have to type "true" with capital T) I want to say only one thing: 
Leave. It. Alone.

**Comment by 1vanK** [comment]
Dont kill me pls :(

**Comment by hdunderscore** [comment]
Type prefixes like in UE4 look like code vomit to me... pls don't. I prefer namespaces.

**Comment by rikorin** [comment]
Аnd it's better to avoid abbreviations, unless absolutely necessary, as they look ugly too.

**Comment by weitjong** [comment]
> Dont kill me pls :(

Hahaha. You asked for it.

**Comment by Modanung** [comment]
I don't think the current naming is confusing at all. Or at least the least confusing.
Functionally in makes sense. Even though AnimatedModel and StaticModel are both components, they very much extend the Model resource, making it functional. I think by now we all know the difference. :)
