### ISSUE TITLE
Texture arrays

### ISSUE THREAD

**Issue by cadaver** [urho3d/Urho3D#1236]
Support texture arrays on GL3 and D3D11. This can either be built into the existing Texture3D class, or a new class be created. D3D9 rendering code cannot support this.

**Comment by reattiva** [comment]
Hello, several months ago I've done some work on texture arrays for DX11. However I started from D3D11TextureCube, the function SetLayers is used to set the number of layers after loading the XML then SetSize is called with layers=0 to create the array, so it is a bit ugly.
Here the header and the branch:
https://github.com/reattiva/Urho3D/blob/25dabf103db6bb9f646da276f1cd34ca1606b0c5/Source/Urho3D/Graphics/Direct3D11/D3D11Texture2DArray.h
https://github.com/reattiva/Urho3D/commits/texture_array
When you have some time, give a look to the header, if it resembles what you had in mind I can try to update it and add OpenGL.

**Comment by cadaver** [comment]
Thanks! This looks rather usable. "Layers 0 means unchanged" is a bit dirty, but I couldn't immediately think of a better way when setting from images.

**Comment by reattiva** [comment]
@cadaver, I have something working on OpenGL, but I have some doubts.

I was thinking to create the texture array and allocate its space in Create(), then upload the texture layers in SetData(..), however Urho does this differently.
In Create() only a not compressed texture is allocated (glTexImage2D) without data, then in SetData(level, x, y ...) it is reallocated again this time uploading the image. Why the double allocation for uncompressed images?
In SetData() if we are changing a whole mip map level (wholeLevel=true) the level is reallocated again with glTexImage2D. Can't we use glTexSubImage2D so we do only the upload? Is it related to how DX works?

On another topic, the function GetData(unsigned layer, unsigned level, void* dest) which downloads a single level of a layer, requires the function glGetTextureSubImage which is OpenGl 4.5, so for now it downloads all the layers, like Texture3D does, however the 'layer' argument becomes useless in OpenGL. 
I've read we could try to set a single layer with glFramebufferTextureLayer then reading it with glReadPixels, but have not tried, do you think it is worth it?

**Comment by cadaver** [comment]
Reallocating the mip level again when doing a full level update follows the same pattern as the vertex buffers / index buffers, which also do glBufferData() instead of glBufferSubData(). This might allow the driver to orphan the old data if it's still being used to render, to avoid a stall. However depending on the driver, this is only a theory and may not actually help.

Feel free to *not* do this same logic for texture arrays and only allocate in Create().

As for GetData() I would recommend avoiding glReadPixels(), as it messes with the currently bound framebuffers, and if it complicates the code. For now I'd say it's OK to just get all the layers.

**Comment by cadaver** [comment]
The pull request was merged, so this can soon be closed. Will just add a small chapter to documentation to mention Texture2DArray.

**Comment by cosmy1** [comment]
Lua still does not have bindings for it. Let me guess... The main issue is tolua++ which does not support compiler directives as Texture2DArray is not available on Direct3D9.

**Comment by cadaver** [comment]
Yes, I didn't know how to conditionally include a class for bindings generation. You should be able to load & assign texture array resources though. A crude solution would be to provide a dummy D3D9 implementation.
