### ISSUE TITLE
chaotic mouse movement

### ISSUE THREAD

**Issue by damu** [urho3d/Urho3D#1237]
The mouse is super chaotic after switching the cursor visibility or after entering the Urho window again. This bug is present in the newest GitHub version and 1.5.
Reproduce:
1. Start a sample like 23_Water 
2. Switch to another application (alt-tab)
3. Click in the Urho window again after moving the mouse so that it regains focus.
4. Camera moves abruptly/wildly immediately or when moving the mouse to rotate the camera.
System is Windows 7 with DirectX9 but I think at least Windows 10 was the same and OpenGL and DX11 too. I'm using MinGW.
I think I even saw code in Input.cpp (or similar) which looked like a fix but the issue is still there.

**Comment by hdunderscore** [comment]
I will soon post an update to my pull request, I'll ask you to try reproduce the error when it's ready: https://github.com/urho3d/Urho3D/pull/1207

**Comment by cadaver** [comment]
Do you have Aero on or off?

**Comment by damu** [comment]
On but it's the same with Aero off.

**Comment by cadaver** [comment]
I recommend debugging inside Urho & SDL event handling as the mouse moves after focusing Urho window again. The relevant function should be WIN_WindowProc in SDL_windowsevents.c. Does it hit some unusual codepaths which would e.g. discard the mouse move? I'm at loss as after fixing the bug I talked about above, I have not seen mouse move glitching.

**Comment by cadaver** [comment]
Also you can check the function WIN_WarpMouse() in SDL_windowsmouse.c by setting a breakpoint. Does it hit the return statement in the middle because of the two boolean flags being left erroneously on?

**Comment by damu** [comment]
This is tricky, not solved yet. Observations so far:
During the update function in the water sample: input->GetMousePosition() is returning good positions when focus or mouse hovers over the window and the last position if not. input->GetMouseMove() logically returns really high values when the abrupt turning happens (x>400 for example).

WIN_WarpMouse: is only called when having focus. data->in_title_click and data->in_modal_loop are always false.

WIN_WindowProc:
case WM_MOUSELEAVE is triggered and goes into all if's on loosing focus. 
case WM_INPUT: is never entered

SDL_SendMouseMotion ist always called

The events WM_ACTIVATE and WM_SETFOCUS are send when the window regains focus. Setting the last mouse position to the current one when this happens may help in that program switching issue.

I also just uploaded a video showing the issue: https://youtu.be/vUmcOCE3QGw
The weirdest thing is that the to high movement values seem to occur over multiple frames.
Any idea?

My "mode switch" code (when pressing tab) is:
if(GetSubsystem<Input>()->GetMouseMode()==MM_RELATIVE)
{
    GetSubsystem<Input>()->SetMouseMode(MM_ABSOLUTE);
    cursor->SetVisible(true);
}
else
{
    GetSubsystem<Input>()->SetMouseMode(MM_RELATIVE);
    cursor->SetVisible(false);
}

I tried setting lastMousePosition_=GetMousePosition(); in Input::SetMouseMode(MouseMode) but that didn't help at all (it seems).

**Comment by cadaver** [comment]
Ok, we can at least rule out the SDL booleans being in the wrong state. Can you record a video of the water sample bugging, where you do things very slowly?

**Comment by hdunderscore** [comment]
Looks to me like there is a link between the movement done while the window isn't in focus, and the direction of the chaotic behaviour when it gains focus (ie, mouse moved left while out of focus, the camera moves very quickly towards the left when focus is regained).

The movement seems to occur over a few frames which is also strange. damu mentioned in irc that flushing the sdl event queue didn't help. He also mentioned that this issue could be related: https://github.com/urho3d/Urho3D/issues/433 

Both in the previous issue and this one, mingw is used.

**Comment by cadaver** [comment]
Quick MinGW compile on Win7 and trying to alt-tab away then back didn't cause any mouse issues for me.

**Comment by damu** [comment]
> Can you record a video of the water sample bugging, where you do things very slowly? (and preferably annotate what you are doing in each stage)

Working on it, currently uploading...

> Looks to me like there is a link between the movement done while the window isn't in focus, and the direction of the chaotic behaviour when it gains focus (ie, mouse moved left while out of focus, the camera moves very quickly towards the left when focus is regained).

Yes that seems to be the case.

> Quick MinGW compile on Win7 and trying to alt-tab away then back didn't cause any mouse issues for me.

Huh? That's really weird. DirectX9? Recent Urho from GitHub? Did you move the mouse before alt-tab back into?

**Comment by damu** [comment]
There https://youtu.be/A7EnuixJYXQ. Hope that helps, that took a while to set up.
You can see how I move the mouse and hear when I press alt-tab.

**Comment by cadaver** [comment]
Current master and OpenGL, though I don't think the render API should make a difference.

**Comment by damu** [comment]
Huh. But you moved the mouse before going back into the Urho window?
Oh wait, WTF:
I just copied the water sample out of my virtual machine to test it on my Windows 7 host. No mouse issue there. There's also no issue with my mouse mode switching application. WTF VMware.
> _These many wasted hours have been sponsored by VMware Workstation Player 12_

It could still hint towards some input issue, but maybe it's really just a bug in the input system of the VM and unrelated to Urho or SDL.

**Comment by cadaver** [comment]
I also have badly behaving (unplayable) mouse in NinjaSnowWar or other hidden mouse Urho3D applications when I run in an Ubuntu VirtualBox. I suspect this is due to the mouse warping not being emulated correctly.
