### ISSUE TITLE
ToolTip: different mouse click, different behavior

### ISSUE THREAD

**Issue by horvatha4** [urho3d/Urho3D#1238]
I made a video from this, to clear see what is my problem.
https://youtu.be/wUSwNeDf_4U
At the bottom there are 12 Urho3D::UI::Button, and every Button have a ToolTip.
If I click a Urho3d::UI::Button with left mouse button then the ToolTip is not disappear (however its parent set to invisibile), but if I click with right mouse button then is functional as expected.
Some technical info:
The user can start commands with these Urho3D::UI::Buttons. Every 12 Urho3d::UI::Button is a child of an UIElement. These UIElements stored in a Vector container. After a click, the correct UIElement is set to visible and the others are set to invisible, so the Urho3D::UI::Buttons are changed properly.

`	...::RefreshTheIconLine()
	{
		for (int l = 0; l < 10; l++)
		{
			if(l == cmdMajor_) menuVector_[l]->SetVisible(true);
			else menuVector_[l]->SetVisible(false);
		}
	}
`

**Comment by cadaver** [comment]
Please check if the commit above fixed your issue.

**Comment by horvatha4** [comment]
Yes, it does! Problem fixed.
Thank you!
