### ISSUE TITLE
IntRect design issue

### ISSUE THREAD

**Issue by OvermindDL1** [urho3d/Urho3D#1241]
IntRect seems to return Height() as a negative number, it seems to be doing bottom_-top_ instead of what would be logical.  As these are ambiguous names anyway, why doesn't IntRect follow Rect where it has containing min_ and max_'s, so instead of doing myIntRect.bottom_=42 we would do myIntRect.min_.y=42 as that is unambiguous of which side should have the lower number.  Currently bottom_ has to have the higher number than what is in top_, which is backwards from the naming convention...

**Comment by cadaver** [comment]
IntRect is intended for 2D addressing of images or viewports where the origin is top-left, and the coordinates grow to bottom & right.

**Comment by OvermindDL1** [comment]
`min`/`max` like Rect would still make it explicit, I was using it as an integral rectangular container as its name implied, so it was surprising finding negatives.  ^.^

**Comment by 1vanK** [comment]
By the way, about IntRect...
In many engines (Unity, XNA) Rect is defined as (x, y, width, height) and often it is more convenient than (min, max). What determined the choice (min, max) ?

**Comment by 1vanK** [comment]
For example
```
<attribute name="Image Rect" value="160 32 176 48" />
```
It is strange, but right and bottom edges not belong to rectangle. 
```
<attribute name="Image Rect" value="160 32 16 16" />
```
looks more clear

**Comment by damu** [comment]
I stumbled over that attribute in xml as well. (x, y, width, height) is more common but min max or (x0,y0,x1,y1) his also sometimes used. Just a short moment of confusion, the usages made that pretty clear.
Also:
> IntRect is intended for 2D addressing of images or viewports where the origin (0,0) is top-left, and the coordinates grow to bottom & right.
This is the usual way and how I would always expect it. I've heard of the origin being sometimes in the bottom left but never used something that had that.

I'm writing a library with a struct rect{vec2 pos;vec2 size;}; (similar to {x,y,width,height})
Is there or would there be a technical/performance difference between {top,left,right,bottom} and {x,y,width,height} in the usage in Urho?
width() and height() are faster in the later case for example and the usage of the rect more straight forward (for me) and the reason I picked that in the system I mentioned over {top,left,right,bottom}, which I even had at first.

**Comment by cadaver** [comment]
If the bounds are defined by origin (in whatever corner) and size instead of min / max, merging points or other bounds becomes more complicated.

The original design reason for IntRect was actually closely mirroring Microsoft's RECT structure for D3D viewports and such.

**Comment by ffpwserver** [comment]
I think this definition may confuse me a little bit at beginning, but when I know the axis for the screen, everything is clear.
On screen, point(0,0) is the (left, top), and x axis points right, y axis points down. And define a Rect using two points is a usual way. the first one is smaller, another is bigger. So the (left, top, right, bottom) format is acceptable.
Take the game engine cocos2dx for example, in it's screen(known as Layer), point(0, 0) is the (left, bottom), so it's Rect definition looks like this Rect(left, bottom, right, top)  :)

**Comment by cadaver** [comment]
This is also the coordinate system of the UI subsystem, and also of textures when you *modify* the image data. However when sampling a texture in a shader, then 1 = top and 0 = bottom, which can be confusing. I believe this doesn't significantly benefit to change, so I'm closing this now.
