### ISSUE TITLE
DrawPhysicsGeomeotry bug when using two cameras?

### ISSUE THREAD

**Issue by ffpwserver** [urho3d/Urho3D#1244]
When I combined two samples together, 09_MultipleViewport && 12_PhysicsStressTest,
I found that when I toggle on DrawPhysicsGeomeotry, I cann't see the boundingbox of the boxes from the main camera, but when I turn around, I can see the green frame of boundingbox from the rear camera...So, is there anything I forget, or it's just a little bug?

**Comment by MonkeyFirst** [comment]
bug or it seam what debugWasEnabled variable does't  work very well.
so I fix EditorView.as (HandleEndViewRender)
line 2130 - debug.enabled = true; // fix issue with preview camera selection and debug render dissapears

**Comment by cadaver** [comment]
When physics world is debug drawn, it will use the camera last set in DebugRenderer to do culling of the debug geometry. With multiple viewports, it could happen that it actually has the small viewport's camera last set. You should be able to set the correct camera before drawing the geometry by calling DebugRenderer::SetView().

**Comment by cadaver** [comment]
Better solution: now you can call SetDrawDebug(false) on the secondary viewport to make sure it will not disturb DebugRenderer camera assignment or culling.
