### ISSUE TITLE
Spec EnvCube

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1246]
Env Cube is reflection of environment, so it should use specular map

```
#ifdef ENVCUBEMAP
    finalColor += cMatEnvMapColor * textureCube(sEnvCubeMap, reflect(vReflectionVec, normal)).rgb * specColor;
#endif
```

Also it allow to simulate metallic parts of model

![metal](https://cloud.githubusercontent.com/assets/13021826/13779014/636e77b2-ead2-11e5-9774-fc95a23193a2.png)

**Comment by cadaver** [comment]
I believe it depends on the look you want to achieve. The current Urho builtin shaders treat the environment mapping as a completely separate effect. Also, it's only evaluated in the base pass, not for lights.

**Comment by 1vanK** [comment]
Specular is blurred reflection of light source, env map - reflection of environment, so it is same physical parameter :) Besides, now there is no way to create a mask for Env Cube

**Comment by 1vanK** [comment]
> Also, it's only evaluated in the base pass, not for lights.
It works correct with and without light sources. Env Map is reflected light rays from environment

**Comment by MonkeyFirst** [comment]
And other case, the light what income from Cubemap into objects needs to be clipped by shadowTerm in per-pixel shader pass, in this case i found strange situation why cubemap are placed in ambient shader pass. Actually I don't know exactly but maybe the using cubemaps in ambient pass is right way.

**Comment by cadaver** [comment]
You could create a compile flag for the shader if you wanted, that way both behaviors would be possible.

**Comment by 1vanK** [comment]
small test (I used diff map as specular, so result not quite correct)
![2](https://cloud.githubusercontent.com/assets/13021826/13781445/c9ec9a28-eadc-11e5-9294-31d2a536bc8c.png)

I found only one problem - cubemap dont work in litbase pass, so technique should be without it

**Comment by MonkeyFirst** [comment]
I guess what per-pixel pass executed for all light sources that affect onto objects what currently rendered by shader. (additive lighting passes)
So in this situation we got some kind of "overfech" from cubemap texure.
I mean instead doing texture fetch in ambient pass and clipping it (cubemap) by shadow term we should doing the same work for every light sources but in per-pixel? So again, in this situation I guess it need use diff value (only shadow term) in ambient pass to avoid this unnecessary job by shader in per-pixel pass.

Is it able to get only shadow term in ambient pass in current master ?

**Comment by cadaver** [comment]
No. Urho doesn't calculate a shadow mask, instead each light pass calculates shadowing independently.

**Comment by 1vanK** [comment]
It also can considered power of ambient light for dynamically brightness

```
finalColor += cMatEnvMapColor * textureCube(sEnvCubeMap, reflect(vReflectionVec, normal)).rgb * specColor * cAmbientColor;
```

![2](https://cloud.githubusercontent.com/assets/13021826/13782001/c66e011e-eade-11e5-9c1d-0afc9142f9fc.png)
