### ISSUE TITLE
D3D9 and D3D11 Build Fails on Mingw-w64

### ISSUE THREAD

**Issue by JTippetts** [urho3d/Urho3D#1247]
I just updated to the latest revision for the first time in several months, and updated my CMake to the latest (to satisfy the recent bump to the minimum required version) and attempted a rebuild (Windows 7, Mingw-w64). Building fails for both D3D9 and D3D11, with the error "Could NOT find DirectX using MinGW default search paths (missing: D3D)"

Build window output here: http://pastebin.com/v36uH5Ar
CMakeOutput.log: http://pastebin.com/RKtq1yd4
CMakeError.log: http://pastebin.com/kxUqALT8

**Comment by damu** [comment]
Worked fine for me. Have you installed the Windows SDK? It includes the DirectX files which may be needed: https://dev.windows.com/en-us/downloads/windows-10-sdk

**Comment by weitjong** [comment]
Sorry to hear that. From my past experience MinGW as a software package tends to be different from version to version. It may be also different between its Windows and Linux offering. The revised FindDirectX.cmake module now expects to find one of the d3dcompiler_xx.lib in MinGW default lib search path. It does not look for the unversioned d3dcompiler.lib anymore. Now, this is fine for my MinGW-w64 on Linux. Could you quickly check your MinGW lib dir whether it just has d3dcompiler.lib but not the others, which is quite strange if it is true.

**Comment by weitjong** [comment]
Confirmed this is a bug. The MinGW on Windows host is indeed a different beast with MinGW on Linux host. I will push some tweaks to get it working again.

**Comment by JTippetts** [comment]
Thanks for looking into it, weitjong. Checking my mingw64\x86_64-w64-mingw32\lib folder, I can see multiple d3dcompiler_xx.a libraries, ranging from _33 to 47.

**Comment by weitjong** [comment]
The problem is with CMake. MinGW knows where its default header path and library path, but CMake does not. CMake only gets that correct when it is on Linux.
