### ISSUE TITLE
Stop specific sound types

### ISSUE THREAD

**Issue by Enhex** [urho3d/Urho3D#1250]
Urho can use the sound type system to stop specific sounds, instead of all sounds or manually selected sounds.
Use case: When opening a menu and the game pauses, pause in-game sound effects only, while still allowing music and UI sound effects.
Note it's important to pause and not mute, so if the game was stopped while playing a sound that sound will resume.

Possible approach:
Either replace `Audio::masterGain_` with a general sound type map (`Audio::soundTypes_`), or make a new map for stop sound types if there's any reason not to have a single map.

Functions:
```C++
Audio::Stop(const String& type);
Audio::Play(const String& type);
```
Could work like `Audio::SetMasterGain()`, iterating over the sound sources and updating them.

**Comment by 1vanK** [comment]
Something like tag?

**Comment by cadaver** [comment]
There are already the master volume types, which can be used here. I believe this will actually be quite easy to implement, Audio just needs to hold a map of which types of sounds are paused, and skip them in mixing.
