### ISSUE TITLE
CMake minor Error: DIRECTX_INCLUDE_DIRS notfound; mingw-w64; workaround

### ISSUE THREAD

**Issue by carnalis** [urho3d/Urho3D#1251]
cmake output:
```
[... found DirectX headers, found Urho3D target, found Doxygen]
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
DIRECTX_INCLUDE_DIRS (ADVANCED)
   used as include directory in directory urho
   used as include directory in directory urho/Source [...]
```
example cmake input:
```cmake -G "MinGW Makefiles" -D CMAKE_BUILD_TYPE=Debug -D CMAKE_CXX_FLAGS="-march=native" -D URHO3D_64BIT=1 -D URHO3D_ANGELSCRIPT=1 -D URHO3D_DOCS_QUIET=0 -D DOXYGEN_SKIP_DOT=1 -D URHO3D_LIB_TYPE=SHARED -D URHO3D_MKLINK=1 -D URHO3D_OPENGL=1 -D URHO3D_SAMPLES=0 -D URHO3D_URHO2D=0 -D URHO3D_LOGGING=1 -D URHO3D_TOOLS=0 "%SOURCE%"```

Workaround:
Define the value for cmake. I tried empty and default mingw-w64 headers are still found:
```cmake -G "MinGW Makefiles" -D DIRECTX_INCLUDE_DIRS=""```

**Comment by weitjong** [comment]
Thanks for reporting this. It is related to #1247.
