### ISSUE TITLE
SDL CMake wrong group entries

### ISSUE THREAD

**Issue by cosmy1** [urho3d/Urho3D#1257]
Some SDL entries are not inside SDL group.
As I don't have CMake knowledge, I don't know if this is fixable or necessary but ofcorse would be prettier. (Feel free to close this issue).

```
All VIDEO_*
ASSEMBLY
ASSERTIONS
DISKAUDIO
DUMMYAUDIO
FUSIONSOUND
LIBC
CLOCK_GETTIME
INPUT_TSLIB
```

I'm using CMake 3.4.0-rc1

![sdl_entries_cmake](https://cloud.githubusercontent.com/assets/1329119/13887311/5292df1c-ed3b-11e5-88d7-d6cfec234fa4.jpg)

**Comment by weitjong** [comment]
This is a known issue and has been documented in #1046. Anyone is welcome to help to fix this. We will probably fixing othet higher priority issues first.

**Comment by cosmy1** [comment]
Closing this as is already documented in #1046
