### ISSUE TITLE
Urho3D fails to grab the mouse cursor

### ISSUE THREAD

**Issue by rikorin** [urho3d/Urho3D#1258]
Start the 04_StaticScene sample (any sample would do, but there you can enjoy the camera going wild), sometimes the cursor won't be grabbed by the window. Tested on D3D11 and D3D9.

[Gif illustrating the issue](https://i.gyazo.com/f7cd1861b29e1649d5466fc90cdd4695.gif)

I believe that issue was introduced somewhere after 451f713a19ea654556c6cfd794be0b81016f5998, probably SDL update.

**Comment by cadaver** [comment]
I think this has been a known bug for a long time, at least if you move the mouse fast enough to "escape" the window in a single frame. The proper fix will be to use SDL's mouse capture facility, if it works now.

**Comment by rikorin** [comment]
It was working fine before I've pulled the recent code changes. It still works fine in my previous build. 
It happens even if you don't move the mouse. The cursor just won't jump to the center of the window anymore (not always). There are no problems with linux build though.

**Comment by cadaver** [comment]
I believe I see this now. It may be the same which was reported by 1vanK before (where it appeared to be the Windows VM as the culprit) if he was testing the SDL update branch early. It's SDL's internal variables

if (data->in_title_click || data->focus_click_pending) 

acting up on Windows and disabling a mouse warp. Since we are already taking measures to use warping responsibly (ie. require a click inside window first) it can be worth trying to just disable these checks.

**Comment by rikorin** [comment]
Commenting out that block of code totally solved the problem for me. 
I'm not sure about consequences, though. It feels a bit hacky. 
Anyway, that will do for now, thanks.

**Comment by hdunderscore** [comment]
Looks like we can try using some of the new SDL2.0.4 mouse functions to address this (eg, the global mouse warp doesn't have those checks), although I see that some of the new functions can fail if a platform doesn't support them. In that case this issue might crop up again.

I'll post a PR with the new mouse functions, and clean up the old todo's I've got in Input.cpp.

**Comment by cadaver** [comment]
Maybe we could get rid of our own mouse centering code completely and just use SDL's relative mouse mode, if it works now across Win/Linux/Mac? Anyway, I'll push the modification to check those variables already now. We can disable the mod if it is found to bring trouble later.

**Comment by hdunderscore** [comment]
It's like in emscripten though, the mouse is forced invisible:
https://wiki.libsdl.org/SDL_SetRelativeMouseMode

**Comment by hdunderscore** [comment]
Scratch that, forced mouse invisible should be ok.

**Comment by hdunderscore** [comment]
Here is an example of using the new SDL mouse options: https://github.com/hdunderscore/Urho3D/tree/input_globalmouse

I won't submit it as a PR though, as there are some issues in there that my other PR provides a better base to solve (same for the removal of the urho mouse centering code).
