### ISSUE TITLE
DebugHud/Profiler average and frame values are weird

### ISSUE THREAD

**Issue by damu** [urho3d/Urho3D#1260]
Something is wrong with the average and the frame values.
The frame value is always the same as average:  
![](http://i.imgur.com/Xautuy0.jpg)  
What is it supposed to display?
I'm optimizing a function and at first it looked like optimizing that function made other functions slower.
This is the normal version of ClearImage (Image::Clear): [http://i.imgur.com/Xautuy0.jpg](http://i.imgur.com/Xautuy0.jpg)
And this my optimized one: [http://i.imgur.com/rhRPt0m.jpg](http://i.imgur.com/rhRPt0m.jpg)
It looks like the optimization made SetTextureData (directly above ClearImage) much slower, which can't be. I'm just setting the bytes a bit differently. Also tried that outside Clear() and by measuring with my own timer, only the clearing gets much faster and SetTextureData does not change on a per call basis.

**Comment by damu** [comment]
Oh my own timer actually reported ~15ms for the unoptimized Clear() which fits to the ~15ms displayed in the profiler. It show something <1ms for the optimized one which also fits to the 0,678 in the profiler. So these values seem to be correct. But why is SetTextureData seemingly getting slower in the profiler but not in my own measure function? Could it be called multiple times outside my measurement due to the slightly different Clear()?

**Comment by weitjong** [comment]
Are using vsync which locks the engine at 60 frames per second?

**Comment by damu** [comment]
My driver was configured to always use VSync. When switching that off and also in Urho to off I get around 200FPS and the SetTextureData is below 0.6ms. As soon as Urho's or the drivers VSync is on the FPS are around 60 and SetTextureData 13-16ms.
Weird.

**Comment by weitjong** [comment]
Even 200 is an artificial cap. Try running with -nolimit and you could even get pass that with really simple scene. As for your SetTextureData thingy, I have no idea without looking into it deeper.

**Comment by damu** [comment]
With -nolimit the FPS are ~450 and SetTextureData is around 0.47 ms. Oh maybe a SetTextureData is measured as measure point before sleeping due to the FPS limit and the measurement of that point is only stopped in the next frame? So that the "FPS-wait" gets added to the SetTextureData time?

**Comment by cadaver** [comment]
The values are calculated as follows. There is a certain measurement interval, which is 1 second by default, so when a function is called once per frame, avg and frame (which really means avg per frame) end up being the same:

                float avg = block->intervalTime_ / block->intervalCount_;
                float max = block->intervalMaxTime_;
                float frame = block->intervalTime_ / intervalFrames;

where intervalTime would be the total time spent inside the function during the measurement interval.
So I believe there is no bug according to these rules. If you have a suggestion how it should work better, that's possible to incorporate however.

**Comment by damu** [comment]
What about the weird SetTextureData time? It depends on the strength of the FPS limitation it seems.
That function is also at least called once per frame.

**Comment by cadaver** [comment]
When you call the GPU driver to do something (render, update some resource) it may be that just that call causes the driver command queue to go full, in which case it will actually perform the render actions and stall for the time being. Or if the data you're modifying is still being used for rendering past frames.

**Comment by damu** [comment]
Ah, ok...  Doing that in different steps like E_BEGINFRAME didn't change anything.
I'm updating the Texture2D of a Sprite2D so I guess it's still used and stalls therefore? That's really unexpected, especially in the profiler, but kinda makes sense. Is there a better way to update a Texture2D with the CPU (if the size doesn't change)? I'm copying an image into it.

**Comment by cadaver** [comment]
Not really. In OpenGL glTexSubImage is practically your only option, and on the other hand I don't think the engine should be second-guessing the OpenGL driver and doing its own automatic doublebuffering, because that would use more GPU memory and could still end up being worse for performance.

Note also that the long update doesn't necessarily mean that your frame rate drops, because it may be that if the driver already stalls in the texture update, then the next Present() may be fast.
