### ISSUE TITLE
Serializable::SaveJSON dest.IsNull()

### ISSUE THREAD

**Issue by rikorin** [urho3d/Urho3D#1265]
I'm not sure if `if (dest.IsNull())` check is necessary in `bool Serializable::SaveJSON(JSONValue& dest) const`. It could be copied from SaveXML method by mistake. One has to assign a dummy object to the JSONFile root in order to use SaveJSON() method, because it returns false otherwise.
Also possibly code could be changed so that JSONFile acts more similarly to XMLFile, allowing to set the default node name.

**Comment by cadaver** [comment]
I remember tripping over this when testing the scene save as json; I already removed it from the derived classes. Should be safe to remove from everywhere.
