### ISSUE TITLE
SQLCompleteAsync not found in odbc32.dll on Win 7 64 bit SP1

### ISSUE THREAD

**Issue by lvshiling** [urho3d/Urho3D#1268]
we can fix it by add micro in nanodbc.cpp  

#ifdef _WIN32
    // needs to be included above sql.h for windows
    #define NOMINMAX
    #include <windows.h>
#endif

#define ODBCVER 0x0351
#define SQL_OV_ODBC3_80 3UL

#include <sql.h>
#include <sqlext.h>

FYI
https://github.com/lexicalunit/nanodbc/issues/56

**Comment by weitjong** [comment]
Thanks for your report but in this case I would agree with lexicalunit that hardcoding the defines in the source code is not the cleanest solution. Our current master branch already has the workaround logic mentioned by lexicalunit. So, if your app really does not use async call or that you are only targeting Win7 platform then you activate that workaround logic. Try to add this in your app main CMakeLists.txt

```
add_definitions (-DNANODBC_ODBC_VERSION SQL_OV_ODBC3)
```

**Comment by lvshiling** [comment]
I add below lines to Urho3d's CMakeLists.txt, still can not work, thanks.

add_definitions (-DNANODBC_ODBC_VERSION=SQL_OV_ODBC3)

# Setup SDK-like include dir in the build tree for building the Urho3D library
file (MAKE_DIRECTORY ${CMAKE_BINARY_DIR}/${DEST_INCLUDE_DIR}/ThirdParty)

# Urho3D source
add_subdirectory (Source)

# Urho3D documentation
add_subdirectory (Docs)

**Comment by weitjong** [comment]
My Win7 VM is corrupted at the moment, so I cannot help you much on Win7 problem now. However, I did a quick test on the suggested add_definitions() command on my Linux box, just to see whether this define would reach the nanodbc.cpp compilation unit and my test shows it will. In other words, I don't see why it did work for your case.
