### ISSUE TITLE
sincosf

### ISSUE THREAD

**Issue by gwald** [urho3d/Urho3D#1294]
Latest master of urho3D
Compiler: minGW TDM-GCC-32
WinXP with C::B
file urho3D/math/mathdefs.h:171
```

#ifndef __GNUC__
    sin = sinf(angleRadians);
    cos = cosf(angleRadians);
#else
    #ifdef __APPLE__
        __sincosf(angleRadians, &sin, &cos);
    #else
        sincosf(angleRadians, &sin, &cos);
    #endif
#endif

```
Error:  sincosf not defined in scope
Changed it to:
#if 1
it worked

Linux build works as is

I'm not that familiar with the code base

**Comment by cadaver** [comment]
Looks like we need a proper HAVE_SINCOSF test instead of using guesswork.

**Comment by cadaver** [comment]
Excellent, I was able to reproduce the bug with newest TDM-GCC. Though it seems using CMake's CheckFunctionExists is a minefield in cross-compiling cases.
