### ISSUE TITLE
option -DURHO3D_LIB_TYPE=SHARED is still reporting Build Shared Library: OFF

### ISSUE THREAD

**Issue by yushli** [urho3d/Urho3D#1296]
vs2015, win7, when running cmake_vs2015.bat -DURHO3D_LIB_TYPE=SHARED, it still reports:

--  Build Shared Library: OFF
--  Build Static Library: ON

**Comment by weitjong** [comment]
That message was from SDL library. All our 3rd-party libraries are built as static, regardless of the URHO3D_LIB_TYPE build option. That build option only controls the library type of Urho3D library.
