### ISSUE TITLE
Cmake GUI Error Configuring build for Mingw-w64

### ISSUE THREAD

**Issue by BlueMagnificent** [urho3d/Urho3D#1302]
Trying to configure for build using Cmake(3.5.1) and Mingw-w64 (5.3.0) with OpenGL chosen gives the below error
```
CMake Error at CMake/Modules/FindDirectX.cmake:78 (file):
  file STRINGS file
  "C:/Urho3D_Build/Urho3D_Git_Build/find_mingw_sysroot_output" cannot be
  read.
Call Stack (most recent call first):
  CMake/Modules/Urho3D-CMake-common.cmake:481 (find_package)
  CMakeLists.txt:50 (include)


CMake Error at CMake/Modules/FindDirectX.cmake:84 (message):
  Could not find MinGW system root.  Use MINGW_SYSROOT environment variable
  or build option to specify the location of system root.
Call Stack (most recent call first):
  CMake/Modules/Urho3D-CMake-common.cmake:481 (find_package)
  CMakeLists.txt:50 (include)
```

I feel this is related to #1247 and #1251 .

**Comment by weitjong** [comment]
Try to provide the MINGW_SYSROOT yourself via build option or environment variable. Or troubleshoot it yourself. Things that you could do:
1. Remove the ERROR_QUIET in the execute_process() command.
2. View the content of the C:/Urho3D_Build/Urho3D_Git_Build/find_mingw_sysroot_output after it has been generated.
From the error, it looks like it had failed to generate the output file. However, I am not able to see why. The issues that you mentioned above are already considered as close.

**Comment by BlueMagnificent** [comment]
For the option 2, C:/Urho3D_Build/Urho3D_Git_Build/find_mingw_sysroot_output was not generated and that even got me more confused. I would try providing MINGW_SYSROOT aas a build option to see if it passes

**Comment by weitjong** [comment]
You are not the one that is confused.
```
execute_process (COMMAND ${CMAKE_COMMAND} -E echo "#include <_mingw.h>" COMMAND ${CMAKE_C_COMPILER} -E -M - OUTPUT_FILE find_mingw_sysroot_output ERROR_QUIET)
file (STRINGS ${CMAKE_BINARY_DIR}/find_mingw_sysroot_output MINGW_SYSROOT REGEX _mingw\\.h)
```
Your error message "file STRINGS ..... could not be read" indicates the output file was not being generated. But the output file should be generated by another CMake command just above it. I have tested numerous error conditions but even at the worse case it should generate an empty output file. In my quick test, the CMAKE_C_COMPILER has a valid value. Since you did not paste the whole log file from CMake, I suspect the error actually happened somewhere else first. Did CMake really detect your MinGW compiler toolchain?

**Comment by BlueMagnificent** [comment]
Yeah CMake detected my MinGW compiler. Below is the output of the CMake configuration process
```
The C compiler identification is GNU 5.3.0
The CXX compiler identification is GNU 5.3.0
Check for working C compiler: C:/MinGW/i686-5.3.0-posix-dwarf-rt_v4-rev0/mingw32/bin/gcc.exe
Check for working C compiler: C:/MinGW/i686-5.3.0-posix-dwarf-rt_v4-rev0/mingw32/bin/gcc.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: C:/MinGW/i686-5.3.0-posix-dwarf-rt_v4-rev0/mingw32/bin/g++.exe
Check for working CXX compiler: C:/MinGW/i686-5.3.0-posix-dwarf-rt_v4-rev0/mingw32/bin/g++.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
CMake Warning at CMake/Modules/Urho3D-CMake-common.cmake:106 (message):
  Could not use MKLINK to setup symbolic links as this Windows user account
  does not have the privilege to do so.  When MKLINK is not available then
  the build system will fallback to use file/directory copy of the library
  headers from source tree to build tree.  In order to prevent stale headers
  being used in the build, this file/directory copy will be redone also as a
  post-build step for each library targets.  This may slow down the build
  unnecessarily or even cause other unforseen issues due to incomplete or
  stale headers in the build tree.  Request your Windows Administrator to
  grant your user account to have privilege to create symlink via MKLINK
  command.  You are NOT advised to use the Administrator account directly to
  generate build tree in all cases.
Call Stack (most recent call first):
  CMakeLists.txt:50 (include)


CMake Error at CMake/Modules/FindDirectX.cmake:78 (file):
  file STRINGS file
  "C:/Urho3D_Build/Urho3D_Git_Build/find_mingw_sysroot_output" cannot be
  read.
Call Stack (most recent call first):
  CMake/Modules/Urho3D-CMake-common.cmake:481 (find_package)
  CMakeLists.txt:50 (include)


CMake Error at CMake/Modules/FindDirectX.cmake:84 (message):
  Could not find MinGW system root.  Use MINGW_SYSROOT environment variable
  or build option to specify the location of system root.
Call Stack (most recent call first):
  CMake/Modules/Urho3D-CMake-common.cmake:481 (find_package)
  CMakeLists.txt:50 (include)


Configuring incomplete, errors occurred!
See also "C:/Urho3D_Build/Urho3D_Git_Build/CMakeFiles/CMakeOutput.log".
```

**Comment by weitjong** [comment]
This is really strange. What command "shell" were you using? cmd.exe or something else?

Assuming MinGW GCC is in your path, could you try this in the "shell":
```
echo "#include <_mingw.h>" |gcc -E -M - >find_mingw_sysroot_output
```
See if you could get the output file or any error instead.

I understand if you probably don't have time for this. In that case then just use initialize the MINGW_SYSROOT manually and forget about this.

**Comment by damu** [comment]
I have also MinGW 64 5.3.0 and for me setting the sysroot worked.
That shell command results in a file with
```
-: 
```
in it.
Have you properly set the variable and restarted CMake (or your whole system to be sure)?
You can test with:
```
C:\Users\gawag>echo %MINGW_SYSROOT%
C:\mingw-w64\x86_64-5.3.0-posix-seh-rt_v4-rev0\mingw64
```
You could also test:
```
C:\Users\gawag>%MINGW_SYSROOT%/bin/g++ -v
Using built-in specs.
[...]
gcc version 5.3.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project)
```

**Comment by BlueMagnificent** [comment]
My bad... sorry for the unnecessary confusion caused. It turned out that the problem was from CMake GUI which was what I used to configure. I used the CLI and it went well without the need to set MINGW_SYSROOT. The GUI still fails with MINGW_SYSROOT set but I'll stick with the CLI for now

**Comment by damu** [comment]
I'm also using the GUI. Have you restarted the GUI after setting or changing the sysroot variable? I have to do that so that it gets the new value. Maybe try rebuilding/deleting the cache if that doesn't work right away. Does it work with that?

**Comment by weitjong** [comment]
I too think this has nothing to do with the interface. Whether CLI or GUI, Cmake is Cmake. There is nothing change fundamentally. Our CMakeLists.txt also should function equally in either interface now. So, closing this now.
