### ISSUE TITLE
Occluder sorting improvement

### ISSUE THREAD

**Issue by Enhex** [urho3d/Urho3D#1305]
Virtually no triangles limit (optimal):
![sb5rflb](https://cloud.githubusercontent.com/assets/7088062/14252941/2a9a2358-fa92-11e5-8a69-4f56f015ab73.jpg)

Default triangle limit with current sorting:
![kdufonc](https://cloud.githubusercontent.com/assets/7088062/14252958/41a115fc-fa92-11e5-95b4-a9478de36206.jpg)

## changes
**Triangle density** instead of triangle count, as an heuristic for the average triangle size.

Prioritize occluders which the camera is inside their AABB.
**When inside occluder's AABB:**
**"0" distance:** (use the camera's near clip distance to avoid dividing by 0)
Inside the start room (inside AABB?)
![thoq9zl](https://cloud.githubusercontent.com/assets/7088062/14253676/2294da4c-fa95-11e5-917d-49e01e56a07a.jpg)
Next to a wall (outside AABB?)
![mduay1l](https://cloud.githubusercontent.com/assets/7088062/14253690/26f67a78-fa95-11e5-8efa-3f663963d4e7.png)

**AABB's diagonal size^2:**
Inside the start room (inside AABB?)
![fugamvj](https://cloud.githubusercontent.com/assets/7088062/14253697/2f7bb3d4-fa95-11e5-8c8c-7848cc52e7ec.jpg)
Next to a wall (outside AABB?)
![boumsbr](https://cloud.githubusercontent.com/assets/7088062/14253701/3326c1f4-fa95-11e5-9ef8-2f6f86c7bd7a.jpg)

size^2 seems to be better in general. An occluder which is near the camera will pretty much always be used.

It still doesn't handle medium/far occluders very well in my case, but that might just be the way my geometry is setup.

# Code
If license info is required, MIT license.
New version of View::UpdateOccluders(): (Note: remove the "0" distance commented part)
```C++
void View::UpdateOccluders(PODVector<Drawable*>& occluders, Camera* camera)
{
    float occluderSizeThreshold_ = renderer_->GetOccluderSizeThreshold();
    float halfViewSize = camera->GetHalfViewSize();
    float invOrthoSize = 1.0f / camera->GetOrthoSize();

    for (PODVector<Drawable*>::Iterator i = occluders.Begin(); i != occluders.End();)
    {
        Drawable* occluder = *i;
        bool erase = false;

        if (!occluder->IsInView(frame_, true))
            occluder->UpdateBatches(frame_);

        // Check occluder's draw distance (in main camera view)
        float maxDistance = occluder->GetDrawDistance();
        if (maxDistance <= 0.0f || occluder->GetDistance() <= maxDistance)
        {
            // Check that occluder is big enough on the screen
            const BoundingBox& box = occluder->GetWorldBoundingBox();
            float diagonal = box.Size().Length();
            float compare;
			if (!camera->IsOrthographic())
			{
				// Occluders which are near the camera are more useful then occluders at the end of the camera's draw distance
				float cameraMaxDistanceFraction = occluder->GetDistance() / camera->GetFarClip();
				compare = diagonal * halfViewSize / (occluder->GetDistance() * cameraMaxDistanceFraction);

				// Give higher priority to occluders which the camera is inside their AABB
				const Vector3& cameraPos = camera->GetNode() ? camera->GetNode()->GetWorldPosition() : Vector3::ZERO;
				if (box.IsInside(cameraPos))
					compare *= diagonal;	// size^2
					//compare = diagonal * halfViewSize / camera->GetNearClip();	// "0" distance. Only left in for reference, should be removed
			}
			else
				compare = diagonal * invOrthoSize;

			if (compare < occluderSizeThreshold_)
				erase = true;
			else
			{
				// Best occluders have big triangles (low density)
				auto density = occluder->GetNumOccluderTriangles() / diagonal;
				// Lower value is higher priority
				occluder->SetSortValue(density / compare);
			}
        }
        else
            erase = true;

        if (erase)
            i = occluders.Erase(i);
        else
            ++i;
    }

    // Sort occluders so that if triangle budget is exceeded, best occluders have been drawn
    if (occluders.Size())
        Sort(occluders.Begin(), occluders.End(), CompareDrawables);
}
```

**Comment by cadaver** [comment]
Thanks for the improvement. When submitting code to Urho, the idea is that the existing Urho license is applied to it and the submitter should be okay with that, or not submit the code, so it's not necessary to state the license.

http://urho3d.github.io/documentation/HEAD/_contribution_checklist.html
