### ISSUE TITLE
Error in Log.cpp - Array index out of bounds

### ISSUE THREAD

**Issue by warzes** [urho3d/Urho3D#1307]
```
void Log::Write(int level, const String& message)
{
...
String formattedMessage = logLevelPrefixes[level];
...
}
```

Log::Write(LOG_RAW, "blablabla"); // Array index out of bounds - LOG_RAW = -1

Log.h
`static const int LOG_RAW = -1;`

**Comment by 1vanK** [comment]
#define URHO3D_LOGRAW(message) Urho3D::Log::WriteRaw(message)

**Comment by weitjong** [comment]
Still, I think in this case the Log::Write() could reroute to Log::WriteRaw() or at the very least do an assert to tell the developer about the programming error instead of throwing index out of bounds during runtime.

**Comment by weitjong** [comment]
Just got time to double check the code. The assert is already there. So, IMHO, this is a pure developer error.

**Comment by cadaver** [comment]
The check for the LOG_RAW level doesn't cost much, so I added it in any case. Also prevents crashing / asserting the player from script using that function.
