### ISSUE TITLE
Consider phasing out D3D9?

### ISSUE THREAD

**Issue by JTippetts** [urho3d/Urho3D#1308]
With the recent texture array commits, a divergence has been created between the render system branches, with D3D9 unable to support arrays. This has caused an issue with the Lua bindings. I think it might be simpler going forward to simply phase out D3D9 support altogether. Thoughts?

**Comment by damu** [comment]
One idea to "fix" the texture array issue was to give DirectX9 a "dummy" Texture2DArray that doesn't do anything.
Texture arrays are a pretty major thing especially for terrain. I guess at least most of my project ideas would need that and I could live without DX9.
Are there maybe still some Windows XP users who need DX9?
Are there other non-DX9 things already in Urho or planned? Like geometry shaders? That would raise the same question. Also without DX9 we could make samples using Non-DX9 stuff without having to make special stuff for DX9 or not building those samples when Urho with DX9 is build.

**Comment by boberfly** [comment]
There's still a huge market of Windows XP + DX9 users, particularly in China. Having said that, they typically do have DX10-level GPUs and drivers with GL 3.x support, but they might be using Intel chipsets which I think would have inferior GL drivers, if you were to target a casual game.

TBH I think GL 3.x/DX10 is a good lowest common denominator, and GL ES 2.0 for mobile. Also do note that GL ES 2.0 doesn't support texture arrays either.

**Comment by boberfly** [comment]
I had another think, I'm all for phasing out DX9 if it's a maintenance burden. If anyone really wants to target WinXP users with bad GL drivers on Intel for a casual game, they could just muck around with ANGLE and treat the platform like you would for mobile or WebGL, sure performance would suffer a bit compared to a native DX9 port, but who cares? :)

**Comment by cadaver** [comment]
The Texture2DArray is not really a problem, as like @damu says it can just be given a dummy implementation that doesn't actually work. This is the same as Texture3D with OpenGL ES.

D3D9 is arguably the most reliable of Urho's render APIs, as there are no gotcha's like "draw fails if shader references elements not in the vertex stream" (D3D11), so I wouldn't want to drop it lightly. Of course if there is suddenly a large influx of features that are incompatible then I would reconsider.

**Comment by cadaver** [comment]
Lua binding for Texture2DArray is now in.

**Comment by cadaver** [comment]
Will close this, not going to remove at the moment. This can be returned to later when necessary.
