### ISSUE TITLE
DropDownList does not Serialize properly

### ISSUE THREAD

**Issue by Quibilia** [urho3d/Urho3D#1310]
Following the call stack, it seems to be an issue with the scroll panel object in the DropDownList class. I cannot get the class to save to an XML file.

My log is as follows:
[Tue Apr 05 17:32:46 2016] INFO: Opened log file Data/HopesLog.log
[Tue Apr 05 17:32:46 2016] INFO: Created 1 worker thread
[Tue Apr 05 17:32:46 2016] INFO: Added resource path Data/
[Tue Apr 05 17:32:46 2016] INFO: Added resource path CoreData/
[Tue Apr 05 17:32:47 2016] INFO: Set screen mode 800x600 windowed resizable
[Tue Apr 05 17:32:47 2016] INFO: Initialized input
[Tue Apr 05 17:32:47 2016] INFO: Initialized user interface
[Tue Apr 05 17:32:47 2016] INFO: Initialized renderer
[Tue Apr 05 17:32:47 2016] INFO: Set audio mode 44100 Hz stereo interpolated
[Tue Apr 05 17:32:47 2016] INFO: Initialized engine
[Tue Apr 05 17:32:47 2016] ERROR: Could not remove popup implicit attributes

**Comment by weitjong** [comment]
I am not able to reproduce your issue. Please provide the steps on how to reproduce it.

**Comment by Quibilia** [comment]
main.cpp:
`	Urho3D::Text* tItem = new Urho3D::Text(context_);
	tItem->SetText("Hello");
	tItem->SetVisible(true);
	tItem->SetEnabled(true);

	((Urho3D::DropDownList*)(context_->GetSubsystem<Urho3D::UI>()->GetRoot()->GetChild(Urho3D::String("MenuNewGame"))->GetChild(Urho3D::String("OptionGameType"))))->AddChild(sView);`

Layout.xml:
`	<element type="DropDownList" style="DropDownList">
		<attribute name="Name" value="OptionGameType" />
		<attribute name="Size" value="300 25" />
		<attribute name="Position" value="400 200" />
		<attribute name="Is Enabled" value="true" />
	</element>`

**Comment by weitjong** [comment]
With all due respect but I don't think that will help. You can test the saving/loading of drop down list in the editor. Thd editor uses the same code in the game engine. If it works there then there is nothing wrong with the engine code but in your own. The part that you posted looks incomplete to me, so this is if course just my guess.

**Comment by Quibilia** [comment]
I think I've figured it out on my own, and it appears to either be an issue with the way my compiler is reading it, or the engine:

DropDownList.cpp:
```
// ListView
    XMLElement childElem = dest.GetChild("element");
    if (!childElem)
        return false;
    if (!listView_->FilterAttributes(childElem))
        return false;
    if (childElem.GetAttribute("style").Empty() && !childElem.SetAttribute("style", "none"))
        return false;
    if (!RemoveChildXML(childElem, "Focus Mode", "NotFocusable"))
        return false;
    if (!RemoveChildXML(childElem, "Auto Show/Hide Scrollbars", "false"))
        return false;

    // Horizontal scroll bar
    childElem = childElem.GetChild("element");
    if (childElem && !childElem.GetParent().RemoveChild(childElem))
        return false;

    // Vertical scroll bar
    childElem = childElem.GetNext("element");
    if (childElem && !childElem.GetParent().RemoveChild(childElem))
        return false;

    // Scroll panel
    childElem = childElem.GetNext("element");
    if (!childElem)
        return false;
    if (childElem.GetAttribute("style").Empty() && !childElem.SetAttribute("style", "none"))
        return false;
```

childElem.GetNext("element") becomes null once the element is removed from its parent. Therefore, the call to childElem.GetParent().RemoveChild(childElem) is setting the previous and next siblings to null pointers.

Again, this might be working on your end, because I've had problems with MSVC before. In any case, I will try modifying the code to fix it.

**Comment by weitjong** [comment]
If you say so. However, usually we don't have such problem with MSVC compiler. If we do then I am not sure how anyone could do cross-platform development with MSVC.

**Comment by cadaver** [comment]
@Quibilia Are you looking at an old version of the engine? In master branch head revision the code has been changed to not GetNext() from a potentially removed element. Generally, we don't backport fixes and issues should be reported only when they also occur on the master branch head revision, or risk being already fixed duplicates.

**Comment by Quibilia** [comment]
@cadaver Actually, I'm using the 1.5 release. With regard to the master branch, that *is* a bit behind, I suppose...
