### ISSUE TITLE
Gitter integration

### ISSUE THREAD

**Issue by cosmy1** [urho3d/Urho3D#1316]
Hello,

There is a cool extension for GitHub that create chat rooms for single projects.
Someone from the Urho3D organization can create a chat room?
It looks like IRC service but updated and directly integrated with GitHub account :smiley: 

Here is the link:
https://gitter.im/

It also have a badger like Travis CI / AppVeyor one.

**Comment by HeadClot** [comment]
+1 for gitter support

**Comment by ffpwserver** [comment]
+1 for gitter support

**Comment by hdunderscore** [comment]
Any opposition?

**Comment by 1vanK** [comment]
As far as I understand it is a chat room? History of messages is stored? On githabe discussion of each problem separately from other discussions. It is very convenient to find out why it was decided any decision.

**Comment by weitjong** [comment]
Abstain.

**Comment by cadaver** [comment]
I would likely not visit; to me it's mostly the same if this is added or not, but does it need moderation? That would be an additional burden. I believe discussion on issues should kept in the issue tracker.

**Comment by cosmy1** [comment]
Yes issues should be kept here but its mostly a way to talk about future plans or maybe ideas or just helping someone without heading forums. Its a sort of forum+issue tracker+irc channel all in one.
Alot of projects is using it, to name a few: angular.js, bootstrap, bgfx, xenko game engine, etc..
Personally I think its an interesting addition as GitHub doesn't provide any chat system or private messaging.

**Comment by rikorin** [comment]
Chat rooms are for losers :3

**Comment by 1vanK** [comment]
@rikorin I do not quite understand, are you for or against? xD

**Comment by rikorin** [comment]
Ha ha, no, I was saying that chat rooms are horrible waste of time and I can't approve that.

**Comment by OvermindDL1** [comment]
No moderation needed.  Gitter is mostly a single place to receive Github notifications, travis updates, and communicate via a shared channel.  I use it fairly extensively with many projects and it is quite useful.  It has an IRC bouncer too if you want to connect via an IRC client as well.

**Comment by hdunderscore** [comment]
Since there wasn't opposition, I went ahead with it. I think it should be ok, and compared to the irc channel a few of us use we should have the ability to moderate on gitter should anything get out of hand.

**Comment by cadaver** [comment]
Revisiting this. Are there Urho developers actively using the gitter chat anymore? The last discussion appears to be from end of November. If not, perhaps it would be better to close the chat down so that people don't attempt to communicate on an unused channel, while the forums & issue tracker are certainly being actively monitored.

**Comment by cosmy1** [comment]
Feel free to close it.
