### ISSUE TITLE
light flickering and micro freeze

### ISSUE THREAD

**Issue by MonkeyFirst** [urho3d/Urho3D#1323]
I found an strange light behavior, when camera look down into floor.
in this video I'm trying demonstrate this issue. 
https://youtu.be/iT5iVV6rJoM
But in same time when light start flickering i have a micro-freezes(when I try to rotate around), but after some time they gone and light just flickering. So that is this may be?

on debug hud parameters you may see: what light count not change (at bug moment), but shadow map count changes

**Comment by cadaver** [comment]
This can be some kind of culling or math inaccuracy issue related to rendering view preparation. I believe I've seen something similar when working with tundra-urho3d project, where we had a test scene with a lot of shadowed spotlights.

Can you supply a test scene which reproduces this issue. Also, what renderpath, what graphics API?

**Comment by MonkeyFirst** [comment]
I think I found potential bug generator for this issue. I turn light component to defaults setting, and again increase range and brightness multiplier for light and after this all works fine. but if I change CSM splits say for 10-20-30-0 I got same bug with flickering as before. I suppose what point light type ignore CSM splits setting (only used by directional), so this test says what actually - no :)  

>Also, what renderpath, what graphics API?
Deferred.xml
OpenGL

**Comment by cadaver** [comment]
This sounds suspicious, as the shadow cascade parameters should only be actually used by directional lights. Particularly it shouldn't be anything that causes issues depending on camera angle or position, since those parameters aren't changing.

But a test scene that exhibits this issue is better than speculation :)

**Comment by MonkeyFirst** [comment]
Yes, you are right because I found a real reason (I guess). 
Actually I forgot turn-off "use clipping" option of camera component. Before this test I play with it.
So I'm sorry for this. I think it may be closed now.  
if test scene still needed it here is (with clipping) https://github.com/MonkeyFirst/files

**Comment by cadaver** [comment]
Thanks for the clarification and the files. In theory clipping shouldn't affect lights differently (the geometry should also be clipped) so it's worth checking if there's an actual engine bug.
