### ISSUE TITLE
TmxFile using deprecated file format

### ISSUE THREAD

**Issue by Layoric** [urho3d/Urho3D#1325]
The TmxFile loading implementation is using uncompressed XML and was [officially deprecated](http://forum.mapeditor.org/t/tiled-0-15-0-released/1001) by @bjorn in January. This means any maps saved with version 0.15.0+ will not load. 

This was also [mentioned in a PR](https://github.com/urho3d/Urho3D/pull/641#issuecomment-106905685) and suggested to support an alternate format, preferably the default of the latest version as Tiled is getting closer to 1.0.

**Comment by bjorn** [comment]
Thanks for opening an issue about this. It's something I had actually wanted to open a pull request for myself, but so far I've been simply too busy.

I'm still undecided whether the default should be CSV or zlib compressed data. It's a choice between either the easiest format to understand and work with, or the most efficient storage format. As it is I think CSV is the default.

Of course ideally Urho3D would support both storage methods regardless.

**Comment by Layoric** [comment]
@bjorn No worries! Given CSV is an improvement on the deprecated format, the simplest and the default it would make sense to support that first to at least give devs a default happy path of create map in tiled -> save -> Load in Urho and for it to actually work. Currently only logs an error and returns null. 

I'm still learning Urho, but I'll try to find some time to have a crack at CSV support given that will be simpler and won't require including/importing zlib support. Thanks for replying and thanks for continued work on Tiled :+1:
