### ISSUE TITLE
Some file keep building even when no changes happen (MinGW)

### ISSUE THREAD

**Issue by ucupumar** [urho3d/Urho3D#1330]
When I'm building Urho from source, some files are keep building even when I don't change anything. This is really annoying when I just want to run or debug my build, it can take up to 3:50 minutes on my PC. I don't remember when this happen, I think it was since last week or something.

Do anyone know about this problem?

Screenshot of my building process:
![build_bug](https://cloud.githubusercontent.com/assets/5253453/14632639/0b0fd308-0644-11e6-972c-de723bb452c5.png)
As you can see, the problem lies on OggVorbisSoundstream.cpp, Sound.cpp, Image.cpp, and RampGenerator.cpp

**Comment by weitjong** [comment]
Those source files appear to be random. Are you using MKLINK? If you are not then there is possibility something is wrong with your build tree, more specifically with its post-build steps. In theory it should not copy anything back from source tree to build tree when there are nothing change. But if it mistakenly does so for some reasons then you can expect the rebuild to happen again.

Also, have you tried to regenerate your build tree?

**Comment by ucupumar** [comment]
No, I don't use MKLINK. I actually don't know how to use it. MKLINK warning is always appear even when I generate project as administrator. 

I tried to clone fresh master again just in case I messed up with something, but this issue is still happens on same source files. Have any idea?

**Comment by ucupumar** [comment]
Anyway, I use MinGW 4.9.2 32-bit

**Comment by weitjong** [comment]
I am sorry to hear that. My Win10 and Win7 VM both have MKLINK setup, so I am afraid I could not help you to reproduce your issue here.

**Comment by ucupumar** [comment]
After hours of trying, finally I can get MKLINK to work on my machine. Fortunately, the problem was gone too. So the problem only appears when MKLINK is not used. Is it still count as bug or not?

**Comment by weitjong** [comment]
I have labelled it as bug last night since from comment it sounded like at least it is reproducible on your side (using a new source tree and presumably using a new build tree as well). Now, whether it would be fixed is another question. Personally I would not setup an environment just to reproduce this. The warning message in the fallback mode is there for a good reason.

**Comment by weitjong** [comment]
Do not get me wrong. Of course it will be welcome if you can figure out what went wrong and submit the fix as PR.

**Comment by ucupumar** [comment]
Let see what can I do. I'm not really familiar with CMake or any build system, so it might take a while if me the one who actually fix this.

**Comment by weitjong** [comment]
I found a way to reproduce this bug using my existing Windows build environment. The problem started to happen after the STB version upgrade. Those cpp files you mentioned all have preprocessor to include STB header.

**Comment by weitjong** [comment]
Please try again. The build configuration has been changed to use file symlink as oppose to directory symlink. Thus, when in fallback mode, it is now a ```copy_if_different``` operation as oppose to ```copy_directory```. The former has the desired behavior where it only copies and touches the file timestamp only when it is absolutely necessary.

**Comment by ucupumar** [comment]
Thank you! Seeing your changes, I don't think I can fix this kind of bug myself, lol.
Btw, I already tried and I can confirm the problem is now really gone. :+1:
