### ISSUE TITLE
Area Lights (new paper/code released)

### ISSUE THREAD

**Issue by boberfly** [urho3d/Urho3D#1334]
Hi all,

This recently got announced:
[Real-Time Polygonal-Light Shading with Linearly Transformed Cosines](https://eheitzresearch.wordpress.com/415-2/)

This could go well with the new PBR merge, and there's source code based on BGFX there.

**Comment by hdunderscore** [comment]
Very nice result, and seems quite flexible. I'd love to see that implemented in urho. I couldn't guess how difficult it would be to implement though.

It's also worth investigating other simpler area lights like the representative point area lights Epic described.

**Comment by Modanung** [comment]
That looks amazing.

**Comment by dragonCASTjosh** [comment]
I was looking into this to finish up the work on a full PBR renderer. upcoming changes will include this technique along with rewritten PBR render paths to improve overall quality and hopefully bring it closer to something like unreal

**Comment by yushli** [comment]
Thank your for all the hard work to bring in this feature. Look forward to the final version with the improved quality.

**Comment by JSandusky** [comment]
It might be more advantageous to consider hermite functions of SDFs. An extruded distance field of a super-elipsoid (whether by affine or non-affine transform)  may be more useful. 

The star shape is a 100% winner for the technique in the paper, but that technique is not a winner to common or patterned shapes that may fit isoline functions.

**Comment by dragonCASTjosh** [comment]
I was also looking at frostbites solution the only issue it is such to basic shapes and can't be textured. Maybe mixing frostbite and the paper above. It would allow every shape including tubes and texturing of 2d shapes

**Comment by dragonCASTjosh** [comment]
After looking into this a little more it seams to propose a new distribution model for PBR that would allow for changes to the specular shape. This would allow for anisotropic speculars and standard speculars to work from the same model making things such a hair and carbon fibre alot easier

**Comment by dragonCASTjosh** [comment]
results also look to heavy for most game applications with around 9 lights dropping the tech demo to 30fps https://www.youtube.com/watch?v=O3TG1VXx1tg

**Comment by dragonCASTjosh** [comment]
So i looked into implementing LTC but from my understanding it would have to implement a new light type that in shaders uses a completely different shading path
