### ISSUE TITLE
Demos in Urho3D master branch runs extremely slow

### ISSUE THREAD

**Issue by yushli** [urho3d/Urho3D#1336]
Download the latest master branch, run the following:
 ./cmake_vs2015.bat ../build -DURHO3D_LIB_TYPE=Shared -DURHO3D_64BIT=1 -DURHO3D_LUA=0  -DURHO3D_C++11=1
then build the solution in VS2015, win7 64bit machine. When running the NinjaSnowWar.bat, it runs extremely slow (FPS around 20). Is it because of PBR is enabled by default now? Before PBR is merged it runs around FPS 200. And all other demos run extremely slow now.

**Comment by weitjong** [comment]
Are you using Debug build configuration by accident?

**Comment by yushli** [comment]
Both debug and release are extremely slow. Ninja jumping will take several seconds to jump up and another several seconds to get down in release build. It is like slow motion pictures. Before PBR is merged , both debug and release run much much faster.

**Comment by weitjong** [comment]
I cannot reproduce it on my Window 10 with 64-bit VS 2015. I am not using C++11 standard, however.

**Comment by hdunderscore** [comment]
I don't believe PBR should be enabled by default.

**Comment by yushli** [comment]
It is false alarm. Somehow my video driver is broken. I ran other old games built before and they also run very slow now. I try to build the latest master branch in another machine and it works perfectly. Thanks for all the reply!
