### ISSUE TITLE
Buttons can not be pressed on android

### ISSUE THREAD

**Issue by r-ku** [urho3d/Urho3D#1337]
Touching buttons on android does not generate E_PRESSED / E_RELEASED events. Buttons light up though, as if they were hovered.

**Comment by cadaver** [comment]
Wasn't able to reproduce on current master. Tested NinjaSnowWar (debug options button) & the SoundEffects sample on a Galaxy Tab 4. Also verified that touch doesn't generate simulated mouse events, only touch events. Do the button presses work in the samples for you?

**Comment by r-ku** [comment]
Oddly sample works. However my own app does not. I am using following UI layout

	<?xml version="1.0"?>
	<element type="Window">
		<attribute name="Name" value="MainMenu" />
		<attribute name="Size" value="180 120" />
		<attribute name="Horiz Alignment" value="Center" />
		<attribute name="Vert Alignment" value="Center" />
		<element type="Button">
			<attribute name="Name" value="btStart" />
			<attribute name="Position" value="20 20" />
			<attribute name="Size" value="140 30" />
			<element type="Text">
				<attribute name="Horiz Alignment" value="Center" />
				<attribute name="Vert Alignment" value="Center" />
				<attribute name="Top Left Color" value="0.85 0.85 0.85 1" />
				<attribute name="Top Right Color" value="0.85 0.85 0.85 1" />
				<attribute name="Bottom Left Color" value="0.85 0.85 0.85 1" />
				<attribute name="Bottom Right Color" value="0.85 0.85 0.85 1" />
				<attribute name="Text" value="Start" />
			</element>
		</element>
		<element type="Button">
			<attribute name="Name" value="btQuit" />
			<attribute name="Position" value="20 70" />
			<attribute name="Size" value="140 30" />
			<element type="Text">
				<attribute name="Horiz Alignment" value="Center" />
				<attribute name="Vert Alignment" value="Center" />
				<attribute name="Top Left Color" value="0.85 0.85 0.85 1" />
				<attribute name="Top Right Color" value="0.85 0.85 0.85 1" />
				<attribute name="Bottom Left Color" value="0.85 0.85 0.85 1" />
				<attribute name="Bottom Right Color" value="0.85 0.85 0.85 1" />
				<attribute name="Text" value="Quit" />
			</element>
		</element>
	</element>

And code:

    _window = new Window(context_);
    gui.GetRoot()->AddChild(_window);
    if(_window->LoadXML(cache.GetResource<XMLFile>("UI/MainMenu.xml")->GetRoot(), true))
    {
        _window->SetStyleAuto();
        auto btStart = _window->GetChild("btStart", true);
        SubscribeToEvent(btStart, E_RELEASED, URHO3D_HANDLER(MenuState, StartGame));
        SubscribeToEvent(_window->GetChild("btQuit", true), E_RELEASED, URHO3D_HANDLER(MenuState, QuitGame));
    }

Needless to say compiling and running it on desktop works just fine - buttons do what they are supposed. However on mobile no amount of pressing triggers button action somehow. Am i doing something wrong here?

**Comment by cadaver** [comment]
Could actually be that there's a missing release event when using touch. The samples use the "press" event as a trigger.

**Comment by cadaver** [comment]
Actually that was an inaccurate conclusion; release event is also used, only the SoundEffects example sound playback is triggered by press. It should also work as long as you release the finger over the button. Why your own program does not work, I cannot determine from the code above.

**Comment by r-ku** [comment]
I managed to put together minimal testcase that has this problem. Is there anything obviously wrong with it? On PC clicking [Exit] button quits application. On mobile (galaxy s5) no amount of pressing does anything. I made sure button is released without moving out of button area and all.

    class TestApplication : public Application
    {
        URHO3D_OBJECT(TestApplication, Application);
    public:
        TestApplication(Context* context)
            : Urho3D::Application(context)
        {
        }
    protected:
        virtual void Setup() override
        {
        }
        virtual void Start() override
        {
            auto style = GetSubsystem<ResourceCache>()->GetResource<XMLFile>("UI/DefaultStyle.xml");
    #if !MOBILE_BUILD
            GetSubsystem<Input>()->SetMouseVisible(true);
    #endif
            UIElement* root = GetSubsystem<UI>()->GetRoot();
            root->SetDefaultStyle(style);
            root->SetStyleAuto();
    
            // Create the button and center the text onto it
            Button* button = root->CreateChild<Button>();
            button->SetStyleAuto();
            button->SetAlignment(HA_CENTER, VA_CENTER);
            button->SetSize(240, 80);
    
            Text* buttonText = button->CreateChild<Text>();
            buttonText->SetAlignment(HA_CENTER, VA_CENTER);
            buttonText->SetFont(GetSubsystem<ResourceCache>()->GetResource<Font>("Fonts/Anonymous Pro.ttf"), 30);
            buttonText->SetText("Exit");
            SubscribeToEvent(button, E_RELEASED, std::bind(&TestApplication::ExitApplication, this));
        }
        void ExitApplication()
        {
            engine_->Exit();
        }
    };
    URHO3D_DEFINE_APPLICATION_MAIN(TestApplication);

**Comment by cadaver** [comment]
It's arguably the correct thing to do on desktops (if both OS cursor is invisible and there's not a visible cursor UI element) so that you don't get accidental UI presses eg. in a FPS mouselook game. But you're right it doesn't make a lot of sense on mobiles. Thanks for bringing this to attention, I believe it should be fixable.
