### ISSUE TITLE
lua call ListView contentElement bug

### ISSUE THREAD

**Issue by hcqmaker** [urho3d/Urho3D#1341]
hierarchyWindow = LoadEditorUI("UI/EditorHierarchyWindow.xml");
hierarchyList = hierarchyWindow:GetChild("HierarchyList");
ui.root:AddChild(hierarchyWindow);
hierarchyList.contentElement

this will crash becase 
[hierarchyList.contentElement]  ==> HierarchyContainer this type can't register in lua

**Comment by weitjong** [comment]
I tried to simplify your issue and tried reproduce it in my Editor app which has both AngelScript and LuaScript subystems enabled. And I was not able to reproduce the crash. I could access the ```contentElement``` of the ```ListView``` class just fine. Here was how I tried it. In the Editor's console window (press F1 to pull it down), and enter:
```
print(ui.root:CreateChild("ListView").contentElement.name)
```
or this:
```
ListView().contentElement.name = "testing"
```
or even simpler one:
```
print(ListView().contentElement)
```

**Comment by weitjong** [comment]
BTW, you need to change the Console's command interpreter to "LuaScript" before replicating this tests.

**Comment by weitjong** [comment]
If I use a newly saved layout XML file containing a window with a ListView element then load it back in Lua, it is OK as well. However, it did crash when I was trying to load the "UI/EditorHierarchyWindow.xml". Interesting.
```
lv = ui:LoadLayout(cache:GetResource("XMLFile", "UI/EditorHierarchyWindow.xml")):GetChild("HierarchyList")
print(lv.contentElement)
```

**Comment by cadaver** [comment]
The Lua bindings indeed don't tolerate subclasses unless they're explicitly registered. Thanks @weitjong for the crashing code snippet, was easy to fix after that.
