### ISSUE TITLE
(Feature request) Automatic calculation of vars hashes when loading from xml files

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1342]
When I manually edit UI's xml file and I want to add a variable to UIElemnt, this variable is not loaded without hash. It's hard to compute the hash manually.

For example:

```
<element type="Window">
	<attribute name="Variables">
		<variant hash="1195757874" type="Vector3" value="1 2 3" name="test" />
	</attribute>
</element>
```

Var "test" is loaded.

```
<element type="Window">
	<attribute name="Variables">
		<variant type="Vector3" value="1 2 3" name="test" />
	</attribute>
</element>
```

Var "test" is not loaded.

**Comment by 1vanK** [comment]
I need it for creating custom default style (it is not possible to open defaultstyle) in Editor.

**Comment by cadaver** [comment]
This looks more like a bugfix than feature enhancement. Considering name is calculated from hash this should be a no-brainer, unless I've overlooked something obvious.

**Comment by 1vanK** [comment]
Thank you!
