### ISSUE TITLE
Sprite does not send event E_UIMOUSECLICK

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1343]
It does not works:
```
    enemy_ = UI_ROOT->CreateChild<Sprite>("Enemy");
    enemy_->AddTags("Gameplay");
    enemy_->SetTexture(CACHE->GetResource<Texture2D>("Urho2D/Gollum.jpg"));
    enemy_->SetSize(IntVector2(450, 285));
    enemy_->SetEnabled(true);
    SubscribeToEvent(enemy_, E_UIMOUSECLICK, URHO3D_HANDLER(UIManager, HandleEnemyClick));
```

But this event works
```
SubscribeToEvent(enemy_, E_HOVERBEGIN, URHO3D_HANDLER(UIManager, HandleEnemyClick));
```

**Comment by 1vanK** [comment]
This works only globally 
```
SubscribeToEvent(E_UIMOUSECLICK, URHO3D_HANDLER(UIManager, HandleMouseClick));
```
Was it so conceived?

**Comment by 1vanK** [comment]
Also AngelScript has no binding Sprite.enabled

**Comment by cadaver** [comment]
The UI system doesn't have a good concept of rotated collision detection; the Sprite was originally created for visual noninteractive elements like a needle in a speedometer. If you can, I recommend using a plain button. Do you specifically need a rotated element in this case?

**Comment by 1vanK** [comment]
I had not planned rotation of sprite, but anyway i should rewrite project to using Sprite2D, because I originally wanted an animated user interface. But in this case I can not use UI events, loading UI from files and other :(

**Comment by cadaver** [comment]
Yes there's a significant amount of "almost-duplicated" functionality between 2D and UI, and preferably everything should be in the same hierarchy, unfortunately it isn't doable without significant refactoring. @aster2013 started work related to this (component based UI branch) but naturally that breaks compatibility with all existing UI code.
