### ISSUE TITLE
samples have visible shadow artifacts on mobile

### ISSUE THREAD

**Issue by yushli** [urho3d/Urho3D#1349]
Running Sample 08_Decals on mobile device, there are visible shadow artifacts.
image1. displays normally. 

![240](https://cloud.githubusercontent.com/assets/1681453/15037181/4a50df1a-12cb-11e6-8233-064415d5fae9.png)

When the camera moves closer, black squares begin to appear:

![241](https://cloud.githubusercontent.com/assets/1681453/15037190/5ea7eecc-12cb-11e6-9267-44819bb7c9dc.png)

**Comment by ucupumar** [comment]
This is happen to me too, I'm using Meizu m2 note with Mali-T720MP3 GPU.
![s60506-142053](https://cloud.githubusercontent.com/assets/5253453/15066839/878290a6-1396-11e6-9ef6-cee6d7d142a4.jpg)

**Comment by cadaver** [comment]
These seem to be device-specific artifacts, for example I don't get these on my Android devices. Unfortunately Urho3D doesn't have resources to implement a "device database" to automatically adjust shadow bias, so the responsibility falls to you to increase the bias according to the worst device you're using to test, or implement some kind of device type detection yourself.

**Comment by yushli** [comment]
Can you give some example code as what and how to adjust to combat this artifact? I see some sample code using 
    light->SetShadowBias(BiasParameters(0.00025f, 0.5f));
    light->SetShadowCascade(CascadeParameters(10.0f, 50.0f, 200.0f, 0.0f, 0.8f));

But how to twist these parameters to get the desired result?

**Comment by cadaver** [comment]
Increase the BiasParameters first value (constant bias). As far as I remember the second value (slope-scale bias) does nothing on OpenGL ES. Also check the Renderer functions SetMobileShadowBiasMul() and SetMobileShadowBiasAdd() which you can use for a global bias adjustment without needing to tweak individual lights.
