### ISSUE TITLE
Transparent Text3D with TE_STROKE looks incorrect

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1351]
Opacity = 1.0:

![1](https://cloud.githubusercontent.com/assets/13021826/15040974/4e91d32c-12c1-11e6-85f6-330356cb631f.png)

Opacity = 0.1:

![1](https://cloud.githubusercontent.com/assets/13021826/15040995/7fe36b5c-12c1-11e6-825e-1165759229e0.png)

TE_SHADOW works perfect:

Opacity = 0.1:

![1](https://cloud.githubusercontent.com/assets/13021826/15041037/b3c85766-12c1-11e6-942d-6504ba9aa64f.png)

Opacity 0.5:

![1](https://cloud.githubusercontent.com/assets/13021826/15041081/f68dbaaa-12c1-11e6-9fbb-1adf7134b2f7.png)

**Comment by cadaver** [comment]
This is a consequence of the stroke effect rendering itself multiple times, so the border color ends up dominating when opacity is low. If you want to tweak the effect (for example render the border with lower alpha) you're welcome to do so and contribute a PR. But there's no actual rendering bug involved.
