### ISSUE TITLE
Audio 100% CPU load on linux

### ISSUE THREAD

**Issue by urs-of-the-backwoods** [urho3d/Urho3D#1361]
I'm using Urho3D 1.5. I have one program which does not play any audio. If I turn audio off it has 20% CPU load, if I enable audio it has >100% CPU load. Even if I reduce audio parameters to 11025 SoundMixRate (Stereo) no change. I know, it might be due to SDL2, but still annoying. Any ideas?

**Comment by cadaver** [comment]
Was this discussed on the forum before? Anyway, now our SDL build should compile all supported audio devices in on Linux, so you should be able to choose a different audio driver.

https://wiki.libsdl.org/FAQUsingSDL

**Comment by urs-of-the-backwoods** [comment]
Great, thank you for your help! Recompiling dependent SDL with all audio drivers in and setting SDL_AUDIODRIVER=pulseaudio actually fixed the problem with the high CPU load.

**Comment by cadaver** [comment]
It might make sense to insert a sleep(0) to the SDL audio thread code to make sure it doesn't hog the CPU with any audio driver.
