### ISSUE TITLE
Engine does not send internal defines to custom "forwardlights" pass

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1365]
I want to render the weapon after blurring of scene:

RenderPath:
```
...
    <command type="quad" tag="MotionBlur" vs="MotionBlur" ps="MotionBlur" output="viewport">
        <texture unit="diffuse" name="viewport" />
        <texture unit="depth" name="depth" />
        <parameter name="ViewProjInv" value="0.0" />
        <parameter name="PrevViewProj" value="0.0" />
        <parameter name="Proj" value="0.0" />
        <parameter name="MyViewProj" value="0.0" />
        <parameter name="TimeStep" value="0.0" />
    </command>
    
    <command type="clear" depth="1.0" output="depth" />
    <command type="scenepass" pass="weaponbase" depthstencil="depth" />
    <command type="forwardlights" pass="weaponlight" depthstencil="depth"/>
```

but the brightness of the weapons varies discretely and there is no specular (It seems that it used vertex lighting)

![1](https://cloud.githubusercontent.com/assets/13021826/15342798/cf3e13f8-1ca0-11e6-9f9c-9a406b686c19.png)

when i add PERPIXEL and SPECULAR to materials
```
<technique vs="LitSolid" ps="LitSolid" psdefines="DIFFMAP">
    <pass name="weaponbase" />
    <pass name="weaponlight" psdefines="SPECMAP PERPIXEL" vsdefines="PERPIXEL" depthtest="equal" depthwrite="false" blend="add" />
</technique>
```
```
<technique vs="LitSolid" ps="LitSolid" psdefines="DIFFMAP">
    <pass name="weaponbase" vsdefines="ENVCUBEMAP" psdefines="ENVCUBEMAP" />
    <pass name="weaponlight" depthtest="equal" depthwrite="false" blend="add" vsdefines="PERPIXEL SPECULAR" psdefines="PERPIXEL SPECULAR" />
</technique>
```
it looks normally
![2](https://cloud.githubusercontent.com/assets/13021826/15342875/3c6dd47c-1ca1-11e6-977e-43b263c9d9b4.png)

may be it used litbase, but 
```
<command type="forwardlights" pass="weaponlight" depthstencil="depth" uselitbase="false"/>
```
does not help me

EDIT: i have 3 light source outside the window and only one has specular (if this is important)

**Comment by cadaver** [comment]
This is a documented issue. When you have a custom pass for lights, the engine can no longer guess that it should be a per-pixel pass. Use the lighting="perpixel" attribute in your custom light pass.

See http://urho3d.github.io/documentation/HEAD/_materials.html

**Comment by 1vanK** [comment]
Oh, it helped. Sorry for my inattention

**Comment by 1vanK** [comment]
custom forwardlights pass replaces standart forwardlights  pass? I can not get them to work simultaneously

**Comment by 1vanK** [comment]
test files: https://github.com/1vanK/MyFiles/raw/master/Temp/Test2Forwardlights.zip

**Comment by 1vanK** [comment]
if I read viewport in quad command, its alpha always == 1 ? or may be stored mask in alpha?

I rework motion blur for working without custom forwardlight pass, but additional texture with mask of weapon make the shader slower
