### ISSUE TITLE
Window loses the ability to resize after double Alt+Enter

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1378]
An example of such problems is the editor. If you press the Alt+Enter, the program will go into full-screen mode. After pressing Alt+Enter program again will go to window mode. But the size of the window can no longer be changed.

Also I consider logical that the application should not change the current resolution when it goes into full screen mode, if it is WindowResizable. The window can take any size, it means it must adapts to the current resolution.

**Comment by cadaver** [comment]
Graphics doesn't remember windowed and fullscreen settings separately. Fullscreen can never be resizable, so when you go back to windowed the resizable flag has been cleared.

If you want, you can disable the automatic fullscreen/windowing switch and handle remembering different settings manually.

**Comment by 1vanK** [comment]
I just disable ALt+Entr in my app. I also have a question. Is it possible to set the minimum size of the window when it is resized?
