### ISSUE TITLE
GL_TEXTURE_CUBE_MAP_SEAMLESS issues

### ISSUE THREAD

**Issue by carnalis** [urho3d/Urho3D#1380]
OGLGraphics.cpp
https://github.com/urho3d/Urho3D/commit/3f861d67dd684d4ca9dbdbdcdbd6dfe9ec701407#diff-878294995c200c1ad22be2b31d26cdf5

There have been some problems with **GL_TEXTURE_CUBE_MAP_SEAMLESS** (OpenGL 3.2) on some older hardware; e.g., GeForce 9800 GT, 9600 GM -- these are OpenGL 2.1

In some cases I have seen, the vertex shader aborts.

**Comment by 1vanK** [comment]
try to update drivers :)

**Comment by carnalis** [comment]
Hi 1vanK :)
The problem exists with the most recent Windows driver, the previous one, an OSX driver, and I would not be surprised to find with all of them, on those hardware. I don't think they will fix it.. Would a conditional (gl 3.2) be an approach?

**Comment by carnalis** [comment]
Also, if there are any changes, they could be posted here and I'll be happy to try them.

**Comment by cadaver** [comment]
Making it conditional on GL3 sounds good. Also, nothing would prevent one from enabling it in application code.

**Comment by cadaver** [comment]
I added extension check in GL2 mode. Please check if it helps.

**Comment by carnalis** [comment]
Sorry for the misinformation, it appears that the 9800 GT does support GL 3.x and GLEW_ARB_seamless_cube_map -- they appear in spec sheets and it passes both of your tests in practice.
So perhaps a revert, or option to disable the extension will not be problematic to users?

Again, the Urho Skybox (11_Physics) does appear fine (although I can notice seams) so something more is going on. The shader in question, for reference
https://github.com/carnalis/ProcSky/blob/master/ProcSky.glsl

**Comment by carnalis** [comment]
Maybe the original method is fine. If we can **disable** the extension in our apps, the issue can rest for me.

**Comment by carnalis** [comment]
Another brief on this issue with OSX
http://distrustsimplicity.net/articles/gl_texture_cube_map_seamless-on-os-x/

Presumably, 1vanK's code was fine and this issue can rest for me.

But some will want a way to disable GL_TEXTURE_CUBE_MAP_SEAMLESS where the implementation does not work.

**Comment by cadaver** [comment]
In that case one can modify the engine, or disable the state after graphics init if that works. In general OpenGL has a bad reputation for issues like this and I'm surprised Urho has not been hit with them more. But in any case, the engine code should be able to act as if drivers work properly according to spec instead of being paranoid. I mean, if a driver lists an extension as supported, it's rather backwards if using it enables a software fallback!

**Comment by 1vanK** [comment]
In Google on request "GL_TEXTURE_CUBE_MAP_SEAMLESS geforce" quite a lot of messages about errors with old nvidia cards. So this is not an isolated case. I think, we can add some command line options (with an explanation of the reasons for its existence and disabled by default) for turn off this paramter for games, that do not use PBR.

**Comment by 1vanK** [comment]
Or at least add commentary in the code about that it may be the error culprit  because debug such errors is difficult.

**Comment by cadaver** [comment]
Command line option for a bug is ugly IMO. If you're concerned, it's also fine by me to remove the code completely and leave it up to application author to enable the seamless state.

**Comment by 1vanK** [comment]
I do not know what to do better, but if the game is not working, let's say 10% of users this is not good.

**Comment by cadaver** [comment]
Yes, but also Urho is not a game itself. It's the application developer's responsibility to test on the hardware they claim to be supported, and install appropriate workarounds if needed. I'm sure there are odd issues with various old cards (especially Intel) but so far we haven't littered the codebase with checks for them. I'm quite sure various commercial engines do, though.

**Comment by 1vanK** [comment]
I agree, so I think a brief comment in the code will be sufficient.
