### ISSUE TITLE
mingw-w64 SSE error in app compilation: inlining failed in call to always_inline

### ISSUE THREAD

**Issue by carnalis** [urho3d/Urho3D#1383]
`In file included from C:/mingw/lib/gcc/x86_64-w64-mingw32/5.3.0/include/emmintrin.h:31:0,
                 from urho/build/include/Urho3D/Math/Quaternion.h:28,
                 from src\CameraController.cc:1:
C:/mingw/lib/gcc/x86_64-w64-mingw32/5.3.0/include/xmmintrin.h: In copy constructor 'Urho3D::Quaternion::Quaternion(const Urho3D::Quaternion&)':
C:/mingw/lib/gcc/x86_64-w64-mingw32/5.3.0/include/xmmintrin.h:982:1: error: inlining failed in call to always_inline 'void _mm_storeu_ps(float*, __m128)': target specific option mismatch
 _mm_storeu_ps (float *__P, __m128 __A)`

errors grep:
`C:/mingw/lib/gcc/x86_64-w64-mingw32/5.3.0/include/xmmintrin.h:982:1: error: inlining failed in call to always_inline 'void _mm_storeu_ps(float*, __m128)': target specific option mismatch
C:/mingw/lib/gcc/x86_64-w64-mingw32/5.3.0/include/xmmintrin.h:933:1: error: inlining failed in call to always_inline '__m128 _mm_loadu_ps(const float*)': target specific option mismatch
C:/mingw/lib/gcc/x86_64-w64-mingw32/5.3.0/include/xmmintrin.h:982:1: error: inlining failed in call to always_inline 'void _mm_storeu_ps(float*, __m128)': target specific option mismatch
C:/mingw/lib/gcc/x86_64-w64-mingw32/5.3.0/include/xmmintrin.h:933:1: error: inlining failed in call to always_inline '__m128 _mm_loadu_ps(const float*)': target specific option mismatch
C:/mingw/lib/gcc/x86_64-w64-mingw32/5.3.0/include/xmmintrin.h:982:1: error: inlining failed in call to always_inline 'void _mm_storeu_ps(float*, __m128)': target specific option mismatch
C:/mingw/lib/gcc/x86_64-w64-mingw32/5.3.0/include/xmmintrin.h:948:1: error: inlining failed in call to always_inline '__m128 _mm_set_ps(float, float, float, float)': target specific option mismatch
C:/mingw/lib/gcc/x86_64-w64-mingw32/5.3.0/include/xmmintrin.h:982:1: error: inlining failed in call to always_inline 'void _mm_storeu_ps(float*, __m128)': target specific option mismatch
C:/mingw/lib/gcc/x86_64-w64-mingw32/5.3.0/include/xmmintrin.h:948:1: error: inlining failed in call to always_inline '__m128 _mm_set_ps(float, float, float, float)': target specific option mismatch
C:/mingw/lib/gcc/x86_64-w64-mingw32/5.3.0/include/xmmintrin.h:968:1: error: inlining failed in call to always_inline 'float _mm_cvtss_f32(__m128)': target specific option mismatch
C:/mingw/lib/gcc/x86_64-w64-mingw32/5.3.0/include/xmmintrin.h:968:1: error: inlining failed in call to always_inline 'float _mm_cvtss_f32(__m128)': target specific option mismatch
C:/mingw/lib/gcc/x86_64-w64-mingw32/5.3.0/include/xmmintrin.h:968:1: error: inlining failed in call to always_inline 'float _mm_cvtss_f32(__m128)': target specific option mismatch
C:/mingw/lib/gcc/x86_64-w64-mingw32/5.3.0/include/xmmintrin.h:786:1: error: inlining failed in call to always_inline '__m128 _mm_movehl_ps(__m128, __m128)': target specific option mismatch
C:/mingw/lib/gcc/x86_64-w64-mingw32/5.3.0/include/xmmintrin.h:185:1: error: inlining failed in call to always_inline '__m128 _mm_add_ps(__m128, __m128)': target specific option mismatch
C:/mingw/lib/gcc/x86_64-w64-mingw32/5.3.0/include/xmmintrin.h:185:1: error: inlining failed in call to always_inline '__m128 _mm_add_ps(__m128, __m128)': target specific option mismatch
C:/mingw/lib/gcc/x86_64-w64-mingw32/5.3.0/include/xmmintrin.h:191:1: error: inlining failed in call to always_inline '__m128 _mm_sub_ps(__m128, __m128)': target specific option mismatch
C:/mingw/lib/gcc/x86_64-w64-mingw32/5.3.0/include/xmmintrin.h:197:1: error: inlining failed in call to always_inline '__m128 _mm_mul_ps(__m128, __m128)': target specific option mismatch
C:/mingw/lib/gcc/x86_64-w64-mingw32/5.3.0/include/xmmintrin.h:197:1: error: inlining failed in call to always_inline '__m128 _mm_mul_ps(__m128, __m128)': target specific option mismatch
C:/mingw/lib/gcc/x86_64-w64-mingw32/5.3.0/include/xmmintrin.h:185:1: error: inlining failed in call to always_inline '__m128 _mm_add_ps(__m128, __m128)': target specific option mismatch
C:/mingw/lib/gcc/x86_64-w64-mingw32/5.3.0/include/xmmintrin.h:197:1: error: inlining failed in call to always_inline '__m128 _mm_mul_ps(__m128, __m128)': target specific option mismatch
C:/mingw/lib/gcc/x86_64-w64-mingw32/5.3.0/include/xmmintrin.h:191:1: error: inlining failed in call to always_inline '__m128 _mm_sub_ps(__m128, __m128)': target specific option mismatch
C:/mingw/lib/gcc/x86_64-w64-mingw32/5.3.0/include/xmmintrin.h:197:1: error: inlining failed in call to always_inline '__m128 _mm_mul_ps(__m128, __m128)': target specific option mismatch
C:/mingw/lib/gcc/x86_64-w64-mingw32/5.3.0/include/xmmintrin.h:197:1: error: inlining failed in call to always_inline '__m128 _mm_mul_ps(__m128, __m128)': target specific option mismatch
C:/mingw/lib/gcc/x86_64-w64-mingw32/5.3.0/include/xmmintrin.h:948:1: error: inlining failed in call to always_inline '__m128 _mm_set_ps(float, float, float, float)': target specific option mismatch
C:/mingw/lib/gcc/x86_64-w64-mingw32/5.3.0/include/xmmintrin.h:933:1: error: inlining failed in call to always_inline '__m128 _mm_loadu_ps(const float*)': target specific option mismatch`

One declaration from xmmintrin.h:
`extern __inline __m128 __attribute__((__gnu_inline__, __always_inline__, __artificial__))
_mm_add_ps (__m128 __A, __m128 __B)`

gcc version 5.3.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project),

make VERBOSE=1 shows "-mno-sse" is among the flags being passed to g++.

**edit 1**
Urho shared build
App cmake options include  -D CMAKE_CXX_FLAGS="-march=native" -D MINGW_SYSROOT="C:/mingw/x86_64-w64-mingw32" -D URHO3D_C++11=1

I'll try another mingw-w64 and keep poking around...

**Comment by cadaver** [comment]
Here something similar was encountered:

http://stackoverflow.com/questions/35772562/inlining-failed-in-call-to-always-inline-m128i-mm-cvtepu8-epi32-m128i-t

I don't think this is an Urho bug as such. As a last resort you could disable URHO3D_SSE

**Comment by uzername** [comment]
Had the same errors. 
Added `-march=native` option and it helped.
(just passing by, no problem)

**Comment by weitjong** [comment]
Perhaps there is something else I miss, but according this code snippet below then when URHO3D_SSE is on then it should automatically set the "-march=native" compiler flag.

https://github.com/urho3d/Urho3D/blob/54ed4c917f242817029797a72eb7867ea7ab0247/CMake/Modules/UrhoCommon.cmake#L612-L619
