### ISSUE TITLE
2D Sounds without scene node

### ISSUE THREAD

**Issue by giovannispina** [urho3d/Urho3D#1385]
Is it possibile to play 2D sounds without a scene dependency?
We are able to draw raw vertices on screen (bypassing the scene), but what about 2D sounds?

e.g. would be an environment with multiple scenes and a VoiceChat/Music stream (does not make sense to be tied to the scene).

**Comment by 1vanK** [comment]
You can create an empty scene for this (see example 14_SoundEffects

**Comment by cadaver** [comment]
Strictly speaking you don't even need a scene, the sound component just needs to be attached to a Node to be considered "enabledEffective". You can "new" a node without it belonging to a scene, though then you must take care of its lifetime management yourself.
