### ISSUE TITLE
ResourceCache wont work inside LogicComponent why?

### ISSUE THREAD

**Issue by rbnpontes** [urho3d/Urho3D#1388]
LogicComponent  guys, i have a problemas with Using ResourceCache inside LogicComponent, if i'm Using GetResource this is not working, not return ResourceCache.
Sorry for english

**Comment by cadaver** [comment]
This is almost certainly an invalid issue. Make sure your LogicComponent has been created using the same Context pointer as the engine. There's an example use of resource access inside LogicComponent in the VehicleDemo sample:

https://github.com/urho3d/Urho3D/blob/master/Source/Samples/19_VehicleDemo/Vehicle.cpp

Also prefer the forum http://urho3d.prophpbb.com/ for questions of the type "why doesn't my code work" until you're somewhat sure that it's an actual engine issue.
