### ISSUE TITLE
Integrate LeapMotion in Urho3D

### ISSUE THREAD

**Issue by Kavignon** [urho3d/Urho3D#1393]
Hi,

I've been going through the issues to find some sort of way to get involve. Thought the VR integration describe in #153 looked super fun but I don't have an headset at this moment. What I've thought we could do is add LeapMotion which could be a cool thing to use inside the engine. Using it with VR brings out cool hack experience as I have seen on the leap motion hackathons. 
I'll be waiting for you guys to see what you've got to say about this.

**Comment by cadaver** [comment]
I'm not terribly in favor of integrating anything that cannot be readily tested by the core developers. Currently for input we have mouse, keyboard, touch, joypad which are easy enough to test. From my perspective this would essentially be a "black box" functionality being added to the codebase. And once something gets contributed, it tends to become the core developers' responsibility to maintain, with the original author potentially disappearing. Therefore I'd rather be in favor of making and maintaining a separate project, which can be linked from Urho documentation, forum etc. and which people can use if they want (for a similar example, consider the Blender exporter)

**Comment by Kavignon** [comment]
I'm not entirely sure what you trying to say here, what would I have to do in order to do such a thing ? I can't just fort the project and make the integration ?

**Comment by cadaver** [comment]
Take a look at this example of LibRocket integration. You wouldn't fork the engine, but provide the code for the integration only. The end result could for example be a library which links to Urho, and which an application author could use. (Urho doesn't support plugins as such)

https://github.com/SirNate0/libRocket-Urho3D

**Comment by paper-pauper** [comment]
LeapMotion SDK is proprietary, and for that reason I recommend against integrating it in Urho.

**Comment by cadaver** [comment]
We have the proprietary Spine 2D animation library integrated in such manner that the user must copy the library code to Urho source directory and enable a build option. This is not terribly clean or straightforward, so yes in general I agree that the technology being integrated should be open source itself. Even "free to use" binary SDKs are difficult since we support so many platforms and compilers, and so we'd rather build everything from source.

**Comment by paper-pauper** [comment]
@cadaver That solution is acceptable. If you want to integrate LeapMotion that way, I don't think anybody here would have an issue but still, IMHO, what makes Urho3D different than other "free of charge" engines like Unreal Engine is that it is also "free as in speech", so whenever there is a FLOSS solution is available that should be used instead, to encourage a better environment for everybody without having to agree to (often unfair) EULAs and ToSs.

This is also true for #1372. In short, if this (or the FBX SDK) is implemented, it wouldn't be fair to say "that feature is implemented". A feature isn't truly implemented until it can be used under the same terms as the rest of the code.
