### ISSUE TITLE
SpritePacker works incorrect when count of input files equals 8

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1394]
When count of input files = 9 all is correct:
![shovel1](https://cloud.githubusercontent.com/assets/13021826/15620201/7b338608-2461-11e6-8087-8ae3ea1ecac7.png)

When 8 (lat frame = first frame):
![shovel1](https://cloud.githubusercontent.com/assets/13021826/15620207/929efb06-2461-11e6-82de-9f16cae1047d.png)

Test files: https://github.com/1vanK/MyFiles/raw/master/Temp/PackerBug.zip

**Comment by 1vanK** [comment]
When count of input files = 8 their order is broken:
![shovel1](https://cloud.githubusercontent.com/assets/13021826/15621612/bc45898a-246a-11e6-992c-d30a1b40353f.png)

**Comment by cadaver** [comment]
Note the XML file that is output. The offsets match the order of the input images. So you would have to use the XML definitions in your animation. The SpritePacker is using the stb image packer library and it would seem it doesn't guarantee the order to be obvious (= same as input order) Can @friesencr clarify?

**Comment by 1vanK** [comment]
> Note the XML file that is output. 
Indeed, I did not notice it :(I just do not use xml-file.
It would be convenient to keep the order of frames in the output file in such cases

**Comment by 1vanK** [comment]
I found another way for it http://acamara.es/blog/2012/12/assembling-sprite-sheets-with-imagemagick/

**Comment by friesencr** [comment]
It does use stb packer and it does not preserve the order.  I think stb is optimized for packing into lines for its fonts.  I mangled it to do a number of trial and errors to try for as small of power of 2 textures as possible.  The intent of the tool was to give people a free option and to later get it to work with the editor so people could drag n drop make sprites.
