### ISSUE TITLE
Why Urho3D has no aliases for simple types like unsigned long?

### ISSUE THREAD

**Issue by EugeneKozlov** [urho3d/Urho3D#1402]
I really wonder why 'unsigned char' is used instead of typedef-ed 'uchar' (for example)

**Comment by Stinkfist0** [comment]
I think this is mostly in order to prevent conflicts and problems with various integrated 3rd-party libraries.

**Comment by cadaver** [comment]
It's also a style choice (meaning an especial need for aliases was not felt) and compatibility-related, since Urho started in era of VS2008 where cstdint header was not available.

**Comment by EugeneKozlov** [comment]
Have you ever had any problems caused by floating size of short/int/long/long long on different platforms? /just a question/

**Comment by cadaver** [comment]
Practically, on the platforms Urho compiles to, the standard types (char, short, int, long long, float) are fixed bitsize and haven't caused any problems.

"Long" type will have different bitsize on Windows and non-Windows, so that is avoided in the codebase,
