### ISSUE TITLE
Smooth model LOD switch

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1405]
http://urho3d.prophpbb.com/topic2163.html

How to make it?
It could be fade through transparency for FR or dithering for DS renderer.

**Comment by cadaver** [comment]
Likely you would need to subclass e.g. StaticModel and make it draw more batches (to draw both LODs) during the transition period.

**Comment by EugeneKozlov** [comment]
To make smooth fade I need fade factor in the destination shader and I shouldn't use shader uniforms to reach this. So I need to pass this factor through SourceBatch into renderer.
Can I safely use e.g. [1] element of worldTransform_ for this purpose?
Do you think about implementing some kind of smooth lods or custom parameters at some point?

**Comment by cadaver** [comment]
In my opinion the easiest/correct way is to use a special material (cloned from the original) for the transition time.This could have for example transparent blending set, and its DiffColor alpha modified for the transition, or a custom uniform used to control e.g. stippling / dithering.

**Comment by cadaver** [comment]
You're right though that if you're after max performance and rendering hundreds of fading objects at the same time, using individually cloned materials, it will break instancing and generally cause slowdown in the render queue preparation stage. For that, you should perhaps look into expanding the object transform into a full 4x4 matrix so you can store extra data. This is a change I'd very likely not want into the core Urho3D, so you'd be diverging from it.

**Comment by EugeneKozlov** [comment]
Extending matrix is easy and bad solution, I agree.. User shouldn't pay for what he don't use.
What about adding second instance array like 'user instance data'? It could be handy for many cases, on my opinion. To pass per-instance color or some other data.
It can look like
`#define NUM_PARAM 0/1/2/etc`
and new member in SourceBatch
`#if NUM_PARAM > 0
Vector4 params_[NUM_PARAM];
#endif`
and the same guards in renderer that allows anybody enable this buffer when needed.

**Comment by EugeneKozlov** [comment]
One more question.
I found that dithering fade looks better when fading is performed during some small time interval instead of distance-based fade.
How can I get 'current time' in updateBatches()?
I don't want to pass it from external code.

**Comment by cadaver** [comment]
In the shaders it's quite easy to add arbitrary per-instance data, just define it to e.g. an unused texcoord.

One just has to think of the best way how to handle it on the engine code side. The engine creates the instance data vertex buffer; its vertex declaration could be made configurable (every instanced object just needs to use the same format of data). I'd possibly prefer a run-time dynamic solution, like a data ptr in SourceBatch that can be null, to ifdefs.

**Comment by cadaver** [comment]
You get the framenumber and deltatime in FrameInfo, but not absolute time. You could either calculate absolute time from the deltas yourself, or use the passed Camera pointer and find the camera's scene, and get the scene's elapsed time. However Urho allows sceneless cameras, so that might not be valid for every situation.

**Comment by eugeneko** [comment]
Thank you, delta time is enough for my algorithm.
So I'll start working on this task this month when I finish my education tasks...

**Comment by eugeneko** [comment]
I am trying to find a way to make custom instance buffer format.
There are a lot of places which rely on fixed instance format.
1. I cannot switch VertexBuffer format without re-allocation, but it is quite easy to fix.
2. View::PrepareInstancingBuffer is hard-coded to uniform instance data too. I suppose, this is fix-able too, with some hacks. E.g. use numVectors[=numInstances*3] instead of numInstances for all manipulations and use one Float4 vector as temporary internal InstanceBuffer vertex format.
3. Graphics::SetVertexBuffers computes offsets using internal vertex format and number of instances.

I need some way to re-use buffer for different formats.
Do you have any ideas?

**Comment by cadaver** [comment]
I recommend the following:

- add a function to Renderer which allows to set the vertex declaration for the instancing buffer. The application would call this in the beginning when it wishes to use custom instancing extra data. 

- View needs to be changed to be smart enough to respect the declaration when setting the position data (texcoord 4-6 are the instance transform matrix, and should be first in the declaration, and anything after that would be the extra data)

- Drawable / SourceBatch specifies the extra data via an added member, and View knows to use it when filling the instancing buffer.

These changes would be acceptable as a PR, since they disturb the existing functionality or performance only minimally if at all.

**Comment by eugeneko** [comment]
Thank you for your quick replies!
I have just implemented subject with small changes in internal Urho3D with ~zero overhead.
[Video here](https://youtu.be/73FjrrF_IW8)

I think it is pretty useless to allow user to specify instance buffer format directly because of many restrictions. Actually, user is only able to add some texcoords starting from 7-th. So I am going to make interface like this `Renderer::SetInstancingBufferExtraData(numVectors)` with small limit to prevent misuse. This function will just add some extra float4-s to instance data format.

**Comment by eugeneko** [comment]
Thank you for writing docs for this feature and your help with implementation!

Actually, I have one more quiestion.
For now your LOD system in Static Model is designed for using the same distance for both N->N+1 and N+1->N LOD switches.
Have you thought about using different distances for different switches?
As far as I know, this is common practice to avoid frequent swithces when camera moves hither and thither.
Of course, it could be easily implemented over Static Mesh.
But I am wondering why it is not implemented inside Static Mesh. It should cost nothing, just few more comparisons.

**Comment by cadaver** [comment]
The model format stores just one distance per LOD level, so it'd require a change. The LOD level system was pretty much copied from Ogre originally.
