### ISSUE TITLE
specifying -DURHO3D_OPENGL=1 on windows 10 still builds d3d9 graphics 

### ISSUE THREAD

**Issue by Lumak** [urho3d/Urho3D#1406]
F:\Urho3D\Urho3D-1.5>cmake_vs2013.bat ..\builds -DURHO3D_SAMPLES=1 -DURHO3D_OPENGL=1
-- The C compiler identification is MSVC 18.0.31101.0
-- The CXX compiler identification is MSVC 18.0.31101.0
-- Check for working C compiler using: Visual Studio 12 2013
-- Check for working C compiler using: Visual Studio 12 2013 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler using: Visual Studio 12 2013
-- Check for working CXX compiler using: Visual Studio 12 2013 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- COMPILER_VERSION:         1800
-- Looking for C++ include d3dcompiler.h
-- Looking for C++ include d3dcompiler.h - found
-- Looking for C++ include d3d9.h
-- Looking for C++ include d3d9.h - found
-- Looking for C++ include d3d11.h
-- Looking for C++ include d3d11.h - found
-- Looking for C++ include ddraw.h
-- Looking for C++ include ddraw.h - found
-- Looking for C++ include dsound.h
-- Looking for C++ include dsound.h - found
-- Looking for C++ include dinput.h
-- Looking for C++ include dinput.h - found
-- Looking for C++ include dxgi.h
-- Looking for C++ include dxgi.h - found

**Comment by weitjong** [comment]
DX headers are required regardless,  I think.

**Comment by cadaver** [comment]
Yes, headers such as dsound.h & dinput.h at least. SDL searches also for D3D related ones as part of its build process, though we don't build SDL with the actual "render" backends compiled in. If you check the solution for what Urho render backend is actually included, you should find it's OpenGL, unless your cmake cache contains URHO3D_D3D11=1, which will override OpenGL, but in that case it'll be D3D11 and not D3D9.

**Comment by Lumak** [comment]
Ah ok. thank you.

**Comment by JimSEOW** [comment]
Could someone let me know if the D3D11 support is now complete? If so, is it possible to build Urho3D for Windows 10 Mobile or UWP. Has anynoe done so, is there any example or internet links. Thanks.
http://urho3d.github.io/releases/2015/11/11/urho3d-1.5-release.html

**Comment by weitjong** [comment]
D3D11 work was completed since release 1.4. But if your question is whether Urho3D has supported all the features available in D3D11 then the answer is no I suppose. Urho3D does not support compute and geometry shaders, just to name a few.

At the moment we do not support targeting UWP also. You may want to look at UrhoSharp downstream project for that.

**Comment by JimSEOW** [comment]
@weitjong Thanks Wei Tjong! It is good to know. Through UrhoSharp, we now have working x86 support for UWP. What is needed is to use visual studio to compile for ARM (D3D11) to generate both the static and dynamic libraries needed to generate the c# binders to bring the most current Urho3d development to Windows 10 mobile ARM devices.

**Comment by weitjong** [comment]
I am afraid I don't have the experience nor incentives to do so.

**Comment by JimSEOW** [comment]
@weitjong No one should be accountable before morning coffee :-) You have given me the answer I need in your first reply. Thanks!
