### ISSUE TITLE
Mouse visibility issue

### ISSUE THREAD

**Issue by giovannispina** [urho3d/Urho3D#1411]
I was trying to hide the default mouse cursor in order to use a custom one but I've just noticed that MouseVisible flag remains true.

```cpp
Input* input = GetSubsystem<Input>();
input->SetMouseVisible(true);
input->SetMouseVisible(false);
bool val = input->IsMouseVisible(); // val = true
```

The problem is here (InputFocus is not true):
https://github.com/urho3d/Urho3D/blob/f6a01c11af1c149af2c96d586e86ceac662a1332/Source/Urho3D/Input/Input.cpp#L553

**Comment by cadaver** [comment]
What OS are you on? Do the Urho example programs (for example NinjaSnowWar) hide the mouse cursor correctly?

The cursor is a global resource so when your application is defocused it is expected that you cannot hide the mouse cursor (ie. otherwise you'd be messing with another application's operation)

**Comment by OldSnake22** [comment]
I have also some issues with mouse cursor / input focus since the SDL update.

**Comment by hdunderscore** [comment]
@giovannispina, you do that at the start of the program? Is the application still in focus?

@OldSnake22, can you give more details or examples?

**Comment by giovannispina** [comment]
@hdunderscore yes, I do that at the start of the program. Although the window is on focus, the InputFocus flag is still false because I load my prerequisite resources from my custom UI as soon as the application is created and initialised however Urho3D doesn't update that flag until the first call of RunFrame().

**Comment by cadaver** [comment]
I see the problem now. That should be workable around in Input::Initialize().

I believe you could also work around by calling Input::Update() manually before attempting to hide the cursor.
