### ISSUE TITLE
fixed size slider bug

### ISSUE THREAD

**Issue by Lumak** [urho3d/Urho3D#1412]
When the slider's knob is set as fixed size, it hops when slid because of the 0.5f value added in the computation.

code below fixes it, tested both horizontal and vertical settings.

void UpdateSlider()
{
    const IntRect& border = knob_->GetBorder();

    if (range_ > 0.0f)
    {
        if (orientation_ == O_HORIZONTAL)
        {
            int sliderLength = (int)Max((float)GetWidth() / (range_ + 1.0f), (float)(border.left_ + border.right_));

            if ( knob_->IsFixedSize() )
            {
                sliderLength = knob_->GetWidth();
            }

            float sliderPos = (float)(GetWidth() - sliderLength) * value_ / range_;

            if ( !knob_->IsFixedSize() )
            {
                knob_->SetSize(sliderLength, GetHeight());
                knob_->SetPosition(Clamp((int)(sliderPos + 0.5f), 0, GetWidth() - knob_->GetWidth()), 0);
            }
            else
            {
                knob_->SetPosition(Clamp((int)(sliderPos), 0, GetWidth() - knob_->GetWidth()), 0);
            }
        }
        else
        {
            int sliderLength = (int)Max((float)GetHeight() / (range_ + 1.0f), (float)(border.top_ + border.bottom_));

            if ( knob_->IsFixedSize() )
            {
                sliderLength = knob_->GetHeight();
            }

            float sliderPos = (float)(GetHeight() - sliderLength) * value_ / range_;

            if ( !knob_->IsFixedSize())
            {
                knob_->SetSize(GetWidth(), sliderLength);
                knob_->SetPosition(0, Clamp((int)(sliderPos + 0.5f), 0, GetHeight() - knob_->GetHeight()));
            }
            else
            {
                knob_->SetPosition(0, Clamp((int)(sliderPos), 0, GetHeight() - knob_->GetHeight()));
            }
        }
    }
    else
    {
        if ( !knob_->IsFixedSize())
        {
            knob_->SetSize(GetSize());
        }
        knob_->SetPosition(0, 0);
    }
}

**Comment by cadaver** [comment]
Thanks for the fix! Will test shortly.
