### ISSUE TITLE
Visual Studio type visualizer

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1415]
Does anybody have one?
E.g. Natvis, or at least AutoExp?..

**Comment by hdunderscore** [comment]
Just updating issue, as you've posted a type visualizer here: https://github.com/eugeneko/Urho3D-Debug

Worth including as part of build or maybe just a mention in the docs?

**Comment by eugeneko** [comment]
Yep, I thought about it.
Unsure that it's good idea to push such very specific stuff into main repo.
However, it's okay to mention it in docs.

**Comment by 1vanK** [comment]
https://urho3d.github.io/documentation/HEAD/_external_links.html ?

**Comment by weitjong** [comment]
How about a new section under the [how-to](https://urho3d.github.io/documentation/HEAD/_misc__how_tos.html) page?

**Comment by 1vanK** [comment]
Or in wiki
