### ISSUE TITLE
Changing node positions is really slow

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1416]
I have 400 moved objects in my scene.

![1](https://cloud.githubusercontent.com/assets/13021826/15983160/0773684a-2fa7-11e6-9c44-1a2004898316.png)

When I disable node translations
```
//node_->Translate(forceDirection * forceModulus * timeStep * 2.0f);
```

![2](https://cloud.githubusercontent.com/assets/13021826/15983168/5fe778fe-2fa7-11e6-83a8-7d45887a95a7.png)

**Comment by 1vanK** [comment]
Is there way to render drawables without using node system (just manually send batches to render) ?

**Comment by cadaver** [comment]
Moving a node is going to send dirty signals to the components and up the child node hierarchy, so it isn't free. You could look into subclassing Drawable and making your own "scene graph" inside it, which essentially sends several objects' batches to be rendered. Look to the StaticModelGroup class for inspiration

**Comment by 1vanK** [comment]
> Look to the StaticModelGroup class for inspiration

Thanks for the advice. Should I close the issue?

**Comment by cadaver** [comment]
I will check the scene graph for performance regressions (eg. the examples) and close if I don't find any. By the way are you running in debug mode or a very slow CPU? Typically 400 moving nodes should be nothing to Urho.

**Comment by 1vanK** [comment]
I used Release version (VS 2015) . I can provide the source code of the project, if they are necessary.

**Comment by eugeneko** [comment]
How to show this nice statistic?
I am not about profiler.

**Comment by cadaver** [comment]
If DebugHud has been created (all samples create it), use debugHud->Toggle(DEBUGHUD_SHOW_PROFILER);

**Comment by cadaver** [comment]
I tested a modifed AnimatingScene .cpp sample by grouping all the objects close together, and making them translate slowly (all were in view). This is 2000 objects, and moving them all took about 1.4 ms per frame on a relatively fast AMD processor. It's not super-fast, but roughly as expected. Each object was moving using their individual LogicComponent, which further adds overhead. 

If you need to move objects multiple times per frame, you could use SetPositionSilent() to avoid signaling overhead, and only when you finalize the node's position, call the normal SetPosition(). This is used by the animation system when blending multiple animations.

Closing this now.

**Comment by 1vanK** [comment]
Hm, i also do not see falling of perfomance in modified AnimatingScene with and without node->translate...

**Comment by 1vanK** [comment]
Please test https://github.com/1vanK/MyFiles/raw/master/Temp/MoveNodePerfomance.zip

(need comment last line in MoleculeLogic.cpp for comparsion)
```
node_->Translate(forceDirection * forceModulus * timeStep * 2.0f); // COMMENT THIS
```

**Comment by 1vanK** [comment]
I think problem not in node translation:

```
    //Vector3 f = forceDirection * forceModulus * timeStep * 2.0f; // VERY SLOW
    Vector3 f = Vector3::ONE * timeStep * 2.0f; // FAST

    node_->Translate(f);
```

**Comment by 1vanK** [comment]
It is strange, but

```
Vector3 f = Vector3::ONE * timeStep * 2.0f
node_->Translate(f);
```
- normal fps.

```
Vector3 f = forceDirection * forceModulus * timeStep * 2.0f;
//node_->Translate(f);
```
- normal fps.

```
Vector3 f = forceDirection * forceModulus * timeStep * 2.0f;
node_->Translate(f);
```
- low fps.

It seems that performance of Tranclate is falling for certain input values

**Comment by 1vanK** [comment]
Ok, I understood my mistake (after hours of profiling xD). When result of calculations don't use for node moving, compiler just remove unused (and havy) code. Therefore, such a big difference for fps.

**Comment by cadaver** [comment]
Nice that it was solved!
