### ISSUE TITLE
draw order in 2d

### ISSUE THREAD

**Issue by yushli** [urho3d/Urho3D#1421]
It looks like there is no actual layer class in 2D, such as UIElement that can act as a container to hold other UI Elements as children. Instead it uses an integer layer to keep the draw order information.
1. Is it desirable to add such a class to hold other 2d drawables as children?  That way the logic of the parent/children relationship would be clearer than using layer and orderInlayer integers.
2. in Drawable2D.h, line 109
   int GetDrawOrder() const { return (layer_ << 20) + (orderInLayer_ << 10); }
   shouldn't it be 
   int GetDrawOrder() const { return (layer_ << 20) + orderInLayer_ ; }

**Comment by yushli** [comment]
Any feedback on this one? Is it fine to change  int GetDrawOrder() const { return (layer_ << 20) + (orderInLayer_ << 10); } to 
 int GetDrawOrder() const { return (layer_ << 20) + orderInLayer_ ; } ?

**Comment by gogoprog** [comment]
I'd also like to know about the << 10 for your second point because I don't get it either

**Comment by cadaver** [comment]
It's a fairly arbitrary choice by the original author, who possibly can't access this project anymore due to China's firewall restrictions.
