### ISSUE TITLE
API-agnostic graphics class headers

### ISSUE THREAD

**Issue by cadaver** [urho3d/Urho3D#1422]
Related to the discussion in https://github.com/urho3d/Urho3D/issues/1397, this proposes a change that just a one graphics API agnostic copy of public Graphics subdirectory header files (ie. Graphics.h, VertexBuffer.h, Texture2D.h ..) exists. 

This increases code maintainability and hides the actual graphics API choice inside the library so that a Urho library built using any graphics API should be interchangeable in applications. Some return values (Graphics::RGBAFormat() etc.) will still be API-dependent so their values should not be relied on in crossplatform applications.

This should also get rid of the issue that the generated documentation would be different depending on the graphics API.

**Comment by 1vanK** [comment]
Because the graphics system will be reorganized, may be is a good idea to split Graphics folder to two folders like AtomicEngine (it has folders Graphics, Atomic2D, Atomic3D).

**Comment by cadaver** [comment]
It could be, but it's a separate issue. There are actually four kinds of graphics classes:
- Graphics low level core classes (Graphics, VertexBuffer, Texture2D)
- High level rendering core classes (View, Batch, Drawable, Octree)
- 3D-specific high level rendering classes (StaticModel, BillboardSet)
- 2D-specific high level rendering classes (Urho2D module)

**Comment by 1vanK** [comment]
```
It could be, but it's a separate issue. There are actually four kinds of graphics classes:

Graphics low level core classes (Graphics, VertexBuffer, Texture2D)
High level rendering core classes (View, Batch, Drawable, Octree)
3D-specific high level rendering classes (StaticModel, BillboardSet)
2D-specific high level rendering classes (Urho2D module)
```

What about of create separate scene-independet level:
* Graphics core (direct draw calls)
* Draw models including skinned (without any info about scenes, all required data can set manually)
* Scene and nodes based on previous level (fill required data)

Just sometimes need to draw models without using scene overhead, checking visibility and other

**Comment by cadaver** [comment]
Not sure if it can be layered that way efficiently. Probably some kind of DrawDrawableImmediate could be done, but it would be a less performant compromise. Also consider the execution of renderpath, which works based on renderqueues that have been collected based on which objects' materials use which pass.
