### ISSUE TITLE
Physics components fail with zero quaternion

### ISSUE THREAD

**Issue by SirNate0** [urho3d/Urho3D#1426]
When I loaded a scene where some nodes had a 0 0 0 0 quaternion, the graphics would display fine but the physics components did not seem to work - there were no collisions, and the editor would not display the triangle mesh when the component/node was selected. This was with a triangle mesh static body, exported from Blender. Manually changing the quaternions to 1 0 0 0 fixed it.

**Comment by cadaver** [comment]
A quaternion should be normalized. 0 0 0 0 is invalid and either Blender or the exporter are giving out invalid data. If rendering works, then it's mostly luck, but it's correct to expect physics not to work in that case. On the other hand, validating quaternions is a waste of CPU cycles.
