### ISSUE TITLE
Complex component properties

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1428]
I am going to make some complex component for procedural tree generation.
Linear structure of fixed amount properties is not enough.
I need some hierarchical structure that consitsts of (may be different) property groups.
How can I do it?

**Update:**
Oh okay, for my case XML config is the best solution.

**Comment by cadaver** [comment]
You could also use an attribute of type VariantMap or VariantVector. This should work code-wise, but you'd probably have to do work in the editor to add editing support. VariantVectors are already used for fixed repeating structures, like billboards or animation states (typically first value = amount of repeating sub-structures)
