### ISSUE TITLE
UIElement::SetDeepEnabled has incorrect implementation?

### ISSUE THREAD

**Issue by tiberiusbrown** [urho3d/Urho3D#1432]
The [UIElement header](https://github.com/urho3d/Urho3D/blob/master/Source/Urho3D/UI/UIElement.h#L271) says that `UIElement::SetDeepEnabled` remembers each element's enabled state so that it can be recalled with `UIElement::ResetDeepEnabled`. 

However, it looks like the [relevant line](https://github.com/urho3d/Urho3D/blob/master/Source/Urho3D/UI/UIElement.cpp#L853) is in fact inside the `UIElement::SetEnabledRecursive` method, not `UIElement::SetDeepEnabled`.

**Comment by hdunderscore** [comment]
If you call SetDeepEnabled() a few times, then call ResetDeepEnabled() you will reset to before any SetDeepEnabled() calls. 

On the other hand SetEnabledRecursive() will record the previous state each change, so ResetDeepEnabled() would only change to what was prior to the last SetEnabledRecursive().

I believe it's correctly implemented.
