### ISSUE TITLE
'Resized scratch buffer to size' message floods the log.

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1434]
STR:

1. Open empty scene in editor
2. Add some light (must be visible to editor camera).
3. **DEBUG mode!**

Then log is flooded with tons of messages like 
`Resized scratch buffer to size 0`
`Resized scratch buffer to size 12`

'Log' means F1-console in editor.
I am worry that this could be a sign of some non-optimal reallocations...

**Update**: Huh, it doesn't reproduce so easy...
**Update 2**: Okay, you also must run Editor in Debug mode

**Comment by cadaver** [comment]
This is benign / normal, and shown only in the debug log mode. However it could be examined whether the constant "bouncing" resize could be eliminated.
