### ISSUE TITLE
Different materials for different LODs

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1435]
E.g. I have tree model that use Material 1 and 2 for first LODs. And the last LOD of this model is proxy billboard with Material 3. Is it possible to implement it in scope of StaticModel functionality?

Number of materials is equal to number of batches. Number of batches is equal to number of geometries. Geometries have LODs.
Soo... I can create three geometries. But it would be hard to link their LODs.

PS: Of course, I always can write my own StaticModel with blackjack and loods..

**Comment by cadaver** [comment]
Material itself can define techniques that change according to LOD distance, but the current system doesn't support actual different materials for LODs, or different amount of batches/materials in different LODs.

A custom drawable should be the easiest solution for getting what you want.

**Comment by Hevedy** [comment]
Yeah in UE4 you can assign per LOD/Mesh materials, could be good to see here the same
