### ISSUE TITLE
the MessageBox class asserts in c++ in the HandleMessageAcknowledged() function due to refCount = 0

### ISSUE THREAD

**Issue by Lumak** [urho3d/Urho3D#1439]
This works find in AS script because the reference count is incremented in the script constructor:
static MessageBox* ConstructMessageBox(const String& messageString, const String& titleString, XMLFile* layoutFile, XMLFile* styleFile)
{
    SharedPtr<MessageBox> messageBox(new MessageBox(GetScriptContext(), messageString, titleString, layoutFile, styleFile));
    if (messageBox)
        messageBox->AddRef();
    return messageBox.Get();
}

My solution to fix this was to move the add reference count in the actual MessageBox constructor and remove the one in the ConstructMessageBox()

**Comment by cadaver** [comment]
The MessageBox is a bit dangerous class as it's trying to effect its own destruction. Maybe "least dangerous" solution would be to refactor it as a UIElement subclass, in which case it could remove itself from the UI hierarchy when needed, and this would result in its destruction if no strong refs are held elsewhere.

**Comment by Lumak** [comment]
In my opinion, this shouldn't be refactored in the UIElement subclass because I tend to hold SharedPtr and WeakPtrs references to various parent UIElements and this could potentially cause problems.  It would require various scenarios to see if this won't break destruct sequence.

From what I see, the MessageBox is the only class that self destructs, and the current implementation of incrementing the refcount for the script works properly. Moving it to the MessageBox constructor require minimal testing.

**Comment by cadaver** [comment]
I don't see much possibility for things going wrong if it's added as a root (top) level modal element, then removes itself from hierarchy when dismissed. If it's still alive after that due to the user holding a strong reference, it's already inactive from a UI standpoint, so there's no harm done.

**Comment by Lumak** [comment]
OK, I trust your judgement.

**Comment by weitjong** [comment]
Also see the discussion here #634.

**Comment by OvermindDL1** [comment]
I'd say change the MessageBox to send a callback but otherwise not destroy itself, that should be done only in the callback via the user.  Explicit is better than implicit.
