### ISSUE TITLE
bool Serializable::LoadXML(const XMLElement& source, bool setInstanceDefault) function doesn't parse AM_DEFAULT attributes

### ISSUE THREAD

**Issue by Lumak** [urho3d/Urho3D#1440]
Not sure if this is a bug or intended design, but the 
bool Serializable::LoadXML(const XMLElement& source, bool setInstanceDefault)
function does not parse AM_DEFAULT attributes and I'm having to duplicate the exact code in the derived class, e.g. Vehicle, with the AM_DEFAULT mask.

**Comment by cadaver** [comment]
This sounds fishy, as if this was true most of Urho inbuilt classes' attributes wouldn't work. It checks attr.mode_ & AM_FILE (1) which should be satisfied by AM_DEFAULT. (3) Check that your class has its typename set up correctly and its attributes are being registered to Context.

**Comment by Lumak** [comment]
I'll verify.

**Comment by Lumak** [comment]
Verified that the AM_DEFAULT arguments are not parsed.  Here was my test setup:
1) override the bool LoadXML(const XMLElement& source, bool setInstanceDefault) function in my Vehicle.cpp
2) changed various AM_DEFAULT default variables in my constructor so that they are different than the values defined in my .xml (prefab) file.
3) break at entry to my LoadXML() function and observed that the variables are still the same as how it was initialized in my constructor.
4) parse the arguments with the AM_DEFAULT mask (exactly same as how Serializable class does it) and see the values changed to what's defined in my .xml file.

Yeah, AM_DEFAULT variables are not changed by the time it gets to my overriden LoadXML() function, not sure if it's supposed to happens after that.

**Comment by Lumak** [comment]
Here is my overriden LoadXML() funtion.  The Animatable::LoadXML() function is called first to ensure the Serializable class pares the data before I start messing with the values.
==========================================================
bool Vehicle::LoadXML(const XMLElement& source, bool setInstanceDefault)
{
    if ( !Animatable::LoadXML(source,setInstanceDefault) )
        return false;

    const Vector<AttributeInfo>* attributes = GetAttributes();
    if (!attributes)
        return true;

    XMLElement attrElem = source.GetChild("attribute");
    unsigned startIndex = 0;

    while (attrElem)
    {
        String name = attrElem.GetAttribute("name");
        unsigned i = startIndex;
        unsigned attempts = attributes->Size();

        while (attempts)
        {
            const AttributeInfo& attr = attributes->At(i);

            if ((attr.mode_ & AM_DEFAULT) && !attr.name_.Compare(name, true))
            {
                Variant varValue;

                // If enums specified, do enum lookup and int assignment. Otherwise assign the variant directly
                if (attr.enumNames_)
                {
                    String value = attrElem.GetAttribute("value");
                    bool enumFound = false;
                    int enumValue = 0;
                    const char** enumPtr = attr.enumNames_;
                    while (*enumPtr)
                    {
                        if (!value.Compare(*enumPtr, false))
                        {
                            enumFound = true;
                            break;
                        }
                        ++enumPtr;
                        ++enumValue;
                    }
                    if (enumFound)
                        varValue = enumValue;
                }
                else
                    varValue = attrElem.GetVariantValue(attr.type_);

                if (!varValue.IsEmpty())
                {
                    OnSetAttribute(attr, varValue);
                }

                startIndex = (i + 1) % attributes->Size();
                break;
            }
            else
            {
                i = (i + 1) % attributes->Size();
                --attempts;
            }
        }

        attrElem = attrElem.GetNext("attribute");
    }

    return true;
}

**Comment by cadaver** [comment]
At this point I believe you should supply a minimal full application code, where it registers your class and tries to use it. Otherwise it's hard to know what's exactly going wrong and we're just guessing.

**Comment by Lumak** [comment]
Disregard this, it's not a bug.  Breaking at my entry at LoadXML() does show the variables are not changed **because I have yet called the Animatable::LoadXML(source,setInstanceDefault) function**

Sorry for wasting your time.
