### ISSUE TITLE
Take ownership of android.toolchain.cmake development

### ISSUE THREAD

**Issue by weitjong** [urho3d/Urho3D#1441]
[All done] This is a question and not necessarily becomes an issue that we need to solve (depends on the feedback). On one hand the development of this toolchain file seems to stale at the upstream. On the other hand, we have deviated more and more from the original version. Personally, I hate to add the "Urho3D" modification tags every time I need to change things, and I also found a few weirdness in that toolchain file that I am not able to fully explain. It is the most complicated toolchain file that we currently have. Our custom toolchain files are much straightforward in comparison. i.e. We may be paying the price of things that we don't actually need.

It is not a CMake standard module at any rate, so I don't think it is terribly wrong if we have our own custom Android toolchain file. We could still track the upstream changes, if any, even after we have developed our custom version, of course.

What say you?

**Comment by cadaver** [comment]
I'm fine with this change, since it's not official / standard anyway. No idea how well it works, but I saw that Allegro's Android CMake toolchain is the same size as our other toolchains, so I imagine it can be slimmed down a bit :)

**Comment by weitjong** [comment]
Thanks for your prompt reply. I have just a quick glanced on Allegro's implementation and I think theirs is too simplistic (I don't think it would work with clang compiler toolchain, for instance). So, if/when we  do this, it will be probably slightly more than that but surely much less than what we currently have - it would be uniquely ours.

**Comment by weitjong** [comment]
Things that expect to be changed:

- Drop support for Android NDK prior to r11.
- Drop support for standalone toolchain.
- Default to use clang compiler toolchain but GCC is 4.9 still supported.

Otherwise, all the existing options are kept for backward compatibility.

**Comment by weitjong** [comment]
It takes me longer than I expected (as usual). Instead of just trimming the bits from the existing android.toolchain.cmake file, I am actually spreading its good bits to the rest of our toolchain files :smile: . Anyway, I am currently examining the ```-fdata-sections -ffunction-sections -Wl,--gc-sections``` flags, it seems that these flags could be beneficial for other embedded Linux build as well (probably on iOS too if Xcode hasn't added that flags behind the scene). I am also considering adding an option to bring back the ```-fstack-protector-strong``` flag. The ndk-build uses this new flag after it is available in 4.9 (used to be ```-fstack-protector``` in 4.8), however, someone has intentionally removed the stack protector flag in the existing android.tool.cmake file, not sure since when, but I guess it makes sense for game applications where speed is paramount. However, other applications may require the flag for better security. The new option will be off by default for backward compatibility. Let me know if any of you have other opinions.

**Comment by weitjong** [comment]
Quick update: contrarily to my expected result, the ```-fdata-sections -ffunction-sections -Wl,--gc-sections``` flags does not reduce the target binary size but actually increases it slightly (tested using our samples using SHARED lib type). No changes in size when using STATIC lib type. What gives? Does it mean our codebase is so good that there are actually little dead code so there is nothing to be eliminated at all during linking phase so the above flags to split the sections become just an overhead without actually giving us any benefit[?]

**Comment by weitjong** [comment]
I have a dilemma. I want the new toolchain file to be usable for other projects too, so I have written it as universal as possible. However, I also want to have a tight integration with Urho3D build system as whole, like it should understand URHO3D-specific build options and ways of configuring Android build tree. I think I would end up with having two versions of the file. One tailored for Urho3D and one "upstream" version without Urho3D-specific logic. The upstream version will probably be hosted in my personal repo, It will be using MIT license, so it should make no diff to Urho3D project.

**Comment by hdunderscore** [comment]
I think that should be good, probably useful to others, and even Urho users who happen to want to make an android project without Urho.

**Comment by weitjong** [comment]
The new Android toolchain file is almost ready now. There are many code branches that I need to verify, but at least I had a first success using 'gnustl_static' STL runtime. This is the runtime we have been using all this time. However, I plan to default it to LLVM 'c++_static', if it makes sense.

**Comment by weitjong** [comment]
I have done testing using "stlport_static" and "stlport_shared" (when URHO3D_NETWORK is disabled), and "gnustl_shared" and also "c++_shared" too. The latter two require a small fix in our Android sample launcher so that it understands how to  handle C++ STL runtime shared library correctly in the apk. What stopping me now is the "c++_static". I got these errors:
```
/home/weitjong/SDKs/android-ndk-r11c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: error: /home/weitjong/SDKs/android-ndk-r11c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/armv7-a/thumb/libgcc.a(pr-support.o): multiple definition of '_Unwind_GetRegionStart'
/home/weitjong/SDKs/android-ndk-r11c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: /home/weitjong/SDKs/android-ndk-r11c/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/thumb/libc++_static.a(Unwind-EHABI.o): previous definition here
/home/weitjong/SDKs/android-ndk-r11c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: error: /home/weitjong/SDKs/android-ndk-r11c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/armv7-a/thumb/libgcc.a(pr-support.o): multiple definition of '_Unwind_GetLanguageSpecificData'
/home/weitjong/SDKs/android-ndk-r11c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: /home/weitjong/SDKs/android-ndk-r11c/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/thumb/libc++_static.a(Unwind-EHABI.o): previous definition here
collect2: error: ld returned 1 exit status
Source/Urho3D/CMakeFiles/Urho3D.dir/build.make:7590: recipe for target 'libs/armeabi-v7a/libUrho3D.so' failed
gmake[2]: *** [libs/armeabi-v7a/libUrho3D.so] Error 1
CMakeFiles/Makefile2:1408: recipe for target 'Source/Urho3D/CMakeFiles/Urho3D.dir/all' failed
gmake[1]: *** [Source/Urho3D/CMakeFiles/Urho3D.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
gmake: *** [all] Error 2
```
I think I know why it happened but I cannot find a clean solution to fix it yet. The libc++_static.a has defined a few symbols that clash with libgcc.a. This happened regardless of whether GCC or Clang is used as the compiler toolchain. Probably related to https://code.google.com/p/android/issues/detail?id=73907

**Comment by weitjong** [comment]
Just when I thought it was almost ready, last night I realized Android NDK r12b made quite some drastic changes on how ndk-build works. The ''armeabi-v7a-hard' ABI is being dropped in r12 and GCC is planned to be removed all together in r13. It appears that I have chosen a challenging time to do this work.

**Comment by weitjong** [comment]
Finally I got the LLVM libc++ (both static and shared) working as well but it needs Android NDK r12b to pull it off. So, that version will be the minimum version required for the new Android toolchain file.

**Comment by sabotage3d** [comment]
I am still getting the same error from https://github.com/urho3d/Urho3D/issues/1616
```
error:
      non-const lvalue reference to type '__builtin_va_list' cannot bind to a value of unrelated type 'va_list'

```
I clonned refactor-buildsystem in a new folder. I adde these flags to cmake_android.sh
```
$(dirname $0)/cmake_generic.sh "$@" \
	-DANDROID=1 \
    -DCMAKE_BUILD_TYPE=Release \
    -DANDROID_ABI="armeabi-v7a" \
    -DANDROID_NATIVE_API_LEVEL=android-19 \
    -DANDROID_FORCE_ARM_BUILD=TRUE \
    -DANDROID_STL=c++_static \
```

**Comment by weitjong** [comment]
Try turning off PCH by passing URHO3D_PCH=0 too. Do you use ccache? What version? Also which version of CMake?

**Comment by sabotage3d** [comment]
Thanks a lot it works now. I tried the samples on Android 6 and everything seems to work.

**Comment by sabotage3d** [comment]
Should I make a separate issue. When I use cmake_android.sh inside my project tree before it was generating properly AndroidManifest.xml and all the other files needed for packaging for Android now it just generate only the NDK files and I have to manually copy all of these from Urho3D Android folder.

**Comment by weitjong** [comment]
It has been awhile but I don't think I have touched anything else except
replacing the toolchain file. I could be wrong though. As long as your
project is structured based on Urho project then you can reuse the same
script used by Urho to generate the build tree for your own project. Are
you saying when using master branch then everything is fine?

**Comment by sabotage3d** [comment]
I noticed the change from 1.5 to 1.6. As my old project no longer build the same way.

**Comment by weitjong** [comment]
> Try turning off PCH by passing URHO3D_PCH=0 too. Do you use ccache? What version? Also which version of CMake?

I was actually you could provide answers to those questions. If you don't use ccache at all and yet also encountered the PCH issue then it means I have been barking up the wrong tree. I looks like culprit may well be newer CMake instead of newer ccache. I will investigate this later when I have time.

**Comment by rokups** [comment]
Speaking of new cmake - i needed [this patch](https://github.com/rokups/Urho3D/commit/0be6a4b673ec82e45e9c40ddca0eb774361c9482) to make engine build and silence bunch of warnings.

**Comment by weitjong** [comment]
This issue is for (b)logging the development progress of a brand new ```Android.cmake``` toolchain file in the ```refactor-buildsystem``` branch. The old/existing toolchain file in the master branch will be replaced by this new one when the refactor branch is eventually merged. It won't happen any time soon though. The new toolchain file is a total new rewrite from scratch and only supports Android NDK 12b onward.
