### ISSUE TITLE
KEY_ESC was not renamed to KEY_ESCAPE on the scripting API page of the documentation

### ISSUE THREAD

**Issue by BlueMagnificent** [urho3d/Urho3D#1446]
Seems to be a subtle omission

**Comment by cadaver** [comment]
If you use the version selector dropdown and choose "HEAD" version you should see that it is updated.

**Comment by BlueMagnificent** [comment]
Thanks alot, I totally forgot that. Though I noticed it in a local documentation build I guess I need to check it again
