### ISSUE TITLE
No OpenGL support in video driver

### ISSUE THREAD

**Issue by TheWilfen** [urho3d/Urho3D#1449]
I get this error after building latest master:
`ERROR: Could not create window, root cause: 'No OpenGL support in video driver'`
Everything worked just fine with 1.5 release

**Comment by weitjong** [comment]
In the master branch we are using CMake auto-detection mechanism, that is available after SDL 2.0.4 upgrade, to automatically switch on or off some options based on the detection results. It works correctly most of the time now, at least on all my test VMs. The error that you got indicates something is wrong with your GL installation that might cause the auto-detection to fail to detect that you have GL installed and switch the GL option to off at the time the build tree was configured/generated. Urho wanted to use OpenGL but SDL didn't have the OpenGL support built-in, hence the error. Are you experiencing this issue on a same machine that you have a success with 1.5? If yes, then you may have found a bug and we will need a full output log from CMake when it performs the initial configuration/generation to investigate this further. If no, then make sure you have installed GL correctly and test that your GL is working before re-attempting to generate a new build tree from scratch.

**Comment by TheWilfen** [comment]
I found that it may be caused because CMake turns off render subsystem when genarating makefile but I have no idea how to change it. I also tried installing Nvidia drivers but it doesn't change anything. And as I mentioned before it worked in 1.5 with no problems and GL is working in every other app.

**Comment by TheWilfen** [comment]
here's the CMake log:
`-- Found Readline: /usr/lib/x86_64-linux-gnu/libreadline.so  
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Performing Test HAVE_GCC_ATOMICS
-- Performing Test HAVE_GCC_ATOMICS - Success
-- Performing Test HAVE_GCC_PREFERRED_STACK_BOUNDARY
-- Performing Test HAVE_GCC_PREFERRED_STACK_BOUNDARY - Failed
-- Performing Test HAVE_GCC_WALL
-- Performing Test HAVE_GCC_WALL - Success
-- Performing Test HAVE_GCC_WSHADOW
-- Performing Test HAVE_GCC_WSHADOW - Success
-- Performing Test HAVE_NO_UNDEFINED
-- Performing Test HAVE_NO_UNDEFINED - Success
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdio.h
-- Looking for stdio.h - found
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Looking for stdarg.h
-- Looking for stdarg.h - found
-- Looking for malloc.h
-- Looking for malloc.h - found
-- Looking for memory.h
-- Looking for memory.h - found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for strings.h
-- Looking for strings.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for ctype.h
-- Looking for ctype.h - found
-- Looking for math.h
-- Looking for math.h - found
-- Looking for iconv.h
-- Looking for iconv.h - found
-- Looking for signal.h
-- Looking for signal.h - found
-- Looking for 8 include files stdint.h, ..., dlfcn.h
-- Looking for 8 include files stdint.h, ..., dlfcn.h - found
-- Looking for M_PI
-- Looking for M_PI - found
-- Looking for sys/mman.h
-- Looking for sys/mman.h - found
-- Looking for strtod
-- Looking for strtod - found
-- Looking for malloc
-- Looking for malloc - found
-- Looking for calloc
-- Looking for calloc - found
-- Looking for realloc
-- Looking for realloc - found
-- Looking for free
-- Looking for free - found
-- Looking for getenv
-- Looking for getenv - found
-- Looking for setenv
-- Looking for setenv - found
-- Looking for putenv
-- Looking for putenv - found
-- Looking for unsetenv
-- Looking for unsetenv - found
-- Looking for qsort
-- Looking for qsort - found
-- Looking for abs
-- Looking for abs - found
-- Looking for bcopy
-- Looking for bcopy - found
-- Looking for memset
-- Looking for memset - found
-- Looking for memcpy
-- Looking for memcpy - found
-- Looking for memmove
-- Looking for memmove - found
-- Looking for memcmp
-- Looking for memcmp - found
-- Looking for strlen
-- Looking for strlen - found
-- Looking for strlcpy
-- Looking for strlcpy - not found
-- Looking for strlcat
-- Looking for strlcat - not found
-- Looking for strdup
-- Looking for strdup - found
-- Looking for _strrev
-- Looking for _strrev - not found
-- Looking for _strupr
-- Looking for _strupr - not found
-- Looking for _strlwr
-- Looking for _strlwr - not found
-- Looking for strchr
-- Looking for strchr - found
-- Looking for strrchr
-- Looking for strrchr - found
-- Looking for strstr
-- Looking for strstr - found
-- Looking for itoa
-- Looking for itoa - not found
-- Looking for _ltoa
-- Looking for _ltoa - not found
-- Looking for _uitoa
-- Looking for _uitoa - not found
-- Looking for _ultoa
-- Looking for _ultoa - not found
-- Looking for strtol
-- Looking for strtol - found
-- Looking for strtoul
-- Looking for strtoul - found
-- Looking for _i64toa
-- Looking for _i64toa - not found
-- Looking for _ui64toa
-- Looking for _ui64toa - not found
-- Looking for strtoll
-- Looking for strtoll - found
-- Looking for strtoull
-- Looking for strtoull - found
-- Looking for atoi
-- Looking for atoi - found
-- Looking for atof
-- Looking for atof - found
-- Looking for strcmp
-- Looking for strcmp - found
-- Looking for strncmp
-- Looking for strncmp - found
-- Looking for _stricmp
-- Looking for _stricmp - not found
-- Looking for strcasecmp
-- Looking for strcasecmp - found
-- Looking for _strnicmp
-- Looking for _strnicmp - not found
-- Looking for strncasecmp
-- Looking for strncasecmp - found
-- Looking for vsscanf
-- Looking for vsscanf - found
-- Looking for vsnprintf
-- Looking for vsnprintf - found
-- Looking for fseeko
-- Looking for fseeko - found
-- Looking for fseeko64
-- Looking for fseeko64 - found
-- Looking for sigaction
-- Looking for sigaction - found
-- Looking for setjmp
-- Looking for setjmp - found
-- Looking for nanosleep
-- Looking for nanosleep - found
-- Looking for sysconf
-- Looking for sysconf - found
-- Looking for sysctlbyname
-- Looking for sysctlbyname - not found
-- Looking for pow in m
-- Looking for pow in m - found
-- Looking for atan
-- Looking for atan - found
-- Looking for atan2
-- Looking for atan2 - found
-- Looking for ceil
-- Looking for ceil - found
-- Looking for copysign
-- Looking for copysign - found
-- Looking for cos
-- Looking for cos - found
-- Looking for cosf
-- Looking for cosf - found
-- Looking for fabs
-- Looking for fabs - found
-- Looking for floor
-- Looking for floor - found
-- Looking for log
-- Looking for log - found
-- Looking for pow
-- Looking for pow - found
-- Looking for scalbn
-- Looking for scalbn - found
-- Looking for sin
-- Looking for sin - found
-- Looking for sinf
-- Looking for sinf - found
-- Looking for sqrt
-- Looking for sqrt - found
-- Looking for sqrtf
-- Looking for sqrtf - found
-- Looking for tan
-- Looking for tan - found
-- Looking for tanf
-- Looking for tanf - found
-- Looking for acos
-- Looking for acos - found
-- Looking for asin
-- Looking for asin - found
-- Looking for iconv_open in iconv
-- Looking for iconv_open in iconv - not found
-- Looking for alloca.h
-- Looking for alloca.h - found
-- Performing Test HAVE_ALLOCA
-- Performing Test HAVE_ALLOCA - Success
-- Performing Test HAVE_SA_SIGACTION
-- Performing Test HAVE_SA_SIGACTION - Success
-- Looking for dlopen
-- Looking for dlopen - not found
-- Looking for dlopen in dl
-- Looking for dlopen in dl - found
-- Performing Test HAVE_DLOPEN
-- Performing Test HAVE_DLOPEN - Success
-- Performing Test HAVE_PTHREADS
-- Performing Test HAVE_PTHREADS - Success
-- Performing Test HAVE_RECURSIVE_MUTEXES
-- Performing Test HAVE_RECURSIVE_MUTEXES - Success
-- Performing Test HAVE_PTHREADS_SEM
-- Performing Test HAVE_PTHREADS_SEM - Success
-- Performing Test HAVE_SEM_TIMEDWAIT
-- Performing Test HAVE_SEM_TIMEDWAIT - Success
-- Performing Test HAVE_PTHREAD_NP_H
-- Performing Test HAVE_PTHREAD_NP_H - Failed
-- Looking for pthread_setname_np
-- Looking for pthread_setname_np - found
-- Looking for pthread_set_name_np
-- Looking for pthread_set_name_np - not found
-- Found OSS: /usr/include/x86_64-linux-gnu  
-- Found ALSA: /usr/lib/x86_64-linux-gnu/libasound.so (found version "1.1.0") 
-- Could NOT find PulseAudio development library (missing:  PULSEAUDIO_LIBRARIES PULSEAUDIO_INCLUDE_DIRS) 
-- Could NOT find Esound development library (missing:  ESOUND_LIBRARIES ESOUND_INCLUDE_DIRS) 
-- Could NOT find aRts development library (missing:  ARTS_LIBRARIES ARTS_INCLUDE_DIRS) 
-- Could NOT find NetworkAudioSystem development library (missing:  NAS_LIBRARIES NAS_INCLUDE_DIRS) 
-- Could NOT find RoarAudio development library (missing:  SNDIO_LIBRARIES SNDIO_INCLUDE_DIRS) 
-- Looking for X11/Xcursor/Xcursor.h
-- Looking for X11/Xcursor/Xcursor.h - not found
-- Looking for X11/extensions/Xinerama.h
-- Looking for X11/extensions/Xinerama.h - not found
-- Looking for X11/extensions/XInput2.h
-- Looking for X11/extensions/XInput2.h - not found
-- Looking for X11/extensions/Xrandr.h
-- Looking for X11/extensions/Xrandr.h - found
-- Looking for X11/extensions/Xrender.h
-- Looking for X11/extensions/Xrender.h - found
-- Looking for X11/extensions/shape.h
-- Looking for X11/extensions/shape.h - found
-- Looking for X11/extensions/scrnsaver.h
-- Looking for X11/extensions/scrnsaver.h - not found
-- Looking for 3 include files X11/Xlib.h, ..., X11/extensions/Xdbe.h
-- Looking for 3 include files X11/Xlib.h, ..., X11/extensions/Xdbe.h - found
-- Looking for 3 include files X11/Xlib.h, ..., X11/extensions/Xext.h
-- Looking for 3 include files X11/Xlib.h, ..., X11/extensions/Xext.h - found
-- Looking for include files X11/Xlib.h, X11/extensions/xf86vmode.h
-- Looking for include files X11/Xlib.h, X11/extensions/xf86vmode.h - found
-- Looking for shmat
-- Looking for shmat - found
-- Performing Test HAVE_CONST_XEXT_ADDDISPLAY
-- Performing Test HAVE_CONST_XEXT_ADDDISPLAY - Success
-- Performing Test HAVE_XGENERICEVENT
-- Performing Test HAVE_XGENERICEVENT - Success
-- Looking for XkbKeycodeToKeysym
-- Looking for XkbKeycodeToKeysym - found
-- Could NOT find Mir display server (missing:  MIR_CLIENT_INCLUDE_DIR MIR_COMMON_INCLUDE_DIR) 
-- Performing Test HAVE_VIDEO_OPENGL
-- Performing Test HAVE_VIDEO_OPENGL - Success
-- Performing Test HAVE_VIDEO_OPENGL_EGL
-- Performing Test HAVE_VIDEO_OPENGL_EGL - Success
-- Performing Test HAVE_VIDEO_OPENGLES_V1
-- Performing Test HAVE_VIDEO_OPENGLES_V1 - Failed
-- Performing Test HAVE_VIDEO_OPENGLES_V2
-- Performing Test HAVE_VIDEO_OPENGLES_V2 - Success
-- Found Wayland: /usr/lib/x86_64-linux-gnu/libwayland-client.so  
-- Performing Test HAVE_VIDEO_VIVANTE_VDK
-- Performing Test HAVE_VIDEO_VIVANTE_VDK - Failed
-- Performing Test HAVE_VIDEO_VIVANTE_EGL_FB
-- Performing Test HAVE_VIDEO_VIVANTE_EGL_FB - Failed
-- Performing Test HAVE_INPUT_EVENTS
-- Performing Test HAVE_INPUT_EVENTS - Success
-- Performing Test HAVE_INPUT_KD
-- Performing Test HAVE_INPUT_KD - Success
-- Looking for libudev.h
-- Looking for libudev.h - found
-- Looking for dbus/dbus.h
-- Looking for dbus/dbus.h - not found
-- Looking for tslib.h
-- Looking for tslib.h - not found
-- 
-- SDL2 was configured with the following options:
-- 
-- Platform: Linux-4.4.0-28-generic
-- 64-bit:   TRUE
-- Compiler: /usr/bin/cc
-- 
-- Subsystems:
--   Atomic:     ON
--   Audio:      ON
--   Video:      ON
--   Render:     OFF
--   Events:     ON
--   Joystick:   ON
--   Haptic:     ON
--   Power:      ON
--   Threads:    ON
--   Timers:     ON
--   File:       ON
--   Loadso:     ON
--   CPUinfo:    ON
--   Filesystem: ON
--   Dlopen:     ON
-- 
-- Options:
--   ALSA                   (Wanted: ON): ON
--   ALSA_SHARED            (Wanted: ON): ON
--   ARTS                   (Wanted: ON): OFF
--   ARTS_SHARED            (Wanted: ON): OFF
--   ASSEMBLY               (Wanted: ON): ON
--   ASSERTIONS             (Wanted: auto): auto
--   CLOCK_GETTIME          (Wanted: ON): ON
--   DIRECTFB_SHARED        (Wanted: OFF): OFF
--   DISKAUDIO              (Wanted: ON): ON
--   DUMMYAUDIO             (Wanted: ON): ON
--   ESD                    (Wanted: ON): OFF
--   ESD_SHARED             (Wanted: ON): OFF
--   FUSIONSOUND            (Wanted: OFF): OFF
--   FUSIONSOUND_SHARED     (Wanted: OFF): OFF
--   GCC_ATOMICS            (Wanted: ON): ON
--   INPUT_TSLIB            (Wanted: ON): OFF
--   LIBC                   (Wanted: ON): ON
--   MIR_SHARED             (Wanted: ON): OFF
--   NAS                    (Wanted: ON): OFF
--   NAS_SHARED             (Wanted: ON): OFF
--   OSS                    (Wanted: ON): ON
--   PTHREADS               (Wanted: ON): ON
--   PTHREADS_SEM           (Wanted: ON): ON
--   PULSEAUDIO             (Wanted: ON): OFF
--   PULSEAUDIO_SHARED      (Wanted: ON): OFF
--   SDL_DLOPEN             (Wanted: ON): ON
--   SDL_HAPTIC             (Wanted: ON): ON
--   SNDIO                  (Wanted: ON): OFF
--   VIDEO_COCOA            (Wanted: OFF): OFF
--   VIDEO_DIRECTFB         (Wanted: OFF): OFF
--   VIDEO_DUMMY            (Wanted: ON): ON
--   VIDEO_MIR              (Wanted: ON): OFF
--   VIDEO_OPENGL           (Wanted: ON): ON
--   VIDEO_OPENGLES         (Wanted: ON): ON
--   VIDEO_RPI              (Wanted: OFF): OFF
--   VIDEO_VIVANTE          (Wanted: ON): OFF
--   VIDEO_WAYLAND          (Wanted: ON): ON
--   VIDEO_WAYLAND_QT_TOUCH (Wanted: OFF): OFF
--   VIDEO_X11              (Wanted: ON): ON
--   VIDEO_X11_XCURSOR      (Wanted: ON): OFF
--   VIDEO_X11_XINERAMA     (Wanted: ON): OFF
--   VIDEO_X11_XINPUT       (Wanted: ON): OFF
--   VIDEO_X11_XRANDR       (Wanted: ON): ON
--   VIDEO_X11_XSCRNSAVER   (Wanted: ON): OFF
--   VIDEO_X11_XSHAPE       (Wanted: ON): ON
--   VIDEO_X11_XVM          (Wanted: ON): ON
--   WAYLAND_SHARED         (Wanted: ON): ON
--   X11_SHARED             (Wanted: ON): ON
-- 
--  CFLAGS:        -march=native -ffast-math -pthread -fdiagnostics-color=auto
--  EXTRA_CFLAGS:  -Wshadow -Wall 
--  EXTRA_LDFLAGS: -Wl,--no-undefined
--  EXTRA_LIBS:    rt;m;dl;GL
-- 
-- Looking for sincosf in m
-- Looking for sincosf in m - found
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Found Urho3D: as CMake target
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/thewilfen/Urho3D
`

**Comment by TheWilfen** [comment]
It's something wrong just with makefiles, everything works with Ninja.

**Comment by weitjong** [comment]
I actually do not see anything wrong in the log. The auto detection mechanism does not change a thing based on the chosen CMake generator. To me, it seems it has detected GL and enabled the GL support in both Makefile and Ninja cases. So, there is something else at play here. It would be great if we could isolate it and find its root cause before 1.6 is being released.

**Comment by phoenix1796** [comment]
Any updates on this issue ?
I am also facing the same issue with the code on master branch.

**Comment by phoenix1796** [comment]
I tried using ninja and it worked perfectly , 

As can be seen here , this time OPENGL was detected fine

$ cat CMakeCache.txt  | grep OPEN
//build the OPENGEX importer
ASSIMP_BUILD_OPENGEX_IMPORTER:BOOL=ON
SDL_DLOPEN:BOOL=ON
VIDEO_OPENGL:BOOL=ON
VIDEO_OPENGLES:BOOL=ON
DLOPEN_FOUND:INTERNAL=
DLOPEN_LIB_dl_FOUND:INTERNAL=1
//URHO3D_OPENGL build option when Doxyfile was last generated
DOXYFILE_URHO3D_OPENGL:INTERNAL=TRUE
//Test HAVE_DLOPEN
HAVE_DLOPEN:INTERNAL=1
//Test HAVE_VIDEO_OPENGL
HAVE_VIDEO_OPENGL:INTERNAL=1
//Test HAVE_VIDEO_OPENGLES_V1
HAVE_VIDEO_OPENGLES_V1:INTERNAL=
//Test HAVE_VIDEO_OPENGLES_V2
HAVE_VIDEO_OPENGLES_V2:INTERNAL=
//Test HAVE_VIDEO_OPENGL_EGL
HAVE_VIDEO_OPENGL_EGL:INTERNAL=
