### ISSUE TITLE
Minor changes in Container

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1457]
I suggest some changes in Urho3D.Container that I found useful during writing some code that uses Urho3D as C++ library.

1. Add nullptr_t ctors to SharedPtr and WeakPtr (guarded by URHO3D_CXX11). This allows to write `foo(nullptr)` or `return nullptr` instead of `return SharedPtr<SomeClass>()`
2. Add aggregate ctor to PODVector (guarded by URHO3D_CXX11). It looks strange that Vector has aggregate ctor but PODVector doesn't.
3. Make [POD]Vector::Buffer() public. It allows to get rid of ugly `foo(&vec[0], vec.Size())` and _it prevents asserts if vector is empty_.

If you accept [some of] these changes I'll make PR.

**Comment by cadaver** [comment]
I believe all of these should be acceptable.

**Comment by cadaver** [comment]
PR merged, closing this.
