### ISSUE TITLE
Can't compile the engine since latest 'api-agnostic-headers' branch merge (DX11)

### ISSUE THREAD

**Issue by OldSnake22** [urho3d/Urho3D#1459]
Can't compile the engine since latest 'api-agnostic-headers' branch merge. (I'm using DX11 and CXX11)

1>...\Urho3D\Source\Urho3D\Graphics\Direct3D11\D3D11Graphics.cpp(234): error C2668: 'Urho3D::WeakPtr<Urho3D::Image>::WeakPtr' : ambiguous call to overloaded function

**Comment by OldSnake22** [comment]
Replacing windowIcon_(0), with windowIcon_(nullptr), fix the compiling issue.

**Comment by cadaver** [comment]
Do you have URHO3D_CXX11=1 enabled? Then this was overlooked when merging an earlier PR.

**Comment by OldSnake22** [comment]
Yes URHO3D_CXX11=1 is enabled :)
