### ISSUE TITLE
Pass custom command line arguments to editor script.

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1460]
Looks like command line parameters are parsed exclusively by Application and then interpret by Engine. Is where some way to access these parameters somewhere else?

**Comment by cadaver** [comment]
The command line arguments (GetArguments() function in ProcessUtils.h) are available in all scripting languages. Look at Editor.as, function ParseArguments, it's already using them to decide the scene / language to load at startup.
