### ISSUE TITLE
Render something in Editor only

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1461]
I know that editor in Urho3D is just script plugin over engine.
However, I am looking for some way to draw in Editor some simple _textured_ geometry related to some node that should be invisible during normal rendering.
How can I do it?

**Comment by cadaver** [comment]
Perhaps the most straightforward way is to run code in the editor that inspects the scene and creates additional temporary nodes / components (these won't be saved or shown in the hierarchy window) for the geometry you want to render. This is how the editor draws the debug icons. See the file bin\Data\Scripts\Editor\EditorViewDebugIcons.as

**Comment by cadaver** [comment]
Seems no further discussion / questions, so closing.
