### ISSUE TITLE
Build Failed on VS2008

### ISSUE THREAD

**Issue by rasteron** [urho3d/Urho3D#1464]
I just stumbled on this build issue by chance while checking out other projects, probably have something to do with C++11?

**Comment by weitjong** [comment]
That is an oxymoron, isn't it?

**Comment by rasteron** [comment]
Nope but perhaps drop the build files if you're no longer supporting it? 

https://github.com/urho3d/Urho3D/blob/master/cmake_vs2008.bat

**Comment by weitjong** [comment]
Our build system still support VS2018 if the C++11 option is not turned on. This option is not enabled by default, but certain build option combinations will force this enabled internally, like URHO3D_ANGELSCRIPT on Web platform. But otherwise, the conflict is caused by user own doing. Switching on C++11 standard on ancient VS "2008" is asking for trouble,  IMHO.

**Comment by rasteron** [comment]
> Our build system still support VS2018 if the C++11 option is not turned on. 

2018? that's VS2008. So, if you can't build the engine with the default build options on "ancient" VS2008, maybe just remove the 2008 build/bat file? 

> Switching on C++11 standard on ancient VS "2008" is asking for trouble, IMHO.

Obviously, so why still include the 2008 batch and related file(s)? I'm just submitting the issue here and actually not using it to do engine builds.

Just FYI.

**Comment by weitjong** [comment]
Oops, I meant 2008, of course. Typing using my phone is not a good idea, I guess  :)

VS2008 is still supported for now, if you manage your expectation what it can handle.

**Comment by rasteron** [comment]
Thanks. Ok so URHO3D_ANGELSCRIPT is not supported in VS2008, all platforms or only web? 

Maybe putting some note or info about this in the docs since it is still supported in some way. That's all.

**Comment by weitjong** [comment]
Yes, that's probably a good idea. On my count this combo will switch on C++11 on internally:

- URHO3D_ANGELSCRIPT on Web platform and Android/ARM platforms that use aarch64 architecture.
- URHO3D_DATABASE_ODBC on all platforms

**Comment by cadaver** [comment]
Verified that default option VS2008 build still works. I believe you can't register VS2008 Express any more but there's a regedit trick which allows you to circumvent this, at least for one month at a time.

**Comment by rasteron** [comment]
Ok noted, thanks.
