### ISSUE TITLE
Create RenderPath that renders n-th output of gbuffer

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1466]
Ok, I found pretty good solution
```
<renderpath>
    <rendertarget name="stub1" sizedivisor="1 1" format="rgba" />
    <rendertarget name="stub2" sizedivisor="1 1" format="rgba" />
    <rendertarget name="depth" sizedivisor="1 1" format="readabledepth" />
    <command type="clear" color="0 0 0 0" depth="1.0" stencil="0" depthstencil="depth" />
    <command type="scenepass" pass="deferred" marktostencil="true" vertexlights="true" metadata="gbuffer" depthstencil="depth">
        <output index="0" name="stub1" />
        <output index="1" name="stub2" />
        <output index="2" name="viewport" />
    </command>
</renderpath>
```

**Comment by cadaver** [comment]
I'd suggest to use the forum primarily for things that are questions on the use of the engine, and not actual bug reports or feature requests.

**Comment by eugeneko** [comment]
My first question was asked on the forum and I received approximatelly zero information there.
However, here I got enough information to implement anything I need.

Actually, this issue was originally 'why-it-does-not-work-is-it-bug'. And then I realized that I am an idiot.
