### ISSUE TITLE
issues with newly commits that affects particle appearance

### ISSUE THREAD

**Issue by yushli** [urho3d/Urho3D#1471]
The newly commits (possible the commit of https://github.com/urho3d/Urho3D/commit/b24bcb89282c2333c3b2a53d6ad423046be958d3) makes the particle effect appearance look different:
The particle effect is from https://github.com/LucKeyProductions/heXon/blob/master/Resources/Particles/BloodDrip.xml

Before:
<img width="651" alt="particle1" src="https://cloud.githubusercontent.com/assets/1681453/16877101/414a1706-4ad9-11e6-81ce-f67825a04b44.png">

After:
<img width="651" alt="particle2" src="https://cloud.githubusercontent.com/assets/1681453/16877285/f7407780-4ad9-11e6-9a5c-44ba335d49ca.png">

After the commit, the color becomes darker and some black.

**Comment by cadaver** [comment]
Thanks. It's probably the optimized directional billboard which needs to be checked, and especially on D3D11 which is picky of the vertex inputs & interpolators.

**Comment by cadaver** [comment]
I'm not able to see changes by switching between that revision and previous. Make sure you're not using outdated shaders, as those changed as a result of the Billboard changes. Also, what graphics API are you using?

Another matter is that I believe the directional billboard algorithm for calculating camera direction is wrong. It's using the billboard's model space position to calculate direction to camera, while camera position is in world space. @ucupumar Can you comment?

**Comment by cadaver** [comment]
If billboards are not node relative then this is a non-issue. I believe it can be fixed for both modes which I'll commit shortly.

**Comment by cadaver** [comment]
@yushli Can you test the latest master with its own shaders, whether you still see issues?

**Comment by ucupumar** [comment]
Sorry for late response. Thanks for the fix @cadaver, I missed that one. I tested on OpenGL and DX9 and it works well with no artifacts.

**Comment by yushli** [comment]
Will test that tomorrow. Thanks for the quick fix.

**Comment by yushli** [comment]
The issue is fixed by the commit. Now the particle effect looks the same. Thank you for the quick fix!

**Comment by yushli** [comment]
The issue is fixed by the commit. Now the particle effect looks the same. Thank you for the quick fix!
