### ISSUE TITLE
DXT1 Image Decompression Issue

### ISSUE THREAD

**Issue by OldSnake22** [urho3d/Urho3D#1479]
Hello, 

I currently have an issue when decompressing DDS DXT1 image. Here is my code: 

```
const size_t _Size = m_pImage->GetWidth() * m_pImage->GetHeight() * 4;
unsigned char* _pData = new unsigned char[_Size];       
m_pImage->GetCompressedLevel(0).Decompress(_pData);  
_pFinalImage->SetData(_pData);
_pFinalImage->SavePNG("test.png");
delete[] _pData;
```

Here is how the produced image look like (using the mushroom texture): 
![test](https://cloud.githubusercontent.com/assets/8931643/16926397/c0bb2ce0-4d28-11e6-95f2-b25bbca225cb.png)

DXT5 compression is working fine.

Am i doing something wrong here ?

**Comment by cadaver** [comment]
I don't see how you're setting up the final image. Decompress always outputs RGBA so it needs 4 components. I tested with following piece of code and it worked OK for the mushroom, both in 32bit and 64bit builds:

    Image* img = GetSubsystem<ResourceCache>()->GetResource<Image>("Textures/Mushroom.dds");
    Image decompImg(context_);
    decompImg.SetSize(img->GetWidth(), img->GetHeight(), 4);
    img->GetCompressedLevel(0).Decompress(decompImg.GetData());
    decompImg.SavePNG("Test.png");

**Comment by OldSnake22** [comment]
So yes that's was a dumb mistake on my side. This is solved thank you Cadaver.
