### ISSUE TITLE
New Lua Script with kaguya.

### ISSUE THREAD

**Issue by aster2013** [urho3d/Urho3D#1481]
Write a new Lua script  binding with [kaguya](https://github.com/satoren/kaguya/). WIP.

**Comment by aster2013** [comment]
Now, All of the Lua API finished.

**Comment by silverkorn** [comment]
Will this break/deprecate those scripts?
[ToCppHook.lua](https://github.com/urho3d/Urho3D/blob/master/Source/Urho3D/LuaScript/pkgs/ToCppHook.lua)
[ToDoxHook.lua](https://github.com/urho3d/Urho3D/blob/master/Source/Urho3D/LuaScript/pkgs/ToDoxHook.lua)
[ToZerobraneStudioHook.lua](https://github.com/urho3d/Urho3D/blob/master/Source/Urho3D/LuaScript/pkgs/ToZerobraneStudioHook.lua)

I was about to add some features to `ToZerobraneStudioHook.lua` and generate a new one. :confused:

**Comment by weitjong** [comment]
I think they will be later but definitely not in this upcoming 1.6 release.

**Comment by silverkorn** [comment]
Ok.
@aster2013: Can [kaguya](https://github.com/satoren/kaguya/) parse the Lua elements so we can re-adapt those scripts to generate stubs and documentation for different IDE/tools?

**Comment by aster2013** [comment]
@silverkorn kaguya can not do such thing now.

**Comment by aster2013** [comment]
@silverkorn , I will add comment in the LuaAPI.cpp file, like following, it is OK for you?
```
void RegisterAnimatedSprite2D(kaguya::State& lua)
{
    using namespace kaguya;

    // Enum: LoopMode2D
    lua["LM_DEFAULT"] = LM_DEFAULT;
    lua["LM_FORCE_LOOPED"] = LM_FORCE_LOOPED;
    lua["LM_FORCE_CLAMPED"] = LM_FORCE_CLAMPED;

    // Class: AnimatedSprite2D : StaticSprite2D
    lua["AnimatedSprite2D"].setClass(UserdataMetatable<AnimatedSprite2D, StaticSprite2D>()
    	// Constructor: AnimatedSprite2D()
        .addStaticFunction("new", &CreateObject<AnimatedSprite2D>)

        // Method: void SetAnimationSet(AnimationSet2D* animationSet)
        .addFunction("SetAnimationSet", &AnimatedSprite2D::SetAnimationSet)
        // Method: void SetEntity(const String& name)
        .addFunction("SetEntity", &AnimatedSprite2D::SetEntity)

        // Method: void SetAnimation(const String& name, LoopMode2D loopMode = LM_DEFAULT)
        .addFunction("SetAnimation", AnimatedSprite2DSetAnimation())

        // Method: void SetLoopMode(LoopMode2D loopMode)
        .addFunction("SetLoopMode", &AnimatedSprite2D::SetLoopMode)
        // Method: void SetSpeed(float speed)
        .addFunction("SetSpeed", &AnimatedSprite2D::SetSpeed)

        // Method: AnimationSet2D* GetAnimationSet() const
        .addFunction("GetAnimationSet", &AnimatedSprite2D::GetAnimationSet)
        // Method: const String& GetEntity() const
        .addFunction("GetEntity", &AnimatedSprite2D::GetEntity)
        // Method: const String& GetAnimation() const
        .addFunction("GetAnimation", &AnimatedSprite2D::GetAnimation)
        // Method: LoopMode2D GetLoopMode() const
        .addFunction("GetLoopMode", &AnimatedSprite2D::GetLoopMode)
        // Method: float GetSpeed() const
        .addFunction("GetSpeed", &AnimatedSprite2D::GetSpeed)

        // Property: AnimationSet2D* animationSet
        .addProperty("animationSet", &AnimatedSprite2D::GetAnimationSet, &AnimatedSprite2D::SetAnimationSet)
        // Property: const String& entity
        .addProperty("entity", &AnimatedSprite2D::GetEntity, &AnimatedSprite2D::SetEntity)
        // Property: const String& animation
        .addProperty("animation", &AnimatedSprite2D::GetAnimation)
        // Property: LoopMode2D loopMode
        .addProperty("loopMode", &AnimatedSprite2D::GetLoopMode, &AnimatedSprite2D::SetLoopMode)
        // Property: float speed
        .addProperty("speed", &AnimatedSprite2D::GetSpeed, &AnimatedSprite2D::SetSpeed)
    );
}
```
You can write a Lua script to scan the file and then generate API for ZerobraneStudio.

**Comment by silverkorn** [comment]
This might be a good solution. :smile: 
(It's not just for ZerobraneStudio but any potential IDE :wink:)
Thanks!

**Comment by aster2013** [comment]
@silverkorn I have add two files:
**LuaScriptAPIParser.lua** - uses to parse Lua API
**LuaScriptAPIWriter.lua**  - using the result from LuaScriptAPIParser.lua then generate **LuaScriptAPI.dox** file, you can refer to LuaScriptAPIWriter.lua for usage and write your writer for IDEs.

**Comment by silverkorn** [comment]
Thanks!
Little notice, the `ToDoxHook.lua` was having an extra layer for also linking the source code descriptions from the comments to be used with the parsed Lua API.
I might eventually transpose this code as an optional feature in `LuaScriptAPIParser.lua` if you allow me. :wink:

**Comment by aster2013** [comment]
Of course, you can do it!

**Comment by amerkoleci** [comment]
Any plans on merging kaguya support into main branch?
