### ISSUE TITLE
Viewport getRect() returns 0, 0, 0, 0

### ISSUE THREAD

**Issue by graph** [urho3d/Urho3D#1482]
And the GetView() View class has no means to get the `viewRect_` member so we can't get the viewport at all. Just takes the sample Hello World application to trigger this in `handleupdate`.

**Comment by cadaver** [comment]
0 0 0 0 means to use the full rendertarget size (possibly changed dynamically.) Viewport doesn't know the rendertarget it's attached to so it cannot give the correct size in this case, but it shouldn't hurt to make the viewRect in View public.

Note that Hello World application doesn't render a 3D scene at all, so it will not define a valid viewport.

**Comment by graph** [comment]
Sorry I meant just add a viewport and necessary dependencies. to helloworld to trigger this. 

I see, the docs only say "Return rectangle".  I'm pretty sure somewhere else where what you say is described in the documentation.

I propose this:

```
    const IntRect& GetRect() const {
       if(rect == IntRect()){
             Graphics *graphics = GetSubsystem<Graphics>();
             return IntRect(0, 0, graphics->GetWidth(), graphics->GetHeight();
        }
        return rect_; 
    }
```

So it always returns a valid rect. But there might be code already depending on the current functionality in the wild, so a documentation update will probably suffice.

Thank you :)

**Comment by cadaver** [comment]
You can't assume a Viewport is a backbuffer viewport (in which case it's valid to ask the Graphics resolution), it could also be a texture viewport, with different dimensions.
