### ISSUE TITLE
Remove assert from ToVectorVariant

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1485]
ToVectorVariant cause assert when source string has unexpected number of elements.
I suppose that this function should have some other mechanism of error handling.

Firstly, other ToSomething functions work with any input data and just return when data is wrong.
**Secondly,** argument of ToVectorVariant may come directly from XML file, e.g. material.

I think that material with empty parameter value shouldn't cause assert and exit of Urho3D even in debug mode...

**Comment by cadaver** [comment]
Yes, I agree that illegal input to an utility function shouldn't cause assert (quite same as Urho's policy of no exceptions). Returning an empty variant in error case is typical.
