### ISSUE TITLE
Draw artifacts on MALI400 GPU

### ISSUE THREAD

**Issue by mayatforest** [urho3d/Urho3D#1489]
Hi.
We have some troubles on devices with MALI400 graphics (Xamarin+urho).
This GPU have default dithering enabled in back buffers and resulted image of rendering is drawed with artifacts (tested on static scene from urho examples).

Please see details here http://urho3d.prophpbb.com/topic2212.html and https://github.com/xamarin/urho/issues/137

Please add options to call glDisable(GL_DITHER) or may be help with other solution to remove artifacts.

**Comment by cadaver** [comment]
I see no problem to adding e.g. a SetDither() function to Graphics class, with the note that it has effect on OpenGL only.

**Comment by mayatforest** [comment]
Thanks, when xamarin updates urho package ill check that this helps.
