### ISSUE TITLE
Add method to Texture2D for change glPixelStorei(GL_UNPACK_ROW_LENGTH,stride);

### ISSUE THREAD

**Issue by MonkeyFirst** [urho3d/Urho3D#1497]
I'm need this for reading YUV planes in shader properly, since the headers became agnostic i'm do not figure out there exactly i must add "stride" stuff (

like so
~~~
	void update_texture(GLuint tex, unsigned char* buf,int w,int h, int stride) {
		glPixelStorei(GL_UNPACK_ROW_LENGTH,stride);
		glBindTexture(GL_TEXTURE_2D,tex);
		glTexSubImage2D(GL_TEXTURE_2D,0,0,0,w,h,GL_LUMINANCE,GL_UNSIGNED_BYTE,buf);
		// set GL_UNPACK_ROW_LENGTH back to 0 to avoid bugs 
		glPixelStorei(GL_UNPACK_ROW_LENGTH,0);
	}
~~~

**Comment by cadaver** [comment]
IMO the correct way to do this would be to add a stride parameter to SetData for all API's. However this is something that Urho itself will never need, so it will be for the most time an untested usecase and complicate the code.

Alternatively if you're only making an OpenGL application, you could call Graphics::SetTextureForUpdate(), obtain the OpenGL handle for the texture with GetGPUObjectName() and perform the texture update with manual OpenGL calls.

**Comment by MonkeyFirst** [comment]
>SetData for all API's.

Oh thanks i will try to do this, 
Previously i trying to add SetStride(int) to Texture2D that gives a lot errors (

>Alternatively if you're only making an OpenGL application

If DX supports some kind of similar stuff with "stride", it also able to use GPU-decoding of YUV planes by using DX-shader i guess, because shader very simple and portable. 

But, yes for testing i'm using only GL-renderer. 

For now with GPU-decoding i have animated colored plane, filled with one color, I'm just thinking that if i setup stride properly for texture i got better result, not ust one color on whole texture :)

**Comment by MonkeyFirst** [comment]
Is it this in-place using of glPixelStorei() are alos properly for using to setup texture?

~~~
void TVComponent::UpdatePlaneTextures() 
{
	Graphics* graphics = GetSubsystem<Graphics>();

	// fill textures with new data
	for (int i = 0; i < YUV_PLANE_MAX_SIZE; ++i)
	{
		int y_offset = m_TheoraInfo.offset_x + m_YUVFrame.y_stride * m_TheoraInfo.offset_y;
		int uv_offset = m_TheoraInfo.offset_x / (m_YUVFrame.y_width / m_YUVFrame.uv_width) + 
			m_YUVFrame.uv_stride * m_TheoraInfo.offset_y / (m_YUVFrame.y_height / m_YUVFrame.uv_height);

		switch (i)
		{
		case YUVP420PlaneType::YUV_PLANE_Y:
			//In this place need set stride for outputTexture[i] = m_YUVFrame.y_stride;
			//outputImage[i]->SetData(m_YUVFrame.y + y_offset);
			glPixelStorei(GL_UNPACK_ROW_LENGTH, m_YUVFrame.y_stride);
			outputTexture[i]->SetData(0, 0, 0, m_YUVFrame.y_width, m_YUVFrame.y_height, m_YUVFrame.y + y_offset);
			glPixelStorei(GL_UNPACK_ROW_LENGTH, 0);
			break;
		case YUVP420PlaneType::YUV_PLANE_U:
			////In this place need set stride for outputTexture[i] = m_YUVFrame.uv_stride;
			//outputImage[i]->SetData(m_YUVFrame.u + uv_offset);
			glPixelStorei(GL_UNPACK_ROW_LENGTH, m_YUVFrame.uv_stride);
			outputTexture[i]->SetData(0, 0, 0, m_YUVFrame.uv_width, m_YUVFrame.uv_height, m_YUVFrame.u + uv_offset);
			glPixelStorei(GL_UNPACK_ROW_LENGTH, 0);
			break;
		case YUVP420PlaneType::YUV_PLANE_V:
			////In this place need set stride for outputTexture[i] = m_YUVFrame.uv_stride;
			//outputImage[i]->SetData(m_YUVFrame.v + uv_offset);
			glPixelStorei(GL_UNPACK_ROW_LENGTH, m_YUVFrame.uv_stride);
			outputTexture[i]->SetData(0, 0, 0, m_YUVFrame.uv_width, m_YUVFrame.uv_height, m_YUVFrame.v + uv_offset);
			glPixelStorei(GL_UNPACK_ROW_LENGTH, 0);
			break;
		}

		//outputTexture[i]->SetData(0, 0, 0, m_YUVFrame.y_width, m_YUVFrame.y_height, m_YUVFrame.y + y_offset);
	}
}
~~~

**Comment by cadaver** [comment]
Yes, that's also valid, if SetData() itself is doing what you want.

**Comment by MonkeyFirst** [comment]
After several attempts to use glPixelStorei(), I decide drop it, because every time I got an NV error in driver's dll, and i don't know why.

So, I decide extract from YUV frame the "planes" data and write those planes into three separetad planar buffers, and then directly put they into texture. 

So i close this issue.

**Comment by cadaver** [comment]
You were likely causing out-of-bounds memory access within the display driver with an illegal stride value.

**Comment by MonkeyFirst** [comment]
But why when I use this stride for exctracting data to planar buffers it's working fine and i do not have out-of-bound memory access.

**Comment by cadaver** [comment]
The GL documents explain the pixel store parameters in a rather unclear way, if I'm honest I wasn't sure how the parameters would actually cause the data to be read. I'm sure the stride value you use is correct for your code, but the question is how to explain it to OpenGL to get the same result :)
