### ISSUE TITLE
Area Lighting

### ISSUE THREAD

**Issue by dragonCASTjosh** [urho3d/Urho3D#1501]
Since my last commit on PBR i have put some work into area lighting. Although its far from PR ready, i thought id share some of the work with area lighting. I also plan to use this thread as a way to seek help on any issues i have.

Sphere Lights:
![screenshot_mon_aug__1_10_15_03_2016](https://cloud.githubusercontent.com/assets/3044415/17289339/33108d50-57d1-11e6-9bbe-ff5820cb3533.png)

**Comment by cadaver** [comment]
Cool! However there is already an area lights issue, so maybe close either one?
https://github.com/urho3d/Urho3D/issues/1334

**Comment by dragonCASTjosh** [comment]
ah yea i forgot that although im using a very diffrent approch

**Comment by luchete80** [comment]
wow is really cool man, i'll look into that DF. Pretty good analysis and DFs summary i was reading today: 
http://www.trentreed.net/blog/physically-based-shading-and-image-based-lighting/

Keep going on that!

**Comment by dragonCASTjosh** [comment]
@luchete80 may of posted that on the wrong thread as this is area light focused :) although i do have some video reference for you from siggraph.

Basic PBR: https://www.youtube.com/watch?v=j-A0mwsJRmk
Advanced PBR: https://www.youtube.com/watch?v=zs0oYjwjNEo

**Comment by luchete80** [comment]
Oh i see, upps my bad, thanks you @dragonCASTjosh for your help :), i'll check that!!

**Comment by dragonCASTjosh** [comment]
Update on the state of Area lighting, i have written it from scratch using epics approach and its much nicer results with better performance

[http://imgur.com/a/69BFR](http://imgur.com/a/69BFR)

**Comment by 1vanK** [comment]
look nice!

**Comment by dragonCASTjosh** [comment]
thanks :)

**Comment by OldSnake22** [comment]
Very cool man, have you done tube shaped lights ? :)

**Comment by dragonCASTjosh** [comment]
im working on tubes right now

**Comment by OldSnake22** [comment]
Can we have your twitch link ? :)

**Comment by 1vanK** [comment]
https://www.twitch.tv/2011josh

**Comment by dragonCASTjosh** [comment]
Tube lighting is now implemented, although i will need to do a little work with the diffuse for the area lighting as an optional thing. The reason for it being optional is its is a large drain in performance compared to the secular and is not really needed on smooth materials 

![screenshot_mon_sep_19_13_43_20_2016](https://cloud.githubusercontent.com/assets/3044415/18632466/7742e792-7e6f-11e6-813f-3f9053265959.png)

![screenshot_mon_sep_19_13_47_52_2016](https://cloud.githubusercontent.com/assets/3044415/18632510/ae05eb26-7e6f-11e6-8626-b4c307f851da.png)

**Comment by dragonCASTjosh** [comment]
implemented in prior PR
