### ISSUE TITLE
How to create a transparent surfaceview in Android?

### ISSUE THREAD

**Issue by zxzx74147** [urho3d/Urho3D#1503]
Like Cocos2D:
http://discuss.cocos2d-x.org/t/how-to-make-game-background-main-activity-transparent-in-cocos2d-xrc0/12548
Thanks!

**Comment by cadaver** [comment]
The app manifest and Java code are in the Android directory in Urho repo. 

The SDL GL attributes setup happens in Source/Urho3D/Graphics/OpenGL/OGLGraphics.cpp, SetMode function. Currently there's minimal setup GLES (e.g. not setting minimum depth bits) to reduce compatibility problems.

You'll have to experiment unless someone has tried this directly.

**Comment by Mike3D** [comment]
For the desktop part, I gave it a try:

```C++
        SDL_GL_SetAttribute(SDL_GL_DEPTH_SIZE, 16);
        SDL_GL_SetAttribute(SDL_GL_RED_SIZE, 8);
        SDL_GL_SetAttribute(SDL_GL_GREEN_SIZE, 8);
        SDL_GL_SetAttribute(SDL_GL_BLUE_SIZE, 8);
        SDL_GL_SetAttribute(SDL_GL_BUFFER_SIZE, 32);

        SDL_GL_SetAttribute(SDL_GL_ALPHA_SIZE, 8);

[...]

    glClearColor(0.5f, 0.5f, 0.5f, 0.0f);

Black window background is accurately cleared to grey, but no transparency is applied.
Any hint on how to setup transparency ?

**Comment by ganusajjan** [comment]
How to make window transparency?? Did you get anything on this??
