### ISSUE TITLE
Move the Forum to Discourse Free Hosting

### ISSUE THREAD

**Issue by rasteron** [urho3d/Urho3D#1505]
Hey guys,

Probably just throwing this out so you guys could consider it. It seems the current PhpBB forum is good but it's getting frequently less accessible these days so it might be a good idea to switch to a better platform.

Discourse is a great forum and it offers free/sponsorship forum to community friendly open source projects. There's a good chance that this project will be given free hosting/sponsorship even though it falls short of their 2k starred requirement. Urho3D already passed their 30 contributor requirement btw.

**Blog Announcement**
http://blog.discourse.org/2016/03/free-discourse-forum-hosting-for-community-friendly-github-projects/
**Application Form Link:**
https://docs.google.com/forms/d/1VqFmJmjqmOmZHkd3zVkQk906utqfVN8inq8pYZmS8dY/viewform

Just a suggestion.

**Comment by hdunderscore** [comment]
Thanks for bringing this up. I have thought in the past that discourse would be more suitable for Urho forums (although the 'view active topics' link on phpbb is a workable alternative). The biggest advantage would be being able to move away from the ad-infested free host we currently have.

**Comment by cadaver** [comment]
It doesn't hurt to try whether they see the 2k as an absolute minimum.

**Comment by 1vanK** [comment]
They require big popularity of the project and at the same time have limit of monthly page views :)

**Comment by badkangaroo** [comment]
just a suggestion but might be nice to see a slack channel as well.

**Comment by OvermindDL1** [comment]
Could always just host it ourselves?  Discourse is easy to run.

**Comment by hdunderscore** [comment]
I got good news on this, they have approved the application for the Urho3D free discourse hosting. 

Will need to find out what our export options with prophpbb are if we want to preserve the existing discussions -- anyone know ?

**Comment by 1vanK** [comment]
https://meta.discourse.org/t/importing-from-phpbb3/30810

**Comment by cadaver** [comment]
Last time migration was discussed the issue came up that with a free prophpbb forum you don't get access to the database dump.

**Comment by OvermindDL1** [comment]
Could leave it since it has a lot of old not-always-relevant-now data, switch it to read-only mode with a banner saying to go to a new site.

**Comment by 1vanK** [comment]
As far as I know _prophpbb.com_ hosting delete forum after some time without new posts

**Comment by OvermindDL1** [comment]
> As far as I know prophpbb.com hosting delete forum after some time without new posts

Fantastic service that...  >.>

Is there really no way to get a DB dump then?  Or write a bot to keep posting on it once a day or so?

/me is really not a fan of proprietary things for just this reason...

**Comment by 1vanK** [comment]
Is there any guarantees for new hosting?

**Comment by OvermindDL1** [comment]
> Is there any guarantees for new hosting?

Well at least with discourse you can take complete backups from the admin view, and easy to automate since it supports api keys.

**Comment by rasteron** [comment]
really good news @hdunderscore !

@1vanK 
and this is the actual Discourse organization that we are talking about and will host the project, but it still doesn't hurt to ask if there are guarantees. ;-)

@cadaver 
I think they do backups, just send email to their support

> Can I Get A Back-Up Of My Forum's Database?
> Most certainly. Premium members can download backups from their admin control panel at any time, and **free forums can request a back-up by emailing support [at] prophpbb.com with the request**.

https://www.prophpbb.com/faqs.hml

> Basically you request a copy of you forum database via email to Prophpbb which you then can upload/install into your own webspace or with another provider.
> 
> It copies all your posts etc but doesn't include things like installed styles etc
> 

https://support.prophpbb.com/topic2930.html?sid=278573f73c8327187e198977b2ae4490#p19052

**Comment by eugeneko** [comment]
Any updates? WIP or on hold?

**Comment by 1vanK** [comment]
We can take it for russian Urho-fan-site :)

**Comment by hdunderscore** [comment]
I've had limited free time to work on migrating the old forum data to the new host. I did attempt it and although I expected the matter to be simple as it involves the use of docker etc, I ran into a hiccup that I wasn't able to find the time to resolve yet.

**Comment by hdunderscore** [comment]
Just an update on this, I have found some time and overcome the small hiccup in migrating data. The data is a few months old now though, but you can view the forum here: http://discourse.urho3d.io/

You should be able to login after doing a password reset. Feel free to test it out, let me know if you run into any issues.

Right now we are still officially on the old forums, but there shouldn't be any significant problems in starting the move to the new forum.

**Comment by 1vanK** [comment]
Login successfully

**Comment by rasteron** [comment]
Awesome update @hdunderscore ! Logged in successfully as well.. great way to start this coming 2017!

**Comment by BlueMagnificent** [comment]
Great job @hdunderscore  , I successfully logged in

**Comment by hdunderscore** [comment]
The migration is complete and the old forum will soon be set to read-only.

Just FYI you'll need to password reset, or alternatively you can log in with your github account if your github email reflects your old forum account.
