### ISSUE TITLE
Undefined Behavior in attributes

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1509]
URHO3D_ATTRIBUTE and URHO3D_ENUM_ATTRIBUTE use offsetof, but offsetof is allowed only for PODs (or standard layout types in C++11)
Actually, any class derived from Object is neither POD nor stdlayout. So, all serialization in Urho3D is based on UB.
http://en.cppreference.com/w/cpp/types/offsetof

Let's think about getting rid of it.

**Comment by cadaver** [comment]
Yes, it's an issue and most of the cases could be replaced with Set / Get accessors.

In practice however there has not been actual wrong behavior on the platforms we use, though it's undefined by the standard. I believe once you have virtual inheritance, then bad things would start to happen with offsetof. There are no virtual inheritance using classes in Urho itself.

**Comment by eugeneko** [comment]
Yep, it should work in most cases. But you mustn't rely on such behaivour.
I don't say 'You must fix it right now it is superdengereous!!11'
I just say 'Let's think about getting rid of it'.

Here is a small example.
http://rextester.com/IHBA32841
Try to explain why this for loop **with constant number of iterations** is getting hang.

One day somebody of open-source developers could say 'Let's rape all UB users to make implementation of feature X easier/to make compilation 0.2% faster/etc'.
And then UB users will be raped and this code will die.

**Comment by eugeneko** [comment]
I suggest to provide for C++11 users UB-free implementation of attributes.
It will give a choise for Urho3D users between C++98-compatible UB and C++11 well-formed code.

1. Create template Attribute Accessor Impl that consumes getter and setter:
```void setter(TClass& class, const TField/Variant& value);
TField/Variant getter(TClass& class)```

2. Use lambdas in macro:
[](TClass& class, const TField/Variant& value) { field_ = value; }
[](TClass& class) -> TField/Variant { return value; }
It is possible because lambdas are convertible to pointers.

Maybe it could be even hacked-around in C++98 with static member functions of local classes...

**Comment by eugeneko** [comment]
**Update:**
After my recent PR it is possible to write UB-free attributes in C++11 using the following macros:

```
#define URHO3D_MEMBER_ATTRIBUTE(name, typeName, variable, defaultValue, mode) URHO3D_ACCESSOR_ATTRIBUTE_FREE(name, [](const ClassName* classPtr) -> typename AttributeTrait<typeName >::ReturnType { return classPtr->variable; }, [](ClassName* classPtr, typename AttributeTrait<typeName >::ParameterType value) { classPtr->variable = value; }, typeName, defaultValue, mode)
#define URHO3D_MEMBER_ENUM_ATTRIBUTE(name, typeName, variable, enumNames, defaultValue, mode) URHO3D_ENUM_ACCESSOR_ATTRIBUTE_FREE(name, [](const ClassName* classPtr) -> unsigned { return static_cast<unsigned>(classPtr->variable); }, [](ClassName* classPtr, unsigned value) { classPtr->variable = static_cast<typeName>(value); }, unsigned, enumNames, defaultValue, mode)
#define URHO3D_MEMBER_ATTRIBUTE_ACCESSOR(name, typeName, variable, getFunction, setFunction, defaultValue, mode) URHO3D_ACCESSOR_ATTRIBUTE_FREE(name, [](const ClassName* classPtr) -> typename AttributeTrait<typeName >::ReturnType { return classPtr->variable.getFunction(); }, [](ClassName* classPtr, typename AttributeTrait<typeName >::ParameterType value) { classPtr->variable.setFunction(value); }, typeName, defaultValue, mode)
```
