### ISSUE TITLE
StaticModel::AddComponent bug

### ISSUE THREAD

**Issue by EgorBo** [urho3d/Urho3D#1510]
If I setup a StaticModel before attaching to a node, it will crash, for example:
```
auto mushroomObject = new StaticModel(context_);
mushroomObject->SetModel(cache->GetResource<Model>("Models/Mushroom.mdl"));
mushroomObject->SetMaterial(cache->GetResource<Material>("Materials/Mushroom.xml"));
mushroomNode->AddComponent(mushroomObject, 0, CreateMode::REPLICATED);
```
If I add it before I do SetModel\SetMaterial, it works fine:
```
auto mushroomObject = new StaticModel(context_);
mushroomNode->AddComponent(mushroomObject, 0, CreateMode::REPLICATED); 
mushroomObject->SetModel(cache->GetResource<Model>("Models/Mushroom.mdl"));
mushroomObject->SetMaterial(cache->GetResource<Material>("Materials/Mushroom.xml"));
```
or if I use CreateComponent or GetOrCreateComponent - also works fine!
```
auto mushroomObject = mushroomNode.CreateComponent<StaticModel>(context_);
mushroomObject->SetModel(cache->GetResource<Model>("Models/Mushroom.mdl"));
mushroomObject->SetMaterial(cache->GetResource<Material>("Materials/Mushroom.xml"));
```
PS: Great engine, guys! love it.

**Comment by cadaver** [comment]
CreateComponent() is in fact the proper way, you shouldn't be doing manual new and AddComponent(). However it's good that you mentioned this since it should be documented better that you shouldn't do that, components still should be crashproofed against illegal sequences, and it's also worth looking if AddComponent can be made protected/private.

**Comment by EgorBo** [comment]
@cadaver yeah I agree. but in C# people love to use property initializators like this:
`var model = new StaticModel { Model = myModel, Material = myMaterial };`
Thanks for adding a comment and that LOGERROR! Most other components work fine with AddComponent approach.
