### ISSUE TITLE
Missing MarkNetworkUpdate of Component in Node::AddChild

### ISSUE THREAD

**Issue by INait** [urho3d/Urho3D#1511]
I've tried to move Node with some components from one Scene to another, but it ended with crash in 
Serializable.cpp:742
` const AttributeInfo& attr = attributes->At(i);`
` if (networkState_->currentValues_[i] != attr.defaultValue_)`
        `attributeBits.Set(i);`

due to inconsistent number of attributes(which is many) and size of currentValues_(which is 0).
I figured, that manually invoking MarkNetworkUpdate on every component of Node fixes the problem.
Can I add this change to Node::AddChild? Something like this
`  for (unsigned i = 0; i < components_.Size(); ++i)`
   `     components_[i]->MarkNetworkUpdate();`

**Comment by cadaver** [comment]
Thanks, that was indeed the proper solution. Additionally I made AllocateNetworkState() to already set the proper size for currentValues & previousValues, so that the crash should be impossible in the future even if a network update somehow failed to be marked.
