### ISSUE TITLE
TileMapLayer2D::GetObject (index) function name conflict

### ISSUE THREAD

**Issue by KonstantinTomashevich** [urho3d/Urho3D#1512]
TileMapLayer2D::GetObject (index) can not be used on MinGW because it conflicts with GetObject macro in wingdi.h (line 3309) and causes linker error when I build my project (Urho3D builds successfully). It can be fixed by setting URHO3D_WIN32_CONSOLE=1.

 But I think it will be good if TileMapLayer2D::GetObject (index) will be renamed to, for example, TileMapLayer2D::GetLayerObject (index), because in my opinion using URHO3D_WIN32_CONSOLE for all windows projects with tile maps is not a good solution.

P.S. My system configuration:

- Windows 7 SP1
- MinGW 4.9.2 (i686-4.9.2-posix-dwarf-rt_v3-rev1)
- CMake 3.6.0
- Urho3D version is release 1.6.

**Comment by Stinkfist0** [comment]
simple
```c++
#ifdef GetObject 
#undef  GetObject 
#endif
```
should do the trick.

**Comment by KonstantinTomashevich** [comment]
Thanks, but with it I get other error:
`E:\CXXProjects\GDLMerchantXVICentury\Source\Game\GameState\GameStateInitializer.cpp:75:16: error: 'class Urho3D::TileMapLayer2D' has no member named 'GetObject'
         layer->GetObject (objectIndex);`
But with URHO3D_WIN32_CONSOLE=1 all works fine.

**Comment by KonstantinTomashevich** [comment]
Thanks for help! I add `#ifdef GetObject 
#undef  GetObject 
#endif`
before include of TileMapLayer2D and all works! Sorry for my foolish issue. :)

**Comment by cadaver** [comment]
Actually I think that's good to add to the engine header itself (and not a foolish question at all), similar to how SendMessage is undefined in Connection.h

**Comment by KonstantinTomashevich** [comment]
I think this is the best solution for this problem.
