### ISSUE TITLE
CMake configuration error: get_filename_component

### ISSUE THREAD

**Issue by hsnabn** [urho3d/Urho3D#1513]
Hello. I'm getting an error trying to build my project with Urho3D (not Urho3D itself), and this error pops up for me:
```
CMake Error at cmake/modules/FindUrho3D.cmake:201 (get_filename_component):
  get_filename_component unknown component C:/Projects/Game
  Development/Engines/Urho3D-1.6-Build/lib/libUrho3D_d.a
Call Stack (most recent call first):
  CMakeLists.txt:29 (find_package)
```
I'm using Urho3D based off of the 1.6 release tag (`e2bad7d`).

Changing line 201 from
`get_filename_component (EXT ${URHO3D_LIBRARIES} EXT)`
to
`get_filename_component (EXT ${URHO3D_LIBRARIES_DBG} EXT)`
fixes the error, magically.

I also noticed that `URHO3D_LIB_TYPE` is a `BOOL` value in my `CMakeCache.txt`? But it is set to `STATIC`.

If you need any more information please ask.

**Comment by weitjong** [comment]
The BOOL type is copy-paste error. Thankfully (or not), CMake still use the value of the cache as intended. Thanks for reporting this. As for the error in line 201, I guess that was caused by FindUrho3D.cmake module being called twice. Please read the porting notes for 1.6 carefully.

**Comment by hsnabn** [comment]
Ah, yes, removing `find_package (Urho3D REQUIRED)` in `CMakeLists.txt` fixed it. Thanks. I had no idea there was a set of porting notes before.

**Comment by weitjong** [comment]
No need. I will fix this typo in a short time.

**Comment by weitjong** [comment]
I also took the liberty of amending the release post to mention the existence of porting notes.
