### ISSUE TITLE
render UI to multiple viewports

### ISSUE THREAD

**Issue by yushli** [urho3d/Urho3D#1514]
according to http://urho3d.prophpbb.com/topic1000.html (
Oculus Rift support ), I can successfully render one scene to two viewports by the following code: 
renderer.viewports[0] = Viewport(scene, left_eye_camera,IntRect(0, 0, graphics.width /2, graphics.height)); 
renderer.viewports[1] = Viewport(scene, right_eye_camera,IntRect(graphics.width /2, 0,graphics.width, graphics.height)); 
But I cannot find any methods to render UI  to multiple viewports. 
How can I do so in Urho3D? 
Also, if rendering one scene to two viewports, the FPS drops around one third, even if I use SetCullCamera. Are there any tricks to improve the performance during this scenario? Thank you for your reply.

**Comment by cadaver** [comment]
You can use a renderpath command to render the UI into arbitrary viewports. This disables the default UI render to the whole-screen backbuffer viewport.

Performance decrease for running the scene render twice is unfortunately a fact of life. I believe there's potential for optimizing it by actually looping the viewports through in each render pass, which would allow for example to run shadow render only once, and drop the amount of view preparation that's needed even further. However I know doing this would complicate the render code, so I'm reluctant to do it and will not give any timeframe for it. If you want, you could experiment with it yourself.

**Comment by yushli** [comment]
Thanks for the reply. I can use "renderui" command to render the UI into two viewports now. But the UI ratio is wrong and looks distorted.  Please look at the attached image. The problem is, should the UI be the viewport size, or the graphics size(viewport size width * 2). I tried both, and both got undesired results. 


<img width="651" alt="ui" src="https://cloud.githubusercontent.com/assets/1681453/17656449/c62ef042-62ec-11e6-9e14-fb8dc55a7095.png">

<img width="651" alt="ui2" src="https://cloud.githubusercontent.com/assets/1681453/17657703/0727873e-62f8-11e6-90ea-f962d401e3bb.png">

**Comment by cadaver** [comment]
Yes, I figured the distortion would be a problem. Probably will need a function to be able to override the UI root size, and use a projection matrix such that distortion will not happen, but rather as much as possible of the UI root is rendered, while keeping pixel-perfect output.

**Comment by yushli** [comment]
Also after using renderui, the click of each UI element no longer works as expected because their positions are wrong. 
I wrote some code to auto resize the UI so that it can layout according to the viewport size. It is not distorted, and the positions are correct so the buttons are clickable. But it can only shows up in one viewport. If we can find a way to duplicate the UI system with the given offset then everything will work.
<img width="651" alt="ui3" src="https://cloud.githubusercontent.com/assets/1681453/17659370/a6f45600-6304-11e6-8635-2b62be57e292.png">

**Comment by yushli** [comment]
@cadaver how do you plan to fix this? As well as fixing the distortion, we may need to keep the UI system workable under this situation. Currently UI is separated from scene, do you think it is desirable to add it into scne so that each scene has it own UI?

**Comment by cadaver** [comment]
Add a function to disable the automatic resizing of UI, so you can set your own root UI size, render the UI always pixel-perfect (no distortion) and maybe change the UI::GetElementAt() function so that if the mouse coordinates are outside the UI root, a modulus operation will be applied so that the right side UI copy will also be interactable. This assumes the UI copies are rendered side by side. I don't plan to add possibility for several UI's at the moment, since the assumption of one UI goes quite deep.

**Comment by cadaver** [comment]
Please check the just added commit. I used following AngelScript code to test, with 2 viewports next to each other and "renderui" added to the renderpath.

    renderer.numViewports = 2;
    Viewport@ viewport = Viewport(scene_, cameraNode.GetComponent("Camera"), IntRect(0, 0, graphics.width/2, graphics.height));
    Viewport@ viewport2 = Viewport(scene_, cameraNode.GetComponent("Camera"), IntRect(graphics.width/2, 0, graphics.width, graphics.height));
    renderer.viewports[0] = viewport;
    renderer.viewports[1] = viewport2;
    ui.customSize = IntVector2(graphics.width/2, graphics.height);

**Comment by yushli** [comment]
Thanks for the quick fix.
