### ISSUE TITLE
Make different icons for unknown components and components without icon

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1515]
Now all components in Editor have '?' icon if they don't have another one.
It would be cool to have different icons for unknown components and components without icon.

**Comment by cadaver** [comment]
Yes, this makes sense. I believe it will work by reserving the question mark for UnknownComponent and using another default icon by default.

**Comment by cadaver** [comment]
Since UnknownComponent actually fakes its typename to the component it's containing, this isn't straightforward to do from the editor. Will leave this on backburner. Cleanly implemented contributions are welcome though.
