### ISSUE TITLE
Add option to build 32 bit version of Urho3D library.

### ISSUE THREAD

**Issue by hsnabn** [urho3d/Urho3D#1516]
Right now, the CMake build system doesn't expose a build option that controls whether the library built will be 32 bit or 64 bit. It seems 64 bit-ness is automatically decided by the build system.

This ability might be useful, since I might want to build a 32 bit version even if I am running a 64 bit OS.

**Comment by cadaver** [comment]
https://urho3d.github.io/documentation/HEAD/_building.html
Use CMake option URHO3D_64BIT=0, default is set based on system.

**Comment by weitjong** [comment]
The build system will detect and default to build in 64-bit when the chosen compiler toolchain supports 64-bit ABI. It will provide the URHO3D_64BIT build option if and only if the chosen compiler toolchain is also multilib-capable, like GCC/Clang where it could target 32-bit ABI by using ```-m32``` compiler flag. For those that don't, however, then this URHO3D_64BIT build option is not really "an option" at all.

**Comment by vitormassaro** [comment]
It has negative subscript error in 32bit version.
