### ISSUE TITLE
1.6 compatibility issue with old code 

### ISSUE THREAD

**Issue by simon-matt** [urho3d/Urho3D#1522]
Hello,

I wanted to try out Urho3D and took this [one-file-example](http://urho3d.wikia.com/wiki/First_Project) (v 1.5!).

Everything working but these 900 boxes are not shown and there are some warnings in the console:
```
[Wed Aug 17 16:31:40 2016] WARNING: Found vertex attribute iInstanceMatrix1 with no known semantic in shader program LitSolid(INSTANCED) LitSolid(DIFFMAP)
[Wed Aug 17 16:31:40 2016] WARNING: Found vertex attribute iInstanceMatrix2 with no known semantic in shader program LitSolid(INSTANCED) LitSolid(DIFFMAP)
[Wed Aug 17 16:31:40 2016] WARNING: Found vertex attribute iInstanceMatrix3 with no known semantic in shader program LitSolid(INSTANCED) LitSolid(DIFFMAP)
[Wed Aug 17 16:31:40 2016] WARNING: Found vertex attribute iInstanceMatrix1 with no known semantic in shader program LitSolid(INSTANCED NORMALMAP PERPIXEL POINTLIGHT) LitSolid(AMBIENT DIFFMAP NORMALMAP PACKEDNORMAL PERPIXEL POINTLIGHT SPECULAR)
[Wed Aug 17 16:31:40 2016] WARNING: Found vertex attribute iInstanceMatrix2 with no known semantic in shader program LitSolid(INSTANCED NORMALMAP PERPIXEL POINTLIGHT) LitSolid(AMBIENT DIFFMAP NORMALMAP PACKEDNORMAL PERPIXEL POINTLIGHT SPECULAR)
[Wed Aug 17 16:31:40 2016] WARNING: Found vertex attribute iInstanceMatrix3 with no known semantic in shader program LitSolid(INSTANCED NORMALMAP PERPIXEL POINTLIGHT) LitSolid(AMBIENT DIFFMAP NORMALMAP PACKEDNORMAL PERPIXEL POINTLIGHT SPECULAR)
[Wed Aug 17 16:31:40 2016] WARNING: Found vertex attribute iInstanceMatrix1 with no known semantic in shader program LitSolid(INSTANCED NORMALMAP PERPIXEL POINTLIGHT) LitSolid(DIFFMAP NORMALMAP PACKEDNORMAL PERPIXEL POINTLIGHT SPECULAR)
[Wed Aug 17 16:31:40 2016] WARNING: Found vertex attribute iInstanceMatrix2 with no known semantic in shader program LitSolid(INSTANCED NORMALMAP PERPIXEL POINTLIGHT) LitSolid(DIFFMAP NORMALMAP PACKEDNORMAL PERPIXEL POINTLIGHT SPECULAR)
[Wed Aug 17 16:31:40 2016] WARNING: Found vertex attribute iInstanceMatrix3 with no known semantic in shader program LitSolid(INSTANCED NORMALMAP PERPIXEL POINTLIGHT) LitSolid(DIFFMAP NORMALMAP PACKEDNORMAL PERPIXEL POINTLIGHT SPECULAR)
```

This example was built for Urho3D v1.5, my system is:

- Urho3D Shared 1.6
- Linux x64 (Kubuntu 16.04)
- GCC version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2) 
- CMake 3.5.1
- Eclipse Neon 4.6.0

The [porting notes](https://urho3d.github.io/documentation/1.6/_porting_notes.html) solved the KEY_ESCAPE issue...

Am I missing something?
Thanks for every help, Simon

**Comment by cadaver** [comment]
This is mentioned in the porting notes, but not very thoroughly. In short: make sure you use 1.6 shaders, or if you have custom shaders, adapt the vertex attribute declarations (from Transform.glsl)

**Comment by simon-matt** [comment]
It's not using any custom shaders, just some static objects and some lights...

**Comment by simon-matt** [comment]
Sometimes a single box appears but when I move it disappears again... 
![001 boxshown](https://cloud.githubusercontent.com/assets/9771909/17741734/9dc69710-649d-11e6-9911-500876130ced.png)

**Comment by cadaver** [comment]
Somewhere your system is picking up Urho data from a previous version. iInstanceMatrix is not used in 1.6.

**Comment by simon-matt** [comment]
@cadaver thank you :)

Refreshing the [default project directories](https://urho3d.github.io/documentation/1.6/_using_library.html) to the latest version fixed it! For whatever reason they were outdated.
