### ISSUE TITLE
Both Urho3D_d.lib and Urho3D.lib used in Released configuration (Visual Studio 2015)

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1523]
I have engine compiled with both configurations (Build\lib contains Urho3D.lib and Urho3D_d.lib).

Cmake generated this project for Relese configuration of my game:

![1](https://cloud.githubusercontent.com/assets/13021826/17763067/bd5e2e0e-651e-11e6-8d01-cefc71c93c0b.png)

**Comment by 1vanK** [comment]
Debug version used rho3D_d.lib twice

```
kernel32.lib;user32.lib;gdi32.lib;winspool.lib;shell32.lib;ole32.lib;oleaut32.lib;uuid.lib;comdlg32.lib;advapi32.lib;D:\MyGames\PuddleSimulator\Engine\Build\lib\Urho3D_d.lib;D:\MyGames\PuddleSimulator\Engine\Build\lib\Urho3D_d.lib;user32.lib;gdi32.lib;winmm.lib;imm32.lib;ole32.lib;oleaut32.lib;version.lib;uuid.lib;ws2_32.lib;winmm.lib;opengl32.lib;imm32.lib;ole32.lib;oleaut32.lib;version.lib;uuid.lib;ws2_32.lib;opengl32.lib
```

**Comment by weitjong** [comment]
Did you revise your project main CMakeLists.txt according to 1.6?

**Comment by 1vanK** [comment]
Ah, sorry
