### ISSUE TITLE
Use Resource Browser for picking resources

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1524]
~~It is surprising that Resource Browser does exactly what is said: it allows to browse resources and nothing more. It is useless for picking resources into components. Editor has no drag-n-drop for resources,~~ and Open dialog for resources is actually plain open dialog that ignores paths. However, you still can't pick resource from outside of resource paths (but can navigate!), it is also could be surprising.
It would be great to have ~~resource drag&drop and/or~~ resource browser instead of plain open dialog at some point.

**Comment by friesencr** [comment]
There are some drag and drop capabilities within the resource browser.  I believe materials can be drag and dropped into the viewport and will apply to a model.  I think it will create nodes for prefabs and models.  The resource browser will drag and drop to text fields and resolve them to paths.  Drag and dropping to path is actually very flexible and works for almost any behavior. There is some code for dragging things into the scene graph/hierarchy control too. You are right that the resource browser is limited to the 'virtual' resource system.  The resource browser also predates the ui drag and drop handling so its a little weird too.

**Comment by eugeneko** [comment]
Huh... I don't know how could I missed this feature. I tried to drag&drop resources right before writing this issue.
