### ISSUE TITLE
Cannot build Urho3D in 32 bit mode, even with URHO3D_64BIT set to false.

### ISSUE THREAD

**Issue by hsnabn** [urho3d/Urho3D#1525]
I'm probably missing something, but I can't for the life of me figure out how to get Urho3D built in 32 bit mode. I ran CMake with `-DURHO3D_64BIT=0` and even still the resulting library is 64 bit.

Out of frustration I just hacked up URHO3D_64BIT and set it to false in the `Urho3D-CMake-common` module.

Can anyone help me figure out why setting the build option isn't working, though? Also, shouldn't it be user-specifiable (if the user is running 64 bit)?

**Comment by simon-matt** [comment]
Do you have the 32-bit versions of the development libraries installed?
What system are you using and which compiler?

**Comment by hsnabn** [comment]
I'm on Windows 64-bit, using TDM-GCC compiler (which is based off of MinGW-w64, I think).

**Comment by weitjong** [comment]
A brief explanation: our build system does not always take URHO3D_64BIT as "build option", i.e. it may predefined it as a normal CMake variable. Set it to 0 or 1 based on the detected native ABI of the compiler toolchain in question. Only a select few compilers that support multilib will have that variable treated like a "build option", i.e. allowing user to flip either way in the CMake GUI or CLI.

Now, we have assumed so far that MinGW-w64 is not multilib-capable. Perhaps that assumption is wrong now. Which version of the MinGW-w64 do you have? Is your 32-bit binaries all tested to be OK? If so, we may have to enhance the build system to correct this wrong assumption. At the very least, I can see that my 64-bit MinGW-w64 in Fedora 24 appears to accept ```-m32``` compiler flag happily.

**Comment by hsnabn** [comment]
Hmm, I've built programs with `m32` with TDM-GCC before, as 32 bit. I have version 5.1.0.

TDM-GCC is apparently multilib-capable (as seen on their (quirks page)[http://tdm-gcc.tdragon.net/quirks], scroll down a bit to the section "TDM64: 32-bit host, 64-bit or 32-bit targets").

Should I be passing `-m32` as a compiler flag, in order to get it to build as 32 bit?

**Comment by weitjong** [comment]
No, it should be still being configured via build option. Basically just need to remove the wrong assumption when deciding whether the URHO3D_64BIT is a build option or not. Here is the patch.
```
[weitjong@igloo Urho3D]$ git diff
diff --git a/CMake/Modules/Urho3D-CMake-common.cmake b/CMake/Modules/Urho3D-CMake-common.cmake
index 2e758ed..5487939 100644
--- a/CMake/Modules/Urho3D-CMake-common.cmake
+++ b/CMake/Modules/Urho3D-CMake-common.cmake
@@ -98,7 +98,7 @@ set (CMAKE_EXE_LINKER_FLAGS "${INDIRECT_DEPS_EXE_LINKER_FLAGS} ${CMAKE_EXE_LINKE
 include (CMakeDependentOption)
 option (URHO3D_C++11 "Enable C++11 standard")
 cmake_dependent_option (IOS "Setup build for iOS platform" FALSE "XCODE" FALSE)
-cmake_dependent_option (URHO3D_64BIT "Enable 64-bit build, the default is set based on the native ABI of the chosen compiler toolchain" ${NATIVE_64BIT} "NOT MSVC AND NOT MINGW AND NOT ANDROID AND NOT (ARM AND NOT IOS) AND NOT WEB AND NOT POWERPC" ${NATIVE_64BIT})     # Intentionally only enable the option for iOS but not for tvOS as the latter is 64-bit only
+cmake_dependent_option (URHO3D_64BIT "Enable 64-bit build, the default is set based on the native ABI of the chosen compiler toolchain" ${NATIVE_64BIT} "NOT MSVC AND NOT ANDROID AND NOT (ARM AND NOT IOS) AND NOT WEB AND NOT POWERPC" ${NATIVE_64BIT})     # Intentionally only enable the option for iOS but not for tvOS as the latter is 64-bit only^M
 option (URHO3D_ANGELSCRIPT "Enable AngelScript scripting support" TRUE)
 option (URHO3D_LUA "Enable additional Lua scripting support" TRUE)
 option (URHO3D_NAVIGATION "Enable navigation support" TRUE)
```
Unfortunately since I upgraded to F24, I have a number other unrelated build issues for a few of my build trees (including MinGW one), so I cannot tested the above patch properly. With the above change, it at least allows you to flip the URHO3D_64BIT to 0 using CMake GUI or CLI. In my short test, it seems to add ```-m32``` as I expected, however, I got a new compiler error when building SDL library in the SDL_error.c related to va_arg. YMMV. Since upgrading to F24, I have seen the va_arg error in my Android build tree as well.

**Comment by cadaver** [comment]
That patch tested OK for me. I tested MinGW-w64 (32bit only), and a 64bit-capable TDM-GCC, which produced a 64bit build by default, but also produced 32bit successfully when -DURHO3D_64BIT=0 was specified.

**Comment by weitjong** [comment]
Thanks for testing it, Lasse. In that case I will commit the patch to master branch then.

**Comment by hsnabn** [comment]
I successfully built Urho3D in 32 bit with the patch you provided.

But now, I have problems getting CMake to build my own project. I'm **sure** that I'm missing something, but I don't know what! Here's the CMake error that's thrown over to me:

```
CMake Error at cmake/modules/FindUrho3D.cmake:352 (message):
  Could NOT find compatible Urho3D library in Urho3D SDK installation or
  build tree.  Use URHO3D_HOME environment variable or build option to
  specify the location of the non-default SDK installation or build tree.
Call Stack (most recent call first):
  cmake/modules/Urho3D-CMake-common.cmake:193 (find_package)
  CMakeLists.txt:27 (include)
```

But the thing is, I've set `URHO3D_HOME` to the correct location. The library files are right there in a `lib` directly inside the `URHO3D_HOME` directory, the `include` directory is there as well.
However, `URHO3D_LIB_TYPE` is not set for me, and neither `URHO3D_LIBRARIES` nor `URHO3D_LIBRARIES_DBG` is anywhere to be found.

Any ideas?

**Comment by weitjong** [comment]
You have to provide the whole log. Anything can happen in between and without the log, it is difficult to tell what went wrong. The log should contain the complete trace of try_compile command. It should give an indication why the library that it found cannot be linked successfully.

**Comment by hsnabn** [comment]
Sorry for not providing it earlier, here's the log I get (using CMake GUI):

```
The C compiler identification is GNU 5.1.0
The CXX compiler identification is GNU 5.1.0
Check for working C compiler: C:/Program Files (x86)/Compilers/TDM-GCC-64/bin/gcc.exe
Check for working C compiler: C:/Program Files (x86)/Compilers/TDM-GCC-64/bin/gcc.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: C:/Program Files (x86)/Compilers/TDM-GCC-64/bin/g++.exe
Check for working CXX compiler: C:/Program Files (x86)/Compilers/TDM-GCC-64/bin/g++.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
CMake Error at cmake/modules/FindUrho3D.cmake:352 (message):
  Could NOT find compatible Urho3D library in Urho3D SDK installation or
  build tree.  Use URHO3D_HOME environment variable or build option to
  specify the location of the non-default SDK installation or build tree.
Call Stack (most recent call first):
  cmake/modules/Urho3D-CMake-common.cmake:193 (find_package)
  CMakeLists.txt:27 (include)


Configuring incomplete, errors occurred!
See also "C:/Projects/Game Development/Thorium/build/CMakeFiles/CMakeOutput.log".
```
And here's a Pastebin link to the full `CMakeOutput.log`: http://pastebin.com/G4m0ehdZ

**Comment by weitjong** [comment]
Unfortunately the information I spoke off is not in your log! Not sure why the it didn't (which is yet totally another issue :smile: ). But without it then I am afraid you are on your own. You probably have to use ```message()``` command to debug-print yourself what went wrong in the FindUrho3D.cmake module. Good luck.

**Comment by hsnabn** [comment]
Hehe. Down the rabbit hole I go, then...
