### ISSUE TITLE
Material->Clone() crashes application

### ISSUE THREAD

**Issue by simon-matt** [urho3d/Urho3D#1528]
Hello,

my application is always crashing when I clone a material. I took the "First Project" code and changed a few lines and got the same issue:
```
Material* defaultBoxMaterial = cache->GetResource<Material>("Materials/Stone.xml");
Material* clonedMaterial = defaultBoxMaterial->Clone();
boxObject->SetMaterial(clonedMaterial);
```

What is wrong about this code? Maybe someone can try it out if it's only crashing on my machine? Code is [here](http://hastebin.com/usoxequfim.cpp) (Line 145-147).

Urho3D.log is [here](http://hastebin.com/zuromanoyu).

Running from console results in this:
![screenshot_20160820_182409](https://cloud.githubusercontent.com/assets/9771909/17832447/6f07c03a-6703-11e6-9898-3cb5f7338490.png)

Thanks for any help, Simon :)

**Comment by 1vanK** [comment]
I see empty pages on the links :(

**Comment by simon-matt** [comment]
@1vanK Thank you very much for your help. **It works now!**  :+1:

**Comment by Stinkfist0** [comment]
`auto clonedMaterial = ...` would have worked here too - a great example that `auto` is not simply for convenience but helps also with code correctness.
