### ISSUE TITLE
Oculus Rift Integration

### ISSUE THREAD

**Issue by tersers** [urho3d/Urho3D#153]
Hello! 

I have experience developing with the OculusRift in C++, and I would be interested in integrating the Oculus with Urho3D so it can easily be used as a component.

This may take some time because I am in a game development course at university, and the workload does not favour any spare time. That being said, the game I am making this semester (I chose Urho for the engine) will be using the Oculus, so I'll write a C++ integration in my local project and then port it to the engine once it's done. I've done this before in Ogre, so I know the necessary operations with the engine's components, such as shaders and viewports.

The latest I can see this being completed would be April.

**Comment by Vytek** [comment]
Any news about Oculus VR integration?

**Comment by boberfly** [comment]
Hi all,

I did notice on the forums that someone has managed to port the DK2 to Urho3D. While this is a great addition, I'd like to make a patch to integrate into Urho3D proper.

Currently I am using both Oculus' latest API as well as Valve's new OpenVR API under the defines 'URHO3D_OCULUS' and 'URHO3D_OPENVR' with some basic CMake searching for these SDKs. I'm up to the stage where it initializes but now I'm debating whether or not to make Urho3D responsible of all of the rendering, or use their built-ins which I'm leaning towards more as they do a lot of clever things like warping the texture to hide latency, but as extra RenderPath commands that's not a quad command (still pending on how I'm approaching it exactly).

If the UI can output to a texture, Valve supplies an 'overlay' function in its Compositor class which just takes in a texture input, and you can tweak it to shape however you want.

As for left/right eye renders, I'm wondering if these should be separate cameras, or use one camera which has a big enough projection matrix to do culling for both eyes, then just make the two viewports render with different eye matrices. There would just be one frustum cull/shadow render pass/software occlusion cull, and it's fairly conservative with bounding-boxes so I'm hoping it doesn't cause any graphical glitches. This will take a bit of undertaking in Urho3D's rendering, I might need to talk to you Cadaver on the most optimal approach.

Cheers

**Comment by cadaver** [comment]
Currently each viewport is a new culling and shadow render, even if the camera is the same. Shadow maps are also not necessarily kept around after the rendering of each shadowed light. I agree that it would be beneficial to not do culling & shadows twice, but you may require some fairly heavy modifications to View / Renderer classes to enable that.

**Comment by boberfly** [comment]
Ok cheers I was reading through those classes. Maybe the best approach is to support stereoscopic rendering first as a toggle which would do all culling and shadow generation to a single larger matrix and then make it render left/right eye matrices. Maybe also either extend the Camera class or make a new StereoCamera class...

**Comment by cadaver** [comment]
Rendertarget changes are expensive, yes.

If you look at the CMD_SCENEPASS, CMD_FORWARDLIGHTS & CMD_LIGHTVOLUMES command execution, these could be quite plausibly be made to perform first all the work for one eye, then for the other, by writing to the same target and changing the GL / D3D viewport between the eyes. When each light is drawn completely to both eyes before moving on to the next, then the shadow map re-use will happen correctly.

**Comment by boberfly** [comment]
Thanks Cadaver that's probably how I'll approach it now, it seems a bit more trivial doing it this way and check camera_ to see if VR is enabled and do left/right eye stuff accordingly. I'd rather just extend the camera class to have some additional VR/stereo-related stuff, or at least just a boolean attribute and some kind of eye offset value.

I'll also keep an eye (or two eyes? ha!) on https://www.khronos.org/registry/gles/extensions/OVR/multiview.txt which could take adoption quickly in the future, probably for GearVR devices.

**Comment by boberfly** [comment]
Actually do you do things in Urho3D where a component looks for another component attached to the same node and does things accordingly? I guess a VRComponent or what have you could be attached that just stores the matrices of the left/right eye and the View class can just look if the camera's node has that component attached and apply things. Saves filling up the Camera component with extra logic that isn't needed in normal rendering situations.

**Comment by cadaver** [comment]
Yes, we often do things like that especially in physics and navigation, so it's perfectly doable.

**Comment by tersers** [comment]
Hey Cadaver,

It's been a while but I have some time again to integrate not only the Oculus RIft but also the new API from Valve to support _all_ VR devices. I would be happy to start on the integration process and while I don't have a rift I can borrow one from a friend.

**Comment by yushli** [comment]
Any updates on this issue? That sounds interesting/exciting to have VR supported integrated.

**Comment by yushli** [comment]
Is there any progress on VR support in Urho3D?

**Comment by JasonBSteele** [comment]
I would love to see this too - any update?

**Comment by Quibilia** [comment]
It's roughly possible on the application end, from my experience. I tried writing a VR program with Urho3D a few months ago, but it was never finished.

```
ovrSession session;
ovrGraphicsLuid luid;
ovrHmdDesc hmdDesc;
ovrSizei hmdRes;
ovrTrackingState ts;

void MainClass::Setup()
{
	if (OVR_FAILURE(ovr_Initialize(nullptr)))
	{
		URHO3D_LOGERROR("Failed to initialize the Oculus Rift SDK. VR will not work in this session.");
	}
	else
	{
		if (OVR_FAILURE(ovr_Create(&session, &luid)))
		{
			ovr_Shutdown();
			URHO3D_LOGERROR("Failed to create the required pointers for Oculus Rift support. VR will not work in this session.");
	
	}
		else
		{
			hmdDesc = ovr_GetHmdDesc(session);
			hmdRes = desc.Resolution;
			
			engineParameters_["WindowWidth"] = hmdRes.Width;
			engineParameters_["WindowHeight"] = hmdRes.Height;
		}
	}
}

void MainClass::Start()
{
	SubscribeToEvent(E_RENDERUPDATE, URHO3D_HANDLER(MainClass, HandleRenderUpdate));
}

void MainClass::Stop()
{
	ovr_Destroy(session);
	ovr_Shutdown();
}

void MainClass::HandleRenderUpdate(StringHash type, VariantMap& data)
{
	ts = ovr_GetTrackingState(session, ovr_GetTimeInSeconds(), ovrTrue);
	
	if (ts.StatusFlags & (ovrStatus_OrientationTracked | ovrStatus_PositionTracked))
	{
		// I haven't programmed with the newer SDK, so I'm not sure what you'd do with the data here.
	}
}

```

The biggest issue is that the window will be automatically placed on your main desktop, which isn't necessarily the Rift. It is possible to modify the Graphics class so that it uses the device LUID to setup a window on the Rift, but this can be tedious. What I would love is if there was an engine parameter that the user could use to specify the monitor to render to; I'm sure this is somehow possible using WindowPositionX and WindowPositionY, but a monitor specification would be much easier.

**Comment by eugeneko** [comment]
There is one more connected issue. It is easy to implement naive
two-viewport rendering, but it is tremendously wasteful to do tons of
pre-rendering work twice.
Urho also needs some mechanism to make several viewports 'grouped' to avoid
as much duplicate work as possible.

2016-09-03 20:49 GMT+03:00 Quibilia <notifications@github.com>:

**Comment by Quibilia** [comment]
@eugeneko Speaking of which, I should really put some multiple-viewport code into that last example.

**Comment by cadaver** [comment]
For visibility tests and view preparations you can define the CullCamera into a viewport, which combines most of the work. However shadows will still be rendered twice, since it's not a 100% grouping of the viewports.

**Comment by yushli** [comment]
Even if CullCamera is shared between two viewports, there is considerable performance drop( roughly 1/3 of the FPS) when adding a second viewport. Thus if Urho3d is to support VR, it needs to optimize this scenario. Also currently there is no post processing shader to do the lens distortion.

**Comment by cadaver** [comment]
You will never get a second scene render for free. The sequence for best performance is non-obvious, because some VR kits render the eye views into two separate textures. If every scene pass or light pass is grouped to render both eyes before moving to the next (this is necessary in case shadow maps are being re-used, because the shadow map will be overwritten by the next light), there are going to be a lot of rendertarget switches, which aren't free either. That said, contributions that don't completely mess up / complicate the code, while improving this situation, are welcome.

**Comment by Cygon** [comment]
NVidia's "Simultaneous Multi-Projection" does give the second scene render for almost free.

With it, you can tell the GPU to render everything to multiple render targets using different MVP matrices. Useful for rendering frames on multiple monitors (at different angles instead of just a wide image) or a VR HMD. Only supported in recent hardware, though.
