### ISSUE TITLE
RCCPP

### ISSUE THREAD

**Issue by alabd14313** [urho3d/Urho3D#1531]
Hello!
Why this branch didn't continue development: https://github.com/pamarcos/Urho3D/tree/RCCpp
It seems this feature can replace Angelscript. Please note your opinions...

**Comment by cadaver** [comment]
In absence of better information or answer from the author we can assume that he moved on to other interests. As far as I remember there never was a pull request.

**Comment by cadaver** [comment]
Closing for lack of further discussion / development.
