### ISSUE TITLE
Wrong color as in material

### ISSUE THREAD

**Issue by simon-matt** [urho3d/Urho3D#1533]
Hello,

I've created a simple cube and applied a material in Blender.
The diffuse color is #DDC9B4 with an intensity of 1. The specular and ambient light is disabled.
When I import this model and material in my Urho3D scene it shows a **wrong color**.

What should I change to get the **exact(!) color code** from Urho3D as I set **in my material**?

My (only) light is a directional light facing down with a brightness of 1, color white and alpha 1.
Distance between camera and plane (cube) doesn't change anything. I think the directional light does not have a position, right?

In this image you can see my target color (left) and the color I get from my scene (right).
![002 coloroffset](https://cloud.githubusercontent.com/assets/9771909/17871166/b1e297f0-68ba-11e6-80e5-1b412c813604.png)

The exact color codes are:
- Current: #CBA480 (R: 203, G: 164, B: 128)
- Target: #DDC9B4 (R: 221, G: 201, B: 180)

I hope someone can help me, Simon :)

**Comment by cadaver** [comment]
The formula for lighting is (NdotL) * light color * material diffuse * texture diffuse (or white if no texture)

Directional light is affected by the angle. Have you tested with no directional light, but just having full white ambient lighting?

**Comment by simon-matt** [comment]
If you mean "ambient light" do you mean the zone light?

I replaced all my light code with this and still wrong color:

```
Node* zoneNode = scene_->CreateChild("Zone");
Zone* zone = zoneNode->CreateComponent<Zone>();
zone->SetAmbientColor(Color(1.0f, 1.0f, 1.0f));
zone->SetBoundingBox(BoundingBox(-2000.0f, 2000.0f));
```

**Comment by 1vanK** [comment]
try unlit material

**Comment by simon-matt** [comment]
I can't figure out the problem.

@cadaver The zone light isn't working. The result is even a slightly darker color than the previous one.

@1vanK I enabled the shadeless mode in Blender for my material but still same result. Nothing has changed.

Is there anything more I can try?

**Comment by 1vanK** [comment]
A try 2 ways:
1) Material with texture:
```
<material>
    <technique name="Techniques/DiffUnlit.xml"/>
    <texture unit="diffuse" name="Textures/DesertSand.png" />
</material>
```
![2](https://cloud.githubusercontent.com/assets/13021826/18027241/88e16240-6c67-11e6-96f6-911ecbc34f67.png)

2) Material without texture:
```
<material>
    <technique name="Techniques/NoTextureUnlitVCol.xml"/>
    <parameter name="MatDiffColor" value="0.86328125 0.78515625 0.703125 1" />
</material>
```

And can't reproduce the problem

**Comment by 1vanK** [comment]
May be is some settings of gamma for OpenGL in your OS?

**Comment by 1vanK** [comment]
Or maybe you forgot slide up color value in blender:
![2](https://cloud.githubusercontent.com/assets/13021826/18027410/7bb73a78-6c6b-11e6-92e5-c1faeb384093.png)

**Comment by simon-matt** [comment]
I got a fully black cube when using:
```
<material>
    <technique name="Techniques/NoTextureUnlitVCol.xml"/>
    <parameter name="MatDiffColor" value="0.86328125 0.78515625 0.703125 1"/>
</material>
```

When I replaced the technique with 
`<technique name="Techniques/NoTextureUnlit.xml"/>`
I got #DCC8B3 which is 1/256th too dark :)

And finally I replaced the MatDiffColor with
`<parameter name="MatDiffColor" value="0.865 0.785 0.705 1"/>`
and I got the correct color.

I think the **real** issue here was the gamma corrected color in Blender.

Thank you for helping me with this issue and have a great day @1vanK
