### ISSUE TITLE
E_PHYSICSBEGINCONTACT2D should be send through participating nodes.

### ISSUE THREAD

**Issue by r-raymond** [urho3d/Urho3D#1535]
As of now, `E_PHYSICSBEGINCONTACT2D` and `E_PHYSICSENDCONTACT2D` are only send globally, not through the participating nodes. This means objects have to subscribe to all events and filter out everything in which they are not involved.

**Comment by cadaver** [comment]
This should be done similarly to the 3D physics, where there's global collision events, and node collision events. Shouldn't be hard to do.
