### ISSUE TITLE
AnimationController::IsPlaying returns false

### ISSUE THREAD

**Issue by EgorBo** [urho3d/Urho3D#1537]
I was playing with CrowdNavigation sample and noticed a small minor bug.
On Windows we can use "\" or "/" in paths so if I define an animation path like this:

`static const char* WALKING_ANI = "Models\\Jack_Walk.ani";`

I'll be able to use it in `animCtrl->Play(WALKING_ANI);` and it'll work, but
`animCtrl->IsPlaying(WALKING_ANI)` will always return false (obviously because Urho3D normalized the path).

**Comment by cadaver** [comment]
Good point. This will be somewhat of a performance loss, but the proper thing to do would be to normalize the resource path on each query.
