### ISSUE TITLE
Problems with two emitters

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1538]
Create node with 2 particle emitters: Fire and SmokeStack. It is flickering. It is some problem with sorting for alpha pass?

**Comment by cadaver** [comment]
Each emitter is a draw call, and the billboards inside are sorted properly. However, the drawcalls themselves get sorted according to whose bounding box is further behind, which may mean that the total order of quads is not correct back to front. Don't think there's an easy fix to this. You could test material draw order, or enabling depth write.

**Comment by 1vanK** [comment]
I think there is a good way, but I'm not sure that it should be in the official repository.

MultieffectEmitter:
1) AddEffect() & RemoveEffect() instead SetEffect (MultieffectEmitter can contains several effects, which will works simultaneously)
2) MultieffectEmitter must use single material for all effects (from firs effect, or need use MultieffectEmitter ::SetMaterial())

Although effects should be used single material, but they can use different UVs (ParticleEffect already has textureFrames_)

Or we can add this functional to exiting ParticleEmitter (but perhaps it breaks backward compatibility)
