### ISSUE TITLE
fbx model causes access violation when drawing

### ISSUE THREAD

**Issue by yushli** [urho3d/Urho3D#1540]
the following fbx can be opened and viewed successfully in open3mod (which is based on assimp), but when using Urho3d's Assimporter to create a mdl file and loaded into urho3d, it causes access violation when drawing.

<img width="960" alt="accessviolation" src="https://cloud.githubusercontent.com/assets/1681453/17998111/4ad870d2-6ba5-11e6-9498-6d14299ff1f0.png">

[models.zip](https://github.com/urho3d/Urho3D/files/438801/models.zip)

**Comment by 1vanK** [comment]
Hm, I opened space.mdl in editor without any problems

**Comment by yushli** [comment]
I forgot to attach the texture file. The crashes happends with the texture. 
http://zuoyouxi.gamemei.com/liyusheng/Space.PNG
It is pretty big. 6144x 3074. 
It can be opened succesfully with the texture in open3mod.

**Comment by cadaver** [comment]
Ok so you're using OpenGL. I'll test shortly...

**Comment by cadaver** [comment]
I cannot reproduce a crash on a Geforce GTX 570 / OpenGL mode. Can test later on worse machines with e.g. Intel GPU.

**Comment by yushli** [comment]
the material xml is auto generated by assetimporter. it is like
<?xml version="1.0"?>
<material>
	<technique name="Techniques/Diff.xml" />
	<texture unit="diffuse" name="Textures/Space.PNG" />
	<parameter name="MatDiffColor" value="0.588 0.588 0.588 1" />
	<parameter name="MatSpecColor" value="0 0 0 2" />
	<parameter name="MatEmissiveColor" value="0 0 0 1" />
</material>

**Comment by cadaver** [comment]
I don't think the material is relevant. What's your OS and GPU?

**Comment by yushli** [comment]
windows7 64bit, 8G memory, urho3d is building 64bit, GL3.
Graphics Card: AMD Radeon R7 200 series

**Comment by yushli** [comment]
The same code and build can load and display mutant model successfully.

**Comment by cadaver** [comment]
What happens if you halve the texture size? (If it still crashes, you can continue dropping the resolution until it's something like 2048 or below)

**Comment by yushli** [comment]
If converted to 50% of the original size, it works properly. Looks like my graphics card doesn't support such high resolution?

**Comment by yushli** [comment]
Looks like it is not Urho3d's issue. I will close it now. Thank you all for lookin into it! I really appreciate it.

**Comment by cadaver** [comment]
I have also seen texture creation failing gracefully (no crash, but texture is not created) when texture is too large; OpenGL functions shouldn't crash so it looks like a driver issue.

**Comment by yushli** [comment]
Yes it should be a driver issue. I was puzzled at first because open3mod can successfully open and display with the original texture on the same machine. It should be using DirectX instead of OpenGL. Thank you for taking time to look into it.
