### ISSUE TITLE
fbx causes assetimporter to crash

### ISSUE THREAD

**Issue by yushli** [urho3d/Urho3D#1542]
The following fbx can be opened and viewed successfully in open3mod. But if importing in the editor, or using the assetimporter to import model, it will cause crash. Looks like caused by adding the supress pivot feature. If -np is used, it runs fine. but the exported model is wrong. 

[plane.zip](https://github.com/urho3d/Urho3D/files/440573/plane.zip)

**Comment by yushli** [comment]
Looks like using -na is fixing the problem. The error is because one of the animated bone cannot be found in the bones.

**Comment by yushli** [comment]
AssetImporter.cpp, line 2799 
unsigned boneIdx = GetBoneIndex(*model, mainBoneName);
should add some check because if the bone is missing ,M_MAX_UNSIGNED will be returned and cause access violation in the next line.

**Comment by Lumak** [comment]
I found the bug that causes this.  This happens when a geometry has key animation, opposed to a bone.

**Comment by Lumak** [comment]
Submitted a PR: fixed a bug where crash is caused by geometry having key animation #1550

**Comment by yushli** [comment]
Thanks for looking into this and make the fix.
