### ISSUE TITLE
Stripe artefacts on Android

### ISSUE THREAD

**Issue by sabotage3d** [urho3d/Urho3D#1543]
Hi I am testing Urho3D 1.6 on my Android phone. The phone is with Snapdragon 650, Adreno 510 GPU. I am getting weird stripe artefacts on the RenderToTexture example, also on the Billboards example I am getting similar stripe artefacts on the mushrooms when the light flies over. I will try to make some screenshots if it is not a known issue.

**Comment by cadaver** [comment]
If stripe artifacts are shadow related, these happen even in desktop due to self-shadowing artifacts. Artifacts in RenderToTexture sound more suspicious; I'll investigate this later, however note that due to possibly crappy GPU drivers, differing hardware, and especially limited resources to test on differing hardware, this may be left as a "your mileage may vary" kind of issue.

**Comment by OldSnake22** [comment]
I have some shadow artifacts issues since the projection matrix changes commit. I think it would be worth to check it :)

**Comment by cadaver** [comment]
Care to elaborate? In some of the examples, your own program, or where?

**Comment by OldSnake22** [comment]
The shadow quality degradation issue is especially visible on terrain shadows (wich were very nicely rendered before that commit). Will try to make some video today.

**Comment by cadaver** [comment]
OpenGL or Direct3D?

**Comment by OldSnake22** [comment]
DirectX11. I think it is some shadow acne artifacts similar to this: http://http.developer.nvidia.com/GPUGems3/elementLinks/08fig03.jpg

**Comment by cadaver** [comment]
I believe I see the issue, it looks like automatic the shadow bias adjustment according to cascade size is using incorrect values after the projection matrix change, resulting in worse self-shadow artifacts on terrain. No need to make a video.

**Comment by OldSnake22** [comment]
Thank you ! I was going to report it today, glad that you found the issue already.

**Comment by cadaver** [comment]
The difference is in the handling of normal offset multiplication factor, which comes from camera's ortho size. Additionally I found that D3D and OpenGL bias is different, which I put into a separate issue.

**Comment by cadaver** [comment]
Hm, actually now that I retest I do not find difference even in the normal offset. No need to make a video, but if you can post your camera parameters and light bias parameters, and possibly before/after pictures, it would help. Ensure that both builds are using the same API.

**Comment by cadaver** [comment]
Fixed the D3D / OpenGL discrepancy in slope-scale bias. There was a quite serious hashing bug that would prevent the use of correct bias value on D3D11 quite randomly. Recommend testing now if the terrain shadow bug is fixed, or if it's indeed related to the camera projection changes.

**Comment by OldSnake22** [comment]
It does not fix the terrain shadows artifact on my side. Here is what i am using as bias parameters for the directional light:

BiasParameters(0.000025f, 0.5f)

**Comment by cadaver** [comment]
Ok, can you confirm commit message or hash of the last working revision for you? Also, camera parameters would be good to know, including whether it's ortho/perspective.

**Comment by OldSnake22** [comment]
I just took the latest revision when i saw your fix and compiled it and double checked it. 

My camera is perspective and here is my near and far clip:

nearclip: 0.2
farclip: 8192.0

**Comment by cadaver** [comment]
Thanks. I mean last revision when it still worked for you. Was it exactly before the projection matrix branch getting merged?

**Comment by OldSnake22** [comment]
Oh i see, hum no my revision was maybe a week older than the projection matrix merge.

**Comment by cadaver** [comment]
Ok, at this point I can't produce differences in terrain+shadows between the old and new camera. Also getting the same amount of batches, which would point to the camera frustums being the same size before & after. My suggestion is to change the bias values to what appears to work well with current Urho, since they should now be the same between all APIs.

If you want me to investigate deeper, please produce a small sample program (can be based on the examples) that highlights the issue, and point me to the exact commit where you notice the behavior changed.

**Comment by OldSnake22** [comment]
Alright thanks cadaver, i will work on this issue and give you detailled infos.

**Comment by cadaver** [comment]
Worse shadow artifacts on mobile is a fact of life due to lack of hardware smooth PCF, however will push a depth bias adjust to 10_RenderToTexture which helps the stripes on the screen. Then will close this issue as the projection matrix discussion has its own dedicated issue now.

**Comment by sabotage3d** [comment]
Thanks a lot.
