### ISSUE TITLE
Compile error with VisualStudio2015 Urho3D V1.6

### ISSUE THREAD

**Issue by 3DRaddict** [urho3d/Urho3D#1544]
On building the projects for the VisualStudio2015 Urho3D V1.6 I received one compile error, namely:
**_C:\Users\Allan\Documents\Urho3D-master\Source\Urho3D\Graphics\Direct3D11\D3D11GPUObject.cpp(36): error C2664: 'Urho3D::GPUObjectHandle::GPUObjectHandle(Urho3D::GPUObjectHandle &&)': cannot convert argument 1 from 'int' to 'const Urho3D::GPUObjectHandle &'_**
On investigating, I traced it to:
`GPUObject::GPUObject(Graphics* graphics) :
    graphics_(graphics),
    object_(0)
{
    if (graphics_)
     graphics->AddGPUObject(this);
}
`
By replacing **object_(0)** with **object_()**, all compiled successfully

**Comment by cadaver** [comment]
Urho 1.6 does not contain D3D11GPUObject.cpp. Please ensure you have a fresh checkout with no leftover files from an earlier version, and regenerate the solution through CMake.

**Comment by 3DRaddict** [comment]
Thank you... that was the answer
