### ISSUE TITLE
Add function to convert JSONValueType and JSONNumberType to String.

### ISSUE THREAD

**Issue by hsnabn** [urho3d/Urho3D#1546]
Hi.

I'd like to propose adding a function to properly convert a `JSONValueType` and `JSONNumberType` to a `String`.

The reason I ask for this is because it would make turning a `JSONValue` into a `Variant` much easier, because `JSONValue::GetVariant()` expects the value to have been set using `JSONValue::SetVariant()`, as far as I know. And so, I wrote my own function to turn a value/number type into a string (I consider it very hacky, though).

With a built-in function to properly convert the value/number type to a string, we can get a proper `Variant` from the `JSONValue` via `JSONValue::GetVariantType(VariantType)` function, where we get the `VariantType` using `Variant::GetTypeFromName(String)`, where the string is the type name of the JSON value.

Thanks for reading.

**Comment by cadaver** [comment]
Commit going in shortly. Note that the typenames between Variant & JSONValue do not all match, for example there's numbertype for float or double, which I named "Real" whereas a floating point Variant is either "Float" or "Double".
