### ISSUE TITLE
CrowdAgent speed decreased, when I rotate node in E_CROWD_AGENT_NODE_REPOSITION

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1548]
```
void PlayerLogic::Start()
{
    SubscribeToEvent(node_, E_CROWD_AGENT_NODE_REPOSITION, URHO3D_HANDLER(PlayerLogic, HandleCrowdAgentReposition));
}

void PlayerLogic::HandleCrowdAgentReposition(StringHash eventType, VariantMap& eventData)
{
    //node_->SetRotation(Quaternion());
}
```
It is very strange, but when I uncomment rotation, movement speed decreased halved, and hero sometimes twitches. (I can give full source code if needed)

I use agent settings:
```
        agent->SetMaxSpeed(40.0f);
        agent->SetMaxAccel(1000.0f);
```

**Comment by 1vanK** [comment]
Wint SetRotationSilent() this problem is missing

**Comment by cadaver** [comment]
The rotation change feeds back to CrowdAgent::OnMarkedDirty(), where it feeds the position back to the crowd system. This shouldn't happen when only rotation is changed and should be easy to fix. It's similar to node transform tracking for rigidbodies.

**Comment by 1vanK** [comment]
NavMesh does not exactly match ground mesh (in some areas hero fly above the earth, in other lowered under ground). Previously, I had planned to correct position in this event handler. But it seems this will cause problems. How should I proceed?

**Comment by cadaver** [comment]
Have separate navigation node and rendering node?

**Comment by 1vanK** [comment]
Oh thanks! Great idea!

**Comment by 1vanK** [comment]
I think event E_CROWD_AGENT_NODE_REPOSITION should be send after node_->SetPosition(newPos);

My rendering node is child for navigation node. I correct its position in eventhanler, but after that nav node position changes and child node also moved.

**Comment by cadaver** [comment]
In general I'd agree, this is the pattern used e.g. by UI events, first something changes, then the event is sent and you can inspect the changed value.

Maybe someone more familiar with the navigation system can fill in if this change would have downsides or unexpected behavior. The event data does include the new position that is going to be set, so you could already read that.

**Comment by cadaver** [comment]
I observe the slowing down even in crowd navigation demo, which also rotates the agent. Changing the event to be sent last fixes this issue, so I believe I'm going to make the change in any case. Also going to add a check that changing only rotation in OnMarkedDirty() doesn't reset the agent state.

**Comment by 1vanK** [comment]
Thanks for all!
