### ISSUE TITLE
Are there unit tests?

### ISSUE THREAD

**Issue by keithyipkw** [urho3d/Urho3D#1549]
I could not find any unit tests. The test in the build logs in OS X looked like compilation tests on the demo samples. I opened some of the demo, they did look like demo only.

**Comment by cadaver** [comment]
There are no unit tests as such. The CI build process runs each of the samples for a time to check that they don't error or crash.

**Comment by keithyipkw** [comment]
How does the project ensure the logic correctness?

**Comment by weitjong** [comment]
Agree that this is not ideal. Contribution is welcome. (Continuous)
Integration test via Travis and AppVeyor is easier to setup without
burdening the devs further, while unit test is not so.

**Comment by cadaver** [comment]
Something like maths classes or containers could benefit from unit tests, however in general, while testing rendering, physics or general game object logic the complexity of interaction grows quickly, and unit tests wouldn't capture that many useful regressions.

**Comment by keithyipkw** [comment]
There are many contributors in this project. If someone tries to fix a bug, there is no ways (code review does not quite count) to tell if they break other things or introduce unexpected behavior changes, even if they want to verify their code.

**Comment by cadaver** [comment]
It's not ideal, but in general you will have an idea of the impact of the code you're touching, based on which classes you work on. For example if you touch physics classes, you can be fairly sure of rendering not being affected, and you would exercise physics features to see that they work as they used to.

This being a hobby project, someone would have to write the unit tests (as a hobby), and once they were in place, we would burden contributors to add tests to each new feature, like @weitjong touched upon.

**Comment by cadaver** [comment]
Actually I think the most insidious situations are those which require an actual game project or complex assets to reveal an issue. For example, we don't have any example models with morphs in the repository, so the morph feature in AnimatedModel is not being exercised. And also where GPU is involved (e.g. is a model skinned correctly) just unit tests themselves aren't the complete answer. Being a hobby project we're probably never going to setup a render farm like Unity to test different GPU's either :)

**Comment by keithyipkw** [comment]
I am not sure how Unity tests their products. From what I read on the internet (potentially biased), they suffer from the problems of fixing here, breaking there. Other game engines seem to have the same problem. The people did not state clearly what the problems were so they were possibly some bugs after integrations.

**Comment by cadaver** [comment]
Yes, Unity has a reputation for regressions, though they certainly do test their codebase: http://aras-p.info/blog/2013/11/08/some-unity-codebase-stats/

**Comment by weitjong** [comment]
I think we also have to be pragmatic here considering the limited resources that we have and also the nature of the problem domain. IMHO, it is easier said than done to test the subsystems or classes at a unit level for a game engine project as the output of classes being tested are spatial and temporal in many cases, unlike Math class where we can easily test its output given a predefined set of input programmatically.
