### ISSUE TITLE
Shadows artifacts since latest projection matrix code changes 

### ISSUE THREAD

**Issue by OldSnake22** [urho3d/Urho3D#1551]
@cadaver So i am opening a proper issue for this bug.

I have tested it by compiling the engine just before the projection matrix branch merge and i can confirm that everything is working fine before the merge. But after that projection matrix branch merge i have shadow issues for all light source types but it is especially visible with terrain shadows. Like i said i have observed huge shadow quality degradation with objects lit by point and spot lights.

I have done my test on DX11 and PBR renderpath. 

GPU: NVidia GTX 760 (tested with two different drivers)

Here is a video of terrain shadow artifacts:

https://www.youtube.com/watch?v=eLRxBge9L34

**Comment by cadaver** [comment]
If you can't make a full repro program like I suggested, please provide your full camera & light setup code.

**Comment by OldSnake22** [comment]
m_pMainCamera->SetNearClip(0.2f);
m_pMainCamera->SetFarClip(8192.0f);

m_pSunLight->SetCastShadow(true);
m_pSunLight->SetShadowBias(BiasParameters(0.000025f, 0.5f));
m_pSunLight->SetShadowCascade(CascadeParameters(16.0f, 50.0f, 75.0f, 150.0f, 0.9f));
m_pSunLight->SetShadowResolution(1.0f);
m_pSunLight->SetSpecularIntensity(1.0f);

And i have of course also enabled terrain shadows.

**Comment by cadaver** [comment]
Thanks. Sun node direction would also be good, to know the angle the light is coming from.

**Comment by OldSnake22** [comment]
Here is the light node world direction: -0.451326 -0.804411 -0.386299

**Comment by cadaver** [comment]
Ok, now see the bug. The relevant thing to see it is to use deferred rendering.

**Comment by OldSnake22** [comment]
Good news :) Thanks to have took the time to find the issue ! Will test the fix as soon as you commit it.

**Comment by cadaver** [comment]
Fix should now be in. It was related to numeric inaccuracy, which manifested in the world space reconstruction with a large far clip.

**Comment by OldSnake22** [comment]
Thank you, everything is working fine now !
