### ISSUE TITLE
Internal compiler error on MinGW GCC 6.2.0 x32

### ISSUE THREAD

**Issue by iSLC** [urho3d/Urho3D#1552]
I was trying to build Urho3D from repository source using MinGW GCC 6.2.0 x32 and I encountered a `internal compiler error: Segmentation fault` while it was building Bullet. I'm about to try a build without SSE to see if it affects anything. I know that SSE on MinGW was always an issue when building Bullet. Also try building with lower MinGW versions.

I've tried building Bullet from repository and seems to also generate several errors like this in other places (_VoronoiFractureDemo_). I'll report these to the Bullet repository.

```
[ 35%] Building CXX object Source/ThirdParty/Bullet/CMakeFiles/Bullet.dir/src/BulletCollision/CollisionDispatch/btInternalEdgeUtility.cpp.obj
cd /d E:\Urho3D\cb-build_32_gl\Source\ThirdParty\Bullet && D:\MinGW\620_32\bin\g++.exe   -DGLEW_NO_GLU -DGLEW_STATIC -DHAVE_STDINT_H -DSTBI_MINGW_ENABLE_SSE2 -DTOLUA_RELEASE -DURHO3D_ANGELSCRIPT -DURHO3D_CXX11 -DURHO3D_FILEWATCHER -DURHO3D_LOGGING -DURHO3D_LUA -DURHO3D_NAVIGATION -DURHO3D_NETWORK -DURHO3D_PHYSICS -DURHO3D_PROFILING -DURHO3D_THREADING -DURHO3D_URHO2D @CMakeFiles/Bullet.dir/includes_CXX.rsp -std=gnu++11 -Wno-invalid-offsetof -march=native -ffast-math -msse -msse2 -static -static-libgcc -static-libstdc++ -fno-keep-inline-dllexport -mstackrealign -fdiagnostics-color=auto -O3 -DNDEBUG   -o CMakeFiles\Bullet.dir\src\BulletCollision\CollisionDispatch\btInternalEdgeUtility.cpp.obj -c E:\Urho3D\Source\ThirdParty\Bullet\src\BulletCollision\CollisionDispatch\btInternalEdgeUtility.cpp
In file included from E:/Urho3D/Source/ThirdParty/Bullet/src/LinearMath/btAlignedObjectArray.h:20:0,
                 from E:/Urho3D/Source/ThirdParty/Bullet/src/LinearMath/btHashMap.h:20,
                 from E:\Urho3D\Source\ThirdParty\Bullet\src\BulletCollision\CollisionDispatch\btInternalEdgeUtility.h:5,
                 from E:\Urho3D\Source\ThirdParty\Bullet\src\BulletCollision\CollisionDispatch\btInternalEdgeUtility.cpp:1:
E:/Urho3D/Source/ThirdParty/Bullet/src/LinearMath/btScalar.h: In member function 'virtual void btConnectivityProcessor::processTriangle(btVector3*, int, int)':
E:/Urho3D/Source/ThirdParty/Bullet/src/LinearMath/btScalar.h:448:16: internal compiler error: Segmentation fault
  return sqrtf(y);
                ^
libbacktrace could not find executable to open
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://sourceforge.net/projects/mingw-w64> for instructions.
mingw32-make.exe[2]: *** [Source/ThirdParty/Bullet/CMakeFiles/Bullet.dir/src/BulletCollision/CollisionDispatch/btInternalEdgeUtility.cpp.obj] Error 1
mingw32-make.exe[1]: *** [Source/ThirdParty/Bullet/CMakeFiles/Bullet.dir/all] Error 2
mingw32-make.exe: *** [all] Error 2
Source\ThirdParty\Bullet\CMakeFiles\Bullet.dir\build.make:762: recipe for target 'Source/ThirdParty/Bullet/CMakeFiles/Bullet.dir/src/BulletCollision/CollisionDispatch/btInternalEdgeUtility.cpp.obj' failed
mingw32-make.exe[2]: Leaving directory 'E:/Urho3D/cb-build_32_gl'
CMakeFiles\Makefile2:1239: recipe for target 'Source/ThirdParty/Bullet/CMakeFiles/Bullet.dir/all' failed
mingw32-make.exe[1]: Leaving directory 'E:/Urho3D/cb-build_32_gl'
E:/Urho3D/cb-build_32_gl/Makefile:148: recipe for target 'all' failed
Process terminated with status 2 (6 minute(s), 4 second(s))
4 error(s), 3 warning(s) (6 minute(s), 4 second(s))
 ```

_The three warnings are related to SDL shadowing variables not to this._

**Comment by weitjong** [comment]
I suppose you are using 1.6 release tag because there is already patch in the latest master branch to workaround exactly this known issue.

**Comment by weitjong** [comment]
I think I know why already, there is a mistake in that patch's condition in the master branch. Should be easy to fix.

**Comment by iSLC** [comment]
Regarding that first comment. Yes you are correct. Apparently, I did a `git fetch origin` instead of a `git pull` which did not obtained the latest code from the repository.

I only realized that when I tried to compile with MinGW 5.4 and received some rounding errors. Then I remembered I've seen a commit regarding this issue (02e1aec083a19b902d12b8d76f9846fb3e1dcbb7). And while looking for the changes from that particular commit to change the MinGW version number. I realized I was behind with the latest repository changes.

I did a `git pull` and compiled with MinGW 5.4 and for now, everything works just fine.

Then I tried building Bullet directly from the official repository. And soon realized that Bullet has some compilation issues with MinGW >= 6.x and then some runtime issues (_crashes_) with anything lower than that. The important thing is the Urho works for now. Sorry for bothering.

**Comment by weitjong** [comment]
No problem. The condition in the patch is indeed incorrect. The original intention is to apply the workaround when using MinGW >= 6.1.0 but somehow that is not what being implemented in the script.

**Comment by damu** [comment]
Could you fix this in the stable version 1.6 (maybe a 1.6.1)? I just stumbled upon the same error it seems when I tried to finish and update the build tutorial (yeah I'm super late) for MinGW and that's quite a bummer.
http://i.imgur.com/pBPYVzp.jpg
https://github.com/urho3d/Urho3D/wiki/Compiling-Urho3D-on-Windows

**Comment by damu** [comment]
The newest version from Git worked.

**Comment by weitjong** [comment]
You can get all the changes related to MinGW since 1.6 using this command in the root of Urho3D project.
```
git log --grep MinGW --since 1.6
```

**Comment by damu** [comment]
This is the result of _git log --grep MinGW --since 1.6_: https://justpaste.it/yado
I'm not sure what you wanted but I made tests with various Git versions to see which works:
4b964a6989d34ff3430b964f9dcb2d3eb0ae1dcc (Aug 25 08:49:44) this internal compiler error
02e1aec083a19b902d12b8d76f9846fb3e1dcbb7 (Aug 25 18:21:58) this internal compiler error
11f319c2cd2675fceee5419657f093545acb4df2 (Aug 31 14:50:02) a multiple definitions error: http://i.imgur.com/9GP7fnS.png
13ed7bbbb6f4e0d1e7db6b13223835b86b582757 (Sep 4 12:02:05) works fine

**Comment by weitjong** [comment]
Basically just want to say, those who want to use 1.6 but still want to use
MinGW 6.1.0+, then they could cherry-pick those shortlisted commits to fix
the ICE issue.

**Comment by qwertysam** [comment]
I came across the error while compiling with MingW on Ubuntu 17.04 using GCC 6.3.0 and CMAKE 3.7.2. I have Ubuntu 16.04 using GCC 5.4.0 and CMAKE 3.5.1 on a different computer where Urho3D compiles just fine. I've tried using the stable release as well as the latest code from the master branch, and get the same errors. 

Using configuration generated by *cmake_mingw.sh*
```
[ 35%] Building CXX object Source/ThirdParty/Bullet/CMakeFiles/Bullet.dir/src/BulletCollision/CollisionDispatch/btHashedSimplePairCache.cpp.obj
[ 35%] Building CXX object Source/ThirdParty/Bullet/CMakeFiles/Bullet.dir/src/BulletCollision/CollisionDispatch/btInternalEdgeUtility.cpp.obj
In file included from /home/samson/Urho3D-1.6/Source/ThirdParty/Bullet/src/LinearMath/btAlignedObjectArray.h:20:0,
                 from /home/samson/Urho3D-1.6/Source/ThirdParty/Bullet/src/LinearMath/btHashMap.h:20,
                 from /home/samson/Urho3D-1.6/Source/ThirdParty/Bullet/src/BulletCollision/CollisionDispatch/btInternalEdgeUtility.h:5,
                 from /home/samson/Urho3D-1.6/Source/ThirdParty/Bullet/src/BulletCollision/CollisionDispatch/btInternalEdgeUtility.cpp:1:
/home/samson/Urho3D-1.6/Source/ThirdParty/Bullet/src/LinearMath/btScalar.h: In member function ‘virtual void btConnectivityProcessor::processTriangle(btVector3*, int, int)’:
/home/samson/Urho3D-1.6/Source/ThirdParty/Bullet/src/LinearMath/btScalar.h:448:16: internal compiler error: Segmentation fault
  return sqrtf(y);
                ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
Source/ThirdParty/Bullet/CMakeFiles/Bullet.dir/build.make:758: recipe for target 'Source/ThirdParty/Bullet/CMakeFiles/Bullet.dir/src/BulletCollision/CollisionDispatch/btInternalEdgeUtility.cpp.obj' failed
make[2]: *** [Source/ThirdParty/Bullet/CMakeFiles/Bullet.dir/src/BulletCollision/CollisionDispatch/btInternalEdgeUtility.cpp.obj] Error 1
CMakeFiles/Makefile2:1240: recipe for target 'Source/ThirdParty/Bullet/CMakeFiles/Bullet.dir/all' failed
make[1]: *** [Source/ThirdParty/Bullet/CMakeFiles/Bullet.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

Using configuration generated by *cmake_generic.sh*
```
[ 76%] Building CXX object Source/Tools/Urho3DPlayer/CMakeFiles/Urho3DPlayer.dir/Urho3DPlayer.cpp.o
[ 76%] Linking CXX executable ../../../bin/Urho3DPlayer
/usr/bin/ld: cannot find -lGL
collect2: error: ld returned 1 exit status
Source/Tools/Urho3DPlayer/CMakeFiles/Urho3DPlayer.dir/build.make:95: recipe for target 'bin/Urho3DPlayer' failed
make[2]: *** [bin/Urho3DPlayer] Error 1
CMakeFiles/Makefile2:1516: recipe for target 'Source/Tools/Urho3DPlayer/CMakeFiles/Urho3DPlayer.dir/all' failed
make[1]: *** [Source/Tools/Urho3DPlayer/CMakeFiles/Urho3DPlayer.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

For compiling I simply execute the command `make` in the directory configured by the `cmake_xxxx.sh` script.

**Comment by weitjong** [comment]
You have to recreate the build tree from scratch when retrying.

**Comment by qwertysam** [comment]
Yup, that's what I've been doing. I just downgraded my g++ and gcc compilers from 6.3.0 to 5.4.1 and the error is persisting.

**Comment by weitjong** [comment]
The reason I asked you to regenerate from scratch is to make sure you don't have previous CMake cache variables in the build tree that could interfere with the build tree generation, this is especially true when you are retrying on a same build tree location again and again. For me, this issue is already closed as I could not reproduce it anymore (the last time I checked). 

To troubleshoot, you can double check if your generated Makefiles are using -O2 instead of -O3 (which causes ICE). If it is still -O3 then that is the problem. Again, if you are unsure, just nuke everything before retrying, even the source tree if you are not using out-of-source build tree.

**Comment by weitjong** [comment]
Btw, "master" is our last stable branch.

**Comment by qwertysam** [comment]
> check if your generated Makefiles are using -O2 instead of -O3 (which causes ICE)

c-c Noob vocabulary please. I don't see those tags or suffixes anywhere within my makefiles. 

I'm going to troubleshoot my CMake distro to see if I can achieve some different results.

**Comment by weitjong** [comment]
My apology. ICE stands for Internal Compiler Error. The -O3/2 refers to the configured compiler flags for the build, you can find the flags in a file called "flags.txt" or something like that somewhere in the generated build tree. Good luck.
