### ISSUE TITLE
Image::GetNextLevel should return nullptr if Image is already 1x1x1

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1554]
... because otherwise we can retreive 'next mip levels' endlessly.

**Comment by cadaver** [comment]
I disagree; think of the Image class as a poor man's paint program. A paint program will not delete the image if you tell it to halve the size lower than possible, instead it will just keep it at the lowest size. 

This is for safety & simplicity in texture loading if the user would instruct the texture config to use more quality reduction levels than possible. Also, in most cases (like creating a GPU texture) you would already need to know the number of mip levels beforehand, for which you can use the static helper function Texture::CheckMaxLevels().

I will add an API documentation note, though.

**Comment by eugeneko** [comment]
Thank you, documentation note is a pretty good fix.
