### ISSUE TITLE
decals are not right when mutil-click on the mushroom

### ISSUE THREAD

**Issue by xiongyaya** [urho3d/Urho3D#1555]
in the decal example, click ground or will create decal on it, ground is all right, but decal on mushroom will disappear when click again.

**Comment by xiongyaya** [comment]
more often when you click on mushrooms and then click around( ground or neighbouring mushroom)

**Comment by cadaver** [comment]
Closing, since no new discussion, and this is not an actual bug / functionality to configure the allowed vertex count exists.
