### ISSUE TITLE
Adding elements from [POD]Vector to itself crashes applictaion.

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1556]
Any insertions that consume elements from the same vector may crash applictaion because of wrong resize implementation.

```
    Vector<String> vec = { "One", "Two", "Three" };
    vec.Push(vec.Front()); // Dies here
```

**Comment by eugeneko** [comment]
I disagree.
Huh... I mean... Urho need better solution.
Even with these new checks this vector is vulnerable to such problems. And it is also not-self-assignable because of similar reason. I suppose it is better to implement Vector in STL style when old buffers are not removed before new ones are completely filled. It does not look important because 
nobody noticed that bug until now. However, I think it should be completely fixed at some point.
When I have propper solution, I'll create a PR.

Here is some synthetic crash example:

```
struct Иode
{
    Vector<Иode> children;
    String tag;
};

    Vector<Иode> nodes(1);
    nodes[0].tag = "One";
    nodes[0].children.Push(Иode());
    nodes.Push(nodes[0].children[0]);
```

**Comment by cadaver** [comment]
Yes, better solution is welcome. Looking at the fix I was making I knew it was a band-aid, because there are compound operations where the resize happens first (deleting the buffer), followed by move / insert operations.
