### ISSUE TITLE
Reloading any resource make attribute editor lose focus.

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1557]
If I force reloading of some resource when I am editing component attributes, text fields lose focus, up/down buttons hangs, etc and editing became unconvinient.
I am working on asset generation, so such case is important to me.
Do you have thoughts about the reason of such behavior?
Could you fix it or give me some ideas how I can do it by myself?

**Comment by cadaver** [comment]
It's an inspector full refresh. It was originally added for scripts, and seems to be necessary for scripts only (as their variables may change, requiring a refresh of attributes)

**Comment by cadaver** [comment]
Check if the commit I just pushed resolves your issue. It doesn't check if the script is actually being shown on the inspector, though.

**Comment by eugeneko** [comment]
It works! Thank you for quick resolving!
