### ISSUE TITLE
NavMesh not updated when node with obstacle is moved

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1558]
I think need to call
```
    if (ownerMesh_)
        ownerMesh_->ObstacleChanged(this);
    MarkNetworkUpdate();
```
like Obstacle::SetHeight()

**Comment by cadaver** [comment]
Yes, missing node dirty handling. It can have some performance implications if the node is moved smoothly / frequently, but missing it altogether looks wrong.
