### ISSUE TITLE
No way to recieve normal of NavMesh poly

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1559]
I use this code for positioning obstacles

```
Vector3 pos = Vector3(Random(90.0f) - 45.0f, 0.0f, Random(90.0f) - 45.0f);
pos = navMesh->FindNearestPoint(pos, Vector3(0.0f, 100.0f, 0.0f));
```

![2](https://cloud.githubusercontent.com/assets/13021826/18203381/6a65d604-711f-11e6-94b2-d4f4d35a0aba.png)

Obstacle not parallel to navmesh, but only touch single side. And navmesh generates incorrect (agent passes through the obstacle).

When I move node down:

```
            Vector3 pos = Vector3(Random(90.0f) - 45.0f, 0.0f, Random(90.0f) - 45.0f);
            pos = navMesh->FindNearestPoint(pos, Vector3(0.0f, 100.0f, 0.0f));
            pos += Vector3::DOWN * 0.3f;
```

all works correct:

![3](https://cloud.githubusercontent.com/assets/13021826/18203529/3d3c0d5a-7120-11e6-9c2a-de5994ab0aca.png)

but then for the obstacles its needed to create a separate node. Also it is difficult to determine what value the node must be immersed (the slope can be steep). But in any case, the object is also to be rotated parallel to the ground.

So I think FindNearestPoint should also return normal of NavMesh

**Comment by 1vanK** [comment]
Hmm, it seems in Detour all obstacles only vertically

**Comment by cadaver** [comment]
Detour's findNearestPoly itself doesn't return a normal, so I guess it would need to be calculated from the polygon. Feel free to make a PR if you implement this.

**Comment by 1vanK** [comment]
Maybe someone knows, in detour vertical component of velocity always == 0? I can not rotate the hero parallel to the ground even in E_CROWD_AGENT_NODE_REPOSITION event

**Comment by JSandusky** [comment]
The dtPoly's will always be planar, so you can just pick any 3 vertices as they will never be coplanar and get a normal from that.

> Maybe someone knows, in detour vertical component of velocity always == 0? I can not rotate the hero parallel to the ground even in E_CROWD_AGENT_NODE_REPOSITION event

IIRC, the vertical will only be present when navigation an off-mesh link.

I strongly advise against treating anything Detour/Recast related as a black-box to not touch. You will very likely have to make extensive modifications and even ports (such as to OpenCL as I've done) for the different parts to fit your project needs.
