### ISSUE TITLE
Where is alphamask technique for PBR shaders?

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1564]
Just curious. Corresponding define in shader exists.

**Comment by cadaver** [comment]
It's probably missing just because it was not needed in developing the example. PR of missing techniques is welcome.

**Comment by dragonCASTjosh** [comment]
the only technique that shouldnt work is terrain due how its handled. So its just a case of adding the techniques xml.

**Comment by cadaver** [comment]
Alphamask techniques have now been removed from the repo in favor of defining in materials, so this can be closed.
