### ISSUE TITLE
Unnecessary shader compilation defines

### ISSUE THREAD

**Issue by cadaver** [urho3d/Urho3D#1567]
As a result from the added feature of shader defines in material, these are going to be applied indiscriminately to shaders that don't need them. For example PACKEDNORMAL defined in material gets applied to the shadow shader, though it doesn't read the normal map. Either detect actually used compilation defines from the shader code, or provide a mechanism (for example undef preprocessor statement) to specify unused defines in shader code.

**Comment by eugeneko** [comment]
What about per-pass parameters like vsundef/psundef to specify defines that should be always ignored?

**Comment by cadaver** [comment]
That is possible too, but requires annotating the technique files. It's true that sometimes the unneeded defines are specific to a pass.

**Comment by 1vanK** [comment]
May be <shader vsdefines="DEFINE1 DEFINE2" psdefines="DEFINE3 DEFINE4" passes="passname1 passname2"/>

**Comment by cadaver** [comment]
An enhancement that allows to target defines to certain pass can be good to have, however I'd like it more for extra control, and not as necessary to avoid unnecessary defines & shader compiles. You'd have to write it to each material.

**Comment by eugeneko** [comment]
I've just thought about the same solution as @1vanK 's.

@cadaver What kind of solution are you searching? I think user anyway should write something in either material or technique to make defines pass-specific. However, you don't like both ways:
> You'd have to write it to each material.
> That is possible too, but requires annotating the technique files


> I'd like it more for extra control

I'm unsure that I understood you.

**Comment by cadaver** [comment]
I meant that the ideal is that the Shader automatically understands which defines are unnecessary, *but* for extra control (and some special effects) it'd be nice to send defines into specific passes on purpose from the material.

But in fact that seems complex to find out the used defines without writing a complete preprocessor, so your solutions are more practical.
