### ISSUE TITLE
CrowdAgent::Remove() cause crash

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1570]
```
void PlayerLogic::HandleCrowdAgentReposition(StringHash eventType, VariantMap& eventData)
{
    using namespace CrowdAgentReposition;
    CrowdAgent* agent = static_cast<CrowdAgent*>(eventData[P_CROWD_AGENT].GetPtr());
    bool arrived = eventData[P_ARRIVED].GetBool();

    if (arrived)
    {
        agent->Remove();
        return;
    }
```

**Comment by cadaver** [comment]
It's a typical pattern in e.g. UI event sending to code defensively and check after each event if "self" still exists. However in this case the crowd agent update is invoked from the crowd library, which may not tolerate arbitrary removal. I'll check quickly, but in case it doesn't, what you can do is to set a flag and remove later (e.g. next update)

**Comment by 1vanK** [comment]
Also maybe you know. In my game monsters are walks to the player and push him from its place. I have not found a way to deprecate it for agent. So I decided remove CrowdAgent from player node and add Obstacle component when player is hold. But it looks as dirty hack.

**Comment by 1vanK** [comment]
Many thanks!

**Comment by 1vanK** [comment]
![2](https://cloud.githubusercontent.com/assets/13021826/18364409/df551258-7616-11e6-923c-43acf631f410.png)

After deleting Obstacle component and adding CrowndAgent? node can not move to target anymore. If just remove and add CrowndAgent (without creating and removing obstacle), all works.

```
void PlayerLogic::HandleCrowdAgentReposition(StringHash eventType, VariantMap& eventData)
{
    if (arrived)
    {
        agent->Remove();
        node_->CreateComponent<Obstacle>();
        return;
    }
```

```
void PlayerLogic::PostUpdate(float timeStep)
{
     if (INPUT->GetMouseButtonDown(MOUSEB_RIGHT))
    {
        Vector3 hitPos;
        if (MouseToGround(hitPos))
        {
            Obstacle* obstacle = node_->GetComponent<Obstacle>();
            if (obstacle)
                obstacle->Remove();

            DynamicNavigationMesh* navMesh = GetScene()->GetComponent<DynamicNavigationMesh>();
            Vector3 pathPos = navMesh->FindNearestPoint(hitPos, Vector3(1.0f, 1.0f, 1.0f));

            CrowdAgent* agent = node_->GetComponent<CrowdAgent>();
            if (!agent)
            {
                agent = node_->CreateComponent<CrowdAgent>();
                agent->SetHeight(2.0f);
                agent->SetMaxSpeed(40.0f);
                agent->SetMaxAccel(10000.0f);
                agent->SetNavigationQuality(NAVIGATIONQUALITY_LOW);
            }
            GetScene()->GetComponent<CrowdManager>()->SetCrowdTarget(pathPos, node_);
        }
```

**Comment by 1vanK** [comment]
Opened new issue https://github.com/urho3d/Urho3D/issues/1571
