### ISSUE TITLE
Agent still move with constant speed after TargetReset

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1572]
Way to reproduce:

```
Node@ jackNode;

void SpawnJack(const Vector3& pos, Node@ jackGroup)
{
    jackNode = jackGroup.CreateChild("Jack");
    ...
}

void HandleUpdate(StringHash eventType, VariantMap& eventData)
{
    ....
     if (input.keyPress[KEY_L])
    {
            CrowdAgent@ agent = jackNode.GetComponent("CrowdAgent");
            agent.ResetTarget();
    }
}
```

Click to set target, then press L

**Comment by cadaver** [comment]
ResetTarget() seems a direct call to DetourCrowd's function, and it doesn't state in the CrowdAgent header that resetting the target would make the agent stop, so apparently it is the proper behavior that it will continue in its existing direction. If you want it to stop you can set the target velocity to a zero vector.

**Comment by 1vanK** [comment]
It is my mistake, sorry. 

I noticed a strange debug geometry after ```agent->SetTargetVelocity(Vector3::ZERO);```

![2](https://cloud.githubusercontent.com/assets/13021826/18412225/fecef9e2-7791-11e6-861b-ee12d52e8f1a.png)

It draw a line to center of scene

**Comment by cadaver** [comment]
Looks to be a minor bug in the debug draw; it should not draw the target in the VELOCITY mode (in which case targetPos means velocity, not position)

**Comment by 1vanK** [comment]
Old condition ```if (crowdAgent->GetTargetState() == CA_TARGET_NONE)```
but 
```
        agent->ResetTarget();
        agent->SetTargetVelocity(Vector3::ZERO);
```
still draw debig line. This means that it is impossible to restore CA_TARGET_NONE state?

**Comment by cadaver** [comment]
DetourCrowd defines the "target velocity set" as a separate state with different behavior. You can get back CA_TARGET_NONE by first setting target velocity zero, and calling ResetTarget() last, but it most likely isn't what you want, as it means the agent will keep walking to current direction instead of stopping.

**Comment by 1vanK** [comment]
I understood, thanks
