### ISSUE TITLE
Is SplinePath Serialization in Editor are broken for now?

### ISSUE THREAD

**Issue by MonkeyFirst** [urho3d/Urho3D#1576]
Hi there! Recently I update my local master with new from Github, and now I have broken spline path in my test scene with stairs.

I think that now editor do not serialize spline points properly (?)  
Or maybe it's because now I use vs2015 instead vs2013 ? (previously the tested scene was compiled with vs2013)

video with this bug:  https://youtu.be/NJxnoKxL4aA

**Comment by cadaver** [comment]
Reproduced the bug; the node ID vector was returning zeroes at the ID resolve phase. The commit should fix it, but I'm not exactly satisfied, since the code (which originally used a reference instead of value copy) used to work for 3 years. Needs more investigation.

**Comment by MonkeyFirst** [comment]
Thanks, now Editor show SplinePath properly after scene loading.

**Comment by 1vanK** [comment]
C ++ breaks my brain :(

What different between
```
const VariantVector& oldNodeIDs = component->GetAttribute(j).GetVariantVector();
```
and
```
Variant attrValue = component->GetAttribute(j);
const VariantVector& oldNodeIDs = attrValue.GetVariantVector();
```

**Comment by cadaver** [comment]
GetAttribute() returns a value copy of the attribute Variant.
Taking a reference to the vector inside the Variant, while it's only being held in a temporary variable seemed to bug, resulting to the vector content being all zeroes. The code as it's now is more explicit and shouldn't be any worse in performance, if the compiler optimizes away the return value copying.

**Comment by 1vanK** [comment]
Thanks for the explanation
