### ISSUE TITLE
Alpha To Coverage Support

### ISSUE THREAD

**Issue by OldSnake22** [urho3d/Urho3D#1578]
This is a feature request, it would be great to add alpha to coverage support for improving vegetation rendering quality for example.

**Comment by OldSnake22** [comment]
Amazing ! Is it working with deferred render path ? I heard that alpha to coverage require MSAA support ?

**Comment by cadaver** [comment]
It doesn't work with deferred, as deferred forces the buffer to be non-multisampled.

**Comment by OldSnake22** [comment]
So there is no way to make it work until we get multisample buffers support in deffered rendering ?

**Comment by cadaver** [comment]
I don't think so, since the color & depth multisample must match, and for G-buffer rendering you  need non-multisampled. Trying to switch midway through the scene render doesn't work, since you still need a properly filled depth buffer.

**Comment by cadaver** [comment]
Note that you could (sort of) emulate alpha to coverage by making a custom stipple in your shader, that would read the fragment screen coordinates and do discard according to a pattern. This would work without hardware multisampling.
