### ISSUE TITLE
Android: we can't create GPU resources if Activity is running in background.

### ISSUE THREAD

**Issue by guijun** [urho3d/Urho3D#1580]
I'm using Urho3d 1.5.

**Comment by cadaver** [comment]
This is as intended, as the GPU context may be lost at that time.

**Comment by guijun** [comment]
well, is there any workaround available?

**Comment by cadaver** [comment]
Main loop getting paused when minimized should be the default on mobiles, see the constructor of the Engine class, and that's the setting which I'd recommend. If you really need to run in background you could check Graphics::IsDeviceLost() and avoid resource operations when it's returning true.

**Comment by guijun** [comment]
I noticed that main loop did't get paused when activity lost focused.

**Comment by cadaver** [comment]
A slight clarification: the main loop doesn't actually pause, but the per-frame update events are skipped, and render should be skipped too due to Graphics::IsDeviceLost() being true. But I'll verify this behavior later.

**Comment by OvermindDL1** [comment]
Is this the case when the android program is in split-screen mode as well?  In split-screen mode a program is 'backgrounded' but it has an active device, programs should keep running in this state or it will look frozen.

**Comment by cadaver** [comment]
Don't have recent enough device to test myself, but SDL's window minimize is tied to the "pause" activity event, so I presume it will freeze. Changing this would likely need SDL changes, and the ability to differentiate between the split-screen pause, and being put to the background for real.

**Comment by OvermindDL1** [comment]
It is in the new Android 7.0 Nougat if you want to test in an emulator, I'm at work currently.  Things like Slack break in it though, Slack freezes so you have to re-tap it to re-render it on occasion, but I don't expect much from Slack honestly...  >.>
Most things I've tried run well in split-screen though.  :-)

**Comment by cadaver** [comment]
Verified that Update per-frame events will cease when the app is minimized / backgrounded. So by ensuring that you only attempt to create or manipulate GPU resources from within these (or check Graphics device loss manually) should be safe.
