### ISSUE TITLE
Xcode 8.0 has issues with Civetweb::clock_gettime(....)

### ISSUE THREAD

**Issue by JohnHouston** [urho3d/Urho3D#1588]
Building with -DURHO3D_NETWORK=0 will work of course.  I am new to using this framework, so I apologize if I am reporting in the wrong area.  I will add more details as I familiarize myself with the build process.  I am building on the command line, and I also notice that I do not have the
CMAKE_OSX_DEPLOYMENT_TARGET=10.12, it's still 10.11.  I am using cmake 3.6.2( installed with homebrew ).

"./cmake_${BUILD_TYPE}.sh "../Project/${GFXLIB_DIR}" -DURHO3D_NETWORK=0" is the cli I use to built the out of tree build of Urho3D, the variables are filled in with a bash script.

**Comment by cadaver** [comment]
Is it the same issue as this in Civetweb repo? In that case the fix could be merged.
https://github.com/civetweb/civetweb/issues/349
https://github.com/civetweb/civetweb/pull/356

**Comment by JohnHouston** [comment]
Are your third party libraries your own forks?  For instance, I should merge from your source or just pull in the required new civetweb files ( seems to be 2 minor versions off ).  When I manually just dropped the .h and .c file in as a replace, I still ran into the same issue with CMAKE to export MACOSX_DEPLOYMENT_TARGET=10.11, rather than 10.12, and the project is generated with --mmacosx-version-min=10.11.  Once again, rather new to the a large cmake project, but I don't mind trying any thing out as long as I think I am heading in the correct direction.

Currently I am just building a stub project with a script so I can select the output format( android, emscripten, ios, eclipse, xcode ).

Is this a case from the docs which shows caution with Cmake versions and XCODE.

Thanks for your time and help!

--John

**Comment by cadaver** [comment]
Civetweb is slightly modified for some compile incompatibilities, so yes to test the change in that PR you should just merge the affected part.

**Comment by weitjong** [comment]
You can control the deployment target by specifying the ```CMAKE_OSX_DEPLOYMENT_TARGET``` build option. When not specified that the build system will target the same OS version that the host system is currently running. Or, at least that is what the build script intends to achieve.

Slightly off-topic. Have you looked at the ```Rakefile``` in the root of Urho project? It has ```rake cmake``` and ```rake make``` tasks which functions similarly to what your script does, if I understand it correctly. Try this at the project root:
```
rake cmake xcode && rake make
```
The tasks accept other parameters for specifying build options and other things too. Refer to this [doc]( https://urho3d.github.io/documentation/HEAD/_using_library.html#Scaffolding) for more detail.

**Comment by JoshEngebretson** [comment]
I had this issue yesterday, it seems that the define in time.h isn't guarded, have it building with XCode 7 and 8 with both SDK's with this: 

```c
/* Determine if the current OSX version supports clock_gettime */
#ifdef __APPLE__
#include <AvailabilityMacros.h>
#ifndef MAC_OS_X_VERSION_10_12
#define MAC_OS_X_VERSION_10_12 101200
#endif
#endif

// Instead of using MAC_OS_X_VERSION_MIN_REQUIRED, which it doesn't appear time.h is guarded by, use MAC_OS_X_VERSION_MAX_ALLOWED
#define CIVETWEB_APPLE_HAVE_CLOCK_GETTIME defined(__APPLE__) && MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_12
#if !(CIVETWEB_APPLE_HAVE_CLOCK_GETTIME)
```

I would have preferred to use MAC_OS_X_VERSION_MIN_REQUIRED and maybe that is possible

**Comment by cadaver** [comment]
Thanks Josh, I'll push this change and we can see how it goes. I don't have XCode 8 yet.

**Comment by weitjong** [comment]
Travis CI jobs for macOS platform is now using Xcode 8.

**Comment by weitjong** [comment]
It looks like I spoke too fast :smiley: 
Travis CI showed that there is now a regression issue with the 43_HttpRequestDemo. I am resetting back the master branch to revert back to use Xcode 7.3 again. However, those that use Xcode 8 to compile master will surely hit by this regression.

**Comment by JoshEngebretson** [comment]
Darn, what is the regression?  Civetweb has a fix applied, though this one didn't work for me, going to have to look closer:

https://github.com/civetweb/civetweb/blob/master/src/civetweb.c#L140

**Comment by weitjong** [comment]
Don't have Xcode 8 installed locally yet also so I cannot try to reproduce and investigate. The job log from Travis CI just said the test run of 43_HttpRequestDemo has thrown an "exception".

**Comment by JoshEngebretson** [comment]
I would venture a missing clock_gettime, I couldn't get a successful compile and link that worked on both XCode 7 and 8 with -mmacosx-version-min=10.9 using a MAC_OS_X_VERSION_MIN_REQUIRED  guard.  Came up with this workaround pretty fast, now if it just was a working workaround :)  Kudos on the regression tests btw, good work!

**Comment by cadaver** [comment]
It's a late linking error which causes the app to exit when attempted to be used.
I'm now testing setting a define (_DARWIN_FEATURE_CLOCK_GETTIME 0) which allows the own version to be used regardless.

**Comment by JohnHouston** [comment]
Guys, I have  some time to dedicate to this.  I am first going to try to run the ruby  _rake_ util, and will head from there, but if there is some help I can do with a hardware setup that you guys are missing please let me know and I can assist.  My hours are rather odd at the moment since I am not working a 9-5.

**Comment by cadaver** [comment]
Pushed the change I mentioned. Tested OSX build on both XCode 7 & 8, though I couldn't get CMake to go through successfully for iOS on XCode 8, so that's untested.

**Comment by JoshEngebretson** [comment]
Curious if you also had a go with the update from here? https://github.com/civetweb/civetweb/blob/master/src/civetweb.c#L140

I did yesterday, it uses ```MAC_OS_X_VERSION_MIN_REQUIRED```, though it didn't work here. I could try again soon, ```_DARWIN_FEATURE_CLOCK_GETTIME```  seems like a good workaround.

**Comment by weitjong** [comment]
> Pushed the change I mentioned. Tested OSX build on both XCode 7 & 8, though I couldn't get CMake to go through successfully for iOS on XCode 8, so that's untested.

Tested the CI build with Xcode8 in a new branch. No more regression issue found. However, I found something else and unrelated to this issue which prevents me to push the change to master branch right now. I suspect it has something to do with the newer ccache 3.3. and I think I have seen the same problem manifested locally in my Android build tree with Clang compiler after Fedora 24 upgraded my ccache version, but I have no time to fix the problem yet.

**Comment by cadaver** [comment]
@JoshEngebretson I didn't try the official fix. The idea behind it looks more robust though more complex, so it can be taken if the current fix fails in some case.

**Comment by JoshEngebretson** [comment]
It looks like they have a 2nd attempt at a fix, so I wasn't crazy :)

https://github.com/civetweb/civetweb/commit/a542401946f00cdada5c61c32eeb67034eaef15a

I am trying this now

**Comment by cadaver** [comment]
@JohnHouston Have you tested the current Urho master branch? Can this be closed now?

**Comment by JohnHouston** [comment]
Folks, sorry for the delay, thanks for the all of the work you do. 
Tested with XCode 8.0 on commit: 108976345785903a92bfc3e0238282bdd5c463a2 and the build succeeded.

Once again thanks you very for your time and effort.

--John
