### ISSUE TITLE
UnknownComponent may lead to memory corruption

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1589]
I've found some bad sequence:
1. I added new component and I used it somewhere in code through GetComponents<>.
2. _I didn't registered it._ Just forgot to.
3. I've manually added it to scene. Just because it was easier.
4. Then my code crashed because UnknownComponent was succesfully casted to MyComponent.

This sequence is obviously erroneous, so crash was okay. But what about other possible sequences?

Type hacking under the hood of UnknownComponent looks dangerous because it can lead to corrupted pointers. UC is the only Object that cannot be safely casted without dynamic_cast.
This type hacking also don't allow to easily fix #1515

Is this type hacking needed only for displaying propper names in Editor?
If so, let's think about better solution like GetComponentName/GetDisplayName virtual functions.

**Comment by cadaver** [comment]
It's not only for displaying, the main thing to ensure is that it gets serialized right (as the type it's impersonating) to scene files. But I agree that hacking the type itself is errorprone.

**Comment by eugeneko** [comment]
Are you going to work on this issue in near future?
If no, I'll try to remove type hacking by myself.

**Comment by cadaver** [comment]
Eventually yes I believe, but you may get to it faster so feel free to work on it.
