### ISSUE TITLE
Frame skipping when CPU is overload

### ISSUE THREAD

**Issue by keithyipkw** [urho3d/Urho3D#1592]
In 27_Urho2DPhytics, I increased the number of objects and reduced their spacing to increase the CPU usage. The debug profile showed FPS > 30. Xcode and a timer in Urho2DPhysics::HandleUpdate showed the same FPS. However, the FPS of most objects was only 1 visually. They teleported about their size every second. The objects colliding the bottom platform moved (teleport) individually with about few Hz. Was it an expected behavior under CPU stress?

Urho3D 1.32
Debug and release
27_Urho2DPhytics
OS X and iOS
With or without vsync and triple buffer

**Comment by cadaver** [comment]
I tested the same on PC by setting 100000 objects. I could observe the engine rendering at 7 fps but most objects updated at 1 fps or less, and collisions were resolved slowly. This looks to be the default behavior of Box2D. I'm not the original author of the 2D physics integration, and it seems that PhysicsWorld2D doesn't expose throttling parameters or set them to Box2D side, but you could look what kind of API the Box2D b2World class (which PhysicsWorld2D owns) offers for configuring the behavior, if any. Then, if you find some useful settings, you could make a PR which exposes them to PhysicsWorld2D, if you wish.

However, in general there are only poor solutions when physics starts to take too much time: slowing down simulation time, "spiraling" the whole app to framerate death, or increasing the time step which makes the simulation more inaccurate.

**Comment by keithyipkw** [comment]
The author set substepping to true. It was a debug function for continuous physics, to prevent tunneling. It should be false in default.

**Comment by cadaver** [comment]
Thanks for the investigation, this looks like it should be configurable.

**Comment by cadaver** [comment]
After testing more, substepping is indeed immature and I agree it should be disabled by default. It allows the simulation to run faster, however it quickly starts skipping movement and not resolving collisions fully, when the load grows.

**Comment by keithyipkw** [comment]
In Box2D, the default value of substepping is false. The function is marked as "for testing". The function means to use manual substepping. Substepping algorithm is in the default continuous physics solver. In PhysicsWorld2D, the author explicitly set it to true. Setting it to true breaks down a step into individual step for fixing each tunnel effects. For example, if substepping is set to true and there are 10 objects passing through a wall, Box2D will need 11 (my guess, certainly not 1) steps for the whole world to finish 1 step. The 11 steps are placed in 11 Urho3D engine step events. It is certainly not general users want.

**Comment by keithyipkw** [comment]
Continuous physics should remain true. It should be what general users want.
