### ISSUE TITLE
Water surface shook when moving the camera on iOS

### ISSUE THREAD

**Issue by keithyipkw** [urho3d/Urho3D#1593]
Running the 23_Water on iOS, when moving the camera, the water surface shook. It happened both using the joystick and other part of the touchscreen. It did not happen on OS X. Was it an iOS bug?

Urho3D 1.32
iOS 9.3

**Comment by cadaver** [comment]
Can test this later, but I would strongly suspect it's the lesser precision in fragment shaders on GLES compared to desktop. There's also another reason why the water example will not run perfect on GLES: missing clip plane support.

In general you can assume the graphical examples to have been developed for desktop first and they are not rigorously tested on mobiles.

**Comment by keithyipkw** [comment]
The fix works at least on iPhone 5s iOS 9.3.
