### ISSUE TITLE
Single pane with one scrollbar for node and all components in Editor

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1594]
Sometimes I have a lot of components per node.
E.g. now I have five ones. And in default mode on my 1366x768 it looks like piece of.. something. Very, very small piece of something.
![image](https://cloud.githubusercontent.com/assets/8576192/18596214/be2ff102-7c50-11e6-8ca0-3cdcaf3c82a2.png)

It would be much better to have editor like in Atomic Engine or Unity with collapsing subpanes on the single editor pane.

**Comment by cadaver** [comment]
Certainly agree it would be better. The question is who has the fortitude to modify the inspector and its UI layout :)
