### ISSUE TITLE
Demos skip frame when keys are pressed (Windows 10)

### ISSUE THREAD

**Issue by WestRice** [urho3d/Urho3D#1596]
I built Urho3D 1.6 in Visual Studio 2015 with URHO3D_D3D11 and URHO3D_WIN32_CONSOLE on.
Then I ran these demos on my notebook(GPU: HD Graphics 4600 and GTX 860M with Nvidia Optimus on).
Demos ran pretty smoothly when no keys are pressed.But if I pressed any key (no matter what it is), demos skipped frame.After releasing the key, demos ran smoothly again.
Especially in AnimatingScene demo, it completely stopped when any key was pressed and became smooth when the key was released. Other demos has the same problem but less severe.
I tried to switch the high performance graphics card for these demos. But it didn't work. Neither did building Urho3D with default options.

PS:I tried these demos online([https://urho3d.github.io/web-samples.html](url)) and these didn't have the problem.

**Comment by cadaver** [comment]
I'm unable to reproduce this on my system which is also a Windows 10 laptop with dual GPUs. Looks to be something specific to your system. You could bring up the profiler (F2 key) to see which function is taking extra time when the engine slows down; my suspicion would be the input handling, if a mass window events is generated for some reason.

**Comment by WestRice** [comment]
It is my IME that does evil.
When IME on, pressing any key for a second will produce a massive amount of input events. Since my default IME setting is on, the problem appears on my machine.It is my fault not to notice that.
Thanks for your patience.

**Comment by cadaver** [comment]
If you have ideas how to mitigate this (bearing in mind that input events are handled by the SDL library and not by Urho3D directly) they're welcome.
