### ISSUE TITLE
AssetImporter generates animation with wrong offsets

### ISSUE THREAD

**Issue by yushli** [urho3d/Urho3D#1603]
Please see the left jet of the plane.

![offset](https://cloud.githubusercontent.com/assets/1681453/18625606/3f490b6a-7e82-11e6-9c65-3856c0700312.jpg)

Which can be played correctly in Max:
![offsetcorrect](https://cloud.githubusercontent.com/assets/1681453/18625620/58bf313c-7e82-11e6-92f6-b4d8ba6cbbfe.png)

The animaion fbx

[plane_standby.zip](https://github.com/urho3d/Urho3D/files/479479/plane_standby.zip)

The model and other animations fbx
https://github.com/urho3d/Urho3D/files/478661/anim.zip

**Comment by Lumak** [comment]
![standby](https://cloud.githubusercontent.com/assets/14249868/18643566/93c84df4-7e5a-11e6-903f-151b80010982.gif)

**Comment by Lumak** [comment]
The gif is not really pertinent. It's my first attempt at converting video to gif :dancers:

**Comment by yushli** [comment]
Can you share the generated .mdl and .ani files? I synced the latest master branch, rebuild and regenerate the mdl and ani, but the offset problem is still there.

**Comment by Lumak** [comment]
No, I can't share it. It's how we got to this point to begin with.  

You had the same problem with the 'fly' and 'attack' animations yesterday and asked me to generate them because you couldn't.

I fear that if you can't build the source, I will forever be generating your fbx files.

Good  luck learning how to build the source.

**Comment by yushli** [comment]
Got it. I have some old .ani files in different folders thus shadowed the new one. You code actually fixed this issue. Thank you!

**Comment by Lumak** [comment]
I'm going to provide the tool in case you weren't able to build it. It's a debug build, as I'm debugging some other things and don't really want to build a release version of my entire solution.
[AssetImporter.zip](https://github.com/urho3d/Urho3D/files/483174/AssetImporter.zip)
