### ISSUE TITLE
Can SetModel and SetMaterial be virtual?

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1605]
Subject.
I've found that it could be useful for writing my own Drawable's.
If I confirm this, can I make'em virtual?
It shouldn't affect performance because Urho already has tons of virtual calls.

**Comment by cadaver** [comment]
You mean in the StaticModel class? Yes, if you find that useful you can make a PR. Note however that the signature is different in StaticModel and AnimatedModel; in AnimatedModel there's an extra bool parameter.
