### ISSUE TITLE
Per-instance material parameters

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1606]
Idea is simple: I suggest to allow setting up material parameters from object instance, because current system forces user to have different material for each _instance_ of prefab if he wants to set different material settings.

It could be some extra optional parameter in batch structures that is used as source of uniforms. I'ven't investigated this deeply, but it doesn't look super-complicated.
Such parameters could be passed into batches from some new attribute in drawables.

**Comment by cadaver** [comment]
This was written by @primitivewaste long ago, but AFAIK it was not finished.
I too can easily see how it would work and it would not be very complicated, but in practice it can have a slight negative impact on the rendering loop performance, since in the very least it has to check for each object: does it have instance parameters. It can also require more data for the batch sorting keys. 

Right now it's clear that you have to clone the material to have different settings, and this already should make it obvious that you break instancing. With per-drawable parameters, it would be less obvious.

**Comment by eugeneko** [comment]
Ok, this makes sence. However, maybe there are something that can be done to make cloning process more convinient?..

My use case is wind system. In most cases global wind is enough, this brings no problem. However, I want to support local wind zones like in Unity. So I need the ability to switch from original material to cloned one when I need per-object settings.

**Comment by cadaver** [comment]
The batch grouping / instancing already splits drawables based on which Zone they belong to, so allowing a Zone to have custom parameters could be better aligned.

**Comment by 1vanK** [comment]
I tested scene wherein all materials are cloned https://github.com/1vanK/Urho3DOutlineSelectionExample
Release version has no problems with fps falling (but debug version sorts batches longer than for scene without cloned materials).

**Comment by eugeneko** [comment]
@cadaver Per-Zone parameters won't help becuase some types of wind zones may have different values in different positions.

I can just replace StaticModel's materials with the cloned ones with the same names, however I won't be able to differ cloned material from original.

**Comment by cadaver** [comment]
You could also virtualize GetMaterial() so that the original is returned, while you manage the cloned materials at some central object and use the cloned materials in the batches.

**Comment by OldSnake22** [comment]
Would be nice to find a system that is easier than current material cloning method yeah :)

**Comment by eugeneko** [comment]
Huh, virtualizing could solve my problem... I'll take a look.

**Comment by OldSnake22** [comment]
@eugeneko Please make a pull request if you end up with something that could be usefull for us and thank you for your regular contributions so far.

**Comment by eugeneko** [comment]
@OldSnake22 Although I'ven't done anything explicitly related to this issue, since my PR #1612 it is possible to implement some complex logic over StaticModel. E.g. I've implemented component over StaticModel that have flag 'Clone Materials'. I'll share my code at some point, but not now.
