### ISSUE TITLE
GLSL compilation issue on NVIDIA Shield

### ISSUE THREAD

**Issue by JoshEngebretson** [urho3d/Urho3D#1607]
On an NVIDIA Shield, I am receiving this GLSL compilation error:

```
[Urho3D] Failed to compile pixel shader LitSolid(AMBIENT DIFFMAP DIRLIGHT PERPIXEL SHADOW SIMPLE_SHADOW SPECULAR):
[Urho3D] (1123) : error C1115: unable to find compatible overloaded function "GetShadow(vec4[1], mediump float)"
[Urho3D] Compiled vertex shader LitSolid(DIRLIGHT NORMALMAP PERPIXEL SHADOW SKINNED)
[Urho3D] Failed to compile pixel shader LitSolid(AMBIENT DIFFMAP DIRLIGHT NORMALMAP PERPIXEL SHADOW SIMPLE_SHADOW SPECULAR):
[Urho3D] (1124) : error C1115: unable to find compatible overloaded function "GetShadow(vec4[1], mediump float)"
```

Changing to ```highp``` here, does fix the error and render properly on device: https://github.com/urho3d/Urho3D/blob/master/bin/CoreData/Shaders/GLSL/Uniforms.glsl#L52

I also tested on an iPad4, and that worked without any changes or errors, any thoughts?  I did try specifying mediump/highp on the GetShadow function declaration, to no avail

**Comment by cadaver** [comment]
The mediump default precision is from times I tested on ancient devices like Samsung Galaxy 2 or iPad 2 which would fail when highp would be default specified. 

However in practice we need to be able to specify highp anyway case-by-case to get e.g. properly working shadows and UV calculations performed in fragment shaders. So the difference is that do we, on ancient devices, fail for all rendering, or only when shadows are attempted to be used :)

The call should in theory be fixable without specifying highp globally, but can also be a shader compiler bug, so it can be tricky in practice. I've not seen this compile error manifest on iOS / Android devices I've tested on.

**Comment by cadaver** [comment]
Ah, one way to fix without failing all rendering on non-compatible devices would be to look for ifdef SHADOW and set precision highp in that case default, and remove the manual highp definitions from elsewhere.

**Comment by cadaver** [comment]
Tested this a bit. Even iPad2 with newest iOS seemed to tolerate highp OK. However using highp globally for fragment shaders results in reduced performance (on poor hardware), so I'd rather not make the change globally, or even when shadows are on, because there are parts of fragment shaders that don't need to be highp. Can you test if renaming the offending GetShadow function makes a difference?

**Comment by cadaver** [comment]
Went ahead and did the change I was thinking of. May or may not help. @JoshEngebretson Can you test whether this has any difference?

**Comment by JoshEngebretson** [comment]
That works great, THANKS! 👍
