### ISSUE TITLE
Cast from U to int in EnumAttributeAccessorImpl::Get

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1608]
EnumAttributeAccessorImpl::Set picks int from Variant and casts it to actual enum type.
If EnumAttributeAccessorImpl::Get would do the same, can it have some unexpected side effects?
I sure no, but I want to confirm.

I want to make this change to allow EnumAttributeAccessorImpl support enum classes that are not implicitly convertible to integer types.

**Comment by cadaver** [comment]
I don't think there should be any more side-effects in an explicit cast.
