### ISSUE TITLE
Strange buffer display problem

### ISSUE THREAD

**Issue by mayatforest** [urho3d/Urho3D#1609]
Hi
We have some software on devices with MALI400 graphics (Xamarin+urho).
Sometimes it seems cycle buffer images.
For testing we display onupdate counter in each OnUpdate 
See this gif with bug
It captured from break in onupdate.
Frames go this way, and cycles forever
8723 
8727 
8679 
8725 
8723 
8727 
8679 
![bug](http://savepic.ru/11467384.gif)

Another example this video
https://drive.google.com/file/d/0B-Z4fIDUXiXmclFzd1ZRS0dHYjg/view

**Comment by cadaver** [comment]
Realistically there is a very slim chance of this being solved, if any of the developers don't have the same hardware in question, and the whole code. Does the same happen when running Urho examples?

**Comment by mayatforest** [comment]
Well, samples work fine, may be some texture artifacts but no this bug. Well ok, i try strip our application to simple possible example to repeat problem.

**Comment by mayatforest** [comment]
I reproduced problem with small example, touch on screen to create triangles and move camera, after 10-20secs bug appear on real hardware

code of scene
http://pastebin.com/9wEXh2kn

full sources
https://drive.google.com/open?id=0B-Z4fIDUXiXmSnE1WEpScGJOUE0

video with bug
https://drive.google.com/open?id=0B-Z4fIDUXiXmNWV6QUpEZGVIVlE

**Comment by cadaver** [comment]
Thanks for the code, however since it's C#, it's not directly testable on vanilla Urho, and could be argued is outside the scope of this project's issue tracker. Can you pinpoint the actual Urho feature that is causing the bug, or replicate it with the languages supported by Urho (C++, AngelScript, Lua)?

**Comment by mayatforest** [comment]
Possible is the same problem as here
http://stackoverflow.com/questions/34866240/repeated-frames-on-android-mali-400

**Comment by mayatforest** [comment]
Well, ok, i try to replicate code to lua or something, but i think is not related to c# specific

**Comment by cadaver** [comment]
My guess is that something in the rendering causes the device / graphics driver to reach an illegal state, so try to isolate it to minimal rendering. It could be something like an illegal draw range (bug in CustomGeometry)

**Comment by mayatforest** [comment]
Well ok, i found solution, if we use (as in example) 2 or more triangles in one geometry - got flickering sometimes after 5-10 geometries.
If we use 50000 geometries with one triangle - got no problem. Its very strange, i dont understand why with 20 triangles by first method we recieve opengl outofmemory, and no error with 50000 triangles.

Btw thanks for help and attention. May be this issue help somebody on this hardware.
