### ISSUE TITLE
Shader cache location

### ISSUE THREAD

**Issue by t-artikov** [urho3d/Urho3D#1610]
Shader cache is written to a fixed location('<Application Directory>/Data/Shaders/HLSL/Cache') now.
When an application is installed to the Program Files this location is not writable and the cache is not working.
I propose to add the ability to specify the shader cache location.

**Comment by OldSnake22** [comment]
Maybe we could put it in application appdata folder ?

**Comment by cadaver** [comment]
It certainly can be made configurable. However before you "ship" an application you should step through all the possible scenes and settings until no more shaders are being generated to the cache, so if properly used the writability shouldn't be an issue. Putting it to appdata means it would be empty by default, unless the program installer has an extra step to copy the cache from the installation data.

**Comment by OldSnake22** [comment]
@cadaver Can you explain the utility of the shader cache ? How it improve performances ?

**Comment by cadaver** [comment]
If a cached binary is found for a shader variation, D3D9 / D3D11 doesn't have to compile it at runtime. It can be a significant loading speed boost since compiling a single shader variation could take anywhere from 0.1 to 1 seconds.

OpenGL doesn't offer a GPU-independent binary format similarly, so there shaders are always compiled when encountered, but in general it's slightly faster (maybe worse optimized?)

**Comment by OldSnake22** [comment]
Thank you

**Comment by t-artikov** [comment]
In my case it is hardly possible to create all shader variations in advance, user can create his own scenes.
Writing the shader cache to the ApplicationData will be fine for me.

**Comment by cadaver** [comment]
After a bit of thinking, it could indeed make sense to put into appdata by default, and instruct authors of games in the documentation that they can "bake" the cache and set its location, but this way the engine itself would not attempt writing into its resource folders by default.

**Comment by eugeneko** [comment]
@cadaver What do you think about generel writable resource folder?
It could be customly mapped onto bin/Cache or AppData/ProjectName/Cache
and have the same structure as Data.

**Comment by cadaver** [comment]
You could setup that in your application if you want, but in general the fewer resource dirs by default, the less there's potential for confusion or getting files from wrong places, so I wouldn't make it an engine default.
