### ISSUE TITLE
Sample crash when changing MaterialQuality engine parameter.

### ISSUE THREAD

**Issue by iSLC** [urho3d/Urho3D#1611]
I've added A method to the `StaticScene` example to change some of the parameters before startup.

```
void StaticScene::Setup()
{
    Sample::Setup();
	engineParameters_["MaterialQuality"]  = 2;
}
```

That works fine, however, if I set the value to something higher than 2, say 3 for example and run the example. When I press the F2 key to draw information about rendering/engine etc. The example crashes.

I know that a value 3 is not supported (_according to documentation_). However, the timing of the crash (_when you bring the rendering information_) seemed weird. Reason I'm reporting it. I'm not very familiar with the internal engine code so I can't attempt to debug this my self. And I'm neither very experienced at that.

Build: MinGW GCC 5.4.0 x32, C++11, Release, Shared Library, OpenGL Graphics.

**Comment by cadaver** [comment]
The material quality was originally made with the intention that there's not necessarily only 3 levels but the user could define more. However in practice this leads into an indexing overflow in the DebugHUD, as it only knows 3 levels. Should be easy to fix.
