### ISSUE TITLE
Alpha to coverage is breaking whole alpha blending

### ISSUE THREAD

**Issue by OldSnake22** [urho3d/Urho3D#1615]
Alpha to coverage is breaking the whole alpha blending process. See by yourself.

Tested on desktop, DX11 and deferred renderpath. (alphatocoverage is not enabled anywhere in material or pass as it is useless with deferred rendering).

This is the bug: 

http://imgur.com/dnZuMwW

And when i change the line 2454 in D3D11Graphics.cpp to stateDesc.AlphaToCoverageEnable = false;

the problem is solved as you can see: 

http://imgur.com/Pj8IjWd

**Comment by OldSnake22** [comment]
Please note that it was quite difficult for me to find the source of the issue since it is very random and sometime everything was fine and sometimes not.

**Comment by cadaver** [comment]
So are you saying that materials / passes have alpha to coverage enabled (and thus is passed to stateDesc) although you didn't intentionally enable it?

**Comment by cadaver** [comment]
Btw. thanks for bringing this to attention, it could have gone unnoticed for long otherwise.

**Comment by OldSnake22** [comment]
No problem ! Thank to you for fixing bugs so fast ! 

But yeah that was a nasty bug since i was using the version with alpha to coverage since a few days and the bug started to appear only today !
