### ISSUE TITLE
Decal rendering issue

### ISSUE THREAD

**Issue by OldSnake22** [urho3d/Urho3D#1618]
Hello i try to use this technique 

```
<technique vs="PBRLitSolid" ps="PBRLitSolid" vsdefines="IBL" psdefines="DIFFMAP PBR IBL">
    <pass name="alpha" depthwrite="false" blend="alpha" />
    <pass name="litalpha" depthwrite="false" blend="addalpha" />
</technique>
```

on a decal and here is the results: 

http://imgur.com/GxeVGX2

As you can see, it is wrongly lit by the point light. Do you know what is the source of this problem ? missing tangent informations ? (DX11, desktop, deferred rendering)

I can use the same technique on a normal mesh without any issue.

Thanks !

**Comment by cadaver** [comment]
What is the exact issue? Do you mean wrong lighting direction due to normal mapping? The image doesn't say much to me.

**Comment by OldSnake22** [comment]
Only half of the decal is lit correctly by the point light and the technique do not use normal map.

**Comment by OldSnake22** [comment]
I am investigating more and i will give you some infos soon.

**Comment by cadaver** [comment]
If you can give a hint how to reproduce the error with built-in Urho assets, or otherwise provide sufficient assets to reproduce it (can send to loorni@gmail.com if you're concerned with sharing to whole world), it'd be great.

**Comment by OldSnake22** [comment]
look like vertex normals are not generated correctly. If i put:

`oNormal = float3(0.0, 1.0, 0.0); `

in the vertex shader then everything is fine (this is decals applied on terrain patch so i use "up" normal vector)

**Comment by OldSnake22** [comment]
Yeah i forgot to say that i was applying my decals on terrain patches. That might be important to know :)

**Comment by cadaver** [comment]
Thanks, this should be sufficient to investigate.

**Comment by cadaver** [comment]
The key was to have decal in different node than the target geometry, in which case normals could be transformed incorrectly.
