### ISSUE TITLE
setShaderParameter Variant overload doesn't handle double case.

### ISSUE THREAD

**Issue by graph** [urho3d/Urho3D#1621]
In my code I had something like

```
something.shaderParameters_["SomeValue"] = 1.4;
```
which didn't work but changing it to

```
something.shaderParameters_["SomeValue"] = 1.4f;
```
worked (note the f at the end). Upon investigation [SetShaderParameter](https://github.com/urho3d/Urho3D/blob/master/Source/Urho3D/Graphics/OpenGL/OGLGraphics.cpp#L1344) does not have a case for when the parameter is a double so it's ignored. 

I like more to remove float support in the variant class and always use double. This way it's simpler. The choice of how you fix this is yours, I'm just giving my opinion from an API users perspective. 

Thank you & great library 👍

**Comment by cadaver** [comment]
This was recently fixed for Material in the master branch. Is something a Material in your example?

Variant didn't originally have double support, however it was added to allow lossless interchange from e.g. Lua & JSON so it's doubtful to be removed. 

It wouldn't cost much to allow doubles to be converted on the fly in SetShaderParameter, too, in case there are custom applications of shader parameters outside materials.

**Comment by graph** [comment]
I'm setting the shader parameter on a RenderPathCommand object of type CMD_QUAD. Also I'm using an older branch. I traced the calls to SetShaderParameter and checked the master branch if Double was added to that function. Seeing it wasn't I then decided to reported this. I didn't test against the master branch.

**Comment by cadaver** [comment]
Ah, thanks for clarifying.

**Comment by graph** [comment]
I just tried the master branch and it appears bug exists when using RenderPathCommand. I like the idea of having SetShaderParameter supporting all variant types and maybe aborting with error for improper use.
