### ISSUE TITLE
Troubles to reconstruct world position from depth

### ISSUE THREAD

**Issue by OldSnake22** [urho3d/Urho3D#1624]
Hello, i have switched from PBRDeferred to PBRDeferredHWDepth (can you confirm me that this is better in terms of performances ?)

I have made a custom height fog shader that was working well with linear depth but since i have switched to hardware depth i have some troubles and the height fog is **working only under certain camera angles**.
I have already adapted the shader to use the "ReconstructDepth" function.

This method for reconstructing the world pos was working well with linear depth: const float3 worldPos = iFarRay * depth; 

Or maybe it is a problem with screenpos ? 

Here is the VS and PS shader. 

Can you help me there ? Thanks

```
void VS(float4 iPos : POSITION,
    out float2 oScreenPos : TEXCOORD0,
	out float3 oFarRay : TEXCOORD1,
    out float4 oPos : OUTPOSITION)
{
    float4x3 modelMatrix = iModelMatrix;
    float3 worldPos = GetWorldPos(modelMatrix);
    oPos = GetClipPos(worldPos);
    oScreenPos = GetScreenPosPreDiv(oPos);
	oFarRay = GetFarRay(oPos);	
}

#ifdef COMPILEPS

void PS(float2 iScreenPos : TEXCOORD0,
	float3 iFarRay : TEXCOORD1,
    out float4 oColor : OUTCOLOR0)
{
	const float fogDist = 16000.0 * cHeightFog_Power;

	const float4 color = Sample2D(DiffMap, iScreenPos);
	
	float depth = Sample2D(DepthBuffer, iScreenPos).r;
	depth = ReconstructDepth(depth);

	const float3 worldPos = iFarRay * depth;

    const float depth2 = 1.0 - clamp(length(worldPos)/fogDist, 0.0, 0.25); // 1.0 
    const float height = (worldPos.y + cHeightFog_CameraElevation)*0.01;

    const float fogFactor =  clamp(exp(-height*depth2+1.0) * (1.0-exp(depth2*2-2)),0.0,1.0);
    const float diffFactor = 1-fogFactor;
	
	const float3 dirRay = normalize(iFarRay);

	const float layer = clamp(exp(((1-dirRay.y)-1) * (0.5 + cHeightFog_CameraElevation*0.001)),0,1);

	//const float3 fogcolor = 1.0 * cHeightFog_Color.rgb * layer;
	const float3 fogcolor = (cHeightFog_Color.rgb * layer) * clamp(abs(-1.0 + depth), 0.8, 1.0);
	
	oColor = color * diffFactor + float4(fogcolor.r, fogcolor.g, fogcolor.b, 0.0) * fogFactor;
}

#endif
```

**Comment by cadaver** [comment]
It should be better performance, since there's one less color buffer involved.
Compare your shader to what PBRDeferred.hlsl is doing with the HWDEPTH define enabled. The depth looks OK on a quick glance. However nowadays you need to do

    worldPos += cCameraPosPS;

to bring the position to true world space.

You could also check that the depth reconstruction uniform is being set to sane values, though it should be, if other camera parameters work. (PSP_DEPTHRECONSTRUCT). 

Also, if you're using a humongous far clip distance, the hwdepth paths haven't really been tested with them, so there could be inaccuracy and linear depth might be better in your case.

**Comment by OldSnake22** [comment]
Just tested with a farclip of 1024 instead of 4096 and by adding worldPos += cCameraPosPS; 

The issue is still here the shader only work at certain camera angles or it does not work a all.

Is it linked to this ? https://urho3d.prophpbb.com/topic2110.html

> One thing to remember is that during fullscreen quad rendering in the renderpath the cViewProj uniform is set to an identity matrix, to avoid possible trouble due to transform inaccuracy, and to also allow rendering quad-only renderpaths without any camera.

**Comment by cadaver** [comment]
That's actually outdated information. Now both a deferred directional light quad and the "quad" command will set viewproj to a proper value, and the quad is drawn to the middle between near & far clip planes to prevent depth clipping.

**Comment by cadaver** [comment]
I'm testing a simple postprocess which reconstructs and outputs the depth as red channel. It works OK with the regular DeferredHWDepth but not with PBRDeferredHWDepth (I'm getting just 0 or 1). Needs investigation.

**Comment by cadaver** [comment]
I don't think there's any engine problems that would prevent this working. Here's a simplified shader that appears to reconstruct worldpos Y correctly, both HWDepth and without.

```
#include "Uniforms.hlsl"
#include "Samplers.hlsl"
#include "Transform.hlsl"
#include "ScreenPos.hlsl"
#include "Lighting.hlsl"

void VS(float4 iPos : POSITION,
    out float2 oScreenPos : TEXCOORD0,
    out float3 oFarRay : TEXCOORD1,
    out float4 oPos : OUTPOSITION)
{
    float4x3 modelMatrix = iModelMatrix;
    float3 worldPos = GetWorldPos(modelMatrix);
    oPos = GetClipPos(worldPos);
    oScreenPos = GetScreenPosPreDiv(oPos);
    oFarRay = GetFarRay(oPos);  
}

#ifdef COMPILEPS

void PS(float2 iScreenPos : TEXCOORD0,
    float3 iFarRay : TEXCOORD1,
    out float4 oColor : OUTCOLOR0)
{
    const float4 color = Sample2D(DiffMap, iScreenPos);

    float depth = Sample2D(DepthBuffer, iScreenPos).r;
    #ifdef HWDEPTH
    depth = ReconstructDepth(depth);
    #endif

    float3 worldPos = iFarRay * depth;
    worldPos += cCameraPosPS;

    float fogFactor = saturate(2 - worldPos.y*0.5);
    float diffFactor = 1 - fogFactor;

    oColor = color * diffFactor + float4(1,1,1,0) * fogFactor;
}

#endif
```

Renderpath invocation (shown for the HWDepth variation)
```
    <command type="quad" vs="HeightFog" ps="HeightFog" depthstencil="depth" psdefines="HWDEPTH" >
        <texture unit="diffuse" name="viewport" />
        <texture unit="depth" name="depth" />
    </command>
```

In general, prefer to avoid using the issue tracker as your debugging service, when there's no direct evidence of an engine problem yet. Imagine if every Urho user did that. Forum may be more appropriate for these cases.

**Comment by OldSnake22** [comment]
Strange i have tested your shader with your renderpath declaration without any changes and i still have the issue (tested DX11 only).

Well i think i will stay with lineardepth

**Comment by cadaver** [comment]
There may be a case where reading the depth texture fails. May or may not be GPU specific. Though in that case I'd suspect the deferred lighting to also go wrong. It can also be related to a more complex renderpath, which causes an interaction which makes the depth reading go wrong, but in that case you'd need to give the whole renderpath you're using.

**Comment by OldSnake22** [comment]
Thank you i will investigate and will reopen this issue if i am 100% sure that there is a bug.
