### ISSUE TITLE
Multisample textures with DX11

### ISSUE THREAD

**Issue by t-artikov** [urho3d/Urho3D#1625]
New multisample textures feature seems not working with DX11.
I change the RenderToTexture example
\- renderTexture->SetSize(1024, 768, Graphics::GetRGBFormat(), TEXTURE_RENDERTARGET);
\+ renderTexture->SetSize(1024, 768, Graphics::GetRGBFormat(), TEXTURE_RENDERTARGET, 8);
As result the renderTexture becomes one-colored.

The same changes work fine with DX9.

**Comment by cadaver** [comment]
It seems to be tied to specific sizes. I get that too at 1024x768, but for example 1024x1024 works.

**Comment by t-artikov** [comment]
Same for me. That's strange. I'm pretty sure there should not be such DX11 limitation.

**Comment by cadaver** [comment]
This looks like an engine bug related to the automatic allocation of depth textures. If I create a depth-stencil texture explicitly and use SetLinkedDepthStencil() it works with 1024x768.
