### ISSUE TITLE
Decalset memory leak

### ISSUE THREAD

**Issue by OldSnake22** [urho3d/Urho3D#1626]
Hello, it seem that decals set have some memory problems.

I have made a terrain decal system so i am creating one decalset per terrain patch (to handle decals at patch border correctly) the system is working fine and the decals are correctly positioned and rendered. 

When i am traveling over the terrain with my free camera i can see the decals and everything is fine but after a few seconds (there is no exact time) the memory start to grow up more and more quite fast. Here is my observations: 

- When the camera do not move the memory consumption is **not** growing up 
- When the camera distance to decalset is above the decalset draw distance and if the camera is moving  the memory consumption is **not** growing up 
- The memory is only growing up when the camera is moving and when the decals are rendered

- It seem that DecalSet::UpdateBuffers() is called regularly, don't know if it is a normal behaviour or not.
- I have tried to set a null drawrange, of course i have 3 frames per seconds but the memory consumption is crazy (like 6Gb instead of 800mb when i use a drawrange of 256.0 on decals sets)

- I have tested to fly with the camera over some StaticModelGroups (my vegetation system) and there no such memory consumption problem. Memory consumption is very stable.

Tested under Windows / DX11.

**Comment by eugeneko** [comment]
Are any leaks reported by MSVC?

**Comment by cadaver** [comment]
Are you adding or removing decals constantly?

**Comment by OldSnake22** [comment]
No i am only adding them once.

**Comment by cadaver** [comment]
UpdateBuffers() shouldn't get called if decals are not being changed. Can you check in debugger if MarkDecalsDirty() is being called, and what causes it to be called? Alternatively, UpdateBuffers() can become necessary if vertex/index buffer data is lost, but that shouldn't be the case on D3D11.

**Comment by cadaver** [comment]
Also, note that the decal vertex buffer / index buffer will be statically allocated according to what is configured with SetMaxVertices() / SetMaxIndices(), and not according to how many decals are in use, so you may end up paying for unused space. You should also be able to use the same decalset for multiple terrain patches, to reduce the amount of unique vertex buffers that are generated.

**Comment by OldSnake22** [comment]
- MarkDecalsDirty() is not called (only called one time so it is normal)
- vertexBuffer_->IsDataLost() || indexBuffer_->IsDataLost() are not called so that is fine

It seem to work as you described but i was very confused how i was able to fly over the terrain with a small memory increase rate for some time and then suddenly memory is growing at a much higher rate. 

Thank you for the precious infos, i will optimize the system by creating less decalsets.
