### ISSUE TITLE
(feature request) Antialiazed wireframes

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1627]
I notoced, that bgfx draws wireframes with enabled anitialiasing BGFX_STATE_LINEAA and it looks nice

In opengl it requires ```glEnable(GL_LINE_SMOOTH);``` and ```graphics->SetBlendMode(BLEND_ALPHA);```
so I pace this line in DebugRenderer::Render() before rendering lines

![2](https://cloud.githubusercontent.com/assets/13021826/19014599/e21a67be-87f9-11e6-8e1e-42795b43a555.png)

(space grid still render without BLEND_ALPHA and looks fat)

**Comment by cadaver** [comment]
Do you know if it has a D3D counterpart? I'm reading some conflicting information on GL_LINE_SMOOTH on the net, apparently it could be unsupported on some vendors, or causing slowdown etc.

**Comment by 1vanK** [comment]
From bgfx code:
dx11: ID3D11RasterizerState.AntialiasedLineEnable
dx9: D3DRS_ANTIALIASEDLINEENABLE

**Comment by cadaver** [comment]
Thanks!

**Comment by 1vanK** [comment]
Nice! Thank you! :)

**Comment by 1vanK** [comment]
I changed DrawGrid in Editor:
```
void CreateGrid()
{
    if (gridNode !is null)
        gridNode.Remove();

    gridNode = Node();
    gridNode.name = "EditorGrid";
    grid = gridNode.CreateComponent("CustomGeometry");
    grid.numGeometries = 1;

    /// Changed
    Material@ gridMat = cache.GetResource("Material", "Materials/VColUnlit.xml");
    gridMat = gridMat.Clone();
    gridMat.lineAntiAlias = true;
    grid.material = gridMat;

    grid.viewMask = 0x80000000; // Editor raycasts use viewmask 0x7fffffff
    grid.occludee = false;

    UpdateGrid();
}
```
and it draw bold lines

![2](https://cloud.githubusercontent.com/assets/13021826/19098169/cfdd7138-8ab3-11e6-9336-a1b23a5506fa.png)

It seems that alpha blending is not enabled

**Comment by 1vanK** [comment]
May be problem is here

https://github.com/urho3d/Urho3D/commit/f8ebf2dbc9a212c0c845545177208f39ad65acb6#diff-ffd7e1f9b69daf21690d8f0ca5b477f8R204

**Comment by 1vanK** [comment]
Or need draw it in alpha pass?
