### ISSUE TITLE
i686-pc-mingw32: Undefined reference to RegisterDeviceNotificationW

### ISSUE THREAD

**Issue by TheComet93** [urho3d/Urho3D#1629]
Problem
-----------
I realise the wiki says to use w64 instead of pc, but I was able to get this one to work regardless and it might be an issue that also occurs when compiling 64 bit (I wasn't able to build a 64 bit compiler so I can't say for sure).

```
../ThirdParty/SDL/libSDL.a(SDL_windowsjoystick.c.obj):SDL_windowsjoystick.c:(.text+0x1c2): undefined reference to `RegisterDeviceNotificationW'
```
Further up, this message occurs:
```
/home/thecomet/documents/programming/cpp/Urho3D/Source/ThirdParty/SDL/src/joystick/windows/SDL_windowsjoystick.c: In function ‘SDL_CreateDeviceNotification’:
/home/thecomet/documents/programming/cpp/Urho3D/Source/ThirdParty/SDL/src/joystick/windows/SDL_windowsjoystick.c:187:5: warning: implicit declaration of function ‘RegisterDeviceNotificationW’ [-Wimplicit-function-declaration]
     data->hNotify = RegisterDeviceNotification(data->messageWindow, &dbh, DEVICE_NOTIFY_WINDOW_HANDLE);
     ^
```

According to this: http://www.mingw.org/category/wiki/how_to
*You need to set defines _WIN32_WINDOWS, _WIN32_WINNT, WINVER and/or _WIN32_IE to the minimum platform you plan to support before including the windows.h header file.*

Solution
-----------
In the file ```Source/ThirdParty/SDL/src/joystick/windows/SDL_windowsjoystick.c``` on line 48:
```
#define WINVER 0x0500      // This fixed the problem
#include "../../core/windows/SDL_windows.h
```

**Comment by cadaver** [comment]
I didn't want to unconditionally overwrite the WINVER define, so I check it first. Please check if that commit fixes the issue.

**Comment by mingwandroid** [comment]
FYI, `w64` vs `pc` does not distinguish between 64-bit and 32-bit, rather the mingw-w64 project and the mingw.org project. The former can build for 32 and 64-bit (and ARM to an extent) while the latter can only target 32-bit.

**Comment by TheComet93** [comment]
Tested and works. Thanks!
