### ISSUE TITLE
64 bit with c++11 option enabled floods output with one warning

### ISSUE THREAD

**Issue by INait** [urho3d/Urho3D#1634]
The warning in question is in line 328 of
Core/Object.h

` EventHandler11Impl(std::function<void(StringHash, VariantMap&)> function, void* userData = 0) :`
`        EventHandler((Object*)0xDEADBEEF /* EventHandler insists for receiver_ not being null but it is ` `captured in
                                          * function_ already and is not used by EventHandler11Impl */, userData),`

(Object*)0xDEADBEEF causes unsigned int to pointer cast, which causes data loss warning in 64 bit config.

**Comment by iSLC** [comment]
Which compiler though?

**Comment by INait** [comment]
Msvs 2015

**Comment by cadaver** [comment]
Yes, I got it on VS2015 too. Should be solvable by moving the assert to the non-C++11 event handler implementation class which actually needs the receiver.
