### ISSUE TITLE
Error no OpenGL support in video driver

### ISSUE THREAD

**Issue by OMID-313** [urho3d/Urho3D#1635]
Hi all,

I installed Urho3D on Ubuntu 14.04 32-bit (on VMware on Windows 7) following the instructions here (https://github.com/urho3d/Urho3D/wiki/G ... d-in-Linux).

After that, I rebooted the system.

Then I tried to run the Ninja example by:
cd /Urho3D/bin
. NinjaSnowWar.sh

But it gives the following error:

[Sat Oct 8 18:31:40 2016] INFO: Opened log file /root/.local/share/urho3d/logs/NinjaSnowWar.as.log
[Sat Oct 8 18:31:40 2016] INFO: Added resource path /home/omid/Urho3D/bin/Data/
[Sat Oct 8 18:31:40 2016] INFO: Added resource path /home/omid/Urho3D/bin/CoreData/
[Sat Oct 8 18:31:40 2016] INFO: Added resource path /home/omid/Urho3D/bin/Autoload/LargeData/
[Sat Oct 8 18:31:40 2016] ERROR: Could not create window, root cause: 'No OpenGL support in video driver'

How can I solve this problem ??

**Comment by OMID-313** [comment]
My graphics card is Nvidia GeForce 9400 GT, but it seems that VMware doesn't use it.

Any suggestions !!!!?

**Comment by OMID-313** [comment]
Here's some info:

root@ubuntu:/home/omid/Urho3D/bin# ldd 01_HelloWorld 

	linux-gate.so.1 =>  (0xb77de000)
	libdl.so.2 => /lib/i386-linux-gnu/libdl.so.2 (0xb77c0000)
	librt.so.1 => /lib/i386-linux-gnu/librt.so.1 (0xb77b7000)
	libGL.so.1 => /usr/lib/i386-linux-gnu/mesa/libGL.so.1 (0xb7724000)
	libstdc++.so.6 => /usr/lib/i386-linux-gnu/libstdc++.so.6 (0xb763c000)
	libm.so.6 => /lib/i386-linux-gnu/libm.so.6 (0xb75f6000)
	libgcc_s.so.1 => /lib/i386-linux-gnu/libgcc_s.so.1 (0xb75d9000)
	libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0xb75bd000)
	libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xb740d000)
	/lib/ld-linux.so.2 (0xb77e1000)
	libexpat.so.1 => /lib/i386-linux-gnu/libexpat.so.1 (0xb73e4000)
	libglapi.so.0 => /usr/lib/i386-linux-gnu/libglapi.so.0 (0xb73cb000)
	libXext.so.6 => /usr/lib/i386-linux-gnu/libXext.so.6 (0xb73b8000)
	libXdamage.so.1 => /usr/lib/i386-linux-gnu/libXdamage.so.1 (0xb73b4000)
	libXfixes.so.3 => /usr/lib/i386-linux-gnu/libXfixes.so.3 (0xb73ad000)
	libX11-xcb.so.1 => /usr/lib/i386-linux-gnu/libX11-xcb.so.1 (0xb73aa000)
	libX11.so.6 => /usr/lib/i386-linux-gnu/libX11.so.6 (0xb7276000)
	libxcb-glx.so.0 => /usr/lib/i386-linux-gnu/libxcb-glx.so.0 (0xb725e000)
	libxcb-dri2.so.0 => /usr/lib/i386-linux-gnu/libxcb-dri2.so.0 (0xb7258000)
	libxcb-dri3.so.0 => /usr/lib/i386-linux-gnu/libxcb-dri3.so.0 (0xb7253000)
	libxcb-present.so.0 => /usr/lib/i386-linux-gnu/libxcb-present.so.0 (0xb724f000)
	libxcb-sync.so.1 => /usr/lib/i386-linux-gnu/libxcb-sync.so.1 (0xb7248000)
	libxcb.so.1 => /usr/lib/i386-linux-gnu/libxcb.so.1 (0xb7226000)
	libxshmfence.so.1 => /usr/lib/i386-linux-gnu/libxshmfence.so.1 (0xb7223000)
	libXxf86vm.so.1 => /usr/lib/i386-linux-gnu/libXxf86vm.so.1 (0xb721c000)
	libdrm.so.2 => /usr/lib/i386-linux-gnu/libdrm.so.2 (0xb720c000)
	libXau.so.6 => /usr/lib/i386-linux-gnu/libXau.so.6 (0xb7208000)
	libXdmcp.so.6 => /usr/lib/i386-linux-gnu/libXdmcp.so.6 (0xb7201000)

**Comment by eugeneko** [comment]
Are you sure that your VM support required version of OpenGL?
Try to run GL Extension Viewer and check.

**Comment by OMID-313** [comment]
Some more info:

root@ubuntu:/home/omid/Urho3D/bin# lspci -vnn | grep VGA

00:0f.0 VGA compatible controller [0300]: VMware SVGA II Adapter [15ad:0405] (prog-if 00 [VGA controller])
	Subsystem: VMware SVGA II Adapter [15ad:0405]

**Comment by OMID-313** [comment]
Thanks @eugeneko for your reply.

How can I check that ?

**Comment by eugeneko** [comment]
Huh.. I suppose Urho needs at least OpenGL 2.0
So you can try to find&run some demos or games that use it.
Or maybe this utility helps you, I'ven't tested it.
http://www.geeks3d.com/20141121/gl-z-opengl-information-utility-extensions-viewer-for-windows-linux-and-os-x/

**Comment by OMID-313** [comment]
Thanks again @eugeneko for your reply.

I tested this GL-Z on windows.
It says GL_Version: 3.3.0

**Comment by eugeneko** [comment]
Have you tested it in VM?

**Comment by OMID-313** [comment]
@eugeneko ,
I couldn't run it on Ubuntu 14.04 32-bit. It is 64 bit.
Is there any other way to check GL version? preferably via terminal commands ?

**Comment by OMID-313** [comment]
Here it is in VM :

root@ubuntu:/home/omid/Urho3D/bin# glxinfo | grep "OpenGL version"

OpenGL version string: 2.1 Mesa 10.3.2

**Comment by OMID-313** [comment]
root@ubuntu:/home/omid/Urho3D/bin# glxinfo | grep OpenGL

OpenGL vendor string: VMware, Inc.
OpenGL renderer string: Gallium 0.4 on SVGA3D; build: RELEASE;  
OpenGL version string: 2.1 Mesa 10.3.2
OpenGL shading language version string: 1.20
OpenGL extensions:

**Comment by OMID-313** [comment]
Ok.
I did it.

First I deleted the whole Urho3D folder.
Then Installed it from the beginning.
This time it didn't give any errors.
And also, the Ninja game works when I run it. (although with problems! just blue screen!!)

Thanks everyone for your support and help.
