### ISSUE TITLE
Prefabs support (level 2)

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1636]
Urho has some prefab support, but for now prefab is just a prototype of object that can be instanciated. This is very limited usage because node don't have any connection to its prefab.
Prefabs are useful for dynamic spawn and useless for scene building because anyway I don't have ability to change all prefab instances in some single place.
I undernstand that this issue can't be easily fixed, but IMO it is quite important.

**Comment by MonkeyFirst** [comment]
I can be easy fixed with using internal marks such as **vars** or **tags** and propagate all changes from selected prefab to all other in then scene, and serialize(update origin) into file.  So all prefabs need to keeping orig object.xml file name/path and some internal mark for this feature

**Comment by pqftgs** [comment]
I hacked this into Urho for my personal projects.  The implementation maybe isn't the most ideal, but it's such a common feature and I wanted maximum XML readability.
https://gist.github.com/pqftgs/781776d922c992b282c131134385c952
Haven't tried nested prefabs but it should work in theory...

**Comment by jforjustin** [comment]
@Bananaft contributed a prefab system.
  https://discourse.urho3d.io/t/poor-mans-prefab-system/4681
