### ISSUE TITLE
34_DynamicGeometry: fromScratchModel impossible save to file

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1638]
Currently I'm experimenting with converting models from Risen game to Urho and use 34_DynamicGeometry as template. I notice that fromScratchModel saved without buffers. ( If I understand correctly it is neccassary to manuall add buffers from geometries to model).

**Comment by eugeneko** [comment]
What about Lua samples?

**Comment by cadaver** [comment]
I didn't manage to expose / marshall a vector of object pointers, so I left it for now.

**Comment by weitjong** [comment]
I have added the Lua binding. Only have time to tested on Linux platform.
