### ISSUE TITLE
ERROR: Could not initialize OpenGL / GLES library

### ISSUE THREAD

**Issue by OMID-313** [urho3d/Urho3D#1644]
Hi all,
I attempted several times to install Urho3D on RPi, which failed.
Finally, I reinstalled Raspbian Jessie OS.
Then reinstalled Urho3D with the following method(with RPi's experimental OpenGL disabled, and GPU=768 MB.) :

```
    sudo apt-get update
    sudo apt-get install build-essential
    sudo apt-get install freeglut3 freeglut3-dev
    sudo apt-get install unixodbc-dev

    sudo apt-get install libevdev2

    sudo apt-get install libasound2-dev
    sudo apt-get install libaudio-dev
    sudo apt-get install libesd0-dev
    sudo apt-get install libpulse-dev
    sudo apt-get install libroar-dev
    sudo apt-get install libreadline6-dev

    sudo apt-get install git cmake make

    sudo git clone https://github.com/urho3d/Urho3D
    cd Urho3D
    sudo ./cmake_rpi.sh /home/pi/Urho3D
    sudo make
```

Now after installation, when I run ./Urho3DPlayer , it gives the following error:

```
    [Thu Oct 13 10:56:17 2016] INFO: Opened log file /home/pi/.local/share/urho3d/logs/NinjaSnowWar.as.log
    [Thu Oct 13 10:56:17 2016] INFO: Created 3 worker threads
    [Thu Oct 13 10:56:17 2016] INFO: Added resource path /home/pi/Urho3D/bin/Data/
    [Thu Oct 13 10:56:17 2016] INFO: Added resource path /home/pi/Urho3D/bin/CoreData/
    [Thu Oct 13 10:56:17 2016] INFO: Added resource path /home/pi/Urho3D/bin/Autoload/LargeData/
    [Thu Oct 13 10:56:17 2016] ERROR: Could not create window, root cause: 'Could not initialize OpenGL / GLES library'
```

What is the problem !!?
How can I successfully get Urho3D to work on RPi !!!?!?!?!?

**Comment by OMID-313** [comment]
Please help @cadaver and @weitjong .

**Comment by 1vanK** [comment]
this error from sdl: Source\ThirdParty\SDL\src\video\SDL_egl.c
SDL can not found GL lib
pls try to update GL drivers

**Comment by OMID-313** [comment]
Thanks for your reply @1vanK .
Would you please tell me how I can do this !!?

**Comment by 1vanK** [comment]
sorry, I do not use rasberry pi

**Comment by Lumak** [comment]
I googled Raspberry Pi openGL driver and came up with:  
https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=140865

**Comment by OMID-313** [comment]
I don't think it's related to the experimental GL driver. Because I have disabled it. Also, Urho3D doesn't support it.

**Comment by OMID-313** [comment]
Any suggestions !?
I'm trying everything I think of. I've reinstalled Urho3D nearly 10 times with different methods.
But all time the same error.
Please help.

**Comment by weitjong** [comment]
Let me repeat what I have said previously in other place, you do not need root (so, don't use sudo) to build and run Urho3D. This is as far as I could advise you until you have this concept understood. Also, please don't abuse our Issue tracker. We use it only when we are sure there is a bug in our software. In your case it is clearly an issue with your build environment. For that please use the forum instead.

**Comment by OMID-313** [comment]
The problem got solved!
I did : 
`sudo apt-get remove mesa-common-dev`
and reinstalled Urho3D.
Now it works.
