### ISSUE TITLE
MRT not supported on iPad mini retina

### ISSUE THREAD

**Issue by meshonline** [urho3d/Urho3D#1645]
iPad mini retina already supports OpenGL ES 3.0, but shaders are limited up to OpenGL ES 2.0.
All shaders which use MRT will refuse to compile.

**Comment by cadaver** [comment]
For now this is a known and documented limitation.
https://urho3d.github.io/documentation/HEAD/_a_p_i_differences.html

**Comment by cadaver** [comment]
Note that it's fine to make a request for OpenGL ES3.0 support and this issue would eventually get rectified as a part of that. However as always, there will be no promise for implementation timetable.
