### ISSUE TITLE
pbr problems,how to solve env-map edge line like unity or unreal

### ISSUE THREAD

**Issue by xiongyaya** [urho3d/Urho3D#1646]
![qq 20161014231916](https://cloud.githubusercontent.com/assets/13036261/19392909/516bd74a-9265-11e6-8a9a-e39a56177784.png)
![qq 20161014232118](https://cloud.githubusercontent.com/assets/13036261/19392910/52bfe9e2-9265-11e6-80d8-9fcb890b7715.png)
cubemap cut-line is obvous on the fronter photo in pbr demo, unity or unreal  have a smooth surface even with a full-roughness material. how to improve this like the two engines?

**Comment by xiongyaya** [comment]
the second parameter has some error, metallic should be 1
![qq 20161014233349](https://cloud.githubusercontent.com/assets/13036261/19393304/b8f49e64-9266-11e6-87ab-f8311ab62445.png)

**Comment by cadaver** [comment]
I don't have a solution, but it's fairly clear where this comes from: it's sampling the roughest mip level of each environment cubemap face, however in that case (at least with the default sampling operation) it doesn't blend across the face edges. If all faces of the cubemap at the roughest mip had same color, the problem wouldn't show.

**Comment by dragonCASTjosh** [comment]
I have been planning to improve the mip level sampling, but the seams themselves are less of an implementation issue and more because the cubemap is not that well filtered, in addition to this we really should be filtering cubemap in engine for best quality and usability but that is not set up and would be a large addition to the engine.

**Comment by xiongyaya** [comment]
good aticle, I'm interesting with pbr and will try to find some solutions on the internet.

**Comment by dragonCASTjosh** [comment]
The error mostly lies in the fact that seamless cubemaps are not supported out the box in D3D9 and is possibly not enabled in GL so we will have to correct it manually

**Comment by xiongyaya** [comment]
thank you for your explains， filtered-method results this error,right? I find another good pbr filtered example at
https://github.com/derkreature/IBLBaker
it do the cube-filter with shader, I do't kown whether his method solve this problem or not and will have a test.

**Comment by dragonCASTjosh** [comment]
Baking the IBL in engine will make the results less apparent but the main causes of the issue is DX9 itself thats there the first link i posted comes in as that is a work around to that issue

**Comment by dragonCASTjosh** [comment]
@xiongyaya if you are running in DirectX feel free to try my latest commit on my personal branch

**Comment by dragonCASTjosh** [comment]
Can someone confirm these issues are fixed

**Comment by dragonCASTjosh** [comment]
@cadaver due to lack of response i guess we can call this solved

**Comment by cadaver** [comment]
It's fine by me, it also depends on the mipmap authoring.
