### ISSUE TITLE
Bucket of minor changes

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1648]
Since I have push access to Urho repo and bucket of minor changes, I'd like to confirm first that they are acceptable.

- Some templatized signature for all `SomeType ToSomeType(String)` functions. I am unsure about its name. `T To<>(String)` is too common word, but I don't have other ideas. **Let's discuss.**

- Image::SaveDDS limited to uncompressed 4-component mip-mapped image wihtout layers

- Image::Save save to JPG, BMP, PNG, TGA or DDS depending on file extension

- UniquePtr as smart wrapper for dumb new/delete ops

- MakeUnique and MakeShared with variadic implementation on C++11 and 0-arg + 1-arg hardcoded signatures on C++98

- Override begin() and end() for Pair to allow using Pair as range in for loops (C++11)

- UpperBound and LowerBound templates in Vector.h

- UnLerp and UnLerpClamped as opposite of Lerp operation

- Pow, Sqrt, Floor, Round, Ceil simple wrappers to bring some naming consistency with other functions and AS

- VectorFloor, VectorCeil, VectorRound, VectorMax, VectorMin as per-component vector wrappers for scalar functions

- Stable 'seed-less' random ops like uint->unit, float->float, vec2->float and vec3->float.
I am unsure about implementation, but there are few variants.

**Comment by cadaver** [comment]
Look OK to me. A simple question to ask is that if it doesn't break existing API and adds useful operations, it should be OK to add. Did you convert the actual engine code to use UniquePtr? That's not mandatory, though it'd be nice to get the CI to exercise the added functionality where easily possible.

For the To string conversion, what comes to mind is FromString, but it's perhaps not entirely logical.

**Comment by eugeneko** [comment]
If I want to test my changes with CI before pushing to master, what should I do?

**Comment by cadaver** [comment]
You can use a feature branch, which you can merge and delete when you're done.

**Comment by eugeneko** [comment]
Are feature branches checked automatically?

I also thought about replacing ugly null pointers like (Geometry*)0 with something short and nice, but I don't know what. Have you any ideas? It could be NULL, but I don't like NULL very much.

**Comment by cadaver** [comment]
Yes, they are checked.

I don't have ideas for the pointers for now. I don't recommend at least changing them to NULL. The number casts are only required in the ternary operators.

**Comment by Lumak** [comment]
UnLerp and UnLerpClamped: isn't more common to use InvLerp or InverseLerp?

**Comment by eugeneko** [comment]
@Lumak Agree, thank you.
https://docs.unity3d.com/ScriptReference/Mathf.InverseLerp.html

**Comment by eugeneko** [comment]
@cadaver, @weitjong 
How can I check why some build jobs have failed?

**Comment by eugeneko** [comment]
I am a bit scared by scope of my changes.
I converted raw ptrs to UPs in ~15 places in Urho. Travis is green and I reviewed my code several times.. However, I almost missed one error, so be careful.

Here is a check-list of changed classes. Check in case of appeared defects:
- DynamicNavigationMesh
- NavigationMesh
- Network
- TriangleMeshData
- CollisionShape
- Constraint
- PhysicsWorld
- RigidBody
- XPathQuery
- XMLFile
- Node
- Serializable
- AnimatedSprite2D
- AnimationSet2D
- PhysicsWorld2D

**Comment by cadaver** [comment]
Thanks! The UniquePtr changes indeed clean up the code nicely.

**Comment by eugeneko** [comment]
BTW, I decided to add MakeShared and MakeUnique only for C++11 compilers.
I realized that MakeUnique is useless without move semantics xD
And using MakeShared in new Urho code will lead to unconsistency with legacy code.

PS: How to close issues wia commit?

**Comment by cadaver** [comment]
You have several options, see https://help.github.com/articles/closing-issues-via-commit-messages/
