### ISSUE TITLE
Missing some rendertarget formats in Docs

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1651]
https://urho3d.github.io/documentation/HEAD/_render_paths.html
"a", "l", "la", "d24s8"

**Comment by cadaver** [comment]
Alpha & luminance are very likely to be invalid for rendertargets and don't need to be included, d24s8 is valid, though if you don't want to specifically define a readable depth/stencil you can just let the renderer auto-assign.

**Comment by 1vanK** [comment]
hmm, I used alpha in https://github.com/1vanK/Urho3DHabrahabr06 without any problems (with enabled -gl2 also), and some people from russian forum tested it also...

**Comment by cadaver** [comment]
You're right, a & l formats seem to work for D3D too. la fails at least on D3D9.
