### ISSUE TITLE
How does WorkQueue work?

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1656]
Look at work with **queue_** list.
It is _optionally_ populated in **AddWorkItem** and nowhere else.
So added items could stay outside queue forewer.
E.g. if I add item with priority 2 and then with priority 1, the last item won't get into queue.
I suppose that items should always be put into queue, am I right?

**Upd:** Actually, it will work because Urho always use 0xffffffff priority

**Comment by cadaver** [comment]
That's a bug.
