### ISSUE TITLE
GCC c++14 key generation

### ISSUE THREAD

**Issue by INait** [urho3d/Urho3D#1657]
Hi, if I understand correctly Urho has option C++11 to enable support of c++11, but I couldn't find any option for c++14 generation. If I modify my project's CMakeLists.txt adding c++14 to CMAKE_CXX_FLAGS it won't work because CMake generator creates flags with c++11 which interrupts c++14 anyway. Is there a correct option to generate with CMake both on Windows and Linux with c++14?

**Comment by iSLC** [comment]
I don't really see the point since Urho3D will not actually take advantage of c++14. It's not as if it'll make any significant difference in the generated code.

You could however enable it in your application where you can take advantage of it if you so desire.

**Comment by INait** [comment]
Yes, I'm enabling it for my application only, what is the correct way of doing this? Get rid of
-DURHO3D_C++11=ON
for project generation and add 
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14")
for project's CMakeLists?

**Comment by iSLC** [comment]
If you want to hack your way into the build system the exact option is set in the file `CMake/Modules/Urho3D-CMake-common.cmake` search for a comment `# Platform and compiler specific options`. And simply modify `foreach (STANDARD gnu++11 gnu++0x)` to `foreach (STANDARD gnu++14 gnu++11 gnu++0x)` to first search to see if C++14 is available and then fallback to the others if not.

**Comment by INait** [comment]
Thanks a lot, I'll try that.

**Comment by weitjong** [comment]
Urho3D buildsystem does not support C++14 yet. However, both of your approaches above should work just fine if you just want to enable the C++14 standard in your own project.
