### ISSUE TITLE
Value editor in Color Wheel works strange.

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1658]
When I am trying to set color value at the black-white 'bar':
1) single click does nothing
2) dragging cause window drag&drop.
It is pretty confusing.

**Comment by MonkeyFirst** [comment]
Use R-mouse button instead L

**Comment by eugeneko** [comment]
Thx, I'll try it.
But it is still confusing, because L works fine for HueSat editor

**Comment by eugeneko** [comment]
@MonkeyFirst R-mouse cause camera rotation, click still does nothing

**Comment by MonkeyFirst** [comment]
I guess it will need turn-off at all in std hotkey mode, and allow to use only in blender mode. where R button - is selecting

**Comment by cadaver** [comment]
@eugeneko If you feel like improving it, go right ahead; it's likely if you find something illogical then others will have the same observation.
