### ISSUE TITLE
Text element GetCharPosition/Size return wrong data on first character of a new line

### ISSUE THREAD

**Issue by Fastran** [urho3d/Urho3D#1659]
The issue presents itself only if the new line is induced by the text wrapping without "/n"
The data returned is the end of the previous line for GetCharPosition and IntVector2::ZERO for GetCharSize

Adding 
`if(lastFilled>printToText_[i])
			lastFilled=printToText_[i];`
in Text.cpp in `void Text::UpdateCharLocations()`
before
`// Fill gaps in case characters were skipped from printing`
       ` for (unsigned j = lastFilled; j <= printToText_[i]; ++j)`
            `charLocations_[j] = loc;`
       ` lastFilled = printToText_[i] + 1;`
should solve the problem

**Comment by cadaver** [comment]
Thanks, will check this shortly.
