### ISSUE TITLE
Upgrade to SDL v2.0.5

### ISSUE THREAD

**Issue by weitjong** [urho3d/Urho3D#1662]

**Comment by weitjong** [comment]
It looks like tvOS is now officially supported by SDL! I think it is time to revisit my earlier attempt of porting Urho3D to tvOS platform.

**Comment by weitjong** [comment]
I am not able to progress much today because there is something wrong with our SDL subtree. I am not able to re-split cleanly using the "Source/ThirdParty/SDL" prefix path.

**Comment by weitjong** [comment]
Learn more about ```git subtree``` today. Finally able to split and push cleanly from our subtree to our sdl-fork. This is the command I use:
```
git subtree split --prefix Source/ThirdParty/SDL 35a616448a5cd065d395031fcc391e925e104d66^.. --onto a9018279076a85c41db22a2cc52c27694c6b67cc --rejoin -b temp
```
The ```temp``` branch name in the end of the command is not important as the branch is pushed to sdl-fork and can be deleted eventually. What worth to mention is the ```--rejoin``` option which inserts a synthetic history back to main repo so that future split/push will not have this problem again (it should just pickup new commits from this rejoin marker onward).

What's next? Rebase the branch in our sdl-fork to upstream's 2.0.5.

**Comment by weitjong** [comment]
EDIT: force to hard reset to remove the synthetic commit created by the rejoin option. Although it works as expected it has a very negative side effect which increases our commit counts as if both Urho3D and SDL code base are being merged). The "modified-for-urho3d" branch in our sdl-fork is still good to go though.

**Comment by weitjong** [comment]
Rebased and pulled back all the changes into SDL subtree. This initial work can be found in ```upgrade-sdl-2.0.5``` branch. So far tested with no regression on Linux platform.

**Comment by cadaver** [comment]
Excellent! I should be able to test Windows / Android / iOS in the coming days.

**Comment by weitjong** [comment]
Not all platforms built cleanly as of last CI, but it is expected and they should be easy to fix.

**Comment by cadaver** [comment]
Windows worked fine for me based on a quick smoke test. For Android (using NDK 12b, and compiling on Windows) I got "ISO C90 forbids mixed declarations and code" from SDL code, should I update my NDK?

**Comment by cadaver** [comment]
Got audio related missing reference (linking) errors from both OSX & iOS builds.

**Comment by weitjong** [comment]
> Windows worked fine for me based on a quick smoke test. For Android (using NDK 12b, and compiling on Windows) I got "ISO C90 forbids mixed declarations and code" from SDL code, should I update my NDK?

I am using NDK 12b too, however, I have switched to use Clang compiler all the way. As you can see, even our Android CI builds on Travis are now all using Clang. I think we should probably not spend more time fixing any GCC issues in Android build anymore because GCC is already no longer supported in NDK 13b. However, I reckon it could be easily fixed if we really want to. I will try to compile using GCC later.

> Got audio related missing reference (linking) errors from both OSX & iOS builds.

That should be an easy fixed too. SDL team has changed the audio framework in their CMake scripts. It is a case of adapting our own macro to match the framework list.

Will try to fix all build issues by end of today hopefully. But currently I am working on cross-compiling with Wayland enabled.

**Comment by weitjong** [comment]
All builds are fixed except iOS. I don't have build environment to build iOS locally, so it is a bit hard to troubleshoot it. @cadaver could you paste the exact linking error that you got? Alternatively, you can just fix it directly in the branch :)

**Comment by cadaver** [comment]
I'll dig the error again today.

**Comment by weitjong** [comment]
I think I have found the missing framework for iOS.

**Comment by cadaver** [comment]
Sweet!

**Comment by cadaver** [comment]
Confirmed successful iOS build on hardware.

**Comment by weitjong** [comment]
Great. I think we could merge this one rather sooner if there are no objection. Perhaps I have verified/fixed the input problem on RPI platform. The input on RPI is broken since SDL 2.0.4 upgrade.

**Comment by cadaver** [comment]
No objection. And remaining issues (if any) will be found faster in master.

**Comment by weitjong** [comment]
It is merged.
