### ISSUE TITLE
Bottleneck in hierarchy ListView

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1664]
I've noticed that adding new nodes in Editor costs much more than I expected.
E.g. when I have several thousands of nodes, adding new node takes about 15ms and this time grows with scene complexity. This is quite important for procedurally spawned nodes (even temporary), because spawning several hundreds of nodes take more than second.
The biggest part of time is spent inside _nodeadded_ event.
I suppose it is caused by rebuilding and reallocating of items list even if hierarchy is hidden or collapsed.
I am trying to somehow optimise it... E.g. create tree data structure instead of plain vector inside HierarchyContainer. Or maybe just disable all these updates if hierarchy is hidden.
Does anybody have good ideas?

**Comment by MonkeyFirst** [comment]
>Does anybody have good ideas?
Catch only one nodeadded event per second or two and update hierarchy ListView, other incoming events ignore.

**Comment by cadaver** [comment]
The UpdateHierarchyItem() function in the editor is quite generic, it could optimize for new node added case. For one thing it looks through the existing items in the list to check if it's already there (and find list index in that case), for a new node we know that's false. Furthermore it's doing the loop in script and not C++.

**Comment by eugeneko** [comment]
@cadaver Then I'll try to optimize it locally, thank you.

@MonkeyFirst It's not so easy because these updates are accumulative and we can't just throttle 'em.

**Comment by eugeneko** [comment]
I tried. It looks like the main problem is in ListView and single vector for whole hierarchy.
I want to at least try to write some other control like ListView but without such indexes.
Is is possible to avoid global indexes at all and use only UIElement ptrs in all ops?

And what's the meaning of overlay checkboxes inside HierarchyContainer?

**Comment by eugeneko** [comment]
I optimized Editor work with invisible temporary nodes. Now it has O(1) complexity instead of O(N), so my ~1s lags just entirely disappeared.
However, it is just a half of work. Spawinig objects throught _Run Script..._ has O(N^2) complexity and this is.. bad.
I suppose that turning off scene updated during _Run Script..._ and `UpdateHierarchyItem(editorScene, true)` call after will significantly improve performance for heavy cases. However, it will probably slow down lightweight scripts.
@cadaver What do you think about proposed solution and adding some flag to Settings or Preferences dialog that will control this behavior?

**Comment by cadaver** [comment]
I don't have a strong opinion. My assumption when I wrote the "Run script" utility is that a script would typically touch the whole scene. I'd say you could go ahead and disable the window update during script run, then do a full update afterward. No need to even have a setting, since the more we have settings, the more confusing it is.

**Comment by eugeneko** [comment]
@cadaver Great! I was afraid that you will be against my solution in simplest form.

I tested this solution. 110sec vs 3.5sec for my spawn script.
Now I am fully satsified with Editor performance, so I am closing this issue.

**Comment by eugeneko** [comment]
@cadaver 
Before I push..
Do I need to call `UpdateHierarchyItem(editorUIElement, true)` in addition to `UpdateHierarchyItem(editorScene, true)`?
I know that Editor exprots 'scene' in script, but maybe changing of UI is also possible somehow...

**Comment by cadaver** [comment]
The intention has been that the scripts you run from the editor will modify the scene. But nothing prevents someone writing a UI manipulation script. Most likely, the UI hierarchy open in the editor is small (compared to scene) so executing that takes negligible time, so it's probably a good idea to call it to be prepared for every possibility.
