### ISSUE TITLE
HiresTick()   wrong behaviour on Windows

### ISSUE THREAD

**Issue by elix22** [urho3d/Urho3D#1667]
Since HiresTick() supposed to return the time in microseconds
timeGetTime() returns the time in milliseconds , hence it should be multiplied by 1000.

Should be :
    if (HiresTimer::IsSupported())
    {
        LARGE_INTEGER counter;
        QueryPerformanceCounter(&counter);
        return counter.QuadPart;
    }
    else
        **return timeGetTime() * 1000; // should be converted into microseconds**

**Comment by cadaver** [comment]
This is not a bug. The HiresTick() is only used internally, and it is not guaranteed to be any specific unit, rather it's divided by the internal frequency when returned to the user. When using performance counter, the internal frequency equals the performance counter frequency.  In Windows fallback mode (timeGetTime) the frequency is left to the default value 1000.

**Comment by elix22** [comment]
Actually I think its a bug 
Yes I know its internal static function.
Yes I know its a fallback function

**It is being called by "HiresTimer::GetUSec(bool reset)"
Which is using  microseconds as its unit of measurement.**

timeGetTime() according to MSDN is returning the time milliseconds .
So it should be multiplied by 1000

**Comment by 1vanK** [comment]
```
long long HiresTimer::frequency(1000); // ----- WIN32

Time::Time(Context* context) :
    Object(context),
    frameNumber_(0),
    timeStep_(0.0f),
    timerPeriod_(0)
{
#ifdef _WIN32
    ...
#else
    HiresTimer::frequency = 1000000; // ----- NOT WIN32
    HiresTimer::supported = true;
#endif
}

long long HiresTimer::GetUSec(bool reset)
{
    ...
    return (elapsedTime * 1000000LL) / frequency;
}

```

**Comment by elix22** [comment]
1vanK
OK I see your point 

All I know is that I changed it (*1000)
And Windows Scene update is now behaving the same as on Android , which is not the case with the original code.
