### ISSUE TITLE
Forward lighting command override existed render target

### ISSUE THREAD

**Issue by meshonline** [urho3d/Urho3D#1671]
I use two pass rending, the first pass is to make a QUAT, the second pass is to render the original effect, then combine them together.

Here is the render path:
```
<renderpath>
    <rendertarget name="blurv" tag="Bloom" sizedivisor="4 4" format="rgb" filter="true" />
    <rendertarget name="blurh" tag="Bloom" sizedivisor="4 4" format="rgb" filter="true" />

    <command type="clear" color="fog" depth="1.0" stencil="0" output="viewport" />
    <command type="scenepass" pass="base2" vertexlights="true" metadata="base" output="viewport" />
    <command type="forwardlights" pass="light2" output="viewport" />

    <command type="quad" tag="Bloom" vs="Bloom" ps="Bloom" psdefines="BRIGHT" output="blurb">
        <parameter name="BloomThreshold" value="0.0" />
        <texture unit="diffuse" name="viewport" />
    </command>
    <command type="quad" tag="Bloom" vs="Bloom" ps="Bloom" psdefines="BLURH" output="blush">
        <texture unit="diffuse" name="blurv" />
    </command>
    <command type="quad" tag="Bloom" vs="Bloom" ps="Bloom" psdefines="BLURV" output="blurb">
        <texture unit="diffuse" name="blurh" />
    </command>

    <command type="clear" color="fog" depth="1.0" stencil="0" output="viewport" />
    <command type="scenepass" pass="base" vertexlights="true" metadata="base" output="viewport" />

    <!--
    <command type="forwardlights" pass="light" output="viewport" />
     -->

    <command type="quad" tag="Bloom" vs="Bloom" ps="Bloom" psdefines="COMBINE" output="viewport">
        <parameter name="BloomMix" value="1.0 1.0" />
        <texture unit="diffuse" name="viewport" />
        <texture unit="normal" name="blurv" />
    </command>
</renderpath>
```

If I uncomment the second 'forwardlights' command, the render target of 'blurv' will be override, its content will change.

**Comment by cadaver** [comment]
Multiple forwardlight commands in a renderpath, using different passes, are not currently supported. I can take a look if it would be possible without significant trouble, but no especial promises.

**Comment by cadaver** [comment]
Ok. Have reviewed the internals of the render commands processing and supporting multiple lights loop commands would be complex and error-prone, so will not add it at least for the moment. I'll add a documentation note that only one command is allowed.

**Comment by meshonline** [comment]
Hi,

I’m trying to read the source code, but find no clue.

Would you hint me what causes multiple lights loop fails? Is the shadow map? Or something else?

Thanks.

Art

**Comment by cadaver** [comment]
The View class code assumes that the forwardlights command is a "singleton" and is not repeated. For example, the pass to use is only stored once, and adding the forwardlight batches is handled in a special way compared to other batches. It's kind of all over the place.
