### ISSUE TITLE
[FindDirectX.cmake] execute_process output_file needs to be absolute

### ISSUE THREAD

**Issue by matanshukry** [urho3d/Urho3D#1674]
I'm trying to build Urho3D from source with cmake and mingw,
and I've encountered an error running cmake. The following line:

https://github.com/urho3d/Urho3D/blob/master/CMake/Modules/FindDirectX.cmake#L78

Results in an error, since the file doesn't seems to exists in the expected directory.
I've solved it by simply editing the output_file path to an absolute one, using same variable.

```
execute_process (COMMAND ${CMAKE_COMMAND} -E echo "#include <_mingw.h>" COMMAND ${CMAKE_C_COMPILER} -E -M - OUTPUT_FILE ${CMAKE_BINARY_DIR}/find_mingw_sysroot_output)
```

As you can see, the original cmake code at line 77 doesn't contains ```${CMAKE_BINARY_DIR}```, and from some reason it causes issues. I also see no reason to use absolute paths either, specially since it's being used a second later to read from that file anyway.

**Comment by weitjong** [comment]
Which version of CMake are you using. From what I know and from all the CMake versions that I have tested and used before, the ```execute_process()``` command generates output file in the current working directory when not explicitly stated. And in the above context, the current directory equals to ```CMAKE_BIN_DIR```. Having said that I see no harm to specify the path explicitly if that solves your issue. I wonder how many users hit by this issue as I have never encountered it.

**Comment by matanshukry** [comment]
I am using cmake 3.6.3.

I will say this though: The exact file and build worked when using cmake with VIsual Studio 14 with cmake 3.7-rc3.

The above description however, which didn't work, was using cmake 3.6.3 and mingw.

Not really sure if they are related, but as you said - it's a small fix, and at least to me - it was easier to simply add that then to find the difference between the two.
