### ISSUE TITLE
Incorrect normal mapping on billboards

### ISSUE THREAD

**Issue by axredneck** [urho3d/Urho3D#1678]
How to reproduce:
- Create Directional light
- Create BillboardSet with some billboards
- Apply any material with normals to it, e.g. Data/Materials/StoneSmall.xml
- Look at the BillboardSet from various angles. Sometimes it is lit correctly, sometimes it becomes black, sometimes normals become flipped or distorted.
Maybe the issue is somehow related to tangent coords of billboards?

**Comment by cadaver** [comment]
Should be solvable by fixing the shader function GetWorldTangent() to return a fixed default tangent value (e.g. one pointing always right) multiplied by the world matrix, when billboard geometry is used. Right now it always assumes to read the model's tangent data, which doesn't exist in that case.

**Comment by axredneck** [comment]
Thanks!
