### ISSUE TITLE
StaticModel Replicator() function

### ISSUE THREAD

**Issue by Lumak** [urho3d/Urho3D#1682]
I'd like to add this https://github.com/Lumak/Urho3D-Geom-Replication to the repo, but I know that a script example must accompany it.

Question is where to add it, vehicle demo?

edit: the link

**Comment by Lumak** [comment]
Odd, you can't add an external link. The link gets converted to https://github.com/urho3d/Urho3D/issues/url

You'll have to copy and paste the link: https://github.com/Lumak/Urho3D-Geom-Replication

**Comment by eugeneko** [comment]
Why not e.g. boxes? It is not as interesting as grass, I agree, but... Somewhy I think that there is no need to pull one more binary asset to main repo just for another simply demo.
Urho already have demo with huge number of objects.. Why not to do something like it?

**Comment by Lumak** [comment]
Two reasons: 1) the stonediffuse texture is ugly, hence, boxes are ugly.  Frankly, some of the sample textures are outdated and more up to date textures should replace them to add appeal.  2) Not that any grass texture is beautiful, the sample demo lacks outdoor examples.

**Comment by Lumak** [comment]
outdoor examples meaning, grass, trees, rocks, etc.

**Comment by yushli** [comment]
I totally agree that the default Urho3D samples should be polished to be more attractive. These samples are showing the performance power of Urho3D, but not in a game engine way: not a single real-world game would use such models and textures. The newly added mutant models and animations greatly improve the appearance. More should be replaced or added to match the expectation of a game engine.

**Comment by eugeneko** [comment]
It would be great to have more attractive examples, I agree.
However, Urho just don't have mechanisms for out-of-box outdooring and there are still many things to do. Sample IMO shouldn't introduce much more than engine can do itself just because it is _sample_ of usage of engine.

Thirdly, IMO this grass is even less attractive than default boxes. Mutant was beatiful, this grass looks dark, pixelized and old.
![](https://github.com/Lumak/Urho3D-Geom-Replication/raw/master/screenshot/replicatedGeom3.jpg)

**Comment by Lumak** [comment]
What, you don't find that pretty?  :) 

That pic as shown by what's written on it depicts replicating a simple geom into a single vertex buffer even 50k times results in very little performance loss.  I'm sure you are aware of this and know it's not about how pretty it is.

Let's drop this request for now.  Maybe we can revisit it later.

**Comment by eugeneko** [comment]
Of course I am aware that this demo is about performance.
My initial concern is that we need either add some nice content in demos (like mutant) or don't add it at all and use simple built-in stuff. I don't like some middle ways.
Let's hold outdoor example until we can do it good.

**Comment by 1vanK** [comment]
Nice! This grass can be animated in some way? Vegetation shader unsuitable, so it translate verticles of neighboring blades of grass together and at looks unnaturally (every blade of grass must wobble independently)

**Comment by 1vanK** [comment]
May be add random "phase" to UV2 every blade

**Comment by 1vanK** [comment]
or calc hash from world positions and use it as phase
