### ISSUE TITLE
Failed to lock index buffer when using intents on Android

### ISSUE THREAD

**Issue by sabotage3d** [urho3d/Urho3D#1684]
I have simple java function that opens a file using intents on Android under Urho3D. When I close the intent window Urho3D starts to print Failed to lock index buffer. At the moment the intent function is part of the Urho3D activity.

**Comment by cadaver** [comment]
This sounds like it could be a thread access issue, (Urho's OpenGL ES access should happen only in the "main thread" SDL has dedicated for graphics access), or a context loss in a way that SDL / Urho are not prepared to handle. Will need closer investigation.

**Comment by sabotage3d** [comment]
A bit more in depth. I have empty scene with camera and it happens if there is nothing drawn on screen. If add some 2d sprites it is no longer happening. I am also using JNI via SDL to call the intent. 
This is my C++ side of the code based on the SDL wiki for JNI. The java side is simple open file intent.

```
// retrieve the JNI environment.
JNIEnv* env = (JNIEnv*)SDL_AndroidGetJNIEnv();

// retrieve the Java instance of the SDLActivity
jobject activity = (jobject)SDL_AndroidGetActivity();

// find the Java class of the activity. It should be SDLActivity or a subclass of it.
jclass clazz(env->GetObjectClass(activity));

// find the identifier of the method to call
jmethodID method_id = env->GetMethodID(clazz, "openFile", "()V");

// effectively call the Java method
env->CallVoidMethod(activity, method_id);

// clean up the local references.
env->DeleteLocalRef(activity);
env->DeleteLocalRef(clazz);
```
