### ISSUE TITLE
UIElement::GetCombinedScreenRect is not recursive

### ISSUE THREAD

**Issue by Fastran** [urho3d/Urho3D#1687]
This method should account for combined rect of children, at the moment it doesn't

inside UIElement::GetCombinedScreenRect()
the portion:

            IntVector2 childPos = (*i)->GetScreenPosition();
            const IntVector2& childSize = (*i)->GetSize();

should be like this if I'm not mistaken

            IntRect childCombined((*i)->GetCombinedScreenRect());
            IntVector2 childPos(childCombined.left_,childCombined.top_);
            const IntVector2& childSize(childCombined.right_-childCombined.left_,childCombined.bottom_-childCombined.top_);

**Comment by cadaver** [comment]
Yes, if we want to ensure correctness with IsInside() checks when there's a chain of child elements that aren't encompassed / clipped by the parent.
