### ISSUE TITLE
AssetImporter.exe incorrect export a model FBX with a node structure meshes.

### ISSUE THREAD

**Issue by Commondor** [urho3d/Urho3D#1691]
AssetImporter.exe incorrect export a model FBX with a node structure meshes.

![bug](https://cloud.githubusercontent.com/assets/9081571/20422872/b1b68520-ad75-11e6-8448-67ca8b88770b.jpg)

**Comment by Lumak** [comment]
Pass the :
`-np         Do not suppress $fbx pivot nodes (FBX files only)`

option to remove the suppression and import the model as is.

**Comment by Commondor** [comment]
Thank you!  :)
