### ISSUE TITLE
Build error on MacOS Sierra.

### ISSUE THREAD

**Issue by NorthSailor** [urho3d/Urho3D#1692]
When building the Civetweb subproject, I initially got a build error about conflicting types for the function `clock_gettime()`. Commenting out the definition of the function solved the issue. Apparently this function is now defined on newer versions of the OS?

**Comment by cadaver** [comment]
We have gone through some nasty magic to try to *not* use the OS built-in function (in favor of the self-defined) because we found runtime crashes due to linking errors on older OS versions. If it would now work on newer ones, appears it'd need some detection magic then.

**Comment by NorthSailor** [comment]
Alright, thanks. I'll try the upstream and close the issue then.

**Comment by cadaver** [comment]
I believe it's good to keep this issue open until verified, as the ideal is that Urho compiles out-of-the-box also on Sierra.

**Comment by weitjong** [comment]
Just managed to upgrade to macOS Sierra + Xcode 8 on a new SSD, strangely I did not encounter any build error whatsoever using latest master branch. My last build uses most of the default build options. The binaries seem to run fine as well.

@NorthSailor Can you specify the steps to reproduce your issue.

**Comment by weitjong** [comment]
> @NorthSailor Can you specify the steps to reproduce your issue.

It is not important now. I will commit a patch to do auto-detection in our build system shortly.

**Comment by dobegor** [comment]
@weitjong @cadaver it's still reproducible on Sierra with latest Urho3D release, and, of course, still workaround-able via commenting this function out.

any plans to release a fix anytime soon?

**Comment by weitjong** [comment]
To me, this issue is already closed because I am no longer able to reproduce the issue (last time I check). If you believe this is not the case then you need to provide the steps on how to reproduce it.

**Comment by dobegor** [comment]
1. Downloaded Urho3D latest release from Github.
2. Launched cmake_osx.sh
3. Opened the project with Xcode (latest).
4. Build fails with aforementioned error.

```int clock_gettime(clockid_t __clock_id, struct timespec *__tp);``` - this function is already defined in time.h in OS X 10.12.5.

**Comment by cadaver** [comment]
If by latest release you mean 1.6 (from August) the fix naturally is not there. Suggest cloning the master branch instead.

**Comment by dobegor** [comment]
Sorry, I accidentally mixed up Urho3D's release cycle with civetweb's.
