### ISSUE TITLE
cannot scale bitmap font 

### ISSUE THREAD

**Issue by yushli** [urho3d/Urho3D#1693]
if using bitmap font, setting the font size doesn't have effect. How to scale the text then if needed?

**Comment by cadaver** [comment]
Currently I believe you'd need several bitmap fonts of different sizes. It would make sense to implement a scale property to Text, similar to sprite element, that would allow it to become non-pixelperfect. Preferably this should be in every UI element, but that would be liable to break child scissor clipping when used.

**Comment by yushli** [comment]
Thanks for considering this. Preferably we can lift the scaling, rotating and translating transform from sprite class to the UI element class so that every UI element has this ability.

**Comment by cadaver** [comment]
That would be sure to break things, so it would be a case of e.g. "do not use if you want scrolling lists to work" etc.

**Comment by yushli** [comment]
That would be fine with me. No harm if not used, but when needed, the feature is there. :)

**Comment by eugeneko** [comment]
This would be confusing. How can user understand what works after scaling and what doesn't?

**Comment by yushli** [comment]
I do expect after scaling or translating everything should just work. As for rotating, not sure the interaction should work or not, but it is preferrable that it will work someway. Imagine we need to add some visual effects to the UI, e.g., when closing the selection window, make it rotate and scale down, and finally disappear. In this scenario it may not need to be interaction perfect.

**Comment by cadaver** [comment]
I think everything should be doable with work, including interaction, as in the end it's just matrix math and inverse matrix math. However at this point it takes quite some courage to start upheaving the UI coordinate system in a large manner, as existing pixel-perfect usecases should not break. So I will not personally promise doing this. There are also optimizations which e.g. allow to skip the first n (which could be a huge number) elements from a scrolling list or such when necessary, and these would be harder to do with freeform transforms.

**Comment by yushli** [comment]
Actually I will settle down with just enabling scaling. Currently I can use SetSize() to mimic the scaling effects on other UI elements such as listview or borderimage. But the solution is not elegant. And text has no effect if just calling SetSize().

**Comment by weitjong** [comment]
UI subsystem scaling is already implemented by Lasse.
