### ISSUE TITLE
[Feature Request] add unit option to assetsimporter

### ISSUE THREAD

**Issue by yushli** [urho3d/Urho3D#1694]
E.g., some models are exported with centimeter as unit instead of meter. When importing into Urho3D, we need to scale down the model. It may be convenient if a unit option can be added into assetsimporter to support this.

**Comment by SirNate0** [comment]
While I don't use assetsimporter, I would suggest calling such a feature scaling, as well as allowing an arbitrary factor (not just predefined conversions between certain units), as units are arbitrary (e.g. an fps may make sense with 1 meter = 1.0f, but in chess who is to say whether 1.0f is 1cm one meter, (or even further out there if we use non-metric units)).

**Comment by yushli** [comment]
Yes anarbitrary factor which can be passed in as an option is great. Anyone interested to implemet that? I can now add code in assetimporter to scale the static model vertexes, but not understand animation good enough to scale the animation data accordingly.

**Comment by Lumak** [comment]
From what I observed comparing animations exported straight from Maximo and the same model/animations rescaled in Maya then exported to fbx and processed through assetimporter was that the root node/bone on the first key frame was scaled.
