### ISSUE TITLE
Incorrect initialization a CrowdAgent component.

### ISSUE THREAD

**Issue by Commondor** [urho3d/Urho3D#1695]
When load xml with InstantiateXML a CrowdAgent component is incorrect initialization because CrowdAgent component initialized (`agentCrowdId_ = crowdManager_->AddAgent(this, node_->GetPosition());`) **before** **node->SetTransform(position, rotation);** and node_ have position = Vector3(0,0,0).

May be make this )) :
`
void CrowdAgent::OnSceneSet(Scene* scene)
{
  AddAgentToCrowd(false, **false**);
}

and

int CrowdAgent::AddAgentToCrowd(bool force**, bool isCreated /*= true*/**)
{
    if (!node_ || !crowdManager_ || !crowdManager_->crowd_ || !**isCreated**)
        return -1;
`

**Comment by cadaver** [comment]
Is there a way to test this in the existing CrowdNavigation sample? It includes scene load/save, but I didn't observe it to work wrong.

**Comment by Commondor** [comment]
In CrowdNavigation sample make this:

Change function:
void CrowdNavigation::SpawnJack(const Vector3& pos, Node* jackGroup)
{
    ResourceCache* cache = GetSubsystem<ResourceCache>();
    SharedPtr<Node> jackNode(jackGroup->CreateChild("Jack"));

	**XMLFile* pJackFile = cache->GetResource<XMLFile>("Objects/test.xml");
	jackNode = scene_->InstantiateXML(pJackFile->GetRoot(), pos, Quaternion::IDENTITY);
	return;**

         . . .
}

Then create file "Objects/test.xml":
<?xml version="1.0"?>
<node id="2">
	<attribute name="Name" value="Jack" />
	<attribute name="Position" value="0 0 0" />
	<attribute name="Rotation" value="1 0 0 0" />
	<attribute name="Scale" value="1 1 1" />
	<attribute name="Variables" />	
	<component type="AnimatedModel" id="4">
		<attribute name="Model" value="Model;Models/Jack.mdl" />
		<attribute name="Material" value="Material;Materials/Jack.xml" />
		<attribute name="Is Occluder" value="false" />
		<attribute name="Can Be Occluded" value="true" />
		<attribute name="Cast Shadows" value="true" />
	</component>
	<component type="AnimationController" id="4" />
	<component type="CrowdAgent" id="4">
		<attribute name="Height" value="2" />
		<attribute name="Max Speed" value="3" />
		<attribute name="Max Accel" value="5" />
	</component>
</node>


Compile this example and try create SpawnJack click (Shift + LBM) and you will see that Jacks start create in mouse click point than jump (move) to another point.

**Comment by cadaver** [comment]
Thanks.

**Comment by cadaver** [comment]
Testing this now, I need to reparent the created node to the jackGroup so that steering happens right. On occasion the agent gets positioned fine, on occasion I actually see the animation explode completely as if the agent's coordinates are nan or something. Needs more investigation.
