### ISSUE TITLE
Animatable Spritesheet support

### ISSUE THREAD

**Issue by sabotage3d** [urho3d/Urho3D#1697]
I have been trying from a few days to get Spritesheets working correctly. So far there isn't an easy way to animate them. Would it be possible to add such support if it doesn't exist already? What I am trying to do is add animated spritesheet to a ParticleEmitter2D.

**Comment by sabotage3d** [comment]
I have added a simple class here: http://urho3d.prophpbb.com/topic2565.html. If anyone thinks it needs PR let me know.

**Comment by cadaver** [comment]
It's cool that you found a solution that works for you. There's a bit of a risk of confusion or non-orthogonality if there's both SpriteSheet2D and SpriteSheet classes.
