### ISSUE TITLE
Cross Compiling Build Error with 1.6

### ISSUE THREAD

**Issue by SirNate0** [urho3d/Urho3D#1698]
When cross compiling with mingw-w64 from Ubuntu, the build failed when building bullet due to a narrowing conversion of +Inf from double to float. Chaning the define in btScalar.h to `#define BT_INFINITY ((btScalar)INFINITY)` (adding a cast to btScalar) fixed it.

**Comment by eugeneko** [comment]
What's the difference with #1637?

**Comment by SirNate0** [comment]
Nothing notable, as far as I can tell. I didn't experience it in a native build, though.
