### ISSUE TITLE
[Feature Request] add "Offset Position" to RigidBody in local space.

### ISSUE THREAD

**Issue by Commondor** [urho3d/Urho3D#1699]
Need add "Offset Position" to RigidBody in local space.

**Comment by cadaver** [comment]
You can already create the collision shapes with an offset and this should cause the center of mass to be calculated correctly. This should mean that the visual mesh and the rigidbody can share the same node position, even if the center of mass isn't at the origin.

**Comment by Commondor** [comment]
Thank you. I try this.
