### ISSUE TITLE
Multiple instances of single animation in AnimationController

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1700]
subj.
I need to simultaneously run one animation several 'times'.
Physical copying of one animation is inappropriate because it is dirty and I have no upper limit of number of instances.
I also don't want to manipulate with AnimatedModel by hand.

**Comment by cadaver** [comment]
Looks like you have to expand the API, for example when playing an animation you could have a bool for "allowMultiple" and then you probably have to add an index parameter to be able to refer to the multiple copies of the same animation. Not going to be very clean in any case I think, but workable.
