### ISSUE TITLE
No mipmapping when texture's filter mode = "nearest"

### ISSUE THREAD

**Issue by axredneck** [urho3d/Urho3D#1701]
I created such XML file:
```
<texture>
	<filter mode="nearest" />
	<mipmap enable="true" />
</texture>
```
But mipmapping doesn't work for the texture.
I think it would be cool to be able to use GL_NEAREST_MIPMAP_NEAREST minification filter, for example if someone wants to make retro-looking 3D game but with mipmapping.

**Comment by cadaver** [comment]
Thanks, good catch. On D3D9/11 it already worked as expected.

**Comment by axredneck** [comment]
Thanks!
