### ISSUE TITLE
More than 16 animations in AnimationController

### ISSUE THREAD

**Issue by orefkov** [urho3d/Urho3D#1703]
When I switch animations for model via PlayExclusive, with 1.0f for fading - first 16 animation works well, but for 17th - playing 0th animation, for 18th - 17th, and so on, playing prior animation, and blending become not worked. I use some combined models on one node.
Also in calling FadeOther from PlayExclusive - if added new animation, others not faded?
Because index no founded.

**Comment by orefkov** [comment]
I found solution:
`bool AnimationController::PlayExclusive(const String& name, unsigned char layer, bool looped, float fadeTime)
{
	bool res = Play(name, layer, looped, fadeTime);
	if (res)
		FadeOthers(name, 0.0f, fadeTime);
	return res;
}`
Thath work.

**Comment by cadaver** [comment]
Thanks, looks to make sense.
