### ISSUE TITLE
question: change in calls to - RigidBody* body = GetComponent<RigidBody>();

### ISSUE THREAD

**Issue by Lumak** [urho3d/Urho3D#1704]
Existing physics classes call `GetComponent<RigidBody>()` which works fine, but of course fails if a class is a derived class from RigidBody.

Can we extend or change existing classes to get instance of RigidBody?

**Comment by cadaver** [comment]
It should be possible to change these to GetDerivedComponent.

**Comment by Lumak** [comment]
I wasn't aware of that function, thanks.
