### ISSUE TITLE
Is VertexBuffer::SetDataRange always used glBufferSubData? (OpenGL)

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1706]
```
SBVertex* vertices = (SBVertex*)vertexBuffer_->Lock(0, count * VERTICES_PER_SPRITE, true);
```
discard value is ignored in OpenGL.
```
void VertexBuffer::Unlock()
{
    ...
    case LOCK_SCRATCH:
        SetDataRange(lockScratchData_, lockStart_, lockCount_); // disacard = false
}
```
```
bool VertexBuffer::SetDataRange(const void* data, unsigned start, unsigned count, bool discard)
{
    ...
            if (!discard || start != 0) // condition always true
                glBufferSubData(GL_ARRAY_BUFFER, start * vertexSize_, count * vertexSize_, data);
            else
                glBufferData(GL_ARRAY_BUFFER, count * vertexSize_, data, dynamic_ ? GL_DYNAMIC_DRAW : GL_STATIC_DRAW);
}
```

Is it correct?

**Comment by cadaver** [comment]
Using this old API only there's not a way to supply a "discard" parameter. It would rather need mapping the buffer using newer (was it GL4?) APIs. Unlike D3D, the actual performance benefit will be at the mercy of the driver.

**Comment by 1vanK** [comment]
I mean line
```
glBufferData(GL_ARRAY_BUFFER, count * vertexSize_, data, dynamic_ ? GL_DYNAMIC_DRAW : GL_STATIC_DRAW);
```
never executed

**Comment by cadaver** [comment]
Ah I see, that should be possible to propagate.

**Comment by 1vanK** [comment]
And yes, I replaced it to
```
            graphics_->SetVBO(object_.name_);
            if (/*!discard || */start != 0)
                glBufferSubData(GL_ARRAY_BUFFER, start * vertexSize_, count * vertexSize_, data);
            else
                glBufferData(GL_ARRAY_BUFFER, count * vertexSize_, data, dynamic_ ? GL_DYNAMIC_DRAW : GL_STATIC_DRAW);
```
and do not see any difference for my SpriteBath (SpriteBath refill VB every frame with different size)

**Comment by 1vanK** [comment]
i just try to find reason, why my realisation http://urho3d.prophpbb.com/topic596-10.html is slower than XNA. It is sadness, that C# works faster than C++ xD

**Comment by cadaver** [comment]
There can be many reasons, does it work faster if you don't update (CPU+GPU transfer bottleneck) or are Urho's shaders more complex (GPU bottleneck) etc.

**Comment by yushli** [comment]
That is interesting. I had always thought that C++ version should be faster than C# version, especially for Urho3D which is actually quite performant, as can be told by the samples. Is anyone willing to do more investigation to find out the reasons and more, to fix that?

**Comment by cadaver** [comment]
If you just make the simplest possible rendering and code directly to the API to get just the rendering you want, I wouldn't be surprised for it to perform better. Urho for example adds extra uniforms to the vertex transform phase for more complex rendering possibilities, and it's hard to take them off without sacrificing the features.

**Comment by yushli** [comment]
That sounds fair. May like to find a way to do some profiling and have some performance data though. Thanks for the explanation.

**Comment by 1vanK** [comment]
Ok, it is my mistake. I compared MonoGame (directx11) with Urho3D DX9.
Native XNA (DirectX 9) shows absolutly identical FPS with my implementation :)

**Comment by yushli** [comment]
Great to hear that. I always think that Urho3D is exceptional in performance, yet with simple an elegant design and code base
