### ISSUE TITLE
Make RandomAccessIterator compatible with STD algorithms

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1711]
It would be convenient... But it will require `<iterator>` header that may slow down compilation of almost all Urho code because it is VectorBase.h...

**Comment by cadaver** [comment]
Maybe you could do that with a compilation define you could enable where needed.

**Comment by eugeneko** [comment]
Sounds good.
But the shortest way is the inheriting from std::iterator that _may_ change iterator size if empty base class optimization doesn't fire.
Can it cause any surprises?

**Comment by cadaver** [comment]
Does it contain virtuals?
I'd recommend testing on some compilers, like MSVC and GCC, and if it works you're probably safe. Plus, it won't be used in the engine itself, but only voluntarily.

**Comment by eugeneko** [comment]
std::iterator contains only typedefs for propper work of STL algorithms.

> Plus, it won't be used in the engine itself, but only voluntarily.
Do you mean std:: algorithms?

**Comment by cadaver** [comment]
Yes, I mean that if this feature is controlled by a define, and there is no binary compatibility issues between enabling and not enabling, then at least presently Urho would not need the define itself.

**Comment by blazej-czapp** [comment]
Note that `std::iterator` is deprecated as of C++17 - inline typedefs are now required.
