### ISSUE TITLE
Request a feature

### ISSUE THREAD

**Issue by sekkit** [urho3d/Urho3D#1712]
Please add Python binding to Urho3D because kbengine & some other popular servers are based on python. We do need a official py binding. thx.

**Comment by cadaver** [comment]
This is unlikely as part of the engine itself. Python is a large dependency, and with our current way of doing script bindings each additional one complicates the source code, so it's detrimental to further development.

I personally think this would make sense as an external project, if someone is willing to do it.

**Comment by cadaver** [comment]
Going to close this as wontfix now. This can be revisited someday if the situation changes.
