### ISSUE TITLE
URHO3D_CLASS

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1713]
Sometimes a programmer may forget add URHO3D_OBJECT to class. What about add defines
```
#define URHO3D_CLASS_BEGIN(className, baseClassName) \
    class URHO3D_API className : public baseClassName \
    { \
        URHO3D_OBJECT(className, baseClassName);

#define URHO3D_CLASS_END };
```
In this way programmer can write
```
URHO3D_CLASS_BEGIN(MyComponent, LogicComponent)
public:
    MyComponent(Context* context);
    virtual ~MyComponent();
    ...
URHO3D_CLASS_END
```

**Comment by iSLC** [comment]
It is a really old design for these days. Also the CLASS_END macro could affect syntax highlighting on some editors. However, if this approach might be implemented, I would make a few suggestions.

First, it changes the default visibility of classes. Which is `private`. So I would suggest adding that somewhere after `URHO3D_OBJECT` if someone is relying on that.

There could also be some overloads for multiple inheritance. But then which of the specified base classes would be the Urho base class?

This is nothing then a convenience macro. Which does come with a bit of confusion. At least to me.

**Comment by eugeneko** [comment]
Huh. Yep. This way is really ugly and break a lot of navigantion/highlight sugar in IDE.
