### ISSUE TITLE
VSM Issues

### ISSUE THREAD

**Issue by dragonCASTjosh** [urho3d/Urho3D#1716]
I know there have been issues with VSM for some time now so i decided it was time to fix them, I started experimenting with the values to see what I could achieve and i feel im onto something but i would like some help/ advice on the remaining issues.

### **Before:**
![screenshot_fri_dec_16_16_39_47_2016](https://cloud.githubusercontent.com/assets/3044415/21270640/62a42e9c-c3af-11e6-9952-c676cb32494a.png)
![screenshot_fri_dec_16_16_41_36_2016](https://cloud.githubusercontent.com/assets/3044415/21270639/62a436e4-c3af-11e6-9ec9-638ea252af6d.png)

### **After:**
![screenshot_fri_dec_16_16_40_54_2016](https://cloud.githubusercontent.com/assets/3044415/21270648/6a180a9a-c3af-11e6-81b2-59aca93a1b40.png)
![screenshot_fri_dec_16_16_41_24_2016](https://cloud.githubusercontent.com/assets/3044415/21270649/6a283e6a-c3af-11e6-9092-9e2a4d58deed.png)

### **Changes:**
The change I made are very simple, it was a simple case of changing the light bleed value to 0.99 (i did this in shader for testing reasons)
```
    p_max = ReduceLightBleeding(0.99, p_max);
```

### **Remaining issues:**

I'm not sure how to explain the issue so images are the best way forward
![screenshot_fri_dec_16_16_46_59_2016](https://cloud.githubusercontent.com/assets/3044415/21270841/47aa517e-c3b0-11e6-8234-035c13289353.png)

**Comment by cadaver** [comment]
Cool, thank you for improving this. Notice (if you didn't already) also that when using VSM, practically all solid geometry should be shadow casters, otherwise they behave poorly as shadow receivers in the distance compare math, unlike in regular depth shadowmapping.

**Comment by cadaver** [comment]
It looks like one cubemap face is empty, or doesn't shadow compare properly. However at the moment I wouldn't know directly what has gone wrong.

**Comment by dragonCASTjosh** [comment]
Lets hope we get this sorted soon

**Comment by cadaver** [comment]
Thankfully it appears there is an easy fix for the point light faces. The VSM shadow shader calculates z/w in the vertex shader, but for some surfaces this will not be correct in perspective. Instead z/w needs to be calculated in pixel shader. I should be able to commit shortly. This could result in less errors for other light types as well.

**Comment by dragonCASTjosh** [comment]
All issues resolved once light bleed value is changed to 0.9, im not sure if its worth a PR but here is the line. https://github.com/urho3d/Urho3D/blob/master/Source/Urho3D/Graphics/Renderer.cpp#L280
