### ISSUE TITLE
Link Urho3D to library

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1717]
I need an ability on CMake level to do the following:
- Statically link Urho3D to library
- Then statically link this library to executable

I tried different ways to do it, but they all end up with
```
4>Urho3D_d.lib(DataDeserializer.obj) : error LNK2005: "void * __cdecl operator new(unsigned int)" (??2@YAPAXI@Z) already defined in MSVCRTD.lib(new_scalar.obj)
4>Urho3D_d.lib(DataDeserializer.obj) : error LNK2005: "void __cdecl operator delete(void *)" (??3@YAXPAX@Z) already defined in MSVCRTD.lib(delete_scalar.obj)
4>Urho3D_d.lib(SerializedDataIterator.obj) : error LNK2005: "void * __cdecl operator new(unsigned int)" (??2@YAPAXI@Z) already defined in MSVCRTD.lib(new_scalar.obj)
4>Urho3D_d.lib(SerializedDataIterator.obj) : error LNK2005: "void __cdecl operator delete(void *)" (??3@YAXPAX@Z) already defined in MSVCRTD.lib(delete_scalar.obj)
4>D:\Root\Repos\Urho3DEditor\Build\vc15\bin\Urho3DEditorLauncher.exe : fatal error LNK1169: one or more multiply defined symbols found
```
every time when I am trying to do `new Context` from library.

**Update:**
I've changed order of linking libraries and it solved this problem.
Library must be linked before Urho3D.lib
How can I force link order if I use `setup_[main_]executable`?

**Update 2:**
Finally I did this by using
```
define_dependency_libs (Urho3D)
setup_target ()
```

Probably, such usecase need to be documanted better.

**Comment by cadaver** [comment]
Feel free to amend the documentation. @weitjong very likely has better insight than me on this matter, though.

**Comment by weitjong** [comment]
If you look at the ```setup_library()``` macro, it would do this call automatically. See https://github.com/urho3d/Urho3D/blob/5568e5bc8b01f64fa3f6ab7c259c7b04684e1622/CMake/Modules/Urho3D-CMake-common.cmake#L1099-L1105.

I would not advice to update the documentation to call the ```define_dependency_libs()``` explicitly. This macro has been marked as deprecated. In the refactoring branch this macro will be removed all together. The usage of the ```setup_library()``` macro is safe, only its internal implementation will be changed in the future.

**Comment by eugeneko** [comment]
@weitjong 
The problem is that this code is for setting up _executable_:
```
add_executable (Urho3DEditorLauncher ${CMAKE_SOURCE_DIR}/Source/EditorLauncher/Main.cpp)
target_link_libraries (Urho3DEditorLauncher Urho3DEditor)
set (TARGET_NAME Urho3DEditorLauncher)
define_dependency_libs (Urho3D)
setup_target ()
```
So `setup_library()` is inappropriate here

**Comment by weitjong** [comment]
Use ```setup_library()``` for library target and ```setup_executable()``` for executable target (or ```setup_main_executable()``` for executable target with additional resource copying/bundling. Of course, there is nothing wrong to use just standard commands from CMake to setup your own target, but if you do so, you will have to take care a lot of "other things" yourself, especially when you plan to target multiple-platforms.

**Comment by eugeneko** [comment]
I have to call `set (TARGET_NAME Urho3DEditorLauncher)` _between_ `add_executable` and linking Urho. But `setup_executable` do both.

If I change order, I get these starnge link errors.
I actually don't know the exact reason of these errors, but I found some article that explains something similar and a way to solve it.
https://support.microsoft.com/en-us/kb/148652

**Comment by weitjong** [comment]
It has been at least two decades since I last touched any project with MFC, so I cannot help you much there.

**Comment by eugeneko** [comment]
I don't need a help with MFC..
I just need a way to link my library before Urho.lib 
Can I somehow do it without re-implementing `add_executable` on my side?

**Comment by weitjong** [comment]
If I understand your issue correctly then unfortunately there is no easy solution, except modifying the ```setup_executable()``` macro itself for your own need, i.e. insert another command to call the ```target_link_libraries (${TARGET_NAME} LIBS_THAT_MUST_COME_BEFORE_URHO3D)``` in between the ```add_executable()``` and ```define_dependency_libs (Urho3D)```. Then you can set this ```LIBS_THAT_MUST_COME_BEFORE_URHO3D``` variable with a list of library targets like ```Urho3DEditor``` before calling the ```setup_executable()``` macro. It is a bit ugly but it should get the job done.

**Comment by KonstantinTomashevich** [comment]
If I correctly understand issue, you should use `setup_executable ()` macro from Urho3D CMake modules instead of `add_executable ()`.

> 
    Statically link Urho3D to library
    Then statically link this library to executable


In my project I did it this way:
```cmake
# CMakeLists.txt in "Colonization" (library) folder.
set (TARGET_NAME Colonization)
define_source_files (RECURSE)
define_dependency_libs (Urho3D)
setup_library (STATIC)

# CMakeLists.txt in "ColonizationLauncher" (game launcher) folder.
set (TARGET_NAME ColonizationLauncher)
define_source_files (RECURSE)
setup_main_executable ()
target_link_libraries (ColonizationLauncher Colonization)
```

**Comment by eugeneko** [comment]
I have no ideas why I haven't solved this issue two months ago, but now this works fine for me:

```
set (SOURCE_FILES ${CMAKE_SOURCE_DIR}/Source/EditorLauncher/Main.cpp ${RESOURCES})
set (TARGET_NAME Urho3DEditorLauncher)
setup_main_executable ()
target_link_libraries (Urho3DEditorLauncher Urho3DEditor)
```
