### ISSUE TITLE
Anisotropic filter shouldn't be mutually exclusive with other filters

### ISSUE THREAD

**Issue by axredneck** [urho3d/Urho3D#1718]
According to http://urho3d.wikia.com/wiki/Texture we can select anisotropic filter **instead of** other filters. But some engines (e.g. GZDoom or EDuke32) can even use anisotropic filter **together with** "nearest" filter: https://www.dropbox.com/s/j0cdb6xyi3wmqcg/doom.jpg?dl=0

**Comment by cadaver** [comment]
Implementing anisotropy control completely separately would be API breakage, but a new enum value for anisotropic+nearest would be rather easily doable.

**Comment by cadaver** [comment]
Got this working on OpenGL fine. On D3D I see only a minor change and not a large increase in sharpness as one would expect. Will require closer investigation.

**Comment by cadaver** [comment]
D3D11 is not going to work in any case. Got D3D9 to work on at least a NVIDIA GPU, but the API usage may be nonstandard (different min & max filters). OpenGL seems to work most reliable.

**Comment by axredneck** [comment]
Great work! Now it works on OpenGL!
