### ISSUE TITLE
Incorrectly generated Urho3DAll.h when compiling the engine in its root folder.

### ISSUE THREAD

**Issue by Inoc4** [urho3d/Urho3D#1720]
If you create a file .sln solutions and compile engine in its root folder, the file Urho3DAll.h is generated incorrectly.
For example in Cmd:
cmake_vs2015.bat D:\my\Urho3D\Urho3D-master -DURHO3D_OPENGL=1 -DURHO3D_SAMPLES=0
When you later compile your own game project, errors link occures. If in the file Urho3DAll.h comment out the line librevision.h,
```
...
#include <Urho3D/Urho2D/Urho2D.h>
#endif
#include <Urho3D/Urho3D.h>
#include <Urho3D/librevision.h> // error LNK2005
// #include <Urho3D/librevision.h> //no error

#include <Urho3D/DebugNew.h>

using namespace Urho3D;
```
then the compilation proceeds without errors.

**Comment by weitjong** [comment]
Confirmed it is a bug.
