### ISSUE TITLE
mac window navigation

### ISSUE THREAD

**Issue by adekto** [urho3d/Urho3D#1723]
on mac the window pane is rendered very poorly

![unnamed](https://cloud.githubusercontent.com/assets/2915947/21405854/ad575d52-c7c8-11e6-8b0c-94249ccf8b4e.png)

**Comment by weitjong** [comment]
It might be related to #1252 and #1371. Try enable the high dpi mode manually.

**Comment by adekto** [comment]
there is no change
`engineParameters_["HighDPI"] = true;`

**Comment by JoshEngebretson** [comment]
What version of OSX?  Try adding this to the app plist:

```xml
    <key>NSHighResolutionCapable</key>
    <true/>
```

**Comment by adekto** [comment]
yes this seem to work, however i noticed that in full screen, high dpi mode seems to give me a black screen.
using Borderless work fine  but the os navigation bar and dock seem to be overlay
![unnamed](https://cloud.githubusercontent.com/assets/2915947/21432136/682646c4-c86a-11e6-8f5d-6a84e0c32a84.png)
