### ISSUE TITLE
Some plug-in system? (feature request)

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1724]
In cryengine user's code compiled in separate dll, that can by loadede by sandbox (Editor) and by game launcher. So if user write own class in c++, he can edit own project in editor, use own classes, run project and it will be work.

In urho currently if user add own class to game project, he can not use it in edior. It should be added to modified version of engine. 

It would be convenient, that user can compile own game to dll and use it with standart version of engine

**Comment by 1vanK** [comment]
Or maybe just add some user library. Engine compiled to urho3d.dll, userclass compiled to custom.dll, then Game.exe and Urhoplayer.exe load both libraries when run

**Comment by cadaver** [comment]
There are differences in philosophy. At its root, Urho is a library for running a rendering/simulation loop and it doesn't care what application is attached to it, or how it's being used. For an advanced user Urho3DPlayer's functionality should be trivial and can be easily replicated in a larger program that is attaching custom functionality, components and subsystems to Urho. In that case you'd also be running the editor under that larger program.

It is fairly trivial to implement a Win32 / Unix plugin system, this was already done in https://github.com/realXtend/tundra-urho3d and it takes maybe about a hundred lines of code. Doing it in Urho itself may carry the expectation of more platforms being supported. In general I'm not a fan of changing the Urho library's role as such that a game dll would be mandated or that the library itself would be searching for it.
