### ISSUE TITLE
playing a footstep sound on a fixed periodic timer tends to slip/overlap

### ISSUE THREAD

**Issue by Lumak** [urho3d/Urho3D#1726]
I first noticed this when I created a footstep sound on a characters and noticed that the sound was not periodic as expected; sometimes it was then it slip/overlap then periodic, and repeat.  For ease of verifying this bug I modified the 14_SoundEffects to play a sound on a periodic, 300 msec timer.  You'll notice when the duration goes over 100 msec or when it hits 5 msec that the sound becomes non-periodic.

You can also hear this slip/overlap in this guys video - https://www.youtube.com/watch?v=Tonig94XWsY

[14_SoundEffects.zip](https://github.com/urho3d/Urho3D/files/671399/14_SoundEffects.zip)

**Comment by Lumak** [comment]
What's more obvious is that it sounds like it plays:
`1-2-3-4-pause-1-2-3-pause-1-2-3-4-pause, etc`
I don't think I should be able hear the pauses on a fixed periodic timer.

**Comment by Lumak** [comment]
From the video, the attached wavefile is what I mean by slip/overlap or out of sync at 1.871 secs.

[footstepoutofsync.zip](https://github.com/urho3d/Urho3D/files/672305/footstepoutofsync.zip)

**Comment by cadaver** [comment]
Could be related to SDL's internal granularity in audio processing, meaning when it calls the Urho's audio callback. There are some adjustment possibilities, but it will also depend on the audio driver SDL is using. Which OS are you on?

**Comment by Lumak** [comment]
Mine is on Windows 10, so DX sound.

**Comment by cadaver** [comment]
OK, what I see happening is that SDL gives me a buffer of 4096 samples (which is actually calculated & requested by the Audio class), then each mix request also is 4096 samples. Would be preferable to have multiple smaller buffer fragments, since that would mean the audio timing granularity is about 100ms at 44.1 kHz.

**Comment by cadaver** [comment]
Yeah. It seems there is no other control than the buffer size (power of two) you specify to the SDL requested AudioSpec when opening the audio device. So I'd recommend trying to halve the engine's audio buffer size from 100ms to 50ms, which will also improve the timing granularity 2x. The default setting is rather conservative to avoid dropouts.

SDL also offers the QueueAudio mechanism which was referenced in another issue some time ago if I remember right, that will also be worth looking into in the future.

**Comment by Lumak** [comment]
Thanks for looking into this.

From my testing, if:
`engineParameters_["SoundBuffer"] <= 30`

the playerFistHit sound plays at a fixed interval.  Not a bug, just a setting.
