### ISSUE TITLE
Errors generating Lua bindings on MinGW

### ISSUE THREAD

**Issue by JTippetts** [urho3d/Urho3D#1727]
Doing a fresh build on a new Win10 laptop.

Checked out latest source and invoked MinGW build with:

cmake_mingw.bat ../Urho3D-GL -DURHO3D_OPENGL=1 -DURHO3D_LUAJIT=1 -DURHO3D_64BIT=1 -DMINGW_SYSROOT="C:\Program Files\mingw-w64\x86_64-6.2.0-posix-seh-rt_v5-rev1\mingw64"

Configuration process works as expected, but build fails upon calling tolua++ to generate the binding code for the LuaScript module. Fails on every module (Audio, etc...) with errors similar to:

http://pastebin.com/idrfbrLA

All attempts to generate the Lua bindings fail in this fashion, and compilation fails when attempting to build the LuaScript generated files since they don't exist.

Edit: Looks like the problem only exists for the LuaJIT build. Building with vanilla Lua works okay.

**Comment by JTippetts** [comment]
This seems to be an issue with MinGW gcc 6.2.0, as reverting to a gcc 5.4.0 build, everything works fine.

**Comment by weitjong** [comment]
I am not able to reproduce this issue with MinGW 6.3.0. Tested on AppVeyor.
