### ISSUE TITLE
Update AngelScript

### ISSUE THREAD

**Issue by alex-rass-88** [urho3d/Urho3D#1728]
AngelScript 2.31.2 released.
Fixed bug with saved byte code not being portable between 32bit and 64bit platforms.
And more...
http://angelcode.com/angelscript/changes.php

**Comment by cadaver** [comment]
Yes, this is long overdue. It will bring some API changes and require going over the arrays / dictionarys again, but nothing in Urho API should change.

**Comment by cadaver** [comment]
Being worked on in update-angelscript branch.

**Comment by cadaver** [comment]
AngelScript branch (which updates to 2.31.2) merged.
