### ISSUE TITLE
(feature request) Variant::GetTypeFromName to AngelScript

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1730]
```
// Register static class member as global method in namespace
engine->SetDefaultNamespace("Variant");
engine->RegisterGlobalFunction("VariantType GetTypeFromName(const String&in)", asFUNCTIONPR(Variant::GetTypeFromName, (const String&), VariantType), asCALL_CDECL);
engine->SetDefaultNamespace("");
```

In AngelScript it can be used:
```
Variant::GetTypeFromName(string");
```
May be use this way for other static members?
Vector::ZERO, Color::WHITE etc

**Comment by iSLC** [comment]
Wouldn't the namespace conflict with the actual class type?

```
engine->RegisterObjectType("Variant", sizeof(Variant), asOBJ_VALUE | asOBJ_APP_CLASS_CDAK);
```

**Comment by 1vanK** [comment]
```
        inputPort.dataType_ = Variant::GetTypeFromName(inputPortElem.GetAttribute("dataType"));
        Variant x = Variant();
```

not generate any errors

**Comment by iSLC** [comment]
Oh I see. From what I could gather, the class name is actually a namespace. Which is why this seems to work.

**Comment by iSLC** [comment]
So that mean you can register [property accessors](http://www.angelcode.com/angelscript/sdk/docs/manual/doc_script_class_prop.html#doc_script_class_prop_index) as global methods to emulate static member variables. Like you mentioned initially.

**Comment by cadaver** [comment]
The existing API doesn't use namespaces so far, so will do this also without, so they're going to be GetVariantTypeName() & GetVariantTypeFromName(). 

Using namespaces would be smart for the static member vars though.

At some point perhaps the API could be cleaned of globals registered to the main namespace, e.g. Graphics::GetRGBAFormat() and such could be actually put into Graphics namespace. However that'd be large-scale API breakage.

**Comment by 1vanK** [comment]
We can mark old method as obsolete and add new functions in namespaces

**Comment by cadaver** [comment]
Duplicate registration of API would cause startup time and exe size increase though.
