### ISSUE TITLE
UI_ROOT->SetLayoutMode(LM_VERTICAL) error

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1738]
```
void CreateUI()
{
    Window* fullScreenElement = UI_ROOT->CreateChild<Window>();
    UI_ROOT->SetLayoutMode(LM_VERTICAL);
}
```
 No error.

```
void CreateUI()
{
    UI_ROOT->SetLayoutMode(LM_VERTICAL);
    Window* fullScreenElement = UI_ROOT->CreateChild<Window>();
}
```
or just
```
void CreateUI()
{
    UI_ROOT->SetLayoutMode(LM_VERTICAL);
}
```
Division by zero
![2](https://cloud.githubusercontent.com/assets/13021826/21579798/d9ca0c64-cfd3-11e6-90e3-c9701c1960c4.png)

**Comment by cadaver** [comment]
Should be trivially fixable, though I don't think it's a good idea to set a layout mode to the UI root element; if you have a software cursor it will be parented to the root.

**Comment by 1vanK** [comment]
> Should be trivially fixable, though I don't think it's a good idea to set a layout mode to the UI root element; if you have a software cursor it will be parented to the root.

Hm, you're right. Ok AnchorMin(0, 0) and AnchorMax(1, 1) for ivisible container is better idea, I think

**Comment by cadaver** [comment]
Yes, you can always create your own "sub-root" which is whole screen sized and would essentially behave like the root, but doesn't suffer from the assumptions of the actual root element.
