### ISSUE TITLE
[Feature Request] Allow to define vector structs for editor for external components.

### ISSUE THREAD

**Issue by KonstantinTomashevich** [urho3d/Urho3D#1741]
In Urho3DEditor, editing of structures such as animation states (in AnimatedModel) and billboards (in BillboardSet) implemented using special vector structs (See lines 1490-1579 in Scripts/Editor/AttributeEditor.as). This mechanism works fine for engine components, but it can't be used for external components (special game components, Unit for example). In my opinion, it will be good to move this structures definitions into AttributeInfos (for easy defining them in external components).

**Comment by cadaver** [comment]
In general, you should not take the editor as some immutable piece of code; quite natural approach would be to just be running your customized editor with your customized attribute structs.

However you're right it would be preferable to do this at the component definition, if we find a good way to do it. Possibly it doesn't need to be anything else than a vector of strings that is optionally filled.

**Comment by KonstantinTomashevich** [comment]
Yes, Now I'm trying to implement it in my fork.

**Comment by cadaver** [comment]
With the AngelScript API functions GetObjectCategories() and GetObjectsByCategory(), defined in SceneAPI.cpp.

**Comment by KonstantinTomashevich** [comment]
Thanks!
