### ISSUE TITLE
Font->SaveXml() crash

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1746]
Possible it is not correct using, but it cause crash
```
Font* font = GetSubsystem<ResourceCache>()->GetResource<Font>("Fonts/Anonymous Pro.ttf");
File file(context_, "TestResult", FILE_WRITE);
font->SaveXML(file, 100, true); // Crach - nullptr texture
//font->SaveXML(file, 100); // No crash, perfect works
```

**Comment by cadaver** [comment]
Save is only intended to work for bitmap fonts, however it shouldn't crash.

**Comment by cadaver** [comment]
Was possibly an untested codepath, since it was pushing image ptrs to an already sized vector, leading to nullptrs being mixed with non-null images.
