### ISSUE TITLE
Colored Bitmap Fonts (Feature request)

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1750]
Bitmap Fonts can contains color information, so it would be good to change Text shader:
```
void PS()
{
#ifdef SIGNED_DISTANCE_FIELD
    ...
#else
    // Non-SDF font will likely be monochrome, in which case the alpha channel will be on the R channel on OpenGL 3
    //#ifdef GL3
    //    gl_FragColor.a = vColor.a * texture2D(sDiffMap, vTexCoord).r;
    //#else
    //    gl_FragColor.a = vColor.a * texture2D(sDiffMap, vTexCoord).a;
    //#endif
    
    // Added
    gl_FragColor = texture2D(sDiffMap, vTexCoord) * vColor;
#endif
}
```

![2](https://cloud.githubusercontent.com/assets/13021826/21740627/47ce18ee-d4d0-11e6-95cb-965375b973be.png)

![2 -](https://cloud.githubusercontent.com/assets/13021826/21740629/4d538808-d4d0-11e6-87f3-2f21bea34e28.png)

**Comment by 1vanK** [comment]
Or add some additional defines for textures with different count of color channels

**Comment by 1vanK** [comment]
Or force to use "Basic" shader for colored Bitmap fonts

**Comment by cadaver** [comment]
Looks like Text3D needs the same shader selection logic based on texture format, as UI does.
