### ISSUE TITLE
(Feature request) XMLFile->GetOrCreateRoot(), XMLElement->GetOrCreateChild()

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1756]
I supplement final XMLFile from different places of program and I think it would be nice to have functions XMLFile->GetOrCreateRoot() and XMLElement->GetOrCreateChild()

**Comment by eugeneko** [comment]
What if XML has root 'aaa' and I asked to get or create root 'bbb'?

**Comment by 1vanK** [comment]
I think, if user request root "bbbb" should be created root "bbbb", but need output warning to log

**Comment by 1vanK** [comment]
currently it drop

**Comment by 1vanK** [comment]
Cool! Thank you!
