### ISSUE TITLE
[Feature request] SSAO support

### ISSUE THREAD

**Issue by kkimdev** [urho3d/Urho3D#1757]
I've read a few SSAO articles and found some good papers:

Optimizations:
- http://wili.cc/research/lsao/
- http://graphics.cs.williams.edu/papers/SAOHPG12/

State of the art:
- http://iryoku.com/downloads/Practical-Realtime-Strategies-for-Accurate-Indirect-Occlusion.pdf

**Comment by cadaver** [comment]
Contributions are welcome. I'm not sure if an universally good (ie. agnostic to the scene scale and content being presented) and performant implementation can be done. On the engine code side nothing should hopefully be missing, so it just needs a suitable shader. Either reading depth only, or depth+normals.

**Comment by kkimdev** [comment]
Yeah, I'm not too sure if it can be universally good, but on the performance side, the line-sweep algorithm (the first link) improved HBAO by x10~x20 so I think we can be optimistic.  I would love to contribute if I can find time, but I'm not sure when it will be.

Throwing another link for reference https://software.intel.com/en-us/articles/adaptive-screen-space-ambient-occlusion .  This looks a solid implementation with permissive license, though it doesn't employ the line-sweep optimization (just asked the author if it's applicable).

**Comment by cadaver** [comment]
If no-one else gets it done first, you're welcome to contribute even if it takes time. I will possibly research this too at some point, but no hard promises.

**Comment by 1vanK** [comment]
> http://graphics.cs.williams.edu/papers/SAOHPG12/

It looks very bad on video :(

**Comment by hdunderscore** [comment]
There have been some shared SSAO shaders on the forums, but no pull requests. They can still be useful as a starting point if you are looking for an improved version.

**Comment by Hevedy** [comment]
So how is going this ?
