### ISSUE TITLE
Jill seems to have wrong bounding box

### ISSUE THREAD

**Issue by weitjong** [urho3d/Urho3D#1761]
![screenshot from 2017-01-14 11-33-07](https://cloud.githubusercontent.com/assets/5548048/21952056/5ac6e6f6-da4d-11e6-8c95-d813a802bf6c.png)

**Comment by 1vanK** [comment]
Hm, model without animation has normal BB
![2](https://cloud.githubusercontent.com/assets/13021826/21953485/dd98afb4-da49-11e6-8f29-7871cf763d28.png)

**Comment by 1vanK** [comment]
Reexportig with latest version https://github.com/reattiva/Urho3D-Blender and enabled "clamp bones BB" not helped me

**Comment by cadaver** [comment]
Fixed by 1vanK's PR.
