### ISSUE TITLE
Some bugs in water sample.

### ISSUE THREAD

**Issue by KonstantinTomashevich** [urho3d/Urho3D#1764]
I found 2 bugs in water sample.
1. If camera goes under water plane, water effect disappears. See picture.
![First picture](https://cloud.githubusercontent.com/assets/19854474/21962790/e870d9d2-db36-11e6-94c9-fcc9ce3c7507.png)

2. Emscripten only. Strange bug, see picture bellow.
![Second picture](https://cloud.githubusercontent.com/assets/19854474/21962791/e8a57a48-db36-11e6-8363-cd88e3c2c9c1.png)

**Comment by 1vanK** [comment]
> If camera goes under water plane, water effect disappears. See picture.

underwater should be another effact and shader

**Comment by cadaver** [comment]
These are known limitations. Clipping plane is not supported on WebGL / GLES2, which it would require to function properly. Wontfix for now.
