### ISSUE TITLE
AngelScript ScriptFile Class Crashes in Mingw (Mingw-w64) Release build

### ISSUE THREAD

**Issue by BlueMagnificent** [urho3d/Urho3D#1765]
I noticed this a while back but couldn't investigate at that moment. 
Traced it down later to discover that the issue is somewhat related to ScriptFile class as is evident in Urho3DPlayer application. This mainly occurs when a subsystem is accessed through script hence the reason why there is no crash in 21_AngelScriptIntegration since the scriptfile does not access any subsystem.

The biggest puzzle is that this crash does not surface in debug build.

I tried using the barest minimally configured build setting with the default provided mingw build batch file 
`cmake_mingw.bat <my_build_directory> -DURHO3D_PACKAGING=1  -DCMAKE_INSTALL_PREFIX=<my_installation_directory>`
and still the crash was there.

My system is 64bit Windows10 OS with 8gb of ram, the MinGW setup is i686-5.1.0-posix-dwarf-rt_v4-rev0 .

**Comment by cadaver** [comment]
I think you've come across a "bad" version of MinGW. Don't think there's an actual systematic error in ScriptFile or subsystem access with AngelScript, as it should have manifested earlier and across many compilers. Will be worth checking how newer versions of MinGW behave, and how the AngelScript update (which should hopefully be soon) will behave.

**Comment by BlueMagnificent** [comment]
When I compile with VC++ the issue does not surface. 
Below are the list of Mingw-w64 installations I have, all of them experiences this issue:
i686-5.1.0-posix-dwarf-rt_v4-rev0
i686-5.2.0-posix-dwarf-rt_v4-rev0
i686-5.3.0-posix-dwarf-rt_v4-rev0
i686-5.4.0-posix-dwarf-rt_v5-rev0
i686-6.2.0-posix-dwarf-rt_v5-rev1

**Comment by cadaver** [comment]
OK, then it looks that newer GCC indeed starts to fail systematically.

**Comment by cadaver** [comment]
You should be able to work around with -DURHO3D_SSE=0. I believe this is an AngelScript syscall stack alignment issue still, which we used to have trouble with before.

**Comment by BlueMagnificent** [comment]
Will check it out right away

**Comment by BlueMagnificent** [comment]
:) -DURHO3D_SSE=0 did the trick, so unfortunate I keep running into this issue, lol .

Let me investigate one more earlier version of MinGW before closing this issue.

**Comment by cadaver** [comment]
I think the issue should be kept open, because Urho build should not require custom settings to not crash. (the nuclear option would be to force URHO3D_SSE 0 on MinGW newer versions in Urho CMake code)

**Comment by weitjong** [comment]
Not just yet. If the SSE is confirmed to be the culprit then the issue is perhaps with the vectorization optimisation. In the first post of the issue, it is also confirmed that debug build (no optimisation) didn't cause the crash. So, I believe we should investigate whether we can check what is now being optimised in the newer MinGW and fine-tuned it.

**Comment by cadaver** [comment]
I think you have had bad luck in crashing versions. It can't be said that a high GCC version alone with SSE on == AngelScript crash.

Just used MinGW x86_64-posix-seh-rev0 6.3.0 to build with SSE on, no crash.
Also i686-posix-dwarf-rev0 5.3.0, no crash.

**Comment by weitjong** [comment]
In case I have time later to reproduce the issue, which sample app or which step should I use to crash it realibly?

**Comment by cadaver** [comment]
Anything AngelScript. I've used 08_Decals.

**Comment by BlueMagnificent** [comment]
just as cadaver said anything angel script and as I noted earlier above it can easily be pinpointed to accessing a subsystem from script

**Comment by cadaver** [comment]
Now I think I understand why x86_64 6.3.0 worked. It actually defaults to a 64-bit build. So it would seem that the combo of high GCC version, 32-bitrelease build / SSE on, and using AngelScript calls causes the crash.

**Comment by weitjong** [comment]
Finally I managed to setup a new MinGW-CI build on AppVeyor to reproduce the error reliably. It should help to fix this issue and also to detect any potential future issues. Besides anything AS, it looks like the native 32-bit PBRMaterials crashed as well.

**Comment by weitjong** [comment]
Just tested 4.9.2 on AppVeyor and no crashes for 32-bit build. Next, to find what has changed in newer MinGW version.

**Comment by cadaver** [comment]
My guess (could be wrong though) is that the -mstackrealign option that we use to force stack alignment for function entry is no longer operational in newer version.

For a reminder, this is the old article I found on it:
http://www.peterstock.co.uk/games/mingw_sse/

**Comment by weitjong** [comment]
Fortunately it was something simpler :)
