### ISSUE TITLE
Cardboard Support

### ISSUE THREAD

**Issue by mgatelabs** [urho3d/Urho3D#1769]
I haven't tried to implement Urh03D yet, but i'm looking for a Android compatible library that is similar to Apple SceneKit so I can re-implement my popular native(Obj-C, SceneKit, OpenGl 2.0) iOS Google Cardboard app for Android.  I know I could use Unity, but Unity is overkill for a vr video player app.  Would Urh03D suffice to display unlit 3d geometry with images/videos textures, multiple cameras (with geometry just for one camera), and perform hit testing?

In the past I successfully use SceneKit + OpenGl 2.0 to create a Google Cardboard app on iOS without Unity or Google Cardboard, everything is native.  So I think Urh03D would also work, but I would need to do a similar thing, which is render the left eye to a target texture and then restart and render the right eye and hit test to detect looking at 3d icons.

**Comment by cadaver** [comment]
Rendering to multiple render textures with different cameras is supported.

The hardware camera is not supported by Urho API, so you would need your own native Android code.
