### ISSUE TITLE
Implement Graphics::GetMultiSampleLevels() for OpenGL

### ISSUE THREAD

**Issue by Enhex** [urho3d/Urho3D#1774]
Currently OpenGL's `Graphics::GetMultiSampleLevels()` doesn't detect supported MSAA levels.

http://stackoverflow.com/a/9317953
and
http://nehe.gamedev.net/tutorial/fullscreen_antialiasing/16008/
suggest it's possible to detect supported level by trying to set a level, and then get it and see if you got what you originally set.
I tried it and it works, but I used `Graphics::SetMode()` which recreates the window which is ugly.

```C++
PODVector<int> Graphics::GetMultiSampleLevels()
{
	PODVector<int> ret;
	// No multisampling always supported
	ret.Push(1);

	auto original_level = multiSample_;

	// Try to set different sample levels and see if they work
	// Keep adding levels until the returned level isn't equal to the last level
	int returned_level = 1;
	int last_level = 1;
	for (int level = 2; returned_level == last_level; level *= 2)
	{
		last_level = level;

		SetMode(width_, height_, fullscreen_, borderless_, resizable_, highDPI_, vsync_, tripleBuffer_, level);
		SDL_GL_GetAttribute(SDL_GL_MULTISAMPLESAMPLES, &returned_level);

		if (returned_level == level)
			ret.Push(level);
	}

	// Restore original level
	SetMode(width_, height_, fullscreen_, borderless_, resizable_, highDPI_, vsync_, tripleBuffer_, original_level);

	return ret;
}
```

Perhaps there's a way to  set & get without re-creating the window.

In addition, `SetMode()` seems to have arbitrary max limit of 16 MSAA.
If it is arbitrary, I think it should be left to the user to decide if and how much to limit.

**Comment by Enhex** [comment]
I found suggestion creating a dummy context or perhaps creating something other than a context that can be configured with MSAA to check if it's supported.

**Comment by cadaver** [comment]
At least on Windows, you can set GL multisample level only once for an OS-level window, that's why the window is intentionally recreated. It might be possible to check for a multisample framebuffer's completeness, but it's not necessarily the same as backbuffer. One possibility is to open invisible windows at startup, before opening the real window.

**Comment by cadaver** [comment]
Couldn't get the temp window + temp context method to work; for me  SDL_GL_GetAttribute(SDL_GL_MULTISAMPLESAMPLES) would always return 0, at least on an Intel GPU. So just added a query for the maximum level, and assume the lesser levels are supported.

**Comment by Enhex** [comment]
If they aren't supported it can cause a black screen
