### ISSUE TITLE
(Feature request) Update FreeType

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1775]
In my font generator I am using FreeType library directly and I had a problem - I could not debug the project from Visual Studio (when I press F5 I recieve access error some within FreeType lib), but compiled and runned *.exe worked perfect. So I just ignored the problem.

Today I replaced FT_Set_Char_Size (set font size in points) to FT_Set_Pixel_Sizes (set font size in pixels) and FT_Glyph_Stroke stopped working correctly.

I updated FreeType lib to 2.7.1 version (just replace files and recompile engine) and it solved both problems

**Comment by cadaver** [comment]
It would be a good idea to update, but the ttf hinting changed in the later versions to be quite ugly looking, at least with Urho's default used fonts. Will have to re-check at some point.

**Comment by 1vanK** [comment]
I do not seee difference but it possible to enable old "v35" interpreter 

https://www.freetype.org/freetype2/docs/reference/ft2-tt_driver.html#interpreter-version

**Comment by cadaver** [comment]
I just did the same as you (update-freetype branch), everything at least in the editor looks good to me. Will just have to see how the CI builds go, as I just overwrote all our own customizations due to some past failures on some platforms.

**Comment by cadaver** [comment]
Branch merged to master.

**Comment by 1vanK** [comment]
Cool! Thank you!
