### ISSUE TITLE
Texture appears as black on Web

### ISSUE THREAD

**Issue by abdllhbyrktr** [urho3d/Urho3D#1776]
Hi, I attempted to add the following texture on a diffuse material. I always get a dark model when applying for it.

DiffuseMaterial.xml
```xml
<?xml version="1.0"?>
<material>
	<technique name="Techniques/Diff.xml" />
	<texture unit="diffuse" name="Textures/BARK5.jpg" />
	<parameter name="MatSpecColor" value="0 0 0 1" />
</material>
```

![bark5](https://cloud.githubusercontent.com/assets/11297739/22171622/72090504-df9a-11e6-9088-574cc2212b35.jpg)

**Comment by abdllhbyrktr** [comment]
These screenshots captured on web platform. Two different materials, two different results in the scene.

```xml
<?xml version="1.0"?>
<material>
	<technique name="Techniques/Diff.xml" quality="0" loddistance="0" />
	<texture unit="diffuse" name="Textures/BARK5.jpg" />
</material>
```
![image](https://cloud.githubusercontent.com/assets/11297739/22172107/7a897a4e-dfa7-11e6-93d9-a32a8a363c8b.png)

```xml
<?xml version="1.0"?>
<material>
	<technique name="Techniques/Diff.xml" quality="0" loddistance="0" />
	<texture unit="diffuse" name="Textures/Jack_face.jpg" />
</material>
```
![image](https://cloud.githubusercontent.com/assets/11297739/22172122/0bb888de-dfa8-11e6-85ac-2a69077d405a.png)

**Comment by weitjong** [comment]
Your texture size is non power-of-two.

**Comment by abdllhbyrktr** [comment]
I feel really stupid. I did not know that. Thank you so much!

**Comment by 1vanK** [comment]
> Your texture size is non power-of-two.

Is this limitation only for the browser? Currently I'm working on SDF calculation on GPU and use textures with non standart sizes (17x15, etc) and I do not see any problems

**Comment by weitjong** [comment]
It is a limitation of the WebGL and OpenGLES, at least on their earlier versions.

**Comment by gogoprog** [comment]
If you really need non-power-of-two textures you'll have to disable mipmapping and texture repeating.

See https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Using_textures_in_WebGL
