### ISSUE TITLE
possible GeometryType geometry enum bug

### ISSUE THREAD

**Issue by YarikTH** [urho3d/Urho3D#1778]
When I serfed in Urho code, I found that GeometryType enum declared on Graphics/GraphicsDefs.h:51 seems broken.

/// %Geometry type.
enum GeometryType
{
    GEOM_STATIC = 0,
    GEOM_SKINNED = 1,
    GEOM_INSTANCED = 2,
    GEOM_BILLBOARD = 3,
    GEOM_DIRBILLBOARD = 4,
    GEOM_TRAIL_FACE_CAMERA = 5,
    GEOM_TRAIL_BONE = 6,
    GEOM_STATIC_NOINSTANCING = 7,
    MAX_GEOMETRYTYPES = 7,
};

MAX_GEOMETRYTYPES value is equal to the prev value, but it is obviously wrong. MAX_GEOMETRYTYPES must be 8 or must be left unassigned. I searched for another enum bugs like this, but fortunately in other enums last "MAX_*" is value left unassigned.

**Comment by 1vanK** [comment]
It is not real type. Later it replaced to GEOM_STATIC:

```
        if (batch.geometryType_ == GEOM_STATIC_NOINSTANCING)
            batch.geometryType_ = GEOM_STATIC;
```

but I do not know why

**Comment by 1vanK** [comment]
May be it depreacate instancing for geometry

**Comment by weitjong** [comment]
I concur with OP, the enum declaration looks wrong. I don't believe it is a deprecated enum, in fact they are one of the newly added. It can be easily from the commit history.

Using following command to double check, I concur that only this enum declaration looks different than the rest.
```
$ git grep -P -B1 '^\s*MAX_\w+(?:\s+=|\n|^M)' -- Source/Urho3D/**/*.h
```

**Comment by eugeneko** [comment]
IMO the last _fake_ enum shan't be counted because `MAX_GEOMETRYTYPES` is used for iterating over _real_ enum values in `Renderer.cpp` and there are arrays with 7 elements. Simple replacement 7 with 8 looks inacceptable.
```
enum GeometryType
{
GEOM_STATIC = 0,
GEOM_SKINNED = 1,
GEOM_INSTANCED = 2,
GEOM_BILLBOARD = 3,
GEOM_DIRBILLBOARD = 4,
GEOM_TRAIL_FACE_CAMERA = 5,
GEOM_TRAIL_BONE = 6,
MAX_GEOMETRYTYPES = 7,
GEOM_STATIC_NOINSTANCING = 7,
};
```

**Comment by cadaver** [comment]
Putting MAX_GEOMETRYTYPES before NOINSTANCING looks good. Also a comment describing that the last one is not "real" for VS variations will not hurt.
