### ISSUE TITLE
CollisionShape::SetTriangleMesh does not work

### ISSUE THREAD

**Issue by SuperWangKai** [urho3d/Urho3D#1779]
It seems **SetTriangleMesh** cannot work properly.
for a quick test: 

1. add **mass = 1** to the mushrooms, and they will just fall down off the terrain.
2. change **SetTriangleMesh** to **SetConvexHull**, they sit still on the terrain.

so in this test, **SetConvexHull works but SetTriangleMesh fails**.

**Comment by 1vanK** [comment]
Use SetTriangleMesh only for levels because collision TriangleMesh + TriangleMesh is very heavy brutforce (and disabled currently it seems).

**Comment by SuperWangKai** [comment]
@1vanK I wonder where is the switch to toggle on the collision, at least, I can test some prototype.

**Comment by eugeneko** [comment]
> This performance concern is not aways rational

Okay, here is another concern. Concave-vs-concave collision cannot be precisely solved in general case.
It can be solved in _some_ way without any quality guarantees.
Bullet physics support trimesh-vs-trimesh collision by `btGImpactMeshShape` but I am unsure that Urho have a facade for this. Urho's trimesh is probably `btBvhTriangleMeshShape` that is designed to be static.

**Comment by 1vanK** [comment]
> I wonder where is the switch to toggle on the collision?

I dont know, but Blender also used Bullet and there TriangleMesh + TriangleMesh (and it is really SLOW)

**Comment by cadaver** [comment]
Trimesh is not currently intended to be movable, so what you see is completely expected. Separate issue can be opened for btGImpactMeshShape, if desired.

**Comment by SuperWangKai** [comment]
OK, I see now, thanks guys.
Maybe I can use tools like blender and python script to generate collision shapes (box/sphere/Cone... ) with correct dimesions.
