### ISSUE TITLE
Build on linux use cmake command, but all not found

### ISSUE THREAD

**Issue by lishulei3389** [urho3d/Urho3D#1785]
Build on linux use cmake command, but all not found.
$uname -a
Linux K26 4.4.0-45-generic #66~14.04.1-Ubuntu SMP Wed Oct 19 15:05:38 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$git cone https://github.com/urho3d/Urho3D
...
$cd Urho3D
$mkdir build
$cd build
$cmake --version
cmake version 2.8.12.2
$cmake ..
-- Found Readline: /usr/lib/x86_64-linux-gnu/libreadline.so  
-- Looking for include file stdint.h
-- Looking for include file stdint.h - not found
-- Performing Test HAVE_GCC_WALL
-- Performing Test HAVE_GCC_WALL - Failed
-- Performing Test HAVE_GCC_WDECLARATION_AFTER_STATEMENT
-- Performing Test HAVE_GCC_WDECLARATION_AFTER_STATEMENT - Failed
-- Performing Test HAVE_GCC_ATOMICS
-- Performing Test HAVE_GCC_ATOMICS - Failed
-- Performing Test HAVE_GCC_SYNC_LOCK_TEST_AND_SET
-- Performing Test HAVE_GCC_SYNC_LOCK_TEST_AND_SET - Failed
-- Performing Test HAVE_GCC_PREFERRED_STACK_BOUNDARY
-- Performing Test HAVE_GCC_PREFERRED_STACK_BOUNDARY - Failed
-- Performing Test HAVE_GCC_WSHADOW
-- Performing Test HAVE_GCC_WSHADOW - Failed
-- Performing Test HAVE_NO_UNDEFINED
-- Performing Test HAVE_NO_UNDEFINED - Failed
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - not found
-- Looking for clock_gettime in c
-- Looking for clock_gettime in c - not found
-- Looking for sys/types.h
-- Looking for sys/types.h - not found
-- Looking for stdio.h
-- Looking for stdio.h - not found
-- Looking for stdlib.h
-- Looking for stdlib.h - not found
-- Looking for stddef.h
-- Looking for stddef.h - not found
-- Looking for stdarg.h
-- Looking for stdarg.h - not found
-- Looking for malloc.h
-- Looking for malloc.h - not found
-- Looking for memory.h
-- Looking for memory.h - not found
-- Looking for string.h
-- Looking for string.h - not found
-- Looking for strings.h
-- Looking for strings.h - not found
-- Looking for inttypes.h
-- Looking for inttypes.h - not found
-- Looking for ctype.h
-- Looking for ctype.h - not found
-- Looking for math.h
-- Looking for math.h - not found
-- Looking for iconv.h
-- Looking for iconv.h - not found
-- Looking for signal.h
-- Looking for signal.h - not found
-- Looking for 8 include files stdint.h, ..., dlfcn.h
-- Looking for 8 include files stdint.h, ..., dlfcn.h - not found
-- Looking for M_PI
-- Looking for M_PI - not found
-- Looking for sys/mman.h
-- Looking for sys/mman.h - not found
-- Looking for strtod
-- Looking for strtod - not found
-- Looking for malloc
-- Looking for malloc - not found
-- Looking for calloc
-- Looking for calloc - not found
-- Looking for realloc
-- Looking for realloc - not found
-- Looking for free
-- Looking for free - not found
-- Looking for getenv
-- Looking for getenv - not found
-- Looking for setenv
-- Looking for setenv - not found
-- Looking for putenv
-- Looking for putenv - not found
-- Looking for unsetenv
-- Looking for unsetenv - not found
-- Looking for qsort
-- Looking for qsort - not found
-- Looking for abs
-- Looking for abs - not found
-- Looking for bcopy
-- Looking for bcopy - not found
-- Looking for memset
-- Looking for memset - not found
-- Looking for memcpy
-- Looking for memcpy - not found
-- Looking for memmove
-- Looking for memmove - not found
-- Looking for memcmp
-- Looking for memcmp - not found
-- Looking for strlen
...

======================================================
why all are found?

**Comment by axredneck** [comment]
Do You have headers installed (dev packages) ?

**Comment by lishulei3389** [comment]
All dev packages are the lastest.

**Comment by weitjong** [comment]
You probably miss the 
libc6-dev package, which is strange  because it is a dependency package that should get installed automatically when you have any other dependent dev packages installed.
