### ISSUE TITLE
Box2D joints handling bug

### ISSUE THREAD

**Issue by barograf** [urho3d/Urho3D#1787]
The way Box2D joints are handled by Urho is not valid. For now every time some joint parameter is changed, the joint gets recreated. It involves destruction of an old object, change of joint definition and then creation of a new joint with altered parameters. For most cases it might be a good way to handle this, despite the fact this is not so performant.

But some joints have internal state which gets lost during the process. For example the prismatic joint with its lower and upper translation. Limits are computed for rigid bodies during the creation of a prismatic joint. If bodies move away during the simulation (due to gravity or a motor) and then joint gets recreated, the limits are computed again but for bodies in other positions, which stretches (or narrows) the limits creating strange behaviors.

I tried to change the joint parameter directly (for example a motor speed) without joint recreation and then it worked correctly. Are there any other reasons this is not implemented this way?

**Comment by cadaver** [comment]
I don't think there's any other reason than being generic & lazy. If you can, please contribute a PR.
