### ISSUE TITLE
Editor: incorrect work with UIElement vars.

### ISSUE THREAD

**Issue by KonstantinTomashevich** [urho3d/Urho3D#1788]
Editor doesn't show values of newly added UIElement vars. UILayout reload solves this problem, but it's very inconvenient to save and reload layout all the time. To reproduce the bug:
1. Create `UIElement` in Urho3D Editor.
2. Add var `MyVar` with type `String` (or any other type, it doesn't matter) to this element using  Attribute Inspector.
3. Set value `XXX` to `MyVar`.
4. In attribute inspector window value of `MyVar` will be empty. But if you save layout, `MyVar` will be saved with value `XXX`. Also, if you press refresh button in Attribute Inspector, `MyVar` will disappear from this window.

**Comment by cadaver** [comment]
Reproduced.
