### ISSUE TITLE
Asset Importer Animation Import Bug

### ISSUE THREAD

**Issue by OldSnake22** [urho3d/Urho3D#1789]
Hello, 

Today i have tried to import a 3D animated model with 6 animations. 

The asset importer tool produced 7 files (the base model and it's animations).

The problem is that every animation produced had the same length and it was the length of the first animation. 

I have commented this line "duration = importEndTime_ - importStartTime_;" (line 1295 in AssetImporter.cpp) and everything worked correctly. All animation were using their correct lenght.

Any idea why this is happening ? 

Thanks !

**Comment by cadaver** [comment]
Looks like a bug of using global variables that doesn't account for multiple animations.

Can you share the model to e.g. loorni@gmail.com ?

**Comment by OldSnake22** [comment]
Done, you should have received it :)

**Comment by OldSnake22** [comment]
Thanks a lot !
