### ISSUE TITLE
BillboardSet with fixed screen size doesn't update properly.

### ISSUE THREAD

**Issue by henu** [urho3d/Urho3D#1790]
The bug happens with immovable Billboards when BillboardSet has `SetFixedScreenSize(true);`

The updates of Billboards only happens when you are moving. When you stop, those that are in front of you look good, but when you start looking around, you find that some of the other billboards have strange small size. When you move even a little, their size gets fixed. I modified the Billboards example to show how this happens.

First I turned off animation:

```Diff
@@ -325,7 +326,7 @@ void Billboards::HandleUpdate(StringHash eventType, VariantMap& eventData)
 
     // Move the camera and animate the scene, scale movement with time step
     MoveCamera(timeStep);
-    AnimateScene(timeStep);
+//    AnimateScene(timeStep);
 }
```

Then I turned BillBoards to fixed size:

```Diff
@@ -150,12 +150,13 @@ void Billboards::CreateScene()
         billboardObject->SetNumBillboards(NUM_BILLBOARDS);
         billboardObject->SetMaterial(cache->GetResource<Material>("Materials/LitSmoke.xml"));
         billboardObject->SetSorted(true);
+        billboardObject->SetFixedScreenSize(true);
 
         for (unsigned j = 0; j < NUM_BILLBOARDS; ++j)
         {
             Billboard* bb = billboardObject->GetBillboard(j);
             bb->position_ = Vector3(Random(12.0f) - 6.0f, Random(8.0f) - 4.0f, Random(12.0f) - 6.0f);
-            bb->size_ = Vector2(Random(2.0f) + 3.0f, Random(2.0f) + 3.0f);
+            bb->size_ = Vector2::ONE * 100;
             bb->rotation_ = Random() * 360.0f;
             bb->enabled_ = true;
         }
```

This is how you can see the bug:

1. Stop moving. Billboards in front of you look good.

![1](https://cloud.githubusercontent.com/assets/3167494/22523543/6f1a91aa-e8c8-11e6-8790-92bbe32a7836.jpg)

2. Look to your side. Some of the billboards are smaller than others, although they should have same size.

![2](https://cloud.githubusercontent.com/assets/3167494/22523564/81aadbb8-e8c8-11e6-8ee7-ef9bfa90d308.jpg)

3. Make a little move forward and back. No you are in same spot, and the size of billboards has been updated.

![3](https://cloud.githubusercontent.com/assets/3167494/22523604/a2b08146-e8c8-11e6-8139-99dd7b074e6f.jpg)

Even better way to see it is to not move at all when the demo starts. Now they have even bigger size difference when I look around:

![4](https://cloud.githubusercontent.com/assets/3167494/22523718/043f6314-e8c9-11e6-843a-00de063d8cdd.jpg)

But again, small moving fixes the problem:

![5](https://cloud.githubusercontent.com/assets/3167494/22523727/0c542954-e8c9-11e6-9adf-40786672173e.jpg)

**Comment by henu** [comment]
I tried to fix this by myself, but I couldn't figure out how the updating is done :(

**Comment by JSandusky** [comment]
Roughly related, there's a bug with dirty updating in UpdateBatches in that it doesn't work with new billboards being added when they have a fixed screen size:

    Vector3 worldPos = node_->GetWorldPosition();
    Vector3 offset = (worldPos - frame.camera_->GetNode()->GetWorldPosition());
    // Sort if position relative to camera has changed
    if (offset != previousOffset_)
    {
        if (sorted_)
            sortThisFrame_ = true;
        if (faceCameraMode_ == FC_DIRECTION)
            bufferDirty_ = true;

        // Calculate fixed screen size scale factor for billboards if needed
        if (fixedScreenSize_)
            CalculateFixedScreenSize(frame);
    }
    else if (bufferDirty_ && fixedScreenSize_)
    {
        // If the buffer is dirty and we're in fixed screen size mode then we need to update fixed screen sizes even if the camera hasn't moved.
        CalculateFixedScreenSize(frame);
    }

See the "else if" case for the fix which is to check for buffer dirtying and fixed screen size. There might be a better way, but when I was fighting with this I didn't have the patience to investigate further than the explicit culprit.

**Comment by cadaver** [comment]
@JSandusky Thanks for the fix for the "billboards added" case.

**Comment by JSandusky** [comment]
@cadaver, NP. 

Here are two screenshots of simpler billboards that demonstrate the issue of the main post:

There should be a billboard at the tip of that bone: http://i.imgur.com/Fx20Lwm.png

Move the camera just a bit and there it is: http://i.imgur.com/lVlpb4X.png

This should be visible as a problem in the editor with icons enabled for reproducibility (assuming the editor isn't doing something extra).

**Comment by cadaver** [comment]
That, or the BillboardSet having been invisible while its size should have been updated. Easiest solution in total would likely be to always recalculate the sizes when fixed size mode is on, and dirty the buffer if some of the sizes actually changed.
