### ISSUE TITLE
Multisampling with DX11 renderer on DX10 hardware

### ISSUE THREAD

**Issue by t-artikov** [urho3d/Urho3D#1792]
Multisampled texture creation is failed.

Log message: 
"ERROR: Failed to create texture (HRESULT 80070057)"

DX11 debug message:
"D3D11 ERROR: ID3D11Device::CreateTexture2D: The Sample descriptor is invalid for a D3D10.0 level driver. DXGI_SAMPLE_DESC::Count (value = 8) must be between 1 and 32, inclusively. For 8 samples, the current graphics implementation only supports DXGI_SAMPLE_DESC::Quality (value = -1) less than 17. <-- if 0 is shown here for Quality, this means the graphics implementation doesn't support this number of samples. Use CheckMultisampleQualityLevels to detect what the graphics implementation supports. [ STATE_CREATION ERROR #93: CREATETEXTURE2D_INVALIDSAMPLES]"

The problem is how multisampling quality is specified.
SampleDesc.Quality == 0xffffffff is not valid value for DX10.
https://msdn.microsoft.com/en-us/library/windows/desktop/bb173072(v=vs.85).aspx

**Comment by cadaver** [comment]
Thanks for notifying. There were also some related bugs, like 10.0 not being able to support a readable multisampling depth-stencil, and read-only depth stencil view (for simultaneous sampling) only available on feature level 11 or greater.
