### ISSUE TITLE
42_PBRMaterials built with 32-bit MinGW compiler toolchain is not runnable

### ISSUE THREAD

**Issue by weitjong** [urho3d/Urho3D#1795]
Continued discussion from #1765. The new MinGW-CI build consistently shows that 42_PBRMaterials crashed during test run.

**Comment by BlueMagnificent** [comment]
Yeah, I did notice it when I ran into #1765 though I didn't investigate cause all my attention was on the fact that AngelScript was the culprit of the crash, but it seems obvious now that they are all of the same cause

**Comment by cadaver** [comment]
The PBR scene contains AngelScript to handle animation; this runs also in the C++ version.

**Comment by weitjong** [comment]
Ah, I see. So it is indeed the same issue. In that case, I will close this one.
