### ISSUE TITLE
Creating a quad cube planet!

### ISSUE THREAD

**Issue by vivienneanthony** [urho3d/Urho3D#1801]
I'm trying to create a cube and shape it spherically in Urho. So far I'm a little confused how to get it to render. I'm looking to do something like https://britonia.wordpress.com/2009/01/23/cube-to-sphere-terrain-projection/ and https://britonia.wordpress.com/2010/05/20/planet-geometry/

I'm not sure if I'm doing the vertex setup correctly.

Replacing the whole terrain system into a new one. The full code I'm testing is on Urho. Basically,
I want to project a cube to a sphere, Terrain=WorldTerrain, TerrainFace, then TerrainPatches(Working similiar in how the patch works without additional nodes)

Any help or idea would be helpful.

[code]
```
void TerrainFace::BuildFace(Vector3 centre, Vector3 dx, Vector3 dy)
{
    // Define the grid size.  i.e. the number of vertices in a grid (16x16)
    unsigned int PatchSize = 16;
    unsigned int PatchSizePlus = 17; // PatchSize + 1

    // Set buffer
    vertexBuffer_->SetSize(PatchSize*PatchSize, MASK_POSITION | MASK_NORMAL | MASK_TEXCOORD1,true);

    Vector<float> _vertexData;

    // Didn't work
    float* tempVertexBuffer = (float*)vertexBuffer_->Lock(0, vertexBuffer_->GetVertexCount());

    int xPos=0;
    int yPos=0;

    // loop through and create a grid of vertices.
    for (int u = 0; u <= PatchSize; u++)
    {
        for (int v = 0; v <= PatchSize; v++)
        {

            // Create the vertex grid around the centre of thecube face (which is passed into the function as Vector3 centre).
            Vector3 tempPosition = centre + (dx / PatchSize) * (v - PatchSize / 2) + (dy / PatchSize) * (u - PatchSize / 2);

            // This is where we would define the height of the vertex.
            float fheight = 0;

            // Project the vertex onto the sphere, taking into consideration the height of the
            // vertex and the radius of the planet.  By specifying 0 as the height, we will
            // get a 'perfectly' round planet/sphere.
            Vector3 newPosition = SurfaceVectorToCoordinates(tempPosition, m_ParentTerrain->GetWorldRadius(), fheight);

            // copy vertex
            _vertexData.Push(newPosition.x_);
            _vertexData.Push(newPosition.y_);
            _vertexData.Push(newPosition.z_);

            // Normal
            _vertexData.Push(1.0f);
            _vertexData.Push(1.0f);
            _vertexData.Push(1.0f); //should point to parent center)

            // Normal
            Vector2 texCoord((float)u/ (float)( PatchSize - 1), 1.0f - (float)v / (float)( PatchSize  - 1));
            _vertexData.Push(texCoord.x_);
            _vertexData.Push(texCoord.y_);
        }
    }

    vertexBuffer_->SetData((float *) tempVertexBuffer);

    vertexBuffer_->Unlock();
}

/// <summary>
/// Transforms a vector from the surface of a cube, onto the surface of a sphere.
/// </summary>
/// surfacePos is the vertex position on the cube.
/// radius is the radius of the planet.
/// height is the height of the terrain at this position.
Vector3 TerrainFace::SurfaceVectorToCoordinates(Vector3 surfacePos, float radius, float height)
{

// Create a return veriable.
    Vector3 loReturnData = surfacePos;

// Get a unit vector ( this will 'point' in the correct direction, from (0,0,0) to
// the position of the vertex on the sphere ).
    loReturnData.Normalize();

// Add the planet radius and the height of the vertex, and return the vector.
    return loReturnData *(radius + height);
}
```
[/code]

Vivienne

**Comment by Lumak** [comment]
This is interesting.  I'm curious, thought.  Do you have cube terrain working already? it should be as simple as rotating each terrain to a cube face - (pic if you have it).  If you have a cube terrain then it would probably simplify your conversion to sphere.  Following the links that you've provided and reading the comments, this link - http://mathproofs.blogspot.com/2005/07/mapping-cube-to-sphere.html seems to provide better distribution conversion from cube to sphere.  I'd use that approach instead.  Math looks simple enough, i.e. 
1 - convert terrain x-z-height space to xyz space for each cube face 
2 - convert it to sphere space
3 - transform new values to x-z-height terrain space.

**Comment by vivienneanthony** [comment]
I downloaded some PDF's of possible doing it the primary problem I have is setting up a object to be seen. I attempted to set the various buffers similiar to to Terrain, TerrainPatch but it fails.

My methology would be to create 3 subsets Terrain, TerrainFace, and TerrainPatch. I'll be more descriptive soon but I guess the major help with someone who been able to create a mesh not using custom geometry class.

**Comment by Lumak** [comment]
I see. Rewriting the three subsets that you mention seems more complex than just rotating six terrain into a cube, but I guess that would work.  What I was thinking was going from this:
![single](https://cloud.githubusercontent.com/assets/14249868/22674180/69e8f73e-ec93-11e6-879e-653b3a55b5fd.jpg)
to this:
![cube](https://cloud.githubusercontent.com/assets/14249868/22674185/70c25abe-ec93-11e6-97b4-15c9d98ae154.jpg)

and then do your transformation w/o rewriting anything.  Well, you might have to do more than cube to sphere transformation. I guess that's why you're rewriting some things...

**Comment by Lumak** [comment]
I came across this - https://github.com/sp4cerat/Planet-LOD
I don't know how relevant it is to your project but could be useful.

**Comment by vivienneanthony** [comment]
I'm trying to see if I should look at this for the custom geometry.

![example](https://cloud.githubusercontent.com/assets/3378677/22809574/69f99178-ef01-11e6-9714-e1bf6cc26180.png)

I have a way to create a grid but it data like
```
[Thu Feb  9 19:30:33 2017] INFO: -1 -1 -1 (point 1)
[Thu Feb  9 19:30:33 2017] INFO: -1 0 -1 (point 2)
[Thu Feb  9 19:30:33 2017] INFO: -1 1 -1
[Thu Feb  9 19:30:33 2017] INFO: -1 -1 0 (point 3)
[Thu Feb  9 19:30:33 2017] INFO: -1 0 0
[Thu Feb  9 19:30:33 2017] INFO: -1 1 0
[Thu Feb  9 19:30:33 2017] INFO: -1 -1 1
[Thu Feb  9 19:30:33 2017] INFO: -1 0 1
[Thu Feb  9 19:30:33 2017] INFO: -1 1 1
```
I'm assuming in Urho3D vertices are stored in v1, v2,v3 forma t(forming one triangle), v4,v5,v6 and on

Maybe someone can clarify.

**Comment by vivienneanthony** [comment]
I have been able to do this playing around with a demo. The only part I am not sure of is calculating the normal.

It's  basically creates two triangles  but I'm not sure of calculating the normal so it's the same. This is for testing. I'm assuming if something similiar is done for the other sides then rounded.  

Any help appreciated. As it's not clear to me how too set the normals and triangles so it appears correct.

![odd8](https://cloud.githubusercontent.com/assets/3378677/22814725/e2502a5c-ef23-11e6-8ae9-2d42c2517cde.png)

...
 // Finally create one model (pyramid shape) and a StaticModel to display it from scratch
    // Note: there are duplicated vertices to enable face normals. We will calculate normals programmatically
    unsigned numVertices = 18;


    // set chunks or patches
    int PatchSize=4;


    // Set Cube size
    float CubeSize=4;

    // Get Cube Center
    Vector3 center = Vector3(-1,0,0)*CubeSize/2;

    Vector3 direction_x = CubeSize*Vector3(0,1,0);
    Vector3 direction_y = CubeSize*Vector3(0,0,1);


    // Create buffer
    Vector<Vector3> vertexData;
    Vector<unsigned short> indexData;

    // Create a index
    unsigned int index = 0;

    // loop through and create a grid of vertices. // do not draw edge
    for (int u = 0; u < PatchSize; u++)
    {
        for (int v = 0; v < PatchSize; v++)
        {
            // Calculate patch size
            Vector3 x1=(direction_x / PatchSize) * (v- PatchSize / 2);
            Vector3 y1=(direction_y / PatchSize) * (u- PatchSize / 2);

            // Create the vertex grid around the center of thecube face (which is passed into the function as Vector3 center).
            Vector3 v1= center+ x1+y1;

            // Calculate patch size
            Vector3 x2=(direction_x / PatchSize) * ((v+1) - PatchSize / 2);
            Vector3 y2=(direction_y / PatchSize) * (u- PatchSize / 2);

            // Create the vertex grid around the center of thecube face (which is passed into the function as Vector3 center).
            Vector3 v2= center+ x2+y2;

            // Calculate patch size
            Vector3 x3=(direction_x / PatchSize) * (v- PatchSize / 2);
            Vector3 y3=(direction_y / PatchSize) * ((u+1)- PatchSize / 2);

            // Create the vertex grid around the center of thecube face (which is passed into the function as Vector3 center).
            Vector3 v3= center+ x3+y3;

            // Calculate patch size
            Vector3 x4=(direction_x / PatchSize) * ((v+1)- PatchSize / 2);
            Vector3 y4=(direction_y / PatchSize) * ((u+1)- PatchSize / 2);

            // Create the vertex grid around the center of thecube face (which is passed into the function as Vector3 center).
            Vector3 v4=center+ x4+y4;

            // store first triangle
            vertexData.Push(v1);
            vertexData.Push(Vector3(1,0,0));
            indexData.Push(index++);

            vertexData.Push(v2);
            vertexData.Push(Vector3(1,0,0));
            indexData.Push(index++);

            vertexData.Push(v3);
            vertexData.Push(Vector3(1,0,0));
            indexData.Push(index++);

            vertexData.Push(v4);
            vertexData.Push(Vector3(0,0,1));
            indexData.Push(index++);

            vertexData.Push(v2);
            vertexData.Push(Vector3(0,0,1));
            indexData.Push(index++);

            // store second triangle
            vertexData.Push(v3);
            vertexData.Push(Vector3(0,0,1));
            indexData.Push(index++);
        }


    }

    numVertices = indexData.Size();

    SharedPtr<Model> fromScratchModel(new Model(context_));
    SharedPtr<VertexBuffer> vb(new VertexBuffer(context_));
    SharedPtr<IndexBuffer> ib(new IndexBuffer(context_));
    SharedPtr<Geometry> geom(new Geometry(context_));
...

**Comment by vivienneanthony** [comment]
Anyone has a idea why the faces normal might be showing per side?

![address9](https://cloud.githubusercontent.com/assets/3378677/23037050/fdb6970c-f452-11e6-929b-7f949c55cb15.png)

**Comment by carnalis** [comment]
Did you get this issue resolved?

**Comment by vivienneanthony** [comment]
Yes. I found some code that help with planet generation which I'm working on. It uses OpenGL and GPU. It might be simple to modify and improve to use with Urho3D. 

https://www.youtube.com/watch?v=rL8zDgTlXso and https://www.dropbox.com/s/7wlaewgc64ruenx/Procedurus_Source.zip

I think I have half of the code setup just have to deal with the Shader part. So if anyone working with DirectX, OpenGl, and Urho3D GPU/Shader. 

Real-time planet generation could be possible.

**Comment by carnalis** [comment]
There's the forum and thread; perhaps this issue can be closed or something?
