### ISSUE TITLE
Compile error SOCKET_SECURITY_QUERY_TEMPLATE unknown type name

### ISSUE THREAD

**Issue by AndreZH** [urho3d/Urho3D#1803]
compiling Urho3d for the first time i'll keep getting this error under MingW and gcc 6.2.0

||=== Build: all in Urho3D (compiler: GNU GCC Compiler) ===|
C:\MinGW\x86_64-w64-mingw32\include\ws2tcpip.h|404|error: unknown type name 'SOCKET_SECURITY_QUERY_TEMPLATE'|
C:\MinGW\x86_64-w64-mingw32\include\ws2tcpip.h|406|error: unknown type name 'SOCKET_SECURITY_QUERY_INFO'|
C:\MinGW\x86_64-w64-mingw32\include\ws2tcpip.h|416|error: unknown type name 'SOCKET_PEER_TARGET_NAME'|
C:\MinGW\x86_64-w64-mingw32\include\ws2tcpip.h|424|error: unknown type name 'SOCKET_SECURITY_SETTINGS'|
Source\ThirdParty\Civetweb\CMakeFiles\Civetweb.dir\build.make|62|recipe for target 'Source/ThirdParty/Civetweb/CMakeFiles/Civetweb.dir/src/civetweb.c.obj' failed|
CMakeFiles\Makefile2|854|recipe for target 'Source/ThirdParty/Civetweb/CMakeFiles/Civetweb.dir/all' failed|
C:\Urho3dBusmanager\Makefile|148|recipe for target 'all' failed|
||=== Build failed: 7 error(s), 0 warning(s) (0 minute(s), 4 second(s)) ===|

**Comment by weitjong** [comment]
Have you tried other versions? I have read another user reported having problem with 6.2.0.

**Comment by AndreZH** [comment]
I am now trying to build with Visual studio, but ill try an other gcc asswell

**Comment by AndreZH** [comment]
"Visual Studio 15" compiles fine even the examples in the bin directory work as expected 
compiling with MingW and gcc 5.3.0 gives issues

**Comment by weitjong** [comment]
I am sorry to hear that. Perhaps you should also listed the steps on how to reproduce your issue. And BTW, we have had successful CI build using MinGW-W64 compiler toolchain recently. We are using the latest 6.3.0. Both 32-bit and 64-bit build fine. We only have a runtime issue on 32-bit build when AngelScript subsystem is enabled. Personally, I have not seen similar build issue like yours in any of my build environments.

**Comment by weitjong** [comment]
Also make sure you are using the code from the master branch and not from 1.6 tag or earlier.

**Comment by AndreZH** [comment]
I upgraded mingw64 to 6.3.0 and i also needed to parse -DVIDEO_OPENGLES=0 to prevent an errror in SDL
and run with administrator rights the *.bat script
and it is compiled :)

**Comment by weitjong** [comment]
In that case I am closing this issue now.
