### ISSUE TITLE
Add cubemap convolution routines

### ISSUE THREAD

**Issue by JSandusky** [urho3d/Urho3D#1807]
PR, ready this is an RFC.

Image class already supports cubemaps structurally. Convolution filters through the mip chain could be specified for filtering mips via cubemap solid angle.

This is a non-trivial issue, as cubemap filtering should depend on the BRDF used. I propose the addition of a downsampling routine to image that includes a function pointer (this is naturally not a process for scripting) that performs the 2x2 to 1x1 reduction. This can replace the existing mipmap generation routines and will make those much more flexible, a default routine should be assumed for mip generation of course.

Cubemap renderer for zones should also probably expand FOV by Castano's method for the Witness to reduce seam issues a bit more.

**Comment by hdunderscore** [comment]
This sounds interesting. Having this in-engine could simplify IBL texture generation for use in urho3d, which isn't quite as smooth as one would hope, considering that some tools that you can use to generate this kind of thing don't directly export into a urho3d ready format, at least the last time I tried,

Although (without testing it) I could see the counter-argument of it potentially not being real-time game focused enough for urho3d. For that reason, I'd like to see more on this and test performance etc.

**Comment by cadaver** [comment]
It's OK by me to include "asset preparation" type functions, though not strictly realtime. Where I'd draw the line is that Image should not behave like it's implementing an actual art package.

**Comment by JSandusky** [comment]
I'll submit a PR tomorrow, it'll actually be different since I see that no one has attempted any process calls to AMDCubeGen or CMFT, so that's what it'll be about.

That avenue should be explored first. I thought it had been already, but I guess not, my bad.

If externally deferring works well enough I'm good to pass on this for a bit until compute is wrapped up.
