### ISSUE TITLE
Add Compute support

### ISSUE THREAD

**Issue by JSandusky** [urho3d/Urho3D#1808]
RFC:

The addition of GPU/CPU Compute. I propose the optional addition of OpenCL as a GPU/CPU compute option through a generic "Compute" interface. That interface being tightly tied to the "ComputeDevice" any instance was instantiated against (support of using both CPU and GPU devices). By "tightly tied" I mean that buffers assigned for a CPU device will reject and present errors when attempting to bind it to a GPU device occurs (as well as the opposite case).

OpenCL is shortstop for longer term GPGPU support, and has broader support than OpenGLs compute capabilities and has much larger mobile reach. This addition will make the implementation of tiled deferred and tiled forward/forward+ more viable. It will also provide opportunities to speed up particle simulation and bone calculations.

I'm prepared both for the PR and to add a naive-surface-nets example that demonstrates running NSN in CPU vs NSN in "best-found-compute" device.

It's important that this not be one entity, as there are good reasons for using both a CPU and GPU compute device.

I do not see this becoming anything core other than the core tracking the "attached" compute devices. Compute is a very specialized matter, and realistically doesn't warrant script exposure.

**Comment by OldSnake22** [comment]
Also interested by this. Does this mean that you have already started working on a tiled deferred renderpath ?

**Comment by MonkeyFirst** [comment]
>current deferred rendering implementation consume a lot of GPU bandwidth for example.
I think it's cuz shadow rendering is not optimal, and the shadow casters reduce performance a lot.

**Comment by OldSnake22** [comment]
Yeah i have already raised this "issue". Hopefully someone can help with this in the future :)

**Comment by eugeneko** [comment]
> I think it's cuz shadow rendering is not optimal

What kind of shadow rendering is more optimal, IYO?

**Comment by cadaver** [comment]
The issue was about caching a shadowmap, ie. not re-rendering the shadowmap it if shadowcasters haven't moved. Or in the case of directional lights, potentially until the camera has not moved enough to invalidate the cascades. 

Personally I've found shadow sampling to be more expensive than shadow caster rendering, but perhaps I've not tested the right kind of scenes. Also on deferred shadow caster rendering is just as lightweight as on forward.

**Comment by JSandusky** [comment]
> Does this mean that you have already started working on a tiled deferred renderpath ?

This is about the compute primitives and compute tasks in renderpaths. 

I'm using forward-clustered in a "eat-your-own-dog-food" project but I skirted the shadowmapping issue by generating an SDF of occluders that's twice the resolution of the cluster grid and raycasting the SDF for shadowcasting lights - which works about as well as one think (which is not well).

There's other issues beyond just the shadowmaps, such as lighting alpha/particle geometry (which is why I went with clustered) and the ramp textures for lights.

I don't think yet another render path is a good idea. There are 4 of them already (PBR deferred might as well be considered to be its' own thing). I'd personally dread the task of doing a general purpose tiled/clustered renderpath, the only nice thing is that the really unique chunks are the same in deferred or forward. I think forward would be a stock shader maintenance nightmare.

I could toss my implementation into a branch as a reference, but that's about as far as I think I'd like to go with actual rendering.

**Comment by boberfly** [comment]
@JSandusky yes please if you can provide your clustered implementation, I'm guessing you followed it based on Doom 2016's implementation or similar? Cheers!

**Comment by JSandusky** [comment]
I revised it a bit after I saw the breakdown of how Doom dealt with things, I implemented it maybe a month before anything was really available on how Doom did things, mostly off of the Just Cause material.

I'll put it up after I've wrapped up compute.

**Comment by JSandusky** [comment]
Canceled.
