### ISSUE TITLE
(feature request) Separate option for AssetImporter

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1813]
I never use AssetImporter (only blender exporter), but compiling of AssetImporter take half compile time. It would be nice to have option like "-DAsset_Importer=OFF".

**Comment by cadaver** [comment]
Should be doable. I often use -DURHO3D_TOOLS=0 for engine testing, but that is of course not nice when you want the other tools.

**Comment by 1vanK** [comment]
Yes, I still use Urho3DPlayer

**Comment by cadaver** [comment]
-DURHO3D_TOOLS=0 will compile Urho3DPlayer, but not the others like RampGenerator, PackageTool etc.

**Comment by 1vanK** [comment]
Hm, I did not know it. So it solved my problem
