### ISSUE TITLE
Add Urho3DFwd.h header

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1815]
Some time ago `Urho3DAll.h` was introduced (and I've never used it for obvious reasons).
I think that header with forward declarations would be also useful.
I understand that genration algorithm would be much more complex and manual enumeration is error-prone on the other hand.
However, let this issue be here.

**Comment by weitjong** [comment]
Rather than script to manually parsing those headers, I believe this can be done with the right tool such as Clang AST.
