### ISSUE TITLE
Editor.bat loading wrong files when modifying Editor scripts

### ISSUE THREAD

**Issue by luveti** [urho3d/Urho3D#1817]
I've built Urho3D from the current source using CLion, so my project structure looks like so:

- Urho3D
   - ...
   - bin
   - cmake-build-debug
   - Source
   - ...

After building, I copied `Urho3DPlayer_d.exe` from `Urho3D/cmake-build-debug/bin` into `Urho3D/bin` and then began editing Editor files in `Urho3D/bin/Data/Scripts/Editor`. On initial load, files are loaded from the correct paths. But after editing a script and saving it, the Editor reloads files from `Urho3D/cmake-build-debug/bin` instead of from `Urho3D/bin`.

This can be reproduced by placing a call to `Print` in `CreateUI ` of `Urho3D/bin/Data/Scripts/Editor/EditorUI.as` and `Urho3D/cmake-build-debug/bin/Data/Scripts/Editor/EditorUI.as`  and then looking at the output in the Editors console.

By the way, removing the `cmake-build-debug` directory seems to fix this issue. So it sounds like Urho3DPlayer is searching parent directories for the first `Data` directory?

**Comment by weitjong** [comment]
Please use the support discussion forum for further questions. What you described is not an issue.

It seems you have confused between source tree and build tree. We do not use use the term parent directory in our official documentation. Instead, all the source files that you cloned from git are resided in so-called source tree. Using CMake you can generate as many build tree you like. For CLion, it by default generate one (for each build configuration) as a sub-dir inside the source tree. I also uses CLion. Personally I configure it to generate the build tree completely outside of the source tree. After the build is complete, there is no need to copy binary from build tree to source tree. All the binaries should be runnable in 'bin' subdirectory of the build tree.

On Windows host system only, when editing editor scripts then you must check whether you are using build tree with symlink setup or using hard-copy. When using symlink, it realy doesn't matter which place you make the change. When using hard-copy, the modification is probably only visible in a single build tree. If you want to contribute back by improving the editor scripts then you are better off spending sometime to setup symlink privilege on Windows host system.
