### ISSUE TITLE
(featur request) GetDerivedComponent for Physics2D

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1822]
Many features in Box2D require using PreSolve() and PostSolve()
May be good way is allow users make own custom tuned PhysicsWorld2D class
and replace
```
void Constraint2D::OnSceneSet(Scene* scene)
{
    if (scene)
        physicsWorld_ = scene->GetOrCreateComponent<PhysicsWorld2D>();
}

void RigidBody2D::OnSceneSet(Scene* scene)
{
    if (scene)
    {
        physicsWorld_ = scene->GetOrCreateComponent<PhysicsWorld2D>();
```
to GetOrCreateDerivedComponent()

but I'm not sure about performance

**Comment by cadaver** [comment]
Anything happening in OnSceneSet should be one-time only, so the performance difference is negligible.

**Comment by cadaver** [comment]
PR merged.
