### ISSUE TITLE
Constraint2D do not restore their rigidbody connection on scene load

### ISSUE THREAD

**Issue by cadaver** [urho3d/Urho3D#1825]
To reproduce: add scene load/save to the PhysicsConstraints2D demo. On load, observe that the connections are broken and objects fall to the ground instead.

**Comment by 1vanK** [comment]
In seems constraints do not serialize id of other body

**Comment by cadaver** [comment]
Yes. There is also something else iffy going on, as the mouse constraint (which is dynamically created in code) doesn't seem to work after load/save.

**Comment by 1vanK** [comment]
When
```
        if (input.keyPress[KEY_F7])
        {
            File loadFile(fileSystem.programDir + "Data/Scenes/Constraints.xml", FILE_READ);
            scene_.LoadXML(loadFile);
           
            Node@ edgeNode = scene_.GetChild("VerticalEdge");
            RigidBody2D@ edgeBody = edgeNode.GetComponent("RigidBody2D");
            
            dummyBody = edgeBody;
        }
```
mouse constraint works (it requred dummyBody, but after loading it is null) but debug line not drawed

**Comment by cadaver** [comment]
Ah, naturally. Thanks for investigating!
