### ISSUE TITLE
RigidBody2D::ApplyLinearImpulseToCenter() is missing

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1826]

**Comment by cadaver** [comment]
Can you make a PR? You're probably soon deeper into the 2D physics system than us others :)

**Comment by cadaver** [comment]
Hm, then it would be a kind of larger work. If you want to do it at the same time, you're welcome.

**Comment by 1vanK** [comment]
I can sent PR with new lib, but I not can test on all platforms

**Comment by 1vanK** [comment]
And it seems they resolve problem

![3](https://cloud.githubusercontent.com/assets/13021826/22943765/ba11e1d6-f2ff-11e6-9834-9a8fa2d2d520.png)

nut i can not test it on Android

**Comment by 1vanK** [comment]
I think we can move m_useFixtureMass hack from Box2D lib to urho class.
Just reset mass data after set dencity

**Comment by cadaver** [comment]
Yes, sounds OK. CI will take care of platform testing, you will see preliminary test results when you publish your PR.

**Comment by 1vanK** [comment]
I hav no idea why the needed hack with m_useFixtureMass in Box2D lib. Without it mass correct recalculate already.

**Comment by 1vanK** [comment]
https://github.com/urho3d/Urho3D/pull/1827
