### ISSUE TITLE
iModelMatrix semicolon

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1829]
If I understand correctly, semicolons is added to defines intentionally and deprecate using iModelMatrix in expressions

Transform.hlsl
```
#if defined(SKINNED)
    #define iModelMatrix GetSkinMatrix(iBlendWeights, iBlendIndices); // SEMICOLON
#elif defined(INSTANCED)
    #define iModelMatrix iModelInstance
#else
    #define iModelMatrix cModel
#endif
```

But it seems in Transform.glsl semicolon is missing
```
#if defined(SKINNED)
    #define iModelMatrix GetSkinMatrix(iBlendWeights, iBlendIndices) // ?????????
#elif defined(INSTANCED)
    #define iModelMatrix GetInstanceMatrix(); // SEMICOLON
#else
    #define iModelMatrix cModel
#endif
```

**Comment by cadaver** [comment]
I no longer remember the reasoning, but right now it seems to me there shouldn't be semicolon in any of these; instead the semicolon should be part of the expression where this macro is inserted.

**Comment by 1vanK** [comment]
I always thought it was in order to prevent the expression like
```
a = f(iModelMatrix);
```
because iModelMatrix not just value and this expression can cause slowdown

**Comment by eugeneko** [comment]
> because iModelMatrix not just value and this expression can cause slowdown

This makes sense. However, it is very dirty way to inform, I defiinetly dislike it.

**Comment by 1vanK** [comment]
Yes, but
```
mat4 modelMatrix = iModelMatrix;
```
also looks strange and someone may try to fix it :)

**Comment by cadaver** [comment]
In any case, shader authors should understand that the macro expansion is happening, so I don't see this as a real risk either way. It's also just a convenience and you don't have to use it.
