### ISSUE TITLE
(Feature request) Event between Renderer::Render() and UI:Render()

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1830]
```
void Engine::Render()
{
    GetSubsystem<Renderer>()->Render();
    //  HERE
    GetSubsystem<UI>()->Render();
    graphics->EndFrame();
}
```
Renderer::Render() clear screen and render viewports. But viewports can be missing (I draw geometry manually) so I can not use E_ENDVIEWRENDER.

Also I need DebugHud, so I can not use E_ENDRENDERING (it calls after UI::Render()).

p.s. I have no idea how to name this new event

**Comment by 1vanK** [comment]
May be E_ENDVIEWSRENDER (but it easily confused with E_ENDVIEWRENDER)
or END_ALLVIEWSRENDER

**Comment by hdunderscore** [comment]
Can you use renderui command in renderpath? or sendevent command:
https://urho3d.github.io/documentation/HEAD/_render_paths.html

**Comment by 1vanK** [comment]
I use direct graphics calls, no any viewports and renderpaths

**Comment by cadaver** [comment]
Good idea, since there's otherwise no way to know if it was the last view rendered.
