### ISSUE TITLE
Not the right parameters are passed to the function

### ISSUE THREAD

**Issue by Commondor** [urho3d/Urho3D#1835]
Please, change in Quaternion.h from:
    /// Spherical interpolation with another quaternion.
    Quaternion Slerp(Quaternion rhs, float t) const;
    /// Normalized linear interpolation with another quaternion.
    Quaternion Nlerp(Quaternion rhs, float t, bool shortestPath = false) const;

to:
    /// Spherical interpolation with another quaternion.
    Quaternion Slerp(const Quaternion& rhs, float t) const;
    /// Normalized linear interpolation with another quaternion.
    Quaternion Nlerp(const Quaternion& rhs, float t, bool shortestPath = false) const;

and change in Quaternion.cpp from:
Quaternion Quaternion::Slerp(Quaternion rhs, float t) const
{
    // Favor accuracy for native code builds
    float cosAngle = DotProduct(rhs);
...
    rhs = -rhs;
...
   return *this * t1 + rhs* t2;
}

to:
Quaternion Quaternion::Slerp(const Quaternion& rhs, float t) const
{
   Quaternion rhsTemp = rhs;
    // Favor accuracy for native code builds
    float cosAngle = DotProduct(rhsTemp);
...
    rhsTemp = -rhsTemp ;
...
   return *this * t1 + rhsTemp * t2;
}

**Comment by eugeneko** [comment]
Why?

**Comment by Commondor** [comment]
This is only a cosmetic change: to pass to the function a constant reference, not a copy of the object. This is C++.   :)))

**Comment by cadaver** [comment]
Just a sidenote (also goes for anyone else) you're not really doing yourself a favor by using smileys on the issue tracker.
