### ISSUE TITLE
Proper new project setup?

### ISSUE THREAD

**Issue by VinnyVicious** [urho3d/Urho3D#1839]
So far, i've been toying around with Lua scripts and the Urho3D player, in order to understand the engine and learn from the docs and examples. However, i'm now planning to start working on the actual project, but i'm not sure how to start:

* Is there a sample CMakeLists.txt file for new Urho3D-based projects?
* Can i link Urho3D statically? 
* Where i should keep my assets? What about my shaders?

**Comment by eugeneko** [comment]
1) Check docs.
2) Yes
3) Somewhere in resource folders. Shaders shall be placed in `Shaders/HLSL` or `Shaders/GLSL`.
