### ISSUE TITLE
Missing licenses in bin/ 

### ISSUE THREAD

**Issue by Alex-doc** [urho3d/Urho3D#1844]
Hello, I've noticed that there are no license headers or files for almost everything in "bin/" and its subdirectories(for instance, see the shaders). 

I also cannot find anywhere the licensing information for the art/sounds/texture assets.

I think it would be useful to have them in place.

**Comment by cadaver** [comment]
Look at the bottom README.md to see where the assets come from. In cases where the license requires the license or copyright information to be distributed with the file, it is included in the same directory.

If the asset is not any of the listed, then assume it's created by the Urho authors and has the same license as Urho3D code. In particular shaders don't have the MIT license header, to reduce runtime overhead when loading and later compiling them.

This could be clarified in the documentation though.

**Comment by Alex-doc** [comment]
Thank you for clearing that up.
