### ISSUE TITLE
broken non c++11 compilation

### ISSUE THREAD

**Issue by alex-rass-88** [urho3d/Urho3D#1845]
If compiler does not support c++11, urho3d can not be compiled.
(strtoll and strtoull available since c++ 11, vs 2010 can't build urho3d)

problem after commit:
https://github.com/urho3d/Urho3D/commit/6a7a57eace7a87f2921c0e3ce9b609a397faeaa7

**Comment by Florastamine** [comment]
Does the following work? 

`#define strtoll _strtoi64`
`#define strtoull _strtoui64`

**Comment by alex-rass-88** [comment]
Yes, it works.

**Comment by weitjong** [comment]
I believe they are available in C99 standard. It looks like we need to auto define the above for older VS.

**Comment by weitjong** [comment]
From a search result, I am quite sure VS 2012 also has this problem. But I am not sure about the VS 2013. Since our CI build using VS 2015 is fine so I am using VS 2015 as the cut over condition.
