### ISSUE TITLE
An unhandled exception occured.

### ISSUE THREAD

**Issue by greatPHPer** [urho3d/Urho3D#1846]
Hi,
I download the sample project from [xamarin website (this link)](https://developer.xamarin.com/guides/cross-platform/urho/introduction/)
then I added 

```
var surface= UrhoSurface.CreateSurface<Sample>(this);
 layout.AddView(surface);
SetContentView(layout);
```
to MainActivity.cs

But when I run it in my AVD, the app opens with title "Urho3d" and in 1 or 2 seconds, an error gets displayed (while debugging in debug mode)
"An unhandled exception occured."

regards
Dhilip

**Comment by weitjong** [comment]
We do not support UrhoSharp issue here.
