### ISSUE TITLE
cmake fails with "d3dcompiler_47.dll not found" on Windows7 64

### ISSUE THREAD

**Issue by faesong** [urho3d/Urho3D#1847]
Using Urho3D-1.6-Windows-64bit-SHARED-3D11

Works okay if I copy d3dcompiler_47.dll from Urho3d to C:\Windows\System32

The problem is somehwere when cmake tries to run some test, I presume, and this d3dcompiler_47.dll is not found when running that test...

**Comment by weitjong** [comment]
Could you try with latest master branch.

**Comment by faesong** [comment]
Works fine with master, thank you
