### ISSUE TITLE
Broken Angelscript spherecasts after dae1c615a998e58f0baf4f275ac8693ef54d7f26

### ISSUE THREAD

**Issue by slapin** [urho3d/Urho3D#1850]
Hi, all!
As I updated Urho yesterday I found that most my scripts are broken.
What is mostly noticeable, Raycasts and SphereCasts are broken badly.
I bisected the issue to commit
dae1c615a998e58f0baf4f275ac8693ef54d7f26

Any ideas what is going on?
C++ stuff works fine.

**Comment by slapin** [comment]
Broken means it returns strange results for ray and sphere collisions,
like ray from point 0,0,0 direction -1,0,1 casts to length 1.5 and gets collision
at -63, 0.4, 20 which is very very weird. Starting from this commit things break,
the problem is not reproducible before this commit.

**Comment by cadaver** [comment]
Please show code. I had to "fix" one vector math equation from the editor that did not appear to be wrong, but changing the operation order fixed it.

**Comment by eugeneko** [comment]
Oh, soo... It seems that we have some nasty arithmetic bug in new AS.

**Comment by slapin** [comment]
Well, the problem is my code is too big and I don't know if minimal
program will be representable.
Well, the raycast funtion is this:

enum RCTYPES {
    RC_SPHERECAST,
    RC_RAYCAST
};

class CollisionRay {
    String name;
    protected int pass;
    protected Ray request;
    protected RCTYPES type;
    protected float distance, radius;
    protected uint mask;
    PhysicsRaycastResult result;
    CollisionRay(String name, int pass, const Ray&in request, RCTYPES type,
            uint mask,
            float distance = 1.5f, float radius = 0.3f)
    {
        this.name = name;
        this.request = request;
        this.pass = pass;
        this.request = request;
        this.type = type;
        this.distance = distance;
        this.radius = radius;
        this.mask = mask;
    }
    void update(int pass)
    {
        if (pass != this.pass)
            return;
        Print("Updating pass: " + pass);
        Print("Ray name: " + name);
        switch(type) {
        case RC_SPHERECAST:
            result = sc.physicsWorld.SphereCast(request,
                    distance, radius, mask);
        case RC_RAYCAST:
            result = sc.physicsWorld.RaycastSingle(request,
                    distance, mask);
            break;
        }
        if (result.body !is null)
            Print("CollisionRay: " + name + " triggered [" +
request.origin.ToString() + " " + request.direction.ToString() + "] "
+ result.body.collisionLayer);

    }
};


class CollisionRayList
{
    protected Array<CollisionRay@> rays;
    protected int num_passes;
    protected int current_pass;
    void add(String name, int pass, const Ray&in request, RCTYPES type,
            uint mask,
            float distance = 1.5f, float radius = 0.3f)
    {
        rays.Push(CollisionRay(name, pass, request, type, mask,
distance, radius));
        if (num_passes < pass + 1)
            num_passes = pass + 1;
    }
    void add(String name, int pass, const Vector3&in origin,
            const Vector3&in direction, RCTYPES type,
            uint mask,
            float distance = 1.5f, float radius = 0.3f)
    {
        Ray request(origin, direction);
        rays.Push(CollisionRay(name, pass, request, type, mask,
distance, radius));
        if (num_passes < pass + 1)
            num_passes = pass + 1;
    }
    CollisionRayList(int max_passes)
    {
        num_passes = max_passes;
    }
    void update()
    {
        for (int i = 0; i < rays.length; i++)
            rays[i].update(current_pass);
        current_pass++;
        if (current_pass >= num_passes)
            current_pass = 0;
    }
    PhysicsRaycastResult get(String name)
    {
        for (int i = 0; i < rays.length; i++)
            if (rays[i].name == name)
                return rays[i].result;
        return PhysicsRaycastResult();
    }
}

class BehaviorCollisionRayList: CollisionRayList {
    BehaviorCollisionRayList()
    {
        super(1);
    }
    void update(Node@ node)
    {
        Ray frontray(node.worldPosition + node.worldRotation *
Vector3(0.0, 0.65, 0.4), node.worldDirection);
        Ray frontleftray(node.worldPosition + node.worldRotation *
Vector3(-0.1, 0.6, 0.4), Quaternion(0.0, -10.0, 0.0) *
node.worldDirection);
        Ray frontrightray(node.worldPosition + node.worldRotation *
Vector3(0.1, 0.6, 0.4), Quaternion(0.0, 10.0, 0.0) *
node.worldDirection);
        Ray frontlray(node.worldPosition + node.worldRotation *
Vector3(-0.1, 0.4, 0.4), Quaternion(0.0, -30.0, 0.0) *
node.worldDirection);
        Ray frontrray(node.worldPosition + node.worldRotation *
Vector3(0.1, 0.4, 0.4), Quaternion(0.0, 30.0, 0.0) *
node.worldDirection);
        Ray frontl2ray(node.worldPosition + node.worldRotation *
Vector3(-0.1, 0.4, 0.4), Quaternion(0.0, -45.0, 0.0) *
node.worldDirection);
        Ray frontr2ray(node.worldPosition + node.worldRotation *
Vector3(0.1, 0.4, 0.4), Quaternion(0.0, 45.0, 0.0) *
node.worldDirection);
        Ray frontl3ray(node.worldPosition + node.worldRotation *
Vector3(-0.1, 0.4, 0.4), Quaternion(0.0, -60.0, 0.0) *
node.worldDirection);
        Ray frontr3ray(node.worldPosition + node.worldRotation *
Vector3(0.1, 0.4, 0.4), Quaternion(0.0, 60.0, 0.0) *
node.worldDirection);
        rays.Clear();
        add("front", 0, frontray, RC_RAYCAST,
STATIC_LAYER|VEHICLE_LAYER|CHARACTER_LAYER, 1.5);
        add("frontleft", 0, frontleftray, RC_RAYCAST,
STATIC_LAYER|VEHICLE_LAYER|CHARACTER_LAYER, 1.8);
        add("frontright", 0, frontrightray, RC_RAYCAST,
STATIC_LAYER|VEHICLE_LAYER|CHARACTER_LAYER, 1.8);
        add("frontl", 0, frontlray, RC_RAYCAST,
STATIC_LAYER|VEHICLE_LAYER|CHARACTER_LAYER, 2.1);
        add("frontr", 0, frontrray, RC_RAYCAST,
STATIC_LAYER|VEHICLE_LAYER|CHARACTER_LAYER, 2.1);
        add("frontl2", 0, frontl2ray, RC_RAYCAST,
STATIC_LAYER|VEHICLE_LAYER|CHARACTER_LAYER, 2.5);
        add("frontr2", 0, frontr2ray, RC_RAYCAST,
STATIC_LAYER|VEHICLE_LAYER|CHARACTER_LAYER, 2.5);
        add("frontl3", 0, frontl3ray, RC_RAYCAST,
STATIC_LAYER|VEHICLE_LAYER|CHARACTER_LAYER, 2.8);
        add("frontr3", 0, frontr3ray, RC_RAYCAST,
STATIC_LAYER|VEHICLE_LAYER|CHARACTER_LAYER, 2.8);
        CollisionRayList::update();
    }
};

The BehaviorCollisionRayList:update() is run each frame (from
FixedUpdate()). This is work in progress code, so don't mind bloat.
If more code is required, I can email that personally (not yet ready
for public).

How it is run:
class NPC: Character {
...
    BehaviorBlackBoard@ bb;
    void Init()
    {
...
        bb = BehaviorBlackBoard(node);
...
    }
    void FixedUpdate(float timeStep)
    {
...
        bb.update();
...
    }
...
}



Reverting the mentioned commit fixes the problem completely, so it is
workaround for people who struggle with this here and now.

**Comment by cadaver** [comment]
Thanks. Your code isn't showing significant math, at least in preparation to the spherecast, so it looks like math objects getting wrong contents. There's one fixed bug in AngelScript WIP version which has to do with undesired temp variable reuse, which could be related here.

**Comment by slapin** [comment]
well, the fix doesn't look too big https://sourceforge.net/p/angelscript/code/2375/
will try a bit later and see.

**Comment by slapin** [comment]
Well, I confirm that patch at https://sourceforge.net/p/angelscript/code/2375/ fixes my problem, so I see 2 options
- nasty - update AngelScript. Probably adventurous path.
- Just apply the following patch:

```diff
diff --git a/Source/ThirdParty/AngelScript/source/as_compiler.cpp b/Source/ThirdParty/AngelScript/source/as_compiler.cpp
index 46745fc4f..b1f2b59b6 100644
--- a/Source/ThirdParty/AngelScript/source/as_compiler.cpp
+++ b/Source/ThirdParty/AngelScript/source/as_compiler.cpp
@@ -11197,6 +11197,8 @@ int asCCompiler::FindPropertyAccessor(const asCString &name, asCExprContext *ctx
                ctx->property_get = getId;
                ctx->property_set = setId;
 
+               bool isHandleSafe = ctx->type.isHandleSafe;^M
+^M
                if( ctx->type.dataType.IsObject() )
                {
                        // If the object is read-only then we need to remember that
@@ -11228,6 +11230,10 @@ int asCCompiler::FindPropertyAccessor(const asCString &name, asCExprContext *ctx
                ctx->type.isTemporary = isTemp;
                ctx->exprNode = node;
 
+               // Remember if the object is safe, so the invocation of the property^M
+               // accessor doesn't needlessly make a safe copy of the handle^M
+               ctx->type.isHandleSafe = isHandleSafe;^M
+^M
                // Store the argument for later use
                if( arg )
                {
@@ -12534,9 +12540,16 @@ int asCCompiler::CompileOverloadedDualOperator2(asCScriptNode *node, const char
                // Did we find an operator?
                if( ops.GetLength() == 1 )
                {
+                       // Reserve the variables used in the right expression so the new temporary^M
+                       // variable allocated for the left operand isn't accidentally overwritten.^M
+                       int l = int(reservedVariables.GetLength());^M
+                       rctx->bc.GetVarsUsed(reservedVariables);^M
+^M
                        // Process the lctx expression as get accessor
                        ProcessPropertyGetAccessor(lctx, node);
 
+                       reservedVariables.SetLength(l);^M
+^M
                        asCExprContext tmpCtx(engine);
                        if (leftToRight)
                        {
@@ -12546,7 +12559,7 @@ int asCCompiler::CompileOverloadedDualOperator2(asCScriptNode *node, const char
                                {
                                        // Reserve the variables used in the right expression so the new temporary
                                        // variable allocated for the left operand isn't accidentally overwritten.
-                                       int l = int(reservedVariables.GetLength());
+                                       l = int(reservedVariables.GetLength());^M
                                        rctx->bc.GetVarsUsed(reservedVariables);
 
                                        if (lctx->type.dataType.SupportHandles())
```

**Comment by slapin** [comment]
In retrospect - to avoid later surprises - probably we need to add some AngelScript API tests to CI?
That could help to see some basic breakage early.

**Comment by cadaver** [comment]
Thanks for testing. It will be easiest to just apply the commit that fixes this specific issue. As for CI tests, it's obvious to test for all samples starting without crashing, but to actually check for API results is far more involved.

**Comment by slapin** [comment]
I think we could add a few sanity checks like a few lines in dedicated sample,
shouldn't be too hard to implement. Like setup scene with cube and try  to raycast it from 4 sides,
and exit with error in case raycast doesn't cast when should and casts when it should not.
And add tests to that sample as soon as we encounter more problems, to avoid future regressions.
