### ISSUE TITLE
Building fails with the latest update of MinGW 

### ISSUE THREAD

**Issue by Florastamine** [urho3d/Urho3D#1853]
The build crashes when building with the latest `MSYS2`/`MinGW` or `MSYS2`/`MinGW-W64` (`g++-6.3.0`). Not Urho's fault, though, because it fails when building SDL2 XInput (`Source\ThirdParty\SDL\src\core\windows\SDL_xinput.h`) due to the double definition of `XINPUT_GAMEPAD_EX` and `XINPUT_STATE_EX` inside both SDL2 and MinGW headers, which does not happen when building with earlier versions of `MinGW`. 

It can be easily fixed by either re-naming the definition on either side (to `XINPUT_GAMEPAD_EX2`, for example). 

Seems like others also experienced this as well: https://github.com/rdp/ffmpeg-windows-build-helpers/issues/204 

![](http://i.imgur.com/lvPp44w.jpg)

**Comment by alex-rass-88** [comment]
In mingw header xinput.h copypasted xbox controller helpers from sdl2.

**Comment by weitjong** [comment]
Duplicate of #1493. MSYS2 Makefile is not (yet) supported.

**Comment by Florastamine** [comment]
@weitjong 
Actually it fails even with `-G "MinGW Makefiles"`. You do not need MSYS2 for the build. I should rephrase the question to only include MinGW and not MSYS2.

**Comment by weitjong** [comment]
I see. Can use another MinGW-W64 project instead, like the one we have been CI tested almost everyday. The CI is using a latest version (6.3.0 also) downloaded from [here](https://sourceforge.net/projects/mingw-w64/).

**Comment by Florastamine** [comment]
Hmm, strange. Looks like recent updates to MSYS2's MinGW(-W64) changed `xinput.h` which caused the compilation error above. Not a compiler issue though. I'll close  this as it's not related to the engine, but I thought I'd let other MSYS2 users know.
