### ISSUE TITLE
ParticleEmitter has a bug.

### ISSUE THREAD

**Issue by Commondor** [urho3d/Urho3D#1854]
_SetAutoRemoveMode(REMOVE_NODE)_ and _SetAutoRemoveMode(REMOVE_COMPONENT)_ is not work for ParticleEmitter and ParticleEffect with **activetime value=0** when I call **SetEmitting(false)**:

void ParticleEmitter::SetEmitting(bool enable)
{
    if (enable != emitting_)
    {
        emitting_ = enable;
        **sendFinishedEvent_ = enable;**
        periodTimer_ = 0.0f;
        // Note: network update does not need to be marked as this is a file only attribute
    }
}

Perhaps need to do:
**sendFinishedEvent_ = !enable;**

This is necessary for the removal of particles after use. For example, the flight of a rocket and its smoky trace.

**Comment by cadaver** [comment]
Looks like sendFinishedEvents should be set whenever the emission mode is changed, because we can get to the state of no particles both ways (either timer expiring, or turning off manually)

**Comment by Commondor** [comment]
But sendFinishedEvents is only for call finish emitting. Is not it?

**Comment by cadaver** [comment]
Will have to re-check. The criteria for being finished should be "no longer emitting + current particles have all died" in which case it's safe to remove the component (if desired) without visual artifacts.

**Comment by Commondor** [comment]
I found another error:
`
void ParticleEmitter::SetEffectAttr(const ResourceRef& value)
{
    ResourceCache* cache = GetSubsystem<ResourceCache>();
    SetEffect(cache->GetResource<ParticleEffect>(value.name_));
}
void ParticleEmitter::SetEffect(ParticleEffect* effect)
{
    if (effect == effect_)
        return;

    **Reset();**
   ...
}
void ParticleEmitter::Reset()
{
    RemoveAllParticles();
    ResetEmissionTimer();
    **SetEmitting(true);**
}
`
My code:

" m_pSmokeTrail->SetEnabled	( true );
   m_pSmokeTrail->SetEmitting	( false );
   m_pSmokeTrail->SetEffectAttr     ( ResourceRef ( String("Particle"), m_sSmokeWheel ) );
"	

These lines of code work in different ways, because call Reset().

" m_pSmokeTrail->SetEffectAttr     ( ResourceRef ( String("Particle"), m_sSmokeWheel ) );
   m_pSmokeTrail->SetEnabled	( true );
   m_pSmokeTrail->SetEmitting	( false );"

**Comment by cadaver** [comment]
It is proper that the effect is changed first, which (must) cause reset of internal state. Only after that you should set the emitting state. I don't consider that an error. When in doubt, look at the order in which attributes are registered, when there are tricky interdependencies the attribute order tells also the correct order to change them.
