### ISSUE TITLE
Mouse events not working on Sierra

### ISSUE THREAD

**Issue by sabotage3d** [urho3d/Urho3D#1860]
I am having issues with Mouse events on Sierra. They are not working when I use the open command which opens a new terminal. It looks like it might be related to SDL. To reproduce build the latest Urho3D from master and run 25_Urho2DParticle a few times until it doesn't react to the input.
`open 25_Urho2DParticle`

**Comment by sabotage3d** [comment]
Can someone check it please it might be an issue on other platforms?

**Comment by cadaver** [comment]
Can't reproduce on El Capitan. Will probably upgrade at some point and then retest.

**Comment by weitjong** [comment]
Not able to reproduce it on my "H" Sierra as well.

**Comment by sabotage3d** [comment]
I will try to update to the latest and try again. It is mostly happening with QtCreator, when I press run it actually does something like open process.

**Comment by sabotage3d** [comment]
Just to update these are the settings that I have in my app.
I have mouse visible to true. I also have touch emulation enabled.
`GetSubsystem<Input>()->SetMouseVisible(true);` 
`GetSubsystem<Input>()->SetTouchEmulation(true);`
These are the events I am using:
E_TOUCHMOVE, E_TOUCHBEGIN, E_TOUCHEND.
I only happens in window mode these are my settings:
`engineParameters_["FullScreen"] = false;
engineParameters_["WindowWidth"] = 1200/2;
engineParameters_["WindowHeight"] = 1920/2;`

**Comment by cadaver** [comment]
Note that if you have touch emulation, it is by design that you will not get mouse events, only touch events.

**Comment by sabotage3d** [comment]
I tested both it just my case at the moment. If the touch emulation is on I am not getting touch events, if I disable the touch emulation I am not getting mouse events. Also I am using SDL raw mouse events they are not working as well. It only happens if I run the app a few times it seems it thinks the window is not in focus as If I click outside the window it minimises and then it receives events again. It might be related to retina or the resolution that I am using it is worth checking if you set the same resolution.
