### ISSUE TITLE
Decal rendering error!!!

### ISSUE THREAD

**Issue by Commondor** [urho3d/Urho3D#1862]
Decals should **always** be drawn **before** particles, shadows and sprites. Now they are **sorted** in a batch and can be drawn **after** particles, shadows and sprites! Decals should be sort only for a owning target. Decals should not be sort from distance camera for a owning target.

  Drawable* hitDrawable; 
   if (Raycast(250.0f, hitPos, hitDrawable))
    {
        // **## Check if target scene node already has a DecalSet component. If not, create now**
        Node* targetNode = hitDrawable->GetNode();
	DecalSet* decal = **targetNode->GetComponent<DecalSet>();**
        if (!decal)
        {
            ResourceCache* cache = GetSubsystem<ResourceCache>();
            decal = targetNode->CreateComponent<DecalSet>();
		static bool trg = true;
		if (trg)
		{
			decal->SetMaterial(cache->GetResource<Material>("Materials/UrhoDecal.xml"));
		} 
		else
		{
			decal->SetMaterial(cache->GetResource<Material>("Materials/UrhoDecal2.xml"));
		}
		trg = !trg;
        }
        // Add a square decal to the decal set using the geometry of the drawable that was hit, orient it to face the camera,
        // use full texture UV's (0,0) to (1,1). Note that if we create several decals to a large object (such as the ground
        // plane) over a large area using just one DecalSet component, the decals will all be culled as one unit. If that is
        // undesirable, it may be necessary to create more than one DecalSet based on the distance
        decal->AddDecal(hitDrawable, hitPos, cameraNode_->GetRotation(), 3.5f, 1.0f, 1.0f, Vector2::ZERO,
            Vector2::ONE);
    }

For example:

Particles is under a decal:
![screenshot](https://cloud.githubusercontent.com/assets/9081571/23890157/28945086-0899-11e7-93b9-53ad90c9ff70.jpg)

The shadow from the tank is under decals:
![screenshot_3](https://cloud.githubusercontent.com/assets/9081571/23891530/87f848c4-089f-11e7-90ec-5a7f24037915.jpg)

Sort decals is to change from camera:
![screenshot_1](https://cloud.githubusercontent.com/assets/9081571/23891555/ac8d3c76-089f-11e7-86a7-79cd433b1c63.jpg)
![screenshot_2](https://cloud.githubusercontent.com/assets/9081571/23891554/ac8cd9ac-089f-11e7-95c7-04e3735afa17.jpg)

**Comment by cadaver** [comment]
The engine does not have hardcoded rules to render order (the render sorting part doesn't "think" of decals as any differently) Instead you control it through the renderpath, and passes you use in materials. Furthermore you can use Material::SetRenderOrder() to set order within pass. I'm going to commit a change to the default decal materials to demonstrate.
