### ISSUE TITLE
E_COMPONENTREMOVED  EventHandler not triggered if Node is removed

### ISSUE THREAD

**Issue by elix22** [urho3d/Urho3D#1864]
Having a Node with multiple components
Subscribing both to  E_NODEREMOVED   & E_COMPONENTREMOVED  (having 2 EventHandlers )

Once removing that Node  from the Scene ( Node::Remove() )
**Expected behaviour ( I might be wrong)**
I would expect  both EventHandlers to be called 
Once for the E_NODEREMOVED   EventHandler
Multiple times for E_COMPONENTREMOVED  EventHandler (depends on components amount)

**Actual behaviour** 
Only  the E_NODEREMOVED   EventHandler  is called .

**It  is caused due to the fact that** 

Scene::NodeRemoved(Node* node) 
{
...
   node->ResetScene();      // scene_ = 0  
}

void Node::RemoveComponent(Vector<SharedPtr<Component> >::Iterator i)
{
    if (Refs() > 0 && scene_)  // scene_ =0  event is not sent
    {
         ...
          scene_->SendEvent(E_COMPONENTREMOVED, eventData);
    }
}

**Comment by eugeneko** [comment]
Moreover, you will not get events for removed children of your node.
Extra events are unnecessary and may degrade performance, so I like current behavior.

**Comment by elix22** [comment]
Yes , 
I understand the performance  concerns .
In my day job I am optimizing AOSP code on specific mobile devices  :) 
However there is also an thing called consistency .
If one subscribes to an event , regardless of the state/scenario , the relevant  EventHandler  should be called.
As I mentioned , I am not sure it's an issue , maybe it should be noted in the documentation 
(I managed to modify the code locally to fit my needs.)
Just my 2 cents

**Comment by eugeneko** [comment]
I agree that it should be mentioned, I had the same problems some time ago.
There is a consistency: both Add-events and Remove-events for both nodes and components are called for the top-most item in hierarchy because it provides enough information for any use-case and is lightweight enough to avoid lags on e.g. scene destruction if one have some non-trivial logic in such events.
