### ISSUE TITLE
UIElement* GetChild(index) fails in lua

### ISSUE THREAD

**Issue by Mike3D** [urho3d/Urho3D#187]
Even after reordering exposition to lua, UIElement\* GetChild(unsigned index) still doesn't work.

**Comment by weitjong** [comment]
I am sorry that I have to bring this old issue up again. I could not understand nor see why the GetChild(unsigned index) overload would have failed after it being declared last in the pkg file. I have reverted back the changes in the tolua_is.c and have verified that both GetChild() overloads work as intended without these change. So now, both tolua_isnumber and tolua_isstring will return true for anything that convertible to number and convertible to string, respectively, as per original lapi.c implementation. The reason for the revert is to give back the type-less feature of Lua. I am still in the middle of optimizing the Variant.pkg bindings. I expect both these two below to work equally. I should an integer stored in a Variant in both cases.
```
    local test2 = Variant(VAR_INT, 100)
    print(test2.typeName, test2:Get())
    local test2 = Variant(VAR_INT, "100")
    print(test2.typeName, test2:Get())
```
It was not before the revert.

The changes are still in my local branch. Give me a shout if you have any concerns.
