### ISSUE TITLE
Forgotten Camera::autoAspectRatio_

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#1873]
```
        camera->SetOrthographic(true);
        camera->SetOrthoSize(2.0f);
```
![3](https://cloud.githubusercontent.com/assets/13021826/24239642/ce19bb36-0fbf-11e7-83a7-6bfc7193a219.png)
```
        camera->SetOrthographic(true);
        camera->SetOrthoSize(Vector2(2.0f, 2.0f));
        camera->SetOrthoSize(2.0f);
```
![3 -](https://cloud.githubusercontent.com/assets/13021826/24239656/df456c34-0fbf-11e7-9223-cca615024220.png)

**Comment by cadaver** [comment]
The overload taking IntVector2 for non-uniform size disables autoaspectratio, and this is documented.

However, setting a uniform ortho size does not automatically re-enable autoAspectRatio, as we can't be sure that is wanted.

In other words, what you're seeing is expected.

**Comment by 1vanK** [comment]
Thanks for clarifying
