### ISSUE TITLE
RTT Z-Buffer problem on Intel HD graphics

### ISSUE THREAD

**Issue by AramisHM** [urho3d/Urho3D#1876]
![screenshot from 2017-03-25 02-38-43](https://cloud.githubusercontent.com/assets/25241174/24320018/efd48386-110a-11e7-9000-f7bffe7c6532.png)

I've noted this issue in 3 different laptops, 2 running Windows 7 and now 1 running Ubuntu 16.04.
The problem only seems to happen on RTT 's with Intel HD graphics chips.

In attempt to determinate this, I've compiled Urho3D with CMake with OpenGL API. I tested the same generated sample 10_RenderToTexture in a regular desktop with a GTX 970 and in a laptop with the HD graphics both running Ubuntu 16.04 with the same packages installed. The problem only occurred in the laptop with HD graphics.

Specs of the graphic chips used in the test.
Desktop - GeForce - GTX 970/PCIe/SSE2 - OpenGL version string: 4.5.0 NVIDIA 375.39
Laptop - Intel® HD Graphics 5500 (Broadwell GT2) - - OpenGL version string: 3.0 Mesa 17.0.1

There is another user that experienced the same bug here: [http://discourse.urho3d.io/t/rendering-to-texture-inverts-z-buffer-on-intel-hd-graphics/2259](url)

I'm not sure if this is actually a bug or if I've missed something while compiling Urho3D's source.

**Comment by AramisHM** [comment]
Just adding more info: I didn't notice, but the laptop I used in this test also has a Nvidia GeForce 830M. By selecting to use this driver in "Additional Drivers" menu (Ubuntu), the sample 10_RenderToTexture worked as expected.
![screenshot from 2017-03-25 19-38-22](https://cloud.githubusercontent.com/assets/25241174/24326710/2d3cfb80-1193-11e7-8287-7f958756156d.png)

**Comment by cadaver** [comment]
I have a machine with Intel GPU which I could use to test (both Linux + Windows), though I don't remember getting this issue myself. Urho tries to use depth+stencil format for RTTs if possible, which may be the problem.

**Comment by cadaver** [comment]
Tested RenderToTexture sample from the newest HEAD revision on an Intel HD (Haswell) on both Windows & Linux, I couldn't reproduce the issue.
