### ISSUE TITLE
Compilation fails in VisualStudio debug configuration

### ISSUE THREAD

**Issue by elix22** [urho3d/Urho3D#1879]
Using Visual Studio , debug configuration 
If Including both files below causing compilation to fail .
#include <Urho3D/DebugNew.h>
#include "BulletCollision/BroadphaseCollision/btBroadphaseProxy.h"

Removing #include <Urho3D/DebugNew.h>  , compilations is passing successfully

**Comment by iSLC** [comment]
Any specific error message? Probably they both define something which collides :/

**Comment by 1vanK** [comment]
#include <Urho3D/DebugNew.h> always should by last

**Comment by elix22** [comment]
Thanks 1vanK , that solved it.
Basically it is related to redefinition of  the "new" operator in DebugNew.h
Causing compilation failure in BT_DECLARE_ALIGNED_ALLOCATOR
