### ISSUE TITLE
Builds with clang broken

### ISSUE THREAD

**Issue by rokups** [urho3d/Urho3D#1880]
Latest HEAD throws following error when using clang:

```
CMake Error at dep/Urho3D/CMake/Modules/CheckCompilerToolchain.cmake:108 (message):
  Could not check compiler toolchain CPU instruction extension as it does not
  handle '-E -dM' compiler flags correctly
```

**Comment by weitjong** [comment]
Try regenerate your build tree from scratch again, if you have not done so. We have a number of Clang-based CI builds on Travis and they ran just fine.

**Comment by rokups** [comment]
Yeah looks like something broke `add_subdirectory()` workaround. Sigh.
