### ISSUE TITLE
[Bug?] AngelScript binding miss Sort compare function callback support

### ISSUE THREAD

**Issue by slapin** [urho3d/Urho3D#1881]
As Sort works very nicely with classes opCmp, there's flexibility problem as one have to implement class
for each way of sorting, which is very not nice and non-flexible.
AngelScript does support callbacks (even ones attached to object), why not use this mechanism to
support supplying sorting function to a Sort method?

**Comment by slapin** [comment]
Well, 'predicate' is not correct form, 'compare function' is

**Comment by iSLC** [comment]
Most likely for performance reasons. Can you imagine having to call a script function for each comparison. 

You might as well write a script function to sort stuff manually and it'll probably be faster. As in performance not coding speed.

**Comment by slapin** [comment]
I really doubt that calling opCmp for each comparison is any different from calling custom callback.
Just some syntax sugar.

**Comment by JSandusky** [comment]
It's not syntax sugar. opCmp is an intrinsic of a registered type, and CScriptArray is template object working with a type.

I've reached out to Andreas for comment on how to accomplish this best. It may well be currently possible and just in the land of undocumented or obscure.

**Comment by JSandusky** [comment]
I got word back that it's possible. v2.31+ supports a `engine->RegisterFuncdef("T &array<T>::MyCallback(const T&in)")` style for templated funcdef registration.
