### ISSUE TITLE
Postfix binary name to allow different builds in the same directory.

### ISSUE THREAD

**Issue by iSLC** [urho3d/Urho3D#1882]
Basically I would like to include a post-fix or something in the `Urho3D.dll/so` in order to be able to keep builds with different options in the same folder. So I could do things like `Urho3D_DX9.dll`, `Urho3D_DX11.dll`, `Urho3D_GL.dll` etc.

Is there something already similar in the build system? Maybe I missed it.

**Comment by weitjong** [comment]
No, there is no such support in the build system.
