### ISSUE TITLE
Getting Started Template

### ISSUE THREAD

**Issue by Borderliner** [urho3d/Urho3D#1888]
I'm new to this engine, and I'm not that much pro when it comes to C++. So it would be amazing if there was a Getting Started template to kickstart a simple structure. There is [one already](https://github.com/damu/UrhoSampleProject), but it's not official and has not been updated for a while.

**Comment by 1vanK** [comment]
What you mean about template? Standart samples have a simple structure. If you need minimal app:
```
#include <Urho3D/Engine/Application.h>
using namespace Urho3D;

class Game : public Application
{
    URHO3D_OBJECT(Game, Application);

public:
    Game(Context* context) : Application(context)
    {
    }
};

URHO3D_DEFINE_APPLICATION_MAIN(Game)
```

**Comment by Borderliner** [comment]
Thank you! I found my answer in the docs, to scaffold a basic project using rake.

**Comment by Modanung** [comment]
Also, if you're using QtCreator you might be interested in [this](https://github.com/LucKeyProductions/QtCreatorUrho3DWizards).

**Comment by Borderliner** [comment]
Amazing! Thanks a bunch!
