### ISSUE TITLE
make shader error logs show the true line number and the source file of the error

### ISSUE THREAD

**Issue by cheece** [urho3d/Urho3D#1889]
hello, since many files are glued together in one single generated string for a shader, when (for example) opengl detects errors on the shaders the log with the information about the errors shows line numbers relative to the generated string, it can be difficult to fix errors that way, it would be better if,  instead of just displaying "ERROR :0:2122 dasdad" it displays "ERROR sourceFile.glsl :0:112 dada " so one knows that the source of the error is in that file and in that line,,

 I haked a bit the code and I have a working implementation for opengl, I just modified the Shader and OGShaderVariation so the output string has tags to identify when starts and ends a file in the generated string, and in the shader error detection a search is performed for the patterns :ERROR: %d:%d: (it is a simple search using the String methods) and the line numbers relative to the generated string are replaced with line numbers relative to the file from what that string section was taken.

**Comment by cheece** [comment]
by the way, i've not made a pull request because i'm not sure if all the implementations of opengl show the errors in that format :ERROR:%d:%d:

**Comment by eugeneko** [comment]
Both HLSL and GLSL have #line directive that IMO is much fair way of doing such things.

**Comment by cheece** [comment]
oh didn't know that!,  i'll make some tests

**Comment by cheece** [comment]
tested, the problem is that "#line directive does not support source files as in C"  https://www.khronos.org/opengl/wiki/Core_Language_(GLSL)#.23line_directive , so i can get the line number but not the source file name

**Comment by JSandusky** [comment]
Yeah, this is an issue. In my local source I have it hackily keep the preprocessed shader source then I find the resource in the resource cache and copy the string into a text editor. It was a huge nightmare when I was doing PBR on GLSL before @dragonCASTjosh took the torch. GLSL definitely suffered for it there.

I recall looking around for a good solution and not finding one. On DX11 it's pretty easy as MSVC's graphics/shader debuggers are pretty good.

**Comment by dragonCASTjosh** [comment]
I normally use #line when working in glsl. as for a solution the only real solution is braking up the shaders in the pipeline

**Comment by eugeneko** [comment]
@cheece #line allows some source index. Can it be used for determining source files?

**Comment by cadaver** [comment]
Agree this is a nasty-ish issue when trying to pinpoint the error in actual source. Could look a bit into different vendors' compilers and see whether the error format is common.

**Comment by cheece** [comment]
@eugeneko that source index is the index of the string being executed, glShaderSource takes an array of strings, usually one passes just one string so there's only an index but it seems like one can put any number there, i think we may set the source index to an integer A + i, being A a large integer, so the procedure is to search in the log for integers larger than A and replace them with the name of the corresponding file, but i don't know if the number of bits assigned to that source index is platform-dependent (like the log format), so one may get  
"ERROR___INTEGER_CONST_OVERFLOW" on some platforms 

about the approach of parsing the log, that is the approach i'm currently using, for the log formats so far i have:

0(35) : error C3008: unknown ... 
ERROR: 0:83: error(#143) Undeclared ident ....

**Comment by eugeneko** [comment]
It is enough to have A=1 ;-)
And then match file names and their indexes, replacing corresponding pieces of error logs.

**Comment by cheece** [comment]
but in that way there's no way of differentiating the file indexes from the line numbers  without implementing a log parser able to handle all log format implementations, so you can't show the file name in the logs, just the file index, although it may work

**Comment by eugeneko** [comment]
I don't remember exact format of HLSL/GLSL error output. However, I can't belive that it is so hard to regex it line-by-line and extract&replace specific number in it.

**Comment by cheece** [comment]
well in the log are other numbers apart from the line number and source string index, so it may be not possible to write a generic parser, 

after thinking and testing I reached the conclusion that it is better if the generated shader source is saved or somehow issued to the user with tags in it identifying source files sections (something like //@source file_name.glsl 444 ). in that way it may be easier to fix errors because you have the whole context in the same file and we don't have to worry about the different shader log formats

**Comment by eugeneko** [comment]
When I worked on my engine, I logged the whole generated shader. However, it is bad soultion in this case, because e.g. Editor console will be spamed with tons of unneeded code.

It is also possible to print list of files to allow user match file index and file name.
Such information can be printed in log cause there are at most few dozens incuded files.
And finally, HLSL support #line directive with string file name.

**Comment by cheece** [comment]
yeah, logging it would be a bad idea, but it may be saved to disk also, so you just show in the logs something like "generated shader source written to ./generated/myshader.glsl", and yeah, the other option of showing a file index before the error and using \#line is nice too

**Comment by JSandusky** [comment]
Assuming the line numbers can be reliably pulled from the error messages the include preprocessor could keep track of the involved files and their line counts.

Getting the correct file and line would just be looping through the records and subtracting off the line until the current # is contained in the file (same thing as when doing a weighted random selection, keep taking until you find the right bucket).

---

Unfortunately, shader error messages are as nasty as template error messages.

**Comment by cheece** [comment]
true, the implementation I have is like that, but it can't be integrated since it's not general, error message format depends on the opengl implementation...
