### ISSUE TITLE
Probably leak of NodeImpl (missed delete impl_)

### ISSUE THREAD

**Issue by MonkeyFirst** [urho3d/Urho3D#1890]
Hi, 
I see how it allocates some mem for impl_ struct, but in same time I don't see any deletions of this (delete impl_;) in Node.cpp
so, mb this is leak place?
'''
Node::Node(Context* context) :
{
    impl_ = new NodeImpl();
    impl_->owner_ = 0;
}
'''

**Comment by yushli** [comment]
impl_ is UniquePtr. It will clean up with reference count.

**Comment by MonkeyFirst** [comment]
Yes, you are right, it fine deleted with helps UniquePtr's destructor.
