### ISSUE TITLE
macOS universal binary CI build failed

### ISSUE THREAD

**Issue by weitjong** [urho3d/Urho3D#1895]
I guess we should not be surprised that out of the blue homebrew "readline" (a very minor/optional library dependency that we could do without) decided to provide only x86_64 arch in its latest version instead of universal binary containing both i386 and x86_64 archs like it used to, because Apple has been phasing out the 32 bit support for years now. But because of that, now our universal binary CI build failed for the i386 arch. Our CI build is still configured to do universal binary build simply because our build system is capable of doing so and it is kind of cool, at least to me. But sentiment aside, I would like to ask whether it is really time now to phase out 32 bit mode in our macOS build?

**Comment by cadaver** [comment]
It's fine by me, since 64bit CPU has been mandatory in updated OSX versions for a long time.

**Comment by weitjong** [comment]
Ok. I will set the build system to default to a 'normal' build instead of universal binary build when targeting macOS platform.
