### ISSUE TITLE
MinGW-w64 XInput SDL compiling error

### ISSUE THREAD

**Issue by JTippetts** [urho3d/Urho3D#1899]
Compiling on a brand new MinGW install:

Mingw-builds ver 6.3.0 x64

Compiling ThirdParty/SDL/src/core/windows/SDL_xinput.c give re-definition errors for the structures typedef'ed as XINPUT_GAMEPAD_EX and XINPUT_STATE_EX, for having already been defined in the xinput.h header in the mingw install. Removing these struct declarations from SDL_xinput.h fixes the issue as a hack fix.

**Comment by cadaver** [comment]
Can see how SDL eventually fix this themselves. Possibly via MinGW version check, which isn't very clean either.

**Comment by Florastamine** [comment]
I encountered the same thing before, as outlined in issue #1853. Earlier versions of MinGW-W64 works just fine, but recent updates just broke the build.

**Comment by weitjong** [comment]
As commented before, this does not appear to be a generic issue that affect all the MinGW-W64 ver 6.3.0 out there. Thus, we could simply delete the struct definition in the SDL or it would break those that do not provide the definition internally. We could, however, add more detection logic on CMake side to automatically hide/unhide the definition using a compiler define. Like Lasse has said, eventually SDL devs would probably do that. So, the question is really, do we want to do it ahead of SDL?

**Comment by cadaver** [comment]
What I find curious is that the _EX structures are not defined in Windows' SDK's own xinput.h, so recent MinGW adds them as extra.

I certainly have nothing against fixing it early (if e.g. you have energy to spare), just means a possible revert further down the line when merging new SDL.

**Comment by weitjong** [comment]
Ok, but not sooner than after I switch my boot partition back to Linux 😄 .

**Comment by alex-rass-88** [comment]
Mingw-w64 headers 5.02 fix with problem

**Comment by weitjong** [comment]
Even the header version 5 revision 1 that we currently use in AppVeyor doesn't have this issue. See https://github.com/urho3d/Urho3D/blob/master/.travis.yml#L160-L161
The problem is, there are a few "vendors" who distribute MinGW-W64 on Windows platform besides the one you just mentioned, and the others (at least the MSYS2) seem to get it wrong by including the "extra" in their header.

**Comment by alex-rass-88** [comment]
I made a mistake. In the branch 5.x duplicate macros not present, they appeared in master. MSYS2 using latest headers.

**Comment by iSLC** [comment]
Well, good luck trying to pinpoint the exact MinGW revision. All you can detect is up to `5.0`. So far I haven't been able to find a way to detect the `.2` via macros or something.

**Comment by weitjong** [comment]
Well, obviously it should not be done by detecting that. Instead we should detect whether a structure is defined or not.

**Comment by iSLC** [comment]
One thing though. I was actually compiling for OpenGL and this still occurred. XInput was not limited to just DirectX.

**Comment by weitjong** [comment]
Yes, this is a known fact. Even when using OpenGL graphics API, the DirectX input may still be required.
