### ISSUE TITLE
Compile fail with -DURHO3D_IK=0 

### ISSUE THREAD

**Issue by OldSnake22** [urho3d/Urho3D#1907]
When i try to compile the engine without the IK module. Visual studio fail to compile Context::RequireIK() and void Context::ReleaseIK() functions. 

It seems that those function are not encapsulated inside any define like #ifndef URHO_IK

**Comment by TheComet93** [comment]
Thanks for reporting, this should fix it: https://github.com/urho3d/Urho3D/pull/1908
