### ISSUE TITLE
Trouble from viewport to image file

### ISSUE THREAD

**Issue by vivienneanthony** [urho3d/Urho3D#1912]
Hi

This is quick. I'm trying to take  a image of the viewport, create a new texture, then save it to disk. I think I have most of the code correct but something is wrong Anyway help appreciated.

Vivienne

```
// Set to the active camera
	Image * OutputImage(new Image(context_));
	Texture2D * pRenderTexture(new Texture2D(context_));
	Texture2D * pDepthTexture(new Texture2D(context_));

	// Set width and height
	const unsigned int outputHeight = 900;
	const unsigned int outputWidth = 1440;

	// Set Image
	OutputImage->SetSize(outputWidth, outputHeight,  4);

	// Create necessary texture
	pRenderTexture->SetSize(outputHeight, outputWidth, m_textureFormat, TEXTURE_RENDERTARGET);
	pDepthTexture->SetSize(outputHeight, outputWidth, Graphics::GetDepthStencilFormat(), TEXTURE_DEPTHSTENCIL);

	// Set parameneters
	pRenderTexture->SetFilterMode(FILTER_NEAREST);
	pDepthTexture->SetFilterMode(FILTER_NEAREST);

	RenderSurface * pRenderSurface = pRenderTexture->GetRenderSurface();

	// Set Render Surface
	pRenderSurface->SetViewport(0, m_pCameraViewport);
	pRenderSurface->SetUpdateMode(SURFACE_UPDATEALWAYS);
	pRenderSurface->SetLinkedDepthStencil(pDepthTexture->GetRenderSurface());

	// Queue Update
	pRenderSurface->QueueUpdate();

	unsigned char* _ImageData = new unsigned char[outputWidth*outputHeight*4];
	pRenderTexture->GetData(0, _ImageData);

	OutputImage->SetData(_ImageData);

	OutputImage->SaveTGA("snapshoot.tga");

	pRenderTexture->SaveTGA("test.tga");
```

**Comment by eugeneko** [comment]
So, what's wrong?
PS: names like _ImageData are forbidden for usage in c++ standard

**Comment by 1vanK** [comment]
bool Graphics::TakeScreenShot(Image& destImage) ?

**Comment by vivienneanthony** [comment]
The render better yet render texture just dont save. I created a texture for rendet, depth, and image. I use the texture and link it to a rendersurface. I have 2 viewports being the main screen full screen and camera. Basically to take a snapshoot. I. am doing a third to output the camera that can saved to file anysize. 

The camera view use similiar code so im not sure whats up.

**Comment by cadaver** [comment]
QueueUpdate does not do immediate render, so you would only have contents after the next frame has completed.

**Comment by vivienneanthony** [comment]
Thanks.  I figured it out. Which pop up another issue.

:)
