### ISSUE TITLE
How to setup travis-ci?

### ISSUE THREAD

**Issue by xiliu98** [urho3d/Urho3D#1915]
I had forked this repo and pushed to travis-ci. Currently travis-ci would compile it with gcc clang mingw.
I want to compile with other plateform and auto upload the compiled binary to sourceforge like this: https://sourceforge.net/projects/urho3d/files/Urho3D/
How to do?

**Comment by weitjong** [comment]
I think this is off-topic here. Even if the feature to process multiple documents in a single yaml stream is supported out of the box by Travis-CI, you should have actually asked your question there in their forum or issue tracker (not to mention Travis-CI actually do not support this feature). I have requested the feature and proposed a workable solution to them a few years ago but for some reason they have shot it down and respect their decision. Probably (this is just my guess) they don't want their worker VMs from being abused when suddenly everyone decides to have a big build matrix than one actually needs. In short, the technique (or hack) that we developed and used to achieve this feat is totally unsupported at best and it may break anytime at worst. Perhaps one day I will blog about it, but not here, not now.
