### ISSUE TITLE
Fullscreen rendering fails on Retina display on Sierra

### ISSUE THREAD

**Issue by cadaver** [urho3d/Urho3D#1917]
When a Retina (high DPI) full screen mode is initialized, possibly the framebuffer sizing goes wrong, and therefore the viewport Graphics tries to set is out of bounds and rendering fails except for clearing to the fog color.

Borderless fullscreen works. This is likely an SDL issue. Would possibly be worth investigating using a standalone test app and/or newest SDL2 master. I don't find discussion on the SDL forums, but this GLFW issue is similar:

https://github.com/glfw/glfw/issues/953

**Comment by thesquib** [comment]
Setting HighDPI to false is another work around. I've investigated this a little but I still haven't found the root of the problem.

**Comment by thesquib** [comment]
I dropped in SDL 2.0.7 from https://github.com/urho3d/SDL-mirror/tree/release-2.0.7-modified-for-urho3d and this appears to have fixed this issue, however now there is an Assertion Failure. I have not investigated this yet, so it may be unrelated:
Assertion failure at SDL_SetWindowPosition (Urho3D/Source/ThirdParty/SDL/src/video/SDL_video.c:1804), triggered 1 time:
  'window && window->magic == &_this->window_magic'

**Comment by weitjong** [comment]
That branch is not yet ready for general users. I got that too on Linux platform and I have not investigated that too. I will come back to that after completing  few more items in my todo list in relation to this SDL upgrade work. But of course, you are welcome to help to pinpoint the root cause.

**Comment by thesquib** [comment]
The issue exists in release-2.0.6-modified-for-urho3d, release-2.0.5-modified-for-urho3d, release-2.0.4-modified-for-urho3d.
It does not exist in release-2.0.3-modified-for-urho3d, although the screen size and position is rendered incorrectly. 

A variety of interesting looking bugs and changes have happened recently to SDL_cocoawindow.m
So this could be the place to start looking. See-
https://hg.libsdl.org/SDL/log/d131f3193794/src/video/cocoa/SDL_cocoawindow.m

**Comment by weitjong** [comment]
Can you check out if this dev WIP branch `https://github.com/urho3d/Urho3D/tree/upgrade-sdl-2.0.7` works for you. Thanks.

**Comment by thesquib** [comment]
I tested the C++ samples, the Urho3DPlayer with the lua and angel scripts, and ninja war. Fullscreen seems to work as expected. 

There is an issue though, and this could be an unrelated issue because i haven't tested this before. Switching from fullscreen to a window using alt-tab produces a very large window which is largely offscreen. This is printed after pressing alt-tab:
> [Sun Nov 19 14:09:50 2017] INFO: Set screen mode 6720x4200 windowed monitor 0
> [Sun Nov 19 14:09:51 2017] DEBUG: Window was moved to -840,45
For that example, the original screen mode was:
> [Sun Nov 19 14:09:46 2017] INFO: Set screen mode 3360x2100 fullscreen monitor 0

**Comment by weitjong** [comment]
I don't have a Retina Mac to reproduce this but just to be sure, did you alt+tab to switch between applications or alt+enter to switch between fullscreen and windowed modes?

**Comment by thesquib** [comment]
Oh sorry that was my mistake. Alt-Enter

**Comment by thesquib** [comment]
There may be something else wrong. The user interface elements are all drawn far too small when using high dpi. I will investigate this some more, it may need a separate issue.

**Comment by eugeneko** [comment]
>  The user interface elements are all drawn far too small when using high
dpi

UI elements are always pixel-precise unless you change UI scale.

2017-11-20 1:24 GMT+03:00 Sam <notifications@github.com>:

**Comment by thesquib** [comment]
Okay, np - false alarm.

**Comment by weitjong** [comment]
Currently the logic to auto double up the UI scale is only implemented inside our Editor script. I think it makes sense to move that logic to UI subsystem instead.

**Comment by thesquib** [comment]
I could take a look at implementing that

**Comment by weitjong** [comment]
Back to the Alt+Enter issue, based on those log entries you provided I think I could guess what have happened. On Retina display, SDL functions may expect parameter and return result in screen coordinate instead of actual pixel. However, internally Urho impl only stores screen dimension  in pixels. So, after one "round trip", the dimension in pixels is wrongly used by Urho when calling an SDL function to create a new SDL window which actually expects dimension in normalized screen coordinate.

**Comment by thesquib** [comment]
Yeah okay I see. This affects all of the sample code except the editor script then.

**Comment by weitjong** [comment]
To be confirmed whether this can be closed now.
