### ISSUE TITLE
Texture artifact  appearing

### ISSUE THREAD

**Issue by vivienneanthony** [urho3d/Urho3D#1920]
Hi

I'm trying to figure out why some textures is not working. At close up everything mostly works, but at some distance when mesh are close there seem to be a conflict.

I place a link because the images are big.

http://imgur.com/a/yyP7q

Vivienne

Some related code
```

// Set camera
	unsigned int factor=2.0f;

	activeView->camera_->SetNearClip(0.01f);
	activeView->camera_->SetFarClip(8192.0f*factor);
	activeView->camera_->SetUseClipping(false);

	Renderer * render= g_pApp->GetRenderer();

	Zone * defaultZone = render->GetDefaultZone();

	defaultZone->SetFogStart(8192.0);
	defaultZone->SetFogEnd(8192.0*factor);

	editorData_->SetActiveCamera(cameraNode_);

	// Set Cull Mode
	render->SetCullMode(CULL_CCW,activeView->camera_);

```

**Comment by vivienneanthony** [comment]
A quick picture of what I mean.

![clip](https://cloud.githubusercontent.com/assets/3378677/25404584/9074bdd4-29ce-11e7-99ad-ebdfa295020d.png)

**Comment by vivienneanthony** [comment]
I also found this http://aras-p.info/blog/2008/06/12/depth-bias-and-the-power-of-deceiving-yourself/

Not sure if it relates

**Comment by cadaver** [comment]
Do you have overlapping geometry that is causing the Z-fighting? Or is it that a (forward rendered) light shined on the object causes the Z-fighting to appear?

In theory, all passes should calculate the same depth value, or you could do depth precision tricks, but ultimately Urho isn't going to "magically" give you more depth buffer resolution at those distances, and this doesn't look like an engine issue that we could fix.

**Comment by vivienneanthony** [comment]
That is light is shined. If you look at the pic. The left side shows similiar to the right side. Ironically if a light is passed over it properly calculate that spot. 

In the meantime I updated my editor so I can tweak the near and fatclip as a stopgap.

**Comment by Modanung** [comment]
De dark parts seem to be separate polygons with the lighter geometry continuing below it. If this is true and if there is no distance between the faces, this is bound to cause Z-fighting if no bias is set for one of the materials.

**Comment by vivienneanthony** [comment]
The distance is as little as .10 meter or .1 unit. I think it might be of issue of precision. Im kinda want to model full scale equivalent at 1 meter per unit. So a face difference might be as little as .33 unit or .33 meter equal to 1 feet roughly

**Comment by Modanung** [comment]
A solution you may be looking for is [LODs](https://vimeo.com/171018835). They allow you to have a more detailed model up close (with different UV coordinates) so you can simply add some polygons to solve this up close and create the colour difference with a texture from a distance.
