### ISSUE TITLE
[Feature request] Models with large number of bones

### ISSUE THREAD

**Issue by slapin** [urho3d/Urho3D#1922]
Current workflow with models with large number of bones is much less than ideal.
Basically it requires manual splitting, mending. Which is especially hard with models which have
morphs. It is obvious it can be handled automagically, without too much hassle.

Why it is better be handled in engine rather than exporter is the fact that only engine knows
limitation set on skinning.

I think it should be sufficient to load Model and split it to multiple structures which could be skinned separately. I'd like to handle this, but my engine knowledge is not high enough
to know what could be done in most effective way for such skinned meshes to work.

My first idea was to split actual Model resource to several Models which all can be added to own AnimatedModel component instance. But is it best way it can be done regarding performance and
memory usage?

Any ideas?

**Comment by Modanung** [comment]
If I understood correctly the bone limit is hard coded into the exporter, not in the engine (except on certain hardware). In which case it would seem to me that adding a "No bone limit" option to the exporter would be the best solution to this problem.

**Comment by 1vanK** [comment]
```
unsigned Graphics::GetMaxBones()
{
#ifdef RPI
    // At the moment all RPI GPUs are low powered and only have limited number of uniforms
    return 32;
#else
    return gl3Support ? 128 : 64;
#endif
}
```
this value sended to shader (size of arra )
```
#ifdef SKINNED
    uniform vec4 cSkinMatrices[MAXBONES*3];
#endif
```

**Comment by slapin** [comment]
Yes, the matrix limit which is I currently fight with.
I wonder how Unity/UE4 handle this? My models work in there unmodified.

**Comment by JSandusky** [comment]
This should be possible to resolve through assimp which has a bone-weights post-processor, likely the current Urho3D converter doesn't bother to check for excessive bones and then perform the action if there are too many bones.

Obviously even assimp's documentation warns that it is a slow process - not surprising since it's fuzzy graph cutting.

**Comment by slapin** [comment]
I need to explain what I want to do, please see attached image
@JSandusky 
to be short I want to work on single mesh in Blender and apply a set of morphs on it (for customization)
then export. And in Urho I want to split the mesh after these morphs are applied. Or
otherwise  split the morhs to. I think the split algorithm should be to pass all triangles
through IndexBuffer and check vertices,copying the result to new IndexBuffer/VertexBuffer(s).
As we have 20 (or 64 or 128) diffrent blendindices, create new model and save previous one.

The other approach would be to export split and unsplit meshes, do all morphs and customizations on unsplit one and copy these mesh data to split meshes. This can be slow, but if done in C++
it might not be. As vertex coordinates are the same on unsplit and split meshes these
will require only vertex manipulation, which might be easier for my poor brain. Unsplit mesh might have
all bone stuff removed or can be just used as reference for split meshes. But I don't know how to split morphs though to use this approach.

![pipeline](https://cloud.githubusercontent.com/assets/6099/25844435/27b845c8-34b3-11e7-83ea-4d5c721f3005.png)

**Comment by JSandusky** [comment]
> Current workflow with models with large number of bones is much less than ideal.
Basically it requires manual splitting, mending.

This is your issue as posted correct? In translation "I need more bones" ... everything is use case specific fluff.

That is reconcilable through the ASSIMP converter, though I'm surprised it isn't already there - I suspect it is but is just a switch that is either hidden or poorly documented.

**Comment by slapin** [comment]
Basically yes, but ASSIMP do not know the actual hardware limits, so that
will either end up in too many drawing calls or incompatibility.
I think this is something which should be managed by internal logic.


On Sat, May 13, 2017 at 5:46 AM, Jonathan Sandusky <notifications@github.com

**Comment by slapin** [comment]
But then again, while ASSIMP implementation might not be perfect, if there
was any that would be much better than nothing.
