### ISSUE TITLE
Unresponsive mouse selection on some UI sections

### ISSUE THREAD

**Issue by rasteron** [urho3d/Urho3D#1923]
I just noticed this when clicking the bottom part of Material Editor as you cannot do any mouse selection when it is set in its default window height. Tabbing works though until you reach the bottom section or do a resize covering from top to bottom of the editor 

![unresponsive](https://cloud.githubusercontent.com/assets/3676827/25526260/58dbb232-2c45-11e7-9779-def9a47e84cc.png)

**Comment by OldSnake22** [comment]
Same issue and i have found the source of the problem but not the correct fix.

It is related to this commit: https://github.com/urho3d/Urho3D/commit/5e9579b23a183d6a53fb37f378570ffb2ba1c2b2

If i revert the code added by this commit. Everything works. Maybe @Cadaver can quickly identify the issue there.

**Comment by rasteron** [comment]
Ah good to know @OldSnake22, thanks.

**Comment by cadaver** [comment]
Good find, and thanks for investigating the history. It was an up/left limit check that should not be made, since a ListView can start far above the screen, and only have a range of its children on the screen.
