### ISSUE TITLE
JSON parsing is limited/not supported with AngelScript

### ISSUE THREAD

**Issue by slapin** [urho3d/Urho3D#1924]
AngelScript binding doesn't support JSON or I found no way to use it. Also there is no example
code to use JSON from AngelScript (due to missing support I guess).

Sample file:

```json
{
        "composites": {
                "dispname": "Composites",
                "members": {
                        "sequence": {
                                "dispname": "Sequence",
                                "max_children": -1,
                                "properties": {
                                }
                        },       
                        "memsequence": {
                                "dispname": "MemSequence",
                                "max_children": -1,
                                "properties": {
                                }
                        },
                        "selection": {
                                "dispname": "Selection",
                                "max_children": -1,
                                "properties": { 
                                }
                        },      
                        "memselection": {
                                "dispname": "MemSelection",
                                "max_children": -1,
                                "properties": { 
                                }       
                        }       
                }       
        }
}
```
There is no way to access keys or values in the file if you don't know names beforehand
(i.e. can't use Get() method). In C++ one can use GetVariantMap() and other methods to do processing.

**Comment by slapin** [comment]
Anyway, building list of key/value pairs from this list is impossible using builtin JSON support
fhich is really frustrating.

**Comment by iSLC** [comment]
[Source/Urho3D/AngelScript/ResourceAPI.cpp#L307](https://github.com/urho3d/Urho3D/blob/master/Source/Urho3D/AngelScript/ResourceAPI.cpp#L307)

```
JSONFile jd;
if (jd.Load("file.json"))
{
    jd.GetRoot()["composites"][dispname];
}
```

**Comment by slapin** [comment]
It is not a point to display all known values hardcoding all names in code.
In this case you actually don't need json at all.
The idea is to produce a list of key/value pairs and display in code to
allow kind of choice.
For example build menu of the selection. It is not possible.
If I don't hardcode "composites" in my code, how would I know if it is even
there?

**Comment by cadaver** [comment]
Proper iteration is typically hard to expose. Returning an array of keys in object type value could be sufficient, similar to how VariantMap works in AS.

**Comment by slapin** [comment]
I think something similar to XML could be implemented.
Also VariantMap does not store actual key values, something more sophisticated
is needed...
 From other hand XML iterates quite nicely, I think some mechanics from there could be used...
