### ISSUE TITLE
CollisionPolygon2D does not react to negative scales

### ISSUE THREAD

**Issue by ricab** [urho3d/Urho3D#1926]
CollisionPolygon2D shapes do not reflect negative scales of their node. An easy way to verify this is to add 

```
    if(input->GetKeyPress(KEY_F))
    {
      auto node = scene_->GetChild("Polygon");
      node->Scale2D(Vector2{1,-1});
    }
```

to `Urho2DConstraints::HandleUpdate` (32nd sample), running it, and pressing <kbd>F</kbd>. The flower sprite flips, but the polygon stays untouched.

**Comment by ricab** [comment]
Some debugging shows that the call `node_->GetWorldScale()` in `CollisionShape2D::OnMarkedDirty` returns the wrong scale (negative sign gone).

**Comment by ricab** [comment]
Thanks for the reply. I could try to contribute a fix if I was sure how to go about it. So far I tried to modify the extraction of the scale from the matrix, like this:

```
diff --git a/Source/Urho3D/Math/Matrix3x4.h b/Source/Urho3D/Math/Matrix3x4.h
index 9d5dc20..c75fc3f 100644
--- a/Source/Urho3D/Math/Matrix3x4.h
+++ b/Source/Urho3D/Math/Matrix3x4.h
@@ -659,9 +659,9 @@ public:
     Vector3 Scale() const
     {
         return Vector3(
-            sqrtf(m00_ * m00_ + m10_ * m10_ + m20_ * m20_),^M
-            sqrtf(m01_ * m01_ + m11_ * m11_ + m21_ * m21_),^M
-            sqrtf(m02_ * m02_ + m12_ * m12_ + m22_ * m22_)^M
+            Sign(m00_) * sqrtf(m00_ * m00_ + m10_ * m10_ + m20_ * m20_),^M
+            Sign(m11_) * sqrtf(m01_ * m01_ + m11_ * m11_ + m21_ * m21_),^M
+            Sign(m22_) * sqrtf(m02_ * m02_ + m12_ * m12_ + m22_ * m22_)^M
         );
     }
```

But it looks like parts of the engine rely on non-negative scales: I get crashes in 2D physics samples and strange behaviors in rag-dolls and vehicle samples, with this change. 

I can try to keep the existing Matrix3x4::Scale as is and provide a separate Matrix3x4::SignedScale instead, so the collision shape can use that instead...

**Comment by ricab** [comment]
By the way, a few more questions:

1. Why are the sprites not affected by the same problem? 
2. Why can't collision shapes do the same as sprites?
3. If negative scales are discouraged, how are 2D "entities" supposed to flip? Rotation about the vertical axis would invert all 2D rotations from that point on (CCW -> CW) so it is not very practical.

**Comment by ricab** [comment]
OK, I have fixed this with the patch below. What do you think?
[SignedScale.patch.txt](https://github.com/urho3d/Urho3D/files/977897/SignedScale.patch.txt)

**Comment by eugeneko** [comment]
How does it work? Rotation matrix is a 3x3 matrix multiplied by positive factors to compensate scale.
So, `worldTransform_` and `worldRotation_.RotationMatrix()` always have the same sign for each element.
So, `scale.x_ *= Sign(rot.m00_) * Sign(worldTransform_.m00_);` literaly does nothing because both elements have the same sign.

**Comment by ricab** [comment]
OK, I had to quickly review some notions I haven't touched since college as I don't usually deal with this low-level math stuff, but my reasoning is more or less the following (please check as I may very well be missing something and I only tested with 2D rotations (about the depth axis)).

The world transform is updated in `Node::UpdateWorldTransform` with the matrix that encodes translation, rotation and scale (`Node::GetTransform`). Let *M* be the 3x3 "sub-matrix" that encodes the scale and the rotation (the translation part only affects the last column, so it can be ignored). 

We have *M* = *S* x *R*, where *S* and *R* are the 3x3 matrices for scale and rotation, respectively. Since *S* has zeros everywhere except in the diagonal, the elements in the diagonal of *M* are given by *M<sub>nn</sub>* = *S<sub>nn</sub>* x *R<sub>nn</sub>*. Let's simplify this as *m* = *s* x *r*.

From this we can derive that the sign of *s* is negative *iff* the sign of *r* is different from the sign of *m*. And fortunately we know *m*, we know *r*, and we know *|s|*. So we can find the last missing piece to fully know *s*: its sign. 

In particular, we have *sign(s)* = *sign(r)* x *sign(m)*. Which means that *s* = *|s|* x *sign(r)* x *sign(m)*. In code, with `s` starting positive, we can say `s *= sign(r) * sign(m)`.

**Comment by eugeneko** [comment]
> we know r

Do we? This _r_ is not truly rotation, it still contains flips if there are.
You'd probably need to extract Quaternion rotation and then restore true rotation matrix.
However, there is no guarantee that you'll get what you want.
Negative scales bring too much ambigity in transformation logic and complexity&bugs all over the engine.
E.g. `Scale(-1,1)` is the same as `Scale(1,-1)*Rotate(180)`, so you may not rely that rotation and scale of the node will remain the same as you set.
This situation is similar to Euler<->Quaternion conversion, but worse.

**Comment by cadaver** [comment]
Looks acceptable.

**Comment by ricab** [comment]
Great, thanks a lot for the feedback and for doing the script bindings for me.

**Comment by eugeneko** [comment]
Note that diagonal elements may be zero and your code don't handle it.
I haven't managed to reproduce the problem because there are always some floating-point noise in epsilon range around zero.
However, I don't like very much solutions that rely on floating-point noise.

    Node node(context);
    node.SetRotation(Quaternion(90, Vector3::FORWARD));
    node.SetScale(Vector3(-1, 1, 1));

**Comment by cadaver** [comment]
@eugeneko If you have time, feel free to fix the function directly.

**Comment by ricab** [comment]
I don't see what the problem is: if the "signed scale" was zeroed by the rotation, the world transform would already have been zeroed as well, in `Node::UpdateWorldTransform`.

In other words, and taking the nomenclature above, for `sign(r)` to be zero in `s *= sign(r) * sign(m)`, `r` would have to be zero. But if that was the case, `s` would also already be zero anyway, because it was derived from a world transform that already takes `r` into account. So zero *is* the right value.

**Comment by eugeneko** [comment]
> I don't see what the problem is

The problem is that you may get zero scale when it is obviously false, see example above.

**Comment by ricab** [comment]
@eugeneko Indeed, you're right, sorry for the confusion. I mistook my own `s` term for the actual scale in the reasoning above, when it is only the diagonal.

So, in these cases, where there is a 0 in the diagonal of either the world transform or the world rotation matrices, we can still try the remaining elements to find the sign (or give up if there is always a zero). That is the approach in the following patch:
[SignedScaleFixedZeroCase.patch.txt](https://github.com/urho3d/Urho3D/files/1005313/SignedScaleFixedZeroCase.patch.txt)

Should I submit a PR?

**Comment by eugeneko** [comment]
Your approach looks overcomplicated...

Every matrix consists of three axises: `M*(1,0,0)` and so on. `scale.xyz` is that vectors' module.
If you want to get sign of the scale, it is enought to check whether the axises of two matrices (`R*S` and `R`) have the same direction.
So, you just dot `(R*S)*(1,0,0)` and `R*(1,0,0)` and then get signed `scale.x`:

`scale.x_ = rot.m00_ * worldTransform_.m00_ + rot.m10_ * worldTransform_.m10_ + rot.m20_ * worldTransform_.m20_; ...`

I'll fix it.

**Comment by ricab** [comment]
> scale.x_ = rot.m00_ * worldTransform_.m00_ + rot.m10_ * worldTransform_.m10_ + rot.m20_ * worldTransform_.m20_; ...

I suppose you forgot the `Sign` there. And you would then still have to check for zero sums. 

So, if I understand correctly, it would be something like:
```
    sign.x_ = Sign(rot.m00_ * trf.m00_ +
                   rot.m01_ * trf.m01_ +
                   rot.m02_ * trf.m02_);
    sign.y_ = Sign(rot.m10_ * trf.m10_ +
                   rot.m11_ * trf.m11_ +
                   rot.m12_ * trf.m12_);
    sign.z_ = Sign(rot.m20_ * trf.m20_ +
                   rot.m21_ * trf.m21_ +
                   rot.m22_ * trf.m22_);

    if(Equals(sign.x_, .0f))
      sign.x_ = 1.0f;
    if(Equals(sign.y_, .0f))
      sign.z_ = 1.0f;
    if(Equals(sign.z_, .0f))
      sign.z_ = 1.0f;

    return trf.Scale() * sign;
```

So this is the **same** as what I proposed, except that:

1. I am stopping short of calculating the whole sums if the next `rot.mXX_ * trf.mXX_` != 0; 
2. I am iterating on indices rather than repeating `mXX_` all over. Unfortunately matrix/vector classes don't accept dynamic indexing, so I had to index arrays instead. Otherwise it would read simpler and avoid copy/pasting:
```
    for(int i = 0; i < 3; ++i)
        for(int j = 0; j < 3; ++j)
            if(!(Equals(rot[j][i], .0f) || Equals(trf[j][i], .0f)))
            {   
                sign[i] *= Sign(rot[j][i]) * Sign(trf[j][i]);
                break;
            }

    return worldTransform_.Scale() * Vector3{signData};
```

**Comment by eugeneko** [comment]
> I suppose you forgot the Sign there.

Nope.
If I understand things correctly, I get true signed scale in my code above. No signs, no multiplication with absolute scale is required. So,

> And you would then still have to check for zero sums.

No, I don't. Zero sum means zero scale.

> So this is the same as what I proposed

I don't think so. The main difference is that my solution has strict geometrical meaning (`(R*S)*axis dot R*axis`), your one looks like tricky number magic.

Actually, I want you to ensure that I am not missing something in this reasoning because I don't want to suddenly break you code..

**Comment by ricab** [comment]
OK, I am not following your reasoning at all then. You're saying `(R*S)*(1,0,0) dot R*(1,0,0)` gives you scale.x? Why? 

The way I see it, it should be the other way around: `(R*S)/R=S`. But I believe division is not well defined for matrices. Did you miss some <sup>-1</sup>? Otherwise, could you please clarify the math for me? Or feel free to share some code, I would gladly give it a try.

> your one looks like tricky number magic.

No magic, I unfortunately am no magician :bowtie: Just tried to follow logic and math and I guess that is why it works.

**Comment by ricab** [comment]
BTW, here is a hand writing attachment to try to convince you there is no magic involved
[ScaleSign.pdf](https://github.com/urho3d/Urho3D/files/1006148/ScaleSign.pdf).

**Comment by eugeneko** [comment]
> OK, I am not following your reasoning at all then. You're saying (R*S)*(1,0,0) dot R*(1,0,0) gives you scale.x? Why?

Let `R = r_ij`, `S = s_ij`, `R*S = m_ij`. `r_ij` and `m_ij` are known. `m_ij = r_ij*s_jj`, as you wrote.
So, it could be written in vector form: `(m_0j, m_1j, m_2j) = (r_0j, r_1j, r_2j)*s_j` aka `M_j = R_j*s_j`
We need to find s_j, other values are known. To get that multiplier we have to project vector `M_j` onto `R_j`. Since `R_j` has always unit length, projection degrades to dot product: `s_j = (M_j, R_j)`
`s_j = m_0j*r_0j + m_1j*r_1j + m_2j*r_2j`

Or, mathematically, `M_j = R_j*s_j -> (M_j, R_j) = (R_j*s_j, R_j) = s_j*|R_j|^2 = s_j`
Note that s_j is signed everywhere above.

**Comment by ricab** [comment]
OK, I got it, you are totally right. And I agree that this is a much cleaner way of getting the actual scale. Please go ahead when you want.

**Comment by ricab** [comment]
I still took some time to get there, so for my own future reference, here is the step by step proof I came up with to convince myself:

We have established that:

1) `M_j = S_j * R_j`

Where `M_j` and `R_j` are vectors and `S_j` is a scalar. We also know that

2) `|R_j| = 1`

Let `P_j` be the projection of `M_j` onto `R_j`. Because of 1), `M_j` is its own projection onto `R_j` (they are collinear). So we have

3) `P_j = M_j`

But, from the rules of projection, we also know that

4) `P_j = x * R_j`

Where `x` is the scalar given by 

5) `x = M_j dot (R_j / |R_j|)`

Replacing 2) into 5), we get

6) `x = M_j dot R_j`

Replacing 6) into 4), we get 

7) `P_j = (M_j dot R_j) * R_j`

And replacing 3) into 7), we get

8) `M_j = (M_j dot R_j) * R_j`

Now, replacing 1) into 8), we derive

9) `S_j * R_j = (M_j dot R_j) * R_j`

And finally, because `R_j` cancels on both sides, we obtain

10) `S_j = M_j dot R_j`

Which allows us to avoid the squares in length calculations and gives the signed scale.

**Comment by ricab** [comment]
@eugeneko let me know if you want to offload the PR, I'd be happy to do it today (going away tomorrow). My local implementation of your method, which seems to work perfectly for me:
```
Vector3 Node::GetSignedWorldScale() const
{
    if (dirty_)
        UpdateWorldTransform();

    Matrix3 rot = worldRotation_.RotationMatrix();
    const Matrix3x4& trf = worldTransform_;

    float sx = rot.m00_ * trf.m00_ + rot.m10_ * trf.m10_ + rot.m20_ * trf.m20_;
    float sy = rot.m01_ * trf.m01_ + rot.m11_ * trf.m11_ + rot.m21_ * trf.m21_;
    float sz = rot.m02_ * trf.m02_ + rot.m12_ * trf.m12_ + rot.m22_ * trf.m22_;

    return Vector3(sx, sy, sz);
}
```
