### ISSUE TITLE
Scene replication.

### ISSUE THREAD

**Issue by xiliu98** [urho3d/Urho3D#1929]
document said "A node's user variables VariantMap will be automatically replicated on a per-variable basis. This can be useful in transmitting data shared by several components, for example the player's score or health.", 

If I don't want the player's score share for other player which contorlled by ohter human , for avoiding hacker watch the hidden infomation,  are there any feature can do this?
SendRemoteEvent() is good choice, but when need to sync many vars, it will use huge bandwidth and become troublesome.

**Comment by cadaver** [comment]
Remote events or custom messages are valid options. The latter allows you to fully define the data payload, if you're concerned that events are inefficient. The VariantMap is indeed for things you want everyone to see. 

Also, please consider rather asking questions on the forums than posting as issues, when it's not an engine bug / issue as such.
