### ISSUE TITLE
Objects with same Model+Material keep disappearing and reappearing

### ISSUE THREAD

**Issue by darkuranium** [urho3d/Urho3D#1936]
It would appear that objects that have the same Model and Material disappear and reappear as the camera is moved. I suspect this is a bug with builtin instancing.

A workaround is to clone either the model or the material.

MCVE (with the workaround demonstrated): https://gist.github.com/darkuranium/a75853e7c99e57bcbc12f3d0c5b1b670 ; the models & materials are the same ones that come distributed with Urho3D.

Videos of the problem (*NOTE 1&2): https://stdrand.com/data/Urho3D/

This happens both with 1.6 *and* master. I've no idea how to get the device information from the Renderer, so I cannot provide that info at the moment.

*NOTE 1: Note how the wireframe video has a small line show up on the left side as the sphere disappears and vice-versa. I suspect the data is somehow misinterpreted.
*NOTE 2: I can't promise I'll keep the videos up forever, as this is my personal server.

**Comment by cadaver** [comment]
Which graphics API you run on? (OpenGL / D3D9 / D3D11)?

**Comment by darkuranium** [comment]
@cadaver: See my edit. I have no idea on how to get device information from the Renderer (or whatever it might be), so I don't know.

**Comment by darkuranium** [comment]
**Update:** The sample 39_CrowdNavigation displays this problem (at least for me). I'm not sure if it's the same reason, but the effect seem to be the same. Things are popping in and out of existence much like in my video as the camera moves (in some cases [read: camera positions], almost all the mushrooms disappear!).

**Comment by cadaver** [comment]
You should know the API statically from the compile flags you use. -DURHO3D_OPENGL enables OpenGL and -DURHO3D_D3D11 D3D11, otherwise it's D3D9 (on Windows). Also during runtime by calling graphics->GetApiName().

However I don't remember to have seen flickering in CrowdNavigation, so it could be a problem specific to your video driver. We'll know more once I run your example through all the APIs.

**Comment by cadaver** [comment]
Cannot reproduce disappearing objects with your sample. NVIDIA GPU, Windows, D3D9 / 11 / OpenGL.

**Comment by darkuranium** [comment]
I most definitely can. Here's a video of the crowd simulation sample: https://stdrand.com/data/Urho3D/Urho3D-Problem-39_CrowdNavigation.mp4

I don't know how to get a "graphics", and neither does anybody who replied in IRC (Urho3D docs have some holes, this is one of them). So I still can't tell you what `GetApiName()` returns. I don't think I'm using any `-D` flag, so I *suspect* it's D3D9 then.

I'm fairly sure this problem is related to the "auto-instancing" (not 100% sure, though), since e.g. cloning the material (or using a different one, or using a different mesh) is enough to work around the problem. Since you cannot reproduce it and I can, it might be undefined behavior. I have the latest NVIDIA drivers as of the time of writing, (385.05; I've just updated them to see if it fixed the issue, and it did not).

... or it might be `cl` miscompiling Urho3D. Wouldn't have been the first time I've seen it do that, even though it's somewhat unlikely.

**Compiler:** Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x86
**OS:** Windows 7 Professional N (64-bit)

**Comment by eugeneko** [comment]
What if you disable instancing at all?

**Comment by darkuranium** [comment]
**Update:** D3D11 and OpenGL modes exhibit the *exact* same problems.

However, `renderer->SetDynamicInstancing(false);` makes things work as they should.

**Comment by cadaver** [comment]
Could even be something like uninitialized memory causing the error on just your machine. I recommend stepping into the rendering code with debugger and seeing if it appears to be doing something weird. Arguably, that will go quite deep / hardcore, but I suspect there's little anyone else can do in this situation.

**Comment by eugeneko** [comment]
You may try to use Visual Studio graphics debugger, it's pretty useful.
You may also try to check whether the problem is in building instance buffer or rendering:

1. Disable all stuff like shadow/etc, leave only plain geometry
2. Manually count objects in your camera frustum (when instancing is disabled)
3. Then turn instancing on and check the content of instancing buffer.

BTW, I've seen driver bug wih similar appearing: DrawInstanced call just ignored _InstanceOffset_ parameter, so all instanced objects except the first rendered one were drawn in completely broken way.

**Comment by darkuranium** [comment]
@cadaver: Yes, I've already mentioned it might be undefined behavior. I don't have the time to do all this stuff right now, however.

@eugeneko: I don't know how to use that debugger. I generally avoid both Visual Studio *and* (especially) their compiler. Right now, I don't have a choice, as GCC is segfaulting if I try to compile Urho3D with it. As for your questions:
1. Doesn't the MCVE I've posted already have that off? I mean, I don't have any shadow casters or such ...
2. I'll do that when I have the time.
3. I'll do that when I have the time.

I doubt it's that same driver bug; you see, even the *first* object is being rendered incorrectly. Also, I know for a fact that instancing works at least in GL3.3, as I've used it before in my own code. Also, it's 2017 --- I think it would also break a shit-ton of other games.

**Comment by eugeneko** [comment]
>  I don't know how to use that debugger. I generally avoid both Visual Studio and (especially) their compiler.

It's pretty simple. You just run DX11 program, capture the frame and look into drawcalls. If your instancing buffer is valid, it's almost only stable way of investigation.

> I doubt it's that same driver bug

I doubt that it is driver bug because you've reproduced it in all APIs. That was just random thought.

**Comment by darkuranium** [comment]
Update: I was wrong about D3D11. Looks like I messed something up with the URHO3D_D3D11 flag.

Now that I managed to ***actually*** compile for D3D11, I can tell that these problems do ***not*** show up! I'll give you OpenGL results momentarily.

**Comment by eugeneko** [comment]
Then, probability of DX9 driver bug became slightly greater...
What about debug/release configs for DX9 renderer? Is there any difference in bug appearance?

**Comment by darkuranium** [comment]
@eugeneko: I'll get back to you on that once I have more time.

**Comment by darkuranium** [comment]
@eugeneko I've just had the problem happen in GL3. Seems to be *far* less common than in D3D9, but it still happens sometimes.

**Comment by Lallassu** [comment]
@darkuranium I saw your message on irc and I got the same issue. But for me it didn't work setting dynamic instancing to false. I'm only using OpenGL since I'm developing under OS X.

Here is my original: https://giphy.com/gifs/3o7aCWI4oDm2zSzWE0
With dynamic instacing off: https://giphy.com/gifs/3ov9jFZthAqsQ8Lpte

Hardware:
MacBook Pro (Retina, 13-inch, Mid 2014)
3 GHz Intel Core i7
16 GB 1600 MHz DDR3
Intel Iris 1536 MB

**Comment by eugeneko** [comment]
@Lallassu 
Try to check whether the draw calls for disappearing objects are sent to the driver. E.g. you could disable shadows and look at number of rendered triangles (Urho must have the metric somewhere). Is the number of triangles constant when camera is moving?
Do you have problems with standard assets?

**Comment by Lallassu** [comment]
@eugeneko Here is debug info: https://giphy.com/gifs/3ohhwzehT1rBCc2ccU/fullscreen
As you said, the triangles are not drawn at all. Number of batches/triangles are changing when moving camera around. Any idea whats causing this?

**Comment by eugeneko** [comment]
> As you said, the triangles are not drawn at all. Number of batches/triangles are changing when moving camera around. Any idea whats causing this?

So, this is the problem at code side. Ensure that bonding boxes are valid, e.g. draw 'em like the Editor do.

**Comment by Lallassu** [comment]
@eugeneko That solved it! It was a bounding box issue from my side! Thank you very much.
