### ISSUE TITLE
Android build engine problem

### ISSUE THREAD

**Issue by halcyonx** [urho3d/Urho3D#1937]
I've tried build Urho3D for android, using this instruction:
https://discourse.urho3d.io/t/howto-urho3d-android-setup-on-win7/1938
`cmake_android.bat Build -DURHO3D_SAMPLES=ON`
cmake printed log:
https://pastebin.com/gxe9NJtm
When I try use command:
`android update project -p . -t 1`
it prints the following: https://pastebin.com/gLfNFAGz
And finally, then I use `make` (path to make: C:\Android\android-ndk\prebuilt\windows\bin)
it starts build process, and it fails then building Urho3D target with message: 

> fatal error: too many errors emitted, stopping now [-ferror-limit=]
> 1 warning and 20 errors generated.
> make.EXE[2]: *** [Source/Tools/Urho3DPlayer/CMakeFiles/Urho3DPlayer.dir/Urho3DPlayer.cpp.o] Error 1
> make.EXE[1]: *** [Source/Tools/Urho3DPlayer/CMakeFiles/Urho3DPlayer.dir/all] Error 2
> make.EXE: *** [all] Error 2

https://pastebin.com/SH0GqAG8
How can I fix this problem?

**Comment by weitjong** [comment]
Based on the log, it seems you are using an old version of the build scripts. In the past we had to pass the similar build option to CMake between Urho3D library-building and library-using time. In the newer version the build system will auto-configure some critical build options to match with the Urho3D library in your own project to avoid such conflict. So, try redo from the start using the master branch, or passing the similar buildb options explicitly, especially URHO3D_LIB_TYPE for this case, if you have to use old version.
