### ISSUE TITLE
Why does AssetImporter merge model root transfrom and animation root transform?

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1944]
I'm importing animation from *.dae
Root node of model has initial scale.
Here is some branch in AssetImporter
https://github.com/urho3d/Urho3D/blob/97b594de3649541ad9219e86e6f4fcab65b3a300/Source/Tools/AssetImporter/AssetImporter.cpp#L1462
This breaks animation of root node's position (because root position from animation is multiplied with initial scale)
What's the point of this logic?

**Comment by cadaver** [comment]
When saving the skeleton itself, the root bone is similarly transformed. It's a long time since this was written, so have to review if it could be removed without breaking the export.

**Comment by cadaver** [comment]
Please check now. Transforming with the root node (which represents AnimatedModel's scene node during runtime) should indeed be incorrect, but now it transforms with any in-between nodes, if there are any.

If it's still not right, you're also free also apply further changes.

**Comment by eugeneko** [comment]
Works fine now, thank you!
