### ISSUE TITLE
CMake Deprecation Warning - add_compiler_export_flags

### ISSUE THREAD

**Issue by ricab** [urho3d/Urho3D#1945]
CMake issues a bunch of warnings about the way the visibility is set when building shared libraries. Something like the following for each binary:
```
CMake Deprecation Warning at CMake/Modules/GenerateExportHeader.cmake:373 (message):
  The add_compiler_export_flags function is obsolete.  Use the
  CXX_VISIBILITY_PRESET and VISIBILITY_INLINES_HIDDEN target properties
  instead.
Call Stack (most recent call first):
  CMake/Modules/UrhoCommon.cmake:1535 (add_compiler_export_flags)
  CMake/Modules/UrhoCommon.cmake:1583 (setup_library)
  Source/Samples/03_Sprites/CMakeLists.txt:30 (setup_main_executable)
```

I am on linux here, using cmake 3.5.1 and and gcc 5.4.0

**Comment by weitjong** [comment]
This is a known issue. At the moment they could be safely ignored. We/I still have other things to do when we have extra time to contribute to Urho3D project. Anyone is welcome to try to fix this.

**Comment by weitjong** [comment]
For Android build this is truly annoying.
