### ISSUE TITLE
For CI - to fix documentation generation

### ISSUE THREAD

**Issue by weitjong** [urho3d/Urho3D#1947]
The newer doxygen version on Ubuntu Trusty throws out warning during documentation update. The generated online documentation seems to be wrong as well.

**Comment by weitjong** [comment]
There are quite a few of warnings coming from rapidjson library. Anyone have any idea why or how to fix this? Actually after Aster added it some years ago I have asked myself the question since then, do we really need the rapidjson documentation to be generated on our online documentation pages. We don't generate the doc for the other 3rd-party libraries.

**Comment by cadaver** [comment]
I would be in favor of dropping Rapidjson documentation. It's only used as a helper during JSON load/save, the actual "meat" is in our JSON classes.

**Comment by weitjong** [comment]
With that dropped, the generated documentation pages look more or less the same as before now. Closing this for now.
