### ISSUE TITLE
Possible bug with loading SpriteSheet2D from PList

### ISSUE THREAD

**Issue by YarikTH** [urho3d/Urho3D#1951]
SpriteSheet2D.cpp has 3 loading variants: XML, Json and PList. Code for them mostly the same and it seems that loading from PList was made via copypast from XML loading, because SpriteSheet2D::EndLoadFromPListFile() at Urho2d/SpriteSheet2D.cpp resets loadXMLFile_ twice at 158 and 194 lines rather than reset loadPListFile_.

``` cpp
bool SpriteSheet2D::EndLoadFromPListFile()
{
    ResourceCache* cache = GetSubsystem<ResourceCache>();
    texture_ = cache->GetResource<Texture2D>(loadTextureName_);
    if (!texture_)
    {
        URHO3D_LOGERROR("Could not load texture " + loadTextureName_);
        loadXMLFile_.Reset(); /// Wrong reset at 158 line
        loadTextureName_.Clear();
        return false;
    }

    const PListValueMap& root = loadPListFile_->GetRoot();
    ...

    loadXMLFile_.Reset(); /// Wrong reset at 194 line
    loadTextureName_.Clear();
    return true;
}
```
I checked JSON loading(EndLoadFromJSONFile) and there are 3 usage of loadJSONFile_ (2 resets and 1 GetRoot) and 0 usage of loadXMLFile_. So it must be a bug.

**Comment by cadaver** [comment]
Good catch. Yes, it's likely copypaste.
