### ISSUE TITLE
FontFace should allow fractional font sizes

### ISSUE THREAD

**Issue by iainmerrick** [urho3d/Urho3D#1952]
Currently the FontFace class only allows integral sizes (11pt, 12pt, etc).

Internally, FontFaceFreeType multiplies the size by 64, so it looks like FreeType is capable of rendering fonts in steps of 1/64th of a point. It would be good to make that functionality available in Urho. That would make it easier to render crisp text at arbitrary scales.

I'm happy to try implementing this! But I could use some feedback on the best approach:

- Just change pointSize from an int to a float? That changes the API, but I think almost all client code would work unchanged.

- Add new parallel methods that take floats, alongside the existing int methods. Safer but makes the API more complicated.

**Comment by cadaver** [comment]
We make API-breaking changes from time to time, so I'd be fine with the first option. Like you say most code would still continue to work, just making an (ugly) implicit conversion where necessary.

**Comment by iainmerrick** [comment]
Great, I'll give it a try. Thanks for the feedback, I appreciate it!

**Comment by iainmerrick** [comment]
It looks like this change doesn't work right now, because of a bug in FreeType. Here's a long discussion: http://lists.nongnu.org/archive/html/freetype-devel/2017-04/msg00042.html

Quick version: glyphs are being incorrectly rounded to pixel boundaries.

It's fixed in 2.8, so updating our copy of FreeType should allow fractional sizes to work correctly.

**Comment by iainmerrick** [comment]
Yep, confirmed that fractional sizes work in 2.8. (I'm working on the Urho API change for that)
