### ISSUE TITLE
Text class should allow per-character subpixel positioning

### ISSUE THREAD

**Issue by iainmerrick** [urho3d/Urho3D#1953]
This is another feature suggestion, a followup to #1952 (allow fractional font sizes).

Inspecting both the code and the rendered output, it looks like Text objects align each character to a pixel boundary. That's OK at large sizes but leads to awkward letter spacing at small sizes.

It would be great to align characters horizontally at subpixel offsets, say 1/4 pixel offsets. I think that could be done by extending FontFace to cache up to 4 renderings of each glyph.

That would obviously use more memory, but it's only needed for small fonts, which don't take up much memory in the first place! So we could use an adaptive strategy -- single pixel alignment for large fonts, half-pixel for medium fonts, quarter-pixel for small fonts, etc.

This will become less important as high-resolution screens get more common, but many users still have low-res screens. As Urho aims to be a lightweight framework, it would be good to have high-quality text rendering by default on those low-end devices.

**Comment by cadaver** [comment]
You're welcome to work on this. Possibly would still be preferable if the multiple copies mechanism can be disabled completely if necessary. There are already functions in the UI subsystem which configure behavior for all fonts globally. See e.g. SetUseMutableGlyphs, SetForceAutoHint.

**Comment by iainmerrick** [comment]
Just to confirm that I'm working on this. Now that I understand the code better, I plan to do it in two steps:
1. Add a "subpixel character positioning" option that positions chars using floats
2. Add a "horizontal oversampling" option to improve rendering quality

I belatedly realized that we don't need N separate copies of each glyph for item 2, we just need a single stretched and filtered image. That makes things a lot simpler! The code changes shouldn't be too big.

**Comment by iainmerrick** [comment]
Forgot about item 0 :). We need to be able to disable hinting, otherwise subpixel positioning makes no sense!

**Comment by iainmerrick** [comment]
To show the current state of play, here's what you get with the normal autohinter:

![autohinted_text](https://user-images.githubusercontent.com/252111/27597610-7ade2506-5b28-11e7-911f-1a5eb9f8fbd9.png)

And here's unhinted text with subpixel alignment:

![unhinted_subpixel_text](https://user-images.githubusercontent.com/252111/27597619-7f3ffd4a-5b28-11e7-989b-b304c4b973a5.png)

Pretty big difference, and it's up to game authors to decide what settings are most appropriate for them.

The subpixel text has accurate spacing but it's a bit blurry. When I add oversampling, that should improve it (but of course it won't ever be as sharp as the fully hinted text).

**Comment by iainmerrick** [comment]
Here's what the oversampling looks like. The difference is clearest in the 7-10pt range:

![text_oversample](https://user-images.githubusercontent.com/252111/27755752-6c7f8004-5db7-11e7-8dae-aad8f2c4a3bb.png)

**Comment by cadaver** [comment]
Merged the related PR, so closing.
