### ISSUE TITLE
feature request: RaycastVehicle should remove itself from action list on disable...

### ISSUE THREAD

**Issue by slapin** [urho3d/Urho3D#1954]
... and add back on enable if was disabled. If I won't die from work, I'll make it.
But feel free to do it, it should be several lines of code, but huge bucket of happiness!

**Comment by cadaver** [comment]
Certainly makes sense. I could look into it during the weekend.

**Comment by slapin** [comment]
Thanks, looking forward to it.

**Comment by cadaver** [comment]
Finished only a week later than originally thought. But better late than never.
