### ISSUE TITLE
Profiler output is confusing

### ISSUE THREAD

**Issue by slapin** [urho3d/Urho3D#1955]
Well, profiling by hand I found that
```c++
world_->stepSimulation(timeStep, maxSubSteps, internalTimeStep);
```
is most time consuming line in Urho I have, it consumes 964 out of 1000 somethings in profiler,
for scene out of 60 RigidBodies (I think Bullet is slowest physical engine I worked with,
but I never seen open source 3D physical engine before). But that is another story.
The profiling block above it,
```c++
URHO3D_PROFILE(UpdatePhysics);
```
correctly indicates the load. But I thought "StepSimulation" block should indicate the load of the above,
but it shows only 80 of 1000 somethings. Which is not informative. Any clues?

**Comment by boberfly** [comment]
Just to note I think the later bullet release had patches related to multi-threading fixes, this could be looked into for Urho's work queue threadpool. Not answering your question but related none the less. :)

**Comment by slapin** [comment]
You'd better add separate issue for this, as your note might be lost in the process.
Probably you could just send PR so somebody could test it. As for this issue, I still look for answer,
is it me or there is something going on. BTW, with Release build numbers are better, so I take back
words about Bullet being slowest. It is actually fine but slower than what I want it to be, but future will
show (need to compare to GTA close character density). Anyway, I think I can manage with tricks if
that will be required. Anyway, I can now have 100 characters with relatively decent FPS (thanks to detour crowd stuff). But I need physics for closer characters, and the numbers are not nice - according to Assassin Creed's presentation they could have quite an amount of physical characters, but with Urho something like 20 physical bodies visibly drop FPS. Especially if fast moving. Also I have a lot of troubles with Crowd navigation - when I switch to non-physical motion (disable physics and move via node position), the position never matches the ground level, it is always +/-1 above or below, looks like navmesh issue over terrain. Using raycast to fix this is not an option, as that consumes too much. But this stuff is off-topic too.

**Comment by cadaver** [comment]
Note that physics is not run each frame, which may add to your confusion. You can try with vsync on to make sure it does both physics step + render each frame. 

Also, I don't recommend any kind of performance testing (even approximate) in debug mode.
