### ISSUE TITLE
Crash: PhysicsWorld2D uses destroyed contact when overlap ceases in broadphase

### ISSUE THREAD

**Issue by ricab** [urho3d/Urho3D#1958]
When `b2ContactManager` finds that a former contact ceases to overlap, it [destroys the contact](https://github.com/urho3d/Urho3D/blob/84c8be164b5187c10edf9a1ad04315d094194b34/Source/ThirdParty/Box2D/Box2D/Dynamics/b2ContactManager.cpp#L162). Note that [`EndContact` is called](https://github.com/urho3d/Urho3D/blob/84c8be164b5187c10edf9a1ad04315d094194b34/Source/ThirdParty/Box2D/Box2D/Dynamics/b2ContactManager.cpp#L46) on `PhysicsWorld2D`, which saves a pointer to the expiring contact before it is actually destroyed. Later on (but still in the same `PhysicsWorld2D::Update` call) [`PhysicsWorld2D::SendEndContactEvents` is called](https://github.com/urho3d/Urho3D/blob/84c8be164b5187c10edf9a1ad04315d094194b34/Source/Urho3D/Urho2D/PhysicsWorld2D.cpp#L350). This method [tries to serialize the recently destroyed contact into the event](https://github.com/urho3d/Urho3D/blob/84c8be164b5187c10edf9a1ad04315d094194b34/Source/Urho3D/Urho2D/PhysicsWorld2D.cpp#L815), dereferencing rubbish and causing a crash.

**Comment by ricab** [comment]
I believe this was introduced in fc88f5a

**Comment by gogoprog** [comment]
I confirmed this issue in the current master

**Comment by eugeneko** [comment]
Yeah, that's mine.
Probably, `PhysicsWorld2D::EndContact` shall serialize contact info and *shan't* serialize contact itself.

**Comment by eugeneko** [comment]
It shall work now. Can you check, please?

**Comment by ricab** [comment]
Yes, it looks ok now, the crash is gone. Thanks a lot!
