### ISSUE TITLE
Disable standard assets building

### ISSUE THREAD

**Issue by CheeryLee** [urho3d/Urho3D#1963]
Hello!
I built engine from sources. When I want to start my project EXE it says that it needs Data and CoreData folders. It's OK, create them. But it also needs all standard content placed there (shaders, UI etc.). How can I disable engine building with these files? I need only my assets which contain my shaders and layouts.

**Comment by cadaver** [comment]
There are certain files in CoreData that you are just going to need. Light ramps and default renderpath at least, and some shaders, like rendertarget blitting. The engine shouldn't fail to start, but rendering will not work right without them.

On the other hand, the engine can be configured to start with any set of resource folders (with the startup parameters), but their nonexistence is fatal like you noticed.

I don't think you can make the engine to not completely require any of those files, without code changes.

**Comment by 1vanK** [comment]
I suggest move from Data to CoreData:
1) UI\MessageBox.xml
2) UI\DefaultStyle.xml
3) Fonts\Anonymous Pro.ttf
4) UI\ScreenJoystick.xml

Also for the harmony of the system
5) Data\PostProcess

Another resources used only in samples and can be deleted without problems.

**Comment by 1vanK** [comment]
I forgot textures for UI

**Comment by weitjong** [comment]
I disagree to move the UI-related resources to the CoreData because I am afraid it would give a wrong impression that the current built-in UI look and feel is non-changeable. Or for those that know it can be changed, is now forced to touch the CoreData directory.

**Comment by 1vanK** [comment]
by default resources from Data used priority over CoreData
```
Vector<String> resourcePaths = GetParameter(parameters, EP_RESOURCE_PATHS, "Data;CoreData").GetString().Split(';');
```
so users can just place modofied resources to Data folder and its will be used instead CoreData files

**Comment by weitjong** [comment]
Still, I don't see the point of having the UI resources in both places.

**Comment by eugeneko** [comment]
> I disagree to move the UI-related resources to the CoreData because I am afraid it would give a wrong impression that the current built-in UI look and feel is non-changeable. 

If I replace UI with, e.g. RenderPath:

> I disagree to move the RenderPath-related resources to the CoreData because I am afraid it would give a wrong impression that the current built-in RenderPath is non-changeable. 

But wait... RenderPath is already in CoreData!

**Comment by weitjong** [comment]
That is different. You can have custom RenderPath in the Data, and yet Urho still has its basic/standard RenderPath in the CoreData. The currently provided UI resources, to me, are really just suitable for the Editor that come with Urho3D project. I cannot imagine you will want to ship your final product in your own project using those resources for your in-game UI.

**Comment by weitjong** [comment]
Since there are no more discussion and as per Lasse it is not feasible to do the original request, can we close this issue?

**Comment by CheeryLee** [comment]
Yeah, I will try to change default files. Thanks for all answers!
