### ISSUE TITLE
[retirement request] Remove b2Contact pointer from EndContact event

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1965]
According to #1958, b2Contact pointer in EndContact event may be dangling and end user is unable to check it. In fact, this is the root cause of the bug. 
I don't see a nice way to fix it, so I suggest to completely remove the pointer from the event.
To compenaste this I suggest to keep contact info in `ContactInfo`.

Any objections, @cadaver ?

**Comment by cadaver** [comment]
No objections.
