### ISSUE TITLE
android crashes after Recreating the Vehicle

### ISSUE THREAD

**Issue by redmouth** [urho3d/Urho3D#1967]
Urho3D library build commit ID: ea15976d7c9621b4a9cccf092cfff64fc1d36225
Tested with x86 and armeabi-v7a version of static library libUrho3D.a

On Android platform,  crash happens with the following steps:
- creating a Vehicle defined in sample 46 RaycastVehicleDemo.
- Removing the Vehicle Node and all it's child Wheel nodes
- Recreating the Vehicle, got the following crash:

Attached source files and stack trace.  It works well on Linux.

stack trace:
* thread #13, name = 'SDLThread', stop reason = signal SIGSEGV: invalid address (fault address: 0x60)
  * frame #0: libworldexplore.so`btRaycastVehicle::updateWheelTransformsWS(this=0xa184f100, wheel=0x00000000, interpolatedTransform=false) at btRaycastVehicle.cpp:154
    frame #1: libworldexplore.so`btRaycastVehicle::updateWheelTransform(this=0xa184f100, wheelIndex=0, interpolatedTransform=false) at btRaycastVehicle.cpp:107
    frame #2: libworldexplore.so`btRaycastVehicle::updateVehicle(this=0xa184f100, step=0.0166666675) at btRaycastVehicle.cpp:273
    frame #3: libworldexplore.so`btRaycastVehicle::updateAction(this=0xa184f100, collisionWorld=0xb4086790, step=0.0166666675) at btRaycastVehicle.h:88
    frame #4: libworldexplore.so`btDiscreteDynamicsWorld::updateActions(this=0xb4086790, timeStep=0.0166666675) at btDiscreteDynamicsWorld.cpp:614
    frame #5: libworldexplore.so`btDiscreteDynamicsWorld::internalSingleStepSimulation(this=0xb4086790, timeStep=0.0166666675) at btDiscreteDynamicsWorld.cpp:513
    frame #6: libworldexplore.so`btDiscreteDynamicsWorld::stepSimulation(this=0xb4086790, timeStep=0.0167804994, maxSubSteps=2, fixedTimeStep=0.0166666675) at btDiscreteDynamicsWorld.cpp:455
    frame #7: libworldexplore.so`Urho3D::PhysicsWorld::Update(this=0xb4286200, timeStep=0.0167804994) at PhysicsWorld.cpp:256
    frame #8: libworldexplore.so`Urho3D::PhysicsWorld::HandleSceneSubsystemUpdate(this=0xb4286200, eventData=0xb43a43b0) at PhysicsWorld.cpp:796
    frame #9: libworldexplore.so`Urho3D::EventHandlerImpl<Urho3D::PhysicsWorld>::Invoke(this=0xa18c29e0, eventData=0xb43a43b0) at Object.h:307
    frame #10: libworldexplore.so`Urho3D::Object::OnEvent(this=0xb4286200, sender=0xa18ba280, eventType=(value_ = 1997371372), eventData=0xb43a43b0) at Object.cpp:113
    frame #11: libworldexplore.so`Urho3D::Object::SendEvent(this=0xa18ba280, eventType=(value_ = 1997371372), eventData=0xb43a43b0) at Object.cpp:325
    frame #12: libworldexplore.so`Urho3D::Scene::Update(this=0xa18ba280, timeStep=0.0167804994) at Scene.cpp:787
    frame #13: libworldexplore.so`Urho3D::Scene::HandleUpdate(this=0xa18ba280, eventData=0xb43f2ca0) at Scene.cpp:1171
    frame #14: libworldexplore.so`Urho3D::EventHandlerImpl<Urho3D::Scene>::Invoke(this=0xa18c2800, eventData=0xb43f2ca0) at Object.h:307
    frame #15: libworldexplore.so`Urho3D::Object::OnEvent(this=0xa18ba280, sender=0xb43fc740, eventType=(value_ = 915638697), eventData=0xb43f2ca0) at Object.cpp:121
    frame #16: libworldexplore.so`Urho3D::Object::SendEvent(this=0xb43fc740, eventType=(value_ = 915638697), eventData=0xb43f2ca0) at Object.cpp:355
    frame #17: libworldexplore.so`Urho3D::Engine::Update(this=0xb43fc740) at Engine.cpp:695
    frame #18: libworldexplore.so`Urho3D::Engine::RunFrame(this=0xb43fc740) at Engine.cpp:519
    frame #19: libworldexplore.so`Urho3D::Application::Run(this=0xb4266600) at Application.cpp:86
    frame #20: libworldexplore.so`RunApplication() at TestRayVehicleEnvironment.cpp:45
    frame #21: libworldexplore.so`::SDL_main(argc=0, argv=0xae7ff9e0) at TestRayVehicleEnvironment.cpp:45
    frame #22: libworldexplore.so`Java_org_libsdl_app_SDLActivity_nativeInit(env=0xb43f9940, cls=0xae7ffa8c, array=0xae7ffa90, filesDir="/data/data/co.deepstudio.worldexplore/files") at SDL_android_main.c:69
    frame #23: 0xa463572b
[raycastVehicle_stacktrace.txt](https://github.com/urho3d/Urho3D/files/1047258/raycastVehicle_stacktrace.txt)
[raycastvehicle_problems.tar.gz](https://github.com/urho3d/Urho3D/files/1047269/raycastvehicle_problems.tar.gz)

**Comment by slapin** [comment]
Could you please update to current master and re-check if this is still reproducible?

**Comment by redmouth** [comment]
Great job, the latest master branch works on android. Thanks :+1:

**Comment by cadaver** [comment]
Can this be closed then?

**Comment by redmouth** [comment]
yes
