### ISSUE TITLE
Incorrect transparency between batches

### ISSUE THREAD

**Issue by sabotage3d** [urho3d/Urho3D#1968]
I am getting wrong transparency when using depth with multiple batches. In my test one of the batches, the green trail is opaque in relation to the red trail where the red trail is working correctly. They both have 0.5 alpha and are placed at the origin.
In my tests I have the following. For red trail is Trail1 and the green trail is Trail2. They have the same material and technique, but renamed to Trail1 and Trail2 accordingly.

Material:
```
<?xml version="1.0"?>
<material>
    <technique name="Techniques/Trail1.xml" quality="1" loddistance="0" />
    <texture unit="diffuse" name="Textures/RibbonTrail.png" />
	<parameter name="UOffset" value="1 0 0 0" />
	<parameter name="VOffset" value="0 1 0 0" />
	<parameter name="MatDiffColor" value="1 1 1 0.5" />
	<parameter name="MatEmissiveColor" value="0 0 0" />
	<parameter name="MatEnvMapColor" value="0 0 0" />
	<parameter name="MatSpecColor" value="0 0 0 0" />
	<cull value="ccw" />
	<shadowcull value="ccw" />
	<depthbias constant="0" slopescaled="0" />
</material>
```
Technique:
```
<technique vs="Trail1" ps="Trail1" vsdefines="VERTEXCOLOR" psdefines="DIFFMAP VERTEXCOLOR">
    <pass name="alpha" depthwrite="true" blend="alpha" />
</technique>
```
The shader is modified Unlit adding `gl_Position.z` offset.
In the Shader for the first image I have:
Trail1:`gl_Position.z = -1.0;`
Trail2:`gl_Position.z = 1.0;`
In the Shader for the second image I have:
Trail1:`gl_Position.z = 1.0;`
Trail2:`gl_Position.z = -1.0;`

Correct behaviour of the Green trail in front of the Red Trail.
![screen shot 2017-06-02 at 21 56 30](https://cloud.githubusercontent.com/assets/4654347/26744635/a91ea510-47de-11e7-9cf5-5053ccee24ad.png)

Incorrect behaviour of the Red trail in front of the Green Trail.
![screen shot 2017-06-02 at 21 56 07](https://cloud.githubusercontent.com/assets/4654347/26744646/b47cdba2-47de-11e7-8252-321b64e648e1.png)

**Comment by cadaver** [comment]
Typically depth write doesn't play well with transparency. Have you tried with it off?

**Comment by sabotage3d** [comment]
When it is off I don't have fine control per polygon sorting between multiple batches. By default with two batches and `depthwrite="false"` the sorting seems to be flipping between the two or sometimes one is always on top of the other. Can we do manual sorting for the transparency between the batches? I am also confused why one works and the other doesn't.

**Comment by eugeneko** [comment]
You can control the order by changing Z value or using z bias. Transparent stuff always was a problem for GAPIs...

**Comment by sabotage3d** [comment]
I already played with the z bias and I am basically modifying the depth with `gl_Position.z`with no success.
If I am not mistaken the sorting in the pass alpha is done back to front using the actual world transform position rather than using the depth.
Can we have an option to sort the transparent objects by the depth value? For the same batch this is already working. Basically I have an index for each polygon which I am using for sorting in my app. If there are any other options that I can use instead of depth that would be great.

**Comment by cadaver** [comment]
The engine sorts transparent passes by distance from camera, a bit differently depending on if it's perspective or orthographic. But it cannot know if you're going to use some other depth value in the shader, if that's what you're asking. 

You can control materials' render order if necessary (Material::SetRenderOrder), this should override the default depth sorting.

**Comment by sabotage3d** [comment]
I tried `Material::SetRenderOrder` but it didn't affect them. Can you please show me the relevant parts of the code for sorting the transparent passes? If the current sorting uses distance to camera can we send our own transformation in Z without actually moving the trails closer to the camera?

**Comment by cadaver** [comment]
For the back-to-front sorting, see BatchQueue::SortBackToFront() in Batch.cpp.

**Comment by sabotage3d** [comment]
I see. If this is the sorting between the batches, how is the sorting done inside the same batch?

**Comment by cadaver** [comment]
In the end, a batch is a Geometry object drawn with a certain Material (or actually technique / pass once we go into the actual draw operation). So the answer is, by the order of vertices in the vertex / index buffer. That's only the business of the Drawable subclass in question. For example, BillboardSet sorts the billboards when sorting is enabled. While naturally for models the sorting is static.

**Comment by sabotage3d** [comment]
What would you suggest for more complex cases where I am ordering my vertices based on my own index attribute between two batches? Would you suggest any workarounds for this case? I understand it is not trivial. The same problem is with multiple RibbonTrails, BillboardSets and ParticleEmitters. I am thinking of merging them in one batch the problem is that if I merge too many I would loose control over controlling the number of batches.

**Comment by cadaver** [comment]
I don't have suggestions for now.

**Comment by sabotage3d** [comment]
Is there way to have two RibbonTrails components with two different materials and combine them into one batch?

**Comment by cadaver** [comment]
You would need to make them aware of each other, for example some kind of RibbonTrail Manager component. So with engine changes, yes.

**Comment by sabotage3d** [comment]
I can merge the batches together what I am not sure is how to apply different materials on one batch? I was looking into OIT as well but the performance won't be great.

**Comment by cadaver** [comment]
You can't use two materials directly in the same batch, so you'd need a custom mechanism where you would index to a material parameters array, and possibly texture array.

**Comment by sabotage3d** [comment]
What about Weighted, Blended Order-Independent Transparency? It requires only GPU that supports blending to render targets with more than 8 bits per channel: http://casual-effects.blogspot.co.uk/2014/03/weighted-blended-order-independent.html

**Comment by sabotage3d** [comment]
I am currently trying to implement  Weighted Blended Order Independent Transparency with Urho3D. One problem I cannot figure out is how to make batch sorting to play nicely with OIT.  What would be the best way of disabling the sorting so that I control it with OIT myself?

**Comment by cadaver** [comment]
There is always going to be some kind of sorting, either front-to-back with state having priority, or back-to-front according to distance (normal behavior with alpha passes.)

Look into the renderpath documentation: https://urho3d.github.io/documentation/HEAD/_render_paths.html

See the "sort" attribute definition for a scenepass command. I'd probably recommend you having your own custom scene pass for OIT rendered batches, instead of reusing the "alpha" pass at all.

**Comment by sabotage3d** [comment]
Thank you. I managed to get OIT working with two passes. The problem is when I composite the result the opaque objects can be either in front or behind. How should I handle intersecting between opaque and transparent objects? Below are the passes used for the transparent OIT objects.
```
    <pass name="oit_accum" depthtest="always" depthwrite="false" psdefines="ACCUM" blend="add" /> 
    <pass name="oit_reveal" depthtest="always" depthwrite="false" psdefines="REVEAL" blend="reveal" /> 
```
![screen shot 2017-07-16 at 18 38 30](https://user-images.githubusercontent.com/4654347/28249886-3c51c576-6a56-11e7-8e05-e2f6b03664f4.png)
