### ISSUE TITLE
Video recording issue

### ISSUE THREAD

**Issue by slapin** [urho3d/Urho3D#1969]
The hardware: GTX660, i7 2600K
OS: Linux

The issue: Not possible to record video for youtube without artefacts. Games and other applications are recorded fine, only Urho applications get artefacts.

Example:

https://www.youtube.com/watch?v=e2Sco61dXzs

This happened not so long ago (may be several months), I was able to make videos before without problems. Enabling vsync for everything, etc. did not help.
I use ffmpeg -f x11grab. Everything else (including games) is perfectly recorded, but not Urho.

**Comment by Modanung** [comment]
Does 'other applications' include continuously 3D accelerated ones?
Maybe give [SSR](https://en.wikipedia.org/wiki/SimpleScreenRecorder) a try.

**Comment by slapin** [comment]
All other 3D applications, including games are recorded fine.

**Comment by SuperWangKai** [comment]
Have you tried to open VSync? @slapin

**Comment by slapin** [comment]
Yes, I tried both with vsync and without vsync, disabling and enabling it
in nvidia-settings and in Urho.

**Comment by slapin** [comment]
Also as I mentioned all other applications/games are recorded fine.

**Comment by slapin** [comment]
Also older versions of Urho worked fine too. But I did not check this
recently.
But still older and newer games are recorded fine (even when running wine).
So system configuration should not be a reason.

**Comment by SirNate0** [comment]
I can't help with the problem, but in my own brief testing just now I found that Simple Screen Recorder gave results with fewer artifacts (I think there were a few frames dropped, but nothing else) than ffmpeg's x11grab (though this could have been because I grabbed the whole screen with ffmpeg and only the window in question with SSR), so you may want to see if the problem persists if you use SSR.

**Comment by slapin** [comment]
There is no difference with whatever tools I use. I tried plain ffmpeg,
OBS, and a set of gnome tools.

**Comment by carnalis** [comment]
Issue resolved?

**Comment by slapin** [comment]
No.
