### ISSUE TITLE
Couldn't set position for borderless window

### ISSUE THREAD

**Issue by pengfei666** [urho3d/Urho3D#1970]
Not sure it is a bug or an intended behavior.

When I want to create a fixed size borderless window, but it seems to ignore the window position I set.

The engine parameters are below
```
    engineParameters_[EP_BORDERLESS] = true;
    engineParameters_[EP_WINDOW_POSITION_X] = 100;
    engineParameters_[EP_WINDOW_POSITION_Y] = 100;
    engineParameters_[EP_WINDOW_WIDTH] = 500;
    engineParameters_[EP_WINDOW_HEIGHT] = 500;
```
I get the below result:
![4_h 9z kzvt0n_ gxtjj](https://cloud.githubusercontent.com/assets/25144819/26776667/b1b00c70-4a0c-11e7-966f-4d99208d21a4.png)

**Comment by pengfei666** [comment]
UPDATE: I find this issue in OpenGL mode and have a fix for it. I am seeing whether it works in DX mode.

I will open a PR for that later.

**Comment by pengfei666** [comment]
After my PR:

![pho95i owyi_0mzasmdj 4](https://cloud.githubusercontent.com/assets/25144819/26777043/53976ce4-4a0e-11e7-838a-0f4a701030e2.png)

**Comment by cadaver** [comment]
Merged PR which fixes this.
