### ISSUE TITLE
DebugRenderer Bug With HW Depth

### ISSUE THREAD

**Issue by OldSnake22** [urho3d/Urho3D#1975]
Hello i have switched from PBRDeferred renderpath to a PBRDeferredHW renderpath  and now debug renderer lines WITH depth testing do not render correctly (line without depth test are rendered correctly).

Here is a video of the issue: https://www.youtube.com/watch?v=hEthCaE5oxs

As you can see it is behaving quite strangely... i can see some partial lines when i move the camera.

Any idea about the cause of this issue ? Thank

**Comment by cadaver** [comment]
Which graphics API (D3D9 / 11 / GL)?

**Comment by OldSnake22** [comment]
Oh sorry, DX11.

**Comment by cadaver** [comment]
Thanks for noticing, this was a quite clear-cut issue with the debug rendering not taking into account that a custom depth buffer had been defined.
