### ISSUE TITLE
Text glyphs are sometimes clipped

### ISSUE THREAD

**Issue by iainmerrick** [urho3d/Urho3D#1978]
This bug usually isn't visible because the font hinter adjusts glyphs to fit the pixel grid. It's much more visible if hinting is disabled:

![clipped_glyphs](https://user-images.githubusercontent.com/252111/26988800-55e4e78c-4d16-11e7-9bc2-79436380a0cc.png)

Note that some glyphs are shifted up or down too.

Looks like this happens because the glyph's size and position are calculated by *rounding* the font metrics (meaning fractional pixels are sometimes discarded). The right thing to do would be to use ceil(), rather than rounding. Better still we should use the exact rendered bitmap size reported by FreeType, which is already in integral pixels.

**Comment by cadaver** [comment]
Thanks for the font-related work; the font algorithms are rather involved and typically dev testing happens with only the limited examples that come with the engine repo, so it's good that someone stresses them properly!
