### ISSUE TITLE
Will be Urho3D supports webp images?

### ISSUE THREAD

**Issue by halcyonx** [urho3d/Urho3D#1985]
webp format has good quality and compression, why webp still not supported?

**Comment by OvermindDL1** [comment]
You should PR support in.  :-)

WebP is quite a good format, I'd be all for it.

**Comment by slapin** [comment]
What is WebP and what is so good about it?

**Comment by OvermindDL1** [comment]
Think of it as a newer png and jpeg (it can be lossless or lossy) designed for better compression (compresses better than both) while having faster decompression speed (great for loading on webpages faster, or say in a game engine):  https://developers.google.com/speed/webp/

It is popping up in a lot of non-web contexts lately due to how well designed it is.

**Comment by carnalis** [comment]
I'm all for it. I am 'exploring' adding webp support to Urho, though if some other is already working on it...

**Comment by 1vanK** [comment]
anyway DDS is optimal format for games (since it has hardware support)

**Comment by carnalis** [comment]
I now have WebP working in a local branch, to push and PR after checking that it's up to Urho standards.

I ran some tests in Urho, mass-loading thousands of images of various sizes and formats.

WebP lossless decodes about 35% **slower** than PNG, and lossy is slower than that. This seems roughly consistent with tests done by others, and not unexpected given such high compression. Actually, early implementations were 50% slower than PNG.

Still, it's a highly configurable modern format with a number of advantages and I intend to add SaveWEBP() too.
https://developers.google.com/speed/webp/

**Comment by cadaver** [comment]
What's the library like? If it's not trivially small like STB or JO_Jpeg you could make a build option, which you can default on. Then someone looking for minimum engine size can disable it.

**Comment by slapin** [comment]
nice, cool thing to have.

**Comment by carnalis** [comment]
@cadaver The library consists of the C source dir in the repo: 
https://chromium.googlesource.com/webm/libwebp/+/master/src/
I have gone with the build option.

**Comment by carnalis** [comment]
Any feedback welcome.  https://github.com/carnalis/Urho3D/tree/webp

**Comment by carnalis** [comment]
WebP support has been merged into master (thanks @cadaver).

**Comment by cadaver** [comment]
Will close this now. Thanks to you for the work!
