### ISSUE TITLE
How to create HDRI sky for PBR scenes?

### ISSUE THREAD

**Issue by VinnyVicious** [urho3d/Urho3D#1988]
I'm trying to find any docs on the PBR implementation of Urho, but could not find anything about how to properly create a sky for it. I'm trying to use this as a base: http://noemotionhdrs.net/hdrday.html 

Should i use cmft to convert that to a cubecross or something? Where do i feed the radiance/irradiance results from cmft?

**Comment by dragonCASTjosh** [comment]
Yes you will need to use cmft, and you only need the radiance (ill have to check the name) once you have filtered it you will have to convert the DDS format as urho doesnt support the specific format cmft uses. For that i used pvrtextool. 

I hope to streamline this at some point but many of the features that would help this are considered beyond the scope of the engine
