### ISSUE TITLE
Where is URHO3D_OPENGL?

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#1989]
Don't see it anymore in CMake UI.

**Comment by weitjong** [comment]
It is now only a build option for Urho3D project and not for downstream projects, if that is your question. The latter inherits certain baked options from the Urho3D library that it links against.

**Comment by eugeneko** [comment]
I am trying to build Urho itself, not downstream. I see URHO3D_D3D11 but somewhy don't see URHO3D_OPENGL.

**Comment by weitjong** [comment]
I just have time to test this out on my Win7 VM and I could not reproduce this issue. The cmake-gui showed both URHO3D_OPENGL and URHO3D_D3D11 as build options, grouped under "URHO3D".

**Comment by eugeneko** [comment]
Ok, I'll re-try to reproduce this issue later

**Comment by eugeneko** [comment]
Can't reprocude with clean fresh work copy, probably I have some cache broken...

**Comment by rasteron** [comment]
@eugeneko Just did a new build with MinGW using the latest and URHO3D_OPENGL works ok.

**Comment by eugeneko** [comment]
@weitjong I found the case!
If I set URHO3D_D3D11, URHO3D_OPENGL disappears.
This may seem logical, but if I want to switch from DX11 to GL I have to switch DX11 off, configure, switch GL on and configure again.
Probably, this shan't behave in this way, floating parameters are confusing.

**Comment by weitjong** [comment]
That is plausible. I also agree current implementation of build options for Graphics API selection is not nice, considering we may  potentially support more in future. Perhaps will revisit it when the time comes.
