### ISSUE TITLE
-s DISABLE_EXCEPTION_CATCHING=1 in Emscripten

### ISSUE THREAD

**Issue by juj** [urho3d/Urho3D#1993]
Reading [Emscripten-specific CMake flags](https://github.com/urho3d/Urho3D/blob/master/CMake/Modules/UrhoCommon.cmake#L680), there's

```CMake
# Preserve LLVM debug information, show line number debug comments, and generate source maps; always disable exception handling codegen
set (CMAKE_EXE_LINKER_FLAGS_DEBUG "${CMAKE_EXE_LINKER_FLAGS_DEBUG} -g4 -s DISABLE_EXCEPTION_CATCHING=1")
set (CMAKE_MODULE_LINKER_FLAGS_DEBUG "${CMAKE_MODULE_LINKER_FLAGS_DEBUG} -g4 -s DISABLE_EXCEPTION_CATCHING=1")
```

the comment says it's desired to always disable exception handling codegen, but in the following code, `-s DISABLE_EXCEPTION_CATCHING=1` is only added for linker flags in debug build. Perhaps that was intended to be as follows?

```CMake
set (CMAKE_EXE_LINKER_FLAGS_DEBUG "${CMAKE_EXE_LINKER_FLAGS_DEBUG} -g4")
set (CMAKE_MODULE_LINKER_FLAGS_DEBUG "${CMAKE_MODULE_LINKER_FLAGS_DEBUG} -g4")
set (CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -s DISABLE_EXCEPTION_CATCHING=1")
set (CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS} -s DISABLE_EXCEPTION_CATCHING=1")
```

(or is the comment outdated?)

Additionally, it is worth noting that `-s DISABLE_EXCEPTION_CATCHING=1` only suppresses catching by making `try-catch` statements no-op fall throughs, but C++ code is still allowed to `throw`, in which case those throws will propagate up to JavaScript code to handle, e.g. `window.onerror()` as last resort.

Searching for `-fno-exceptions` in Urho3D, I find the following:

```
e:\code\urho3d\CMake\Toolchains\Android.cmake:
  101  #
  102  #     Possible values are:
  103: #       system         -> Use the minimal system C++ runtime library. Implies -fno-rtti -fno-exceptions.
  104  #       gabi++_static  -> Use the GAbi++ runtime as a static library.
  105  #       gabi++_shared  -> Use the GAbi++ runtime as a shared library.
  ...
  572              set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fexceptions" CACHE INTERNAL "CXX Compiler flags")
  573          else ()
  574:             set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fno-exceptions" CACHE INTERNAL "CXX Compiler flags")
  575          endif ()
  576          set (CMAKE_EXE_LINKER_FLAGS -Wl,-z,nocopyreloc)

e:\code\urho3d\Source\Clang-Tools\CMakeLists.txt:
   64      set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /EHs-c- /GR-")
   65  else ()
   66:     set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fno-exceptions -fno-rtti")
   67  endif ()
   68  

e:\code\urho3d\Source\ThirdParty\LuaJIT\src\lj_err.c:
   56  ** TARGET_CFLAGS), all of your C/Lua binding code, all loadable C modules
   57  ** and all C libraries that have callbacks which may be used to call back
   58: ** into Lua. C++ code must *not* be compiled with -fno-exceptions.
   59  **
   60  ** EXT cannot be enabled on WIN32 since system exceptions use code-driven SEH.
```

Is Urho3D generally compiled with `-fno-exceptions` and/or `-fno-rtti`? In Emscripten `-s DISABLE_EXCEPTION_CATCHING=1` is often paired with `-fno-exceptions` to disallow `throw` statements as well - would that be intentional for Urho3D?

**Comment by weitjong** [comment]
As I recall it, I wanted to configure as per what you wrote in the longer version. But I saw EMCC implementation has actually already set that setting by default (for performance), except when the optimization is turned off. And since we turn off optimization in our Debug build config, to make it consistent everywhere in our build system (as per comment) then I figure I just have flip the switch for that build config.
