### ISSUE TITLE
(Possibly) the newly contributed code has caused Urho3D not build out-of-the-box for Web platform on Windows host system

### ISSUE THREAD

**Issue by weitjong** [urho3d/Urho3D#1998]
see https://discourse.urho3d.io/t/using-urho-emscripten-build-system-leads-to-asmjs-exception/3267/5

Add it as an issue here so we don't forget about it.

**Comment by cadaver** [comment]
Can check this in near future. Possibly didn't test the very latest versions of the PR on Win / Emscripten anymore. Ifdef check should do the trick.

**Comment by Florastamine** [comment]
Disabling the particular API in question is one way, rewriting the `_WIN32` section of GetOSVersion() would be another way. Problem is, the method which utilizes `RTL_OSVERSIONINFOW` is very accurate while maintaining backwards compatibility, while other APIs for version detection are either old, deprecated, or not supported on old versions of Windows.
