### ISSUE TITLE
Working directory is not respected when prefixing resource paths.

### ISSUE THREAD

**Issue by iSLC** [urho3d/Urho3D#2001]
Changing the working directory does not affect the `FileSystem::GetProgramDir` result (_on windows at least_) and as such, when `resourcePrefixPaths` are being processed inside `Engine::InitializeResourceCache`, the paths are prefixed with the path of the executable and not the working directory.

Not sure if this is the intended behavior but I find it more preferable to use the working directory than the actual executable path.

For example. I may group my binaries in sub-folders like `win##`, `linux##` and I would like to not have to duplicate the resources in each of those folders. Of course, I could manually add such a prefix path, but having it by default seems more appropriate.

I could've sworn this is how it worked so far because this only occurred when I pulled the latest source from the repository.

**Comment by weitjong** [comment]
The behavior change is intended. See commit https://github.com/urho3d/Urho3D/commit/420ce387e0dce0a8d396b14a128805fd98259fc9.

**Comment by iSLC** [comment]
The behavior of `GetProgramDir` is correct. I guess I expressed myself incorrectly. My question was mostly about this code:

```
    for (unsigned i = 0; i < resourcePrefixPaths.Size(); ++i)
        resourcePrefixPaths[i] = AddTrailingSlash(
            IsAbsolutePath(resourcePrefixPaths[i]) ? resourcePrefixPaths[i] : fileSystem->GetProgramDir() + resourcePrefixPaths[i]);
```

On whether it should use `GetCurrentDir` instead of `GetProgramDir`. Because `GetProgramDir` is not affected by changes to the working directory.

**Comment by weitjong** [comment]
I understand your point. However, with the current prefix paths setup, an app could configure any search path relative to the "Program Dir" that it wants. In the past that "Program Dir" may fallback to cwd, which is not the case any longer. And we see that to be more a consistent behavior. If your app need to include another path to be search, the app has to configure the search path explicitly.

**Comment by iSLC** [comment]
No problem. I'll just add the path explicitly. I just wanted to be sure that this was the intended behavior. Thanks for clearing this out.
