### ISSUE TITLE
Font kerning is broken

### ISSUE THREAD

**Issue by iainmerrick** [urho3d/Urho3D#2003]
Kerning values are associated with the wrong char codes. This is due to an off-by-one error introduced by my own commit 39930c9ab492 -- doh! Sorry about that, will fix ASAP.

Additionally, I'm not sure that the kerning values are being interpreted correctly. I don't see any scaling from abstract em units to on-screen pixels. But I could be wrong, I'll investigate further.

**Comment by cadaver** [comment]
Merged the fix PR.
