### ISSUE TITLE
PhysicsWorld2D in child node

### ISSUE THREAD

**Issue by keithyipkw** [urho3d/Urho3D#2006]
There seem to be no established ways to manage different "scenes" like other game frameworks. I am trying to move all child nodes and related components under a parent node. `PhysicsWorld2D` does not fully work if I add it to a child node of a `Scene`. `PhysicsWorld2D::GetRigidBody` does not return a body to the same screen coordinates I clicked anymore. `PhysicsWorld2D::DrawDebugGeometry` does not draw anything. Is it true that `PhysicsWorld2D` must be added to a `Scene`?

**Comment by eugeneko** [comment]
Yes. Some components must lay in the root.
If you need two of them, you shall have two scenes.

**Comment by cadaver** [comment]
Going to close this, as this is the intended limitation.
