### ISSUE TITLE
Possible editor bug: can't run editor from SDK installation if resource path doesn't equal to SDK's Data.

### ISSUE THREAD

**Issue by KonstantinTomashevich** [urho3d/Urho3D#2011]
I build latest Urho3D (from master branch) and then I generate Urho3D SDK using `make install`.
Editor from Urho3D works perfectly if resource path is setted to SDK's Data. In my system it's `D:/CXXProjects/Urho3D-Windows-Static-Build/SDK/share/Resources/Data/`.
Then I set resource path to my project data (`D:/CXXProjects/colonization/colonization/bin/Data/`).
Then I restart editor and editor console shows this error:
```
[Wed Jul 05 21:06:42 2017] ERROR: Scripts/Editor/EditorTerrain.as:33,9 - Exception 'Null pointer access' in 'void TerrainEditorBrushVisualizer::Hide()'
AngelScript callstack:
	Scripts/Editor/EditorTerrain.as:void TerrainEditorBrushVisualizer::Hide():33,9
	Scripts/Editor/EditorTerrain.as:void TerrainEditor::HideBrushVisualizer():142,9
	Scripts/Editor/EditorView.as:void ViewMouseMove():1833,13
	Scripts/Editor/EditorEventsHandlers.as:void EditorMainHandleMouseMove(StringHash, VariantMap&inout):58,5
```
I can't use editor because it spams this error to console and doesn't shows any inspector windows.

**Comment by cadaver** [comment]
Thanks for reporting, have to test. Just to make it clear, do you use the editor GUI to set the resourch path?

**Comment by cadaver** [comment]
Managed to reproduce. Believe this is two bugs in one, the terrain editor not being robust enough for failure, and the resource system going a bit bonkers with the SDK resources dir.

**Comment by KonstantinTomashevich** [comment]
Yes, I use editor GUI.
