### ISSUE TITLE
WeakPtr and friend class

### ISSUE THREAD

**Issue by Commondor** [urho3d/Urho3D#2015]
Hi,

Cosmetic bug: class WeakPtr self-friendly:

Code:
`
template <class T> class WeakPtr
{
...
private:
     template <class U> friend class WeakPtr;
...
}`

**Comment by eugeneko** [comment]
Have you tried to remove the line and compile?
https://ideone.com/SynzaD

**Comment by Commondor** [comment]
ok, Understood
