### ISSUE TITLE
"Smart" techniques

### ISSUE THREAD

**Issue by t-artikov** [urho3d/Urho3D#2018]
The thing that our designers found complicated in Urho3D is the assignment of material techniques. They are used to working with 3ds Max, which has a small number of material types with a rich set of parameters. Why would not Urho3D work in the same way? The engine could have special "smart" techniques which set the shader defines and the render states based on material parameters. _Default.xml_ technique, for example, can replace all techniques with the standard lighting model. As result,
```
<material>
    <technique name="Techniques/Default.xml" />
    <texture unit="diffuse" name="Textures/diffuse.png" />
    <texture unit="specular" name="Textures/specular.png" />
    <parameter name="MatDiffColor" value="1 1 1 0.5" />
</material>
```
will be equal to a material with the _DiffSpecAlpha.xml_ technique.
Other possible "smart" techniques are _PBR.xml_, _Unlit.xml_, _Particle.xml_.

I suggest to @cadaver to consider the feasibility of this feature, and want to know how useful it will be for the engine's users.

**Comment by 1vanK** [comment]
You already can set defines in material

**Comment by t-artikov** [comment]
@1vanK 
It is not better than the complicated technique names from the designer's point of view. You have to write weird strings "DiffNormalSpecEmissiveAlpha.xml" or "DIFFMAP NORMALMAP SPECMAP EMISSIVEMAP" instead of just select the required texture maps. It also does not solve the problem with transparency, a material with MatDiffColor.a < 1 should have alpha blending.

**Comment by SirNate0** [comment]
But if Textures/diffuse.png has an alpha channel, shouldn't it also use either alpha blending or masking?
And how would the smart technique decide? I'm not opposed to it, I just wanted to point out that there may be other things that have to be considered in making it.

Also, if this is a feature implemented more in the engine code than in the definition of the techniques, I would prefer going with the technique name "Default", but I think you are proposing allowing the technique to somehow specify defines based on conditionals within the definition of the technique, so I don't think that suggestion is actually important. Something like:
```xml
<technique vs="LitSolid" ps="LitSolid" psdefines="DIFFMAP">
    <if condition="MatDiffColor.a &lt; 1">
        <pass name="alpha" depthwrite="false" blend="alpha" />
        <pass name="litalpha" depthwrite="false" blend="addalpha" />
    </if>
    <else>
        <pass name="base" />
        <pass name="litbase" psdefines="AMBIENT" />
        <pass name="light" depthtest="equal" depthwrite="false" blend="add" />
        <pass name="prepass" psdefines="PREPASS" />
        <pass name="material" psdefines="MATERIAL" depthtest="equal" depthwrite="false" />
        <pass name="deferred" psdefines="DEFERRED" />
        <pass name="depth" vs="Depth" ps="Depth" />
    </else>
    <pass name="shadow" vs="Shadow" ps="Shadow" />
</technique>
```
(But with a lot more conditions)

**Comment by t-artikov** [comment]
@SirNate0
Yes, I believe the alpha channel of the diffuse texture should be taken into account. To enable alpha masking, an additional material parameter can be used.
Please note that I do not propose a specific solution. I don't know which implementation is better in C++ code or fully data driven (with Turing complete language inside technique definitions 😄). I believe the first one is much simpler. 
My idea is to make life easier for designers - reduce the number of techniques, don't duplicate information that is already known from the material parameters.
To achieve it, knowledge of the engine internals much greater than mine is required.

**Comment by eugeneko** [comment]
@t-artikov this topic was discussed some time ago when @cadaver improved materials definitions but I don't remember conclusion... AFAIK, the problem was that there is no clean proposal of such smart techniques implementation plus there are possible problems with redundand shaders.

Once you start to turn definitions on automatically, there appears a chance that some redundand or useless defines will be turned on. This will lead to additional shader variances and worse rendering performance.

**Comment by cadaver** [comment]
There's built-in automatic shader defines insertion.. it's documented here. https://urho3d.github.io/documentation/HEAD/_shaders.html

But it's pretty strict, it's only limited to lighting, geometry types, shadows - the things where you want the same material or technique to dynamically behave right.

I can safely say I'm not going to work on this. A well-written PR will be considered, but it should always be possible to opt-out of the "smart" technique mechanism.

**Comment by t-artikov** [comment]
@cadaver 
Thanks for the answer. I also don't have plans to implement it myself in the near future.

**Comment by t-artikov** [comment]
I have remembered the implementation of the material system in a little-known abandoned engine written by a talented Russian programmer.
https://bitbucket.org/DikobrAz/slonengine/src/6980bc7e71a18feeedfbfc50319ca63cb5f046b3/bin/Data/Effects/ForwardRendering.fx
A great source of inspiration, I believe.

**Comment by SuperWangKai** [comment]
The problem is not the techniques, it's the inconvenience of the editor. If we can select from a list instead of files...
