### ISSUE TITLE
Error with Maximizing Window

### ISSUE THREAD

**Issue by SirNate0** [urho3d/Urho3D#2019]
I'd have to go back and build with 1.6, but I think in switching from 1.6 to HEAD calling Graphics::Maximize() increases the size of the window, but leaves the game rendering to the same size region (placed in the lower left of the window) though the view is changed to match the new full window size (i.e. that little region is 'zoomed in' on the lower left part of the camera, with everything else black). It only occurs when running through the discrete graphics card (using optirun), so this may just be a problem with bumblebee, and not with Urho. Maximizing the window with the window controls exhibits the same behavior, but if I resize the window by grabbing the borders it works properly (it also works properly with the Ctrl+Alt+NumPad5 shortcut that resizes the window to fill the screen without maximizing it, and then maximizes it if pressed again).

**Comment by cadaver** [comment]
Cannot reproduce this in a simple Windows OpenGL build, so it's potentially something OS- driver- or windowmanager-specific. Can retry in Linux later, but I don't have an Optimus configuration running Linux.

**Comment by SirNate0** [comment]
I tried with some other programs -- Blender doesn't have the same problem, but does have a different one, and Voxelands has an identical problem, so I would assume its something OS- driver- or windowmanager-specific as you suggested.

**Comment by cadaver** [comment]
Didn't reproduce on a laptop running Ubuntu 14 + Intel graphics.
