### ISSUE TITLE
Knowing which nodes finish their attribute animation

### ISSUE THREAD

**Issue by keithyipkw** [urho3d/Urho3D#2021]
I have multiple similar nodes to animate. Basic event subscriptions are insufficient to know which nodes finish. There are no senders in the callback or in the `VariantMap& eventData`. I can only think of two workaround

1. Use eventTypes as the animation IDs and store them in a `map`
2. Use `std::bind`
```
SharedPtr<ValueAnimation> animation(new ValueAnimation(GetContext()));
animation->SetEventFrame(duration, StringHash(1));
node->SetAttributeAnimation("Position", animation, WM_ONCE);
SubscribeToEvent(node, StringHash(1), bind(&MyClass::MyCallback, this, SharedPtr<Node>(node), _1, _2));
```

Is there a built-in way to do it ~~(without subclassing `Node`)~~?

**Comment by SirNate0** [comment]
Isn't there a pointer to the node in the `AnimationFinished` event? Or is this a different event?

**Comment by eugeneko** [comment]
Offtop: You are not allowed to subclass `Node`.

**Comment by SirNate0** [comment]
You could try adding the node to the event data for that frame (`animation->SetEventFrame(duration, E_ANIM_FINISHED, variantMapContainingReferenceToNode);`). If you didn't want to add it to the VariantMap, you could also write a new component that would just listen for the node sending your event and then send a second event (the actual one) that has the node as a parameter. 

There is also `context_->GetEventSender()`. Will that suffice for your needs?

**Comment by keithyipkw** [comment]
Thanks. They both work nicely.
> You could try adding the node to the event data for that frame (animation->SetEventFrame(duration, E_ANIM_FINISHED, variantMapContainingReferenceToNode);). If you didn't want to add it to the VariantMap, you could also write a new component that would just listen for the node sending your event and then send a second event (the actual one) that has the node as a parameter.

Xcode does not show the optional parameters in auto-complete so I have not noticed the variantData.

> There is also context_->GetEventSender(). Will that suffice for your needs?

It is quite a surprise in the API design that the event sender is not in the callback but in context.
