### ISSUE TITLE
"Roughness", "Metallic" material parameters

### ISSUE THREAD

**Issue by t-artikov** [urho3d/Urho3D#2022]
Since Urho3D 1.6, the material created by the constructor has "Roughness" and "Metallic" parameters. This is a waste of resources when PBR is not used. This is also a bad architectural solution, the Material class should not know about the specific material types.

**Comment by eugeneko** [comment]
The same could be said about any pre-defined parameter, couldn't it?

**Comment by t-artikov** [comment]
I agree, but the problem with the other parameters is not so strong, because they are used in most shaders.

**Comment by cadaver** [comment]
This could maybe be solved by having default values in shaders. However it would need some kind of annotation into the GLSL / HLSL code so it wouldn't be super-clean. For now I just recommend customizing the engine if it bothers you. At runtime, this translates into a couple of hashmap lookups when rendering with a different material, then Graphics quickly notices the parameter is not used by the shader, and skips it.

**Comment by SirNate0** [comment]
A better option, perhaps, for the defaults would be to have them stored in the techniques, as they are responsible for selecting which defines are used that largely determine the parameters needed, and then there doesn't need to be further modification to the shader code. It would make the techniques much longer and more complicated, though...
