### ISSUE TITLE
Quaternion-Vector3 SSE multiply broken

### ISSUE THREAD

**Issue by QBkGames** [urho3d/Urho3D#2025]
The SSE implementation of the function:
Vector3 operator *(const Vector3& rhs) const
seems to be broken. 
When I multiply the Quaternion with Vector::FORWARD, the resulting vector has the y component 0 (when it should be something else).
I've tried getting the Matrix of the Quaternion and multiply that with the vector and that produces the correct result.
I haven't tried the non-SSE implementation.

**Comment by cadaver** [comment]
Can you state the values (both in the quaternion and vector) that you are using, and the result you are expecting. Thus we can verify with the exact same data, and test the difference between SSE and non-SSE.

**Comment by QBkGames** [comment]
This is embarrassing, I can't reproduce the issue anymore. It must have been a compilation bug that produced erroneous machine code, MS VS does that sometimes if you don't do a clean build for a long time.
Apologies for raising a false alarm.

**Comment by cadaver** [comment]
Thanks for confirming. I tested one randomly picked quaternion + its matrix yesterday, and didn't find any difference either.
