### ISSUE TITLE
Specular calculation is incorrect: it is not eye direction ralated

### ISSUE THREAD

**Issue by SuperWangKai** [urho3d/Urho3D#2027]
![spec_issue](https://user-images.githubusercontent.com/15721569/28356763-c47f7e4c-6c9b-11e7-8ddb-8575bcf80ad7.jpg)

The model is using 'DiffNormal.xml' technique (I also tried the 'DiffNormalSpec.xml' by adding a specular map generated by some textures generation tool).

According to the GLSL or HLSL code, Urho's specular light contribution is calculated under Blinn-Phong model and the specular (highlight) will be changed if we move the camera. However, there is no specular changing if I rotate/translate the editor camera which is very strange.

I hope there is something I missed otherwise it is an serious issue we need to solve.

**Comment by cadaver** [comment]
If you stay in place and rotate, the vector from eye to the object stays unchanged. But when you move, the specular should change too. Check that you in fact have specular lighting in your scene: that the light has non-zero specular intensity, and material has non-zero MatSpecColor parameter (the "a" component is specular power)

**Comment by SuperWangKai** [comment]
Hi @cadaver Thanks for the reply. 

I have checked the specular lighting you mentioned and they are all set correct. However, the specular still stays unchanged if I move the camera (by selecting the character and rotating by middle mouse button). I've been think the rendering result should be more dynamic/shining looking.

I also did a test by using the PBR material and the highlight behaves just all right. i.e. changes following the eye vector change.

![pbr](https://user-images.githubusercontent.com/15721569/28396801-51831e68-6d30-11e7-929d-d1674ec917b4.jpg)
_Correct specular using PBR material_

**Comment by SuperWangKai** [comment]
The alpha component of MatSpecularColor should be large enough otherwise the specular will not have enough power (used in pow() of the shader). Problem solved!

![large_pow](https://user-images.githubusercontent.com/15721569/28406929-e9909a94-6d64-11e7-9a74-fb3e5fae1080.jpg)
