### ISSUE TITLE
Built-in time triggered event in C++

### ISSUE THREAD

**Issue by keithyipkw** [urho3d/Urho3D#2029]
Is there any built-in time trigger events? It seems that there is only delayed calls in the script engine and SDL_timer (not direct Urho3D). I have also found a thread discussing it https://discourse.urho3d.io/t/delayed-execution-in-c/3176.

**Comment by cadaver** [comment]
Not built in. For now I'd recommend building a custom "scheduling" system based on the frame update and sending event by yourself when the time has expired.

**Comment by OvermindDL1** [comment]
Yeah I would never toss that to another thread.

I'd probably just make a module that holds a sorted deque and push a 'time/event' struct on to it, and on each iteration I'd compare the current game time to the head, if the head is less then pop it off and send the event and repeat until it is not greater then, then return.
