### ISSUE TITLE
Text with word wrap not visible

### ISSUE THREAD

**Issue by QBkGames** [urho3d/Urho3D#2043]
If you have a Text visual in the UI that has the "Word Wrap" attribute enabled, the text does not show up until you set its size/width (again) in code.
So, every time you change the Text value, you have to also set its size again, otherwise it is not visible.

**Comment by cadaver** [comment]
Check whether this commit fixes your issue. It may have broken something else, so it might need to be reverted shortly, hopefully not :)

In general, you will need to set a sensible width at least once for a wordwrapping text. Previously, the best answer was to set fixed width for the text element.

**Comment by QBkGames** [comment]
I do have fixed text width set to a sensible value, so the bug was in the engine code.
This fixes the issue (as long as it's not reverted back :) ), thank you.
