### ISSUE TITLE
Editor not launched from Windows Explorer when used symlinks 

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#2046]
https://github.com/urho3d/Urho3D/pull/2041
https://github.com/urho3d/Urho3D/issues/1974

Also ConvertModels.bat does not work never https://github.com/urho3d/Urho3D/pull/2044

**Comment by weitjong** [comment]
The variable expansion for first argument `%0` to obtain the drive letter `~d` and the path `~p` is proven to be not reliable and need to be replaced.

**Comment by 1vanK** [comment]
I vote for copying *.bat :)

**Comment by weitjong** [comment]
And I vote not to. The replacement is a no brained.

**Comment by 1vanK** [comment]
I'm talking about copying not because I do not like simlinks, just I do not known another working variants. Using "current path" %cd% in bat also unreliable. Your variants?

**Comment by 1vanK** [comment]
Opimal variant for my is creating shortcuts for bats (like shortcuts for folder, which are created currently), but it requires external tools

**Comment by OvermindDL1** [comment]
You could just PR in a replacement to the bat file by actually compiling a C++ executable that always works properly on all platforms then.  ^.^

/me is not a fan of script files in general, anytime something weird happens I just switch it to a C++ program instead.  Usually not even much longer either.

**Comment by weitjong** [comment]
Safe the trouble guys. I already know how to fix it but at the moment I have other things to fix. So, this one will just have to wait for a little while.

**Comment by weitjong** [comment]
@1vanK Please try the latest commits in the `better-pch` branch and report back. Thanks.

**Comment by 1vanK** [comment]
Hmm, looks like hack, but it works xD
There is a small problem, when path contains spaces.
In this case I should use quotes it path
![1](https://user-images.githubusercontent.com/13021826/28754188-3b2268ba-7549-11e7-9077-466b4b760e3c.png)
and it breack hack. But I think it's not important. In this case, user can use CD first.

Also still problem with ConvertModels.bat. I think it should use 2 different paths:
PATH_TO_BUILD/tool/OgreImporter PATH_TO_SOURCES/SourceAssets/Jack.mesh.xml
But I do not think that users will use it at all. May be just move ConvertModels.bat from bin to SourceAssets, and users will be able to see, how convert Ogre models, if they suddenly need it

**Comment by weitjong** [comment]
You can't have your cake and eat it too :)

**Comment by 1vanK** [comment]
Anyway I newer use console for launch Editor :)

**Comment by weitjong** [comment]
Exactly! Those batch files and shell scripts are really designed for developers and developers use console or terminal to launch up things, don't they? :)

Let me sleep on it. I don't like the fix that breaks other use case. Thanks for reporting it.

**Comment by 1vanK** [comment]
> developers use console or terminal to launch up things

I happy with Total Commander :)

**Comment by weitjong** [comment]
Since we are not trying to make a generic solution, I think there is one more trick we could try later tonight to detect.

> I happy with Total Commander :)

I used to love the original Norton Commander and its clone too. On Linux we have `Midnight Commander` for free.

**Comment by cadaver** [comment]
Excellent, thanks for the fix!
