### ISSUE TITLE
Vertical Progress Bar wrong direction

### ISSUE THREAD

**Issue by QBkGames** [urho3d/Urho3D#2050]
The ProgressBar in vertical mode scales from top to bottom. It would be a lot more useful in practice if it scaled from bottom to the top.
Also, when setting the range, it should also clamp the value to prevent the situation when the range is made smaller than its current value.

Suggestions:
Have the text be able to show 2 modes: Percent (the way it is now) and Ratio, which would show "[value] / [range]", this would be useful for example:
 - Inventory:  "25 / 50 kg"
 - HP: "250 / 600 HP", etc
Which also means that you would be able to set the unit to something other than just "%".

**Comment by weitjong** [comment]
Already closed in #2561.
