### ISSUE TITLE
FindUrho3D.cmake fails with custom install location

### ISSUE THREAD

**Issue by TheComet93** [urho3d/Urho3D#2052]
On my 64-bit Gentoo linux machine I tried installing Urho3D to ```/usr/urho3d```. libUrho3D.so is then located under ```/usr/urho3d/lib64/Urho3D/libUrho3D.so```

This call to ```find_library()``` fails:
```cmake
find_library (URHO3D_LIBRARIES NAMES Urho3D ${URHO3D_LIB_SEARCH_HINT} PATH_SUFFIXES ${PATH_SUFFIX} ${SEARCH_OPT} DOC "Urho3D library directory")
```

If I rename the ```lib64``` directory to ```lib```, it works. So I think there's an issue with cmake not testing for lib64 folders on my machine.

**Comment by TheComet93** [comment]
Ugh, I figured out the issue. I had to first ```include (UrhoCommon)``` before ```find_package (Urho3D)``` works.

**Comment by weitjong** [comment]
Yes, this is how currently it is designed to work. In fact I think UrhoCommon will auto find all the necessary required modules, including "Urho3D", to setup the downstream project.
