### ISSUE TITLE
File::Tell() and relative File::Seek()

### ISSUE THREAD

**Issue by TheComet93** [urho3d/Urho3D#2053]
File should support relative seeking. I'm currently using it to read data from a binary format and need to be able to skip over blocks of data.

**Comment by cadaver** [comment]
GetPosition() + add offset manually if you need to do relative seek, OK enough?

**Comment by TheComet93** [comment]
That should be enough

**Comment by cadaver** [comment]
Ok. Will meditate a bit, could actually add SeekRelative() and Tell() which would just redirect to GetPosition().

**Comment by TheComet93** [comment]
SeekRelative() seems like the way to go. I had a glance at the code and Seek() is already fairly complex.

You speak of GetPosition(), but I don't see any method with this name in File. I thought you were talking about it in the future tense.

**Comment by cadaver** [comment]
Look at Deserializer.
