### ISSUE TITLE
IK fails to set/adhere to target position setting with Makehuman skeleton

### ISSUE THREAD

**Issue by slapin** [urho3d/Urho3D#2054]
With yet unknown circumstances (will debug and add) IK ignores targetPosition setting
using Makehuman skeleton. While it works with stock Urho provided skeletons this
might be by accident. Something is definitely lurking there, will look into this this weekend (unless @TheComet93 provides some solution faster). Now the behavior is like with target set to (0, 0, 0)

Normal scene (IK enabled but not solved):

https://youtu.be/4q72eSFKFiA

Full IK enabled for NPCs (not for player character)

https://www.youtube.com/watch?v=Ca4TuZpX7A4

**Comment by slapin** [comment]
Cc: @TheComet93

**Comment by TheComet93** [comment]
Hopefully we can get to the bottom of how to reproduce this. I would appreciate a minimal example demonstrating effector targets pointing to 0,0,0.
