### ISSUE TITLE
Strange behavior and crash in 39_CrowdNavigation.as sample

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#2056]
I was playing with crowd navigation sample. These jacks are somewhy unable to climb on the boxes by off-mesh. If I move the jack on the connection first, it climbs successfully. If I don't, it "stucks".

When I spawned a lot of jacks and asked them to climb, the jacks started to stuck and at some point I got a crash in the debug renderer:

```
Urho3DPlayer_d.exe!Urho3D::CrowdManager::DrawDebugGeometry(Urho3D::DebugRenderer * debug, bool depthTest) Line 153
Urho3DPlayer_d.exe!Urho3D::CrowdManager::DrawDebugGeometry(bool depthTest) Line 190
```

`ag->params.userData ` somewhy was zero.

**Update**: broken climbing is caused by #1695 fix in `CrowdAgent::OnMarkedDirty`

**Comment by cadaver** [comment]
The #1695 fix is somewhat arbitrary and I'm not happy with it. Revert it if you want.
