### ISSUE TITLE
No such file or directory for all my headers project

### ISSUE THREAD

**Issue by Belvarm** [urho3d/Urho3D#2057]
Hi all. 
My IDE Code Blocks, i use mingw w64.

When compiling my project, I get an error: No such file or directory. For all my headers.

structure project:
```
Root folder.
    Bin
        Autoload
        CoreData
        Data
    CMake
        Modules
        Toolchains
    WTGame.CPP
    version.h
```

My CMakelists

```
# Set project name
project (WTGame)
######################################
# Set CMake minimum version and CMake policy required by Urho3D-CMake-common module
if (WIN32)
    cmake_minimum_required (VERSION 3.2.3)      # Going forward all platforms will use this as minimum version
else ()
    cmake_minimum_required (VERSION 2.8.6)
endif ()
if (COMMAND cmake_policy)
    cmake_policy (SET CMP0003 NEW)
    if (CMAKE_VERSION VERSION_GREATER 2.8.12 OR CMAKE_VERSION VERSION_EQUAL 2.8.12)
        # INTERFACE_LINK_LIBRARIES defines the link interface
        cmake_policy (SET CMP0022 NEW)
    endif ()
    if (CMAKE_VERSION VERSION_GREATER 3.0.0 OR CMAKE_VERSION VERSION_EQUAL 3.0.0)
        # Disallow use of the LOCATION target property - so we set to OLD as we still need it
        cmake_policy (SET CMP0026 OLD)
        # MACOSX_RPATH is enabled by default
        cmake_policy (SET CMP0042 NEW)
	cmake_policy (SET CMP0063 OLD)
    endif ()
endif ()
# Set CMake modules search path
set (CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/CMake/Modules)
# Include Urho3D Cmake common module
include (UrhoCommon)
# Define source files
define_source_files (RECURSE)
# Define target name
set (TARGET_NAME WTGame)
# Setup target with resource copying
setup_main_executable ()
```
Here are the lines.

![errors](https://user-images.githubusercontent.com/13874433/28870752-1900c284-778a-11e7-83fc-b11f0116dd41.PNG)
![errors1](https://user-images.githubusercontent.com/13874433/28870794-42373598-778a-11e7-985a-1d8c2fd9f111.PNG)
![errors2](https://user-images.githubusercontent.com/13874433/28870751-18d9c9c2-778a-11e7-976f-c10bcbd8dbb0.PNG)
![errors3](https://user-images.githubusercontent.com/13874433/28870750-18d734e6-778a-11e7-8b21-950bde66a32b.PNG)

I'm already in despair..
Thank you so much!

**Comment by weitjong** [comment]
You should show the relavant implementation and header files as well where you include the `version.h` of yours. However, most probably all you need to do to fix it is, to add the directory where the `version.h` can be found into your build tree header search path. Something like before calling the `setup_main_executable()` macro.

```
set (INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR})
```

For such question you should have asked it in the support forum instead of raising an issue in our issue tracker.
