### ISSUE TITLE
IKSolver should ignore child IKSolver components

### ISSUE THREAD

**Issue by TheComet93** [urho3d/Urho3D#2058]
As discussed here: https://discourse.urho3d.io/t/inverse-kinematics-mass-instances/3405/23

It should be possible to have multiple solvers in a skeleton, where one solver can potentially be in a parent solver's subtree. In this case, the parent solver's tree should end at the node the child solver is attached to.

**Comment by cadaver** [comment]
What is your feeling, should the release wait for this and the 0,0,0 effector fix?

**Comment by TheComet93** [comment]
I feel this issue should be fairly trivial to fix, and should definitely be included if the 1.7 release can wait for it.

I've yet to reproduce the 0,0,0 effector bug a second time, but my gut tells me once I find out what's causing it, it's going to be something really stupid and easy to fix.

**Comment by cadaver** [comment]
No problem for me at least to wait a little more. It's good to have IK in a good condition.
