### ISSUE TITLE
OffMeshConnection-s don't work sometimes

### ISSUE THREAD

**Issue by eugeneko** [urho3d/Urho3D#2059]
Let it be here, but it may be Detour/Recast bug.

1. Open Sample 39
2. Change plane size and location:

```
    Vector3 mmin(-54.4f, 0, -54.4f);
    Vector3 mmax(51.2f, 0, 51.2f);
    planeNode->SetScale(mmax - mmin + Vector3::UP);
    planeNode->SetPosition((mmin + mmax) / 2);
```

3. Set tile size to 32

`navMesh->SetTileSize(32);`

4. Try to climb on the marked box

![39_crowdnavigation_d 2017-08-05 19-11-54-281](https://user-images.githubusercontent.com/8576192/28996942-8a9af312-7a12-11e7-9a99-70ebbcf3e8c7.jpg)

**Comment by JSandusky** [comment]
Does this only occur with DetourCrowd? As far as I know with Detour it shouldn't happen but I do know that it can happen with crowd agents when they're too far the link.

I haven't personally seen it fail for an agent that was near the link ... though I suppose it could during corridor finding.
