### ISSUE TITLE
Engine hangs when removing compound shape

### ISSUE THREAD

**Issue by pqftgs** [urho3d/Urho3D#2064]
To replicate:
1. Create a compound shape by adding two or more CollisionShape components to a node.
2. Wait for the next frame
3. Begin deleting shapes with node.RemoveComponent()
4. Engine will freeze when only 1 shape remains.

```
// First shape
shape_ = box_->CreateComponent<CollisionShape>();
shape_->SetBox(Vector3::ONE);

// Second shape
shape_ = box_->CreateComponent<CollisionShape>();
shape_->SetBox(Vector3::ONE);

// Trigger the freeze sometime later
box_->RemoveComponent(shape_);
```

Modified 11_Physics to show the problem
http://pasteall.org/504185

And I get this in debug mode
```
Assert colObjWrap->getCollisionShape()->isCompound() in line 244, file /home/user/repos/Urho3D/Source/ThirdParty/Bullet/src/BulletCollision/CollisionDispatch/btCompoundCollisionAlgorithm.cpp
Trace/breakpoint trap
```

EDIT
Workaround = remove the last 2 collision shapes at the same time and re-create the original.

**Comment by eugeneko** [comment]
Reproduced. It seems that `rigitBody.setCollisionShape makes some internal bullet cache dirty and rigid body shall probably be re-added to the physical world.
http://bulletphysics.org/Bullet/phpBB3/viewtopic.php?t=5194

**Comment by cadaver** [comment]
Possibly broken logic, or logic misusing Bullet, when returning to *not* using a compound for optimization. Can look into this too.

**Comment by eugeneko** [comment]
It's possible to either remove this optimization or do this in `RigidBody::UpdateMass`:
```
    // Rigid body shall be re-added to physics world if shape is changed
    btCollisionShape* newCollistionShape = useCompound ? shiftedCompoundShape_.Get() : shiftedCompoundShape_->getChildShape(0);
    if (newCollistionShape != body_->getCollisionShape())
    {
        btDiscreteDynamicsWorld* world = physicsWorld_->GetWorld();
        world->removeRigidBody(body_.Get());
        body_->setCollisionShape(newCollistionShape);
        world->addRigidBody(body_.Get(), (short)collisionLayer_, (short)collisionMask_);
    }
```
What's better?

**Comment by cadaver** [comment]
Should be fixed. Downside of fix can be that the readd happens to every body when they initially add their components, so there can be some lost performance.

**Comment by Lumak** [comment]
> Downside of fix can be that the readd happens to every body when they initially add their components, so there can be some lost performance.

This is disconcerting, but I'm seeing this as only happening during the initial load, right but then...  
This implementation seems like a special case to me. How often do people actually implement multiple collision shapes to add/remove at run-time.  If it is in fact a special use-case, couldn't we provide a pre-processor define for a such case as to not affect everyone else who don't need this feature to lose performance?

**Comment by Lumak** [comment]
Disregard. I looked at the code and I don't see any issue.

**Comment by cadaver** [comment]
The RigidBody <-> CollisionShape interaction is already non-optimal to begin with, there's "conversation" between them when they're being created, and we have to be prepared for any order.

**Comment by Lumak** [comment]
As I already said, not an issue. I have the diff and will maintain the previous version in my branch.
