### ISSUE TITLE
Current working directory as default resource prefix path instead of executable path

### ISSUE THREAD

**Issue by BlueMagnificent** [urho3d/Urho3D#2066]
In the `InitializeResourceCache` method of the engine class the default resource prefix path is set as the executable path through `FileSystem::GetProgramDir()` . A side effect of this is that running any Urho3D program through a path that doesn't contain "Data" and "CoreData" folder, even after setting the current working dir to a folder that contains them, throws up the path prefix warning prompt. 
This happens while trying to run an app directly through an IDE after building  (noticed in QtCreator and Codeblocks).

I know that you can resolve this by setting `ResourcePrefixPaths` value of the engine parameter to your current working directory. However, If there is no specific reason why `FileSystem::GetProgramDir()` is used as default value instead of `FileSystem::GetCurrentDir()` then I believe setting it as the later wouldn't be bad. At least to make some IDEs happy :grin:

**Comment by iSLC** [comment]
#2001

**Comment by BlueMagnificent** [comment]
Thanks. Actually felt something like this should have been noticed before now

**Comment by weitjong** [comment]
You can also set the prefix path via environment variable in the IDE setting.
