### ISSUE TITLE
15_Navigation broken

### ISSUE THREAD

**Issue by TheComet93** [urho3d/Urho3D#2069]
It seems the navmesh is not generated in the 15_Navigation example until you place an obstacle into the scene. When I start the example and immediately try to left-click somewhere to set the goal, nothing happens.

**Comment by eugeneko** [comment]
Cannot reproduce. What exactly sample did you tested? Then, how does debug geometry look like?

**Comment by TheComet93** [comment]
Strange, it just started working again for me after a recompile. Not sure what that was about.

**Comment by eugeneko** [comment]
Maybe you have accidentially pressed Tab and so switched to streaming mode? You should have checked debug geometry...

**Comment by TheComet93** [comment]
I did check debug geometry, it wasn't drawing (because there was no navmesh to draw).

Either way, this seems to be fixed and everything seems to be working. False alarm.

**Comment by eugeneko** [comment]
> I did check debug geometry, it wasn't drawing (because there was no navmesh to draw).

Thanks! Damn, I hate floating bugs so much... Let's hope there is nothing important here. I almost didn't changed old navmesh code when introduced navmesh streaming, but I refactored some parts of old code...
