### ISSUE TITLE
PBR on a model without tangents

### ISSUE THREAD

**Issue by t-artikov** [urho3d/Urho3D#2072]
See the attached scene. The model is rendered incorrectly, an error occurs: "Failed to create input layout for shader PBRLitSolid(IBL) due to missing vertex element(s) (HRESULT 80070057)".
I suppose the problem is that the PBR shader tries to use tangents, although in fact they are not required. Tangents and bitangents are passed to the 'ImageBasedLighting' function, but not used in it.

[pbr_tangents_bug.zip](https://github.com/urho3d/Urho3D/files/1227032/pbr_tangents_bug.zip)

**Comment by cadaver** [comment]
It's in a commented out part, so yes, it could be removed. Note however that the moment you use normal mapping you're actually going to need tangents.

**Comment by t-artikov** [comment]
Thanks.
A small addition. IBL define is used only in the pixel shader now. So, I belive, it can be removed from vsdefines in PBR*.xml techniques.

**Comment by cadaver** [comment]
That's true.

**Comment by dragonCASTjosh** [comment]
The commented out IBL system was an importance sampled approach that would require no external filtering of the Cubemap. It was left in by request during the PR. The reason it not used by default is because it is more costly to run compared to the current approach
