### ISSUE TITLE
SIGINT ignored on linux in headless mode

### ISSUE THREAD

**Issue by TheComet** [urho3d/Urho3D#2073]
When launching an application in headless mode, pressing CTRL-C does nothing. What I'd expect to happen is the E_EXITREQUESTED event to be sent.

I haven't looked into this in great detail, but it seems that the place to start investigating is in SDL. It appears that the SDL_QUIT event is not generated when pressing CTRL-C.

**Comment by slapin** [comment]
In not headless mode too, in terminal ^C works only if frame code running (Update/FixedUpdate, etc.),
but not in Start or DelayedStart

**Comment by nick70** [comment]
An older build of my code using Urho3D 1.6 doesn't have this issue.

**Comment by weitjong** [comment]
This issue is/was related to the discussion in the forum [here](https://discourse.urho3d.io/t/catching-sigint/3451/12). However. since @TheComet  has gone MIA for quite some time now and not responding to that forum post, I am closing this issue now. Feel free to reopen.
