### ISSUE TITLE
Incorrect normals on Cylinder.mdl?

### ISSUE THREAD

**Issue by iainmerrick** [urho3d/Urho3D#2075]
The shading on these cylinders doesn't look right:

![cylinders](https://user-images.githubusercontent.com/252111/29465504-2b479626-83ff-11e7-8117-79c2e4cb45a6.jpeg)

These are the built-in Cylinder.mdl, basic white material with a directional light. Per-vertex light so it's easier to see what's going on.

I would expect each facet of the cylinder to have flat shading along its length, as the top and bottom edges should have the same normals, but instead the facets have bright and dark ends.

**Comment by cadaver** [comment]
Possibly a smoothing group issue. These were last changed / re-exported, when vertex colors were added.

**Comment by Lumak** [comment]
I noticed that myself.  Try this:

[Cylinder.zip](https://github.com/urho3d/Urho3D/files/1234967/Cylinder.zip)

**Comment by iainmerrick** [comment]
Much better!

![cylinders2](https://user-images.githubusercontent.com/252111/29468345-73018152-8409-11e7-96a9-8235bee59abd.jpeg)

**Comment by Lumak** [comment]
It seems the normals on the bottom of the cylinder were manipulated and will always remain black, no matter how you orient the cylinder.

**Comment by cadaver** [comment]
@Lumak Did you do modifications to the Blender file? Could you share that, if you did?

**Comment by Lumak** [comment]
Unfortunately, I don't use Blender and don't have what you're asking. However, I'll attack the fbx file (if you can use that).

[Cylinder.zip](https://github.com/urho3d/Urho3D/files/1235275/Cylinder.zip)

**Comment by cadaver** [comment]
Ok, thanks anyway. I'll play around with Blender's auto-smoothing, something seemed fishy even in the Blennder viewport..
