### ISSUE TITLE
build failed on Mac OSX 10.11.6 with XCode 8.2.1

### ISSUE THREAD

**Issue by haolly** [urho3d/Urho3D#2076]
> Ld Build/bin/43_HttpRequestDemo normal x86_64
    cd /Users/liuhao/dev/Urho3D
    export MACOSX_DEPLOYMENT_TARGET=10.11
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -L/Users/liuhao/dev/Urho3D/Build/bin -F/Users/liuhao/dev/Urho3D/Build/bin -filelist /Users/liuhao/dev/Urho3D/Build/Source/Samples/43_HttpRequestDemo/Urho3D.build/Debug/43_HttpRequestDemo.build/Objects-normal/x86_64/43_HttpRequestDemo.LinkFileList -mmacosx-version-min=10.11 -Xlinker -object_path_lto -Xlinker /Users/liuhao/dev/Urho3D/Build/Source/Samples/43_HttpRequestDemo/Urho3D.build/Debug/43_HttpRequestDemo.build/Objects-normal/x86_64/43_HttpRequestDemo_lto.o -Xlinker -no_deduplicate -Wl,-no_weak_imports -Wl,-search_paths_first -Wl,-headerpad_max_install_names /Users/liuhao/dev/Urho3D/Build/lib/libUrho3D.a -liconv -framework AudioToolbox -framework Carbon -framework Cocoa -framework CoreFoundation -framework SystemConfiguration -framework CoreAudio -framework CoreServices -framework CoreVideo -framework ForceFeedback -framework IOKit -framework OpenGL -Xlinker -dependency_info -Xlinker /Users/liuhao/dev/Urho3D/Build/Source/Samples/43_HttpRequestDemo/Urho3D.build/Debug/43_HttpRequestDemo.build/Objects-normal/x86_64/43_HttpRequestDemo_dependency_info.dat -o /Users/liuhao/dev/Urho3D/Build/bin/43_HttpRequestDemo
**ld: weak import of symbol '_clock_gettime' not supported because of option: -no_weak_imports for architecture x86_64**
clang: error: linker command failed with exit code 1 (use -v to see invocation)

This happens when build sample 43 HttpRequestDemo and sample 47 Typography

**Comment by weitjong** [comment]
Try to nuke your build tree and recreate one from scratch targeting macOS 10.11 and see the issue goes away. Most probably you have modified the deployment target build option **after** the build tree has been created earlier.

**Comment by haolly** [comment]
@weitjong  Still exist, but in different sample scheme

**Comment by weitjong** [comment]
Did you use the `CMAKE_OSX_DEPLOYMENT_TARGET` build option?show us the steps you generate your build tree. This issue you have described should have been fixed a few months ago already.

**Comment by weitjong** [comment]
Not reproducible when the build tree is generated using the supported use case, i.e. `./cmake_xcode.sh CMAKE_OSX_DEPLOYMENT_TARGET=10.11` on a Mac Sierra host system with Xcode 8.x. Tested with both Debug and Release build configs.

I am closing this issue for now as I don't believe it is a bug.

p.s. our build system builds in parallel, so the link "error" may appear first in any target order, but that does not have any significant in this case.

**Comment by haolly** [comment]
`URHO3D_DEPLOYMENT_TARGET` is set to 10.11. I use cmake gui to generate the xcode project.
Anyway, I switched to use makefile and build success

**Comment by weitjong** [comment]
You are using wrong build option. The one you use is for Makefile-based build tree. For xcodebuild-based build tree you have to use the one I mentioned before.
