### ISSUE TITLE
adding freetype/base/md5.c to CMakeLists.txt fails to copy md5.h to DEST_INCLUDE_DIR

### ISSUE THREAD

**Issue by Lumak** [urho3d/Urho3D#2077]
This is more of a question for @weitjong. As described in the title, the md5.h file doesn't get copied to the DEST_INCLUDE_DIR.  The inserted line is shown below in the FreeType/CMakeLists.txt

```
. . .
    src/base/ftwinfnt.c
    src/base/md5.c
    src/bdf/bdf.c
. . .
```
My vs2015's Freetype project includes/compiles/links the md5.c, just don't understand why the md5.h is not copied.

**Comment by Lumak** [comment]
Duh, it's because the md5.h is not found in the: 
\Source\ThirdParty\FreeType\include\freetype
folder.

**Comment by weitjong** [comment]
It is not automatic. You have to tell the build system explicitly which header files you want to "install". See the last two lines of the CMakeLists.txt in the `Source/ThirdParty/FreeType` directory. Most probably you can achieve what you desire by inserting the path to `md5.h` to the last line (the macro expects a list in this context). BTW, you should not abuse our issue tracker to ask question, use the support forum instead.

**Comment by Lumak** [comment]
Ok, thanks. Yeah, I wasn't sure if I should've asked here or the forum, but I'll be sure to post on the forum for any questions that I may have in the future.
