### ISSUE TITLE
1.7 tag fails to pickup cmake build options from batch file

### ISSUE THREAD

**Issue by Lumak** [urho3d/Urho3D#2079]
Just tested tag 1.7 and using my cmake_vs2015_GL.bat, which has:
`@"%~dp0cmake_generic.bat" %* -VS=14 -DURHO3D_OPENGL=1
`
failed to create a build for opengl and created projects for D3D9 instead. My previous update was July 7, 2017, and the same batch file worked, so something from that point broke.

**Comment by weitjong** [comment]
I don't recall there is anything changes in build system in this regards. Perhaps you can help to bisect to see which commit is the culprit, if there is.

**Comment by Lumak** [comment]
Debugging with echo statements from the `:loop`  label
```
:loop
    echo :loop --- beg
if not "%~1%" == "" (
    if "%~1" == "-DANDROID" if "%~2" == "1" set "OPTS=-G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="%TOOLCHAINS%\Android.cmake""
    if "%~1" == "-DWEB" if "%~2" == "1" set "OPTS=-G "MinGW Makefiles" -DCMAKE_TOOLCHAIN_FILE="%TOOLCHAINS%\Emscripten.cmake""
    if "%~1" == "-DMINGW" if "%~2" == "1" set "OPTS=-G "MinGW Makefiles""
    if "%~1" == "-DURHO3D_64BIT" if "%~2" == "1" set "arch= Win64"
    if "%~1" == "-DURHO3D_64BIT" if "%~2" == "0" set "arch="
    if "%~1" == "-VS" set "OPTS=-G "Visual Studio %~2%arch%""
    if "%~1" == "-G" set "OPTS=%OPTS% %~1 %2"
    set "ARG1=%~1"
    set "ARG2=%~2"
    echo ARG1 =%ARG1%
    echo ARG2 =%ARG2%

    if "%ARG1:~0,2%" == "-D" set "BUILD_OPTS=%BUILD_OPTS% %ARG1%=%ARG2%"
    shift
    shift
    echo ~1 =%~1%
    echo ~2 =%~2%
    goto loop
)
echo :loop --- end

```

Using the **cmake_vs2015_GL.bat** file described previously, the output shows:

```
:loop --- beg
ARG1 =..\builds\bbTestGL
ARG2 =1
~1 =-VS
~2 =14
:loop --- beg
ARG1 =-VS
ARG2 =14
~1 =-DURHO3D_OPENGL
~2 =1
:loop --- beg
:loop --- end

```
Loop exits when `~1 =-DURHO3D_OPENGL` It looks like a bug to me and I don't know how to fix it.

**Comment by Lumak** [comment]
adding a garbage char at the end, e..g
`@"%~dp0cmake_generic.bat" %* -VS=14 -DURHO3D_OPENGL=1 x`
fixes it.

**Comment by weitjong** [comment]
The argument parsing in our generic batch file has been a little bit wonky since the beginning. As I recall it, I had to tweak the batch file in such a way that it works for all the provided derivative batch files at the time. It may be broken now in an unexpected ways after all the other unrelated changes. Unlike its shell scripts counterpart, I myself find it to be difficult to get it right. Contribution is welcome if you or anyone else know a bulletproof way to do argument passing in batch file.

**Comment by weitjong** [comment]
Let's keep this open until someone find a proper fix.

**Comment by Lumak** [comment]
I'm not sure if it's a parsing problem. As you saw in my echo dump, it does parse all arguments. What I don't understand is how` %~1%` is evaluated as being empty when it's equal to `-DURHO3D_OPENGL`.  My cmake_android_bld.bat file has more flags added and all flags are processed properly.

**Comment by weitjong** [comment]
You can easily isolate the problem by using cmake-gui. If it works then there is nothing to do with the build system.

**Comment by Lumak** [comment]
The problem is already isolated to Windows batch file command problem, in particular, the evaluation of NOT %~1%.

I just tested what's shown below and that works properly - comment out the `::if not "%~1%" == ""` and have` if "%~1%" == "" goto loopexit`

```
:loop
::if not "%~1%" == "" 
(
    if "%~1" == "-DANDROID" if "%~2" == "1" set "OPTS=-G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="%TOOLCHAINS%\Android.cmake""
    if "%~1" == "-DWEB" if "%~2" == "1" set "OPTS=-G "MinGW Makefiles" -DCMAKE_TOOLCHAIN_FILE="%TOOLCHAINS%\Emscripten.cmake""
    if "%~1" == "-DMINGW" if "%~2" == "1" set "OPTS=-G "MinGW Makefiles""
    if "%~1" == "-DURHO3D_64BIT" if "%~2" == "1" set "arch= Win64"
    if "%~1" == "-DURHO3D_64BIT" if "%~2" == "0" set "arch="
    if "%~1" == "-VS" set "OPTS=-G "Visual Studio %~2%arch%""
    if "%~1" == "-G" set "OPTS=%OPTS% %~1 %2"
    set "ARG1=%~1"
    set "ARG2=%~2"

    if "%ARG1:~0,2%" == "-D" set "BUILD_OPTS=%BUILD_OPTS% %ARG1%=%ARG2%"
    shift
    shift
    if "%~1%" == "" goto loopexit
    goto loop
)
:loopexit
```
