### ISSUE TITLE
cross compiling 1.7 for Android in Windows fails

### ISSUE THREAD

**Issue by Lumak** [urho3d/Urho3D#2080]
1) android_ndk and path are set correctly
2) at command prompt, type:

`d:\Urho3D-1.7-prototype>cmake_android.bat ..\builds\android_1.7 -DANDROID_TOOLCHAIN_NAME=x86-4.9
`

**It starts out OK - it's able to find the toolchain:**
```
-- Check for working C compiler: C:/Android/android-ndk-r15c/toolchains/x86-4.9/prebuilt/windows-x86_64/bin/i686-linux-android-gcc.exe
-- Check for working C compiler: C:/Android/android-ndk-r15c/toolchains/x86-4.9/prebuilt/windows-x86_64/bin/i686-linux-android-gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Android/android-ndk-r15c/toolchains/x86-4.9/prebuilt/windows-x86_64/bin/i686-linux-android-g++.exe
-- Check for working CXX compiler: C:/Android/android-ndk-r15c/toolchains/x86-4.9/prebuilt/windows-x86_64/bin/i686-linux-android-g++.exe -- works
```
**SDL2 config options:**
```
-- SDL2 was configured with the following options:
--
-- Platform: Android-1
-- 64-bit:   FALSE
-- Compiler: C:/Android/android-ndk-r15c/toolchains/x86-4.9/prebuilt/windows-x86_64/bin/i686-linux-android-gcc.exe

```

**then it errors out with:**
```
-- Performing Test HAVE_NATIVE_COMPILER
-- Performing Test HAVE_NATIVE_COMPILER - Failed
CMake Error at CMake/Modules/CheckCompilerToolchain.cmake:134 (message):
  Could not find native compiler toolchain.  This is usually caused by wrong
  PATH env-var value.

  CMake Error in CMakeLists.txt:

    No CMAKE_C_COMPILER could be found.

    Tell CMake where to find the compiler by setting either the environment
    variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
    to the compiler, or to the compiler name if it is in the PATH.

Call Stack (most recent call first):
  Source/Urho3D/CMakeLists.txt:198 (check_native_compiler_exist)

```
**I have also tried this with the x86_64-4.9 toolchain in a clean build tree, and that also fails with the same error.**

Edit: added the last bit of error info.

**Comment by weitjong** [comment]
This is a common pitfall when cross-compiling on Windows host system. You actually need two compiler toolchains installed correctly so that CMake can find them. One for building the target and one for building the native build tool(s) on the fly. In the past we let you passed the CMake configuration/generation stage then you would later fail during tool building stage. Now if we detect something is amiss, we error out ahead of time and giving a fatal error as early as possible. 

In short, you need MinGW too.

**Comment by Lumak** [comment]
Thanks for the tip. Figured out how to build the target w/o MinGW.

**Comment by weitjong** [comment]
Glad to hear that. Yeah, any compiler that could produce native/host tool will do.

**Comment by Lumak** [comment]
Er, key words **"build the target"**, meaning omit building tools. I do this because I import the target build directly to Android Studio to further build/debug/package and prep for release.

**Comment by weitjong** [comment]
I suppose you are not using Lua or asset packaging build option, so there is no host tool building and the native compiler check appears to be a redundant to your case can could be safely bypass. May be that's exactly what we should do, only check when there is any host tool to be built.

**Comment by Lumak** [comment]
Making a build to import into Android Studio might be a special case, but it doesn't require any modification to the existing build files.  Just need these flags:

`@"%~dp0cmake_generic.bat" %* -DANDROID=1 -DANDROID_TOOLCHAIN_NAME=x86-4.9  -DURHO3D_LUA=0 -DURHO3D_PACKAGING=0 -DURHO3D_TOOLS=0
`
