### ISSUE TITLE
[iOS] Call to unavailable function system: Not available on iOS

### ISSUE THREAD

**Issue by csotiriou** [urho3d/Urho3D#2083]
Seems that Lua and Urho File Utils (like in FileSystem.cpp) are making calls to the `system()` function, which is deprecated long ago, and is now stripped from iOS.

https://stackoverflow.com/questions/45420717/call-to-unavailable-function-system-not-available-on-ios

This happens with Xcode 9 beta, which will be finalised in a month or so. That will render Urho uncompilable on Xcode 9, which will then render it unable build against iOS 11.

**Comment by cadaver** [comment]
Seems there's the check already in place for AppleTV port, needs just expanding to iOS as well. System call on these systems does not make sense in any case.
