### ISSUE TITLE
Runaway shadow

### ISSUE THREAD

**Issue by QBkGames** [urho3d/Urho3D#2090]
After just upgrading to version 1.7, from 1.6.1024 (I think) and also changing the renderer from DX9 to DX11, I've got some strange shadow behaviour, where the shadow disappears when the camera is moved at certain angles. I'm not sure if is't a an upgrade issue or DirectX issue as I've changed both at the same time.
![shadow_visible](https://user-images.githubusercontent.com/30278394/29565250-8429d31c-8788-11e7-80ae-f50445889244.png)
![shadow_missing](https://user-images.githubusercontent.com/30278394/29565252-88666530-8788-11e7-876e-b6b8cb219a65.png)

I just have a single directional light.
Any ideas? A bug or some lighting configuration needs to be changed in the new version?

**Comment by eugeneko** [comment]
Please provide STR, it doesn't seem to be hard. Is the problem reproducible with standard assets? Could you share minimal scene with the problem?

**Comment by QBkGames** [comment]
I'm in the middle of a task that I'd like to stay focused on for now, so I'll have to come back to trying to reproduce the problem in one of the Samples, using standard assets.

However, I did try to change back to using DirectX 9 and the problem has gone, so it seems to be some problem with the DirectX 11 implementation.

**Comment by QBkGames** [comment]
Not sure if it helps, but here's the code I use to create the scene, the lighting and shadowing. My terrain is 2049x2049 scaled by 3 so it's fairly large (aiming for an open world game).

void GameApp::CreateScene()
{
    const float TERRAIN_SCALE = 3.0f;
    BoundingBox sceneSize(-1000.0f * TERRAIN_SCALE, 1000.0f * TERRAIN_SCALE);

    ResourceCache* pResCache = GetSubsystem<ResourceCache>();

    // Create the scene and its components
	_scene = new Scene(context_);

	Octree* pOctree = _scene->CreateComponent<Octree>();
	pOctree->SetSize(sceneSize, pOctree->GetNumLevels());

	_scene->CreateComponent<PhysicsWorld>();
	_scene->CreateComponent<DebugRenderer>();

    // Create a Zone component for ambient lighting & fog control
    Node* zoneNode = _scene->CreateChild("Zone");
    
	Zone* zone = zoneNode->CreateComponent<Zone>();
	zone->SetBoundingBox(sceneSize);
    zone->SetAmbientColor(Color(0.5f, 0.65f, 0.45f));
    zone->SetFogColor(Color(0.8f, 0.8f, 1.0f));
    zone->SetFogStart(500.0f);
    zone->SetFogEnd(768.0f);

    // Create a directional light to the world. Enable cascaded shadows on it
    Node* lightNode = _scene->CreateChild("SunLight");
    lightNode->SetDirection(Vector3(0.6f, -1.0f, 0.8f));

	Light* light = lightNode->CreateComponent<Light>();
    light->SetLightType(LIGHT_DIRECTIONAL);
    light->SetCastShadows(true);
    light->SetShadowBias(BiasParameters(0.00005f, 0.5f, 0.001f));
    light->SetShadowCascade(CascadeParameters(96.0f, 256.0f, 640.0f, 0.0f, 0.8f));
	light->SetShadowResolution(1.0f);
    light->SetSpecularIntensity(0.7f);
    // Apply slightly overbright lighting to match the skybox
    light->SetColor(Color(0.9f, 1.05f, 1.05f));

    // Create skybox. The Skybox component is used like StaticModel, but it will be always located at the camera, giving the
    // illusion of the box planes being far away. Use just the ordinary Box model and a suitable material, whose shader will
    // generate the necessary 3D texture coordinates for cube mapping
    Node* skyNode = _scene->CreateChild("Sky");
    skyNode->SetScale(1000.0f); // The scale actually does not matter

    Skybox* skybox = skyNode->CreateComponent<Skybox>();
    skybox->SetModel(pResCache->GetResource<Model>("Models/Basic/Box.mdl"));
    skybox->SetMaterial(pResCache->GetResource<Material>("Materials/Skybox.xml"));

    // Create heightmap terrain
    Node* terrainNode = _scene->CreateChild("Terrain");

    Terrain* terrain = terrainNode->CreateComponent<Terrain>();
    terrain->SetPatchSize(64);
	terrain->SetSpacing(Vector3(TERRAIN_SCALE, 0.8f, TERRAIN_SCALE)); // Spacing between vertices and vertical resolution of the height map
    terrain->SetSmoothing(true);
    terrain->SetHeightMap(pResCache->GetResource<Image>("Textures/HeightMap.png"));
    terrain->SetMaterial(pResCache->GetResource<Material>("Materials/Terrain.xml"));

    // The terrain consists of large triangles, which fits well for occlusion rendering, as a hill can occlude all
    // terrain patches and other objects behind it
    terrain->SetOccluder(true);
	terrain->SetCastShadows(true);

	RigidBody* pRigidBody = terrainNode->CreateComponent<RigidBody>();
	pRigidBody->SetCollisionLayer(ENVIRONMENT_COLLISION_LAYER);
	pRigidBody->SetFriction(0.75f);
	pRigidBody->SetRollingFriction(0.5f);
	CollisionShape* pShape = terrainNode->CreateComponent<CollisionShape>();
	pShape->SetTerrain();
	pShape->SetMargin(0.005f);

	// Populate the level with all required entities.
	WorldBuilder levelBuilder(_scene, pResCache, terrain, sceneSize.Size());
	levelBuilder.Populate();

    // Create the player node, with a camera node attached.
	Node* pPlayerNode = _scene->CreateChild(CCToString("Player"));
	_pPlayer = pPlayerNode->CreateComponent<Player>();
	// TODO: Handle player initialisation errors
	_pPlayer->Initialise();

	Node* pCameraNode = pPlayerNode->CreateChild(CCToString("Camera"));
	Camera* pCamera = pCameraNode->CreateComponent<Camera>(Urho3D::LOCAL);
	pCamera->SetFarClip(768.0f);

	pCameraNode->SetPosition(Vector3(0.0f, CHARACTER_HEIGHT, 0.0f));

	// Set up a viewport to the Renderer subsystem so that the 3D scene can be seen
	Renderer* _pRenderer = GetSubsystem<Renderer>();

	SharedPtr<Viewport> viewport(new Viewport(context_, _scene, pCamera));
	_pRenderer->SetViewport(0, viewport);

	_pRenderer->SetShadowQuality(ShadowQuality::SHADOWQUALITY_SIMPLE_24BIT);
	_pRenderer->SetShadowMapSize(4096);
}

**Comment by cadaver** [comment]
Not able to reproduce in the VehicleDemo by using your farclip, shadow bias and shadow cascade settings. The shadow map resolution 4096 looks potentially too high, as for a 2x2 cascade map it would actually create a 8K x 8K texture. I recommend trying to get more highres shadows just by tweaking the cascade settings and focusing.
