### ISSUE TITLE
Not getting user preference option in file menu

### ISSUE THREAD

**Issue by Abhijeet-Xamarin** [urho3d/Urho3D#2109]
Not getting user preference option in file menu. 

Please correct me on this ? 
<img width="514" alt="screen shot 2017-08-30 at 3 39 45 pm" src="https://user-images.githubusercontent.com/12145362/29867543-88cdd92e-8d99-11e7-9233-8d3b39f38895.png">

**Comment by 1vanK** [comment]
view > editor settinngs
view > editor preferences

**Comment by carnalis** [comment]
I think this issue can be closed now.
