### ISSUE TITLE
There is currently no explicit conversion from IntVector3 to Vector3

### ISSUE THREAD

**Issue by TrevorCash** [urho3d/Urho3D#2110]
Some constructor that would cast the float componts of the Vector3 to integers for the IntVector3 would be nice.

**Comment by OvermindDL1** [comment]
It is a lossy conversion though, should definitely not be implicit, but an explicit conversion is fine.

**Comment by SirNate0** [comment]
The title of the issue and your description are opposites -- did you mean No Explicit Conversion from Vector3 to IntVector3? (Also, I think it would probably be useful, but I agree, it should definitely be explicit)

**Comment by OvermindDL1** [comment]
I think the title is titled as "There are currently no explicit conversion from IntVector3 to Vector3" is how I read it.  ^.^;

**Comment by Modanung** [comment]
A `Vector3` can already be constructed from an `IntVector3`. The other way around there is not one logical way, that's what these functions are for:
```
/// Per-component floor of 3-vector. Returns IntVector3.
inline IntVector3 VectorFloorToInt(const Vector3& vec) { return IntVector3(FloorToInt(vec.x_), FloorToInt(vec.y_), FloorToInt(vec.z_)); }

/// Per-component round of 3-vector. Returns IntVector3.
inline IntVector3 VectorRoundToInt(const Vector3& vec) { return IntVector3(RoundToInt(vec.x_), RoundToInt(vec.y_), RoundToInt(vec.z_)); }

/// Per-component ceil of 3-vector. Returns IntVector3.
inline IntVector3 VectorCeilToInt(const Vector3& vec) { return IntVector3(CeilToInt(vec.x_), CeilToInt(vec.y_), CeilToInt(vec.z_)); }
```

**Comment by TrevorCash** [comment]
Ah I see - I did not see those explicit conversions. That's great!
Closing.
