### ISSUE TITLE
DebugRenderer is jittering for fast moved objects

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#2119]
For test add debugRenderer to 18_CharacterDemo.as:
```
scene_.CreateComponent("DebugRenderer");
...
SubscribeToEvent("PostRenderUpdate", "HandlePostRenderUpdate");
...
void HandlePostRenderUpdate(StringHash eventType, VariantMap& eventData)
{
    scene_.physicsWorld.DrawDebugGeometry(true);
}
```
and increase speed
```
const float MOVE_FORCE = 10.8f;
```

**Comment by Lumak** [comment]
Not an issue. This is expected behavior for ALL physics objects when using debugrenderer.

**Comment by 1vanK** [comment]
Why?

**Comment by Lumak** [comment]
Or are you saying it ONLY happens on 18_CharacterDemo.as?

**Comment by 1vanK** [comment]
No, it problems actual for all fast moved rigid bodies. I'm wondering why this is not a issue

**Comment by Lumak** [comment]
Nodes are processed via SmoothedTransform to remove jitter from rigidbodies, but the rigidbodies themselves are not smoothed.

**Comment by 1vanK** [comment]
I think smoothedTransform component shoul be add manually if need (so it is not used by default)

![1](https://user-images.githubusercontent.com/13021826/30216323-4bd3b9b6-94bb-11e7-952f-3fa629583089.png)

**Comment by 1vanK** [comment]
Do u test issue yourself?

**Comment by eugeneko** [comment]
Both physics debug geometry and node transforms are supplied by the Bullet itself.
I suppose that Bullet just draw things without interpolation.

**Comment by 1vanK** [comment]
Uff, it seems that we are engaged in exorcism.

**Comment by 1vanK** [comment]
I disable interpolations for bullet

```
        PhysicsWorld* w = scene_->CreateComponent<PhysicsWorld>();
        w->GetWorld()->setLatencyMotionStateInterpolation(false);
```

but did not see a noticeable impact on the objects, but the jittering of the debugging geometry is just awful

**Comment by 1vanK** [comment]
When I move a kinematic body http://dropmefiles.com/cOrPk

**Comment by eugeneko** [comment]
@1vanK I tested this. If you set `physicsWorld.interpolation = false`, there is no jittering. So, I was right.

**Comment by 1vanK** [comment]
I do not see any difference: http://dropmefiles.com/xPOA0

Even if you just argue, If interpolation smoothes such a large jittering, after disabling interpolation, node would start to jitter too. Have you seen this?

**Comment by 1vanK** [comment]
AH I see my mistake in last video, I make second PhysicsWorld component and disable interpolation for it. So yes physicsWorld.interpolation = false disable jittering.

**Comment by eugeneko** [comment]
> node would start to jitter too

Yep, it starts. Physics debug rendering is "fair". It draws physical bodies where they are really located. Interpolation is just visual effect and isn't considered here. But sometimes it looks dirty, I agree.

Anyway, we couldn't just use interpolated position without rewriting either Bullet or PhysicsWorld. So let it be closed now...

**Comment by 1vanK** [comment]
Still problems with kinematic bodies even with world->SetInterpolation(false);

It can be may be related with https://github.com/urho3d/Urho3D/issues/2132
