### ISSUE TITLE
Add Basic Text Rendering To DebugRenderer.

### ISSUE THREAD

**Issue by TrevorCash** [urho3d/Urho3D#2121]
It would be nice to have the ability to render basic text labels in the DebugRenderer.

Something along the lines of AddLabel(String labelText, Color color, depthTest).  Similar to AddLine or AddCircle.

**Comment by eugeneko** [comment]
I also wanted this feature. However, it's easier to say than to implement.

**Comment by cadaver** [comment]
Yes, in a sense Graphics / Renderer (+ DebugRenderer) are the low-level subsystems, which don't know about text / fonts / UI elements at all, and UI subsystem is a client of Graphics. So it could be done, but not necessarily in a clean manner.

**Comment by TrevorCash** [comment]
I have a feature branch that adds a new subsystem called VisualDebugger that provides what I was looking for: https://github.com/urho3d/Urho3D/compare/master...TrevorCash:feature/VisualDebugger

see https://discourse.urho3d.io/t/visualdebugger-subsystem/3814 for info.
