### ISSUE TITLE
While holding leftMouseButton, windows get removed if rightMouseButton or Esc are pressed

### ISSUE THREAD

**Issue by ext-1** [urho3d/Urho3D#2129]
Hello,

While holding `left mouse button` over a `UI Window object` and then pressing `right mouse button` or `esc` removes the `UI Window object`.

I've made a small test demo: [https://gist.github.com/ext-1/9a15b0e9eabd8f090634c085285ece70](https://gist.github.com/ext-1/9a15b0e9eabd8f090634c085285ece70)

Also replicated on Urho3D's 02_HelloGUI sample: [https://gist.github.com/ext-1/505ce67b213a32db7761d8b15978c879#file-hellogui-cpp-L59](https://gist.github.com/ext-1/505ce67b213a32db7761d8b15978c879#file-hellogui-cpp-L59)

I guess it may be related to `SetAlignment()`. All windows with `SetAlignment()`, except the one with `SetAlignment(HA_LEFT,VA_TOP)`, seen to be affected.

Setting the windows to `SetModal(false)` didn't appear to have any effect on this issue.

Best regards.

**Comment by carnalis** [comment]
I can replicate, if I: left click, move the mouse, right click. Maybe it happens specifically after a drag operation begins? Using a debugger with some breakpoints (like in UI.cpp) should help track it down.

**Comment by carnalis** [comment]
How about a change to Window::OnDragCancel()
https://github.com/urho3d/Urho3D/blob/master/Source/Urho3D/UI/Window.cpp#L246
to
``` if (dragButtons == MOUSEB_LEFT && CheckAlignment())```

It uses the same test as OnDragBegin() at https://github.com/urho3d/Urho3D/blob/master/Source/Urho3D/UI/Window.cpp#L135

It is by no means well tested.. ;)

**Comment by carnalis** [comment]
Maybe this is more correct:
```
    if (dragButtons == MOUSEB_LEFT)
    {
        dragMode_ = DRAG_NONE;
        if (CheckAlignment())
          return;
        SetPosition(dragBeginPosition_);
        SetSize(dragBeginSize_);
    }
```

**Comment by weitjong** [comment]
Or perhaps this (untested yet)

`
if (dragButtons == MOUSEB_LEFT && dragMode != DRAG_NONE)
`
