### ISSUE TITLE
Kinematic body does not moved by body::SetPosition()

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#2132]
```
void CharacterController::CreatePhysComponents(float height, float diameter)
{
    RigidBody* body = node_->CreateComponent<RigidBody>();
    body->SetKinematic(true);
   // body->SetMass(1.0f);
    body->SetAngularFactor(Vector3(0.0f, 1.0f, 0.0f));

    CollisionShape* shape = node_->CreateComponent<CollisionShape>();
    shape->SetCapsule(diameter, height, Vector3(0.0f, height * 0.5f, 0.0f));
}
```

```
void CharacterController::FixedUpdate(float timeStep)
{
#if 1
    // Not works
    RigidBody* body = node_->GetComponent<RigidBody>();
    body->SetPosition(body->GetPosition() + Vector3::LEFT * 100 * timeStep);
#else
    // Works
    node_->Translate(Vector3::LEFT * 100 * timeStep, TS_WORLD);
#endif
}
```

**Comment by 1vanK** [comment]
Video: http://dropmefiles.com/Z7K7Z

As you can see debug geometry for kinematic body is moved but node still stay on place

**Comment by weitjong** [comment]
Cannot view your video on iPhone. Could you host it somewhere else?

**Comment by 1vanK** [comment]
https://youtu.be/9YyRJc5Tjl4

**Comment by cadaver** [comment]
That may be Bullet's intended behavior for kinematic rigidbodies. If it doesn't fire setWorldTransform callback, the node's position doesn't get updated.

**Comment by eugeneko** [comment]
Even if it is Bullet intended behavior, Urho don't have to inherit it.
E.g. SetPosition/etc could re-direct logic to SetWorldPosition/etc in case of kinematic body.

**Comment by 1vanK** [comment]
body->SetPosition() activate body, but it is not dynamic

**Comment by 1vanK** [comment]
> kinematic rigidbody it's OK to move the node.

yes, I do it, but the reason why I'm starting to look for some problem somewhere, movements begin to be more discrete with time (the body start move jerks, but not immediately, but after some time)

**Comment by eugeneko** [comment]
@1vanK It is incorrect to update kinematic body in FixedUpdate because it has no interpolation.

**Comment by 1vanK** [comment]
fixed update used not because of interpolation, but because physically has a own fps. For example I wont independently simalate gravity and interaction with other bodies, I have to do this in fixedUpdate

**Comment by eugeneko** [comment]
Doesn't matter. If you update kinematic body in the FixedUpdate, it _will_ shake unless you manually add some interpolation stuff.

**Comment by 1vanK** [comment]
The reason for my problem is not interpolation, because I turned off interpolation

**Comment by eugeneko** [comment]
> I turned off interpolation
> the body start move jerks

So what do you expect?
Disabled interpolation is the synonym of jerking objects.

**Comment by 1vanK** [comment]
> Disabled interpolation is the synonym of jerking objects.

https://github.com/urho3d/Urho3D/issues/2132#issuecomment-331852493
The discrete movement does not begin immediately

Also https://github.com/urho3d/Urho3D/issues/2119#issuecomment-331751117
with disabled interpolation debug geometry always match dynamic bodies, bot not match kinematic bodies

**Comment by eugeneko** [comment]
> The discrete movement does not begin immediately

I probably don't understand what do you mean here. Could you elaborate? I thought you are talking about shaking and jerking artifacts of moving object.

> with disabled interpolation debug geometry always match dynamic bodies, bot not match kinematic bodies

Yeah, that's issue. I have no idea what's wrong here.

**Comment by 1vanK** [comment]
> Could you elaborate? I thought you are talking about shaking and jerking artifacts of moving object.

I mean, that with time the jerks of movement become more noticeable

**Comment by eugeneko** [comment]
> the jerks of movement become more noticeable

I don't know why does it change as time passes, but it could be plain random or environment-related behavior.
You cannot avoid jerking unless you use interpolation, so I think that it's good place to start.

**Comment by 1vanK** [comment]
I try to record video but only 60 fps is allowed, and the difference is not so noticeable as when using app yourself:
* first part of video - noticeable jerks
* the second part of the video - I restart the application and it works without jerks (but affects the restriction of video recording)

> logically correct code
```
void CharacterController::FixedUpdate(float timeStep)
{
    // No difference rotate node in Update or in FixedUpdate
    //node_->SetRotation(Quaternion(0.0f, global->yaw_, 0.0f));

    const float MOVE_SPEED = 10.0f;

    Vector3 dir;

    if (controls_.IsDown(CTRL_FORWARD))
        dir += Vector3::FORWARD;
    if (controls_.IsDown(CTRL_BACK))
        dir += Vector3::BACK;
    if (controls_.IsDown(CTRL_LEFT))
        dir += Vector3::LEFT;
    if (controls_.IsDown(CTRL_RIGHT))
        dir += Vector3::RIGHT;

    if (dir.LengthSquared() > 0.0f)
    {
        dir.Normalize();
        dir = node_->GetWorldRotation() * dir;
        dir.y_ = 0.0f;

        speed_.x_ = dir.x_;
        speed_.z_ = dir.z_;
    }
    else
    {
        speed_.x_ = 0.0f;
        speed_.z_ = 0.0f;
    }

    speed_ *= 100.0f;

#if 0
    RigidBody* body = node_->GetComponent<RigidBody>();
    body->SetPosition(speed_ * timeStep);
#else
    node_->Translate(speed_ * timeStep, TS_WORLD);
#endif
}
```

it is all code

**Comment by eugeneko** [comment]
> I try to record video but only 60 fps is allowed

I'll watch it later, don't have player now.

> it is all code

I already explained why this code _will_ have jerks regardless of physics settings. It is literally desigend to make movement jerky.

**Comment by 1vanK** [comment]
> I already explained why this code will have jerks regardless of physics settings.

should be permanent

**Comment by eugeneko** [comment]
> should be permanent

That's true, so I'll watch video later.
However, it doesn't mean that this code is well-formed. IMO, debugging malformed code is waste of time.

**Comment by Lumak** [comment]
> Even if it is Bullet intended behavior, Urho don't have to inherit it.
E.g. SetPosition/etc could re-direct logic to SetWorldPosition/etc in case of kinematic body.

Would this break how kinematic flag is currently used to allow nodes to automatically update and position kinematic rigid bodies that are attached to nodes?
