### ISSUE TITLE
Lua garbage collector

### ISSUE THREAD

**Issue by alex-rass-88** [urho3d/Urho3D#2135]
Why in lua_gc used LUA_GCCOLLECT?
I replace it to LUA_GCSTEP, and has increase perfomance of Lua scripts to +25%.
Memory leaks are not noticed.

**Comment by weitjong** [comment]
There are places where LUA_GCCOLLECT is being used. Which one did you replace and what parameter value did you use? Would be good if you can provide some comparison benchmark between the two. As for the reason, see this commit https://github.com/urho3d/Urho3D/commit/fa6d92d39a22bf8a0deda81371f8d87d6e826cc5

The whole LuaScript subsystem was mainly contributed work from Aster, so @aster2013 may be the best person to answer this.

**Comment by alex-rass-88** [comment]
https://github.com/urho3d/Urho3D/blob/b53cda9d6fdf6d0ca297ff55e3abaaa1f1a53b5d/Source/Urho3D/LuaScript/LuaScript.cpp#L479

I tested on 20_HugeObjectCount.lua (not press G)
clean master 32 fps
modified gc flag 44 fps

20_HugeObjectCount.lua (press G and start rotation of cubes)
clean master 36 fps
modified gc flag 50 fps

**Comment by weitjong** [comment]
This is exactly the line being changed in the commit I mentioned above and I would like to think it was changed for a very good reason. Could you elaborate more on how did you change, specifically the parameter value to the LUA_GCSTEP. A PR is welcome so other Lua users can easily verify if it is better of. Thanks.

**Comment by alex-rass-88** [comment]
lua_gc(luaState_, LUA_GCCOLLECT, 0);
change to
lua_gc(luaState_, LUA_GCSTEP, 0);

**Comment by weitjong** [comment]
I see. So just a single replacement with the default parameter, I thought you have performed fine tuning.

**Comment by alex-rass-88** [comment]
Yes. Just one line. Make PR?

**Comment by Florastamine** [comment]
I can confirm this behaviour. 

This is the original `master` branch - 
![0](https://user-images.githubusercontent.com/4599467/31001791-8cd0fd74-a510-11e7-832d-fa1561b1c4e0.jpg)

The same, but with `LUA_GCSTEP` instead of `LUA_GCCOLLECT` - 
![1](https://user-images.githubusercontent.com/4599467/31001823-c05c35be-a510-11e7-9450-bca92b9df179.jpg)

**Comment by Florastamine** [comment]
Actually, we also has a similar case (#1870), but it's AngelScript, where turning off `AS_NO_THREADS` can potentially boosts peformance, but needs some testing.

**Comment by 1vanK** [comment]
> 20_HugeObjectCount.lua

all objects are created on start, how does garbage collector every frame?

**Comment by eugeneko** [comment]
@1vanK Memory may be allocated regardless of objects lifetime. GC may spend 10 msec for nothing without any garbage collected.

**Comment by 1vanK** [comment]
anyway need test on more real applications

**Comment by weitjong** [comment]
Tested with LuaJIT build option on Linux platform. It showed the same promising result as showed by @Florastamine. I have also temporarily modify the engine code to output the current amount of memory (in Kbytes) in use by Lua VM. With the incremental GC, there was fluctuation in the Lua in-use-memory each frame (I was using 20_HugeObjectCount.lua too), however, the good news is in my short test it showed the memory usage would peak (it might drop slightly from this peak before it was on rising trend again and the whole cycle repeated), i.e. it looks like the incremental GC may eventually catch up and reach an equilibrium. Comparing that with the full GC, the Lua in-use-memory remained constant each frame at the cost of the performance.

It is a fair trade-off and I think we can merge the PR as is. For games that use more memory then the incremental GC could collect each frame, they can easily revert back the GC strategy or fine tune the step size and/or step multiplier individually.
