### ISSUE TITLE
In samples, keys [1..9] don't works

### ISSUE THREAD

**Issue by fredakilla** [urho3d/Urho3D#2137]
In samples, Keys 1 to 9, for common rendering quality controls, don't works anymore since....
(I have an AZERTY keyboard)

for example in sample.inl :
// Texture quality 
else if (key == '1')

when I press key 1 on my keyboard it's in fact the SDLK_AMPERSAND that is trigerred (don't works using shift key too)

**Comment by weitjong** [comment]
We are relying on SDL2 library for our input handling and I don't think SDL2 as any support for AZERTY. A quick search on "AZERTY" keyword in the SDL2 code base returned zero result. However, it is a common problem for other AZERTY users so the problem should be already solved by others. See https://fossies.org/linux/SDL2/src/events/SDL_keyboard.c on line 605-612. Don't have AZERTY keyboard to test, so I am not sure if it works or not.

**Comment by weitjong** [comment]
Feel free to reopen.
