### ISSUE TITLE
TextureView

### ISSUE THREAD

**Issue by TooLazyy** [urho3d/Urho3D#2138]
Hi, in your SDLActivity you use your own implementation of a SurfaceView.
I have tried to use TextureView, but failed. Is it possible?
And is it possible to use Urho3d within a fragment but not activity?

**Comment by weitjong** [comment]
The `SDLactivity` is only lightly modified by us. It is originated from SDL2 library which handles, among others, our windowing and input interfacing for each target platform. In case of Android, we have this platform-specific `SDLActivity` class provided. In other words, it's design is not our decision.

I know I am not answering your question. But exactly for question like this, I think you have a better luck to ask it in the SDL and/or our Urho forums as there are more readers there than our issue tracker.
