### ISSUE TITLE
AssetImporter support morphs

### ISSUE THREAD

**Issue by c4augustus** [urho3d/Urho3D#2142]
AssetImporter is currently ignoring any morphs coming through the third-party assimp library. The latest version of assimp seems to support morphs in COLLADA. I'm probably going to implement this enhancement soon, and then will submit a PR for it. assimp will probably need to be upgraded as well.

**Comment by weitjong** [comment]
Thanks for the head up. Please separate the PR for `AssetImporter` enhancement from the `assimp` upgrade later. We may take this chance to turn the directory holding `assimp` into a git subtree. Let us know which release/tag you plan to use.

**Comment by c4augustus** [comment]
Yes, of course.

**Comment by c4augustus** [comment]
I do need to upgrade assimp to it's latest release 4.0.1. Would you like me to just copy that version of the files into Source/ThirdParty/Assimp, or change it to be git submodule instead of copied files? This would be the first git submodule in Urho3D. And if so, do you still want it in the same place: Source/ThirdParty/Assimp? I usually keep my git submodules separate from my project source (i.e. "code/src" for project source and "dep/<git project name>" for dependencies). But this is your project, not mine :-D

**Comment by c4augustus** [comment]
So there are quite a few custom changes made by Urho3D to its copy of assimp release v3.2 source files, mostly Urho3D's own CMakeLists.txt file and C++ conditional compilation for VS2008 compatibility. I see that urho3d doesn't have it's own fork of assimp. I'm therefore making my own fork of assimp so that I can create a branch in it to hold these Urho3D customizations. Then I'm pointing my fork of Urho3D at my new assimp fork. I'm doing this at assimp release v3.2 to make sure the change over to git submodule is compatible and builds successfully (at least on macOS). I'll submit this change a separate PR. Then I will upgrade assimp to its release v4.0.1 and submit this as a second PR. Finally, I will enhance AssetImporter to support morphs and submit this as a third PR.

**Comment by weitjong** [comment]
Thanks for taking this work. Note that we have decided one or two years ago that we will slowly convert all the 3rd-party subdirectories into git subtrees. We feel `git subtree` is less instrusive than `git submodule` as the former is "transparent" to the users. But I do admit we are really too slow in this regards. In any case, we will have a fork of `assimp` repo in our Github org at the end of the day this time.

You can see how we manage the subtrees in the already converted 3rd-party libs, such as AngelScript or SDL. Typically we have master branch tracking the original upstream' master branch and have a separate branch with our custom fixes on top a "base" that we last synced. In other words, we just need to "rebase" in order to sync the upstream changes.

**Comment by c4augustus** [comment]
Ah, okay. I'll follow your approach with git subtree and use your urho3d/assimp fork when it's available. Please bear in mind that for now I'm only doing enough of the import morphs enhancement that I need for work that I'm doing for my client. I selected Urho3D as the embedded 3D engine to use within their Android app, but it won't be solidified until I can successfully get the morphs working properly. Thanks.

**Comment by c4augustus** [comment]
I hope that Urho3D works out for us. I'm very impressed on how well the whole project is put together. The code and it's organization are straightforward and comprehensible. I samples sold me on the completeness and quality of the feature set. Kudos, truly, a job well done.

**Comment by weitjong** [comment]
I will perform a minor clean up while I am at it as it appears the manual version upgrade that we did in the past have left a few unused source code in the directory.

**Comment by c4augustus** [comment]
@weitjong do you want to convert Source/ThirdParty/Assimp into a git subtree first? If so, then I will follow you with the upgrade to 4.0.1 and then the changes to AssetImporter.

**Comment by weitjong** [comment]
I have already started the process but not able to complete it last night. Hope to get it done tonight. No promise.

**Comment by c4augustus** [comment]
It seems that the integration of assimp's CMake and Urho3D's CMake is non-trivial, and I'm guessing you did a lot of work to resolve it. I'll wait an see where you get with the git subtree change, and possibly you might need to do the upgrade from v3.2 to v4.0.1. Thanks.

**Comment by weitjong** [comment]
Sorry for the delay. I have the subdir converted to subtree already on my local repo but could not push it yet because it didn't build cleanly yet. I have resolved all the conflicts, except for CMakeLists.txt. Now I understand why the version was v3.2 although assimp was just upgraded at the beginning of this year by someone. The versions after that release use more C++11 stuffs and we were not ready for that then. Thus, now a few of the conflicts were actually resolved by simply reverting to original, i.e. discarding our local fixes to make it work for non-C++11 compiler last time. If there is no further surprise then the subtree will be pushed later tonight when it is done.

**Comment by c4augustus** [comment]
Thanks for all the effort. For the time being, I've just been trying to copy the new ColladaParser.cpp/.h over from v4.0.1 into the existing v3.2 files. But I'm not sure whether this will be more or less work than the full v4.0.1 upgrade. I need to make this happen soon, so I'm trying the fastest, rather than the cleanest approach, but just for now.

**Comment by c4augustus** [comment]
I was successful with the minor surgery of copying ColladaParser.cpp/.h from assimp v4.0.1 into Urho's copy of assimp v3.2. And it looks like it is creating morph meshes for the shape keys imported from a blender file. My next step is to enhance AssetImporter to convert the morph data into Urho's format.

**Comment by c4augustus** [comment]
FYI, this is that commit in my fork (without any changes yet to AssetImporter): https://github.com/c4augustus/Urho3D/commit/1a61600bf3543dfd846ee3e7e0d45aec9bc45269

**Comment by weitjong** [comment]
You can check out the 4.0.1 assimp subtree in the branch now. https://github.com/urho3d/Urho3D/tree/update-assimp.

**Comment by weitjong** [comment]
I was misled to believe that the 4.0.1 "-Wa,-mbig-obj" would fix a known build issue with MinGW compiler which we have previously workaround it using other approach. However, it turns out that I may have to revert back to our own approach as Travis-CI showed the former does not work. D'oh!

**Comment by c4augustus** [comment]
Believe me, I get it. Multiplatform engines and frameworks are not easy. I spent several years struggling with MinGW for my own 3D game engine.

**Comment by c4augustus** [comment]
@weitjong your branch "update-assimp" works great for me using Xcode. So now I'm working on AssetImporter. We are going to need to patch assimp though because they drop the "target" mesh name when creating AnimMesh(es) (morph meshs), so we end up losing the name of the morph.

**Comment by weitjong** [comment]
No problem. For the smallish custom patch, you can make submit it as part of the PR against the `update-assimp` branch directly.

**Comment by weitjong** [comment]
On second thought, if you have tested the new assimp to be in good working order then we may just as well merge the branch to master first. Decoupling it from your plan changes. Then you can make your PR against the master branch as per normal.

**Comment by c4augustus** [comment]
Either way works for me. I'm making progress and will use what I come up with in my repo because I need to produce a working demo ASAP. Fingers crossed.

**Comment by c4augustus** [comment]
FYI, assimp 4.0.1 is not parsing COLLADA morphs correctly. So it will need to be fixed.

**Comment by c4augustus** [comment]
Apparently assimp completely re-indexes all vertices from imported meshes, treating every face as if it has unique vertices not shared with other faces (worst-case scenario). The original list of source indices is gone once assimp creates it's intermediary aiMesh structure. This vastly increases the vertex counts and overhead in converted assets. Given this, I'm surprised that assimp is being used. If we are going use Urho3D, we will have to get another converter working, but we only need FBX.

**Comment by c4augustus** [comment]
assimp has not yet completed their morph support, clearly. None of the post-processing steps account for AnimMeshes. It's this one that is the biggest problems: https://github.com/assimp/assimp/blob/master/code/JoinVerticesProcess.cpp. I'm just disabling it for now and living with 26915 vertices never getting condensed down to 4990, or its original 4548.

**Comment by c4augustus** [comment]
I finally got morphs working well enough for my demo. These changes aren't clean enough for a PR yet. But here is what it looks like in my fork: https://github.com/c4augustus/Urho3D/commits/dev-c4augustus-assetimporter-morphs-e

**Comment by 0x4D3342** [comment]
@c4augustus @weitjong thanks for your improvement,but actually it's not work for me,the count of morph also is wrong ,and the morph animation also not working well,any suggestion,thanks a lot

**Comment by weitjong** [comment]
We are still waiting for the PR from OP. We have upgraded assimp on our end though as promise.

**Comment by c4augustus** [comment]
Sorry but I did just the minimal work that was needed for my client, whom unfortunately decided to abandon the product that was using Urho3D. It comes as no surprise that the support I coded doesn't satisfy all, or many, use cases. By all means, use this a starting point to continue the work and submit your own PR. I don't have any need for Urho3D at this time, but if that changes then I will pick up the baton. Cheers.

**Comment by CaichaoGitHub** [comment]
is the Morph supported ?

I export my model to FBX format in blender with some shape keys , then i use AssetImporter to convert fbx to urho3d model
like this : ./AssetImporter model soldier.fbx soldier.mdl
after that i load my model into urho3d framework , but the morph count is zero ?
