### ISSUE TITLE
Call C++ function from javascript (emscripten)

### ISSUE THREAD

**Issue by MichalPetryk** [urho3d/Urho3D#2144]
Hi,

I'm trying to call c++ function definied in my Application class from javascript, but with no success.

My application class definition is:

<pre>
SharedPtr<Text> helloText;
public: SampleApplication(Context * context) : Application(context) {}
void CreateText()
	{
		helloText=new Text(context_);
		helloText->SetText("Hello!");
		helloText->SetFont(cache->GetResource<Font>("Fonts/Anonymous Pro.ttf"), 30);
		helloText->SetColor(Color(0.0f, 1.0f, 0.0f));
		helloText->SetHorizontalAlignment(HA_CENTER);
		helloText->SetVerticalAlignment(VA_CENTER);
		GetSubsystem<UI>()->GetRoot()->AddChild(helloText);
	}
public: void ChangeTextFromJs()
{
	helloText->SetText("Hello from JS!");
}
</pre>

I want to call public function ChangeTextFromJs in my javascript code (after click some html button).

<pre>
<script type='text/javascript'>
      var Module = {
        preRun: [],
        postRun: [],
        print: (function() {
.....
</pre>

**Comment by kabukunz** [comment]
Have a look at: https://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/embind.html
