### ISSUE TITLE
AnimatedSprite2D is not applying opacity ( alpha ) data from Spriter data files ( scml ).

### ISSUE THREAD

**Issue by slaverne** [urho3d/Urho3D#2145]
Created a Spriter file (scml) with animated opacity changes included.
Checked that the file contains the opacity information (TextEdit).
The animated sprite runs, appears, but without transparency changes.
Inspected code, and can see that the application of alpha_ to vertex data is missing in AnimatedSprite2D::UpdateSourceBatchesSpriter. Perhaps more downstream changes are needed as well ? or side effects - anyway it looks like that code should be added for completeness in supporting Spriter.

**Comment by weitjong** [comment]
Should be already fixed in #2145.
