### ISSUE TITLE
SDL 2.0.7

### ISSUE THREAD

**Issue by amerkoleci** [urho3d/Urho3D#2146]
Version 2.0.6 has been released (https://discourse.libsdl.org/t/sdl-2-0-6-released/23109).

If I'm able I will send PR

**Comment by weitjong** [comment]
Thanks. The PR for this should be made against the https://github.com/urho3d/SDL-mirror (our SDL fork), and not in the Urho main repo.

**Comment by alex-rass-88** [comment]
SDL 2.0.7 released

**Comment by weitjong** [comment]
Just an update: I am about half way there rebasing our SDL subtree to release 2.0.7. And after that some work is required to assimilate it, especially on Android platform (SDL_android_main.c was decommissioned since 2.0.6 but we have custom change there which is critical to our engine initialization).

**Comment by weitjong** [comment]
Just got time to continue and complete the rebasing today. Next, to pull those new changes in and see what breaks beside Android.

**Comment by weitjong** [comment]
The SDL 2.0.6 has added a new audio driver to interface with WASAPI on Windows platform. Their future plan is to decommission the existing XAudio2 audio driver. Currently I have moved the WASAPI development header detection logic to our existing FindDirectX.cmake module, but now I doubt that decision is correct. Now thinking to move that part of the logic back to the SDL's CMakeLists.txt as it seems WASAPI does not belong to DirectX. I am also not sure what this means to MnGW. Any idea?

**Comment by weitjong** [comment]
One of the class in SDL now attempts to use SSE3. For GCC/Clang, it is easy to detect when the extension is available and enable it. For MSVC though, I do not know anyway to do the detection. Instead, we just assume it has SSE and SSE2 in the past. So for SSE3, I will assume it has it when targeting 64-bit only. See https://msdn.microsoft.com/en-us/library/7t5yh4fd.aspx.

If anyone of you know a better way, let me know.

**Comment by weitjong** [comment]
Update: fresh installing my primary system to Fedora 27 and took more time than I expected to reconfigure all my development environments. Anyway, got Android environment configured today and just starting debugging why the Android app cannot be started.

**Comment by weitjong** [comment]
Android is building fine now. Tested using x86_64 ABI on Linux host only, but other ABI/build host should not make any differences in this case.

Next, fix RPI build which should make our engine supports Raspbian Stretch.

**Comment by eugeneko** [comment]
@weitjong Just curious. Why simple 3rdParty update causes so many problems?

**Comment by weitjong** [comment]
SDL is anything but simple. Also because 2.0.6/2.0.7 makes a few breaking changes. And that I have limited time working on Urho recently. It’s not like I was stuck for weeks because of an issue or something.

**Comment by weitjong** [comment]
The RPI build is fixed now. I haven't tested it on the actual RPI with Raspbian Stretch yet. Stretch will be the only supported version for now.

The last platform to fix is iOS/tvOS. Once that's done I can wrap this one up.

**Comment by weitjong** [comment]
The "upgrade-sdl-2.0.7" branch can be considered ready for merging (after a final rebasing). I would appreciate if some of you can do some preliminary tests across all the Urho3D supported platforms and report any issue back. For iOS you have to use 10.x as the highest deployment target at the moment (see issue reported in #2190, this issue will be tracked there separately).

**Comment by weitjong** [comment]
This dev branch is merged. A little disappointed by not having any feedback. I guess it is as usual, we have to merge it to master branch first and that's when shit hits the fan.

**Comment by 1vanK** [comment]
It is best way for testing :)
