### ISSUE TITLE
opengl32.lib not added by cmake on windows.

### ISSUE THREAD

**Issue by TrevorCash** [urho3d/Urho3D#2147]
After I regenerated and rebuilt Urho3D with OpenGL enabled.   And then regenerated and rebuilt my project, I had to manually add "opengl32.lib" to my project settings.  Interestingly, "b3d9.lib" was still present in the project.

I am using Visual Studio 2017.

**Comment by weitjong** [comment]
Use separate build tree when you switch from one graphics API to another. In fact you should do that when you change a few of the critical build options. When in doubt, like I always said, it is safe just to nuke your existing build tree and regenerate from scratch. That's the benefit of using out-of-source build tree.
