### ISSUE TITLE
Can't build for android

### ISSUE THREAD

**Issue by nesrak1** [urho3d/Urho3D#2148]
I'm trying to build the default android project on windows. Tried 1.7 and master.
1. `cmake_android c:/blah/blah/projectpath` in urho3d-master
2. `make -j2` in project root

Eventually errors to
```
C:/Users/karse/Downloads/Urho3D-master/Urho3D-master/Source/Urho3D/Container/Str.cpp:1081:14: error: non-const lvalue reference to type '__builtin_va_list' cannot bind

      to a value of unrelated type 'va_list' (aka '__builtin_va_list')
    va_start(args, formatString);
             ^~~~
c:\NVPACK\android-ndk-r12b\toolchains\llvm\prebuilt\windows-x86_64\bin\..\lib64\clang\3.8.256229\include\stdarg.h:33:48: note: expanded from macro 'va_start'
#define va_start(ap, param) __builtin_va_start(ap, param)
                                               ^~
```
Error looks similar to [this](https://github.com/urho3d/Urho3D/issues/1616#issuecomment-249433877)?

**Comment by nesrak1** [comment]
Looked into the link in the above link, set URHO3D_PCH:BOOL to off and it seems to have worked, however it would be nice if this was documented on the building page/wiki somewhere.

**Comment by weitjong** [comment]
Strange. I thought we have taken care of that. Both 1.7 and current master have line like this. https://github.com/urho3d/Urho3D/blob/2ac4f89a86bc9f978a8212883ebeb82ba873b53c/CMake/Modules/CheckHost.cmake#L82-L88

**Comment by nesrak1** [comment]
`# Turn off PCH when building on macOS...`
I'm on Windows so wouldn't that if statement not go through?

**Comment by nesrak1** [comment]
Hm, that is strange. I am using the sdk from nvpack which was installed with unreal and might have some weird changes to the name? I would try to debug this but not really too sure how.

**Comment by weitjong** [comment]
Most probably it's because the `ANDROID` CMake variable is not defined. We define that variable in our own custom CMake/Android toolchain file (not the one shipped by the Android NDK (or any other SDK). But I haven't checked other toolchain file personally.

**Comment by nesrak1** [comment]
I meant maybe the CMAKE_CXX_COMPILER_ID was not specifically "Clang". Pretty sure I saw the android variable defined, I'll check later and see if that's the case.

**Comment by Lumak** [comment]
@nesrak1, odd you're getting a compile error. I tested the 1.7 tag, built it and also verified running on x86 emulation devices with no problems, as discussed here https://github.com/urho3d/Urho3D/issues/2080
Only difference is, I used the latest ndk-r15c.

**Comment by nesrak1** [comment]
Check wasn't executing because I was running windows and so it never made it to that check. I copied the block @weitjong pasted inside the `if (CMAKE_HOST_WIN32)` block and sure enough it compiled fine without changing anything else.

**Comment by weitjong** [comment]
I see it now. There is no reason why Clang cannot work with PCH in the first place, so there must be something wrong on our setup. That block is actually supposed to be a temporary fix until we can figure out where we have done wrong.
