### ISSUE TITLE
App not being updated on window resize

### ISSUE THREAD

**Issue by uniquejack** [urho3d/Urho3D#2150]
Whenever I try to resize the window, the application stops to update until I release the mouse button. 
Here's an image of what happens:
![immagine](https://user-images.githubusercontent.com/6839120/31567316-379566dc-b06f-11e7-9cb6-68af4f7ac9b1.jpg)

It looks ugly because it doesn't even clear the screen. I know in some cases the engine should stop rendering but I don't think this should be the case since the device don't get lost and the window still has the mouse focus. What I would like to do is to render while I'm resizing the window so I can see how my UI responses to a resize in realtime without the need to wait the mouse button release. Is it possible?

**Comment by weitjong** [comment]
This looks like a platform-specific issue. Just tested on Linux and could not reproduce the issue there (using one of the sample app and editor). If you build your project using DEBUG build configuration, you should be able to see SDL fires the windows resized event while it is still in progress and not after the mouse has been released. The Urho's input subsystem handles these events by delegating to the Graphics subsystem which performs the actual work and then adds a debug log entry among others. So, you could at least quickly verify whether the window resized events come while you resizing or not on Windows platform. It it doesn't then it is beyond us (it is SDL/Windows problem). However, if it does come multiple times then you can try to switch between D3D9 and D3D11 to see whether both Graphics API produce the same issue or not.

**Comment by weitjong** [comment]
Close. Feel free to reopen if you have more to add.
