### ISSUE TITLE
Ninja always generates build tree on source toplevel

### ISSUE THREAD

**Issue by cirosantilli** [urho3d/Urho3D#2152]
I can't to a ninja out of tree build, e.g.:

```
./cmake_ninja.sh build-ninja
```

generates build file on current directory instead of inside `build-ninja`.

Same if I do:

```
mkdir build-ninja
cd build-ninja
cmake .. -G ninja
```

Ubuntu 17.04, CMake 3.7.2, ninja 1.7.2.

**Comment by weitjong** [comment]
Most probably you have remnant CMake generated files in the source tree from your past attempt. Remove them if any before retrying.
