### ISSUE TITLE
HashSet Allows duplicate items

### ISSUE THREAD

**Issue by TrevorCash** [urho3d/Urho3D#2153]
I created a HashSet of Vector4's. I expected if I insert 2 identical values, only 1 would exist in the set.

Here is a the printout after I iterate through a hashset:

```
HashSet<Vector4> consideredCorners;

//Insertion code here..

for (auto i = consideredCorners.Begin(); i != consideredCorners.End(); i++)
{
	Vector4 corner = i.operator*();
	if (corner.z_ > 0 && corner.w_ > 0.0f)
	{
		URHO3D_LOGINFO("Failed On Corner: " + String(corner));
	}
		return false;
}

```

Output:

> **[Mon Oct 16 15:40:29 2017] INFO: Failed On Corner: -0.5 0.5 0.5 1**
> [Mon Oct 16 15:40:29 2017] INFO: Failed On Corner: 0.5 0.5 0.5 1
> [Mon Oct 16 15:40:29 2017] INFO: Failed On Corner: -0.5 -0.5 0.5 1
> **[Mon Oct 16 15:40:29 2017] INFO: Failed On Corner: -0.5 0.5 0.5 1**
> [Mon Oct 16 15:40:29 2017] INFO: Failed On Corner: 0.5 0.5 0.5 1
>

**Comment by TrevorCash** [comment]
Or could this be the float values of the vector4's are actually different and generating different hash values

**Comment by eugeneko** [comment]
Could you make a sample?

**Comment by TrevorCash** [comment]
Never Mind - Its working fine :) It was a silly printout miss-interpretation on my own part.
