### ISSUE TITLE
Direct3D11 backend: Texture2D.SetSize fails when using TEXTURE_DYNAMIC

### ISSUE THREAD

**Issue by andrekoehler** [urho3d/Urho3D#2165]
This bug was already reported in issue #1153 and was fixed, but it seems like commit 46b9a90fb1df053860adc9ce219ac05b2b295310 removed the fix later on.

The following code fails (added to the end of the HelloWorld::Start() method in the 01_HelloWorld sample):
```
Graphics &graphics = *GetSubsystem<Graphics>();
Urho3D::Texture2D tex(context_);
bool success = tex.SetSize(
	256, 256,
	graphics.GetFormat(Urho3D::CompressedFormat::CF_RGBA),
	Urho3D::TextureUsage::TEXTURE_DYNAMIC);
```

I debugged it and the error occurs in D3D11Texture2D.cpp in the bool Texture2D::Create() method at the following line:
https://github.com/urho3d/Urho3D/blob/37cba9522d6ce0d47445951469291ea078ac9440/Source/Urho3D/Graphics/Direct3D11/D3D11Texture2D.cpp#L416

textureDesc has the following content:
-	textureDesc	{Width=256 Height=256 MipLevels=9 ...}	D3D11_TEXTURE2D_DESC
		Width	256	unsigned int
		Height	256	unsigned int
		MipLevels	9	unsigned int
		ArraySize	1	unsigned int
		Format	DXGI_FORMAT_R8G8B8A8_UNORM (28)	DXGI_FORMAT
	-	SampleDesc	{Count=1 Quality=0 }	DXGI_SAMPLE_DESC
			Count	1	unsigned int
			Quality	0	unsigned int
		Usage	D3D11_USAGE_DYNAMIC (2)	D3D11_USAGE
		BindFlags	8	unsigned int
		CPUAccessFlags	65536	unsigned int
		MiscFlags	0	unsigned int

hr has the following value after CreateTexture2D returns:
hr	E_INVALIDARG One or more arguments are invalid.	HRESULT

The DirectX debug runtime prints the following error explanation: D3D11 ERROR: ID3D11Device::CreateTexture2D: A D3D11_USAGE_DYNAMIC Resource must have MipLevels equal to 1. [ STATE_CREATION ERROR 102: CREATETEXTURE2D_INVALIDMIPLEVELS]

**Comment by eugeneko** [comment]
Yeah.
The second part of the condition seems to be removed
https://github.com/urho3d/Urho3D/commit/46b9a90fb1df053860adc9ce219ac05b2b295310#diff-0a849acc7a05fff203eb72ec5c91a46bR125
https://github.com/urho3d/Urho3D/commit/46b9a90fb1df053860adc9ce219ac05b2b295310#diff-ebe8801d02f032b87daecb0df51311d8L142
