### ISSUE TITLE
Apple Spotlight created files makes Android Ndk build crash on Os X

### ISSUE THREAD

**Issue by kabukunz** [urho3d/Urho3D#2167]
Spotlight, a very useful tool by Apple on Os X, sparingly creates .DS_Store files all over filesystem.
If you happens to "visit" android ndk installation dirs, by chance it will create a file like that in ${ANDROID_NDK}/toolchains/llvm/prebuilt. 
This, in turn, makes the Android.cmake used by Urho to go crazy over this line:

file (GLOB ANDROID_NDK_HOST_SYSTEM_NAME RELATIVE ${ANDROID_NDK_TOOLCHAINS_PATH}/llvm/prebuilt ${ANDROID_NDK_TOOLCHAINS_PATH}/llvm/prebuilt/*)

which will get the string: .DS_Storedarwin-x86_64 causing the build to fail.

Unsure about the fix, because, apart from simply deleting the file manually, it appears to be system dependent and ndk-dependent: simply changing to 

${ANDROID_NDK_TOOLCHAINS_PATH}/llvm/prebuilt ${ANDROID_NDK_TOOLCHAINS_PATH}/llvm/prebuilt/darwin-x86_64) 

works on Os X but not on other systems; deleting the file into cmake with:

file(REMOVE ".DS_Store" RELATIVE ${ANDROID_NDK_TOOLCHAINS_PATH}/llvm/prebuilt)

gets "permission denied" (read only file).

Crazy but true.

**Comment by weitjong** [comment]
This issue is now fixed in the `gradle-kotlin-dsl` dev branch. That dev branch will be merged soon. To safe me time to come back to issue log again later, I am closing it now.
