### ISSUE TITLE
VS 2017 having problem compiling Assimp 4.0.1

### ISSUE THREAD

**Issue by weitjong** [urho3d/Urho3D#2175]
https://discourse.urho3d.io/t/how-to-pass-build-options/3753/5
See https://github.com/assimp/assimp/issues/1548

**Comment by 1vanK** [comment]
https://github.com/urho3d/Urho3D/issues/2162

**Comment by eugeneko** [comment]
I merged compilation hotfix to make life a bit simpler for ones who use VS 2017 only.
I think we have to update whole AssImp tho, but with lower priority.

**Comment by 1vanK** [comment]
All changes in assimport looks like
```
// Urho3D: modified to not use C++11
```
so we can just try to copy new version without modify

**Comment by eugeneko** [comment]
BTW, I haven't marked my change as `Urho3D` because it's taken from assimp head.

**Comment by weitjong** [comment]
You should have used git cherry pick to do that, so it is easier to reconcile later when we do version upgrade. Having said that, it will not be a big problem so you can let it be.

**Comment by eugeneko** [comment]
@weitjong I thought about it, but I don't know how to cherry pick a commit from another repo with different file structure and so on...
That commit also had some OpenMP stuff that we don't have.

**Comment by weitjong** [comment]
I plan to do this when I have time but you beat me to it. There is more than one way to fix things. So don't worry about what I just said.
