### ISSUE TITLE
Object TypeInfo should implement equality operator

### ISSUE THREAD

**Issue by amerkoleci** [urho3d/Urho3D#2180]
I have case where same TypeInfo are not not equal, thus IsInstanceOf or Cast fails. Probably TypeInfo IsTypeOf should check only using the StringHash.

**Comment by eugeneko** [comment]
> I have case where same TypeInfo are not not equal, thus IsInstanceOf or Cast fails. 

Could you provide an example?

**Comment by amerkoleci** [comment]
I have for example TestComponent that has URHO_OBJECT usage and when I check IsInstanceOf <Component> it returns false, the component is defined in external lib if thar makes sense

**Comment by eugeneko** [comment]
The proposed change makes sence IMO. However, the situation is quite strange. Do you use DLLs?

**Comment by amerkoleci** [comment]
I have my example (exe) which contains the component and I link shared Urho version.

**Comment by eugeneko** [comment]
From all my heart I suggest you to never ever use shared libraries if you have a choise.
DLL is much harder to configure and stabilize than static library. This error could be a sing that shared Urho DLL is not properly linked to the executable. I'll try to reproduce & debug it later tho...
