### ISSUE TITLE
OpenGL ES 3 Support

### ISSUE THREAD

**Issue by sofmz** [urho3d/Urho3D#2181]
It would be nice if Urho3D supports OpenGL ES 3, there are couple of features that are very useful. One example is the standardised ETC2 compressed texture. Urho users that are targeting for mobile platforms now need to work with different compressed texture format and different restrictions for Android and iOS, supporting ES3 could make the ETC2 possible to be used. 

Most mobile devices nowadays support ES3 , in fact most mainstream mobile devices that are released in past 2-3 years support OpenGL ES3.

**Comment by weitjong** [comment]
Sorry for the fat finger.

**Comment by rokups** [comment]
You got me worried there for a moment
