### ISSUE TITLE
Api docs is very confusing when using Angel Script

### ISSUE THREAD

**Issue by GeorgeBekh** [urho3d/Urho3D#2199]
When using Angel Script almost at the start i stumbled across very confusing thing:
when i want to use some setter or getter, say, Node::GetName() it says "No matching signatures" and at first i though it was a bug, because when i typed Node::GetChild("someName") it was ok.
After some exploration of Editor source code i've figured out that instead getters and setters i should use public properties of an object. But at first it was very scary.  Would you mind pointing me some docs where this is specified (because i still don't know how it actually works xD) and maybe make this thing more availible so it wouldn't scare newbies and force them to go to C++ where these getters and setters actually works.

Scary docs:
https://urho3d.github.io/documentation/1.7/class_urho3_d_1_1_node.html#a3c19eb87f2855894c1757659ede5a509

Thanks for your efforts!

**Comment by 1vanK** [comment]
https://urho3d.github.io/documentation/1.7/_script_a_p_i.html
