### ISSUE TITLE
Wrong Operator in Texture2D.cpp Line 78

### ISSUE THREAD

**Issue by askamn** [urho3d/Urho3D#2205]
```
loadImage_ = new Image(context_);
if (!loadImage_->Load(source))
{
    loadImage_.Reset();
    return false;
}
```

I am pretty sure that loadImage_->Reset() since its a class pointer.

**Comment by Stinkfist0** [comment]
loadImage_ is a SharedPtr to Image.

**Comment by askamn** [comment]
Oh. my bad. I actually just saw the code online :P Didn't really download and see everything thoroughly.
