### ISSUE TITLE
Scripting API Inconsistency in File Class

### ISSUE THREAD

**Issue by SirNate0** [urho3d/Urho3D#2208]
I noticed when doing some work on abstracting parts of the File class that the LuaScript API exposes SetName, but the AngelScript exposes the name as only a readonly property. I will probably correct this with some work that I'm doing, but I didn't want to forget (and if my work wasn't accepted, probably best to point it out here).

I'm not sure which is correct, as SetName is meant for the ResourceCache to use, but I will probably go with exposing it to both scripting subsystems.

**Comment by 1vanK** [comment]
Fixed in auto generated bindings
