### ISSUE TITLE
Add GetCreateMode() to Node and Component

### ISSUE THREAD

**Issue by TrevorCash** [urho3d/Urho3D#2211]
Adding GetCreateMode() to the Node and Component classes would be nice to have for later polling of which create mode a node or component was created with.

Is there a philosophical reason this is not already there?

**Comment by eugeneko** [comment]
> would be nice to have for later polling of which create mode a node or component was created with.

You could do it by checking ID. But some helpers would make sence. Maybe `IsLocal/IsReplicated` instead of `GetCreateMode`.

**Comment by weitjong** [comment]
Agree with @eugeneko . This kind of check is being done in the Editor in a few places. This is one of them.
https://github.com/urho3d/Urho3D/blob/bae678b1324c8d54782d0fffe662316d5b5d80b1/bin/Data/Scripts/Editor/EditorActions.as#L138
I like IsReplicated() over the other as I think it is clearer what it is for even without reading the doc.

**Comment by TrevorCash** [comment]
IsReplicated() would be awesome.  Is FIRST_LOCAL_ID a constant number in the engine that splits all the local and replicates apart in the nodeID spectrum?

**Comment by weitjong** [comment]
Yes. The constant is used for both Node and Component.
