### ISSUE TITLE
Emscripten build error in sdl_config.h & filesystem.cpp

### ISSUE THREAD

**Issue by rifai** [urho3d/Urho3D#2224]
Just trying to build with cmake_emscripten.bat on windows. I got this error. 
```
xxx/include/Urho3D/ThirdParty\SDL/SDL_config.h:48:10: fatal error: 'SDL_config_linux.h'
      file not found
#include "SDL_config_linux.h"
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
make[2]: *** [Source/Urho3D/CMakeFiles/Urho3D.dir/IO/FileSystem.cpp.o] Error 1
make[1]: *** [Source/Urho3D/CMakeFiles/Urho3D.dir/all] Error 2
make: *** [all] Error 2
```
Looking at SDL_config.h, emscripten build trying to include SDL_config_linux.h. 
``` c
#else 
// Urho3D: add Linux prebuilt config file
#include "SDL_config_linux.h"
#endif /* platform config */
```

For quick temp fixed, I added something like this. 
``` c
#elif defined(__LINUX__)
// Urho3D: add Linux prebuilt config file
#include "SDL_config_linux.h"
#else
#include "SDL_config_minimal.h"
#endif /* platform config */
```

But, I got another error.
```
xxx\Urho3D\Source\Urho3D\IO\FileSystem.cpp: In member function 'Urho3D::String Urho3D::FileSystem::GetTemporaryDir() const':
xxx\Urho3D\Source\Urho3D\IO\FileSystem.cpp:1075:40: error: 'SDL_arraysize' was not declared in this scope
    GetTempPathW(SDL_arraysize(pathName), pathName);
```
I don't know how to fix this, If I just return "/tmp/", I don't get any error anymore and build emscripten successfully.

**Comment by weitjong** [comment]
Something is wrong with your setup but I am not sure what. The SDL config header file being used in the build is the one auto-generated by CMake in the build tree. The one in the source tree is now defunct. If you have setup correctly then the header search path should include the “generated” dir in your build tree. And this is done automatically by our build system.

**Comment by weitjong** [comment]
Just tried install and activate the latest EM SDK on my Win7 VM, I could not reproduce the first issue but I could confirm the second error you encountered is a bug.

**Comment by weitjong** [comment]
Looks like I spoke too fast. After fixing the FileSystem class compilation error, I now hit by the first issue you reported. :smile:

**Comment by weitjong** [comment]
The now defunct "SDL_config.h" in the source tree was the root cause of the first issue. It appears Windows MKLINK does not know how to overwrite the symlink which initially pointing to the header in the source tree. On *Nix, this is not a problem. The easiest way out is to just remove this unused file.
