### ISSUE TITLE
How to create a planetarium-like application using Urho?

### ISSUE THREAD

**Issue by laheller** [urho3d/Urho3D#2225]
Hello,

I am just collecting information about how to create a planetarium like application using Urho.
For example an application, like [Stellarium](http://stellarium.org/).
What I think I need definitely is a sphere (Earth) in the center of the world (Universe) where the camera (observer, telescope) will be somewhere on the surface of that sphere (Earth).
Stars (or other objects, like clusters, galaxies, nebulaes) on the sky can be also small spheres, where visibility and position is calculated based on real star catalogue information ([Simbad](http://cdsportal.u-strasbg.fr/), [NED](http://ned.ipac.caltech.edu/forms/byname.html)).

Any help, information or link to similar project implemented using Urho is appreciated!

Best Regards,

Ladislav

**Comment by weitjong** [comment]
You should post question in our forum instead of using our issue tracker. Also, I think you will get more responses there.

**Comment by laheller** [comment]
@weitjong OK, I already posted my question to Urho forum.
