### ISSUE TITLE
Node::Clone and CloneComponent will lead to crash when used outside of a scene

### ISSUE THREAD

**Issue by lezak** [urho3d/Urho3D#2230]
Both E_NODECLONED and E_COMPONENTCLONED events are supposed to be send by a scene and this will  lead to access violation when the node (or component) that is being cloned doesn't belong to any scene.

**Comment by weitjong** [comment]
Thanks for pointing this out. The code is now fixed by only sending these events when the scene is not null. The commit will be pushed shortly.
