### ISSUE TITLE
Color constants in AngelScript are in the global namespace.

### ISSUE THREAD

**Issue by MajorMcDoom** [urho3d/Urho3D#2237]
Color constants in AngelScript are in the global namespace.
This is inconsistent with constants for Vector3s and other math types.
For example, you would write `Vector3::ZERO`, but just `WHITE`.

**Comment by weitjong** [comment]
There are a few other constants being exposed as global constants as well. The color constants are not the exception. On the contrary it is the constants from the IntVector2/Vector3/etc that are declared within their own namespace for obvious reason, i.e. to avoid name clash.

**Comment by MajorMcDoom** [comment]
I see. That makes sense. Thanks!
