### ISSUE TITLE
SSE problem

### ISSUE THREAD

**Issue by bosoni** [urho3d/Urho3D#2238]
After this commit
" Adjust compiler flags to enable SSE3 when it is supported.
  SHA 093a5b61058e8f5ffc55a5a269584344051ab266
" 
compiling with default cmake settings, all .exe files crashes.
They work when I disable SSE.

(AMD phenom x4, W7 x64)

**Comment by weitjong** [comment]
Your CPU does not support AVX. Unfortunately on Windows/VS I don’t know how to auto detect that and configure the build accordingly. You will have to manually revise the UrhoCommon.cmake to revert back the “/AVX” flag to “/SSE2” for now, until we can think of a better solution. Or stay with 1.7 release.

**Comment by sirop** [comment]
BTW, 

> If you try to use them on a Windows version prior to Windows 7 **SP1**, they will be considered illegal instructions, even if the CPU has AVX support.

https://insufficientlycomplicated.wordpress.com/2011/11/07/detecting-intel-advanced-vector-extensions-avx-in-visual-studio/

**Comment by weitjong** [comment]
On Linux and Mac, we have URHO3D_DEPLOYMENT_TARGET or similar build option to influence the compiler to conditionally emit the __SSE2__ or __SSE3__, etc compiler predefined macros and use that for configuring the build tree. That is, the detection is done during build tree generation time; and not during build time nor during run time. If someone can show me how to do that for VS on Windows host system then I am willing to make the necessary change in the build system.

**Comment by weitjong** [comment]
Closing this now. Feel free to reopen when there is more information on how to do this for VS.

**Comment by sirop** [comment]
Just for the record:
maybe, the anaser: https://stackoverflow.com/a/42755665/4599792

**Comment by weitjong** [comment]
I don’t think it solves our issue. It only checks the capability of the VS compiler being used during build tree generation. That does not capture the user intention of selecting deployment target. In theory I could use the latest compiler available on the latest CPU available but yet specify that the build only generate binary compatible to lower spec CPU as my target.

**Comment by boberfly** [comment]
Can we just have SSE2 minimum spec and AVX as an optional forced flag for now until it's figured out? Seems reasonable to me for a good out of the box experience....

**Comment by weitjong** [comment]
I try to avoid to have another build option for SSE3 but it appears to be a good compromise in this case. I am currently out of town, so will revisit this later when I am back (unless someone has bitten me to it).

**Comment by bosoni** [comment]
SSE3 works and even SSE4 but AVX doesnt. 
I think boberfly's idea is good.

This is my (not so old, maybe 5years) processor info, so I think Urho3D trunk should not require newest hardware:
![cpu](https://user-images.githubusercontent.com/2569545/36627664-9f0411cc-194e-11e8-8f87-61a5453e9d3f.png)

**Comment by weitjong** [comment]
The latest SDL only rakes advantage of SSE3 anyway. In the past it only able to use SSE2 when it is available. In other words, if VS users do not use AVX flags and falling back to SSE2 then it will miss out something to non-VS users.

**Comment by weitjong** [comment]
See my edited comment in Github.

**Comment by boberfly** [comment]
Yeah that's strange how MSVC doesn't let you disable AVX then. Yeah this is just speculation on my part but I would think there's not a huge advantage in Urho currently for this unless someone explicitly codes in some fast path that takes advantage of SIMD or there's some thirdparty lib that can use it. 

On another note, to accelerate Urho I am thinking that using ISPC is a good option, as it builds for multiple SIMD extensions as separate symbols and will pick the right one at runtime. Here's an example integration for converting to GPU compressed formats:
https://github.com/boberfly/urho3d/tree/ispc_texcomp
And an example of when SSE or NEON is set to activate the right flags for ISPC:
https://github.com/boberfly/Urho3D/blob/ispc_texcomp/CMake/Modules/Urho3D-CMake-common.cmake#L1712

I think the build system has progressed since then though, but this is a basic integration of ISPC if anyone is interested...

**Comment by weitjong** [comment]
I think I have already made it clear that for now I have no issue to let VS to stay with SSE2 (if that’s all the VS users want) and allow the Urho3D lib to not have feature parity between Windows and non-Windows platforms. Like you said, currently there is not much (yet) being missed out. However, SDL 2.0.6/7 (not sure which version) only started to use SSE3 support for fast audio conversion, in future who knows what else. So, we are only delaying the inevitable, at some point in time we need to make a bump on the required hardware. 

Thanks for sharing your work in the link. I am interested to see what technique it employs to build multiple code path during compile time and to switch dynamically during runtime.

**Comment by weitjong** [comment]
I actually do not appreciate people bad mouthing my good intention to not let VS-users from feeling not being taken care of when I upgrade the build system. After reverting back the build script so it again always only assume MSVC can support SSE2, I promise myself not to touch the MSVC/Windows part of the script anymore.

**Comment by weitjong** [comment]
I have decided to do as minimal as possible to revert the thing as it was. @boberfly Feel free to submit PR to have another build option for enabling AVX yourself.
