### ISSUE TITLE
Urho3D, AngelScript & LibCpuId Failing to Build using VS2017 

### ISSUE THREAD

**Issue by kieranhaycock** [urho3d/Urho3D#2239]
Hi all, hope someone can give us a hand.

I've been following this:
https://github.com/urho3d/Urho3D/wiki/Setting-up-Urho3D-on-Windows-with-Visual-Studio
Except I'm using Visual Studio 2017 and running Windows 10.

I've been hoping to look at the samples to see if Urho3D will be suitable for my next project.
There are three projects that are failing when I build as 32 or 64 bit.
If anyone could give us a hand I would be grateful. I've attached the build log.

Thanks in advance!
[Urho3DBuildLog.txt](https://github.com/urho3d/Urho3D/files/1638851/Urho3DBuildLog.txt)

**Comment by weitjong** [comment]
We just changed our AppVeyor to use VS2017 for our CI builds. See whether the CI can reproduce your issue or not.

**Comment by weitjong** [comment]
For what it's worth, I know other users don't have issue with VS2017. Upgrading to use VS2017 in our own CI is anyway due and I don't expect it to have build error. I cannot give you any useful information on how to rectify your issue at the moment. Aside from reading this section https://urho3d.github.io/documentation/HEAD/_misc__how_tos.html#symlinking_on_windows and see whether you have better luck with MKLINK properly configured.

**Comment by weitjong** [comment]
> We just changed our AppVeyor to use VS2017 for our CI builds. See whether the CI can reproduce your issue or not.

Both 32-bit and 64-bit CI build job using VS2017 went successfully. Thus, as originally stated, there is nothing wrong with our VS2015 build support. I am closing this now. If you still cannot figure this out, please ask more question in the forum instead, posting your exact steps to generate the build tree (VS solution file) and how you prepare your build environment, if it is non-standard.

Once last tip. If you are retrying, remember to delete the whole build tree and retry from scratch. Use out-of-source build tree so you can easily discard the generated build tree without effecting the source tree.
