### ISSUE TITLE
Add Generic Graph Container

### ISSUE THREAD

**Issue by TrevorCash** [urho3d/Urho3D#2240]
It would be nice to have a generic graph container similar to LinkedList<T> that supported building/analyzing basic graphs(directed and undirected)

**Comment by weitjong** [comment]
For generic thing like this, I reckon there are already a number of freely available implementation out there. What is the benefit of having yet another implementation in Urho that we have to keep maintaining ourselves?

**Comment by cadaver** [comment]
I could see the benefit in having an uniform API that looks familiar to the other structures / containers. But trying to supply everything by the engine itself has proven to not be a really sustainable path.

**Comment by OvermindDL1** [comment]
I used `boost::graph` personally, what of it does not support what you want?

**Comment by TrevorCash** [comment]
I could probably use boost::graph or LEMON or something.  sometimes It just feels nice to work with one set of containers across a codebase.  I'll close this.

**Comment by OvermindDL1** [comment]
> sometimes It just feels nice to work with one set of containers across a codebase

Which is why I'm for the Urho3D containers working like stdlib containers, then everything would 'just work' together with all the same algorithms and all, unlike the very odd naming schemes it uses now (although at least iterators were added a few years back so they match now).  ^.^
