### ISSUE TITLE
Rendering issue when using hardware depth

### ISSUE THREAD

**Issue by OldSnake22** [urho3d/Urho3D#2243]
Hello, I have a rendering issue when i'm trying to use PBRDeferredHWDepth.xml renderpath.

When a surface that is using refraction (water) is in the camera frustum, It seem that all depth information is "lost" for the next renderpath commands and my post process effects that are using depth information are broken because the depth is not valid anymore. I have tested with the PBRDeferred.xml renderpath and it works fine. 

@cadaver If you are around maybe you know what's could cause this ?

Thanks for your support.

**Comment by eugeneko** [comment]
Could you show full renderpath?
Actually I don't really trust these HWDepth things..
There is `depth` texture set bot as depthstencil and texture unit that is obviously wrong. Maybe this is handled inside the code tho...

**Comment by OldSnake22** [comment]
Tested with the default PBRDeferredHWDepth.xml. Thanks eugeneko for taking a look.

**Comment by OldSnake22** [comment]
Alright it seems that adding <texture unit="depth" name="depth" /> like so: 

```
<command type="scenepass" pass="refract" depthstencil="depth">
        <texture unit="environment" name="viewport" />
	<texture unit="depth" name="depth" />
</command>
```
Is fixing the issue ! Is it logical to have it there ?

**Comment by eugeneko** [comment]
Checked the code, it seems valid. Disregard my concerns above.

> Is it logical to have it there ?

If you want to read depth in some pass, you have to set is as texture unit.
So your fix looks valid.

**Comment by OldSnake22** [comment]
Alright thank you eugeneko. You can put this fix in the master branch then I guess.

**Comment by eugeneko** [comment]
@OldSnake22 Keep in mind that you cannot read and write the same depth simultaneously.
So you should also switch sorting like for transparent objects: `sort="backtofront"`
And be aware that refractive objects won't change depth.
