### ISSUE TITLE
Triage and fix coverity issues

### ISSUE THREAD

**Issue by ricab** [urho3d/Urho3D#2246]
To track _Coverity_ issue triaging and fixing.

**Comment by ricab** [comment]
This issue follows some discussion in an [unrelated PR](https://github.com/urho3d/Urho3D/pull/2214) which went too off-topic. I am planning to triage/fix a couple of Coverity issues once in a while, as I find time (no strings attached). Others may want to do the same or just discuss related matters here.

**Comment by weitjong** [comment]
Something is still fishy on the Coverity-Scan service. One of our CI has submitted the Urho3D for analysis a few days ago. At first it was put into a queue and finally when it is our turn to run, it just stuck there in the running days. At least for 3 days already, if I counted correctly. 

https://scan.coverity.com/projects/urho3d-urho3d

**Comment by ricab** [comment]
OK, thanks for the info. Where can you see that? I can only see that the last scan was on Feb 19. I suppose their system is overloaded after being down for so long. Perhaps it will get sorted out in a few more days.

**Comment by ricab** [comment]
I can't see it, but I believe you.

**Comment by ricab** [comment]
Perhaps only admins can see running instances? I can see the "passed" badge only: <a href="https://scan.coverity.com/projects/urho3d-urho3d">
  <img alt="Coverity Scan Build Status"
       src="https://scan.coverity.com/projects/4954/badge.svg"/>
</a>

Maybe this merits a question to scan-admin@coverity.com. Perhaps it could be manually restarted or something.

**Comment by weitjong** [comment]
I just did and now we wait for their reply.

**Comment by weitjong** [comment]
The last run result is in. The defect density dropped a tiny little.

**Comment by ricab** [comment]
It is still a positive balance :slightly_smiling_face: I suspect most variation comes from Assimp

**Comment by ricab** [comment]
For curiosity, how often does Coverity run on Urho?

**Comment by weitjong** [comment]
On our side we have set it up for CI to scan on every single commit to master branch (only). However, on Coverity-Scan side they have a quota system that limits the scan (determined based on the project size = lines of code), which effectively reduces our scan to maximum once a day, no matter how many commits we make within a day.
