### ISSUE TITLE
Specular is multiplied by brightness twice.

### ISSUE THREAD

**Issue by Bananaft** [urho3d/Urho3D#2252]
When Batch.cpp sets shader parameters:

```
graphics->SetShaderParameter(PSP_LIGHTCOLOR, Color(light->GetEffectiveColor().Abs(),
                light->GetEffectiveSpecularIntensity()) * fade);
```
It uses GetEffectiveSpecularIntensity and GetEffectiveColor, they both return value multiplied by brightness:
```
/// Return effective specular intensity, multiplied by absolute value of brightness.
    float GetEffectiveSpecularIntensity() const { return specularIntensity_ * Abs(brightness_); }
```

Then in shader, specular is multiplied by both cLightColor.rgb and cLightColor.a:

`finalColor = diff * lightColor * (diffColor.rgb + spec * specColor * cLightColor.a);`

I believe that this is wrong, and when brightness<1 specular is too dim, and when brightness>1 it is too bright.

I've checked deferred and forward, haven't checked prepass(but it has hacky specular anyway :) ) and PBR, maybe PBR need EffectiveSpecularIntensity? Otherwise changing Batch.cpp to GetSpecularIntensity() might be a best solution.

**Comment by weitjong** [comment]
@eugeneko I think this one is yours :smile:

**Comment by weitjong** [comment]
Related to issue #242 and commits: 094006ef9145830bc469c93289b99e4a44eba8f9 and d534efd7c974ad4a59e4f08cf1996f06e99da655.

**Comment by JSandusky** [comment]
> Then in shader, specular is multiplied by both cLightColor.rgb and cLightColor.a:
finalColor = diff * lightColor * (diffColor.rgb + spec * specColor * cLightColor.a);
I believe that this is wrong, and when brightness<1 specular is too dim, and when brightness>1 it is too bright.

They're used separately within the shader so multiplying them separately makes sense. That code does look appropriate. 

Is there an unexpected interplay that adjusting *Specular Intensity* independently of brightness or the *material specular power* (it's the alpha channel of MatSpecColor) doesn't work well?

> I've checked deferred and forward, haven't checked prepass(but it has hacky specular anyway :) ) and PBR, maybe PBR need EffectiveSpecularIntensity? Otherwise changing Batch.cpp to GetSpecularIntensity() might be a best solution.

It doesn't use it, everything is shiny.
