### ISSUE TITLE
Texture2D::SetData on dynamic texture causes black texture

### ISSUE THREAD

**Issue by andrekoehler** [urho3d/Urho3D#2253]
I modified the RenderToTexture example to test how I can write CPU-generated pixels to a texture.
Before:
https://github.com/urho3d/Urho3D/blob/1.7/Source/Samples/10_RenderToTexture/RenderToTexture.cpp#L183-L203

After:
```
SharedPtr<Texture2D> renderTexture(new Texture2D(context_));
//renderTexture->SetSize(1024, 768, Graphics::GetRGBFormat(), TEXTURE_RENDERTARGET);
renderTexture->SetSize(128, 128, Graphics::GetRGBFormat(), TEXTURE_DYNAMIC);
unsigned char buffer[128 * 128 * 3];
// generate white pixels 0xFFFFFF
for (int i = 0; i < (128 * 128 * 3); ++i) {
	buffer[i] = 0xFF;
}
renderTexture->SetData(0, 0, 0, 128, 128, buffer);
renderTexture->SetFilterMode(FILTER_BILINEAR);

...

//RenderSurface* surface = renderTexture->GetRenderSurface();
//SharedPtr<Viewport> rttViewport(new Viewport(context_, rttScene_, rttCameraNode_->GetComponent<Camera>()));
//surface->SetViewport(0, rttViewport);
```

The expected outcome is a plane with a 128x128 texture that contains only white pixels, but this result can only be observed with the Direct3D9 backend. When compiling the same code for the OpenGL or Direct3D11 backends, the plane is black instead of white.

Direct3D9:
correct:
![d3d9](https://user-images.githubusercontent.com/22099714/35820383-b6d6f8a8-0aa5-11e8-879a-9eaa23a8850e.png)

Direct3D11:
wrong:
![urho3d_d3d11](https://user-images.githubusercontent.com/22099714/35820400-c3ed0cc6-0aa5-11e8-8f93-389987e0f927.png)

OpenGL:
wrong:
![urho3d_opengl](https://user-images.githubusercontent.com/22099714/35820405-c9b3c3ca-0aa5-11e8-9cb8-358b64be16d2.png)

I verified that this issue is not caused by device loss because Texture2D::IsDataLost() returns false for each frame in the sample's update loop.

**Comment by JSandusky** [comment]
On DX11 the RGB format is RGBA.

https://github.com/urho3d/Urho3D/blob/0631979496f920c14a889367a48dab9cfdf9a96c/Source/Urho3D/Graphics/Direct3D11/D3D11Graphics.cpp#L1960

IIRC, that's because DX11 completely axed 16 and 24 bit formats (except from the BC# family).

**Comment by andrekoehler** [comment]
@JSandusky Oh you are right, Texture::GetRowDataSize correctly returns width * 4 for RGB Format on D3D11, but even if I create a 32bpp bitmap instead of a 24bpp one, I still get a black screen:
```
renderTexture->SetSize(128, 128, Graphics::GetRGBFormat(), TEXTURE_DYNAMIC);
unsigned char buffer[128 * 128 * 4];
for (int i = 0; i < (128 * 128 * 4); ++i) {
	buffer[i] = 0xFF;
}
renderTexture->SetData(0, 0, 0, 128, 128, buffer);
```

I enabled DirectX debugging and noticed the following warning is printed once per frame:

> D3D11 WARNING: ID3D11DeviceContext::DrawIndexed: The Pixel Shader unit expects a Sampler to be set at Slot 0, but none is bound. This is perfectly valid, as a NULL Sampler maps to default Sampler state. However, the developer may not want to rely on the defaults.  [ EXECUTION WARNING #352: DEVICE_DRAW_SAMPLER_NOT_SET]

But it might not be relevant because it even appears if I do not use my generated texture by commenting out the line:
`renderMaterial->SetTexture(TU_DIFFUSE, renderTexture);`

**Comment by JSandusky** [comment]
It's all related to: #1153 and #2165

The dynamic cases need to get the mip levels forced to 1 for DX11 at least. Haven't checked OGL yet.

**Comment by andrekoehler** [comment]
I found a workaround for versions before that patch:
Just call
`Texture::SetNumLevels(1);`
 before calling
`Texture2D::SetData(unsigned, ...)`
