### ISSUE TITLE
ReleaseAllResources does not release all unused resources pre one call

### ISSUE THREAD

**Issue by UnickSoft** [urho3d/Urho3D#2261]
I need to call ResourceCache::ReleaseAllResources several time to release all unused resources (force is false). I have this problem with materials. I think materials have reference to texture. After first call ReleaseAllResources releases only material, but texture and techniques are in cache.

In my program i add loop to fix it (psevdocode):

```
int prevResNum = 0;
int resNum = GetResNumInCache(cache); // Count total number of resources in cache
do
{
    prevResNum = resNum;
    cache->ReleaseAllResources(false);
    resNum = GetResNumInCache(cache);
} whle (resNum != prevResNum)
```

Maybe you need to add the same code to ReleaseAllResources method.

**Comment by eugeneko** [comment]
Good catch!

**Comment by weitjong** [comment]
@UnickSoft I changed the loop control logic slightly. I think it should be sufficient to solve the issue.
