### ISSUE TITLE
Missing include in UI/ScrollBar.h

### ISSUE THREAD

**Issue by etherealvisage** [urho3d/Urho3D#2262]
Hi,

Just noticed that the file `UI/ScrollBar.h` doesn't have the correct includes in it. The class `Urho3D::ScrollBar` inherits from `Urho3D::BorderImage`, but the only include in `UI/ScrollBar.h` is for `UI/UIElement.h`. Changing it to `UI/BorderImage.h` allows you to include only `UI/ScrollBar.h` without other UI includes. (Or, as in my case, order them alphabetically when you only want a few. :-) )

**Comment by weitjong** [comment]
I believe it was just an oversight.

**Comment by etherealvisage** [comment]
Sounds about right! I figure someone switched the base class around and forgot to update the include. Thought I'd let you know about the problem, at least. Caused me a few minutes' grief while blaming my own code for the compile error. :-)

**Comment by weitjong** [comment]
Thanks for pointing this out.
