### ISSUE TITLE
Small issue of Vector::MoveRange

### ISSUE THREAD

**Issue by windhill108** [urho3d/Urho3D#2263]
problem at the for condition.
it runs with no problem since unsigned overflow(underflow).
but acts weirdly.

**Comment by weitjong** [comment]
If you have looked at enough Urho code base then you would find this kind of for loop condition is quite common in Urho and there is nothing wrong about it as unsigned underflow is not UB in C/C++.

**Comment by windhill108** [comment]
wow, I see.
