### ISSUE TITLE
update assimp to support glTF2

### ISSUE THREAD

**Issue by yushli** [urho3d/Urho3D#2268]
according to https://discourse.urho3d.io/t/nice-article-on-gltf-2-0-by-godot-devs/3420, it is good to have glTF2 support in Urho3D. Assimp already has that support. Maybe it is time to add this feature?

**Comment by weitjong** [comment]
Thanks for bringing this up.

**Comment by weitjong** [comment]
This will take some time because I am redoing the integration part with Assimp's own CMake build scripts. Hopefully it will pay off in the future when syncing future upstream's upgrades.

**Comment by yushli** [comment]
Thanks for looking into this feature request.

**Comment by weitjong** [comment]
Sorry for the delay. The updated library can be found in the `update-assimp` dev branch now. Please check out and test it locally, if you have time. Otherwise, the branch will be merged after it passes all the CI build test.

**Comment by weitjong** [comment]
All CI passed now. If there is no objection then the development branch will be merged at the soonest.
