### ISSUE TITLE
Cmake build on debian for Android, problem with thirdparty dependency SDL

### ISSUE THREAD

**Issue by SimonScholl** [urho3d/Urho3D#2269]
I am trying to build urho3D for android on debian 

as cmake starts building SDL i get the following error:
/urho3d/Source/ThirdParty/SDL/src/cpuinfo/SDL_cpuinfo.c:73:22: fatal error: sys/auxv.h: No such file or directory
 #include <sys/auxv.h>
                      ^
compilation terminated.

I should mention, that i am trying to build it into docker, here is the related RUN statement:

RUN git config --global http.sslVerify false && \
    git clone --branch master --depth 1 https://github.com/urho3d/Urho3D.git urho3d && \
    cd urho3d && \
    mkdir build && cd build && \
    cmake .. -G"Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="CMake/Toolchains/Android.cmake" -DANDROID_ABI=armeabi-v7a -DANDROID_NATIVE_API_LEVEL="android-19" -DANDROID_TOOLCHAIN_NAME=arm-linux-androideabi-4.9 && \
    make && \
    make install && \
    make clean

Maybe someone has or had an equal issue can help.

**Comment by weitjong** [comment]
I suspect something is wrong with you setup. It is not clear to me from the above where did you install the Android NDK. Note that when you cross-compiling to target Android platform, the compiler toolchain and the system root are provided by the NDK.

**Comment by SimonScholl** [comment]
Okay thank you for your fast response, i installed my Android SDK as well as my Android NDK and setup some Env vars for them via 
ENV ANDROID_HOME=/opt/android-sdk
ENV ANDROID_NATIVE_API_LEVEL=android-19
ENV ANDROID_NDK=/opt/android-ndk-r14
ENV PATH=$PATH:/opt/android-sdk/tools:/opt/android-sdk/platform-tools:/opt/android-ndk-r14

i install both via
# Setup android sdk && android list sdk --all --extended
RUN wget https://dl.google.com/android/repository/tools_r25.2.3-linux.zip --no-check-certificate && \
  unzip -qq tools_r25.2.3-linux.zip  && \
  rm tools_r25.2.3-linux.zip  && \
  mkdir $ANDROID_HOME  && \
  mv tools $ANDROID_HOME/. &&\
  (echo y |  android update sdk --no-ui --all --filter platform-tools,android-19,build-tools-19.1.0,android-21,build-tools-21.1.0 )

# Setup android ndk
RUN wget https://dl.google.com/android/repository/android-ndk-r14-linux-x86_64.zip --no-check-certificate && \
  unzip -qq android-ndk-r14-linux-x86_64.zip  && \
  rm android-ndk-r14-linux-x86_64.zip  && \
  mv android-ndk-r14 /opt/.

okay that confused me cause there is already a toolchain in the cmake folder of the project.

**Comment by SimonScholl** [comment]
Okay little update i used your shell script and was able to build urho3d from shell of my docker container :)

**Comment by weitjong** [comment]
Glad to hear that.
