### ISSUE TITLE
2D support in editor.

### ISSUE THREAD

**Issue by aster2013** [urho3d/Urho3D#227]

**Comment by billyquith** [comment]
@aster2013
>  I prefer to make a Qt based Urho3D Editor, but it is a large project for us.

I think this is a more profitable use of time for a complex scene editor than an internal editor. I still think an internal editor is useful for  in-game debugging, quick iteration, scene navigation, but you have to spend a lot of time on building a widget system, designer, etc. Qt has a very strong IDE now, great layout tools, great widget set. Also, using scripting languages for these type of applications with multiple users means runtime bugs happen more often.
