### ISSUE TITLE
Support Rectange Area light?

### ISSUE THREAD

**Issue by ghost** [urho3d/Urho3D#2277]
Hi Dev,

I am using Urho3D and i want to implement Rectangle Area Light in my project.
It will be nice if Devs can support to add it into Urho3D. Or I may try to do it myself.
Is it possible to add Rectangle Area Light to Urho3D right?
Sorry, I am new on this.

**Comment by dragonCASTjosh** [comment]
Adding rectangle area lights shouldn't be to difficult, especially if you take the same root as frostbite. Currently the sphere and tube lights follow the same structure of frostbite and unreal. The frostbite paper provides code examples are other light shapes if you wish to give it a try.

**Comment by TamNT27** [comment]
Can you give me the link for reference? Many thanks

**Comment by dragonCASTjosh** [comment]
https://seblagarde.files.wordpress.com/2015/07/course_notes_moving_frostbite_to_pbr_v32.pdf
