### ISSUE TITLE
bugprone-undefined-memory-manipulation

### ISSUE THREAD

**Issue by weitjong** [urho3d/Urho3D#2282]
This is the last failed check using Clang-Tidy 6.0 in our dev branch.

https://travis-ci.org/urho3d/Urho3D/jobs/358458226

```
/home/travis/build/urho3d/Urho3D/Source/Urho3D/Core/Variant.cpp:136:9: warning: undefined behavior, destination object type 'Urho3D::VariantValue' is not TriviallyCopyable [bugprone-undefined-memory-manipulation]
/home/travis/build/urho3d/Urho3D/Source/Urho3D/Core/Variant.cpp:136:9: warning: undefined behavior, source object type 'const Urho3D::VariantValue' is not TriviallyCopyable [bugprone-undefined-memory-manipulation]
/home/travis/build/urho3d/Urho3D/Source/Urho3D/Graphics/Batch.cpp:658:9: warning: undefined behavior, source object type 'const Urho3D::Matrix3x4' is not TriviallyCopyable [bugprone-undefined-memory-manipulation]
```

Open it as an issue here to discuss whether we should fix them or just dismiss them as Urho3D lib seems to be working fine in all the supported platforms.

**Comment by eugeneko** [comment]
> undefined behavior, destination object type 'Urho3D::VariantValue' is not TriviallyCopyable
> undefined behavior, source object type 'const Urho3D::VariantValue' is not TriviallyCopyable

Should be safe to ignore. Technically it's not TriviallyCopyable because of deleted ctor, but in fact it is: all underlying types are TriviallyCopyable .

> undefined behavior, source object type 'const Urho3D::Matrix3x4' is not TriviallyCopyable

Same here. Matrix3x4 is not TriviallyCopyable just because of SSE copying instead of just copying.
BTW, I never understood the benefit of using SSE in Urho. Maybe for occlusion culling, IDK.

**Comment by weitjong** [comment]
Yeah. I came to the same conclusion last night. The class is almost POJO and is trivially copyable, if not due to user-defined copy ctor and user-defined assignment operator.

So, will add NOLINT marker for these 3 occurrences but the check itself stays enabled.

**Comment by weitjong** [comment]
I meant to say POD instead of POJO, obviously 😁

**Comment by cadaver** [comment]
The SSE math was contributed by clb when optimizing for his Emscripten test suite; don't think I ever profiled the results before / after.

**Comment by weitjong** [comment]
Actually if the memcpy works fine in these occurrences then logically it should work fine everywhere. And if so, doesn’t it make more sense we convince the compiler the class is indeed TriviallyCopyable by removing the offending user-defined methods?

**Comment by weitjong** [comment]
Upgrading to Clion 2018.1 and instantly regretting it. Not because it is bad or anything, but because it's a major upgrade and somehow the new version has messed up my local setup for Clang-Tidy inspection and I am not able to reconfigure it to work as I like it before. Falling back to use "clang-tidy" on CLI now. Fortunately, I only left with this one rule to check.

Anyway, removing the two offending methods for the `Matrix3x4` class does the trick and it makes the `memcpy` call in the `Batch` class valid (i.e. not being flagged up as UB anymore). Running "rake make test" showed there is no regression after this change. However, I don't have time to check/profile whether the compiler generates better/faster code for copying or not though. And, I don't want to open another can of worms. If we go this route then probably we have to profile properly and also investigate other Math/POD classes too.

So, as per original plan, I will just add the "NOLINT" marker and close this issue.
