### ISSUE TITLE
RenderPathCommand "quad" output is upside-down when using OpenGL backend

### ISSUE THREAD

**Issue by andrekoehler** [urho3d/Urho3D#2284]
I use UrhoSharp 1.8.93 where the backend (D3D11 or OpenGL) can be toggled by setting UseDirectX11 to true or false in the ApplicationOptions.

I render my scene to a texture and then use a custom render path to draw that texture onto the screen:
```
<renderpath>
  <command type="quad" vs="CopyFramebuffer" ps="CopyFramebuffer">
    <texture unit="diffuse" name="MULTISAMPLED_RENDER_TARGET" />
  </command>
</renderpath>
```

To my understanding there should not be any major differences between the backends, but it seems like using OpenGL draws the texture upside-down to the screen:

(The stuff in the upper-left corner can be ignored because those are UI elements)

UseDirectX11 = false: (This is upside-down)
![opengl](https://user-images.githubusercontent.com/22099714/38091892-13188e62-3367-11e8-8825-18dc0a746752.jpg)

UseDirectX11 = true: (This is correct)
![d3d11](https://user-images.githubusercontent.com/22099714/38091910-1ee87770-3367-11e8-9a45-c236a3f4707b.jpg)

The same thing happens when I draw a static texture resource instead of a render target:
```
<renderpath>
  <command type="quad" vs="CopyFramebuffer" ps="CopyFramebuffer">
    <texture unit="diffuse" name="Textures/Arrow.png" />
  </command>
</renderpath>
```

UseDirectX11 = false: (upside-down)
![opengl](https://user-images.githubusercontent.com/22099714/38092353-58761afa-3368-11e8-87ce-4f8e64ad0166.jpg)

UseDirectX11 = true: (correct)
![d3d11](https://user-images.githubusercontent.com/22099714/38092379-63134cee-3368-11e8-8b7a-2b298231d5f9.jpg)

Textures/Arrow.png:
![arrow](https://user-images.githubusercontent.com/22099714/38092404-6e46e53a-3368-11e8-8da3-dbfef3f4729b.png)

**Comment by weitjong** [comment]
I think you should raise this bug to UrhoSharp instead of us. For sure, all our samples work the same way across all the platforms whether it is on Direct3D or OpenGL. If you have read our documentation (https://urho3d.github.io/documentation/HEAD/_conventions.html) or have looked at our OpenGL source code, you will see a lot of places where vertical flip operation are being done to cater for the difference in handedness. By default OpenGL is right-handed.

**Comment by andrekoehler** [comment]
No this bug is not caused by the UrhoSharp wrapper, it also occur when using the latest version of native Urho3D: https://github.com/urho3d/Urho3D/issues/2287

**Comment by weitjong** [comment]
May be I have not explained it better, so let me try that again. At the higher layer Urho3D provides abstraction to shield us from the fact that Direct3D is a left-handed graphics system, while OpenGL a right-handed one. At that layer switching graphics backend does not apparently produce difference result. However, when you go below this abstraction layer then, of course, you have to take care the differences yourself by adding the logic to vertically flip the texture or UV.

**Comment by eugeneko** [comment]
@weitjong There _is_ some code that seems to be written for flipping.
Why it doesn't work?..
https://github.com/urho3d/Urho3D/blob/6d08bcd8c00cc600b0c73315aa61dd7d5c6dec1d/Source/Urho3D/Graphics/View.cpp#L2143

**Comment by weitjong** [comment]
There are a number of places where you can find the flipping logic. I am not sure why you just narrow in to this particular one, which by the way would does nothing when the corresponding camera flag is not set to flipped.

**Comment by andrekoehler** [comment]
I found a workaround: Display the rendered texture using a full-screen UI BorderImage. This works the same on OpenGL and D3D11 backends.
