### ISSUE TITLE
RenderPathCommand "quad" output is upside-down when using OpenGL backend

### ISSUE THREAD

**Issue by andrekoehler** [urho3d/Urho3D#2287]
To reproduce, add the following lines of code to the beginning of the "StaticScene::Start" method:
https://github.com/urho3d/Urho3D/blob/master/Source/Samples/04_StaticScene/StaticScene.cpp#L52
```
XMLFile *xmlFile = new XMLFile(GetContext());
xmlFile->FromString("<renderpath><command type=\"quad\" vs=\"CopyFramebuffer\" ps=\"CopyFramebuffer\"><texture unit=\"diffuse\" name=\"Textures/LUTIdentity.png\" /></command></renderpath>");
GetSubsystem<Renderer>()->GetDefaultRenderPath()->Load(xmlFile);
```

This sets the default render path to use a single render command which draws a quad with a texture that is part of the CoreData assets package.

The texture looks like this:
![lutidentity](https://user-images.githubusercontent.com/22099714/38102550-e25d8044-3383-11e8-9cd6-6abacfd303b0.png)

When compiling the modified sample with URHO_D3D11, the output looks like expected:
![d3d11](https://user-images.githubusercontent.com/22099714/38102604-0364eb10-3384-11e8-8b06-d1f75a91b283.png)

However when compiling with URHO_OPENGL, the output is upside-down (wrong):
![opengl](https://user-images.githubusercontent.com/22099714/38102638-1b31a9cc-3384-11e8-8358-1afeac45b1e1.png)

This was tested with Urho commit 7508b9003bd6c9c6fa2e99ec527c8df30b5f1049

**Comment by weitjong** [comment]
I would say at that layer it works as intended.

**Comment by andrekoehler** [comment]
I found some documentation that might be related:

"To ensure similar UV addressing for render-to-texture viewports on both APIs, on OpenGL texture viewports will be rendered upside down."

SOURCE: https://urho3d.github.io/documentation/HEAD/_a_p_i_differences.html
