### ISSUE TITLE
Your repo includes copyrighted Microsoft content?

### ISSUE THREAD

**Issue by equin0x80** [urho3d/Urho3D#2288]
bin/Data/Textures/UI.png  -- this contains various Microsoft material such as the standard "hourglass" cursor from earlier versions of Windows.

**Comment by eugeneko** [comment]
Could you please reference to specific icon of specific version of Windows?
Icon in Urho looks like Windows one, but it's not exactly the same (as far as I could see).

**Comment by thesquib** [comment]
The cursor from early versions of Windows is not exactly the same. What other material are you referring to?

**Comment by equin0x80** [comment]
A Win3.x screenshot: https://guidebookgallery.org/pics/gui/settings/mouse/winnt31-2-1.png
The hourglass and the arrow (top left of your UI.png) are clearly copied, even if a very few pixels may have been changed. Legally I suppose they would be "derivative works", which still violate copyright. Not sure if anything is copied beyond those two icons, but it's worth checking it out because someone who rips from one source may equally rip from another source.

**Comment by weitjong** [comment]
Just like Microsoft ripped Apple Lisa wait icon, I suppose.

**Comment by eugeneko** [comment]
We definetely need some legal guys here.

> Legally I suppose they would be "derivative works", which still violate copyright

The idea to use arrow as idle cursor or hourglass as wait cursor can't be patented.
I doubt it's possible to talk about "derivative works" in context of 16x16 grayscale images.
1000 of independently painted 16x16 grayscale houglasses would all be similar. It doesn't mean they derivate from each other.

**Comment by equin0x80** [comment]
eugeneko, 1. this is about copyrights, not patents, which are a COMPLETELY different thing, 2. can you *possibly* look at the two images and believe that they were created independently, without copying?! -- It's fine if you guys say "we don't care about this because Microsoft won't bother to sue", but it's trashy to copy other people's work and at least now you're aware that you've done so.

**Comment by eugeneko** [comment]
So, the only option is... @cadaver, could you recall where did you take the icon?
https://github.com/urho3d/Urho3D/commit/902dfd4a13104ce14300c5121b724c811b343399#diff-eed95d5751577b8df460c00f9ca3f078

> can you possibly look at the two images and believe that they were created independently, without copying?!

Without Ctrl+C & Ctrl+V? Easily.
Without looking at somebody's else work?
Meh, almost everything is made by copying and recombinding something that already exists.
I hope some game engines have cube model. Does it mean that Urho's cube violates their copyrights?

**Comment by thesquib** [comment]
Microsoft didn't invent the mouse cursor or the hourglass. This issue should be closed as this is clearly a troll.

**Comment by Modanung** [comment]
@thesquib is probably right, can I [eat](https://www.youtube-nocookie.com/embed/S50oirJzrOI) the copyright troll?

I _could_ create an alternative UI texture if we conclude @equin0x80's point to be valid.

**Comment by weitjong** [comment]
@Modanung I am hoping you would ask. The existing cursors are ugly anyway. In fact our coin spinner in the our sample looks more decent. I reckon we can easily use 2D sprites to make our cursor animated.

**Comment by cadaver** [comment]
I pixeled the original UI icons in GrafX2 drawing program. I clearly was inspired by the Microsoft icons (there are not many ways to draw a nice angled arrow for the cursor, and that's how I've used to draw it, even fror my C64 graphics editors beforehand) but didn't actually lift the icons from anywhere.

**Comment by boberfly** [comment]
Does it really matter? This is pretty pedantic imo...

**Comment by Modanung** [comment]
I started on an SVG version based on the current UI. That way it can be easily upscaled for higher resolutions.

> ![SVG UI](https://www.LucKeyProductions.nl/images/UI.svg)

**Comment by Modanung** [comment]
...which currently looks like:
![WIP](https://www.luckeyproductions.nl/images/UrhoUIsvg.png)
