### ISSUE TITLE
Useless pass PBRDeferred.xml ?

### ISSUE THREAD

**Issue by darwikey** [urho3d/Urho3D#2291]
Hi,
I have noticed something quite strange in the render path "PBRDeferred.xml",
there is a : 
`<command type="scenepass" pass="base" vertexlights="true" metadata="base" />`
before the deferred pass. I might be wrong, but it shouldn't be here in deferred and moreover it's not present in the render path "Deferred.xml".
This pass is heavy to compute and it could be a good thing if we could get rid of it :)

**Comment by JSandusky** [comment]
It should be there. The base pass is used for writing the ambient (zone) and IBL into the viewport.

You can modify the shaders and render-path if you want to get rid of it.

**Comment by weitjong** [comment]
Feel free to reopen.
