### ISSUE TITLE
Single VAO

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#2292]
Currently Urho3D uses single global VAO

OGLGraphics.cpp
```
// Create and bind a vertex array object that will stay in use throughout
unsigned vertexArrayObject;
glGenVertexArrays(1, &vertexArrayObject);
glBindVertexArray(vertexArrayObject);
```
I founded benchmark single VAO vs multiple VAOs http://www.openglsuperbible.com/2013/12/09/vertex-array-performance/

(May be single global VAO is reason why constant buffers does not improve performance currently)

We can use single global VAO for dynamic geometry (DebugRenderer), but I have no idea where store VAO names for Urho's drawables

**Comment by cadaver** [comment]
At least like the way Graphics & SetVertexBuffer is currently done and how it ties to shaders, it's not possible to just store a VAO per drawable. 

For example, in instancing two vertex streams are combined from different VBOs, and the vertex attribute indices may change per each shader.

(Furthermore, the drawable class is an API-independent construct, while VAOs only exist on OpenGL)

Don't think it's impossible, but the way how it would be need to be done on the current API would be to have a management system inside Graphics class, to create VAOs as needed.

**Comment by eugeneko** [comment]
Maybe some clever real-time caching would help?

вс, 1 апр. 2018 г. в 18:29, Lasse Öörni <notifications@github.com>:

**Comment by cadaver** [comment]
Yes, it'd likely become some hashing-based system in practice, ie. look for VAO combination hash for the current shader signature and vertex buffers, create new if doesn't exist, otherwise just bind existing. Also needs to handle invalidation when VBOs are destroyed.

Urho lacks nice torture scenes for testing though, as any of the examples don't stress the binding API by having tons of different objects approximating a real game scene.

**Comment by 1vanK** [comment]
Currently OpenGL is slower than DirectX in every standard Urho's samples. So we can use standart samples for testing. For example dota 2 show same fps in OpenGL and Dx11 modes, so I believe it is possible to optimize OpenGL build.

**Comment by cadaver** [comment]
In my experience the (fragment) shaders just run slower on OpenGL, so you can have a very simple scene but as long as it e.g. has shadow sampling, it's slower. And don't know what can be done about that.

This is already old (2007), but Aras P. from Unity did testing with similar conclusions:
https://aras-p.info/blog/2007/09/23/is-opengl-really-faster-than-d3d9/

**Comment by JSandusky** [comment]
> For example dota 2 show same fps in OpenGL and Dx11 modes, so I believe it is possible to optimize OpenGL build.

Just an FYI, Valve is the origin of the whole *use a single VAO* thing. There was a presentation (slides should be out there somewhere) where they fervently insisted they couldn't get multiple VAOs to perform.

**Comment by 1vanK** [comment]
https://developer.nvidia.com/sites/default/files/akamai/gamedev/docs/Porting%20Source%20to%20Linux.pdf

```
Vertex Attribute Objects (VAOs)
Good mapping for D3D (seductive!)
Slower than glVertexAttribPointer on all implementations
Recommendation: Skip it
```

Hmm, Vertex Attribute Objects is same as Vertex Array Object?

**Comment by 1vanK** [comment]
> Urho lacks nice torture scenes for testing though, as any of the examples don't stress the binding API by having tons of different objects approximating a real game scene.

As far as I remember @gleblebedev has ported level from Half-Life 2: Lost Coast. Also I have ported Viking's Village https://assetstore.unity.com/packages/essentials/tutorial-projects/viking-village-29140 somewhere on my computer. But I think it is not fully legal xD

**Comment by JSandusky** [comment]
> Hmm, Vertex Attribute Objects is same as Vertex Array Object?

Yes, same thing.
