### ISSUE TITLE
Reset Animations In A Scene

### ISSUE THREAD

**Issue by tkgamegroup** [urho3d/Urho3D#2293]
Hi, I'm using a viewport to render a texture through a camera of a scene. In the scene, there is a particle emitter, how can I reset that particle emitter? What I do now is to reload the scene, which is too expensive.

**Comment by eugeneko** [comment]
What if you call `SetNumParticles(0)` and then revert it back?
A bit ugly, maybe we need shortcut for this.

**Comment by JSandusky** [comment]
Use `ParticleEmitter::Reset` on your particle emitters.

    particleEmitter_->Reset();

**Comment by eugeneko** [comment]
/facepalm/ I have no idea how could I have missed it.
I definitely dislike browsing Git via browser when looking for answers.

вт, 3 апр. 2018 г. в 22:13, Jonathan Sandusky <notifications@github.com>:

**Comment by tkgamegroup** [comment]
Nice, I will try that.
