### ISSUE TITLE
Color::TRANSPARENT #undef TRANSPARENT

### ISSUE THREAD

**Issue by Enhex** [urho3d/Urho3D#2298]
`#undef TRANSPARENT` in `Color.h` may be used before `#include <windows>` is used, letting Windows' `TRANSPARENT` define shadow `Color::TRANSPARENT`.

Perhaps the `#undef` should be used directly after the `windows.h` include?

Or perhaps put the `#undef` outside `Color.h`'s include guard?

**Comment by chenjie199234** [comment]
#undef TRANSPARENT in color.h is useless!

**Comment by Stinkfist0** [comment]
Just an idea how I decided to handle these problems for my little project:
https://github.com/Stinkfist0/PoGoCmp/blob/master/src/Lib/MinimalWin32.h
Usage:
https://github.com/Stinkfist0/PoGoCmp/blob/master/src/Lib/Utf8.cpp#L12

**Comment by weitjong** [comment]
Could you try my patch at #2308?

**Comment by 1vanK** [comment]
>> #undef TRANSPARENT in color.h is useless!

yes, it does not work and can be deleted

**Comment by 1vanK** [comment]
defining "#define NOGDI" instead "#undef TRANSPARENT" works for me (windows.h included later?)
