### ISSUE TITLE
FileWatcher does not respond to deleted files on windows

### ISSUE THREAD

**Issue by TrevorCash** [urho3d/Urho3D#2299]
FileWatcher does not seem to pickup on changes when a file is deleted on windows. It does respond to new files and modified files.

**Comment by TrevorCash** [comment]
changing
` if (record->Action == FILE_ACTION_MODIFIED || record->Action == FILE_ACTION_RENAMED_NEW_NAME)
`
to

`                if (record->Action == FILE_ACTION_MODIFIED || record->Action == FILE_ACTION_RENAMED_NEW_NAME || record->Action == FILE_ACTION_REMOVED)`

on line 262 of FileWatcher.cpp fixed the issue for me.

**Comment by SuperWangKai** [comment]
Also, it does not respond to adding. We need to add `FILE_ACTION_ADDED` in the condition.

**Comment by TrevorCash** [comment]
If I remember right - FILE_ACTION_MODIFIED will be called if a file is added.  but is not very descriptive of the initial adding event.

**Comment by SuperWangKai** [comment]
I've tested on Windows, If I remember it right, after we enabled hot reloading resource, if we create a new file under e.g. "bin/Data/", no `E_FILECHANGED` event will be sent.
