### ISSUE TITLE
Save rendered screen to image automatically?

### ISSUE THREAD

**Issue by TamNT27** [urho3d/Urho3D#2303]
Hi Dev, 
I want to save rendered screen to images automatically. (I change a little bit object's rotation for each image, and i want to save rendered image once time.

Problem is all images are same, (they are not updated for each object's rotation).
` /// I change object's rotation and call below code many times (in a loop)
               var obj = cmd.Payload.Object;
                renderTexture = new Texture2D();
                renderTexture.SetSize(cmd.Payload.ImageSize.Width, cmd.Payload.ImageSize.Height, Graphics.RGBFormat, TextureUsage.Rendertarget);
                renderTexture.FilterMode = TextureFilterMode.Bilinear;

                renderTexture.RenderSurface.SetViewport(0, sceneModel.CreateViewport());
                renderTexture.RenderSurface.UpdateMode = RenderSurfaceUpdateMode.Manualupdate;

                Renderer.QueueRenderSurface(renderTexture.RenderSurface);
                Utils.ImageExporter.SaveTo(renderTexture, cmd.Payload.ExportFormat, cmd.Payload.ImageOutputPath, cmd.Payload.SingleImage, cmd.Payload.ShowMessage, cmd.Payload.ObjectName, cmd.Payload.SettingName);`

**Comment by weitjong** [comment]
Please use the forum for question.
