### ISSUE TITLE
Use base64 for Buffer type output in XML serialization

### ISSUE THREAD

**Issue by JSandusky** [urho3d/Urho3D#2304]
Presently Buffers are written into XML as a space delimited list of the byte value:

`<variant hash="1744159084" type="Buffer" value="99 99 255 255 99 99 ... 99" />`

This gets unwieldly really fast. Embedding a 128x128 png image @ 36kb turns a 64kb scene into 926kb.

The same data written in base64 comes out to 135kb for the same 64kb scene.

As far as I could tell it's just historical and base64 was never used until Tiled support in Urho2D came along.

- Note: image embedding use-case is a file preview-thumbnail.

**Comment by weitjong** [comment]
That base64 decoding is only added to the code base when aster2013 contributed the work to parse the TMX tile format (which is not our own). That is, in Urho3D code base we have never serialized anything out using base64 encoding before. However, I agree with you that it makes a lot of sense to do that.
