### ISSUE TITLE
Editor freezes when scene object is inside camera

### ISSUE THREAD

**Issue by andrekoehler** [urho3d/Urho3D#2306]
After upgrading from the 1.6 editor to the 1.7 editor I noticed the editor always freezed for multiple seconds or even minutes when I was looking at a specific object in the scene. I compiled a debug build of the master branch (https://github.com/urho3d/Urho3D/commit/218e4d7592cf8681001e795cac6672fb29fb156a) and paused the editor in Visual Studio. It seems like the editor is always stuck in the Ray::HitDistance method in _while (indices < indicesEnd)_
I have no idea to find out which line of the action script is executing tough...

![editor freeze](https://user-images.githubusercontent.com/22099714/38990814-fb9cea50-43db-11e8-9a3e-bc687427fbdb.png)

The object that definitely causes this issue has 136k+72k triangles in Blender (Golf Putter Shaft + Head). The issue also occurs if I load only that object into the editor without loading a scene before. The issue only occurs when rotating the editor camera (middle and right mouse button both cause the issue). My guess is that one of the algorithms in the editor does not scale well with high-poly objects.

I use the x86 OpenGL backend of the editor on Windows 10 x64.
I re-verified that the same object does not cause any freezes in the 1.6 Editor.

**Comment by weitjong** [comment]
Can you do a git-bisect to pinpoint exactly the commit that causing the regression?

**Comment by eugeneko** [comment]
@weitjong Let me guess...
This?
https://github.com/urho3d/Urho3D/commit/1ce189361d37af7e699e13157e7c2da43134701b#diff-58cf103e1734ef9d88f2c4115b18f192R1806

**Comment by weitjong** [comment]
If you have a gut feeling that is the one then you can quickly test it by building a version with just before that commit and another version with it included. Once you have confirmed that is the culprit then we can help to zoom in to find the root cause. Thanks.

**Comment by weitjong** [comment]
@eugeneko Just realize it was you instead of OP :)

**Comment by eugeneko** [comment]
@weitjong I can't test things right now, but..
If it doesn't help to comment out the block above, the second suspected commit is this
https://github.com/urho3d/Urho3D/pull/2115/files
I haven't managed to find the possible root cause tho.

**Comment by andrekoehler** [comment]
@eugeneko I built the commit 1ce189361d37af7e699e13157e7c2da43134701b and the one before it (8d7b4b0b5839bf99e6efc49d3288a0dd59b04e3c) but the editor works without freezing in both versions.

**Comment by eugeneko** [comment]
@andrekoehler Try the version before this PR too, please.
https://github.com/urho3d/Urho3D/pull/2115/files

**Comment by andrekoehler** [comment]
@eugeneko The PR you mentioned can not be the culprit because it was merged AFTER the 1.7 release but the issue already occurs with 1.7

**Comment by eugeneko** [comment]
Ah, damn, really. I'm out of ideas for now. I'll try to reproduce this issue later.

**Comment by weitjong** [comment]
Rather than guessing, use the git-bisect to systematically find the offending commit.

**Comment by andrekoehler** [comment]
I got it now. @eugeneko was right, the faulty commit is 1ce189361d37af7e699e13157e7c2da43134701b. 8d7b4b0b5839bf99e6efc49d3288a0dd59b04e3c is good, I just had to make sure to copy \bin\Data\Scripts\Editor\*.as to the build output \build\bin\Data\Scripts\Editor\*.as because CMake/Visual Studio do not update these files on an incremental build.

**Comment by andrekoehler** [comment]
I created a test model with almost 200k polygons and converted it to Urho format and added it to a scene so you can reproduce this issue.
[HighPolyTestObject.zip](https://github.com/urho3d/Urho3D/files/1932184/HighPolyTestObject.zip)

I can reproduce the issue 100% of the time by selecting the object, pressing middle mouse button to orbit around and then look at it from above while holding the middle mouse button. Looking at the object from below or from the side does not cause performance issues, only looking at it from above.

**Comment by andrekoehler** [comment]
Oh and another hint: The issue does not occur in the actual game when looking at the object from above, only in the editor.

**Comment by eugeneko** [comment]
> I created a test model with almost 200k triangles and converted it to Urho format and added it to a scene so you can reproduce this issue.

Oh, thanks, I almost asked for this.

> Oh and another hint: The issue does not occur in the actual game when looking at the object from above, only in the editor.

Cuz https://github.com/urho3d/Urho3D/commit/1ce189361d37af7e699e13157e7c2da43134701b is in Editor code

**Comment by eugeneko** [comment]
@andrekoehler FYI

If you want quick fix and don't need Terrain Editor, you could just comment out code snippet I mentioned above.

Then, if talking about _fixing_ the problem...
The first idea is to add a kind of filtering for Octree queries, e.g. test only specific type of components.
This is what exactly needed by Terrain Editor (pick only `TerrainPatch`es)

The second idea is that our raycasting is not very good... There would be FPS drop even if just hover mouse over high-poly mode. In perfect world there should be fallback mechanism to use lower LODs if current LOD level is too dense, or IDK. It would have its own downsides tho.
