### ISSUE TITLE
Build Urho3D for Android on ArchLinux (#include <features.h>???)

### ISSUE THREAD

**Issue by gerardogc2378** [urho3d/Urho3D#2311]
Hi guys, I have this issue, I execute this from shell 

./cmake_android.sh ./Build-Android -DANDROID=1 -DANDROID_ABI=armeabi-v7a -DANDROID_NATIVE_API_LEVEL=android-27

my output is this:

```
./cmake_android.sh ./Build-Android -DANDROID=1 -DANDROID_ABI=armeabi-v7a -DANDROID_NATIVE_API_LEVEL=android-27
./cmake_generic.sh: line 30: /home/ggc/mobile-projects/urho3d-projects/demo/.bash_helpers.sh: No such file or directory
CMake Deprecation Warning at CMakeLists.txt:9 (cmake_policy):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


CMake Error at CMake/Modules/FindUrho3D.cmake:346 (message):
  Could NOT find compatible Urho3D library in Urho3D SDK installation or
  build tree.  Use URHO3D_HOME environment variable or build option to
  specify the location of the non-default SDK installation or build tree.
  For Android platform, double check if you have specified to use the same
  ANDROID_ABI as the Urho3D library in the build tree or SDK.  Change Dir:
  /home/ggc/mobile-projects/urho3d-projects/demo/Build-Android/CMakeFiles/CMakeTmp


  

  Run Build Command:"/usr/bin/make" "cmTC_79e5c/fast"

  /usr/bin/make -f CMakeFiles/cmTC_79e5c.dir/build.make
  CMakeFiles/cmTC_79e5c.dir/build

  make[1]: Entering directory
  '/home/ggc/mobile-projects/urho3d-projects/demo/Build-Android/CMakeFiles/CMakeTmp'


  Building CXX object CMakeFiles/cmTC_79e5c.dir/CheckUrhoLibrary.cpp.o

  
  /home/ggc/opt/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++
  --sysroot=/home/ggc/opt/android-ndk-r16b/platforms/android-27/arch-arm
  -DURHO3D_STATIC_DEFINE -isystem
  /home/ggc/opt/android-ndk-r16b/sources/cxx-stl/llvm-libc++/include -isystem
  /home/ggc/opt/android-ndk-r16b/sources/cxx-stl/llvm-libc++abi/include
  -isystem /home/ggc/opt/android-ndk-r16b/sources/android/support/include
  -I/home/ggc/repos/Urho3D/include -fsigned-char -funwind-tables
  -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16
  -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -fdata-sections
  -ffunction-sections -frtti -fexceptions -fPIE -o
  CMakeFiles/cmTC_79e5c.dir/CheckUrhoLibrary.cpp.o -c
  /home/ggc/mobile-projects/urho3d-projects/demo/CMake/Modules/CheckUrhoLibrary.cpp


  In file included from
  /home/ggc/opt/android-ndk-r16b/sources/cxx-stl/llvm-libc++/include/iostream:37:0,


                   from /home/ggc/mobile-projects/urho3d-projects/demo/CMake/Modules/CheckUrhoLibrary.cpp:24:

  
  /home/ggc/opt/android-ndk-r16b/sources/cxx-stl/llvm-libc++/include/__config:169:22:
  fatal error: features.h: No such file or directory

   #include <features.h>
                        ^

  compilation terminated.

  make[1]: *** [CMakeFiles/cmTC_79e5c.dir/build.make:66:
  CMakeFiles/cmTC_79e5c.dir/CheckUrhoLibrary.cpp.o] Error 1

  make[1]: Leaving directory
  '/home/ggc/mobile-projects/urho3d-projects/demo/Build-Android/CMakeFiles/CMakeTmp'


  make: *** [Makefile:126: cmTC_79e5c/fast] Error 2

Call Stack (most recent call first):
  CMake/Modules/UrhoCommon.cmake:238 (find_package)
  CMakeLists.txt:20 (include)
```

How to fix that? Thanks

**Comment by gerardogc2378** [comment]
It is a NDK Issue, with ncurses library and ArchLinux.

**Comment by gerardogc2378** [comment]
This issue is related with https://github.com/android-ndk/ndk/issues/688

**Comment by weitjong** [comment]
This is a known issue. We have yet had time to upgrade our Android build to support Android NDK r16 yet. See https://discourse.urho3d.io/t/android-studio-2-3-build-with-gradle/2995.

BTW, our own custom Android.cmake toolchain is not derived from taka-no-me/android-cmake project which is now defunct. And it appears its development is now continued by Android-NDK team. We have created and used our own since we noticed the former has staled.

Contribution is welcome to upgrade our Android build system.

**Comment by rprichard** [comment]
The NDK provides a CMake toolchain file (https://android.googlesource.com/platform/ndk/+/ndk-release-r17/build/cmake/android.toolchain.cmake). Maybe Urho3D can use it? There was a successful attempt to do so about a year ago (https://discourse.urho3d.io/t/android-studio-2-3-build-with-gradle/2995/13).

**Comment by weitjong** [comment]
Yes, we will reevaluate to see whether it makes more sense to use the CMake/Android toolchain from Android NDK instead of spending time to maintain our own. We will also upgrade the Android build to use Gradle now that the upstream SDL has finally done that.

**Comment by weitjong** [comment]
I just have a preliminary success using the latest Android SDK/NDK and the SDK provided android.toolchain.cmake to build against Urho3D project with the Gradle build system. I only needed to adapt one of our CMake module to work with the "new" android.toolchain.cmake and the rest of C/C++ code build happily without hitting the reported issue.

**Comment by weitjong** [comment]
Hit the button too early. Will push my changes into the "gradle-kotlin-dsl" development branch later.

**Comment by weitjong** [comment]
This issue is fixed in my local branch after adapting the `CheckCompilerToolchain.cmake` module to work with the `android.toolchain.cmake` file. I am closing this issue, all the related updates will be done in #743.
