### ISSUE TITLE
Suspicious dead code?

### ISSUE THREAD

**Issue by movie-travel-code** [urho3d/Urho3D#2314]
Hi all,
I'm henry wong, from Qihoo360 CodeSafe Team. We found a series of suspicious dead code in `as_bytecode.cpp`. These dead codes are mainly caused by `AddInstruction()`. A typical case as the code [below](https://github.com/urho3d/Urho3D/blob/master/Source/ThirdParty/AngelScript/source/as_bytecode.cpp#L1647). `AddInstruction()` does not return other values except 0， that means `AddInstruction() < 0` always be false.
```
void asCByteCode::Call(asEBCInstr instr, int funcID, int pop)
{
	if( AddInstruction() < 0 )
		return;
        ...
}
```

Is this intentional? Or are some code tricks I don't know about? 

Since I'm unfamiliar with `Urho3D`, I think I should report this issue here to ask for your advice so as to improve `Urho3D`.

Henry Wong
Qihoo360 CodeSafe Team

**Comment by iSLC** [comment]
This should be reported to the AngelScript author http://www.angelcode.com/forums/

**Comment by movie-travel-code** [comment]
Thank you for providing this information, iSLC. I will try!
