### ISSUE TITLE
Incorrect comment in Str.h

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#2315]
/// String buffer, null if not allocated.

https://github.com/urho3d/Urho3D/blob/master/Source/Urho3D/Container/Str.h#L521

If I understand correctly buffer_ never equals null because **buffer_(&endZero)** in every constructor

**Comment by weitjong** [comment]
Yeah, I think it should read "String buffer, point to &endZero if buffer is not allocated yet" or something like that.
