### ISSUE TITLE
Add define for using only the 2D part of the engine.

### ISSUE THREAD

**Issue by Murii** [urho3d/Urho3D#2316]
Currently you're able to disable the 2D support. I suggest adding the same feature for the 3D part as well. This would make the engine more versatile !

**Comment by iSLC** [comment]
I believe that the 2D subsystem depends on the 3D subsystem. Or at least some parts of it. I could be wrong tho. I never bothered much with the 2D subsystem.

**Comment by OvermindDL1** [comment]
The 2D subsystem is just the 3D subsystem constrained is all, so yes it depends on the 3D subsystem.
