### ISSUE TITLE
Problem rendering in new project

### ISSUE THREAD

**Issue by troll-kadabra** [urho3d/Urho3D#2319]
hi
I build the urho samples and it works well, but when i move same code to new project (after steps in urho wiki) the camera dont render correctly, its like it never moves when i press w:
![1](https://user-images.githubusercontent.com/25616533/40817396-9e1eefc2-6528-11e8-9a67-664cc3a077e8.png)
![2](https://user-images.githubusercontent.com/25616533/40817399-a0045ae8-6528-11e8-9613-9b4c1d8ce326.png)
![3](https://user-images.githubusercontent.com/25616533/40817403-a30e8290-6528-11e8-8f76-841980d0f700.png)
it clips objects but it dont go forward, when i move mouse its wrong too:
![mouse](https://user-images.githubusercontent.com/25616533/40817394-9b546b82-6528-11e8-8c4b-349cf170dc38.gif)
i thought it was because of opengl but both projects use directx11 (string from Graphics object). code is same from static sample (copy paste) scept for the text on screen
i think it is because of the sse or avx because i had problems with that before but i dont know
also how do you render debug? i try DebugRender->Add but it dont render

**Comment by ArnisLielturks** [comment]
This was already discussed and fixed here: https://github.com/urho3d/Urho3D/issues/2318

**Comment by weitjong** [comment]
I take ArnisLielturks’s word and label this as duplicate for now. Feel free to reopen.
