### ISSUE TITLE
Some Urho3D samples built using WASM throw uncaught runtime exception

### ISSUE THREAD

**Issue by weitjong** [urho3d/Urho3D#2322]
The latest CI build for WASM uses the Emscripten v1.38.4.

**Comment by weitjong** [comment]
In view of this, if we are not able to fix this issue quick then we probably should revert back the default for EMSCRIPTEN_WASM build option to FALSE.

**Comment by eugeneko** [comment]
I confirm that forcing occlusion culling off fixes this hang.
I'll try to investigate this problem, but I don't think that software occlusion culling ever makes sence for Web builds because they all have CPU bottleneck.
