### ISSUE TITLE
Race condition when suspending application on Android

### ISSUE THREAD

**Issue by rokups** [urho3d/Urho3D#2328]
Any idea what is rationale behind disabling [SDL_ANDROID_BLOCK_ON_PAUSE](https://github.com/urho3d/Urho3D/blob/master/Source/ThirdParty/SDL/src/video/android/SDL_androidevents.c#L29-L30) in SDL? This creates a race condition when suspending application. Tapping "tasks" button rapidly eventually causes application to glitch out and objects become black or appear as if they were "textured" with uninitialized memory. Even worse side effect is that minimized application still spins main loop at 10 fps which is a battery killer. Reenabling `SDL_ANDROID_BLOCK_ON_PAUSE` i have not noticed any unwanted side effects. Decision for disabling this should probably be reevaluated.

@cadaver / @weitjong either of you recall why was it actually disabled? Comment is rather obscure. I thought `SDL_ANDROID_BLOCK_ON_PAUSE` meant app could no longer be quit by pressing UI button, but that works fine.

**Comment by weitjong** [comment]
There is nothing much I can find too. https://github.com/urho3d/Urho3D/commit/e74ee4ce52bf67756335978fad40989792776a40

Probably it is just a remnant from the past. If reverting back the changes does not cause any app exiting problem then you are welcome to send a PR to do that.

**Comment by cadaver** [comment]
That's ancient.. The issue was (as far as I remember) exactly like it says in the comment, the application could not be manually terminated, because it would pause and block before actually exiting.
