### ISSUE TITLE
Audio input support?

### ISSUE THREAD

**Issue by CingKong** [urho3d/Urho3D#2329]
I see Urho3D 1.7 already upgraded to SDL 2.0.5 which supports audio input, but didn't integrate that part?

**Comment by weitjong** [comment]
In master branch we have upgraded to SDL 2.0.7 which just starts to use the audio stream to auto convert audio format. It is still just scratches the surface though. Contribution is welcome.

**Comment by CingKong** [comment]
Uh uh, I'm just a computer newbie trying to get into game industry directly( for the so-called hobby), can't help 😂

BTW will Urho3D replace its UI subsystem anytime soon, with something like imgui? I think people have been talking about this for a long time.

**Comment by eugeneko** [comment]
It’s pointless to replace stateless GUI with canonical GUI or vise versa.
Most probably they will stay together. ImGUI was integrated two or three
times, but nobody ever made PR

пн, 11 июня 2018 г. в 10:50, Virgo <notifications@github.com>:

**Comment by CingKong** [comment]
I see related functions changed, is audio capturing supported now? how do we use it?
