### ISSUE TITLE
Resizing window breaks mouse movement events on MacOS

### ISSUE THREAD

**Issue by x6herbius** [urho3d/Urho3D#2330]
If I create a window with mouse movement applied to the camera as per the wiki's "My First Project", resizing this window on MacOS causes the engine to think the mouse is translated when it isn't. This results in the camera slowly turning, in a direction depending on how the window is resized. See: https://www.youtube.com/watch?v=3YsuyuEXhHQ

The code in my current application that deals with camera rotation is as follows:

```
Urho3D::Input* input = GetSubsystem<Urho3D::Input>();

if(!input->IsMouseVisible())
{
	float sensitivity = 0.1f;

	Urho3D::IntVector2 mouseMove = input->GetMouseMove();
	yaw_ += sensitivity * mouseMove.x_;
	pitch_ += sensitivity * mouseMove.y_;
	pitch_ = Urho3D::Clamp(pitch_, -89.0f, 89.0f);

	sampleScene_->cameraNodes_[0]->SetDirection(Urho3D::Vector3::FORWARD);
	sampleScene_->cameraNodes_[0]->Yaw(yaw_);
	sampleScene_->cameraNodes_[0]->Pitch(pitch_);
}
```

Resizing the window does not cause the same issue on Linux.

**Comment by weitjong** [comment]
I suspect it could be related with our incomplete Retina display support. You can try to disable the High DPI mode to see if the problem disappear, just to confirm it first.

**Comment by x6herbius** [comment]
You're right - running with `-lowdpi` doesn't cause the same problem.

**Comment by weitjong** [comment]
As currently we always return things in pixels instead of normalized screen coordinates, you probably have to readjust the sensitivity variable accordingly. HTH.

**Comment by x6herbius** [comment]
I don't think that'll work. The way the code works (which I took from the sample project), the incoming `mouseMove.x_` and `mouseMove.y_` values are treated as a deltas on the previous frame's pitch and yaw:

```
yaw_ += sensitivity * mouseMove.x_;
pitch_ += sensitivity * mouseMove.y_;
```

If I change the sensitivity, all that'll do is change how fast or slow the drift is - it won't change the fact that the `mouseMove` vector is wrong.

I suspect the underlying issue is that when the mouse is grabbed in high DPI mode, the "centre" of the window that its position is reset to is different from the "centre" that the delta is measured from.

**Comment by weitjong** [comment]
I see. Yes, that sounds more plausible.

**Comment by cadaver** [comment]
I tried the latest master's StaticScene sample in windowed highdpi mode on a Retina Mac, but didn't get it to exhibit mouse centering misbehavior when the window was resized. Tried both manual window resizing while alt-tabbed out + programmatic timed resize via graphics.SetMode()

**Comment by x6herbius** [comment]
I have a small repo that I was using when I experienced the issue. I think it's still present, but it was definitely present at the following commit: https://github.com/x6herbius/calliper-urho3d/commit/5f2713c03bc1b59125e63ffaa1904783034e1990 That should give you an idea of the code I was using - if it's still not reproducible, I can dig out detailed specs of the MacBook system I encountered it on.

**Comment by weitjong** [comment]
I don't have Retina Mac so I cannot help in reproducing the issue.
