### ISSUE TITLE
Question about JSON

### ISSUE THREAD

**Issue by chenjie199234** [urho3d/Urho3D#2332]
I need to encode and decode json;
I Read Json like this:
File * file = new File(context_);
file->open(path)
String s = file->readstring()
+++
s = mydecode(s);
+++
JSONFile test;
test.fromstring(s);

The question is how to serialize a json object to string.
like this:
JSONFile test;
test.Getroot().set();
     .
     .
     .
+++++
how to serialize this json to a string.
i need the string to encode,like this:
s = myencode( the string which is seriazed from json);
++++

**Comment by weitjong** [comment]
I believe I have answered this question as well in the example I gave in the other issue, although that example uses XMLFile instead of JsonFile. If you have more questions, please use our forum instead of our issues log. Thanks.
