### ISSUE TITLE
Question about File and FileSystem

### ISSUE THREAD

**Issue by chenjie199234** [urho3d/Urho3D#2333]
Game needs config file.
we can use File class to open a file.
but we cant use Filesystem to create a file.
if there is no config file,player delete it or data miss,then i we cant create a new one and write the default config into it.

Game's config can be changed!
player change the config,we need to delete the content in old config file and write the new config into it.
but there is no api to delete file or clear the content in the existing config file.

**Comment by weitjong** [comment]
I am not sure I quite understand your question.  But I guess your confusion arise from the fact you have mixed up between File/FileSystem i/o classes and XMLFile/JsonFile resource classes. The former abstracts a way what a "file" is (regardless of the platform you are targeting). The latter is what I think you are looking for, they are two example of document resource that you serialize/deserialize the content. You can look at these line as the source of inspiration.

https://github.com/urho3d/Urho3D/blob/master/bin/Data/Scripts/Editor.as#L175-L442

**Comment by SirNate0** [comment]
I believe the question may have been how to create/overwrite files. If that's the case, open them as FILE_WRITE, and I believe the file should be created if it doesn't exist and overwritten if it does.
