### ISSUE TITLE
Conversion from '__int64' to 'const unsigned int' warning in Vector

### ISSUE THREAD

**Issue by SuperWangKai** [urho3d/Urho3D#2338]
Warning in VS2017 for x64, minor but annoying.

https://github.com/urho3d/Urho3D/blob/dcbc0046c71a37f411d78e8ecd10cfe322f3db19/Source/Urho3D/Container/Vector.h#L549

message:
```
build_vs2017\include\urho3d\container\vector.h(558): warning C4244: 'initializing': conversion from '__int64' to 'const unsigned int', possible loss of data
```

**Comment by SuperWangKai** [comment]
I think truncation for the offset is alright. I've heard people talking about using STL or 'modern c++' to replace the buildin facilities so much, however, I strongly for keeping as KISS as we can and to stick mostly to Urho way. That't the pros of Urho.

**Comment by OldSnake22** [comment]
Hello, any fix for this minor issue ?
