### ISSUE TITLE
can we add an api named tostring() in jsonfile.

### ISSUE THREAD

**Issue by chenjie199234** [urho3d/Urho3D#2346]
there is an api named fromstring.
can we add an api named tostring.
i need to crypt the string come from json.
can we offically support this,so that i dont need to rebuild when i update the urho3d.

**Comment by weitjong** [comment]
It sounds like you already have something done about it. If so, you can just send the patch in as PR to see if gets merged as it is. Thanks.

**Comment by chenjie199234** [comment]
@weitjong 
I just dont know how to up load the code;
Write it here,and can u help me to add it to the engine code?

Add this in JSONFile.h
String ToString(const String& indendation = "\t");

Add this in JSONFile.cpp
String JSONFile::ToString(const String& indendation)
{
rapidjson::Document document;
ToRapidjsonValue(document, root_, document.GetAllocator());
StringBuffer buffer;
PrettyWriter<StringBuffer> writer(buffer);
writer.SetIndent(!indendation.Empty() ? indendation.Front() : '\0', indendation.Length());
document.Accept(writer);
return buffer.GetString()
}

**Comment by weitjong** [comment]
Thanks for that. Will try to patch the code manually when I have time. If you want it to get merge quickly then sending the patch as Pull Request is the right way to go (because any one of the maintainers can do that via GitHub web interface).
