### ISSUE TITLE
Is it possible to resize AnimatedSprite2D?

### ISSUE THREAD

**Issue by bartusb** [urho3d/Urho3D#2350]
Is it possible to resize AnimatedSprite2D to given size? I've tried using SetDrawRect & SetUseDrawRect as below but with no success so far:
```
auto cache = context_->GetSubsystem<ResourceCache>();
auto animationSet = cache->GetResource<AnimationSet2D>(animationSetName);
auto spriterNode = scene_->CreateChild("SpriterAnimation");
auto spriterAnimatedSprite = spriterNode->CreateComponent<AnimatedSprite2D>();

spriterAnimatedSprite->SetAnimationSet(animationSet);
spriterAnimatedSprite->SetAnimation(animationSet->GetAnimation(animationIndex));

spriterAnimatedSprite->SetDrawRect(Rect(0, 0, 100, 100));
spriterAnimatedSprite->SetUseDrawRect(true);
```

**Comment by weitjong** [comment]
Try use the node to scale the component.

**Comment by bartusb** [comment]
Sure, scaling node is working but in my case I need to resize AnimatedSprite2D to given size - Rect(0,0,100,100). I couldn't find SetDrawRect on Node so it seems that Scale or SetScale is the only way to resize the sprite. To scale the sprite first I need to calculate proper scale ratio. Could you please advice how to get size of AnimatedSprite2D or particular animation from given animation set?  Thanks.
