### ISSUE TITLE
texturequality bug when change texture quality by Renderer

### ISSUE THREAD

**Issue by chenjie199234** [urho3d/Urho3D#2351]
At Step():set engineParameters_["TextureQuality"] = 2;
At other place:GetSubsystem<Renderer>()->SetTextureQuality(QUALITY_MEDIUM);
Then the texture size will change to half of the normal.
Is it correct?
This is the normal texture
![correct](https://user-images.githubusercontent.com/29348971/42986799-97fd40c6-8c29-11e8-96bc-ec919abd82d1.PNG)
Here is the problem
![error](https://user-images.githubusercontent.com/29348971/42986800-983b4d08-8c29-11e8-9d24-825574bf35c6.PNG)
Here is the testing file and the prebuild testing program
[Desktop.zip](https://github.com/urho3d/Urho3D/files/2216029/Desktop.zip)

**Comment by weitjong** [comment]
Which backend Graphics API are you using?

**Comment by chenjie199234** [comment]
@weitjong prebuild version from sourceforge,windows dx11 static.my pc is win10 version 1803

**Comment by weitjong** [comment]
I don't have Win10 host system to test at the moment. However, I cannot reproduce the issue on my Linux host system using OpenGL. I tested using one of the samples, bringing up the debug HUD by pressing "F2"  and cycling the texture quality by pressing "1". Perhaps you can repeat the same test on your Win10 system.

**Comment by weitjong** [comment]
Can you confirm that the issue also exists when you try one of provided samples? I just want to ensure it is not caused by programming error somewhere else in your own code. Thanks.

**Comment by chenjie199234** [comment]
@weitjong The sample is ok!But i write another sample with problem!here is the code and resource!
[Urho3D_Projects.zip](https://github.com/urho3d/Urho3D/files/2215932/Urho3D_Projects.zip)

**Comment by weitjong** [comment]
Thanks for your confirmation. In that case I think it is better you seek support from the forum as there are more readers there and hopefully someone is willing to lend a hand.

**Comment by chenjie199234** [comment]
@weitjong can u find a windows pc and run the program.The problem is exist.
the code is very clear.just create a button and try to crycling the texture quality.

**Comment by weitjong** [comment]
I have a valid Windows Pro license, however, my Win10 which is installed on one of my boot partitions has gone kaput many months ago and I still don't find enough incentive to revive it. So sorry. I don't want to waste the remaining of my weekend reinstalling Windows :smile:

**Comment by sirop** [comment]
@chenjie199234 @weitjong 
I can partly reproduce this behaviour in my own code:
![text_low](https://user-images.githubusercontent.com/1533811/43034906-6f01cda6-8ce5-11e8-88c7-6bc509ed08d9.png)



![text_higher](https://user-images.githubusercontent.com/1533811/43034910-7df6421a-8ce5-11e8-8e91-b07b05107f12.png)

As you see only the logo in the right lower corner is affected. The blue buttons do not get "resized" or "chopped".

**Comment by cadaver** [comment]
Anything in the UI works by absolute pixel rects. Therefore you should make UI textures "immune" to the texture quality resizing by defining quality low="0" on them, see UI.xml in the Data folder.

**Comment by sirop** [comment]
@chenjie199234 
I looked into your code. You do smth. like:
```
new_button->SetName("new_button");
	new_button->SetBorder(IntRect(0, 0, 0, 0));
	new_button->SetTexture(GetSubsystem<ResourceCache>()->GetResource<Texture2D>("Textures/login_button_normal.png"));
```
So this button has a texture. In my case the blue buttons have no texture.
So try to follow @cadaver advice above.

**Comment by chenjie199234** [comment]
@weitjong @sirop @cadaver 
i did like cadaver said,and problem has been solved!
thank you guys very much!
but i have many ui textures and i didnt pack it into one texture.so i need to add the "xml file" for every texture?
is there any way to add the "xml file" to the folder,and every texture in the folder will use it!

**Comment by SirNate0** [comment]
@chenjie199234 
I don't think there's a way to do it from the engine, but it is easy enough to automate creating the files, just run a script along the lines of `for %f in (*.png) do copy Logo.xml "%~nf.xml"` where Logo.xml is in the directory and has the xml you need (I used the Logo.xml from Data/Textures).
