### ISSUE TITLE
LogicComponent is incorrectly running E_UPDATE even when node disabled.

### ISSUE THREAD

**Issue by solorvox** [urho3d/Urho3D#2356]
Test scene with repo case:
https://pastebin.com/4PiEzt0s

Usage, add files, use spacebar to toggle root node on/off via SetEnabledRecursive();

Root node has a child node with a with LogicComponent that receives E_UPDATE event callbacks.  

NOTE the logic componet update code should not run when node is disabled.  
docs: https://urho3d.github.io/documentation/HEAD/_scene_model.html
"If a node is disabled, all of its components are treated as disabled regardless of their own enable/disable state."
	
And per source:
https://github.com/urho3d/Urho3D/blob/master/Source/Urho3D/Scene/LogicComponent.cpp#L112
bool enabled = IsEnabledEffective();
	
Again according to docs:
https://urho3d.github.io/documentation/HEAD/class_urho3_d_1_1_component.html
IsEnableEffective() "Return whether is effectively enabled (node is also enabled). "
	
Yet this code will ALWAYS run even if node_ is disabled, root_->SetEnabledRecursive(false); is has been called.  Notice in the console it prints "DISABLED" to both node and IsEffectiveEnabled() but this should only  execute when node_ is enabled.

**Comment by cadaver** [comment]
You're supposed to override LogicComponent's virtual Update() function to have your tick update be switchable on/off along with the enabled status.

If you just subscribe to the scene update manually with your own function, the behavior you observed is expected.

**Comment by weitjong** [comment]
Thanks Lasse. Should have checked the code in the pastebin this morning before labeling.

**Comment by solorvox** [comment]
The problem with that is most of the Urho3D/Samples use that method for updates.   The documentation seems to make it rather clear that the expected behavior for a component is controlled by the node's state.  

Furthermore, I didn't see anywhere in the documentation that says events bypass both the node and component's enabled state.

**Comment by cadaver** [comment]
The event system is a global mechanism operating on a lower level, it doesn't know of scenes or nodes or them being enabled / disabled.

**Comment by solorvox** [comment]
I just started using Urho this month.  My starting points to learning the API is checking are the docs and samples.  Both seem counterintuitive to be able to infer that behavior.

For example, https://urho3d.github.io/documentation/HEAD/_events.html nor https://github.com/urho3d/Urho3D/wiki/Events mention that events would act in that manor.  Neither do most of the samples using E_UPDATE as the main method for running updates.  

Then the "Scene Update" docs to me, clearly imply otherwise that all types of components stop functioning when disabled via node or component SetEnabled().   I would think a few good places that could use a bold notice that using events will act in that manor so new users would be aware.

Cheers

**Comment by weitjong** [comment]
As we are shorthanded, you are welcome to fix the docs. Thanks.
