### ISSUE TITLE
Removal of replicated node has no effect on client connected afterwards

### ISSUE THREAD

**Issue by fnadalt** [urho3d/Urho3D#2363]
I have this personal project https://drive.google.com/open?id=1chko8MpacAUgmSWMnhY0dTEI18wkmxX_. I have been recently playing around with networking. Since I have one xml scene file, there coexist local and replicated nodes. After starting the server, I remove a replicated node. Then, when I start the client, the node is still there. Does not happen with other transforms made BEFORE client connection.

Urho3D git version @ commit 17c4a1022d3342b6318fa095661a0ecba6306284
4.17.2-1-ARCH
gcc versión 8.1.1
AMD Athlon(tm) 64 X2 Dual Core Processor 4600+
1995MiB System memory
Cedar [Radeon HD 5000/6000/7350/8350 Series]

**Comment by ArnisLielturks** [comment]
https://github.com/urho3d/Urho3D/pull/2364
