### ISSUE TITLE
Vertex and Pixel shader defines doesn't match

### ISSUE THREAD

**Issue by gleblebedev** [urho3d/Urho3D#2366]
> _temp(LIGHTBASEPASS PERPIXEL SHADOW SPOTLIGHT) and pixel shader _temp(LIGHTBASEPASS PCF_SHADOW PERPIXEL SHADOW SPECULAR SPOTLIGHT):

I guess this happens because Urho is trying to optimize shader compilation? But the shader is a combination of VS and PS so a new set of arguments in either of them produces a new shader variant.

This blocks varying optimization as I can't decide what varyings are required as I can't predict what is needed by pixel shader. 

Is there a reason why they should be different?

**Comment by cadaver** [comment]
I'd turn the question around, why should they necessarily be the same? For example specular calculations only have significance for the pixel shader. Apart from the in-engine defines, materials / techniques are free to add whatever defines they want, separately for VS & PS. Also, ShaderVariations are either VS or PS, not a combination of them. In OpenGL terms they're a shader source that has been compiled. Then the OpenGL backend combines (links) them internally as a shader program (as required), but D3D doesn't.

For well-behaved shaders, you could assume the same define is controlling the inclusion of a varying in both VS & PS source. But if some material / shader author wanted to be evil and use a different define to do so, it wouldn't even strictly speaking be an error from the engine's point of view.

**Comment by gleblebedev** [comment]
> For example specular calculations only have significance for the pixel shader

I believe this is something that shader developer should decide and engine should not dictate. It may be only used in PS and may be not.

**Comment by gleblebedev** [comment]
I'll do the PR, thanks :-)

**Comment by cadaver** [comment]
Note however, that it may have the effect of unnecessary vertex shaders being compiled (for example previously the same vertex shader would be fine for both specular on / off), so the core devs may not want to merge it.

Also note the warning code in ShaderVariation implementations, which detects & warns of unused defines (only debug mode). At that point it's already too late to prevent the unnecessary extra variation from being created, though.

So if you'd want to be thorough, the unused define analysis would need to be done in the Shader class beforehand, before deciding to create a new variation. This however would add runtime overhead, so it's not a perfect solution either.

**Comment by gleblebedev** [comment]
Currently I have to put extra calculations into vs because I can't tell if ps needs them or not. This also causes runtime overhead if shader optimizer in driver discards it or even worse - extra work is done per each vertex if there is no optimizer.
