### ISSUE TITLE
Editor mouse cursors only two colours

### ISSUE THREAD

**Issue by Modanung** [urho3d/Urho3D#2367]
I noticed the mouse cursors in the Editor are being reduced to two colours in runtime. Can this change be reverted or should I make new/alternative cursors? The fuglyness is clearest during drag and drop operations.
Whilst designing them half a year ago this was not the case.

**Comment by weitjong** [comment]
I am sure it is not intentional. Do you which change causing it?

**Comment by Modanung** [comment]
I have no Idea, I just noticed and don't use the editor much. But I thought it might be an optimisation (like _hardware cursor_) that the graphics would have to be adapted to.
![image](https://user-images.githubusercontent.com/7316241/44573918-3a482e80-a788-11e8-832c-b0836bb11c92.png)
Left is how it should be, right is how it shows.

**Comment by weitjong** [comment]
I have a bad eye sight but I don’t think I have observed that (yet). Last I remember the arrow cursor looks like the left picture.

**Comment by Modanung** [comment]
Hm, It might be local then. I'll see how it looks after making the Gradle rock.

**Comment by weitjong** [comment]
Not reproducible.

**Comment by Modanung** [comment]
The cursor is displayed as intended once again.
I recently updated my video drivers, maybe it has something to do with it.
