### ISSUE TITLE
CI package build may run out of disk space for STATIC lib type

### ISSUE THREAD

**Issue by weitjong** [urho3d/Urho3D#2368]
Affected platforms: RPI (armeabi-v7a with NEON), ARM (armhf)

While I am at it, CI also runs out of time for Web platform (asm.js) on both lib types.

**Comment by headupinclouds** [comment]
I experience this recently in a project, and we simply switched from the Travis container builds to VM builds to get more space.  There is a big difference between the container based builds (`sudo: false` == `9 GB`) and the standard VM builds (`sudo: required` == `18 GB`) as documented here:

https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system

If you update your travis config [here](https://github.com/urho3d/Urho3D/blob/3db124b5cd8ca3afab7a10a2626d738048feabb2/.travis.yml#L33) you will likely have plenty of space.  Unfortunately, this also requires a change in the package setup -- you have to use standard `apt-get` installation syntax, i.e.: 

```
sudo apt-get install -y libc++-dev libc++abi-dev libclang-5.0-dev libclang-common-5.0-dev libclang1-5.0 clang-5.0;
```

**Comment by weitjong** [comment]
Thanks for the info. Before we migrate to container-based CI, our build script used to have apt-get command similar like that. Personally I don’t think I would like to see a reverse in direction, even when it has bigger space on VM.

**Comment by weitjong** [comment]
> While I am at it, CI also runs out of time for Web platform (asm.js) on both lib types.

Actually it is the other way round. It is the WASM build that runs out of time.
