### ISSUE TITLE
Shadows crash on Android

### ISSUE THREAD

**Issue by Mike3D** [urho3d/Urho3D#237]
When switching between scenes on Android, I have to disable shadows to prevent from crash.

Steps to reproduce:
- take Aster's sample at https://dl.dropboxusercontent.com/u/56770481/SwitchScene.lua
- modify to make lights, boxes and mushrooms cast shadows
- switch back and forth between the scenes to reproduce the crash

This issue seems to be related to the mods done for "inView", as it previously didn't crash.

**Comment by Mike3D** [comment]
In fact crash occurs with every samples and also in AngelScript, it takes about one minute to crash, unless I remove shadows.
I post an abridged log, maybe it can give some clues:

A/libc(12294): Fatal signal 11 (SIGSEGV) at 0x0000015c (code=1), thread 12309 (SDLThread)
I/DEBUG(96): pid: 12294, tid: 12309, name: SDLThread  >>> com.github.urho3d <<<
I/DEBUG(96): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0000015c
I/DEBUG(96): backtrace:
I/DEBUG(96):     #00  pc 00011abc  /system/vendor/lib/egl/libGLESv2_POWERVR_SGX540_130.so
I/DEBUG(96):     #01  pc 000144f0  /system/vendor/lib/egl/libGLESv2_POWERVR_SGX540_130.so
I/DEBUG(96):     #02  pc 0000bdc4  /system/vendor/lib/egl/libGLESv2_POWERVR_SGX540_130.so (glClear+52)
I/DEBUG(96):     #03  pc 00311d03  /data/app-lib/com.github.urho3d-2/libUrho3DPlayer.so (Urho3D::Graphics::Clear(unsigned int, Urho3D::Color const&, float, unsigned int)+206)
I/DEBUG(96):     #04  pc 002ef091  /data/app-lib/com.github.urho3d-2/libUrho3DPlayer.so (Urho3D::View::RenderShadowMap(Urho3D::LightBatchQueue const&)+284)

**Comment by Mike3D** [comment]
I've identified the commit from which the issue arose, it's commit 4c02e19352fa8ec6f242a7402ac806175abb1a6e, which dramatically improved shadows.
Reverting to 2 cascades fixes the issue, but I'm back with crappy shadows.

**Comment by cadaver** [comment]
I would suspect that the cascade count is used as an array length, and when it's 1, a memory invasion happens because somewhere else a longer length is expected. Will investigate.

**Comment by cadaver** [comment]
I've added a safeguard to Urho3D side code. Unfortunately, if the crash persists, it means that the GPU driver is acting up and can not handle an array with size 1 correctly. In that case it's unpleasant to start working around that in Urho3D code, though I guess a large amount of these Android-specific crap driver workarounds are a reality for engines like Unreal4, Unity etc.

**Comment by Mike3D** [comment]
Thanks for investigations!
This fix seems to have improved fluidity, but unfortunately it still crashes.
What's strange is that on my device I get a dark area around camera position (I don't have this on desktop) and everything inside this area is shadowed and everything outside isn't (see attached image).
![device-2015-02-09-161530](https://cloud.githubusercontent.com/assets/6427048/6110617/33cb0c30-b083-11e4-8eb5-fdc799a139d0.png)
And 4 seconds before the crash (which happens invariably at the exact same time), the dark area disappears and there's a 1 second freeze.

**Comment by Mike3D** [comment]
Unity doesn't seem to handle this kind of issue any better: http://forum.unity3d.com/threads/game-crashes-unless-on-development-build.192696/

**Comment by cadaver** [comment]
On my device I cannot reproduce a similar issue. The darkening looks like the shadow brightness multiplier uniform (cShadowIntensity) isn't set right; there are 4 shadow samples so for every un-shadowed pixel to be lit up right, the multiplier needs to be 0.25.

Realistically (as I don't want to go making wild-guess commits with no way to verify the effect directly) you'll have get your hands dirty and tweak the GLSL code to see whether you can get it to a state where it doesn't crash, for example replacing the [1] sized shadow coord arrays with just a plain variable, as accessing an array with size 1 is honestly unnecessary.

**Comment by Mike3D** [comment]
Many thanks for advices! Unfortunately tweaking the shader is currently beyond my skills (I've tried many fixes to no avail), I will have to postpone until I improve my skills in this field.
