### ISSUE TITLE
StringHash case sensitivity

### ISSUE THREAD

**Issue by orefkov** [urho3d/Urho3D#2372]
Why StringHash become casesensitivity from 8ba6a369733280c96a0 ?
That broke backward compatibility.

**Comment by eugeneko** [comment]
There's some discussion in the comment section below referenced commit.

2018-09-11 11:30 GMT+03:00 orefkov <notifications@github.com>:

**Comment by weitjong** [comment]
Closing it now. Feel free to reopen if you have anything to add later.
