### ISSUE TITLE
right to left languages

### ISSUE THREAD

**Issue by hassanrahimi** [urho3d/Urho3D#2379]
hi urho developers.
I have problems,urho don't support right to left languages like farsi and arbic.
can you develop urho for support right to left languages?
or learn to me how do might this.
I post here to show problem
https://discourse.urho3d.io/t/use-right-to-left-languages/4546

**Comment by Modanung** [comment]
@hassanrahimi [passed](https://discourse.urho3d.io/t/use-right-to-left-languages/4546/10) the hurdle he encountered. Should this issue be closed?
