### ISSUE TITLE
Read image that format is RGB will crash.

### ISSUE THREAD

**Issue by Y-way** [urho3d/Urho3D#2383]
https://github.com/urho3d/Urho3D/blob/954738f04fca8d20213c8919d07223641d1ae91e/Source/Urho3D/Urho2D/TmxFile2D.cpp#L772
SharedPtr<Image> image = info.image->ConvertToRGBA();

**Comment by weitjong** [comment]
I would appreciate if you can provide us the steps to reproduce the crash, if not the stack trace of the crash itself. Thanks.

**Comment by Y-way** [comment]
1.create a tmx map with tiled map editor.
2.add a image layer or a single tile image with a jpg file.
3.use the tmx map in engine.
Above the steps would reproduce the crash.
Because a jpg image file has RGB components and the TmxFile2D::LoadTileSet method processes the image as RGBA (4 components).
Copying data [https://github.com/urho3d/Urho3D/blob/954738f04fca8d20213c8919d07223641d1ae91e/Source/Urho3D/Urho2D/TmxFile2D.cpp#L776](Urho3D/Source/Urho3D/Urho2D/TmxFile2D.cpp) outof range.
A fatal error.
My poor English.

**Comment by weitjong** [comment]
Related to PR #2407.
