### ISSUE TITLE
Save generated convex hull

### ISSUE THREAD

**Issue by codec-abc** [urho3d/Urho3D#2385]
Hi,

For the application I am developing, I want the user to be able to click on a mesh to select it. Selection does not need to be pixel perfect. Auto generated convex hulls from seems like a good fit because they have a low memory footprint, are runtime efficient and works well even for collision with other geometry (even if I only need picking). From the tests I made this seems to works great. Yet, the meshes I use are fairly detailed and the generation of the convex hulls take quite a bit of time (but the result looks good and the picking works as expected). So, what I would like to do is to save the generated convex hulls. 

I think I can kind of do it by generating the convex hull once, call `collisionShape->GetGeometryData()`, cast it to `a ConvexData*` then save in a file the members `vertexData_` and `vertexCount_`. Then at the next launch time I can create a `ConvexData*` and inject the previously saved `vertexData_` and `vertexCount_` and inject this into the `collisionShape`. I probably need to call a few methods (which may be private) to forward the data to Bullet but I think it is doable . But, this seems way too hacky and error prone. Also modifying the Urho3D source code which is not something I want to do. 

So if the API is "slightly" reworked it may allow to save the generated the convex hull like a scene/model which would be a nice addition. Ideally this should be without too much risk for the user to shoot him/her self in the foot.

What do you think?

**Comment by Modanung** [comment]
@codec-abc Could [this](https://discourse.urho3d.io/t/solved-its-possible-to-export-customgeometry/2358) help?

**Comment by codec-abc** [comment]
Thanks, it the end I didn't use the convex hull colliders.
