### ISSUE TITLE
Rendering issues

### ISSUE THREAD

**Issue by LL2** [urho3d/Urho3D#2388]
I've cloned and compiled Urho3d 1.7 a week or so ago and after recompiling my old project i'm getting issues with the camera or renderer. The camera is upside down and when i move the mouse, the projection seems to be corrupted.

this is not only happening with my old projects, but also with the Urho's demos. Here an example with CharacterDemo:

![](https://media.giphy.com/media/1wo0BIpxjhJsUnNQ51/giphy.gif)

https://media.giphy.com/media/1wo0BIpxjhJsUnNQ51/giphy.gif

I'm using Ubuntu Mate 18.10 (Cosmic Cuttlefish)

**Comment by iSLC** [comment]
Check your GCC version and either patch your code or use the latest version fom repository.

See more at: https://github.com/urho3d/Urho3D/pull/2344

**Comment by iSLC** [comment]
Latest version of Urho. My apologies for being ambiguous.

As for how to disable it. Simply look at what was changed in the pull request made to fix this issue. https://github.com/urho3d/Urho3D/pull/2344/commits/c8596d427d1536fe7348a88b1be402697f6fa2a3

**Comment by LL2** [comment]
Thank you so much @iSLC I'll give it a try

**Comment by LL2** [comment]
definitely the latest version of Urho solved my problem :+1:
