### ISSUE TITLE
50_Urho2DPlatformer invisible traps

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#2390]
![urho2dinvisibletrap](https://user-images.githubusercontent.com/13021826/48618850-aadba180-e9ab-11e8-9aa3-5c37a0734ddf.png)

**Comment by 1vanK** [comment]
Inivisible plathorms?

![urhoinvisplathorms](https://user-images.githubusercontent.com/13021826/48619010-24738f80-e9ac-11e8-84e0-a585f76f6952.png)

**Comment by weitjong** [comment]
I am not that sure it is a bug as I have not played it that much :smile: .

**Comment by 1vanK** [comment]
As far as I remember, there should be a flower there, but now for some reason it isn’t

**Comment by urnenfeld** [comment]
Urho2D/Aster.png for the flowers, and Urho2D/Box.png for the platforms... all the StaticSprite2D nodes affected except the background ...

**Comment by 1vanK** [comment]
Fix:
```
void Sample2D::CreateBackgroundSprite(TileMapInfo2D info, float scale, const String& texture, bool animate)
{
    ...
    sprite->SetLayer(-99); // Added
```
