### ISSUE TITLE
Spine animation support

### ISSUE THREAD

**Issue by zxzx74147** [urho3d/Urho3D#2394]
https://github.com/EsotericSoftware/spine-runtimes/tree/3.6/spine-c/spine-c
I copy this spine-c runtime to ThirdParty folder and rename it to spine(I find the config in /Source/CMakeLists.txt),then I run cmake configure and generate.

When I make the project ,the errors:

/home/zx/workspace/Urho3D/Source/Urho3D/Urho2D/AnimatedSprite2D.cpp: In member function ‘void Urho3D::AnimatedSprite2D::UpdateSourceBatchesSpine()’:
/home/zx/workspace/Urho3D/Source/Urho3D/Urho2D/AnimatedSprite2D.cpp:326:50: error: ‘spSlot {aka struct spSlot}’ has no member named ‘r’
         unsigned color = Color(color_.r_ * slot->r,
                                                  ^
/home/zx/workspace/Urho3D/Source/Urho3D/Urho2D/AnimatedSprite2D.cpp:327:31: error: ‘spSlot {aka struct spSlot}’ has no member named ‘g’
             color_.g_ * slot->g,
                               ^
/home/zx/workspace/Urho3D/Source/Urho3D/Urho2D/AnimatedSprite2D.cpp:328:31: error: ‘spSlot {aka struct spSlot}’ has no member named ‘b’
             color_.b_ * slot->b,
                               ^
/home/zx/workspace/Urho3D/Source/Urho3D/Urho2D/AnimatedSprite2D.cpp:329:31: error: ‘spSlot {aka struct spSlot}’ has no member named ‘a’
             color_.a_ * slot->a).ToUInt();
                               ^
/home/zx/workspace/Urho3D/Source/Urho3D/Urho2D/AnimatedSprite2D.cpp:334:85: error: too few arguments to function ‘void spRegionAttachment_computeWorldVertices(spRegionAttachment*, spBone*, float*, int, int)’
             spRegionAttachment_computeWorldVertices(region, slot->bone, slotVertices);
                                                                                     ^
In file included from /home/zx/workspace/Urho3D/build/linux2/include/Urho3D/ThirdParty/spine/spine.h:44:0,
                 from /home/zx/workspace/Urho3D/Source/Urho3D/Urho2D/AnimatedSprite2D.cpp:38:

...and so on

Does Urho3d 1.7 support spine runtime now? Or specified spine runtime version is necessary?

**Comment by weitjong** [comment]
The person who contributed this part of the code has left the project. So, this part of the code is not well maintained at the moment. And since it depends on an optional (and non-free) 3rd-party software, this part of the code is not included in our CI build tests. Thus, after a while it is not surprising to find it is out-of-sync with the rest. However, it should not be difficult to fix the problem. You are welcome to do that, if you are interested.
