### ISSUE TITLE
Site documentation rendered with errors after Doxygen update

### ISSUE THREAD

**Issue by weitjong** [urho3d/Urho3D#2398]
The site documentation is now generated using dockerized build environment with the latest Doxygen version (1.8.13) on Ubuntu bionic. However, it appears there is a bug in 1.8.13 where it does not generate the file "dynsections.js", or at least it may require additional tweak to Doxyfile to do so. Doxygen version 1.8.14 (only available on Fedora) does not appear to have this issue.

Also, the newer Doxygen version seems to have dependency on jquery, which means we need to modify our documentation page template to include the jquery.js.

**Comment by weitjong** [comment]
The "document-switcher" still being rendered behind the doxygen's smartmenus on iOS devices for some reason.

**Comment by DavidTocino** [comment]
Hi, the Wiki pages are open, everybody can edit?
Check it out.

**Comment by weitjong** [comment]
Sorry for late reply. For some reason I just saw your comment now. Yes, it is intentional that the wiki pages are open. It’s content is community maintained.

Also I realized I have erroneously opened the issue about the main website here, it should be in other repo. So closing this now.
