### ISSUE TITLE
android build out of memory

### ISSUE THREAD

**Issue by cryforyou** [urho3d/Urho3D#2405]
out of memeory when build android with ./gradlew build ,  or dockerized.sh android ./gradlew build.
host system:ubuntu 18.04

**Comment by weitjong** [comment]
At the minimum your host system needs to have 8GB of memory. Without any IDE open, I am able to perform a default build (all 4 ABIs) on my Fedora 29. I did a few "free -h" command and could see the build process take about 4GB. If you have anything else heavy on memory opened then most probably you would get hit by OOM exception. Travis CI VM only has about 8GB and it also proven to build Android CI just fine, although we cheat a bit there by having multiple CI builds in parallel, each with split ABI mode turned on. My recommendation is to have 16GB of memory for Android build, especially if you want  run/debug with Android Studio or IntelliJ.

**Comment by weitjong** [comment]
My "free -h" may not be that accurate because my ccache has a very high cache hit rate, that is the memory utilization during the initial build should be slightly higher than 4GB. But otherwise, what I have just said above is still valid.

**Comment by cryforyou** [comment]
total        used        free      shared  buff/cache   available
Mem:            11G        1.3G        8.7G        289M        1.7G        9.8G
Swap:           15G          0B         15G


memory status before building, but still java heap space error

**Comment by cryforyou** [comment]
> I am sorry to hear that. 11GB should be enough, not sure why it failed on your system. Interesting memory configuration though. I would try two things if I were you.
> 
> 1. Create a new `local.properties` file in the project root and set another JVM max heap size there to override what defined in the `gradle.properties`.
> 2. Build with split ABI build option turned on, i.e. build one ABI at a time. With `ANDROID_CACHE` properly set and assuming split ABI build work for you, then you can later do a full ABIs build taking advantage of the cache objects. "devide et impera"

Thanks, build success with one abi at a time!
