### ISSUE TITLE
Window size is not restored when un-maximizing window

### ISSUE THREAD

**Issue by Science-and-Motion-Sports** [urho3d/Urho3D#2413]
This can be observed on all examples. For example, 01_HelloWorld.exe in the prebuilt Urho3D-1.6-Windows-SHARED.zip and Urho3D-1.7-MinGW-SHARED.zip (both use OpenGL) is started in windowed mode with a window size of 1024x768 pixels. When I press Alt+Enter, it goes into fullscreen mode and my monitor says it displays at 1024x768 pixels. When I press Alt+Enter again, it goes back to windows mode with 1024x768 pixels.

Now when I compile the latest version (32a4a504722b9f0fc2e2a388f3c7926fdc4e5866) and do the same test, then in fullscreen my monitor says it displays at 1920x1200 and when I go back to windowed mode with Alt+Enter the window also has this resolution (1920x1200) instead of its initial resolution (1024x768).

Log Output:

> [Thu Jan 17 14:13:14 2019] DEBUG: Initialising SDL
> [Thu Jan 17 14:13:14 2019] INFO: Opened log file C:/Users/Andre/AppData/Roaming/urho3d/logs/HelloWorld.log
> [Thu Jan 17 14:13:14 2019] INFO: Created 3 worker threads
> [Thu Jan 17 14:13:14 2019] INFO: Added resource path C:/dev/urho-native/mybuild/bin/Data/
> [Thu Jan 17 14:13:14 2019] INFO: Added resource path C:/dev/urho-native/mybuild/bin/CoreData/
> [Thu Jan 17 14:13:14 2019] INFO: Added resource path C:/dev/urho-native/mybuild/bin/Autoload/LargeData/
> [Thu Jan 17 14:13:15 2019] INFO: Adapter used NVIDIA Corporation NVS 5400M/PCIe/SSE2
> [Thu Jan 17 14:13:15 2019] INFO: Set screen mode 1024x768 windowed monitor 0
> [Thu Jan 17 14:13:15 2019] INFO: Initialized input
> [Thu Jan 17 14:13:15 2019] INFO: Initialized user interface
> [Thu Jan 17 14:13:15 2019] DEBUG: Loading resource Textures/Ramp.png
> [Thu Jan 17 14:13:15 2019] DEBUG: Loading temporary resource Textures/Ramp.xml
> [Thu Jan 17 14:13:15 2019] DEBUG: Loading resource Textures/Spot.png
> [Thu Jan 17 14:13:15 2019] DEBUG: Loading temporary resource Textures/Spot.xml
> [Thu Jan 17 14:13:15 2019] DEBUG: Loading resource Techniques/NoTexture.xml
> [Thu Jan 17 14:13:15 2019] DEBUG: Loading resource RenderPaths/Forward.xml
> [Thu Jan 17 14:13:15 2019] INFO: Initialized renderer
> [Thu Jan 17 14:13:15 2019] INFO: Initialized engine
> [Thu Jan 17 14:13:15 2019] DEBUG: Loading resource Textures/FishBoneLogo.png
> [Thu Jan 17 14:13:15 2019] DEBUG: Loading temporary resource Textures/FishBoneLogo.xml
> [Thu Jan 17 14:13:15 2019] DEBUG: Loading resource Textures/UrhoIcon.png
> [Thu Jan 17 14:13:15 2019] DEBUG: Loading resource UI/DefaultStyle.xml
> [Thu Jan 17 14:13:15 2019] DEBUG: Loading resource Textures/UI.png
> [Thu Jan 17 14:13:15 2019] DEBUG: Loading temporary resource Textures/UI.xml
> [Thu Jan 17 14:13:15 2019] DEBUG: Loading resource Fonts/Anonymous Pro.ttf
> [Thu Jan 17 14:13:15 2019] DEBUG: Font face Anonymous Pro (11pt) has 624 glyphs
> [Thu Jan 17 14:13:15 2019] DEBUG: Font face Anonymous Pro (30pt) has 624 glyphs
> [Thu Jan 17 14:13:15 2019] DEBUG: Reloading shaders
> [Thu Jan 17 14:13:15 2019] DEBUG: Loading resource Shaders/GLSL/Basic.glsl
> [Thu Jan 17 14:13:15 2019] DEBUG: Compiled vertex shader Basic(DIFFMAP VERTEXCOLOR)
> [Thu Jan 17 14:13:15 2019] DEBUG: Compiled pixel shader Basic(DIFFMAP VERTEXCOLOR)
> [Thu Jan 17 14:13:15 2019] DEBUG: Linked vertex shader Basic(DIFFMAP VERTEXCOLOR) and pixel shader Basic(DIFFMAP VERTEXCOLOR)
> [Thu Jan 17 14:13:15 2019] DEBUG: Compiled pixel shader Basic(ALPHAMAP VERTEXCOLOR)
> [Thu Jan 17 14:13:15 2019] DEBUG: Linked vertex shader Basic(DIFFMAP VERTEXCOLOR) and pixel shader Basic(ALPHAMAP VERTEXCOLOR)
> [Thu Jan 17 14:13:17 2019] INFO: OpenGL context lost
> [Thu Jan 17 14:13:17 2019] DEBUG: Loading temporary resource Textures/Ramp.xml
> [Thu Jan 17 14:13:17 2019] DEBUG: Loading temporary resource Textures/Spot.xml
> [Thu Jan 17 14:13:17 2019] DEBUG: Loading temporary resource Textures/FishBoneLogo.xml
> [Thu Jan 17 14:13:17 2019] DEBUG: Loading temporary resource Textures/UI.xml
> [Thu Jan 17 14:13:17 2019] INFO: Adapter used NVIDIA Corporation NVS 5400M/PCIe/SSE2
> [Thu Jan 17 14:13:17 2019] INFO: Set screen mode 1920x1200 fullscreen monitor 0
> [Thu Jan 17 14:13:17 2019] DEBUG: Font face Anonymous Pro (11pt) has 624 glyphs
> [Thu Jan 17 14:13:17 2019] DEBUG: Font face Anonymous Pro (30pt) has 624 glyphs
> [Thu Jan 17 14:13:17 2019] DEBUG: Compiled vertex shader Basic(DIFFMAP VERTEXCOLOR)
> [Thu Jan 17 14:13:17 2019] DEBUG: Compiled pixel shader Basic(DIFFMAP VERTEXCOLOR)
> [Thu Jan 17 14:13:17 2019] DEBUG: Linked vertex shader Basic(DIFFMAP VERTEXCOLOR) and pixel shader Basic(DIFFMAP VERTEXCOLOR)
> [Thu Jan 17 14:13:17 2019] DEBUG: Compiled pixel shader Basic(ALPHAMAP VERTEXCOLOR)
> [Thu Jan 17 14:13:17 2019] DEBUG: Linked vertex shader Basic(DIFFMAP VERTEXCOLOR) and pixel shader Basic(ALPHAMAP VERTEXCOLOR)
> [Thu Jan 17 14:13:37 2019] INFO: OpenGL context lost
> [Thu Jan 17 14:13:39 2019] DEBUG: Loading temporary resource Textures/Ramp.xml
> [Thu Jan 17 14:13:39 2019] DEBUG: Loading temporary resource Textures/Spot.xml
> [Thu Jan 17 14:13:39 2019] DEBUG: Loading temporary resource Textures/FishBoneLogo.xml
> [Thu Jan 17 14:13:39 2019] DEBUG: Loading temporary resource Textures/UI.xml
> [Thu Jan 17 14:13:39 2019] INFO: Adapter used NVIDIA Corporation NVS 5400M/PCIe/SSE2
> [Thu Jan 17 14:13:39 2019] INFO: Set screen mode 1920x1200 windowed monitor 0
> [Thu Jan 17 14:13:39 2019] DEBUG: Font face Anonymous Pro (11pt) has 624 glyphs
> [Thu Jan 17 14:13:39 2019] DEBUG: Font face Anonymous Pro (30pt) has 624 glyphs
> [Thu Jan 17 14:13:39 2019] DEBUG: Compiled vertex shader Basic(DIFFMAP VERTEXCOLOR)
> [Thu Jan 17 14:13:39 2019] DEBUG: Compiled pixel shader Basic(DIFFMAP VERTEXCOLOR)
> [Thu Jan 17 14:13:39 2019] DEBUG: Linked vertex shader Basic(DIFFMAP VERTEXCOLOR) and pixel shader Basic(DIFFMAP VERTEXCOLOR)
> [Thu Jan 17 14:13:39 2019] DEBUG: Compiled pixel shader Basic(ALPHAMAP VERTEXCOLOR)
> [Thu Jan 17 14:13:39 2019] DEBUG: Linked vertex shader Basic(DIFFMAP VERTEXCOLOR) and pixel shader Basic(ALPHAMAP VERTEXCOLOR)

**Comment by Science-and-Motion-Sports** [comment]
From debugging I found out that the Input subsystem calls graphics_->ToggleFullscreen() when I press Alt+Enter. This in turn calls Graphics::SetMode(width=1024, height=768, fullscreen=true, borderless=false, resizable=false, highDPI=false, vsync=false, tripleBuffer=false, multiSample=1, monitor=0, refreshRate=0)

Note that a resolution of 1024x768 is specified but the function sets the monitor to its native resolution fullscreen.

**Comment by Science-and-Motion-Sports** [comment]
This might be a bug in SDL. SDL_CreateWindow is called with SDL_WINDOW_FULLSCREEN and 1024x768 but it creates a window/screen size of 1920x1200 as returned by SDL_GL_GetDrawableSize and SDL_GetWindowSize

**Comment by weitjong** [comment]
Not reproducible on my Windows 7 VM as well. Tested it using Dx9. Below are the relevant logs.

```
[Sat Jan 19 17:59:51 2019] DEBUG: Window was resized to 1024x768
[Sat Jan 19 17:59:52 2019] INFO: Device lost
[Sat Jan 19 17:59:52 2019] INFO: Adapter used VirtualBox Graphics Adapter for Windows Vista and 7
[Sat Jan 19 17:59:52 2019] INFO: Set screen mode 1024x768 fullscreen monitor 0
[Sat Jan 19 17:59:57 2019] INFO: Device lost
[Sat Jan 19 17:59:57 2019] INFO: Adapter used VirtualBox Graphics Adapter for Windows Vista and 7
[Sat Jan 19 17:59:57 2019] INFO: Set screen mode 1024x768 windowed monitor 0
```

**Comment by weitjong** [comment]
> This might be a bug in SDL. SDL_CreateWindow is called with SDL_WINDOW_FULLSCREEN and 1024x768 but it creates a window/screen size of 1920x1200 as returned by SDL_GL_GetDrawableSize and SDL_GetWindowSize

I agree with your assessment. May be it's time to upgrade the SDL library.

**Comment by Science-and-Motion-Sports** [comment]
> I agree with your assessment. May be it's time to upgrade the SDL library.

I tried to upgrade the SDL library, but I gave up because it was too complicated for me to fix all the merge conflicts due to the many changes required by the Urho3D engine.

By the way, you can create a new local Git repo in order to do the SDL merge. Create one branch with the Urho3D version of libSDL 2.0.7. Then create another branch with the unchanged libSDL 2.0.7 upstream and copy the libSDL 2.0.9 upstream files over it and commit. Then you can merge this commit over the Urho3D branch of libSDL.

**Comment by weitjong** [comment]
Yeah, SDL is the toughest 3rd-party library to merge. I happened to be the one who did merge for the past few times, so I know it's a pain.

**Comment by eugeneko** [comment]
May be related:
https://github.com/urho3d/Urho3D/pull/2602

**Comment by weitjong** [comment]
@eugeneko You can merge your PR if you think it is ready.

**Comment by weitjong** [comment]
Closing this for now as the new PR has been merged.
