### ISSUE TITLE
IOS PVRTC Texture data size error

### ISSUE THREAD

**Issue by Yuki001** [urho3d/Urho3D#2414]
Hi, 
When I use PVRTC texture in IOS, I get a GL_INVALID_VALUE error in glCompressedTexImage2D function call.
I found the data size of PVRTC texture is wrong , PVRTC1_4BPP 's data size should be the same of ETC1.

OGLTexture.cpp : line 238 
function Texture::GetRowDataSize
```
    case COMPRESSED_RGB_PVRTC_4BPPV1_IMG:
    case COMPRESSED_RGBA_PVRTC_4BPPV1_IMG:
       return (unsigned)(width * 4 + 7) >> 3u;

    case COMPRESSED_RGB_PVRTC_2BPPV1_IMG:
    case COMPRESSED_RGBA_PVRTC_2BPPV1_IMG:
       return (unsigned)(width * 2 + 7) >> 3u;
```
should be changed to 
```
    case COMPRESSED_RGB_PVRTC_4BPPV1_IMG:
    case COMPRESSED_RGBA_PVRTC_4BPPV1_IMG:
        return ((unsigned)(width + 3) >> 2u) * 8; // = ETC1 

    case COMPRESSED_RGB_PVRTC_2BPPV1_IMG:
    case COMPRESSED_RGBA_PVRTC_2BPPV1_IMG:
        return ((unsigned)(width + 3) >> 2u) * 4;
```

This change makes my PVRTC texture load successful.

**Comment by weitjong** [comment]
I have not used this before, so I could be wrong. However, according to this spec then our current implementation seems to be correct. https://www.khronos.org/registry/OpenGL/extensions/IMG/IMG_texture_compression_pvrtc.txt

**Comment by Yuki001** [comment]
According to Texture.cpp : Line 150
```
unsigned Texture::GetDataSize(int width, int height) const
{
    if (IsCompressed())
        return GetRowDataSize(width) * ((height + 3) >> 2u);
    else
        return GetRowDataSize(width) * height;
}
```
The full data size for a compress image is GetRowDataSize(width) * height / 4, so GetRowDataSize(width) for compress image = 4 * real row size 

According to the spec : 
Image Size = ( max(width, 8) * max(height, 8) * 4 + 7) / 8
Real Row Size =  ( max(width, 8) * 4 + 7) / 8
GetRowDataSize(width) = ( max(width, 8) * 4 + 7) / 8 * 4 ≈ width * 2 

ETC1 's data size is somewhat correct.
((unsigned)(width + 3) >> 2u) * 8 ≈ width * 2 
so my PVRTC texture works.

**Comment by weitjong** [comment]
My bad. I was not using IDE to check the code and did not realize the code has two code paths. I wonder it would be better to simplify it to just one path, so that we can keep the formula as close to the original specs.

**Comment by sssooonnnggg** [comment]
I have the same problem when using pbr texture on iOS device，current code returns data size is 1/4 of the real data size

**Comment by weitjong** [comment]
We would accept quick fix via PR as well.

**Comment by sssooonnnggg** [comment]
#2515
