### ISSUE TITLE
High poly object material seems color filled

### ISSUE THREAD

**Issue by ilievmark** [urho3d/Urho3D#2418]
Hi everyone,
I have specific task, I hope you can help me)
I have plane with 22000 virtices and i have to set image texture on this one. When i try method FromImage to recieve material that i need, plane seems like color filled.
What can I do with this?

**Comment by Modanung** [comment]
This seems more like a case for the [support forums](https://discourse.urho3d.io/c/discussions/support).

Could you (here or there) share a screenshot of the problem you're experiencing?

**Comment by SirNate0** [comment]
Not sure if you already got help in the forums, but does your plane have correct UV coordinates?
