### ISSUE TITLE
AngelScript ListView.selected crash

### ISSUE THREAD

**Issue by orefkov** [urho3d/Urho3D#2423]
Programm crashed when call from AngelScript method `selected` for `ListView`, because in `ApiTemplates.h` in `RegisterUIElement`
`    engine->RegisterObjectMethod(className, "bool get_selected() const", asMETHOD(T, IsSelected), asCALL_THISCALL);
`
binded method `ListView::IsSelected(unsigned) const` insted of `UIElement::IsSelected() const` and stack corrupted after native call.
Need change binding to
`    engine->RegisterObjectMethod(className, "bool get_selected() const", asMETHOD(UIElement, IsSelected), asCALL_THISCALL);
`
In that case AngelScript method binded to right function.

**Comment by weitjong** [comment]
Thanks for reporting this. When there are overloaded methods then the binding should use asMETHODPR to choose the right overload.

**Comment by orefkov** [comment]
This can also be done, but in this case it is wrong.
When we register base methods for UIElements, we cannot know in advance that one of the  inherited classes can create another method with the same name. And since the registration is templated (we use macro asMETHOD(**T**,...)  ), it will always use the method from the inheriting class. But we want to register here the basic methods of UIElement for its inherited classes, and therefore it is more correct to indicate to use the method from base class UIElement. And therefore it is better to use here not the template type, but UIElement.

**Comment by orefkov** [comment]
asMETHODPR is right to use to choose from several overloaded methods from ONE class, and to clarify the choice of method from the base class it is better to use the name of the base class itself.

**Comment by weitjong** [comment]
Just got time to actually have a look at the source code. Yes, in this case I agree with you.
