### ISSUE TITLE
i cant compile my urho3d app in vs2019

### ISSUE THREAD

**Issue by tbutton2005** [urho3d/Urho3D#2428]
hello, this is my code
`#include <Urho3D/Engine/Application.h>
#include <Urho3D/Engine/Engine.h>
#include <Urho3D/Input/InputEvents.h>

using namespace Urho3D;
class MyApp : public Application
{
public:
	MyApp(Context* context) :
		Application(context)
	{
	}
	virtual void Setup()
	{
		// Called before engine initialization. engineParameters_ member variable can be modified here
	}
	virtual void Start()
	{
		// Called after engine initialization. Setup application & subscribe to events here
		SubscribeToEvent(E_KEYDOWN, URHO3D_HANDLER(MyApp, HandleKeyDown));
	}
	virtual void Stop()
	{
		// Perform optional cleanup after main loop has terminated
	}
	void HandleKeyDown(StringHash eventType, VariantMap& eventData)
	{
		using namespace KeyDown;
		// Check for pressing ESC. Note the engine_ member variable for convenience access to the Engine object
		int key = eventData[P_KEY].GetInt();
		if (key == KEY_ESCAPE)
			engine_->Exit();
	}
};
URHO3D_DEFINE_APPLICATION_MAIN(MyApp)`
and i cant compile it. visual studio writes 24 errors:
`
Ошибка	LNK2001	неразрешенный внешний символ ""public: __thiscall Urho3D::Context::Context(void)" (??0Context@Urho3D@@QAE@XZ)"	hello	C:\Users\tbutton\source\repos\hello\hello\main.obj	1	
Ошибка	LNK2001	неразрешенный внешний символ ""class Urho3D::StringHashRegister & __cdecl Urho3D::GetEventNameRegister(void)" (?GetEventNameRegister@Urho3D@@YAAAVStringHashRegister@1@XZ)"	hello	C:\Users\tbutton\source\repos\hello\hello\main.obj	1	
Ошибка	LNK2001	неразрешенный внешний символ ""public: class Urho3D::StringHash __thiscall Urho3D::StringHashRegister::RegisterString(char const *)" (?RegisterString@StringHashRegister@Urho3D@@QAE?AVStringHash@2@PBD@Z)"	hello	C:\Users\tbutton\source\repos\hello\hello\main.obj	1	
Ошибка	LNK2001	неразрешенный внешний символ ""void * __cdecl Urho3D::AllocatorReserve(struct Urho3D::AllocatorBlock *)" (?AllocatorReserve@Urho3D@@YAPAXPAUAllocatorBlock@1@@Z)"	hello	C:\Users\tbutton\source\repos\hello\hello\main.obj	1	
Ошибка	LNK2001	неразрешенный внешний символ ""void __cdecl Urho3D::AllocatorUninitialize(struct Urho3D::AllocatorBlock *)" (?AllocatorUninitialize@Urho3D@@YAXPAUAllocatorBlock@1@@Z)"	hello	C:\Users\tbutton\source\repos\hello\hello\main.obj	1	
Ошибка	LNK2001	неразрешенный внешний символ ""public: void __thiscall Urho3D::RefCounted::ReleaseRef(void)" (?ReleaseRef@RefCounted@Urho3D@@QAEXXZ)"	hello	C:\Users\tbutton\source\repos\hello\hello\main.obj	1	
Ошибка	LNK2001	неразрешенный внешний символ ""public: void __thiscall Urho3D::RefCounted::AddRef(void)" (?AddRef@RefCounted@Urho3D@@QAEXXZ)"	hello	C:\Users\tbutton\source\repos\hello\hello\main.obj	1	
Ошибка	LNK2001	неразрешенный внешний символ ""protected: void __thiscall Urho3D::HashBase::ResetPtrs(void)" (?ResetPtrs@HashBase@Urho3D@@IAEXXZ)"	hello	C:\Users\tbutton\source\repos\hello\hello\main.obj	1	
Ошибка	LNK2001	неразрешенный внешний символ ""protected: void __thiscall Urho3D::HashBase::AllocateBuckets(unsigned int,unsigned int)" (?AllocateBuckets@HashBase@Urho3D@@IAEXII@Z)"	hello	C:\Users\tbutton\source\repos\hello\hello\main.obj	1	
Ошибка	LNK2001	неразрешенный внешний символ ""public: __thiscall Urho3D::StringHash::StringHash(char const *)" (??0StringHash@Urho3D@@QAE@PBD@Z)"	hello	C:\Users\tbutton\source\repos\hello\hello\main.obj	1	
Ошибка	LNK2001	неразрешенный внешний символ ""public: int __thiscall Urho3D::Application::Run(void)" (?Run@Application@Urho3D@@QAEHXZ)"	hello	C:\Users\tbutton\source\repos\hello\hello\main.obj	1	
Ошибка	LNK2001	неразрешенный внешний символ ""public: __thiscall Urho3D::Application::Application(class Urho3D::Context *)" (??0Application@Urho3D@@QAE@PAVContext@1@@Z)"	hello	C:\Users\tbutton\source\repos\hello\hello\main.obj	1	
Ошибка	LNK2001	неразрешенный внешний символ ""private: void __thiscall Urho3D::Variant::SetType(enum Urho3D::VariantType)" (?SetType@Variant@Urho3D@@AAEXW4VariantType@2@@Z)"	hello	C:\Users\tbutton\source\repos\hello\hello\main.obj	1	
Ошибка	LNK2001	неразрешенный внешний символ ""public: class Urho3D::Variant & __thiscall Urho3D::Variant::operator=(class Urho3D::Variant const &)" (??4Variant@Urho3D@@QAEAAV01@ABV01@@Z)"	hello	C:\Users\tbutton\source\repos\hello\hello\main.obj	1	
Ошибка	LNK2001	неразрешенный внешний символ ""public: __thiscall Urho3D::TypeInfo::~TypeInfo(void)" (??1TypeInfo@Urho3D@@QAE@XZ)"	hello	C:\Users\tbutton\source\repos\hello\hello\main.obj	1	
Ошибка	LNK2001	неразрешенный внешний символ ""public: __thiscall Urho3D::TypeInfo::TypeInfo(char const *,class Urho3D::TypeInfo const *)" (??0TypeInfo@Urho3D@@QAE@PBDPBV01@@Z)"	hello	C:\Users\tbutton\source\repos\hello\hello\main.obj	1	
Ошибка	LNK2001	неразрешенный внешний символ ""void __cdecl Urho3D::AllocatorFree(struct Urho3D::AllocatorBlock *,void *)" (?AllocatorFree@Urho3D@@YAXPAUAllocatorBlock@1@PAX@Z)"	hello	C:\Users\tbutton\source\repos\hello\hello\main.obj	1	
Ошибка	LNK2001	неразрешенный внешний символ ""public: void __thiscall Urho3D::Object::SubscribeToEvent(class Urho3D::StringHash,class Urho3D::EventHandler *)" (?SubscribeToEvent@Object@Urho3D@@QAEXVStringHash@2@PAVEventHandler@2@@Z)"	hello	C:\Users\tbutton\source\repos\hello\hello\main.obj	1	
Ошибка	LNK2001	неразрешенный внешний символ ""public: virtual void __thiscall Urho3D::Object::OnEvent(class Urho3D::Object *,class Urho3D::StringHash,class Urho3D::HashMap<class Urho3D::StringHash,class Urho3D::Variant> &)" (?OnEvent@Object@Urho3D@@UAEXPAV12@VStringHash@2@AAV?$HashMap@VStringHash@Urho3D@@VVariant@2@@2@@Z)"	hello	C:\Users\tbutton\source\repos\hello\hello\main.obj	1	
Ошибка	LNK2001	неразрешенный внешний символ ""public: virtual __thiscall Urho3D::Object::~Object(void)" (??1Object@Urho3D@@UAE@XZ)"	hello	C:\Users\tbutton\source\repos\hello\hello\main.obj	1	
Ошибка	LNK2001	неразрешенный внешний символ ""class Urho3D::Vector<class Urho3D::String> const & __cdecl Urho3D::ParseArguments(wchar_t const *)" (?ParseArguments@Urho3D@@YAABV?$Vector@VString@Urho3D@@@1@PB_W@Z)"	hello	C:\Users\tbutton\source\repos\hello\hello\main.obj	1	
Ошибка	LNK2001	неразрешенный внешний символ ""public: void __thiscall Urho3D::Engine::Exit(void)" (?Exit@Engine@Urho3D@@QAEXXZ)"	hello	C:\Users\tbutton\source\repos\hello\hello\main.obj	1	
Ошибка	LNK2001	неразрешенный внешний символ "_main"	hello	C:\Users\tbutton\source\repos\hello\hello\MSVCRT.lib(exe_main.obj)	1	
Ошибка	LNK1120	неразрешенных внешних элементов: 23	hello	C:\Users\tbutton\source\repos\hello\Release\hello.exe	1	
`
im link Urho3D_d.lib, and include urho3d folders. what am i doing wrong? please, help me, i want create 3d game using this engine!

**Comment by weitjong** [comment]
Please do not use our issue tracker for personal questions regarding build problem. Use our forum for support instead.

**Comment by tbutton2005** [comment]
ok, where is forum?

**Comment by LeithKetchell** [comment]
2001 is a linker error : unresolved external symbol.
My guess is that you didn't add the lib to the linker settings in MSVC, or that you didn't add the path to it.
Are you new to MSVC?

**Comment by LeithKetchell** [comment]
at least we know that the compiler completed with success, so urho app DID compiler, because the linker runs after compiling completes.
