### ISSUE TITLE
I CAN NOT MAKE URHO3D!!!

### ISSUE THREAD

**Issue by tbutton2005** [urho3d/Urho3D#2436]
...
[ 53%] Built target GLEW
[ 53%] Generating toluabind.c and toluabind.h
Scanning dependencies of target tolua++
[ 53%] Building C object Source/ThirdParty/toluapp/src/bin/CMakeFiles/tolua++.dir/tolua.c.o
[ 53%] Building C object Source/ThirdParty/toluapp/src/bin/CMakeFiles/tolua++.dir/generated/toluabind.c.o
[ 53%] Linking C executable ../../../../../bin/tool/tolua++
../../../Lua/libLua.a(loslib.c.o): In function `os_tmpname':
loslib.c:(.text+0x230): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
[ 53%] Built target tolua++
make[2]: *** Нет правила для сборки цели «/home/satomi2005/ /Urho3D/Source/Urho3D/Container/Str.h», требуемой для «Source/Urho3D/Precompiled.h.Release.pch.trigger».  Останов.
CMakeFiles/Makefile2:1428: recipe for target 'Source/Urho3D/CMakeFiles/Urho3D.dir/all' failed
make[1]: *** [Source/Urho3D/CMakeFiles/Urho3D.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
satomi2005@satomi2005-P85-D3:~/Рабочий стол/Urho3D/build$

**Comment by weitjong** [comment]
You should provide more information like how you generated your build tree, what build options you use, etc. Also this is not the place to solve individual problem.

**Comment by tbutton2005** [comment]
i just run this commands:
1. git clone https://github.com/urho3d/Urho3D
2. cd Urho3D
3. mkdir build
4. cd build
5. cmake ..
6. make

**Comment by ArnisLielturks** [comment]
@tbutton2005 use our generated scripts to automate build. 
```
git clone
./script/cmake_generic.sh build
cd build
make
```
