### ISSUE TITLE
Current trunk fails to build RakNetSocket

### ISSUE THREAD

**Issue by Triangle345** [urho3d/Urho3D#2440]
I'm using mingw gcc version 8.3 on Win 10 x64. I cloned the current trunk, ran cmake configure and generate. When building, i'm getting the following error:

```
Urho3D\Source\ThirdParty\SLikeNet\Source\src\RakNetSocket2_Berkley_NativeClient.cpp:105:53: error: call of overloaded 'inet_ntop(int, in_addr*, char*&, int)' is ambiguous
  inet_ntop(AF_INET, &sockaddr_ipv4->sin_addr, ip, 65);
```

**Comment by ArnisLielturks** [comment]
We have our own generated `linux_adapter.h` and `linux_adapter.cpp` which contains the missing `inet_ntop` methods and couple more methods which were missing from the MinGW that was used when this library was implemented. 

Definitions here:
https://github.com/urho3d/Urho3D/blob/master/Source/ThirdParty/SLikeNet/Source/src/linux_adapter.cpp#L332
https://github.com/urho3d/Urho3D/blob/master/Source/ThirdParty/SLikeNet/Source/include/slikenet/linux_adapter.h#L24

Could you try commenting out these defintions and try again? Maybe this file needs and update for the newest MinGW versions.

**Comment by Triangle345** [comment]
After removing that function, everything compiled.

**Comment by ArnisLielturks** [comment]
@weitjong  Latelly there has been a lot of issues regarding different versions of MinGW. Versions are inconsistent and each of them contains different set of methods that are needed for the SLikeNet library. Is there any MinGW preprocessor values which we could use to check the actual MinGW version?

**Comment by ArnisLielturks** [comment]
Seems like there is `__MINGW32_MAJOR_VERSION`, `__MINGW32_MINOR_VERSION`, `__MINGW64_VERSION_MAJOR`, `__MINGW64_VERSION_MINOR` defines that we could use.

**Comment by ArnisLielturks** [comment]
@Triangle345 could you provide the MinGW version header values in your case?

**Comment by Triangle345** [comment]
I have the following:

```
#define __MINGW64_VERSION_MAJOR 6
#define __MINGW64_VERSION_MINOR 0

#define __MINGW32_MAJOR_VERSION 3
#define __MINGW32_MINOR_VERSION 11
```

**Comment by ArnisLielturks** [comment]
@Triangle345 could you help testing the possible fix in the `slikenet-build-updates` branch?
https://github.com/urho3d/Urho3D/commits/slikenet-build-updates

**Comment by Triangle345** [comment]
This branch seemed to give me an unrelated error while building. Do i need to set any specific flags?

```
Urho3D/Source/ThirdParty/SLikeNet/Source/include/slikenet/linux_adapter.h:88:33: error: redefinition of 'template<long long unsigned int BufferSize> int vsnprintf_s(char (&)[BufferSize], size_t, const char*, va_list)'
 template<size_t BufferSize> int vsnprintf_s(char (&buffer)[BufferSize], size_t count, const char *format, va_list argptr)
```

**Comment by ArnisLielturks** [comment]
@Triangle345 Thanks for the results! The error message is something that I was expecting since I packed a bunch of methods under the same CMake condition, will update that.

**Comment by ArnisLielturks** [comment]
@Triangle345 I think I managed to fix the build issues. At least that's what I see from the CI builds and the ones I tested manually.

**Comment by Triangle345** [comment]
```
RakNetSocket2_Berkley_NativeClient.cpp: In function 'void DomainNameToIP_Berkley_IPV4(const char*, char*)':
slikenet-build-updates\Source\ThirdParty\SLikeNet\Source\src\RakNetSocket2_Berkley_NativeClient.cpp:105:53: error: call of overloaded 'inet_ntop(int, in_addr*, char*&, int)' is ambiguous
  inet_ntop(AF_INET, &sockaddr_ipv4->sin_addr, ip, 65);
```

**Comment by ArnisLielturks** [comment]
@Triangle345 this is the line that obviously fails on your machine:
https://github.com/urho3d/Urho3D/blob/slikenet-build-updates/Source/ThirdParty/SLikeNet/CMakeLists.txt#L28

It is unable to compile the following code:
```
#include <arpa/inet.h>

int main() {
    struct sockaddr_in sa;
    char str[INET_ADDRSTRLEN];
    inet_pton(AF_INET, "192.0.2.33", &(sa.sin_addr));
    inet_ntop(AF_INET, &(sa.sin_addr), str, INET_ADDRSTRLEN);
}
```
and marks the inet_ntop functions as missing. I would guess that the `#include <arpa/inet.h>` line fails due to missing file. 

Could you try to compile small application using the provided code? If that doesnt work, could you try to replace 
```
#include <arpa/inet.h>
```
with 
```
#include <winsock2.h>
#include <ws2tcpip.h>
```

Thanks in advance!

**Comment by Triangle345** [comment]
correct, i'm able to compile the winsock includes by using the mingw ws2_32 lib but not arpa/inet.h

**Comment by ArnisLielturks** [comment]
And if you change the lines https://github.com/urho3d/Urho3D/blob/slikenet-build-updates/Source/ThirdParty/SLikeNet/CMakeLists.txt#L27-L32 with these:
```
        check_cxx_source_compiles ("#include <arpa/inet.h>\nint main() {\n    struct sockaddr_in sa;\n    char str[INET_ADDRSTRLEN];\n    inet_pton(AF_INET, \"192.0.2.33\", &(sa.sin_addr));\n    inet_ntop(AF_INET, &(sa.sin_addr), str, INET_ADDRSTRLEN);\n}" INET_FUNCTIONS_EXISTS_1)
	check_cxx_source_compiles ("#include <winsock2.h>\n#include <ws2tcpip.h>\nint main() {\n    struct sockaddr_in sa;\n    char str[INET_ADDRSTRLEN];\n    inet_pton(AF_INET, \"192.0.2.33\", &(sa.sin_addr));\n    inet_ntop(AF_INET, &(sa.sin_addr), str, INET_ADDRSTRLEN);\n}" INET_FUNCTIONS_EXISTS_2)
	if (NOT INET_FUNCTIONS_EXISTS_1 AND NOT INET_FUNCTIONS_EXISTS_2)
	    add_definitions(-DINET_FUNCTIONS_MISSING=1)
	endif()
```

That might just do the trick.

**Comment by Triangle345** [comment]
hmm i replaced those lines and i'm still getting 

```
\Urho3D\Source\ThirdParty\SLikeNet\Source\src\RakNetSocket2_Berkley_NativeClient.cpp:105:53:
error: call of overloaded 'inet_ntop(int, in_addr*, char*&, int)' is ambiguous
  inet_ntop(AF_INET, &sockaddr_ipv4->sin_addr, ip, 65);
```

I will need to rerun after i get back from work, maybe I missed something.

**Comment by ArnisLielturks** [comment]
It's probably because of the `ws2_32 lib` library which might not be available when cmake checks are run. Will have to look up how to correctly add it.

**Comment by Triangle345** [comment]
Just to confirm.. i'm getting the same results I described.

**Comment by ArnisLielturks** [comment]
@Triangle345 I still have few ideas how to possibly fix the issue:

replace these lines https://github.com/urho3d/Urho3D/blob/slikenet-build-updates/Source/ThirdParty/SLikeNet/CMakeLists.txt#L26-L33
with 
```
if (NOT HAVE_INET_NTOP)
    add_definitions(-DINET_FUNCTIONS_MISSING=1)
endif()
```

**Comment by Triangle345** [comment]
no change after applying the above

**Comment by ArnisLielturks** [comment]
@Triangle345 thanks for helping out! 
One more thing to try is this:
replace line https://github.com/urho3d/Urho3D/blob/slikenet-build-updates/Source/ThirdParty/SLikeNet/CMakeLists.txt#L26
with:
```
if (NOT CMAKE_HOST_SYSTEM_NAME MATCHES "Windows")
```

**Comment by Triangle345** [comment]
this worked. Thanks!

**Comment by ArnisLielturks** [comment]
Sorry for the delayed response.
Yesterday I added additional changes to the `slikenet-build-updates` branch which hopefully fixed the issues you faced. Haven't got any errors using our CI tools. Fingers crossed that everything works as expected. If it does, changes will go right in the master. (fingers crossed)

**Comment by Triangle345** [comment]
yep looks good on my end

**Comment by ArnisLielturks** [comment]
Thanks! Then I'm closing this issue.
