### ISSUE TITLE
Release builds are broken

### ISSUE THREAD

**Issue by gogoprog** [urho3d/Urho3D#2441]
Hello, 

I tested the following tags:
- 1.4 : build error
- 1.5 : visual glitches
- 1.6 : visual glitches
- 1.7 : visual glitches

But [master] is fine so I think it is time for a new release and remove the wrongly built ones.

The visual glitches look like this:
![2019-04-11_11:55:14](https://user-images.githubusercontent.com/1249453/55948387-b24c6180-5c50-11e9-94b6-696610405343.png)

This is the Skeletal Animation sample. It seems that all samples are broken.

**Comment by weitjong** [comment]
I supposed you are using newer GCC. if so, it is a known issue that only had been fixed in master branch. As we don’t do backport, the issue will surface in all the old releases.

**Comment by gogoprog** [comment]
Thanks for the info.
The related gcc issue was #2326
