### ISSUE TITLE
 AssetImporter as dotnet tool?

### ISSUE THREAD

**Issue by andmos** [urho3d/Urho3D#2453]
Just a quick request, would be nice to have the  AssetImporter CLI packaged as a `dotnet tool`.
[more info about dotnet tool](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools-how-to-create). I currently just run it from the global NuGet cache, but the experience would be better via `dotnet tool`. 

just a thought 😃

**Comment by Modanung** [comment]
The [asset importer](https://github.com/assimp/assimp) is a third-party library.
