### ISSUE TITLE
E_CONNECTFAILED not sent on second attempt

### ISSUE THREAD

**Issue by TheComet** [urho3d/Urho3D#2454]
Two bugs. E_SERVERDISCONNECT is sent in response to ```Connect()``` and E_CONNECTFAILED is only sent once.

Steps to reproduce:

1) Call ```Connect("127.0.0.1", 6666)``` (with no server application running)
2) E_CONNECTFAILED is sent after timeout occurs (this is fine). E_SERVERDISCONNECT is not sent.
3) Call ```Connect("127.0.0.1", 6666)``` again. For some reason, this sends E_SERVERDISCONNECT immediately (bug?)
4) Get log message "Failed to connect to server", but E_CONNECTFAILED is never sent again, no matter how many times you retry. E_SERVERDISCONNECT is not sent.
5) Call ```Connect("127.0.0.1", 6666)``` again. Again, this sends E_SERVERDISCONNECT (bug?) and E_CONNECTFAILED is never sent, even after timeout.

Expected behavior:
1) Call ```Connect("127.0.0.1", 6666)``` (with no server application running)
2) E_CONNECTFAILED is sent after timeout occurs.
3) E_SERVERDISCONNECT is never sent, because we never successfully connected. I expect E_SERVERDISCONNECT only to be sent if E_SERVERCONNECT is sent.

**Comment by ArnisLielturks** [comment]
Fixed in the latest commit by adding multiple network status checks + added new events for that.
