### ISSUE TITLE
GLSL version of LitSolid shader apparently does not support NOUV define.

### ISSUE THREAD

**Issue by UNDEFINED-BEHAVIOR** [urho3d/Urho3D#2457]
Original issue
https://github.com/rokups/rbfx/issues/104

NOUV define exists in HLSL version of LitSolid shader
https://github.com/urho3d/Urho3D/blob/master/bin/CoreData/Shaders/HLSL/LitSolid.hlsl

But not GLSL's
https://github.com/urho3d/Urho3D/blob/master/bin/CoreData/Shaders/GLSL/LitSolid.glsl

was this intentional?

**Comment by 1vanK** [comment]
https://urho3d.github.io/documentation/1.6/_a_p_i_differences.html

**Comment by UNDEFINED-BEHAVIOR** [comment]
Based on this explanation webGL is also apparently pretty strict then.

I don't have time to prepare a sample right now. symptom is, webgl's glDrawElement will complain about lack of vertex attribute number 2, when I only defined 0 and 1 (pos, normal), error messages to these: https://stackoverflow.com/questions/21200386/webgl-gl-error-gl-invalid-operation-gldrawelements-attempt-to-access-out-of

But will work again when I also define UV data so this NOUV define is a suspect. 
Happens on both CustomGeometry and StaticModel that is created grammatically and updated every frame.
