### ISSUE TITLE
Updating Static Model Geometries

### ISSUE THREAD

**Issue by SirNate0** [urho3d/Urho3D#2470]
The StaticModel class stores it's own BoundingBox and list of Geometries. If we update one of the geometries to have different vertices, thus changing the bounding box, StaticModel does not update it's own BoundingBox (nor will it update it if we change the underlying Model's BoundingBox). Obviously, this causes problems with models having incorrect bounding boxes, but the only way to correct this (that I can tell) is to remove the Model from the static model with `staticModel->SetModel(nullptr)` and then re-add the modified model `staticModel->SetModel(model)` * since `StaticModel::SetBoundingBox()` is protected. Is there a reason not to make `StaticModel::SetBoundingBox()` public? Or would it be better to have StaticModel listen for some sort of ModelChanged event that the model can send when updated?

I believe there's a similar issue with a model allowing you to change it's number of geometries and the static model not updating to reflect the models changes without a similar re-adding of the model.

*Edit: Unfortunately, this seems to cause the static model to lose all of it's materials since it resizes the drawable batches to 0 in the process of doing this.

**Comment by Modanung** [comment]
> Or would it be better to have StaticModel listen for some sort of ModelChanged event that the model can send when updated?

This option makes most sense to me.

-----

> *Edit: Unfortunately, this seems to cause the static model to lose all of it's materials since it resizes the drawable batches to 0 in the process of doing this.

By this you mean the setting to `nullptr` and re-adding the model right?

**Comment by eugeneko** [comment]
What if you send `E_RELOADFINISHED` from that model after you change it?

**Comment by SirNate0** [comment]
I believe this is still relevant, unless someone else has gone and fixed it.

**Comment by eugeneko** [comment]
Did you try suggestion from comment above?

**Comment by SirNate0** [comment]
My bad, I hadn't gotten to that yet. It did work, though, thank you for the suggestion. But it crashed initially because in handling the event it reset the model_ SharedPtr, which was the only reference to it. Switching `Model* currentModel` to `SharedPtr<Model> currentModel` in `StaticModel::HandleModelReloadFinished()` should fix this though.

If you want this issue can be closed now. Either way I'll submit a PR in a couple days with the correction I described (and close it then if it's not already).

**Comment by eugeneko** [comment]
`StaticModel` was probably never tested with unreferenced model, since `ResourceCache` keeps 1 ref by default, and the reload event is invoked from `ResourceCache`.

I think that triggering reload event is the most proper way to fix the initial issue.
Therefore, `HandleModelReloadFinished` shall be patched like you said.

**Comment by SirNate0** [comment]
Sounds good. Would it be a good idea to add such an event to Sample 34_DynamicGeometry as an example for other users?

**Comment by Modanung** [comment]
`BillboardSet`s have a `Commit()` function. Maybe we could apply the same logic here?

**Comment by eugeneko** [comment]
The internal state of `BillboardSet` is edited by its member functions and the `Commit` is used to finalize the edit.
In case of `StaticModel`, we don't have any changing internal state that has to be committed.

`Model` is external resource that may be changed anywhere, without any knowledge about being used by some `StaticModel` somewhere else in the code.

It is probably the `Resource` who shall have `Commit`, not the user like `StaticModel`.

**Comment by SirNate0** [comment]
> It is probably the `Resource` who shall have `Commit`, not the user like `StaticModel`.

I agree with the idea, but if it's just Model that we're adding the feature to I think Model should be there only class with a `Commit` function, otherwise we risk implying to the user that changes won't be made (it at least complete) in the other classes until `Commit` is called. Potentially this is not an issue and allows extra preparation for the future if other Resources end up needing a `Commit` function later, as it would just be a no-op for now.

I do question the naming a bit, though. It seems weird to me having `Model::Commit` basically be a wrapper for `SendEvent(E_RELOADFINISHED)`. Further, it is unclear to me whether `Commit` should be called in the loading process.

**Comment by Modanung** [comment]
Ok, so maybe the situation is not similar enough to aim for naming consistency.
How about a public `UpdateBoundingBox`?

**Comment by eugeneko** [comment]
> I do question the naming a bit, though. It seems weird to me having Model::Commit basically be a wrapper for SendEvent(E_RELOADFINISHED).

> otherwise we risk implying to the user that changes won't be made (it at least complete) in the other classes until Commit is called

@SirNate0 I don't really like this naming too. "Commit()" is too vague and misleading.
`SendEvent(E_RELOADFINISHED)` doesn't really commit anything into Resource.
It commits changes into listeners.

`SendResourceUpdateFinished`/`SendResourceUpdated`, maybe?

> How about a public UpdateBoundingBox?

@Modanung it doesn't really solve anything in the grand scheme of things.
It is the `Model` we work with and change. We may know nothing about whether it's used by `StaticModel` or `CollisionShape` or something else. There are dozens of reload handlers in the Urho, and all these places are susceptible to this issue.

Maybe I'm missing something tho... What benefits of exposing private interface of `StaticModel` do you see?

**Comment by SirNate0** [comment]
Looking through the code a bit more, `Commit` is growing on me. I don't like `UpdateBoundingBox` as I'm pretty sure a few other things get updated as well, like the number of geometries (which I'd forgotten about until looking through the code). What do you guys think of `CommitUpdate` or `CommitManualUpdate`?
