### ISSUE TITLE
[1.7.1] Cant disable Terrain editor's painting brush

### ISSUE THREAD

**Issue by IlyaStuurFedorov** [urho3d/Urho3D#2471]
Windows 7/10

After creating and sculpting a terrain a bit there is no way to properly exit terrain editor, so paintbrush would just be active until editor restart.

**Comment by ArnisLielturks** [comment]
Does the same happens when using editor from the master branch?

**Comment by IlyaStuurFedorov** [comment]
[I just tried it out and can confirm that this problem is still presented in the master.](https://i.imgur.com/wRN5A1M.png)
