### ISSUE TITLE
AssetImporter animation keyframes skipped when start time is higher than zero

### ISSUE THREAD

**Issue by costinsandu** [urho3d/Urho3D#2484]
When using AssetImporter to import animation and the start time (in the imported file) is higher than zero, some keyframes will be skipped. 
The issue is caused by the code in function BuildAndSaveAnimations (AssetImporter.cpp) and is present in the latest commit (a476f0c40114b92c2637145c24f50ccef6de5d3c).
kf.time_ is calculated at lines 1430 to 1435 by subtracting the start time, but later is compared (at line 1474) with original start time and the subtraction of start time occurs again even if it passes the test. It can be fix either by not subtracting the start time when is first calculated or by adjusting the comparison and adjustment at line 1474 and  1476,

**Comment by Modanung** [comment]
The asset importer is an external library with [its own issue tracker on GitHub](https://github.com/assimp/assimp/issues).
