### ISSUE TITLE
cling based C++ as scripting language / hot code reload

### ISSUE THREAD

**Issue by blockspacer** [urho3d/Urho3D#2488]
cling based C++ as scripting language / hot code reload
Why? Able to run C++ script in runtime or compile it for max speed ( as in example https://github.com/derofim/cling-cmake )

> **HOT code reload**
> possible approaches:
> 
> store app state
> fix cling undo for files
> https://root-forum.cern.ch/t/loading-unloading-class-as-interpreted-macro-in-cling-multiple-times/32976/2
> 
> execute cling code to change callbacks & variables
> nested cling::Interpreter with multiple cling::MetaProcessor
> IDK how to do it, but you can create child cling::Interpreter

**Comment by iSLC** [comment]
You already have c++ at your disposal for max speed. In case you were wondering why.

Seriously take the prose take the cons and weigh them.

Let me throw a few cons:

Extra tooling necessary to work with the engine.
Duplicate functionality. You already come from c++, there's nothing extra to benefit

**Comment by 1vanK** [comment]
https://discourse.urho3d.io/t/c-as-the-scripting-language/2880

**Comment by blockspacer** [comment]
> Seriously take the pros take the cons and weigh them.

**web builds (emscripten) without scripting size engine overhead, only C++ to WASM**
**embedded builds without scripting engine size overhead, only C++**
**cling requires no/very minimal binding to C++**
tooling may be optional (dev/devCling/release/e.t.c.)
You can use cling for fastest debug (dev) builds, than for release builds you will get compiled C++

**Comment by blockspacer** [comment]
Other similar thread: https://discourse.urho3d.io/t/use-clang-to-compile-urho/3723

**Comment by iSLC** [comment]
> **web builds (emscripten) without scripting size engine overhead, only C++ to WASM**
> **embedded builds without scripting engine size overhead, only C++**

So you are saying that Clang/LLVM is smaller than the current scripting engine? Unless I misinterpreted `scripting engine`.

Because by the looks of it Cling does imply embedding Clang/LLVM into your application.

**Comment by blockspacer** [comment]
> > **web builds (emscripten) without scripting size engine overhead, only C++ to WASM**
> > **embedded builds without scripting engine size overhead, only C++**
> 
> So you are saying that Clang/LLVM is smaller than the current scripting engine? Unless I misinterpreted `scripting engine`.
> 
> Because by the looks of it Cling does imply embedding Clang/LLVM into your application.

End user usually can`t modify scripts. Some apps may benefit from script-to-native 'conversion'.
Develop much faster with Cling help (dev/debug build), release same code compiled without Cling at all (release build).

Also: you can embed Cling for some platforms even in release build, if you want.
