### ISSUE TITLE
FR: Shader Source translator

### ISSUE THREAD

**Issue by Angramme** [urho3d/Urho3D#2493]
This feature requests idea is inspired from bgfx. What if Urho had system for translating HLSL code to GLSL automatically. 
There are several benefits:
 - Easier and faster prototyping
 - Lower entry point for contributor features ( for example if someone writes a SSAO shader in DirectX he/she can publish it directly for cross-platform use )
 - make it optional, when the xml parser for materials doesn't find a glsl shader it automatically gets the hlsl version and translates it.

As well as cons:
 - some overhead, obviously ( although a cache might be implemented similar to the one used for DirectX when "compiling" shader source, where the translated shaders would be saved )
 - possible compatibility issues
 - API and/or source inconsistency?

I know that it might be not possible to implement such a feature, but I would really enjoy it :)

If it's not possible, then meaby attach a tool so the source can be translated "manually" (with the tool) and shipped to the user "pre-translated".

I don't know much about game engine architecture so I leave the decision to you.

Btw I think it's even possible to "borrow" some of bgfx's already written code to do the task.

**Comment by eugeneko** [comment]
I was thinking about it. I'm going to try it eventually.
The most promising library for me is this one:
https://github.com/floooh/sokol-tools/blob/master/docs/sokol-shdc.md
It basically uses only existing supported tools with little manual code.

**Comment by Angramme** [comment]
Cool, sorry for a delayed response :) I don't check my emails often. Yeah if you can do this that would be awesome 👍 I really think it would be a useful feature.

**Comment by JSandusky** [comment]
If precompiling is acceptable then C# -> HLSL/GLSL transpiling would be pretty easy to do. `Microsoft.CodeAnalysis.CSharp` makes C# transpiling fairly easy.

Being able to run shaders through a competent debugger (MSVC) in a limited software mode would be a huge boon. Much bigger win when looking at compute shaders. 

I've been transpiling C#->C++/Javascript for a while now and for HLSL/GLSL I think pinning down the interface (ie. does vertex data need to be a struct?, MRT as `float[] MyShader.Fragment(...)`, etc) would be way more painful work than the transpiler itself.

**Comment by Angramme** [comment]
> If precompiling is acceptable then C# -> HLSL/GLSL transpiling would be pretty easy to do. `Microsoft.CodeAnalysis.CSharp` makes C# transpiling fairly easy.
> 
> Being able to run shaders through a competent debugger (MSVC) in a limited software mode would be a huge boon. Much bigger win when looking at compute shaders where whats being done can get pretty dicey.
> 
> I've been transpiling C#->C++/Javascript for a while now and for HLSL/GLSL I think pinning down the interface (ie. does vertex data need to be a struct?, MRT as `float[] MyShader.Fragment(...)`, etc) would be way more painful work than the transpiler itself.

wow, that would be really cool! being able to write everything in the same language. I don't quite understand the rest of what you have said but I agree.

**Comment by JSandusky** [comment]
@Angramme someone's already whipped one (C#->GLSL/HLSL) together: https://github.com/mellinoe/ShaderGen doesn't look bad though I don't dig the way conditionals are dealt with (but `mcpp` or w/e could be used ahead of it so *meh*).

Khronos' glslang-validator and spirv-cross are quite stable today though - though using the HLSL -> GLSL parts are still something that you'd want to do offline because it's way too slow to do on the fly.

**Comment by Angramme** [comment]
So it exists, awesome. Though you say that it is slow. At least it can be done offline. I think it is a viable solution. Thank you for research!

**Comment by Modanung** [comment]
Problem solved!

@weitjong || @ArnisLielturks Could this issue be closed?

**Comment by Angramme** [comment]
problem solved! good day!
