### ISSUE TITLE
Blending in render textures doesn't work right

### ISSUE THREAD

**Issue by MystMagus** [urho3d/Urho3D#2500]
If you set for UI to render to a texture then even if the blend mode is set to BLEND_ALPHA it looks like the pixels are simply being replaced while not fully transparent. Attached is a modification of sample 48 that saves the render texture.

Note that the problem isn't really visible on the cube itself, however if you save the texture (of if you render it on a StaticSprite2D, which is what I do in my own project), then you can see the transparency. In the example I made the button transparent, but you can also see it in the text.

I've tried really hard to solve this on my own but I'm out of ideas, so I hope someone who knows the engine better will take a look at it.

[48_Hello3DUI.zip](https://github.com/urho3d/Urho3D/files/3582851/48_Hello3DUI.zip)

**Comment by Modanung** [comment]
Could you ask your question in the [support category of the forums](https://discourse.urho3d.io/c/discussions/support) as well? In case it's not a bug.

Please link to this issue on order tie the discussions together.

**Comment by MystMagus** [comment]
Certainly.

**Comment by MystMagus** [comment]
I realized that the problem goes beyond UI and can be gotten at least with Urho2D as well (dunno about general 3d, since I only use UI and Urho2D). Here is a better example I put together: 
[blend_issue.zip](https://github.com/urho3d/Urho3D/files/3610279/blend_issue.zip)

**Comment by SuperWangKai** [comment]
May it be the issue with background color? Urho's background color is from the default zone if you don't set a new zone. You may try this, if you see red (you can change the color), that's the root cause - 

```c++
GetSubsystem<Renderer>()->GetDefaultZone()->SetFogColor(Color(1.0f, 0.0f, 0.0f));
```

**Comment by MystMagus** [comment]
Thank you for the response.

It may be so. As I commented in the example
		// The alpha for the fog needs to be 0 in order for the render texture to get transparency.
		// Otherwise the transparent parts are set to the fog color.
I'm not sure what the behavior for that should be. If I set a color (red in this example) and keep the alpha as 0 then the color of the square is the same as in the example now, whereas otherwise the render texture background is set to red, so you can't see the green background image at all (though the square is still green when doing indirect rendering).
