### ISSUE TITLE
Improve Materials Documentation

### ISSUE THREAD

**Issue by SirNate0** [urho3d/Urho3D#2501]
The [Materials](https://urho3d.github.io/documentation/HEAD/_materials.html) documentation page is a wonderful resource, but presently it does not specify what the default values will be. I don't mind fixing this myself over the next few days, but I was wondering what people thought would be the best way to specify it? Some options I've thought of:

1. A separate XML section with values populated with the default material values
2. Comments within the existing section `<cull value="cw|ccw|none" /><!--default ccw-->`
3. A secondary attribute `<cull value="cw|ccw|none" default="ccw" />` and perhaps a note that the default attributes specify the default for the value, they are not required in the material file itself
4. Something along the lines of `<cull value="cw|ccw|none = ccw" />`
5. Minimal effort: just adding a reference to Material::ResetToDefaults() and having people look in the code (bonus: the documentation won't get out of date).

My preferred approaches are 1, which then provides a concrete example of a material definition in the documentation, and 3, which places the information next to the relevant part of the specification while avoiding looking cleaner/clearer (in my opinion) than 4. Downsides of 1 - it basically duplicates the documentation that is there presently. Downsides of 3 - it could lead to some confusion about a default attribute being available to set the default for the engine.

For those interested, default values are set in `Material::ResetToDefaults()`

**Comment by weitjong** [comment]
IMHO you can try to use the HTML tags (e.g. ```<strong>``` or ```<span class='default'>``` to enclose  the text representing the default value of an attribute. The CSS could be adjusted to style how it will looks afterward. A meta program/script to auto update the tag if/when the code default value actually change will be just a bonus.

**Comment by SirNate0** [comment]
While I certainly like the idea of using formatting to display it instead, I ended up not taking that approach because of the increased difficulty in maintaining the documentation that would impose and because I felt there wouldn't be a good way to do that for the options that aren't enumerated (the technique name, for example, rather than the cull value).
