### ISSUE TITLE
More accurate 3D audio with soloud library

### ISSUE THREAD

**Issue by codec-abc** [urho3d/Urho3D#2504]
Hi,

Yesterday I discovered [soloud](http://sol.gfxile.net/soloud/) which seems to be a powerful audio library with a permissive license which fit Urho. Theoretically, it should provide more accurate 3D audio than the current implementation with SDL.

Do you think it might be a good idea to try to integrate this library in Urho?

**Comment by weitjong** [comment]
You can follow the discussion in the forum, already the thread seems to have gone cold.

https://discourse.urho3d.io/search?q=soloud
