### ISSUE TITLE
Compiler Error C2118 in 32 bit compilation.

### ISSUE THREAD

**Issue by vitormassaro** [urho3d/Urho3D#2545]
SDL has not a specific configuration for 32 bit compilation.
Negative subscript: The value defining the array size is larger than the maximum array size or smaller than zero.

**Comment by weitjong** [comment]
There is not enough context on how to reproduce your build issue. Our CI build jobs have tested both 64-bit and 32-bit build and they are fine. FYI, we do not use hard-coded configuration file for SDL. Our build system detects and generates a custom config for SDL and other subsystems used by Urho3D.

**Comment by vitormassaro** [comment]
I compiled to 32 bit with success after it. The problem is the Windows SDK 10.0.18362.0 for 32 bit compilation only. Windows SDK 10.0.16299.0 work fine on 32 and 64 bit. the problem is in winnt.h file located in Windows SDK path. Array got values higher than max array size or less than 0. This files are header from SDK.

**Comment by weitjong** [comment]
Thanks for the update. In that case there is nothing we can do to avoid it.
