### ISSUE TITLE
Unnecessary explicit specifier in smart pointers. 

### ISSUE THREAD

**Issue by VladBolotov** [urho3d/Urho3D#2551]
Hello. I was looking into Urho guts and found one weird thing. Urho3D::WeakPtr and Urho3D::SharedPtr have the ctors from a raw pointers BUT they have `explicit` specifier. So… they can not be used for copy initialization from a raw pointer. And It’s looks weird for me. Consider the next example: 
```C++
class Some : public Urho3D::RefCounted {
};
```
```C++
void Assigment() {
    Some *ptr = new Some;
    Urho3D::SharedPtr<Some> sPtr;
    sPtr = ptr; //Okay.
    Urho3D::WeakPtr<Some> wPtr;
    wPtr = ptr; //Okay
}
```

```C++
void Construction() {
    Some *ptr = new Some;
    Urho3D::SharedPtr<Some> sPtr = ptr; //ERROR: No suitable ctor since SharedPtr(T* ptr) have explicit specifier.
    Urho3D::WeakPtr<Some> wPtr = ptr; //ERROR: No suitable ctor since WeakPtr(T* ptr) have explicit specifier.
}
```

Is this desired behavior or am I missing something?

**Comment by eugeneko** [comment]
In perfect world there shouldn't be any implicit conversion between raw and smart pointer.
Making these ctors implicit too will not make things _much_ worse, but it would be yet another step to implicit casting hell.
I don't really care in this case, but I wish we have moved another direction in general.

**Comment by VladBolotov** [comment]
> In perfect world there shouldn't be any implicit conversion between raw and smart … 

I am strongly agreed that explicit is better than implicit. 
What I am trying to say - this ‘explicit’ thing in ctor hurts my feeling of beauty and IMHO make API inconsistent since assignment and copy initialization code will do much the same thing. That is why I was asking about – is this desired behavior (for what reason, I am curious)? Or explicit was added occasionally?

> I don't really care in this case, but I wish we have moved another direction in general.

What is your suggestions?

**Comment by eugeneko** [comment]
> What is your suggestions?

Unfortunatelly, I don't have realistic constructive suggestions.

I wish Urho codebase moved away from implicit casts at all, adding `.Get()` and `Reset` all over the place.
It essentially means removing `operator T` and `operator =(T*)` from SP and WP and fixing the rest of the code.
However, there's just way too many places relying on implicit casts now, and it would be tremendous (and tremendously boring) task. People will start complaining aboout extra casts too.
