### ISSUE TITLE
[Web] Clicking outside game window on web build sometimes causes mouse to stop registering button clicks.

### ISSUE THREAD

**Issue by JTippetts** [urho3d/Urho3D#2552]
On web builds, sometimes, if you inadvertently click in the header box at the top, in the debug console at the bottom, or the areas to the right/left of the game window, the mouse will stop registering mouse clicks. It will still process mouse position but it won't register any clicks. Occurs in the samples, ie in https://urho3d.github.io/samples/37_UIDrag.html if you try clicking in various locations around the game window, then try to drag the elements. It will register Hover, but drag won't occur.

**Comment by JTippetts** [comment]
I think it's some kind of focus-related issue. If you make a html shell that has no other element but the game window canvas on it, it doesn't seem to happen no matter how much you click outside of the window, so the problem seems to be the header section or the debug console log stealing focus away. But it doesn't return when you click on the canvas.

**Comment by ArnisLielturks** [comment]
@JTippetts is this still an issue with the new shell?

**Comment by JTippetts** [comment]
It seems to be fixed as far as I can tell.
