### ISSUE TITLE
Bug with PODVector::Push(*this)

### ISSUE THREAD

**Issue by SirNate0** [urho3d/Urho3D#2563]
Possibly related to #1556, PODVectors's `void Push(const PODVector<T>& vector)` fails if you pass it *this as it resizes the vector, and then uses the other vector's `size_` to copy the buffer, but the other vector (i.e. this vector)'s `size_` was also just doubled, resulting in potentially overlapping buffers (and probably generally incorrect results).

The relevant piece of the valgrind output:
```
==30471== Source and destination overlap in memcpy(0x1c464d88, 0x1c464d60, 80)
==30471==    at 0x4C32513: memcpy@@GLIBC_2.14 (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==30471==    by 0x797F58: Urho3D::PODVector<future::VoxelLine::LengthDir>::CopyElements(future::VoxelLine::LengthDir*, future::VoxelLine::LengthDir const*, unsigned int) (Vector.h:1210)
==30471==    by 0x7E368F: Urho3D::PODVector<future::VoxelLine::LengthDir>::Push(Urho3D::PODVector<future::VoxelLine::LengthDir> const&) (Vector.h:875)
==30471==    by 0x7E2A2E: Urho3D::PODVector<future::VoxelLine::LengthDir>::operator+=(Urho3D::PODVector<future::VoxelLine::LengthDir> const&) (Vector.h:778)
```

**Comment by eugeneko** [comment]
It's not just related. It's duplicate, it was fixed before and the fix was reverted due to performace reasons.
