### ISSUE TITLE
[Emscripten] Uncaught RuntimeError: float unrepresentable in integer range

### ISSUE THREAD

**Issue by Dimous** [urho3d/Urho3D#2568]
Hello!

Web samples randomly throw overflow exceptions.
What causes and how to work around it -- https://groups.google.com/forum/#!topic/emscripten-discuss/IJr4ApiW_zU

TLDR
Just add `-s "BINARYEN_TRAP_MODE='clamp'"` in Emscripten-specific part of UrhoCommon.cmake

**Comment by weitjong** [comment]
This has been discussed before in other issues. I intentionally left the trap mode to "allow", thinking that user can easily override it to "clamp" mode if it is required and that most of our samples work in "allow" mode. I think only the "water" sample requires "clamp" mode.

**Comment by Dimous** [comment]
I got it, thanks!
