### ISSUE TITLE
String foreach support

### ISSUE THREAD

**Issue by SirNate0** [urho3d/Urho3D#2569]
We seem to be missing a begin/end implementation for String so that we can do `for (char c : str)`. I believe adding this to the end of Str.h will work:
```
inline Urho3D::String::ConstIterator begin(const Urho3D::String& s) { return s.Begin(); }

inline Urho3D::String::ConstIterator end(const Urho3D::String& s) { return s.End(); }

inline Urho3D::String::Iterator begin(Urho3D::String& s) { return s.Begin(); }

inline Urho3D::String::Iterator end(Urho3D::String& s) { return s.End(); }
```

**Comment by 1vanK** [comment]
Iterator looks like char iterator, in most cases, users will prefer to work with code points

**Comment by Modanung** [comment]
Over in [Dry](https://gitlab.com/luckeyproductions/dry) land, `Begin()` and `End()` have been _renamed_ to `begin()` and `end()`.
