### ISSUE TITLE
Urho3dPlayer black screen

### ISSUE THREAD

**Issue by MatthewScholefield** [urho3d/Urho3D#2574]
Hi, I downloaded the latest 64 bit linux tarball (1.7.1) and ran `Urho3DPlayer Scripts/NinjaSnowWar.as` (from `/usr/local/share/Urho3D/Resources/Data`) as mentioned in the examples page. It opens fullscreen, but everything is black (and no keys work to exit). If I kill the process (from another tty terminal), a single properly rendered frame flashes on the screen right before it closes.

**Other details:**
Running the compiled examples like `./01_HelloWorld`, but running `Urho3DPlayer Scripts/01_HelloWorld.as` still shows a black screen (but I see my mouse cursor over the black screen).

**Logs:**
```
[Sun Jan 26 00:24:44 2020] INFO: Opened log file /home/matthew/.local/share/urho3d/logs/NinjaSnowWar.as.log
[Sun Jan 26 00:24:44 2020] INFO: Created 3 worker threads
[Sun Jan 26 00:24:44 2020] INFO: Added resource path /usr/local/bin/../share/Urho3D/Resources/Data/
[Sun Jan 26 00:24:44 2020] INFO: Added resource path /usr/local/bin/../share/Urho3D/Resources/CoreData/
[Sun Jan 26 00:24:44 2020] INFO: Added resource path /usr/local/bin/../share/Urho3D/Resources/Autoload/LargeData/
[Sun Jan 26 00:24:44 2020] INFO: Set screen mode 1920x1080 fullscreen monitor 0
[Sun Jan 26 00:24:44 2020] INFO: Initialized input
[Sun Jan 26 00:24:44 2020] INFO: Initialized user interface
[Sun Jan 26 00:24:44 2020] INFO: Initialized renderer
[Sun Jan 26 00:24:44 2020] INFO: Set audio mode 44100 Hz stereo interpolated
[Sun Jan 26 00:24:44 2020] INFO: Initialized engine
[Sun Jan 26 00:24:44 2020] INFO: Compiled script module Scripts/NinjaSnowWar.as
[Sun Jan 26 00:24:44 2020] INFO: Loading scene from Scenes/NinjaSnowWar.xml
```

**Comment by weitjong** [comment]
Do you have a discrete graphic card with its proprietary driver installed?

**Comment by MatthewScholefield** [comment]
I have a laptop with optimus graphics (hybrid NVIDIA / intel integrated) with the NVIDIA card disabled (no proprietary or open source NVIDIA drivers).

**Comment by weitjong** [comment]
Urho3D is a 3D game engine which requires 3D  hardware acceleration. At the very least it requires nouvea driver (kmod) to be installed if not better when you have an NVIDIA card.

**Comment by MatthewScholefield** [comment]
The intel integrated graphics surely supports 3D hardware acceleration. Shouldn't it work on integrated graphics (ie. for users who are running on laptops without dedicated graphics cards)? Just to clarify, I run my entire system like this and play open source and proprietary games fine (albeit, a little laggy) without NVIDIA-specific drivers installed.Perhaps it could be an issue with Urho3D detecting a NVIDIA card without checking if it's the card that's rendering, but I don't know enough about rendering to know if that's a reasonable guess. Here's some more info:

Parts from `glxinfo`:
```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
server glx vendor string: SGI
server glx version string: 1.4
client glx vendor string: Mesa Project and SGI
client glx version string: 1.4
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 630 (Kaby Lake GT2) 
OpenGL core profile version string: 4.6 (Core Profile) Mesa 19.3.1
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL version string: 3.0 Mesa 19.3.1
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 19.3.1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

Some output from `glxgears -info`:
```
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
GL_RENDERER   = Mesa DRI Intel(R) HD Graphics 630 (Kaby Lake GT2) 
GL_VERSION    = 3.0 Mesa 19.3.1
GL_VENDOR     = Intel Open Source Technology Center
```

**Comment by ArnisLielturks** [comment]
@MatthewScholefield Could you try running the Urho3DPlayer in the windowed mode? `./Urho3DPlayer Scripts/NinjaSnowWar.as -w -x 1280 -y 720`.
Similar issue happens on my Linux Mint laptop with intrgrated and dedicated video card, but it's not related to the engine, it's a bug with one of the linked graphics libraries, don't remember which exactly.

**Comment by MatthewScholefield** [comment]
Yeah, that fixes it! Thanks for the tip.
