### ISSUE TITLE
[CMake] Put header and source file in the same folder

### ISSUE THREAD

**Issue by SuperWangKai** [urho3d/Urho3D#2579]
Is there a particular reason why we separate header and source?

Can we put the header files and source files into the same folder? By doing this, navigating in an IDE will be easier.

from -
![image](https://user-images.githubusercontent.com/15721569/73971550-0ea80c80-495a-11ea-888b-da7df2c5cff5.png)

to -

![image](https://user-images.githubusercontent.com/15721569/73971608-25e6fa00-495a-11ea-910a-5d3156813630.png)

(This is from comparing Urho to rbfx, no politics here, bored of arguments. I am more interested in Urho itself)

**Comment by weitjong** [comment]
There is no specific reason for that. It is a matter of personal preference I guess and I just preserve this behavior as I have found it in the first place after becoming the main maintainer for the build system. You see, what you observed is actually also IDE-specific. On Clion I don't get the segregation, see left side of the below image.

![image](https://user-images.githubusercontent.com/5548048/74086282-4cbd4180-4abc-11ea-9ab0-2316d6825545.png)

The instruction to segregate the source and header groups is provided in our CMake build script, but only the IDE that actually supports it will take effect. If recall it correctly, only VS and Xcode support it. See lines between 990 and 1006 on the right side of the image, the logic is inside the "define_source_files" macro. And, also notice it is actually not hard-coded from the macro side. The macro caller can choose whether to group or not. Having said that, our CMake build script for Urho3D library target itself has been scripted to enable the grouping. See https://github.com/urho3d/Urho3D/blob/c1bb0917bcecdb1c55cd120d64ffcad241213ff5/Source/Urho3D/CMakeLists.txt#L150

So, have it your way. We cannot keep everyone happy. The grass is always greener on the other side.

**Comment by SuperWangKai** [comment]
Thank you @weitjong and thanks for the information :)

**Comment by 1vanK** [comment]
I wrote a config for my small program (not Urho-based), and noticed that VS puts * .cpp and * .h files to different folders by default.

I used
`source_group(TREE ${CMAKE_SOURCE_DIR} FILES ${SRC_FILES})`
to force VS to store existed directory tree

**Comment by weitjong** [comment]
Thanks for the information. This is a little different from my understanding. If you remove the “GROUP” parameter in the line 150 above, can you tell me what you observe  then in VS?

**Comment by 1vanK** [comment]
![Без груп](https://user-images.githubusercontent.com/13021826/74586906-87afff80-4ffd-11ea-83b8-950d2949aaae.png)

**Comment by weitjong** [comment]
So basically you are saying, with or without the "GROUP" parameter, you ended up with the same result. Interesting. Feel free to reopen this issue if that is the case. I just don't have the VS at the moment to test this and rectify this locally. Contribution for the fix is welcome.

**Comment by 1vanK** [comment]
No, with group another result:

![С группами](https://user-images.githubusercontent.com/13021826/74587357-6f8eaf00-5002-11ea-9352-7fb36cb79332.png)

**Comment by weitjong** [comment]
Ok. That's make some sense to me. But are you guys saying you want the source + header to be grouped together instead always along the line of their physical directory structure.

**Comment by weitjong** [comment]
I just checked there is a new option in the `source_group` CMake command that is only available in the newer version of CMake that can make this happen easily without writing many lines of script like in the past. And, since we have bumped up our minimum CMake version to 3.10.2, we can safely use this new option.

**Comment by 1vanK** [comment]
```
Ok. That's make some sense to me. But are you guys saying you want the source + header to be grouped together always, along the line of their physical directory structure?
```
That would be convenient for me too.

**Comment by weitjong** [comment]
Can you check if this patch works for you.

```
diff --git a/CMake/Modules/UrhoCommon.cmake b/CMake/Modules/UrhoCommon.cmake
index 08582aa5ee..0619fffc61 100644
--- a/CMake/Modules/UrhoCommon.cmake
+++ b/CMake/Modules/UrhoCommon.cmake
@@ -989,20 +989,7 @@ macro (define_source_files)
     endif ()
     # Optionally group the sources based on their physical subdirectories
     if (ARG_GROUP)
-        foreach (CPP_FILE ${CPP_FILES})
-            get_filename_component (PATH ${CPP_FILE} PATH)
-            if (PATH)
-                string (REPLACE / \\ PATH ${PATH})
-                source_group ("Source Files\\${PATH}" FILES ${CPP_FILE})
-            endif ()
-        endforeach ()
-        foreach (H_FILE ${H_FILES})
-            get_filename_component (PATH ${H_FILE} PATH)
-            if (PATH)
-                string (REPLACE / \\ PATH ${PATH})
-                source_group ("Header Files\\${PATH}" FILES ${H_FILE})
-            endif ()
-        endforeach ()
+        source_group (TREE ${CMAKE_CURRENT_SOURCE_DIR} PREFIX src FILES ${SOURCE_FILES})
     endif ()
 endmacro ()
```

**Comment by weitjong** [comment]
One more question to you guys. Does it make sense to apply this by default in the macro? So, it may apply to all source codes (c/c++ and its header files) for 3rd-party libs as well.

**Comment by 1vanK** [comment]
> Can you check if this patch works for you.

![Тест](https://user-images.githubusercontent.com/13021826/74590759-71686a80-5022-11ea-83cd-ee9453762c25.png)

> Does it make sense to apply this by default in the macro?

I can’t speak for everyone, but it seems to me that displaying files as is - is the only correct way.

**Comment by weitjong** [comment]
Fair enough. I will attempt to group those generated files currently under “Source Files” and “Header Files” under this “src” and perhaps rename the “src” to “Source Codes” or (final) “Source Files”. Thanks for your help, at least I now know how the new option works in VS. Again, all this command is a no-ops for other IDE. And, to make VS to have a consistent grouping with other IDE (that only show files based on physical dir structure) is good enough reason for the change to me.

**Comment by weitjong** [comment]
See commit c2b8d259625bda28daaa437745d5474d43e309e6

I didn't touch the 3rd-party because I am making changes blind here. Further changes from VS users are welcome.
