### ISSUE TITLE
Box2D Violating Strict Aliasing

### ISSUE THREAD

**Issue by SirNate0** [urho3d/Urho3D#2598]
Box2D has a line in this function that breaks strict aliasing rules, producing a warning. I would have made an issue upstream, but it seems our version of Box2D is several years old, so it may be better to fix it in Urho.
```
/// This function is used to ensure that a floating point number is not a NaN or infinity.
inline bool b2IsValid(float32 x)
{
	int32 ix = *reinterpret_cast<int32*>(&x);
	return (ix & 0x7f800000) != 0x7f800000;
}
```

> /home/nathan/Projects/Urho/Urho3D/Build/include/Urho3D/ThirdParty/Box2D/Common/b2Math.h: > In function ‘bool b2IsValid(float32)’:
> /home/nathan/Projects/Urho/Urho3D/Build/include/Urho3D/ThirdParty/Box2D/Common/b2Math.h:28:41: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
 ` int32 ix = *reinterpret_cast<int32*>(&x);`

Suggested workaround
https://stackoverflow.com/questions/17789928/whats-a-proper-way-of-type-punning-a-float-to-an-int-and-vice-versa#answer-51301622

**Comment by OvermindDL1** [comment]
For note, casting between Integer and Floating types is absolutely Undefined Behaviour in C and C++.  Depending on what registers they get promoted to (MMX/SSE/AVX/etc...) and how optimizations happen and the archetecture and more can make it either seem to work (common on x86 but very uncommon on ARM), give corrupt data (less common on x86 but becoming more common because of AVX/SSE usage, someone common on arm), or just outright crashing if you are lucky (common on arm).

The only standards-compliant way to convert between an integral and a floating type is via a union, which has no UB for that because it enforces alignment and register usages that allow it to work everywhere.

And yes, I've hit that UB because, the spec is fairly clear that it is UB and should never ever be done like that, it is categorically always a bug.

**Comment by eugeneko** [comment]
> The only standards-compliant way to convert between an integral and a floating type is via an allocated (heap or stack, whichever, do not cast to it) union, which has no UB

@OvermindDL1 casting anything via union is UB too.
Only the most-recently-written field may be read from union in C++.

I fixed such places by `memcpy`, I think this is the most legitimate way to do.

**Comment by OvermindDL1** [comment]
> @OvermindDL1 casting anything via union is UB too.

Exactly, hence why I put this in my post:

> The only standards-compliant way to convert between an integral and a floating type is via an allocated (heap or stack, whichever, do *not* cast to it) union

Though perhaps I should have bolded the **not** instead of italicized it.

You *have* to copy it to a known aligned location without register issues, meaning it has to be copied into an existing union on the heap or stack (or just keep it as a union internally for fast access).

> Only the most-recently-written field may be read from union in C++.

For primitives it's not UB to read different types, only for complex types.

**Comment by eugeneko** [comment]
> For primitives of the same size it's not UB to read different types in C99 and higher, only for complex types or mismatched sizes of primitives.

Urho is not C99. Urho is C++.

**Comment by OvermindDL1** [comment]
C++11 defines it the same as C99, compilers before C++11 still followed C99 in every case I've seen (it was technically UB however).

If Urho3D requires a minimum of C++11 then allocated union is still the most efficient standards compliant method with no UB.

**Comment by OvermindDL1** [comment]
> Finally, one of the changes from C90 to C99 was to remove any restriction on accessing one member of a union when the last store was to a different one. The rationale was that the behaviour would then depend on the representations of the values. Since this point is often misunderstood, it might well be worth making it clear in the Standard.

Footnote 95 of the C++11 spec, footnote copied from the C99 spec (footnote 82).

**Comment by eugeneko** [comment]
I always considered cppreference as "sane" explanation of standard. It's super-weird if it lies.
I cannot find the text you quoted in C++11 standard draft. Can you share a link?

**Comment by OvermindDL1** [comment]
Do you own a copy of the C++ ISO spec?

**Comment by OvermindDL1** [comment]
Oh hey, the footnotes are available online:  https://port70.net/~nsz/c/c11/n1570.html#note95

**Comment by OvermindDL1** [comment]
And for further clarity on what it means by a trap representation:

> Certain object representations need not represent a value of the object type. If the stored value of an object has such a representation and is read by an lvalue expression that does not have character type, the behavior is undefined. If such a representation is produced by a side effect that modifies all or any part of the object by an lvalue expression that does not have character type, the behavior is undefined.50) Such a representation is called a trap representation.
>
> When a value is stored in an object of structure or union type, including in a member object, the bytes of the object representation that correspond to any padding bytes take unspecified values.  The value of a structure or union object is never a trap representation, even though the value of a member of the structure or union object may be a trap representation.
>
> When a value is stored in a member of an object of union type, the bytes of the object representation that do not correspond to that member but do correspond to other members take unspecified values.

In short, if the fields in a union aren't all the same size, and you set something that is of a smaller size than another, then reading the other is a trap representation as it's partially valid, but reading others of the same size is still valid, and even in any of these cases the union itself is not a trap representation and may still be fully read.

**Comment by Modanung** [comment]
Box2D got rid of these `float32`s a few months ago.

**Comment by eugeneko** [comment]
> This International Standard specifies the form and establishes the
interpretation of programs expressed in the programming language C

I don’t get how it is related to C++, although.
This is the standard of C99 that has nothing to do with standard of C++11

вт, 3 марта 2020 г. в 02:39, 魔大农 <notifications@github.com>:

**Comment by OvermindDL1** [comment]
> This is the standard of C99 that has nothing to do with standard of C++11

C11 6.5.2.3 Footnote 95 is from C++11, it was brought in from the C99 standard.

**Comment by 1vanK** [comment]
At the time of this ticket, this issue has already been resolved:

https://github.com/urho3d/Urho3D/commit/79573004ae6323cb9a9bcddb6586c4370dc94bb2
