### ISSUE TITLE
Problem with point light shadows.

### ISSUE THREAD

**Issue by ChrisDenham** [urho3d/Urho3D#2606]
I've been trying to track down a strange issue with shadows cast by point lights when running in OpenGL mode (on Windows10, not tried other platforms). They seem to work well for me in DX9 mode, just not in OGL. I am currently using master branch at commit a98d17ad. The problem shows as black speckled lines where the projections from the light source of the edges of the 6 shadow maps used for implementing the point light shadows.

I'm happy to investigate and fix, but wonder if anyone had any pointers or suggestions for area of code to look at. My suspicion was that it seemed like it might be something to do with how texture edges for the shadow map are clamped, but that was just a wild guess.

I can easily reproduce the problem by changing the 04_StaticScene example to use a point light:

![urho3d-ogl-pointlight-shadow-problem-code-diff](https://user-images.githubusercontent.com/2325443/77256038-91173200-6c63-11ea-8280-4c24b6fb4f69.png)
    
In OGL mode it gives me:

![urho3d-ogl-pointlight-shadow-problem](https://user-images.githubusercontent.com/2325443/77256050-b146f100-6c63-11ea-90c6-a0f0d8356934.png)

I've hightlighted the problem areas in green here:

![urho3d-ogl-pointlight-shadow-problem-emphasized](https://user-images.githubusercontent.com/2325443/77256070-cde32900-6c63-11ea-9ff8-6176570266b2.png)

Any thoughts or fixes?
Regards
Chris.

**Comment by ChrisDenham** [comment]
Does no one have any suggestions where to investigate to fix this issue? As I said, I can have a go myself but was sure someone with a deeper knowledge of Urho3D could point me in the right direction to save me wasting time looking in the wrong places?  Can anyone confirm they have the same issue?

**Comment by ChrisDenham** [comment]
Just making the issue is a bit more obvious in this screen grab:

![image](https://user-images.githubusercontent.com/2325443/80082816-c3f76300-854c-11ea-959c-7453c4aa9acf.png)

**Comment by ChrisDenham** [comment]
I've just been poking around in the GLSL shader code associated with point light shadows.
Whilst I admit I feel way out of my depth, I did spot a comment that seemed like it could be related to this issue and wondered if anyone had any thoughts about whether I'm anywhere close to the cause. The comment mentions something about variable GPU support for texture filtering across cubemap faces, and as that seems to be precisely where I'm seeing anomalies in the rendered shadows, and so raised a flag in my thinking.
The code I'm talking about is in "Lighting.glsl":
```
 #ifdef POINTLIGHT
float GetPointShadow(vec3 lightVec)
{
    vec3 axis = textureCube(sFaceSelectCubeMap, lightVec).rgb;
    float depth = abs(dot(lightVec, axis));

    // Expand the maximum component of the light vector to get full 0.0 - 1.0 UV range from the cube map,
    // and to avoid sampling across faces. Some GPU's filter across faces, while others do not, and in this
    // case filtering across faces is wrong
    const vec3 factor = vec3(1.0 / 256.0);
    lightVec += factor * axis * lightVec;

    // Read the 2D UV coordinates, adjust according to shadow map size and add face offset
    vec4 indirectPos = textureCube(sIndirectionCubeMap, lightVec);
    indirectPos.xy *= cShadowCubeAdjust.xy;
    indirectPos.xy += vec2(cShadowCubeAdjust.z + indirectPos.z * 0.5, cShadowCubeAdjust.w + indirectPos.w);

    vec4 shadowPos = vec4(indirectPos.xy, cShadowDepthFade.x + cShadowDepthFade.y / depth, 1.0);
    return GetShadow(shadowPos);
}
#endif
```

**Comment by 1vanK** [comment]
I don't remember ever seeing a similar problem. Have you installed the latest drivers for your video card?

**Comment by ChrisDenham** [comment]
> I don't remember ever seeing a similar problem. Have you installed the latest drivers for your video card?

Yep, drivers always up-to-date using "Nvidia experience".  I have seen the issue on a number of machines. Note that I have only noticed the issue in OpenGL builds running on Windows so far.  

An interesting result from my investigation of this was that I was surprised the DX9 build doesn't show the issue because I would have thought that would also be doing bilinear sampling across cube map faces of the indirectionCubemap, which should also be causing an issue for that target too.  But I can only assume seamless cubemap is not enabled by default for dx9 build?

**Comment by 1vanK** [comment]
Can you explain how the interpolation between two black regions turns into white line? I see this as a driver error.

Enabling seamless should solve the problem of seams, but not become the cause of seams.

> Under the standard filtering rules for cubemaps, filtering does not work across faces of the cubemap. This results in a seam across the faces of a cubemap. This was a hardware limitation in the past, but modern hardware is capable of interpolating across a cube face boundary.
>
> To globally enable seamless cubemap texture accesses, use glEnable(GL_TEXTURE_CUBE_MAP_SEAMLESS). 

https://www.khronos.org/opengl/wiki/Cubemap_Texture#Seamless_cubemap

**Comment by ChrisDenham** [comment]
My fix disables the filtering across the seam for the indirectionCubemap. This map does not contain depth values, it contains positional information for looking up depth values from the depth render texture. I'm not really sure why it was done that way, but I think it means the position info in the indirection cubemap should not be averaged over the seam.

**Comment by ChrisDenham** [comment]
I probably didn't explain that very well. What I mean is, the indirection map seems to hold uv position into the depth texture, and therefore has sudden transitions of values at the seams.
