### ISSUE TITLE
urho3d example can't open the window

### ISSUE THREAD

**Issue by tbutton2005** [urho3d/Urho3D#2607]
when i try to run any urho3d example, it writes 

[Mon Mar 23 10:51:38 2020] INFO: Opened log file /home/max/.local/share/urho3d/logs/Water.log
[Mon Mar 23 10:51:38 2020] INFO: Created 1 worker thread
[Mon Mar 23 10:51:38 2020] INFO: Added resource path /home/max/Urho3D/build/bin/Data/
[Mon Mar 23 10:51:38 2020] INFO: Added resource path /home/max/Urho3D/build/bin/CoreData/
[Mon Mar 23 10:51:38 2020] INFO: Added resource path /home/max/Urho3D/build/bin/Autoload/LargeData/
[Mon Mar 23 10:51:38 2020] ERROR: Could not create window, root cause: 'No available video device'

help me please,

**Comment by eugeneko** [comment]
What version of the engine do you use? Graphical API?
Did it work before?
Do other graphical apps work on this machine?

**Comment by iSLC** [comment]
- What Linux distribution and what version of that distribution.
- What architecture is the distribution and what architecture is your binary (_whether you build it or not_).
- What hardware is being used (_GPU mostly_) and whether this is one of those machines/laptops with dual GPUs that switch dynamically depending on the load (_who knows_).
- Like @eugeneko  asked above. Can you run other games on that machine. Are you sure that you have the necessary drivers installed on that machine. Especially the GPU driver. Is it the universal one that comes with the OS or the dedicated/proprietary driver offered by the manufacturer.
- Did you compile the example yourself or it was one of the pre-built packages available.
- Which version of the engine you are using. Released or master.

There request is quite vague and leaves a lot of unanswered questions. On the surface, this seems to be related to SDL. A commonly (_but not universal_) reported fix happens to be in the form of some missing packages `sudo apt-get install ia32-libs-sdl`. Depending on the used distribution, that might not be the same everywhere.

Again, a bunch of information is missing here to properly inspect this.
