### ISSUE TITLE
No error reporting on windows Urho3DPlayer

### ISSUE THREAD

**Issue by Bambofy** [urho3d/Urho3D#2613]
I am running a Lua scripted game using the Urho3DPlayer.exe provided in the binary releases hosted on sourceforge.

```
The error is as follows:

    function onCallback()
        undefinedValue:PerformFunction() -- should print "ERROR: Execute Lua function failed: Attempt to index nil value 'undefinedValue'
    end
```

### On my OS X laptop i can run the commands:
1) To start the server application  ./Urho3DPlayer Scripts/Serverside/main.lua -w
2) To start the client appliciation ./Urho3DPlayer Scripts/Clientside/main.lua -w 

In this environment the errors are printed to the OS X terminal (see attached image), so i can debug the problems. (In the example image the variable inPlayerClass is nil, and the error is reported correctly.

<img width="1333" alt="Screenshot 2020-04-01 at 11 50 51" src="https://user-images.githubusercontent.com/1304898/78129208-20180d00-740f-11ea-965b-246ad4177d80.png">

### However on my windows 10 PC i run these commands:
1) ./Urho3DPlayer.exe Scripts/Serverside/main.lua -w
2) ./Urho3DPlayer.exe Scripts/Clientside/main.lua -w

The client application fails to perform the code, but it doesn't give any error information in either the built in "OpenConsoleWindow()" nor the command prompt the player was executed in.

I have tested the Urho3DPlayer.exe against a single test.lua, and it does correctly print basic errors but it seems for my more complex project, the exe doesn't print the errors correctly on windows.

![Windows command prompt](https://user-images.githubusercontent.com/1304898/78129010-cadbfb80-740e-11ea-9019-382aabb02260.png)

**Comment by Bambofy** [comment]
Link to the forum post: https://discourse.urho3d.io/t/windows-urho3dplayer-doesnt-print-lua-errors/6039

**Comment by SirNate0** [comment]
> I have tested the Urho3DPlayer.exe against a single test.lua, and it does correctly print basic errors

Are you sure it's calling the function that should be printing the errors? It kind of sounds like it may never reach the code that is an error on Windows.

**Comment by weitjong** [comment]
When targeting Windows platform you may try to enable `URHO3D_WIN32_CONSOLE` if you want to use console main(). Regardless the app output should be also available in the log file. Read the online docs for more detail.
