### ISSUE TITLE
String::ToHash() vs StringHash::Calculate()

### ISSUE THREAD

**Issue by SirNate0** [urho3d/Urho3D#2618]
I noticed that there seem to be 2 implementations of the code to perform string hashing. My tentative guess is that this may be due to the old behavior where hashing was case-insensitive or from when there was a ShortStringHash, but I was wondering why there are two implementations?

Why do we not just move the definition of String::ToHash() to Str.cpp and then use the StringHash implementation?

Somewhat related, why are the string hashes registered in StringHash's constructor rather than in StringHash::Calculate?

**Comment by weitjong** [comment]
I don't have answer to all your questions but I could say that the cause for having two implementation is not due to the reason you gave above. You can use git log to see when the code were introduced and for what purpose.
