### ISSUE TITLE
Strange result in BRDF shader's Diffuse().

### ISSUE THREAD

**Issue by kannsokusha** [urho3d/Urho3D#2622]
![20200409175839](https://user-images.githubusercontent.com/26665589/78886011-200fb100-7a90-11ea-8e65-0534df3d9695.png)
![20200409175608](https://user-images.githubusercontent.com/26665589/78886040-2b62dc80-7a90-11ea-96c2-fc5ae9142c53.png)

See the streaks on the plane. I think, "toCamera" is the mistaken,but I don't know how to solve it.

**Comment by 1vanK** [comment]
I think it’s caused by limited computational accuracy when using floats. I noticed a similar effect even in 3D packages on dark images.

**Comment by eugeneko** [comment]
Display has limited number of colors. There is nothing to fix in the library.

All I can suggest is not to make such shallow gradients.

**Comment by 1vanK** [comment]
> Display has limited number of colors.

This is so, but in this case, this is not the cause of sharp color changes. 

If this were the reason, then you would not be able to blur the border between the colors, since there are no intermediate colors, right?

**Comment by eugeneko** [comment]
> If this were the reason, then you would not be able to blur the border between the colors, since there are no intermediate colors, right?

Right. Have you managed to blur the border in this case?

**Comment by 1vanK** [comment]
Ok, I checked the colors in the editor, they difference == 1, so yes a limit of 256 values is the reason for this

P.S. Blender use Dither posteffect  to reductions similar effets

**Comment by kannsokusha** [comment]
> 显示的颜色数量有限。库中没有要修复的东西。
> 
> 我所能建议的就是不要做出如此浅的渐变，也不要调整场景的伽玛/对比度/亮度。

You're right. But I didn't do anything but add directional light and use PBR materials. There is no deliberate gradient. This effect is instead caused by the default shader.

**Comment by 1vanK** [comment]
Direction from camera to each pixel of the scene is different -> for each pixel angle between look direction and light direction is different ->gradient

**Comment by eugeneko** [comment]
This is an issue of level and/or material design. I don't think there exists an engine that can magically fix such issues in gradients.
You should build your level in the way you don't get such kind of gradients.

You can use textured materials. If you make reflective material, reflect skybox and whole environment. You can adjust properties of material or light to shift this gradient into brighter areas of gray where you have more colors.

**Comment by kannsokusha** [comment]
Thanks,I got it.
