### ISSUE TITLE
IOS cpu core counts is not correct (only return 2 cores on a real phone)

### ISSUE THREAD

**Issue by Yuki001** [urho3d/Urho3D#2630]
In ProcessUtils.cpp: (lines : 436 443 470 476
Change : 
#if defined(TARGET_OS_SIMULATOR)
To : 
#if TARGET_OS_SIMULATOR

The macro TARGET_OS_SIMULATOR is defined to 0 on real iphone.

**Comment by weitjong** [comment]
Thanks for reporting this.
