### ISSUE TITLE
CMake fails for macbook

### ISSUE THREAD

**Issue by honghaoli** [urho3d/Urho3D#2640]
I've been using Urho3D for quite a while on my macbook and it works fine without any issue.
I played it by messing around some source code in my test project.
Now I want to get a clean Urho3D source code for another project. So I set a new folder and git clone the most recent repo. But I had issue for the very 1st step ```cmake .```.

Here is what I did:
1. ```git clone https://github.com/urho3d/Urho3D.git```
2. ```cd Urho3D```
3. ```cmake .```

Then I got the error message:
```
In file included from /Users/XXX/Documents/Urho3D_Projects/Urho3D/Source/Urho3D/Precompiled.h:28:
In file included from /Users/XXX/Documents/Urho3D_Projects/Urho3D/Source/Urho3D/Container/HashMap.h:28:
In file included from /Users/XXX/Documents/Urho3D_Projects/Urho3D/Source/Urho3D/Container/../Container/Vector.h:27:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cassert:21:10: fatal error: 'assert.h' file not found
#include <assert.h>
         ^~~~~~~~~~
1 error generated.
CMake Error at CMake/Modules/UrhoCommon.cmake:1260 (message):
  Could not generate dependency list for PCH.  There is something wrong with
  your compiler toolchain.  Ensure its bin path is in the PATH environment
  variable or ensure CMake can find CC/CXX in your build environment.
Call Stack (most recent call first):
  CMake/Modules/UrhoCommon.cmake:1730 (enable_pch)
  CMake/Modules/UrhoCommon.cmake:1563 (_setup_target)
  Source/Urho3D/CMakeLists.txt:312 (setup_library)


-- Configuring incomplete, errors occurred!
See also "/Users/XXX/Documents/Urho3D_Projects/Urho3D/CMakeFiles/CMakeOutput.log".
See also "/Users/XXX/Documents/Urho3D_Projects/Urho3D/CMakeFiles/CMakeError.log".
```

I search the internet found it might be related to xcode command line too.
So I uninstall it and reinstall it following [here](https://apple.stackexchange.com/questions/93573/how-to-reinstall-xcode-command-line-tools).

It does not solve the problem.

Any help?

**Comment by honghaoli** [comment]
btw, my system parameters

macOS Catalina 10.15.5 (I just updated today, it did not work for last version neither).

```
-- The C compiler identification is AppleClang 11.0.3.11030032
-- The CXX compiler identification is AppleClang 11.0.3.11030032
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
```

**Comment by honghaoli** [comment]
Updates:

I can use ```./script/cmake_xcode.sh```, there is no failure. After that I can open xcode and build the sample projects.
But I cannot use ```./script/cmake_generic.sh```. It has the same error as if I run ```cmake .``` in root folder.
Sadly, I am using CLion instead of xcode. So I would like to know how to fix this.

**Comment by ArnisLielturks** [comment]
@honghaoli try this approach, add the following line to your `~/.bash_profile` file
```export CPATH=`xcrun --show-sdk-path`/usr/include```
The issue is caused by missing include directories. I'am too using CLion on OSX and this did fix the issue for me.

**Comment by honghaoli** [comment]
@ArnisLielturks 
Thanks! That solved my ```cmake .``` problem.
But I still get error for ```make```
```
[ 76%] Linking CXX executable ../../../bin/Urho3DPlayer
ld: weak import of symbol '___darwin_check_fd_set_overflow' not supported because of option: -no_weak_imports for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/Urho3DPlayer] Error 1
make[1]: *** [Source/Tools/Urho3DPlayer/CMakeFiles/Urho3DPlayer.dir/all] Error 2
make: *** [all] Error 2
```

I guess it's another question anyway.

**Comment by ArnisLielturks** [comment]
@honghaoli I removed the `-no_weak_imports` flag from the engine cmake files to fix this. Not really sure what the implications of doing this are.

**Comment by honghaoli** [comment]
@ArnisLielturks 
Thanks! Now it finally works. I wonder what's happened since last time I built Urho3D without any issue (Nov 2019). Not sure if it's due to Urho3D updates or MacOS updates. 
Anyway, I'll summarize what we need to do to build it now.

In the root folder of Urho3D:

1. ```export CPATH=`xcrun --show-sdk-path`/usr/include```;
2. remove ```-no_weak_imports``` flag in ```UrhoCommon.cmake``` file.
3. ```cmake  -DURHO3D_PCH=0 .``` 
    - or set ```URHO3D_PCH``` to  ```FALSE``` in ```UrhoCommon.cmake``` file and Reset Cache and Reload CMake project through ```CLion```.
4. ```make && make install```.

**Comment by ArnisLielturks** [comment]
It stopped working with the new osx version - catalina.
