### ISSUE TITLE
The README file in this repo has some bad links - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [urho3d/Urho3D#2715]
The README file in this repo has some bad links - [404:NotFound]

Status code [404:NotFound] - Link: http://home.comcast.net/~tom_forsyth/papers/fast_vert_cache_opt.html
Status code [404:NotFound] - Link: https://lexicalunit.github.io/nanodbc
Status code [404:NotFound] - Link: http://www.codenix.com/~tolua

This was found by an new experimental hobby project that I have just created: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
If this has been in any way helpful then please consider giving the above Repo a Star.

**Comment by 1vanK** [comment]
https://web.archive.org/web/20131010100600/http://home.comcast.net/~tom_forsyth/papers/fast_vert_cache_opt.html

Links to libraries will be updated along with the libraries
