### ISSUE TITLE
Pasting in LineEdit may exceed SetMaxLength() limit

### ISSUE THREAD

**Issue by tril0byte** [urho3d/Urho3D#2725]
SetMaxLength() is a useful method which is correctly preventing typing text that would increase the widget's length over the limit specified. However, I am able to exceed the limit if textCopyable_ is true. 
Steps to reproduce:

1. Create a LineEdit widget
2. Set the Max Length with SetMaxLength()
3. Enter sufficient text into the widget so it's near the limit
4. Select a bunch of the text
5. Press Ctrl-C to copy text to the clipboard
6. Deselect the text (so that it doesn't just replace itself in the next step) by clicking to move the cursor anywhere inside the LineEdit
7. Press Ctrl-V. The length can now be longer then that specified by SetMaxLength().

I would guess the limit should be enforced in the KEY_V case in UI/LineEdit.cpp method LineEdit::OnKey(). https://github.com/urho3d/Urho3D/blob/f909775ca7d61e6291342b33921a22d837ac6b18/Source/Urho3D/UI/LineEdit.cpp#L237
Is there a reason not to implement this? Should anyone depend on the current behavior of being able to paste to increase text above the limit?

**Comment by tril0byte** [comment]
I see a few ways to proceed if this is desired.
1. truncating the string and allowing the paste to possibly go partly through. should the characters be removed from the existing text starting from the end, or from the text being pasted? 
2. blocking the entire paste and triggering an exception or error to allow the caller to handle this

**Comment by 1vanK** [comment]
Yes, it looks like truncating the string at the end `case KEY_V:` the easiest way. Can you create PR?
