### ISSUE TITLE
Android build with cmake params

### ISSUE THREAD

**Issue by talarcon** [urho3d/Urho3D#2730]
From a cloned copy from the repository, the next command it's not working

gradlew.bat -P ANDROID_ABI=arm64-v8a -P URHO3D_ANGELSCRIPT=0 -P URHO3D_PCH=0 -P URHO3D_WEBP=0 -P URHO3D_LUA=0 -P URHO3D_LUAJIT=0 build

I think only environment variables are taken by the new build system.
Is this deliberately removed? I could submit a PR (based on previous versions of the file) to support again command line options

**Comment by 1vanK** [comment]
Have you already found the change that is causing this problem?

**Comment by talarcon** [comment]
Yes, in the file android/urho3d-lib/build.gradle.kts the lines
```
    // Pass along matching env-vars as CMake build options
    addAll(project.file("../../script/.build-options")
        .readLines()
        .mapNotNull { variable -> System.getenv(variable)?.let { "-D $variable=$it" } }
    )
```
should be change to

```
    val vars = project.file("../../script/.build-options")	
        .readLines()
    addAll(vars	
        .filter { project.hasProperty(it) }	
        .map { "-D $it=${project.property(it)}" }	
    )	
    addAll(vars	
        .mapNotNull { variable -> System.getenv(variable)?.let { "-D $variable=$it" } }
    )
```

**Comment by 1vanK** [comment]
Create the PR and I'll merge it if @weitjong doesn't will return. I really hope that you understand what you doing, because android is out of my area of competence

**Comment by talarcon** [comment]
I've create a PR, I'm sure that this allow to take again options from command line. From what I've see in the new CI/CD setup options are only passed through environment. But I don't know why isn't support command line options anymore.

**Comment by 1vanK** [comment]
https://github.com/urho3d/Urho3D/pull/2731
