### ISSUE TITLE
16_Chat crash when MSG_CHAT = 153

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#2734]
@ArnisLielturks

AS version of 16_Chat used `MSG_CHAT = 153`.
C++ version of 16_Chat used `MSG_CHAT = 154`.

With `MSG_CHAT = 153` client crash after server doing `network.BroadcastMessage(MSG_CHAT, true, true, sendMsg);`. With `MSG_CHAT = 154` everything works fine. What is causing this crash?

**Comment by ArnisLielturks** [comment]
@1vanK https://github.com/urho3d/Urho3D/blob/305214ccd5cb59e767573a8033bfb974368679f5/Source/Urho3D/Network/Protocol.h#L68

153 is now reserved for something else, samples must be updated to use 154 for chat messages instead.

**Comment by 1vanK** [comment]
Can we create new const
```
static const int MSG_USER = xxxx;
```
like https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-user

and use

```
MSG_CHAT = MSG_USER + 1;
```

in examples

**Comment by ArnisLielturks** [comment]
Sounds good, will you implement it? Seems rather quick solution.

**Comment by 1vanK** [comment]
ok
