### ISSUE TITLE
Missing unistd.h in zlib

### ISSUE THREAD

**Issue by beached** [urho3d/Urho3D#2738]
Building will fail on MacOS(11.0/x64) with missing declarations for symbols like lseek.  Adding `#include <unistd.h>` to https://github.com/urho3d/Urho3D/blob/master/Source/ThirdParty/Assimp/contrib/zlib/gzguts.h fixes the issue. This is with Alpha release and 04b952cb6765e7040ef7457d1711be69fe5ffb6d

**Comment by 1vanK** [comment]
Can you create PR?
