### ISSUE TITLE
editor path issue

### ISSUE THREAD

**Issue by SoNewBee** [urho3d/Urho3D#2739]
Urho3D is an amazing project.
Thanks for the efforts everyone made.
I am a beginner and I really like this engine.
But it is difficult for me to recompile source code everytime.
So I compressed the compiled engine.
But it seems that the path finding function of editor would not work when I got the rar file unpacked.
I have tried many versions,but this issue is still not fixed.
BTW, even if I recompile the current master branch,the the path finding function of editor seems not work correctly.
I wish this issue would be fixed quickly.
Thanks again.

**Comment by iSLC** [comment]
Is it a self extracting archive?
How do you invoke the editor? Simply opening the executable or using the provided batch file.
What operating system does it happen on?

I'm a bit confused as to what compression does in this case. A few missing details to put the pieces together.

**Comment by SoNewBee** [comment]
> Is it a self extracting archive?
> How do you invoke the editor? Simply opening the executable or using the provided batch file.
> What operating system does it happen on?
> 
> I'm a bit confused as to what compression does in this case. A few missing details to put the pieces together.

Thanks for your reply.
Emmm,Sorry, I don't know what is a self extracting archive.
I am using Windows10 and WinRAR.
Then I just click the right mouse button on the compiled engine folder and select "add to compressed file".
I am using the provided batch file to open the editor because I don't know if there was another way to invoke it,haha.
There are variable reasons why I use the compressed file,such as easy to transport or easy to use(needn't to compile the source code again).

**Comment by 1vanK** [comment]
Can you clarify which paths the editor cannot find?

**Comment by SoNewBee** [comment]
> Can you clarify which paths the editor cannot find?

It can not recongnize anything.
For example, before I compress it, I can copy my model to data\model folder and I can search for it in the editor.
Then I compress it and unpack.
In the unpack version,this function will not work.

**Comment by 1vanK** [comment]
Try View > Editor settings > Remember resource path

**Comment by 1vanK** [comment]
Also pls provide your archive, I'll take a look at him

**Comment by SoNewBee** [comment]
> Try View > Editor settings > Remember resource path

It seems that it is checked by default.

**Comment by SoNewBee** [comment]
> Also pls provide your archive, I'll take a look at him

Thanks for your reply.
But I can not provide it because it is too big(about 1.5GB).
Could you please try it?
"I recompiled the current master branch,the path finding function of editor seems not work correctly."
I have found the way to solve this problem.
This is because the default path of editor is "xx\bin\Autoload\LargeData\Models\".
Maybe this is a bug?

**Comment by 1vanK** [comment]
> It seems that it is checked by default.

try uncheck

> But I can not provide it because it is too big(about 1.5GB).

I can't even imagine what you put in the archive

**Comment by 1vanK** [comment]
I had an assumption that you are using links instead of real folders with resources.

**Comment by kannsokusha** [comment]
> > Can you clarify which paths the editor cannot find?
> 
> It can not recongnize anything.
> For example, before I compress it, I can copy my model to data\model folder and I can search for it in the editor.
> Then I compress it and unpack.
> In the unpack version,this function will not work.

The editor's default resource path and other editor configs is stored in the user folder C:\Users\your username\AppData\Roaming\urho3d.
If you want to use an editor from another location, you can delete it.

**Comment by SoNewBee** [comment]
> > It seems that it is checked by default.
> 
> try uncheck
> 
> > But I can not provide it because it is too big(about 1.5GB).
> 
> I can't even imagine what you put in the archive

Just compress the compiled engine.Samples are included.
I compile the source code with VS2017 Release mode.

> > It seems that it is checked by default.
> 
> try uncheck
> 
> > But I can not provide it because it is too big(about 1.5GB).
> 
> I can't even imagine what you put in the archive

Just compress the compiled engine.Samples are included.
I compile the source code with VS2017 Release mode.
Now I can not uncheck it because I deleted the newest version and recompile 1.7.1 version.
But when I open the editor,the same problem like the newest version came up.
And now I can not even open the samples.It shows a dialog with the information that I can not understand.
I have recompiled the source code about 10 times,but the problem still there.

**Comment by SoNewBee** [comment]
> > > Can you clarify which paths the editor cannot find?
> > 
> > 
> > It can not recongnize anything.
> > For example, before I compress it, I can copy my model to data\model folder and I can search for it in the editor.
> > Then I compress it and unpack.
> > In the unpack version,this function will not work.
> 
> The editor's default resource path and other editor configs is stored in the user folder C:\Users\your username\AppData\Roaming\urho3d.
> If you want to use an editor from another location, you can delete it.

I have tried this.
And I always delete the xx\Romaing\urho3d folder before I compile the source code.
It seems that nothing changed.
I have tried to modify the file path in the xml file and open the editor,it worked.
But many error shows and it seems that I should put everything to the path like "xx\bin\Autoload\LargeData\Models".
If I am not doing this,it can not find anything.
Very complicated.

**Comment by 1vanK** [comment]
you cannot show the archive, so at least record a video demonstrating the problem

**Comment by SoNewBee** [comment]
> you cannot show the archive, so at least record a video demonstrating the problem

OK,I will try.

**Comment by SuperWangKai** [comment]
You could use ScreenToGif  https://www.screentogif.com/

**Comment by SoNewBee** [comment]
> You could use ScreenToGif https://www.screentogif.com/

Thanks a lot.

**Comment by SoNewBee** [comment]
![good](https://user-images.githubusercontent.com/51787223/102102510-dbca8100-3e66-11eb-98c6-df5a13d7ee65.gif)
This is how I make the project.
After this gif, I opened VS2017 and clicked Generate by using Release mode.

**Comment by SoNewBee** [comment]
![good3](https://user-images.githubusercontent.com/51787223/102103109-89d62b00-3e67-11eb-85de-74c58ebc06c8.gif)
As you can see,I opened the editor and it can not locate the correct file path.
The searching function will not work also.

**Comment by 1vanK** [comment]
I didn't see anything that I wanted to see

**Comment by 1vanK** [comment]
I am closing this issue because you require us to have telepathic abilities. You can continue the further discussion on the forum, maybe someone can guess the source of your problem.
