### ISSUE TITLE
Can't build (ArchLinux 64, gcc)

### ISSUE THREAD

**Issue by br3eze** [urho3d/Urho3D#2758]
Sorry, don't know is the master branch at working state or not, but there were no commits for a long time.
mkdir build; cd build; cmake .. && make leads to this

[ 77%] Linking CXX static library ../../lib/libUrho3D.a
Merging all archives into a single static library using ar
[ 77%] Built target Urho3D
Scanning dependencies of target Urho3DPlayer
[ 77%] Building CXX object Source/Tools/Urho3DPlayer/CMakeFiles/Urho3DPlayer.dir/Urho3DPlayer.cpp.o
[ 77%] Linking CXX executable ../../../bin/Urho3DPlayer
/usr/bin/ld: ../../../lib/libUrho3D.a(SDL_surface.c.o):(.bss+0x0): multiple definition of `WAYLAND_wl_proxy_get_user_data'; ../../../lib/libUrho3D.a(SDL_video.c.o):(.bss+0x0): first defined here
/usr/bin/ld: ../../../lib/libUrho3D.a(SDL_surface.c.o):(.bss+0x8): multiple definition of `WAYLAND_wl_proxy_set_user_data'; ../../../lib/libUrho3D.a(SDL_video.c.o):(.bss+0x8): first defined here
/usr/bin/ld: ../../../lib/libUrho3D.a(SDL_surface.c.o):(.bss+0x10): multiple definition of `WAYLAND_wl_proxy_add_listener'; ../../../lib/libUrho3D.a(SDL_video.c.o):(.bss+0x10): first defined here
...

How can it be solved?

**Comment by 1vanK** [comment]
As the last active contributor, I can say that this problem can be solved only if you find the source of the problem and send a pull request, because I am not using Linux.

**Comment by br3eze** [comment]
Is this engine dead already and I should choose another one without need to fix something?
Or this is just about time?

**Comment by 1vanK** [comment]
There are no engines that fully satisfy all your needs. Either way, you will need to make an effort. If you are not ready for this, changing the engine will not help you, you should think about changing the type of activity.

**Comment by SuperWangKai** [comment]
Please see this -https://discourse.urho3d.io/t/build-system-broken/6653

**Comment by SuperWangKai** [comment]
https://github.com/urho3d/Urho3D/issues/2755

**Comment by eugeneko** [comment]
> Is this engine dead already and I should choose another one without need to fix something?
> Or this is just about time?

Urho3D is supported (improved, updated and fixed) by its users (aka you, among others).
If it doesn't fit you, you can pick an engine with actual paid staff working on it full-time (Unity, UE, Unigine, Godot, etc).

**Comment by br3eze** [comment]
didn't helped.

> There are no engines that fully match all your needs.

Oh, You're so wrong. 
Urho3D actually is my ideal for simple C++ games and there're no alternatives(!). But like eugeneko said "paid staff working on it full-time" wanted here. Sad but I have no time to support it. 
I already worked with UE4 (AAA projects), cocos2d-x and I can say we really need projects like Urho3D. 
Will try to work with it for some more time anyway. 
Thank You!

**Comment by stievie** [comment]
Try to disable `VIDEO_WAYLAND`, that worked for me on Manjaro. See here https://discourse.urho3d.io/t/linker-issue-with-urh3d-1-7-1-and-gcc-10-1-0-on-linux-manjaro-20-0-3/6221/4

**Comment by br3eze** [comment]
> Try to disable `VIDEO_WAYLAND`, that worked for me on Manjaro. See here https://discourse.urho3d.io/t/linker-issue-with-urh3d-1-7-1-and-gcc-10-1-0-on-linux-manjaro-20-0-3/6221/4

But how about people with wayland, they're left behind here so it's a partial solution.
Anyway, thank You, it works!

**Comment by SirNate0** [comment]
The issue might be the same as the one here, which seems to be from using GCC 10 and was fixed by adding `-fcommon`
https://github.com/onivim/oni2/issues/1778

**Comment by dmlo** [comment]
-DVIDEO_WAYLAND=OFF fixes this issue on Arch for both GCC and Clang.
