### ISSUE TITLE
build failed for android on linux!

### ISSUE THREAD

**Issue by tigerpeng** [urho3d/Urho3D#2767]
* What went wrong:
Execution failed for task ':android:launcher-app:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process ninja with arguments {-C /root/Urho3D/android/launcher-app/.cxx/cmake/debug/armeabi-v7a Urho3DPlayer}
  ninja: Entering directory `/root/Urho3D/android/launcher-app/.cxx/cmake/debug/armeabi-v7a'

  ninja: error: '/root/Urho3D/android/urho3d-lib/.cxx/cmake/debug/armeabi-v7a/lib/libUrho3D.so', needed by '../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libUrho3DPlayer.so', missing and no known rule to make it

**Comment by SuperWangKai** [comment]
When building samples on Android, we need to define `URHO3D_LIB_TYPE` to `1` as an environment variable -

https://discourse.urho3d.io/t/build-system-broken/6653/9

Hope it helps.

**Comment by tigerpeng** [comment]
I have set the environment variable, but I still get the same error.

This scheme fails
./gradlew cleanAll
./gradlew -PANDROID_ABI=armeabi-v7a -PURHO3D_LUA=0 -PURHO3D_LUAJIT=0 -PURHO3D_LIB_TYPE=SHARED -PURHO3D_SAMPLES=1 clean build --stacktrace

The second is also a failure
./gradlew cleanAll
# echo $URHO3D_LIB_TYPE
SHARED
# echo $URHO3D_LUA
0
# echo $URHO3D_LUAJIT
0

./gradlew -PANDROID_ABI=armeabi-v7a  -PURHO3D_SAMPLES=1 clean build --stacktrace

**Comment by tigerpeng** [comment]
Compiled successfully ！   I made a mistake

thanks！

**Comment by br3eze** [comment]
Can someone help me with this? First time working with Android as is, without scripts-helpers like in other project where it's very simple. Already died inside trying to build:

Urho3D/master

export .... NDK/android-ndk-r21d/prebuilt/linux-x86_64/bin/    (also tried r10e)
export .... SDK includes for Android 8.1 (API 27, rev. 3) installed with AndroidStudio
 
./gradlew cleanAll
./gradlew -PANDROID_ABI=armeabi-v7a (also tried x86_64) -PURHO3D_LUA=0 -PURHO3D_LUAJIT=0 -PURHO3D_LIB_TYPE=SHARED -PURHO3D_SAMPLES=1 build

No errors about SDK & NDK, then:

Execution failed for task ':android:urho3d-lib:generateJsonModelDebug'.
> java.lang.NullPointerException (no error message)
