### ISSUE TITLE
"First Project" Movement Issue

### ISSUE THREAD

**Issue by nickwebha** [urho3d/Urho3D#2777]
I copied and pasted the example from [First Project](https://github.com/urho3d/Urho3D/wiki/First-Project) but the forwards and backwards movement (KEY_W, KEY_S) is all slanted. It strafes left and right just fine but forwards and backwards move on a slant. The kicker is, if I define `__DEBUG__` and have it run in a window, everything works fine.

**Comment by 1vanK** [comment]
Use forum
