### ISSUE TITLE
SDL "Cannot open source/include file" issue when trying to build project

### ISSUE THREAD

**Issue by tijon1** [urho3d/Urho3D#2810]
I'm using Visual Studio 2022 and Vcpkg.
## Build output

```
Build started...

1>------ Build started: Project: GeometryTest, Configuration: Debug Win32 ------

1>MyApp.cpp

1>C:\Users\??????\vcpkg\installed\x86-windows\include\Urho3D\Input\InputConstants.h(30,10): fatal error C1083: Cannot open include file: 'SDL/SDL_joystick.h': No such file or directory

1>Done building project "GeometryTest.vcxproj" -- FAILED.

========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

## Error list after trying to building
```
E1696	cannot open source file "SDL/SDL_joystick.h"
E1696	cannot open source file "SDL/SDL_gamecontroller.h"
E1696	cannot open source file "SDL/SDL_keycode.h"	
E1696	cannot open source file "SDL/SDL_mouse.h"
C1083	Cannot open include file: 'SDL/SDL_joystick.h'

```
## Steps to reproduce
1. Download Visual Studio (2022, haven't tried using Urho3D on other versions of VS)
2.Install the Urho3D package via Vcpkg via "vcpkg install urho3d"
3.Create a empty project in VS
4.Use the application framework in the link below (no modifications)
https://urho3d.io/documentation/1.7.1/_main_loop.html
5.Build the solution/project

**Comment by weitjong** [comment]
We do not support vcpkg officially. Please contact directly the person who build that package.

**Comment by gleblebedev** [comment]
I've contacted the author of the package. He can't look into this now, may help to resolve the issue it a week or two.

**Comment by JackBoosY** [comment]
I'm vcpkg maintainer.
After some investigations, I found that the third-party library version used in the build process in Urho3D is inconsistent with the version in vcpkg, and some dependent codes **have been modified** (such as SDL), which makes it impossible to adapt to the upstream official version code.
The only way is to export these "private" header files to include.

**Comment by eugeneko** [comment]
> and some dependent codes have been modified (such as SDL)

I think about a half of Urho 3rdparties are modified custom versions.
Urho will not work otherwise, even if you will manage to build it.

**Comment by koprok** [comment]
Hi @tijon1,

I am the creator of the Urho3D package in Vcpkg. @JackBoosY and @eugeneko are right: Urho3D contains a custom versions of SDL and other 3rd party libraries. These 3rd party libraries (SDL in particular) are linked-in into the main Urho3D library. The include files of these 3rd party libraries are also installed in "Urho3D/ThirdParty" subdirectory inside Vcpkg include directory. What you have to do is to add this "Urho3D/ThirdParty" directory to your include path.

Now, I currently don't have a Windows PC with Visual Studio at hand. But I have tried similar steps to reproduce the issue on a Linux machine and the same happens. I use CMake to build my projects and I have prepared a simple CMakeLists.txt file that contains the very basics needed to build the above mentioned application framework example on Linux. Here is it:

```cmake
cmake_minimum_required(VERSION 3.16)

project(urho3d_issue_2810)

find_package(OpenGL REQUIRED)
find_package(Threads REQUIRED)

# Find Urho3D include dirs
find_path(URHO3D_INCLUDE_DIRS "Urho3D/Urho3D.h")
find_path(URHO3D_THIRDPARTY_INCLUDE_DIRS "SDL/SDL_gamecontroller.h" PATH_SUFFIXES "Urho3D/ThirdParty")
list(APPEND URHO3D_INCLUDE_DIRS ${URHO3D_THIRDPARTY_INCLUDE_DIRS})
message(STATUS "Urho3D include dirs: ${URHO3D_INCLUDE_DIRS}")

# Find Urho3D library
find_library(URHO3D_LIBRARY "Urho3D" PATH_SUFFIXES "Urho3D")
message(STATUS "Urho3D library: ${URHO3D_LIBRARY}")

add_executable(urho3d_issue_2810 main.cpp)
target_include_directories(urho3d_issue_2810 PRIVATE ${URHO3D_INCLUDE_DIRS})
target_link_libraries(urho3d_issue_2810 PRIVATE
    ${URHO3D_LIBRARY}
    ${OPENGL_LIBRARY}
    ${CMAKE_DL_LIBS}
    Threads::Threads)
```

Put this CMakeLists.txt file together with main.cpp file that contains the example source code. Here is also how I build it on Linux:
```
cmake -D CMAKE_TOOLCHAIN_FILE=~/vcpkg/scripts/buildsystems/vcpkg.cmake -B build
cmake --build build
```

To make this CMakeLists.txt file work on Windows with Visual Studio compiler, some minor tweaks will be needed (maybe some additional Windows-specific libraries have to be added). I hope this helps.
