### ISSUE TITLE
GetCompilerDefines of LibraryInfo is not complete

### ISSUE THREAD

**Issue by SuperWangKai** [urho3d/Urho3D#2813]
Is there some automation approach we can use to dump the defines to this cpp?

[LibraryInfo.cpp](https://github.com/urho3d/Urho3D/blob/master/Source/Urho3D/LibraryInfo.cpp)

**Comment by weitjong** [comment]
It was not designed for general purpose usage. It was originally used in our “FindUrho3D” CMake module and it worked fine for some time. Having said that, I consider it to be remnant of the past. Those old CMake scripts and their related counterparts should be replaced.
