### ISSUE TITLE
Scene Deconstructor crash [MSVC?!]

### ISSUE THREAD

**Issue by An0nyMooUS** [urho3d/Urho3D#2817]
If I make a  global `Shared_Ptr<Scene>` like:

`SharedPtr<Scene> abc;`

In the start() method:

`abc = SharedPtr<Scene>(new Scene(context_));`

If I close the window, it crashes.

![image](https://user-images.githubusercontent.com/73304497/127862816-b18237a6-46ff-440c-8326-517e8096a648.png)

**Comment by 1vanK** [comment]
https://github.com/urho3d/Urho3D/issues/802

**Comment by XXxR4GALXxx** [comment]
> #802

Why is this only in debug mode? in release mode works correctly. :thinking:

**Comment by 1vanK** [comment]
You can register own subsystem Global and store all global varibles there. 

> in release mode works correctly.

Probably no checks happen in the release version (for performance reasons)

**Comment by XXxR4GALXxx** [comment]
> You can register own subsystem Global and store all global varibles there.

how?

**Comment by 1vanK** [comment]
RegisterSubsystem()
