### ISSUE TITLE
compile with swift failed

### ISSUE THREAD

**Issue by newNcy** [urho3d/Urho3D#2821]
I want to add a empty swift file into source of main, then I use define_source_files (RECURSE GROUP GLOB_CPP_PATTERNS *.m *.mm *.cpp *.swift). 
but after generating Xcode project, the .swift file not at the compile source of target in Xcode build setting.

**Comment by weitjong** [comment]
Have you tried to enable the `swift` language in your CMakeLists.txt anywyere?

https://cmake.org/cmake/help/latest/generator/Xcode.html
