### ISSUE TITLE
launcher-app crash

### ISSUE THREAD

**Issue by Ganerdene** [urho3d/Urho3D#2822]
on android phone when click samples nothing show or crash

08/22 02:14:06: Launching 'launcher-app' on Google Pixel 2.
$ adb shell am start -n "io.urho3d.launcher/io.urho3d.launcher.LauncherActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 8525 on device 'google-pixel_2-HT7B11A01793'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
I/AdrenoGLES-0: QUALCOMM build                   : e883189, Ia11ce2d146
    Build Date                       : 09/02/20
    OpenGL ES Shader Compiler Version: EV031.31.04.00
    Local Branch                     : gfx-adreno.lnx.2.0
    Remote Branch                    : quic/gfx-adreno.lnx.2.0
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING
I/AdrenoGLES-0: Build Config                     : S L 10.0.5 AArch64
    Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
I/AdrenoGLES-0: PFP: 0x005ff113, ME: 0x005ff066
W/AdrenoUtils: <ReadGpuID_from_sysfs:197>: Failed to open /sys/class/kgsl/kgsl-3d0/gpu_model
    <ReadGpuID:221>: Failed to read chip ID from gpu_model. Fallback to use the GSL path
I/Gralloc4: mapper 4.x is not supported
W/Gralloc3: mapper 3.x is not supported
V/SDL: Device: walleye
    Model: Pixel 2
    onCreate()
V/SDL: nativeSetupJNI()
V/SDL: AUDIO nativeSetupJNI()
    CONTROLLER nativeSetupJNI()
D/hidapi: Initializing Bluetooth
V/SDL: onStart()
V/SDL: onResume()
V/SDL: surfaceCreated()
    surfaceChanged()
    pixel format RGB_565
    Window size: 1920x1044
    Device size: 1920x1080
V/SDL: Running main function SDL_main from library lib01_HelloWorld.so
    nativeRunMain()
V/SDL: surfaceChanged()
    pixel format RGB_565
    Window size: 1920x991
    Device size: 1920x1080
I/Urho3D: Created 7 worker threads
I/Urho3D: Added resource path /apk/Data/
I/Urho3D: Added resource path /apk/CoreData/
E/libEGL: validate_display:87 error 3008 (EGL_BAD_DISPLAY)
V/SDL: onWindowFocusChanged(): true
V/SDL: setOrientation() orientation=6 width=1024 height=768 resizable=false hint=LandscapeLeft LandscapeRight
V/SDL: nativeFocusChanged()
I/Urho3D: Adapter used Qualcomm Adreno (TM) 540
    Set screen mode 1920x991 rate 0 Hz windowed monitor 0
I/Urho3D: Initialized input
    Initialized user interface
E/Urho3D: Could not find resource Textures/Ramp.png
E/Urho3D: Could not find resource Textures/Spot.png
E/Urho3D: Could not find resource Techniques/NoTexture.xml
E/Urho3D: Could not find resource RenderPaths/Forward.xml
I/Urho3D: Initialized renderer
    Initialized engine
E/Urho3D: Could not find resource UI/ScreenJoystick_Samples.xml
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x48 in tid 8601 (SDLThread), pid 8525 (SDLActivity)
Connected to process 8623 on device 'google-pixel_2-HT7B11A01793'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
I/AdrenoGLES-0: QUALCOMM build                   : e883189, Ia11ce2d146
    Build Date                       : 09/02/20
    OpenGL ES Shader Compiler Version: EV031.31.04.00
    Local Branch                     : gfx-adreno.lnx.2.0
    Remote Branch                    : quic/gfx-adreno.lnx.2.0
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING
    Build Config                     : S L 10.0.5 AArch64
    Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
I/AdrenoGLES-0: PFP: 0x005ff113, ME: 0x005ff066
W/AdrenoUtils: <ReadGpuID_from_sysfs:197>: Failed to open /sys/class/kgsl/kgsl-3d0/gpu_model
    <ReadGpuID:221>: Failed to read chip ID from gpu_model. Fallback to use the GSL path
I/Gralloc4: mapper 4.x is not supported
W/Gralloc3: mapper 3.x is not supported

**Comment by weitjong** [comment]
The errors indicate you have issue with your app's assets directory. Check the content of `android/launcher-app/src/main/assets` in the Urho3D project root. It should contain two symlinks to the actual directories. 
```
$ ls -l
total 8
lrwxrwxrwx. 1 weitjong weitjong 27 May 12  2020 Autoload -> ../../../../../bin/Autoload
lrwxrwxrwx. 1 weitjong weitjong 23 May 12  2020 Data -> ../../../../../bin/Data
```
On Windows host system, you will have to replace these two symlinks with the hard-copies of the corresponding directories.
