### ISSUE TITLE
UniquePtr not set to nullptr when constructed with nullptr

### ISSUE THREAD

**Issue by SirNate0** [urho3d/Urho3D#2852]
I believe these lines reflect a bug, the UniquePtr's `ptr_` value does not seem to be set to `nullptr` when the UniquePtr is constructed with a `nullptr`.

https://github.com/urho3d/Urho3D/blob/master/Source/Urho3D/Container/Ptr.h#L588
```
    /// Construct empty.
    UniquePtr(std::nullptr_t) { }   // NOLINT(google-explicit-constructor)
```

**Comment by eugeneko** [comment]
Oh wow. This mistake was there for 5 years... I guess I just assumed that ptr_ has default value.
