### ISSUE TITLE
Size of wasm binary?

### ISSUE THREAD

**Issue by lonnietc** [urho3d/Urho3D#2855]
Hello,

I am seeking a very small 2D engine that is capable of webassembly and that loads very fast in browsers for simple 2D games like a 2D Maze, for example.

Can you please tell me more about the wasm sizes of Urho3D for simple applications?
Thanks in advance

**Comment by eugeneko** [comment]
When I boil it down to the absolute minimum, I get this:
![image](https://user-images.githubusercontent.com/8576192/146784315-66629c11-cd5a-4913-b7cb-0606b1a2f570.png)
https://eugeneko.itch.io/snake4d

**Comment by lonnietc** [comment]
Thanks as this is very helpful.

I will have to search for some 2D WebAssembly engines as well, but thinking ahead, in the future I could also see possibly having some simple 3D game widgets as well and Urho3D might be the best approach at that time.

Have a great day
