### ISSUE TITLE
Editor Argument Parsing

### ISSUE THREAD

**Issue by SirNate0** [urho3d/Urho3D#2858]
I may be wrong, but shouldn't the `break`s be `continues` in this code? It seems to me that it's impossible to pass a scene and a language as is.

https://github.com/urho3d/Urho3D/blob/4075d36fe75bf834410c80c9207d6055e8b82761/bin/Data/Scripts/Editor.as#L102-L126

**Comment by 1vanK** [comment]
```
if (++i < arguments.length) 
```

`++i` allows to get next agrument

**Comment by 1vanK** [comment]
There is a more serious error. `i` can be out of range if command line is `Editor.bat -scene`
