### ISSUE TITLE
You don't deserve the privileges that you were given tot this project.

### ISSUE THREAD

**Issue by iSLC** [urho3d/Urho3D#2870]
@1vanK You are a goddamn joke man. Seriously? People of this community really need to review your behavior. What the heck is wrong with you?

![screenshot](https://i.imgur.com/hwvlpjO.png)

**Comment by 1vanK** [comment]
Please don't use bug tracker for trashtolking.

**Comment by iSLC** [comment]
> Please don't use bug tracker for trashtolking.

I would use other means of communication. But oh, wait. I can't!

**Comment by 1vanK** [comment]
If you continue I have to ban you here , you will lose the opportunity to submit a PR
