### ISSUE TITLE
Does urho3d support Korean?

### ISSUE THREAD

**Issue by zdx1012** [urho3d/Urho3D#2877]
When I display Korean characters, boxes are displayed on the screen
![image](https://user-images.githubusercontent.com/23023879/154637264-08c730c6-28e0-452e-b608-a78de73cf150.png)

**Comment by eugeneko** [comment]
I am not sure built-in fonts contain Korean characters, but Urho should be able with rendering any left-to-right script, provided appropriate font.

**Comment by zdx1012** [comment]
@eugeneko I tried different font files, such as Microsoft YaHei font. I tried to use Python language to call the same font file to draw a picture. I don't understand why the correct text can't be displayed on urho3d?

**Comment by 1vanK** [comment]
@weitjong I fully support your idea to add a new beautifulfont with a large character set. We can use it in Editor that already has multilingual support.

**Comment by weitjong** [comment]
@1vanK Maybe Roboto font for default and one of the Noto Sans fonts based on the chosen CJK language. Yes, that would be nice.

**Comment by 1vanK** [comment]
Old Anonymous Pro.ttf
![изображение](https://user-images.githubusercontent.com/13021826/154792587-1e4cd1a9-516d-4f12-8cfb-3d6fc8190355.png)

NotoSans-Regular
![изображение](https://user-images.githubusercontent.com/13021826/154792539-7c9b4bbf-f4d2-4feb-bba9-0aea34c0a347.png)

Roboto-Regular
![изображение](https://user-images.githubusercontent.com/13021826/154792515-3ce869c6-3bfc-4644-a94c-4b3d1935773a.png)

**Comment by weitjong** [comment]
Just quickly glanced it on my iPhone. My eyes tell me Roboto is better. Just my two cents.

**Comment by 1vanK** [comment]
+

**Comment by weitjong** [comment]
Back to the original topic. We might also need a few language-specific Noto sans font files for the CJK language that we might want to support. See https://fonts.google.com/?query=noto+sans
