### ISSUE TITLE
Building for Macbook M1 Pro based machines

### ISSUE THREAD

**Issue by advaitraut** [urho3d/Urho3D#2880]
Hi
What is the correct way to build Urho3D on Macbook M1 Pro based machines ?
What is the correct cmake command to build it ?

**Comment by 1vanK** [comment]
At the moment we do not have developers using Apple products. You can take on this work.

**Comment by weitjong** [comment]
It is currently not possible as SDL itself has yet to support Apple Silicon properly and Urho3D relies on SDL for platform support. I don't have time to test this myself with my MBP M1 Max, but from the SDL's forums I found only a few posts with user having trouble with Apple Silicon.
