### ISSUE TITLE
54_WindowSettingsDemo: Resizable flag works only on OpenGL

### ISSUE THREAD

**Issue by 1vanK** [urho3d/urho3d#2898]

**Comment by 1vanK** [comment]
The sample uses deprecated function `graphics->SetMode()`

**Comment by 1vanK** [comment]
`bool SetScreenMode(int width, int height, const ScreenModeParams& params, bool maximize = false);` also not changes `resizable` for already created window on D3D9 & D3D11

**Comment by eugeneko** [comment]
AFAIK it's just impossible to change resizability on the fly.
OpenGL cannot change anything at all in created context, so it just recreates window with new params.
