### ISSUE TITLE
Mismatched Case in SLikeNet include path

### ISSUE THREAD

**Issue by SirNate0** [urho3d/Urho3D#2908]
When building with docker, I'm noticing a fairly large number of errors similar to 
`
../../../../../../Source/Urho3D/Network/Network.cpp:43:10: warning: non-portable path to file '<slikenet/peerinterface.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
#include <SLikeNet/peerinterface.h>
`

We should probably either change the folder case to match the includes or change the includes to match the folder case.

**Comment by 1vanK** [comment]
The problem is somewhat more complicated, because when compiling on Windows, the header files are installed in a directory with the correct name
![1](https://user-images.githubusercontent.com/13021826/165228672-7c83742d-80d3-40c4-83fc-ff81049247f2.png)

**Comment by 1vanK** [comment]
Can you test this? https://github.com/urho3d/Urho3D/pull/2910
