### ISSUE TITLE
Doxygen listing URHO3D_OBJECT as a function in UISelectable

### ISSUE THREAD

**Issue by SirNate0** [urho3d/Urho3D#3010]
It's an issue for my lua binding script - doxygen is listing URHO3D_OBJECT as a function in UISelectable. You can see it in the online documentation as well:

https://urho3d.io/documentation/HEAD/class_urho3_d_1_1_u_i_selectable.html

--- 

Not sure if it is an error or not, but it then lists for the constructor:

> [UIElement](https://urho3d.io/documentation/HEAD/class_urho3_d_1_1_u_i_selectable.html#a5094f1083fac273772c260e5f310bbf2) ([Context](https://urho3d.io/documentation/HEAD/class_urho3_d_1_1_context.html) *context)

This may be correct, since UISelectable has the following:
```c++
    /// Construct.
    using UIElement::UIElement;
```

**Comment by 1vanK** [comment]
This is a known issue, in my binding generator I keep a list of defines to distinguish between defines and functions
