### ISSUE TITLE
TileMapLayer2D using raw pointers to RefCounted

### ISSUE THREAD

**Issue by SirNate0** [urho3d/Urho3D#3013]
You can see from a copy of the documentation, `TileMapLayer2D` is using 4 const raw pointers to various layer/group data. All of these classes derive from `RefCounted`, though, so I'm not sure why they are not weak pointers or shared pointers instead.

Type | Variable | From  [Docs TileMapLayer2D.h](https://urho3d.io/documentation/HEAD/class_urho3_d_1_1_tile_map_layer2_d.html#a2f03d074501817638269f1b3f8db078d)
-- | -- | --
const TmxLayer2D * | tmxLayer_ {}  | Tmx layer.
const TmxTileLayer2D * | tileLayer_ {}  | Tile layer.
const TmxObjectGroup2D * | objectGroup_ {}  | Object group.
const TmxImageLayer2D * | imageLayer_ {}  | Image layer.

---

Disclaimer: I have basically no experience with the Urho2D side of things, I'm just coming across some things with it in trying to automate the Lua bindings. It wouldn't affect me, except the bindings store all things derived from `RefCounted` in `SharedPtr `(so the Lua will own a copy) and I can't construct a `SharedPtr` from the `const T*` because `AddRef()` cannot be called on a `const` object.

**Comment by 1vanK** [comment]
I believe that bindings should not restrict the style of C++ code, C++ code authors should not think about bindings, that's the point of automation. Anything that cannot be linked automatically can be binded manually

**Comment by SirNate0** [comment]
I agree fully with that notion. I just am wondering in this case if the existing code is incorrect (or really, not following the best practice - it obviously functions correctly). Since the pointed-to objects are RefCounted, why is the count not being updated by the TileMapLayer2D object to reflect that it is using them? There are several possibly good reasons for the code being the way it is, I'm just not aware of them myself (and am not interested enough in 2D games to try and figure it out on my own).
