### ISSUE TITLE
Not building on arch Linux.

### ISSUE THREAD

**Issue by ItisrainingMasterDwarf** [urho3d/Urho3D#3145]
Not building on arch Linux.
```
 [ 91%] Linking CXX static library libAssimp.a
[ 91%] Built target Assimp
make: *** [Makefile:156: all] Error 2

```
And there are no messages explaining what went wrong.

**Comment by 1vanK** [comment]
Our CI/CD successfully build the Engine on Ubuntu with GCC, Clang and MingGW. No one can help you without more information. The error message can be much higher in the log because the compilation is multi-threaded

**Comment by 1vanK** [comment]
Try reproduce this on your local machine https://github.com/urho3d/Urho3D/blob/master/.github/workflows/main.yml#L417-L455

**Comment by ItisrainingMasterDwarf** [comment]
Same error. OK. Sorry. I will try to build on Ubuntu. It just strange error without any description even with VERBOSE=1 parameter.
