### ISSUE TITLE
Collisions not Registering

### ISSUE THREAD

**Issue by hjmediastudios** [urho3d/Urho3D#396]
I have a situation where I'm calling PhysicsWorld::GetRigidBodies; two rigid body objects are colliding with the specified rigid body, but the resulting list is empty.
1. Collision masks and layers are set appropriately- the objects should be colliding.
2. The colliders are appropriately shaped, and using DrawDebugGeometry clearly shows the colliders are intersecting.
3. The call is within a method triggered by the PostUpdate event.

**Comment by reconndev** [comment]
Thanks! That led me to the solution of my problem.

I was searching for it all over the Internet. I had static-static collisions, too. I changed to kinematic with trigger but I also needed to create a **separate child node** first. Otherwise the trigger wouldn't work.
