### ISSUE TITLE
Multiple Terrain splatmaps/materials

### ISSUE THREAD

**Issue by luveti** [urho3d/Urho3D#434]
Is there support for using more than 3 textures on a Terrain? I have a feeling this will require that the terrain is rendered more than once if you want to have more than just 3 (2 times if you want 6 textures, 3 times if you want 9 textures, etc.)

**Comment by JTippetts** [comment]
Is it "safe" to modify the current TerrainBlend shader to use register S4 for another detail shader, weighted by the alpha channel of the blend texture? I do this currently in my terrain editor, but I don't know what possible repercussions it might have for other platforms etc... Even having that one more detail layer makes a pretty big difference for my needs.

**Comment by cadaver** [comment]
Unit 4 is safe, as that is the environment channel. There was also a fairly recent modification that a material can define any of the texture units 0-15, not just the first 5. Units 5-9 are unsafe as they're used for lighting, 10-11 are used in deferred lighting, and 13 is reserved for the zone texture (if any in use).

We could probably just make the unit defines different on mobiles (max 8 units), though that has implications for precompiling scripts on desktop, then using them on mobile.
