### ISSUE TITLE
UI should be percentage of screen based, and not absolute

### ISSUE THREAD

**Issue by tersers** [urho3d/Urho3D#443]
There are a few ways to do this (which I can discuss in detail if so desired), but this would help for resizing and multiple resolutions. 

I know the idea is to make different layouts for different resolutions, but this method would cut down on a LOT of that work.

**Comment by argylelabcoat** [comment]
The Editor on a 4K display has microscopic UI elements that do not scale nicely. 
![2016-11-03_11-50-24](https://cloud.githubusercontent.com/assets/1558014/19975925/c9ff8be2-a1bb-11e6-8ed2-666a0e5b4c17.png)

I've worked with in-house engines that were completely relative size (percentage) based with anchor points.  I'm not saying that's best for Urho, but something should be done to support different DPIs even within the editor.

**Comment by mazataza** [comment]
any update for this Issue.
I work on a laptop with 4K Display and really working with this editor will make be blind somedays :-)

**Comment by hdunderscore** [comment]
I am not sure anyone is working on this yet, but in the meanwhile you can always change the ui scale, open the console and type:
```ui.scale = 2.0```

**Comment by mazataza** [comment]
how could i open the console?

**Comment by hdunderscore** [comment]
Press F1 while the editor is open. If you want the change to be more permanent, you can edit the editor script too.
