### ISSUE TITLE
ListView : Selection fails

### ISSUE THREAD

**Issue by vivienneanthony** [urho3d/Urho3D#459]
Hello

I'm trying to set up a SubscribeToEvent for a ListView. A simple selection. I have been testing a basic selection which fails. I attempted to attach the SubscribeToEvent to the actual ListView, UIElement, and Text components and I do not get in event.  I am not sure if it's me or Urho3D. The menu is hard coded. I am posting the code on PasteBin.

http://pastebin.com/VYJKDBS0

Any thoughts? Currently if I move the most outside the ListView nothing is highlighted. Also, If I attempt to set one of the options. It does not highlight. The SubscribeToEvent doesn't run either.

Vivienne

**Comment by hdunderscore** [comment]
I believe this question was answered, so closing.
