### ISSUE TITLE
[Request] 2D Ilumination (Color Lights + Shadows + Normals)

### ISSUE THREAD

**Issue by Hevedy** [urho3d/Urho3D#462]
I see nice changes in the 2D side of the engine and i like add ideas to this:
- Add option to use lights.
- Add color lights and color blend, and collision with object
- Add shadows, select if collide with the light and the value of shadow.
- Add penumbra and dark zones.
- Add normal map for detail the light in the sprites
- 2D Examples shaders & light.

Sources:
http://robotloveskitty.tumblr.com/post/33164532086/legend-of-dungeon-dynamic-lighting-on-sprites
http://www.gamedev.net/page/resources/_/technical/graphics-programming-and-theory/dynamic-2d-soft-shadows-r2032

**Comment by MonkeyFirst** [comment]
Today I trying understood with Urho2D made a simple sketch. With multiple sprites. 
I tried to add light to the scene and was very surprised that the lights has no effect on sprites. 
I think this feature is very necessary to 2D-renderer that we could make the effects of shading with normal map for sprites. 
As in this video : http://www.youtube.com/watch?v=Yuwbj4Nvu_o
or this video:
http://www.youtube.com/watch?v=W0H4vza9knM

I would not want to use a 3D renderer to get these 2D effects
