### ISSUE TITLE
Procedural geometry creation?

### ISSUE THREAD

**Issue by danhambleton** [urho3d/Urho3D#470]
Hi there,

I was wondering what the general method is for creating procedural geometry (i.e. meshes that constructed at runtime) and rendering them. From some reading, I have the following code:

```
//create scene node
Node* node = scene_->CreateChild("Object");
node->SetPosition(Vector3(0.0f, 0.0f, 0.0f));
StaticModel* object = node->CreateComponent<StaticModel>();

CustomGeometry*  _geometry = new CustomGeometry(context_); 
_geometry->BeginGeometry(0, TRIANGLE_LIST);

// tri 1
_geometry->DefineVertex(Vector3(-1, 0, 0));
_geometry->DefineTexCoord(Vector2(0.0, 0.0));

_geometry->DefineVertex(Vector3(1, 0, 0));
_geometry->DefineTexCoord(Vector2(0.0, 1.0));

_geometry->DefineVertex(Vector3(1, 0, 1));
_geometry->DefineTexCoord(Vector2(1.0, 0.0));

// tri 2
_geometry->DefineVertex(Vector3(-1, 0, 0));
_geometry->DefineTexCoord(Vector2(0.0, 1.0));

_geometry->DefineVertex(Vector3(1, 0, 1));
_geometry->DefineTexCoord(Vector2(1.0, 1.0));

_geometry->DefineVertex(Vector3(-1, 0, 1));
_geometry->DefineTexCoord(Vector2(1.0, 0.0));

_geometry->Commit();
_geometry->GetLodGeometry(0,0);

Model* model = new Model(context_);
model->SetGeometry(0, 0, _geometry->GetLodGeometry(0,0));

object->SetModel(model);
```

This doesn't seem to work; the model object doesn't get created properly. Is custom geometry class the way to go? Or should I be setting the vertex/index buffers of a geometry object directly?  Are static models the only way to display a mesh?

**Comment by florin-chelaru** [comment]
Hi, I'm trying to apply a texture on a static model generated this way ([DynamicGeometry.cpp](https://github.com/urho3d/Urho3D/blob/master/Source/Samples/34_DynamicGeometry/DynamicGeometry.cpp)), but with no luck. I saw DefineTexCoord on CustomGeometry, but there doesn't seem to be anything like it directly on Geometry. I am new at Urho3d, so maybe I'm going about it the wrong way?

**Comment by cadaver** [comment]
You must include a texcoord in your vertex declaration and fill the UV data to the vertex buffer, similarly how DynamicGeometry is filling positions & normals.

**Comment by florin-chelaru** [comment]
Got it, thank you!

**Comment by IgorMats** [comment]
@cadaver very useful thread!
