### ISSUE TITLE
Link errors in xcode 6 , when compiling for device  iphone 5 using ios8 target to ios 7

### ISSUE THREAD

**Issue by meiry** [urho3d/Urho3D#498]
getting linking errors 
This is what i did :
meirs-Mac-mini:Urho3D meiryanovich$ ./cmake_clean.sh 
meirs-Mac-mini:Urho3D meiryanovich$ ./cmake_ios.sh -DURHO3D_64BIT=0 -DURHO3D_SAMPLES=1

error:
Ld /Users/meiryanovich/Documents/3d/urho3d/git/Urho3D/ios-Bin/Urho3DPlayer.app/Urho3DPlayer normal armv7
    cd /Users/meiryanovich/Documents/3d/urho3d/git/Urho3D/Source
    export IPHONEOS_DEPLOYMENT_TARGET=7.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.0.sdk -L/Users/meiryanovich/Documents/3d/urho3d/git/Urho3D/ios-Bin -F/Users/meiryanovich/Documents/3d/urho3d/git/Urho3D/ios-Bin -filelist /Users/meiryanovich/Documents/3d/urho3d/git/Urho3D/ios-Build/Tools/Urho3DPlayer/Urho3D.build/Debug-iphoneos/Urho3DPlayer.build/Objects-normal/armv7/Urho3DPlayer.LinkFileList -dead_strip -framework AudioToolbox -framework CoreAudio -framework CoreGraphics -framework Foundation -framework OpenGLES -framework QuartzCore -framework UIKit -Wl,-search_paths_first -Wl,-headerpad_max_install_names /Users/meiryanovich/Documents/3d/urho3d/git/Urho3D/ios-Lib/libUrho3D.a -ldl -lpthread -lpthread -lpthread -ldl -lpthread -lpthread -miphoneos-version-min=7.0 -Xlinker -dependency_info -Xlinker /Users/meiryanovich/Documents/3d/urho3d/git/Urho3D/ios-Build/Tools/Urho3DPlayer/Urho3D.build/Debug-iphoneos/Urho3DPlayer.build/Objects-normal/armv7/Urho3DPlayer_dependency_info.dat -o /Users/meiryanovich/Documents/3d/urho3d/git/Urho3D/ios-Bin/Urho3DPlayer.app/Urho3DPlayer

ld: entry point (_main) undefined. for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by meiry** [comment]
say what is good tips to start clean and fresh project in xcode ? 
i will try to build working example from scratch that is not from the cmake generated files 
any tips ?

**Comment by xpol** [comment]
#604 have information about how to get native build work for OS X 10.10 and Xcode 6.

**Comment by weitjong** [comment]
I believe this can be closed now.

**Comment by meiry** [comment]
yes sure!
