### ISSUE TITLE
IOS orientation issue

### ISSUE THREAD

**Issue by abcjjy** [urho3d/Urho3D#553]
When launch Urho3dPlayer in the ios simulator, the orientation is wrong. The device turns to landscape mode while the app still use portrait. 
![hhh](https://cloud.githubusercontent.com/assets/1791493/5292866/ff96eee4-7ba2-11e4-9146-3220ff3ddfa9.png)

**Comment by meiry** [comment]
Any plans to fix it ? 
Thanks

**Comment by cadaver** [comment]
I briefly attempted a fix, by transplanting SDL head revision code. That did not help. There is already code in SDL to detect width / height mismatch but at some point it apparently still goes wrong. The fix seems not to be as straightforward as in GamePlay3D. Contributions are welcome.

**Comment by cadaver** [comment]
Added a simple fix based on forcibly resetting the window frame to the screen bounds on iOS8. There's something happening in SDL's view / controller code which prevents the automatic mechanism from working.

**Comment by meiry** [comment]
Thanks for your quick response 
So if i understand right we need to wait to new SDL release so it will be stable fix?
how stable is you fix ? do you reset the view once or each frame?

**Comment by cadaver** [comment]
The view reset is called when the OS decides to call it, probably when the screen is actually rotated. You should try for yourself; basic operation seemed to be OK but as stated in the commit message there are in the very least cosmetic problems when the screen keyboard appears.
