### ISSUE TITLE
break in Urho's foreach(v) buggy/doesn't work

### ISSUE THREAD

**Issue by Stinkfist0** [urho3d/Urho3D#561]
Example code to reproduce the bug:
```c++
Vector<int> v;
v.Push(1);
v.Push(2);
v.Push(3);
foreach(int val, v)
{
    if (val == 2)
        break;
    printf("%i\n", val);
}
```
Instead of expected
````
1
```
the code outputs
```
1
3
```

The foreachv macro also suffers from the same bug.

**Comment by spongebob** [comment]
Line 121 in Container/ForEach.h has the macro defined. As usual with iterator macros it's hard to read.

I think the problem might be that there are two nested for loops, break will only end one of them.

**Comment by Stinkfist0** [comment]
Yup, the second for-loop is problematic.

**Comment by OvermindDL1** [comment]
Huh, never noticed the foreach macro before, is there something wrong with C++'s natural for each construct?
```cpp
for (auto &item : myContainer) {
    // etc...
}
```
Or if you want backwards compat to very old versions of C++ then Boost's foreach could certainly be ripped out using bcc into the Urho3D's namespace and is very well tested:  http://www.boost.org/doc/libs/1_57_0/boost/foreach.hpp
I used it for years without issue, though I was a bit blasphemous and did `#define foreach BOOST_FOREACH`...  >.>
Thought not any worse than what Urho3D's define is...  ^.^
But still, the C++ spec defines `for (auto &item : myContainer)` syntax for foreach looping and has for many years now, are there really any compilers that do not support it anymore?

**Comment by Stinkfist0** [comment]
The macros are an outside contribution and are not used internally in Urho at all, as they use the C++11 `auto` feature and Urho is currently sticking to C++03 only.

**Comment by OvermindDL1** [comment]
In that case, especially due to the poor design of it, it should be removed.  The C++ standard has it built in now and if people really want one then they can use Boosts's, which is shown to work everywhere already and has sensical scoping.

And yes, the containers *really* should have been following standard conventions from the start, or just using the standard containers when available, compilers optimize those *really* well now.

**Comment by cadaver** [comment]
At this point, the primary reason for using Urho custom containers is predictable binary object size, which is needed for aggregation inside the Variant data structure. However adding STL compatibility and ditching the custom foreach is a good idea.

**Comment by dervus** [comment]
> Possibility to use the C++11 range-based for would require addition of STL-compliant lowercase begin() and end() functions.

AFAIK, it's not a mandatory. There are global functions std::begin and std::end, which can be overloaded to make custom container classes compatible with range-based for loop.

**Comment by Stinkfist0** [comment]
Ah, you're right. That's how range-based for works also for C arrays.

**Comment by Stinkfist0** [comment]
Also, IIRC, `foreach(int val, FunctionReturningVectorOfInts())` is buggy or crashes. It would seem best to simply remove these buggy macros altogether if no one has time to fix them.

**Comment by cadaver** [comment]
At this point the only notable user for these is tundra-urho3d which naturally has to be fixed / changed then, but in generally I agree; best to make a lightweight std::begin() & std::end() based solution and use C++11 foreach.

**Comment by cadaver** [comment]
Tested a C++11 range based for solution with std::begin() & std::end() overloads, it worked fine but will not work on VS2010 like the previous solution did. The main question is whether we find this acceptable for tundra-urho3d (this is starting to sound more like a tundra-urho3d issue than urho3d...)

**Comment by spongebob** [comment]
I'm really a C++ noob, is there a reason you can't subclass a vector (as an example) and set new allocators to? I'm sure there's a way to keep track of how much memory is used with the default containers (also alignment and packing) or I don't see anyone using them anywhere on modern architecture.

Also, as Bjarne says, "always use vectors, never linked lists" because you get the added bonus of remaining inside the cache longer when iterating, very much faster on Intel (and maybe others).

**Comment by cadaver** [comment]
I'm not talking about the dynamic memory allocated by a vector, but sizeof(vector).

**Comment by spongebob** [comment]
So, the containers in Urho3D can give a correct precompile sizeof for static or stack allocations? Like "Vector v[4]; sizeof(v);" would give sizeof(Vector) * 4 like any array? Anyway, don't mind my comment, I'm not really good enough with C++ to comment on advanced containers. I'll have a peek in the sources to learn more.

**Comment by cadaver** [comment]
No, it's not related to the data allocated by the Vector at at all, but the static Vector object size, which comes from:

´´´
    /// Size of vector.
    unsigned size_;
    /// Buffer capacity.
    unsigned capacity_;
    /// Buffer.
    unsigned char* buffer_;
´´´

If we were using STL vectors, the size would be implementation-dependent. But using our own Vectors we can safely store them inside a Variant without an additional dynamic allocation indirection. Strictly speaking it is not allowed to store non-POD objects inside an union, but the Variant class does the necessary calls to constructor & destructor to ensure it works right.
