### ISSUE TITLE
Question about per-vertex light processing in GetBasePatches

### ISSUE THREAD

**Issue by nemerle** [urho3d/Urho3D#568]
_Reader beware: I'm not 100% sure if the thing I'm describing is causing any actual issues at runtime, and I don't have enough experience with Urho3D to verify the correctness of current implementation._

Context:
The code below ( part of ```View::GetBatches()``` )  seems to be collecting per-vertex lights of a drawable, and constructing vertexLightQueues_ key value by calling GetVertexLightQueueHash. If vertexLightQueues_ does not contain such a hash, a new LightBatchQueue is constructed, and collected per-vertex lights are assigned to it. 

Now for the question :)

* Isn't it possible for GetVertexLightQueueHash in it's current form to return the same value for two different vectors of lights ? i.e.
```
vector1:
Light0 ptr value 0x04566100,
Light3 ptr value 0x04566400
GetVertexLightQueueHash(vector1) == 0x8ACC500

vector2:
Light1 ptr value 0x04566200,
Light2 ptr value 0x04566300
GetVertexLightQueueHash(vector1) == 0x8ACC500
```
* If there is such a clash, wouldn't that cause the collected per-vertex lights to be discarded, and not added to the proper queue ?

```c++
if (info.vertexLights_ && !drawableVertexLights.Empty())
{
    // For a deferred opaque batch, check if the vertex lights include converted per-pixel lights, and remove
    // them to prevent double-lighting
    if (deferred_ && destBatch.pass_->GetBlendMode() == BLEND_REPLACE)
    {
	vertexLights.Clear();
	for (unsigned i = 0; i < drawableVertexLights.Size(); ++i)
	{
	    if (drawableVertexLights[i]->GetPerVertex())
		vertexLights.Push(drawableVertexLights[i]);
	}
    }
    else
	vertexLights = drawableVertexLights;
    
    if (!vertexLights.Empty())
    {
	// Find a vertex light queue. If not found, create new
	unsigned long long hash = GetVertexLightQueueHash(vertexLights);
	HashMap<unsigned long long, LightBatchQueue>::Iterator i = vertexLightQueues_.Find(hash);
	if (i == vertexLightQueues_.End())
	{
	    i = vertexLightQueues_.Insert(MakePair(hash, LightBatchQueue()));
	    i->second_.light_ = 0;
	    i->second_.shadowMap_ = 0;
	    i->second_.vertexLights_ = vertexLights;
	}
	
	destBatch.lightQueue_ = &(i->second_);
    }
}
else
    destBatch.lightQueue_ = 0;
```

**Comment by cadaver** [comment]
On further reflection it's better that this works like it does now, so that a light queue with lights A B C is equivalent to lights C B A (or any other permutation), and we don't create an unnecessary new light queue. The possibility for an error due to pointers adding up just to the same value exists, but should be quite improbable.
