### ISSUE TITLE
Cannot set camera aspect ratio on Urho3D editor

### ISSUE THREAD

**Issue by ucupumar** [urho3d/Urho3D#571]
When I set camera aspect ratio, it always reset the value to something else. If I use perspective, it always reset to 1.778. If I use orthographic, it always reset to 1.0 when I save the scene.

**Comment by ucupumar** [comment]
Sorry for late-late response. It's been long holiday. 
I already uncheck auto aspect ratio, but Urho3D editor still won't save my inputted aspect ratio.
After some investigation, this happens if I change orthographic size other than 20 (default value). This happens even if I use perspective. Is this problem happen to you too?

**Comment by cadaver** [comment]
Thanks for the clarification, now I was able to find the cause (modification of ortho size as an attribute forces aspect ratio to 1.0) and it should be fixed in master.

**Comment by ucupumar** [comment]
Thanks cadaver!
