### ISSUE TITLE
Blender-Exported Animations Fail

### ISSUE THREAD

**Issue by hjmediastudios** [urho3d/Urho3D#576]
Using the Urho3D-Blender exporter script and Blender 2.72 allows for models to be exported without a problem, but animations do not play. Observing the file size of *.ani files and adding debug-print behavior to the exporter indicates that data is being exported, but the final animations do not play either in the application or in the Urho3D editor when "test" is hit. The model simply stays in its neutral pose.

**Comment by MonkeyFirst** [comment]
hmm, ok try to change path from your "animation" folder to std model path and set speed
Like in 18 CharacterDemo
'''
animCtrl->PlayExclusive("Models/Jack_Walk.ani", 0, true, 0.2f);
animCtrl->SetSpeed("Models/Jack_Walk.ani", planeVelocity.Length() * 0.3f);
'''
mb animation loads only from this folder and not from other
and comment this in your code:
'''
marineModel->AddAnimationState(cache->GetResource<Animation>("Animations/RunWhip.ani"));
'''
i don's see it in example 18 mb it's not needed

at last if you share your model (blend file) (or simular your example) i'm try to check it for playing by my self.

**Comment by hjmediastudios** [comment]
I've tried all of these. With our without adding the animation state, it doesn't work (but does either way with the Jack animation.) Placing the Jack_Walk animation in the same folder still plays, so it's not a path issue. Setting the speed makes no change.

**Comment by reattiva** [comment]
@hjmediastudios, I'm late but have you solved your problem? If not, can you reproduce it with a simple cube?

**Comment by hjmediastudios** [comment]
Nope; the problem remains unsolved. I can't reproduce it with a simple cube by definition, as the model itself exports correctly- it's the animation that's the problem.

**Comment by reattiva** [comment]
Can you send me at gmail.com the .blend file?

**Comment by hjmediastudios** [comment]
Sure thing; I just did.

**Comment by hjmediastudios** [comment]
After some more testing, the animation exports but does so incorrectly. I'll attempt to determine if this is an engine or exporter problem.

**Comment by gabdab** [comment]
Same problem .

**Comment by reattiva** [comment]
This was my reply to hj, maybe it suits you too:
"I've looked into it and it seems to work in the Urho editor. The only thing I had to do is setting the "Start Bone" to "Root". It was set to "Leg R", and this is due the fact that your skeleton has three bones at the root level, you'd better have only one."

**Comment by gabdab** [comment]
Where do you set the 'Start Bone' from ? Didn't find such field in Editor ..

**Comment by Mike3D** [comment]
It is available only after you have set "Animation Count" to at least 1.

**Comment by gabdab** [comment]
..they actually work flawless inside the editor . Must be my code ..

**Comment by christianclavet** [comment]
Hi, Looking at your post I've seen that. I'm not sure it the issue, but it's not a good practice. If you look at your export log:
---- Exporting Minifig ----
Creating file /home/.../Minifig.mdl
Creating file /home/.../Run with Rifle.001.ani

Please don't use spaces in names (meshes, animation names, and folder names). Could cause issues.
So the name should be written like this:
Run_with_Rifle.001.ani

**Comment by JimSEOW** [comment]
A good source to learn from others on how to export Blender to Orho3D

**Comment by yrpcity777** [comment]
Blender-Exported Animations and Beginner Web Code 

★§Androidアプリ入門編⑤☆Drawing 3D-Animation by UrhoSharp.Forms.
　http://yrpcity.dip.jp/strongbox/csherp/and023.html

★§Androidアプリ入門編⑥☆Multiple 3D-Animation by UrhoSharp.Forms.
　http://yrpcity.dip.jp/strongbox/csherp/and025.html

Beginner Web Code ↓↓↓

・§Androidアプリ入門編①☆Lottie Animation Forms.
　http://yrpcity.dip.jp/strongbox/csherp/and012.html

・§Androidアプリ入門編②☆Drawing 3D-Shape by UrhoSharp.Forms.
　　http://yrpcity.dip.jp/strongbox/csherp/and015.html

・§Androidアプリ入門編③☆xamarinのサンプル・3D-Cubeの棒グラフチャートを描く
　　http://yrpcity.dip.jp/strongbox/csherp/and016.html

・§Androidアプリ入門編④☆3D-おでん串 by UrhoSharp.Forms.
　　http://yrpcity.dip.jp/strongbox/csherp/and021.html

**Comment by weitjong** [comment]
Although I believe you meant good but I have to say that this is an English-speaking community!
