### ISSUE TITLE
Drag UI elemetrs by mouse in UI editor.

### ISSUE THREAD

**Issue by VladimirPobedinskiy** [urho3d/Urho3D#59]
Please add dragging UI elements by mouse in UI editor.

**Comment by eugeneko** [comment]
Is this issue resolved in scope of #1463?

**Comment by cadaver** [comment]
If this means actual dragging by mouse in the editor view (not in hierarchy), then not. Some elements can be made draggable (Window) but there's no actual drag-editing of the design like in Qt UI designer.
