### ISSUE TITLE
Shadows Flicker on Galaxy S2

### ISSUE THREAD

**Issue by practicing01** [urho3d/Urho3D#596]
For this project of mine: https://github.com/practicing01/FlowerPixieTsumiki  the scene nodes originally had shadows and everything worked fine on pc (linux).  On my  galaxy s2, the shadows flickered and the ground plane would flicker occasionally for brief periods so it was too dark to see the ground.  I had to turn off shadows.  Not sure if this is a bug or something that I'm doing wrong.

**Comment by cadaver** [comment]
OpenGL ES devices will have lower shadow map precision so the shadows will exhibit more self-shadowing artifacts compared to desktop. You will likely need to use higher shadow depth bias values (note that only constant bias works, slope-scaled doesn't exist on GLES).

Do you see shadow artifacts if you run the NinjaSnowWar example on your device?

**Comment by SuperWangKai** [comment]
I see very serious artifacts on iPhone 6. After using higher depth bias value, the flicker is better but the shadow begins to disappear. e.g. the character shadow near the feet will be cut off. And it's very hard to set the just right value and get a satisfied effect. I wonder if there is some bug in the implementation.
