### ISSUE TITLE
Render to texture with FBO

### ISSUE THREAD

**Issue by sabotage3d** [urho3d/Urho3D#597]
I went through the source code of Urho3d but I couldn't find a relevant call to write Framebuffer to texture using glTexImage2D . The only place seems to be here: https://github.com/urho3d/Urho3D/blob/master/Source/Urho3D/Graphics/OpenGL/OGLTexture2D.cpp#L248
Where it doesn't seems to be affecting the render to texture using renderpath.
This is my reference as standard RTT with FBO: https://www.opengl.org/wiki/Framebuffer_Object_Examples

I also couldn't find where are we actually binding the texture to 2d sampler like sDepthBuffer or sDiffMap .

**Comment by cadaver** [comment]
There is no code in Urho that would copy framebuffer content to textures, rather textures are bound to FBO for rendering. Graphics::SetRenderTarget() and Graphics::SetDepthStencil() set a dirty bit, and later, before a draw call, the appropriate FBO is set up in Graphics::CommitFrameBuffer() function. The actual FBO's are hidden from the user to enable the same kind of API as Direct3D.

Binding of texture units to samplers happens in a hardcoded fashion in the GLShaderProgram::Link() function. Either the sampler name must match known texture units, or it has to indicate the texture unit with a number appended to its name, like sMyCustomSampler9 would use texture unit 9. 

Later, binding of textures to units using Graphics::SetTexture() happens all over the place, mostly in the View and Batch classes for 3D rendering.

**Comment by sabotage3d** [comment]
Thanks cadaver, would it be currently possible to use: https://www.khronos.org/registry/gles/extensions/OES/OES_depth_texture.txt 
As I am not sure if this is possible without glTexImage2D call. Would it work if we just add DEPTH_COMPONENT component to the existing workflow in Urho3d ? It would be nice if we can define our storage like GL_RGBA8, GL_RGBA16 and so on.

**Comment by cadaver** [comment]
It already uses it for OpenGL ES shadow mapping.

**Comment by cadaver** [comment]
This is probably something we can also support on desktops, D3D9 though only with the "INTZ" depth buffer hack. I remember some AMD cards crapping out with strange artifacts when the depth buffer was being both depth-tested and sampled at the same time (writing to it while sampling it would obviously be an error), so it needs to be used with caution.

**Comment by sabotage3d** [comment]
Is there currently any workaround I have a custom depth shader that is writing the depth to the alpha channel is there a way to pass it as  depthmap texture, maybe using the shadowmap sampler ? At the moment I am passing it to diffuse which is a lot heavier.

**Comment by cadaver** [comment]
Not really. Wait for proper depth texture support in the renderpath. It should not take long or be complex.

**Comment by sabotage3d** [comment]
Thanks a lot let me know if there is any update :)

**Comment by ghidra** [comment]
always like new features, this sounds like it would be helpful. thanks cadaver.

**Comment by cadaver** [comment]
Depth texture support in renderpath has been added. On OpenGL ES the DEPTH_COMPONENT format will be used, as I've never got anything else to work. I'll make no claims of its quality / accuracy. Look at the ForwardHWDepth.xml renderpath for a partial example (it renders the depth, but doesn't sample it.) Note that on GLES samplers like sDepthBuffer fall outside the range of 8 supported texture units, so use your own samplers.

**Comment by sabotage3d** [comment]
Awesome ,I can't wait to try it out. I didn't fully understand is it mapped by default to sDepthBuffer ? If we have to define our own samplers how do we do it ?

**Comment by cadaver** [comment]
There is no default automatic binding of textures that have been rendered. Look at the deferred renderpaths and read the documentation on shaders. You can define own samplers, if necessary.

**Comment by sabotage3d** [comment]
Thanks, just to double check if I am doing it correctly.
```
<renderpath>
<rendertarget name="depth" sizedivisor="1 1" format="readabledepth" />
<command type="clear" depth="1.0" output="depth" />
<command type="scenepass" pass="shadow" output="depth" />
<command type="clear" color="fog" depthstencil="depth" />
<command type="scenepass" pass="base" vertexlights="true" metadata="base" depthstencil="depth" />
<command type="forwardlights" pass="light" depthstencil="depth" />
<command type="scenepass" pass="postopaque" depthstencil="depth" />
<command type="scenepass" pass="refract" depthstencil="depth">
	<texture unit="environment" name="viewport" />
</command>
<command type="scenepass" pass="alpha" vertexlights="true" sort="backtofront" metadata="alpha" depthstencil="depth" />
<command type="scenepass" pass="postalpha" sort="backtofront" depthstencil="depth" />
<command type="quad" tag="depth_copy" vs="process" ps="process" output="viewport">
	<texture unit="diffuse" name="depth" />
</command>
</renderpath>
```

And then I am calling it in the shader like this : 

```
float depth = ReconstructDepth(texture2D(sDiffMap, vScreenPos).r);
gl_FragColor = vec4(depth,depth,depth,1);

```

**Comment by cadaver** [comment]
Yes, that looks like it would right for using the readable depth-stencil to render, then bind it to diffuse and reconstruct the linear depth value in shader.
