### ISSUE TITLE
[Editor] Prefabs (objects) auto cloning, then they added to scene from sub dir

### ISSUE THREAD

**Issue by MonkeyFirst** [urho3d/Urho3D#599]
I'm store (some of) my objects by type in subfolder of main prefab folder ( bin\data\objects\ )
but there has some strange bug.
there video about this bug:

http://www.youtube.com/watch?v=b3O4qn6nitI

**Comment by friesencr** [comment]
Well that looks silly :)  I am looking at it.  Thanks for reporting the bug.

**Comment by MonkeyFirst** [comment]
Thanks @friesencr, this is strange little bug but it's a bit confusing me, when i'm trying to locate prefabs on scene )

**Comment by friesencr** [comment]
I found the source of the bug. The issue is that the extra folder level it adds another resource dir.  @cadaver We could add a check to the Editor's add resource path to make sure that the file doesn't exist within an existing resource dir.

**Comment by cadaver** [comment]
Yes that is a nice solution. However I'm now questioning why it is even adding the resource path in the first place, because the scene is likely not going to work when reloaded if it depends on an additional resource path somewhere else on the file system. Probably what it really should do, would be to copy the resources used by the prefab, if imported from outside.

**Comment by friesencr** [comment]
There would still be assumptions made like what resource dir to copy to and that the resources from the node where in the same resource.  If the node isn't in an available resource path then I would think it ok to fail the load node and leave it to the user to make sure it is in the scene path or a resource dir.

**Comment by cadaver** [comment]
You're right. There's probably a point where doing too much automatically is evil, and rather let the user manage the resources properly, as that's needed for running the project anyway.
