### ISSUE TITLE
can't build on windows 7

### ISSUE THREAD

**Issue by ijsonlin** [urho3d/Urho3D#602]
Hi, 
    I can't run the cmake_vs2013.bat on windows 7, the errors are below:
    
![qq 20150111112905](https://cloud.githubusercontent.com/assets/7456629/5694231/16d8a93a-9985-11e4-90a3-bd9c84f2b34b.jpg)

The cmake version is 3.0.0

**Comment by MonkeyFirst** [comment]
i'm use cmake-gui 3.1.0 and it works fine
