### ISSUE TITLE
Consider namespace in scripting?

### ISSUE THREAD

**Issue by xpol** [urho3d/Urho3D#605]
Currently Urho3D Lua scripting API (classes constants) are globals ( `_G` members).

eg.

```Lua
function myfunction()
    scene = Scene() -- Scene is a global and luacheck can't handle this as know global.
   -- ...
end
```
That is, IMHO, not a good idea.

I think it is better to have all api in a table, maybe `urho3d` or `urho`.
And even submodules are better like `urho3d.io`, `urho3d.math` etc.

eg.

```Lua
local Scene = urho3d.Scene
local function myfunction()
    local scene = Scene()
    -- ...
end
```

**Comment by xpol** [comment]
I'm working on this [here](/xpol/Urho3D/commit/9f65341d306141a53efc99a3d93cc5fb2f8f67fb)

Currently pkg files are done.

Next step, update the example in Bin/Data/LuaScripts.

**Comment by aster2013** [comment]
Keep it simple and same as Anglescript.
