### ISSUE TITLE
Provide Lua and tolua headers in SDK installation

### ISSUE THREAD

**Issue by JTippetts** [urho3d/Urho3D#610]
I'm reconfiguring some projects to work with the new build installation, and in the process have found opportunity to try to clarify how I find include paths. So far, I've been hard-wiring include paths for lua.h and tolua++.h, but I was wondering if we should make those more readily available. I noticed that when doing a make install, the install script will copy some ThirdParty includes such as AngelScript, the physics libs and SDL. I think that in order to facilitate extension through Lua bindings, it might be a good idea to copy Lua headers as well.

**Comment by weitjong** [comment]
We only install the header files of the "exposed" third party libraries. It makes sense to include Lua/LuaJIT and tolua++ into this category.
