### ISSUE TITLE
ResourcePrefixPath requires trailing slash.

### ISSUE THREAD

**Issue by spongebob** [urho3d/Urho3D#612]
By changing line 205 in Engine.cpp from
    String resourcePrefixPath = GetParameter(parameters, "ResourcePrefixPath", defaultPrefixPath).GetString();

to
    String resourcePrefixPath = AddTrailingSlash(GetParameter(parameters, "ResourcePrefixPath", defaultPrefixPath).GetString());

Does this make sense? May be a non-issue, but it bothered me for almost 30 minutes when I wasn't able to set the prefix path. Finally I gave up and checked the sources. This is bread and butter code, should the user really have to worry about a trailing slash or not when it's so easy for the API to do it in a portable way?

**Comment by spongebob** [comment]
Actually, I'll comment myself. :) Using something like PhysicsFS I always clean up the paths real good, remove double slashes, back-and-forth-referencing (../a../a/.. is the same as ..) and so on before I use them, just as a service to users. Also, all returned paths from any functions are nice and clean like that.

**Comment by spongebob** [comment]
I'll comment myself again. Realized now that you need to check that the specified path is INDEED a directory before you decide to add the trailing slash. Also available in FileSystem. :)

**Comment by weitjong** [comment]
A good catch.

**Comment by cadaver** [comment]
Already committed a fix which adds the trailing slash similarly when reading from the environment. In which case should the slash not be added? (considering you're concatenating another path to it)

**Comment by weitjong** [comment]
Thanks, Lasse. You are fast, as always.

**Comment by spongebob** [comment]
The only time you don't want a trailing path is if you're trying to add a package file, but that case is easily covered with checking for dir or file on that path.

**Comment by spongebob** [comment]
Also great work on that speed for patch. :) No wonder this engine is so amazing.

**Comment by cadaver** [comment]
Thanks for clarifying. I believe the prefix path is not intended to hold a full path + file name alone, because that would imply one would have to supply an empty string in the ResourcePaths variable.
