### ISSUE TITLE
(feature request) pls add reading CommandLine.txt for all platforms

### ISSUE THREAD

**Issue by v0van1981** [urho3d/Urho3D#615]
pls add reading CommandLine.txt for all platforms (not only android and ios) if Urho3DPlayer.exe do not have parameters

**Comment by cadaver** [comment]
The side-effect of this would be to always start NinjaSnowWar instead of telling how Urho3DPlayer should be used, unless the CommandLine.txt is named differently on desktops.

Is this for deploying a game without having to run a shell script that contains the Urho3DPlayer arguments?

**Comment by v0van1981** [comment]
But for android Urho3DPlayer always start NinjaSnowWar and this is not problem :) We can run another script by default, which will show information.
