### ISSUE TITLE
GraphicsDefs.h needs URHO3D_API for external symbols.

### ISSUE THREAD

**Issue by spongebob** [urho3d/Urho3D#621]
Since -fvisibility=hidden is in effect, all the StringHash symbols requires explicit visibility.

EDIT: adding __attribute__((visibility("default"))) did not help for me. I'm not sure why symbols are still hidden.

EDIT2 and patching:
1. Put URHO3D_API for every extern you want public.
2. #include "GraphicsDefs.h"  was missing from GraphicsDefs.cpp, it must be added or the symbols won't be properly declared at object build time.

**Comment by cadaver** [comment]
Problem reproduced also on MSVC when on a shared library build.
