### ISSUE TITLE
(feature request) Option to build both shared and static with samples dynamically linked.

### ISSUE THREAD

**Issue by spongebob** [urho3d/Urho3D#622]
Proposal, a default value for URHO3D_LIB_TYPE set to SHARED, other options are STATIC or BOTH. When chosing BOTH, the project acts as if SHARED, but the make still spits out the static lib too. (samples are dynamically linked, but libUrho3D.a is still generated)
Very convenient to have support for both types of linking on the same system and in the same build.

Now, if I want both I'll build Urho3D twice with SHARED last so the dynamically linked and significantly smaller binaries overwrite the previous ~1.7G of sample binaries.

**Comment by weitjong** [comment]
Good idea but it is impossible to configure so in one build with CMake, at least according to my understanding of what CMake can do. So, if you know how to, please send the changes in as PR.

**Comment by spongebob** [comment]
If it was impossible with cmake then nobody would use it. It is ALMOST as capable as writing a pure Makefile, it certainly can allow you to pick what targets you want to build. 

Excerpt from one of my cmake setups:

# Build either shared, static or both.
option(BUILD_SHARED "Build shared libraries" ON)
option(BUILD_STATIC "Build static libraries" ON)

# Make sure that at least one target is run.
if (NOT BUILD_STATIC)
  set(BUILD_SHARED ON)
endif ()

# The rest is self-explanatory.

if (BUILD_SHARED)
  include_directories(BEFORE "${SOURCE_DIR}" "${CMAKE_CURRENT_BINARY_DIR}/${BUILD_OUTPUT_DIR}/include")
  add_library(vision SHARED ${LIBRARY_SOURCES})
  set_target_properties(vision PROPERTIES VERSION ${VISION_VERSION_STRING} SOVERSION ${VISION_VERSION_MAJOR} COMPILE_FLAGS "${CMAKE_C_FLAGS} -DVISION_SHARED")
  install(TARGETS vision DESTINATION ${INSTALL_DESTINATION_LIB})
endif (BUILD_SHARED)

if (BUILD_STATIC)
  include_directories(BEFORE "${SOURCE_DIR}" "${CMAKE_CURRENT_BINARY_DIR}/${BUILD_OUTPUT_DIR}/include")
  add_library(vision_static STATIC ${LIBRARY_SOURCES})
  set_target_properties(vision_static PROPERTIES VERSION ${VISION_VERSION_STRING} COMPILE_FLAGS "${CMAKE_C_FLAGS} -DVISION_STATIC" OUTPUT_NAME "vision")
  install(TARGETS vision_static DESTINATION ${INSTALL_DESTINATION_LIB})
endif (BUILD_STATIC)

**Comment by weitjong** [comment]
If you can do it then by all means, DO IT!

**Comment by spongebob** [comment]
I don't know about all the 3rd party libraries, but I do know SDL allows this using autoconf, I'd be hard pressed to see why they wouldn't allow it with cmake. I'd have to research the other components.

From SDL's CMakeLists.txt:
  254:  set(SDL_SHARED ON CACHE BOOL "Build a shared version of the library")
  255:  set(SDL_STATIC ON CACHE BOOL "Build a static version of the library")

It's not a coincidence that it looks similar to what I used in my projects. It is a common practice to write any toolchain for libraries in this way, at least in the unix world, regardless of using cmake or autoconf. SDL also sets it's own flags, including -fPIC if need be, setting flags is a non-issue anyway, that's sort of the biggest job of any build tool, including cmake. It handles it very well.

As far as "DO IT" (with capital letters), overhauling a toolchain is time consuming, I'm not eager to spend time on issues with an advesarial aproach. I only responded to ongoing threads as a courtesy, but I already zoned out. You can just lock this conversation as well.

**Comment by weitjong** [comment]
Sure thing.
