### ISSUE TITLE
Lua: console.GetCommandInterpreter() would raise error.

### ISSUE THREAD

**Issue by xpol** [urho3d/Urho3D#623]
In Lua `console.GetCommandInterpreter()` would raise error.

Console.pkg:

~~~~C++
class Console : public Object
{
    //...
    const String& GetCommandInterpreter() const;
   //...
}
~~~~

Generates:

~~~~C++
const String tolua_ret = (const String)  self->GetCommandInterpreter();
~~~~

Where assign to an `const String` would raise `Segmentation fault: 11` (on Mac OS X).

**Comment by aster2013** [comment]
Please use console:GetCommandInterpreter().

**Comment by xpol** [comment]
yes，i did use “：”。just typo here。
