### ISSUE TITLE
[Editor] Shortcut numpad 1,3,7 change camera view from active selected object to scene origin(0,0,0)

### ISSUE THREAD

**Issue by MonkeyFirst** [urho3d/Urho3D#625]
And it is possible to do so that the focus has always been on the selected objects or the midpoint if a group objects is selected ?

**Comment by friesencr** [comment]
sounds reasonable

**Comment by friesencr** [comment]
Should be done.  Give it a try and let me know if there is anything wrong with it.  

P.S.  Your robot dude is pretty cool.  Good luck with your gamedev :metal:

**Comment by MonkeyFirst** [comment]
Thanks @friesencr ! 
it's works perfect now.

p.s. Thank @friesencr, I like cartoon and handpaint style modeling and painting ) non-photo-realicstic.
