### ISSUE TITLE
[Editor] In ortho view the object's Manipulator is very thin, and it's very hard to select by mouse.

### ISSUE THREAD

**Issue by MonkeyFirst** [urho3d/Urho3D#626]
![clipboard01](https://cloud.githubusercontent.com/assets/9577466/5819828/8e39c1d0-a0e2-11e4-9900-3c0ebf4dfb80.png)

Is it possible to make it thicker or better make it actual width not visible and keep it thin.

![123](https://cloud.githubusercontent.com/assets/9577466/5819833/974b2034-a0e2-11e4-9aab-21bd81f5557e.png)

And another problem he is drawn behind other objects can be drawn so that it is always the last and not behind the other debugging objects?

**Comment by cadaver** [comment]
The scale can be fixed. Draw order in relation to other debug geometry is not possible presently, as the gizmo is a scene object (rendered in scene pass) and debug geometry comes after all scene passes.

**Comment by MonkeyFirst** [comment]
Thanks @cadaver for fix.
it's pretty good looks in ortho but in perspective the size of the manipulator has a variable size )
it's looks very huge sometimes)
see this:
http://youtu.be/7c-icED5kDo

**Comment by cadaver** [comment]
Thanks for remark, there was some wrong matrix math and zoom was not used.

**Comment by MonkeyFirst** [comment]
Yes, now it's look better.
