### ISSUE TITLE
Set resource path

### ISSUE THREAD

**Issue by v0van1981** [urho3d/Urho3D#628]
I try move all content from CoreData to Data and recieve 2 problems

1) When i add "-p Data" to CommandLine.txt i recieve error 
![1](https://cloud.githubusercontent.com/assets/9742588/5850390/0432998a-a20e-11e4-96db-d1f827c34900.jpg)

despite the fact that in Urho3DPlayer.cpp
const String commandFileName = filesystem->GetProgramDir() + "Data/CommandLine.txt";

2) When i run Urho3DPlayer.exe -p Data

![1](https://cloud.githubusercontent.com/assets/9742588/5850444/e0d6dfe0-a20e-11e4-82c5-ecf04dbed2e0.jpg)

It seems that "-p" parameter do not work

p.s. we really need two folders for resurces? :)

**Comment by cadaver** [comment]
Can't comment on the rest of the issue yet, but Urho3DPlayer -p Data tries to attempt to run a script called Data, as Urho3DPlayer does its own command line parsing which doesn't understand the -p parameter, but just looks for the first entry without - in the beginning. This actually should be fixed to strictly just use the first argument as a script file name.

CoreData and Data separation exists to keep "low-level" resources you're unlikely to modify at first, in their own directory. In your own projects you're free to configure the resource dirs however you want.

**Comment by cadaver** [comment]
Fairly certain that this isn't a bug. Tested the following:

Copy all of CoreData's contents to Data
Deleted CoreData
Modify commandline.txt to read Scripts/NinjaSnowWar.as -p Data
Run Urho3DPlayer

which worked without errors.

Of course, by default Urho3DPlayer would attempt to add CoreData dir and fail fatally if it doesn't exist, so now all invocations of Urho3DPlayer (whether through command line or CommandLine.txt) must include -p Data after the script name.
