### ISSUE TITLE
Urho3DAll.h and/or Urho3D/<Submodule>/All.h headers for convenience

### ISSUE THREAD

**Issue by Stinkfist0** [urho3d/Urho3D#629]
Aforementioned header files would be handy, especially for PCH.

**Comment by weitjong** [comment]
What is the difference in adding more stuffs into the already existing
"Urho3D.h" than creating yet another header file that user needs to include
again in their code?

Best regards,
YaoWT

**Comment by cadaver** [comment]
In my experience it's rare that you are going to be using eg. all (or even most) of Graphics in a single .cpp file. Whether it's beneficial from a PCH standpoint would need measurements.

At least for building the Urho library itself IMO nothing should be added to the current Urho3D.h, which just lists the vital defines for export/import/deprecation.

**Comment by weitjong** [comment]
What I wanted to say in my last comment was actually that I am not in favor of having yet another header file, be it being called as "Urho3DAll.h" or "Urho3D_fwd.hpp" or whatever. But this is just my humble opinion.

> At least for building the Urho library itself IMO nothing should be added to the current Urho3D.h, which just lists the vital defines for export/import/deprecation.

Good point.

**Comment by Stinkfist0** [comment]
Was mainly thinking these headers for users of Urho, and agree that Urho itself doesn't need these internally. These files could be maybe automatically generated during Urho deployment, if the feature request is accepted and implemented.

**Comment by v0van1981** [comment]
This is very useful feature, at the moment i use script (C#)

http://paste.ofcode.org/BZHxd2K9cahvPnuYH4DkxS

>> Compiling:
>> csc /target:exe /out:Program.exe *.cs
