### ISSUE TITLE
LuaScripts samples missing #21, #22, #29, and #34 from bin/Data/LuaScripts

### ISSUE THREAD

**Issue by devrich78** [urho3d/Urho3D#630]
Why are these scripts missing? I partially ask because a week ago or so one of them was referenced on the forums which is how I found out that they are missing

**Comment by cadaver** [comment]
21 is C++ integration with AngelScript
22 is C++ integration with Lua
29 is realtime soundsynthesis that implements a C++ class that feeds audio data
34 is dynamic geometry manipulation using raw vertex buffer access in C++

In other words, those samples can not be implemented with bare lua.
