### ISSUE TITLE
Using TileMap2D::PositionToTileIndex()

### ISSUE THREAD

**Issue by Mike3D** [urho3d/Urho3D#631]
I've modified line 97 of TileMapDefs2D.cpp to get accurate result from TileMap2D::PositionToTileIndex():
```c++
            y = (x_add_y - x_sub_y) / 2;
```
(may also need rounding)

Now, PositionToTileIndex() returns a boolean, so how can I access x and y using this function in script (AngelScript and lua)?

**Comment by aster2013** [comment]
in lua it will return 3 values for result,x,y.

**Comment by Mike3D** [comment]
It works fine with AngelScript, but not with lua.
I'm doing:
```lua
local x, y
tileMap:PositionToTileIndex(position, x, y)
print(x, y)
```

**Comment by aster2013** [comment]
USE:
```
success, x, y = tileMap:PositionToTileIndex(position)
```

**Comment by Mike3D** [comment]
Many thanks Aster, works perfectly :clap:
