### ISSUE TITLE
MessageBox in lua

### ISSUE THREAD

**Issue by CaptainCN** [urho3d/Urho3D#634]
I'm doing:
![image](https://cloud.githubusercontent.com/assets/6292878/5885921/f8837860-a3b7-11e4-9858-e45c0882163c.png)

when I press ok,got this

![image](https://cloud.githubusercontent.com/assets/6292878/5885924/1baffad4-a3b8-11e4-8dba-f519221d0fab.png)

**Comment by weitjong** [comment]
This has been discussed [here](http://urho3d.prophpbb.com/topic406.html). I think you need to the same on Lua too. Call AddRef() before the local var goes out of scope.

Contribution is welcome to make this class easier to use in other context besides AngelScript.

**Comment by CaptainCN** [comment]
there is no AddRef in lua.

**Comment by weitjong** [comment]
Then you are out of luck, I am afraid. The implementation of the MessageBox
class need to be fixed first in this case.

Best regards,
YaoWT

**Comment by Mike3D** [comment]
Seems there is a typo, try:
```lua
local msg = MessageBox:new("Hello")
```

**Comment by cadaver** [comment]
This can be "fixed" by adding AddRef() in tolua_UILuaAPI_MessageBox_new00 in MessageBox.pkg. But this will result in a memory leak when the engine is closed without dismissing the message box first.

**Comment by aster2013** [comment]
I will rethink the lua binding of refcounted object when I finish my python work.
