### ISSUE TITLE
Drawable2D visibility check

### ISSUE THREAD

**Issue by Mike3D** [urho3d/Urho3D#636]
I'd like to check visibility of 2D drawables (AnimatedSprite2D and StaticSprite2D) to limit the udpate calls when drawables are not visible.
As Drawable2D derives from Drawable, IsInView() should work for 2D either, but it always returns false (I've tried in C++, AS and lua).
Renderer2D class has a CheckVisibility() method and Drawable2D has a visibility_ variable that is not used.

**Comment by cadaver** [comment]
Drawable2D's are not marked in view similarly as ordinary drawables, due to going through Renderer2D. Should be fixable.

**Comment by Mike3D** [comment]
A big thank for this fix Cadaver :+1:
Maybe something is missing in the pushed commit, it fails to compile and this is confirmed by Travis.

**Comment by cadaver** [comment]
There were errors which were detectable at least on MinGW. Travis history seemed to be hanging so couldn't inspect the failed build logs.

**Comment by Mike3D** [comment]
Many thanks for quick fix.
Unfortunately I still can't get it to work, maybe I'm missing something.
For example, if I add these lines in the update function of sample 33_Urho2DSpriterAnimation, IsInView() always returns false:
```c++
    AnimatedSprite2D* sprite = spriteNode_->GetComponent<AnimatedSprite2D>();
    LOGINFO(String(sprite->IsInView()));
    Camera* camera = cameraNode_->GetComponent<Camera>();
    LOGINFO(String(sprite->IsInView(camera)));
```

**Comment by cadaver** [comment]
AnimatedSprite is a tricky component, because it instantiates internal StaticSprite components in child nodes, and those actually render stuff. So you'd really have to check visibility from them instead of the AnimatedSprite.
