### ISSUE TITLE
Enable precompiled header for GCC and Clang

### ISSUE THREAD

**Issue by weitjong** [urho3d/Urho3D#637]
Currently the ```enable_pch()``` macro does not actually handle the precompiled header for GCC and Clang correctly.

**Comment by weitjong** [comment]
The ```enable-pch``` branch is ready to be merged. The revised enable_pch() macro can be used by library users on their own project too. Please let me know if there is any concerns.

**Comment by weitjong** [comment]
I have a question. In the current implementation for GCC and Clang, the rule for precompiling the header file is only triggered when the PCH does not exists yet or when its timestamp is older than its dependency files. The dependency files are: the corresponding *.pch.rsp file (containing the compiler flags) and the header file itself. This works well when any of the build options has invalidated the compiler flags and prompted the *.pch.rsp file to be recreated with newer timestamp. It also works when user adds/removes include statement in the header file. However, it won't work when the included header files in the include statements themselves have changed. I don't want to parse the original header file manually just to add the other included header files as dependencies. What to do?

**Comment by weitjong** [comment]
I think I have cracked the problem. The dependency list is now derived from the actual compiler's preprocessor output. The branch is ready for testing and merging.

**Comment by MonkeyFirst** [comment]
Yes, i'am already tested this branch-pch, the engine compiles - fine.
and new project from scratch also compiled without any errors.
(all tested on visual studio 2013 + cmake-gui )

**Comment by weitjong** [comment]
Thanks for testing it on MSVC. Although as the subject of the this issue implied, the changes mainly will benefit GCC and Clang users. Nevertheless, your test shows there is no regression issue on MSVC.
