### ISSUE TITLE
Precompiled header error with Rigidbody.h and PhysicsWorld.h

### ISSUE THREAD

**Issue by MonkeyFirst** [urho3d/Urho3D#640]
i'm create a new project from scratch and then i'am include Rigidbody.h or PhysicsWorld.h in my precompiled header i got an error. Only this files (if they added) produce compilation error.

example:
http://www.youtube.com/watch?v=_aA9KNoQrcY

**Comment by weitjong** [comment]
I am not able to reproduce your problem. Are you using the new enable_pch() macro in the new ```enable-pch``` topic branch? If not, then you have to ensure that you have configured the include search paths correctly in your own project. From the error, it looks like you have not added ```include/Urho3D/ThirdParty/ThirdParty/Bullet``` into the search paths.

**Comment by weitjong** [comment]
Ops. It looks like I am speaking too soon :). Thanks for reporting. You have found a bug indeed.

**Comment by MonkeyFirst** [comment]
i'm still have an same bug. and only with Rigidbody.h and PhysicsWorld.h, then  they included to my precompiled header. i don't know how to solve this.  

maim ,,, http://pastebin.com/QznunZhF
precompiled .... http://pastebin.com/dLaprzvh

**Comment by MonkeyFirst** [comment]
Oh, i'm trying to change place of physics group (include's) from middle of my header to the head of header and it's now compiles. wt..??? )

how to looks precompiled now: http://pastebin.com/rMyXnp37

**Comment by weitjong** [comment]
The order is important. Take the extreme case, Urho3D.h, for example. It will only work when it is the first being included.

Glad to hear you have a working PCH now. Personally, however, I don't do what you have done to that extreme.

**Comment by MonkeyFirst** [comment]
ok, thank's for reply.
now i'm also going to use forward declaration in my fh test game
i'm rewrite precompiled at all. (sort they by category)
and split some my old header to few others.
