### ISSUE TITLE
Segfault when using ui::Clear() with engine::RunFrame()

### ISSUE THREAD

**Issue by Mike3D** [urho3d/Urho3D#642]
Simple lua script to replicate:
```lua
function Start()
	CreateButton()
	input.mouseVisible = true
end

function CreateButton()
    local button = ui.root:CreateChild("Button")
    button:SetSize(200, 100)
    button:SetAlignment(HA_CENTER, VA_CENTER)
    SubscribeToEvent(button, "Released", "Reload")
end

function Reload(eventType, eventData)
	UnsubscribeFromAllEvents()
	ui:Clear()
	engine:RunFrame()
	CreateButton()
end
```

Note that:
- it may take more than one single click on the button to reproduce the crash (3 clicks should be enough)
- this piece of code worked fine a few months ago.

**Comment by cadaver** [comment]
I believe this can be fixed, but in general you're asking for hurt by running the whole engine frame (re-entering all frame processing) from within a UI event handler. It'd be safer to set a flag in response and call RunFrame() for example within an Update event. 

Can't imagine eg. Unity allowing you to recurse into the engine frame loop from a script; we exposed this to allow things like loading screens easily, but it comes with a risk.
