### ISSUE TITLE
Code::Blocks 13.12 for Windows

### ISSUE THREAD

**Issue by Vytek** [urho3d/Urho3D#644]
Please add cmake bat commad for Code::Blocks 13.12 for Windows

**Comment by Vytek** [comment]
There is some problem in the build?

C:\urho3d\Urho3D>dir

 Directory di C:\urho3d\Urho3D

03/02/2015  11.43    <DIR>          .
03/02/2015  11.43    <DIR>          ..
03/02/2015  11.42             7.141 .bash_helpers.sh
03/02/2015  11.42             1.153 .gitignore
03/02/2015  11.42             4.975 .travis.yml
03/02/2015  11.42    <DIR>          Android
03/02/2015  11.43    <DIR>          bin
03/02/2015  11.42    <DIR>          CMake
03/02/2015  11.42             8.305 CMakeLists.txt
03/02/2015  11.43             1.192 cmake_android.bat
03/02/2015  11.43             1.232 cmake_android.sh
03/02/2015  11.43             1.681 cmake_clean.bat
03/02/2015  11.43             1.582 cmake_clean.sh
03/02/2015  11.43             1.214 cmake_codeblocks.bat
03/02/2015  11.43             1.253 cmake_codeblocks.sh
03/02/2015  11.43             1.522 cmake_eclipse.sh
03/02/2015  11.43             2.791 cmake_generic.bat
03/02/2015  11.43             2.919 cmake_generic.sh
03/02/2015  11.43             1.227 cmake_ios.sh
03/02/2015  11.43             1.229 cmake_macosx.sh
03/02/2015  11.43             1.201 cmake_mingw.bat
03/02/2015  11.43             1.230 cmake_mingw.sh
03/02/2015  11.43             1.228 cmake_rpi.sh
03/02/2015  11.43             1.193 cmake_vs2008.bat
03/02/2015  11.43             1.187 cmake_vs2010.bat
03/02/2015  11.43             1.187 cmake_vs2012.bat
03/02/2015  11.43             1.187 cmake_vs2013.bat
03/02/2015  11.42    <DIR>          Docs
03/02/2015  11.42            26.911 License.txt
03/02/2015  11.42            38.218 Rakefile
03/02/2015  11.42            23.951 Readme.txt
03/02/2015  11.42    <DIR>          Source
03/02/2015  11.42    <DIR>          SourceAssets
              25 File        136.909 byte
               8 Directory  538.339.291.136 byte disponibili

C:\urho3d\Urho3D>cmake_codeblocks.bat
An error has occured, build tree has to be provided as the first argument OR call this scri
pt in a build tree itself

C:\urho3d\Urho3D>cmake -version
cmake version 3.1.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).

C:\urho3d\Urho3D>

**Comment by weitjong** [comment]
You have to provide a path to the new build tree location as the first argument.

**Comment by Vytek** [comment]
Thank you very much!

But there is another problem:

C:\urho3d\Urho3D>cmake_codeblocks.bat c:\urho3d\Urho3D\ -URHO3D_OPENGL
-- Building SDL without DX joystick support due to missing wbemcli.h
-- For MSVC, get it from Windows 7 SDK. For MinGW, get it from eg. Wine sources or from Min
GW-w64
g++.exe: error: unrecognized command line option '-static-libstdc++'
CMake Error at CMake/Modules/Urho3D-CMake-common.cmake:538 (file):
  file STRINGS file
  "C:/urho3d/Urho3D/Source/Urho3D/Precompiled.h.Release.pch.deps" cannot be
  read.
Call Stack (most recent call first):
  CMake/Modules/Urho3D-CMake-common.cmake:584 (enable_pch)
  CMake/Modules/Urho3D-CMake-common.cmake:623 (setup_target)
  Source/Urho3D/CMakeLists.txt:163 (setup_library)


CMake Error at CMake/Modules/Urho3D-CMake-common.cmake:539 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.
Call Stack (most recent call first):
  CMake/Modules/Urho3D-CMake-common.cmake:584 (enable_pch)
  CMake/Modules/Urho3D-CMake-common.cmake:623 (setup_target)
  Source/Urho3D/CMakeLists.txt:163 (setup_library)


g++.exe: error: unrecognized command line option '-static-libstdc++'
CMake Error at CMake/Modules/Urho3D-CMake-common.cmake:538 (file):
  file STRINGS file
  "C:/urho3d/Urho3D/Source/ThirdParty/Assimp/AssimpPCH.h.Release.pch.deps"
  cannot be read.
Call Stack (most recent call first):
  CMake/Modules/Urho3D-CMake-common.cmake:584 (enable_pch)
  CMake/Modules/Urho3D-CMake-common.cmake:623 (setup_target)
  Source/ThirdParty/Assimp/CMakeLists.txt:724 (setup_library)


CMake Error at CMake/Modules/Urho3D-CMake-common.cmake:539 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.
Call Stack (most recent call first):
  CMake/Modules/Urho3D-CMake-common.cmake:584 (enable_pch)
  CMake/Modules/Urho3D-CMake-common.cmake:623 (setup_target)
  Source/ThirdParty/Assimp/CMakeLists.txt:724 (setup_library)


-- Configuring incomplete, errors occurred!
See also "C:/urho3d/Urho3D/CMakeFiles/CMakeOutput.log".
See also "C:/urho3d/Urho3D/CMakeFiles/CMakeError.log".

**Comment by cadaver** [comment]
I have been getting the REGEX error also on OS X when running cmake_macosx.sh. In my case running cmake_generic.sh instead fixed it, though generating a makefile project instead of Xcode.

**Comment by hdunderscore** [comment]
Well just FYI, I solved a similar smelling issue for windows in the emscripten branch by specifying the extension for the compilers.

**Comment by weitjong** [comment]
I don't think they are all same issue, although I could be wrong.

@Vytek Are you using MinGW-W64?
@cadaver What OS X version and Xcode are you using? I have returned the Mac with 10.10 SDK back. At the moment I can only use VM with OS X 10.8 and Xcode 5, and build went fine as I just tested it.
@hdunderscore MinGW/CMake toolchain file should not get the same issue with Emscripten/CMake toolchain file. This is because only Emscripten compiler toolchain uses python wrapper scripts. All other toolchains are dealing with genuine binaries.

**Comment by cadaver** [comment]
I'm using OSX 10.9.5 with Xcode 6. CMake is 3.1.0; was about to upgrade to 3.1.1 but didn't have time yet.

**Comment by Vytek** [comment]
I am using MinGW-W32 that codeblock 13.12 use in path:

C:\Program Files (x86)\CodeBlocks\MinGW\bin
Windows version:
Microsoft Windows [Versione 6.3.9600]
Windows 8.1 64Bit

**Comment by weitjong** [comment]
This has discussed in the forum before. See http://urho3d.prophpbb.com/topic595.html. You cannot use TDM-GCC that shipped by Code::Blocks to build Urho3D.

**Comment by Vytek** [comment]
Thank you very much...I would like to write a little guide for your wiki.
