### ISSUE TITLE
Networking breaks on non-windows non-debug mode

### ISSUE THREAD

**Issue by grumblygibson** [urho3d/Urho3D#645]
The network demo breaks within a few seconds for me. Always works on windows, and never works for me on other systems when not compiled in debug mode. Debug mode fixes the issue. I've tried both on localhost server/client configuration and actual two computers configuration.

Observed on:

Linux
version: Sabayon (gentoo-based, vanilla install)
compiler: g++ (Gentoo Hardened 4.8.3 p1.1, pie-0.5.9) 4.8.3
kernel: 3.17.0-sabayon
processor: x86_64 AMD Phenom(tm) II X4 920 Processor

Mac OSX
version: 10.9.5
compiler: Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
kernel: 13.4.0
processor: Intel core i7 x86_64

I would attach log outputs, but they're different every time where and how it breaks, which makes me think is a memory issue, or a variant of that such as a threading issue. I seem to be the only one in the forums who can replicate this issue so please ping me if you have any hints how I can debug this.

Form post: http://urho3d.prophpbb.com/topic652.html

**Comment by cadaver** [comment]
Realistically it looks like you'll have to debug inside kNet to find where it goes wrong, as it'll be extremely hard to debug a bug we can't reproduce. I would suspect either threading, over-eager optimizations by compiler, or memory initialization values. However I recently updated Xcode on OSX so I'll test that next week.

You can also try cloning the kNet repo (https://github.com/juj/kNet), running the example programs in UDP mode and see if you run into similar issues.

**Comment by cadaver** [comment]
I believe I was able to reproduce this on OSX.

**Comment by cadaver** [comment]
Seems that one rather crude fix is to set -O0 compiler flags for kNet.
