### ISSUE TITLE
DropDownList::SetResizePopup() wrong behaviour

### ISSUE THREAD

**Issue by LonelyBitsGames** [urho3d/Urho3D#646]
DropDownList::SetResizePopup(bool enable) function is not working correctly. it's behavior is inverted. 

When true is set the popup is not re-sized and when false is set the popup is re-sized according to it's content.

**Comment by cadaver** [comment]
The meaning of the parameter is "resize popup to button width" so it's working as expected: when true, the popup is resized to match button width. When false, it's using the content width.
