### ISSUE TITLE
Lua: Objects not being garbage collected.

### ISSUE THREAD

**Issue by JTippetts** [urho3d/Urho3D#649]
I believe there may be a problem with the way Lua and tolua collect garbage from locally created objects and objects that are returned as values from C++ calls.

I have pasted here a small example: http://pastebin.com/bd8f1M6G]. The sample uses the Lua sample framework and sets up a very simple scene. It displays the currently used memory as reported by collectgarbage("count"). If you execute the script, you are given the option to press 'd' to run the function:

[code]
function DoThing()
    local c
    for c=1,10000000,1 do
        local c=Color(1,1,1,1)
    end
end
[/code]

All it does is loop a large number of times and create a local Color object. (It's not just Color objects that exhibit the problem; pretty much any object type will do.) The loop will execute, then the update function will update the on-screen text with the amount of memory currently being used. Update also includes an explicit call to collectgarbage() to execute a full collection cycle.

Here is a screenshot from before 'd' is pressed: http://i.imgur.com/nMaE6fZ.png

Here is a screenshot from after: http://i.imgur.com/xxNeZm0.png

As you can see, even with the collectgarbage() call, there is still a LOT of memory used, memory that should be freed up by a garbage collection cycle because it was all allocated as temporary locals inside the DoThing loop. Note also the drastic framerate drop. This drop is permanent, as is the memory hogging. Leaving the window to run for several minutes results in zero change.

I noticed this behavior with a game project that I have since semi-abandoned due to performance issues. As time went by the framerate would drop to unworkable levels. Revisiting the project and logging reported memory use showed that garbage was accruing and never being cleaned up, resulting in a progressive performance loss.

Edit: The behavior occurs in builds using both Lua and LuaJIT.

**Comment by cadaver** [comment]
According to another experiment I made, where I'd generate a large number of objects each frame, the objects (Color etc.) themselves do get collected, but this still leaves the collector table permanently large, incurring memory use and performance loss on each frame after that, as what probably happens is the GC will walk through a large empty table.

**Comment by JTippetts** [comment]
I think that is it exactly. Re-writing my fractal filter to add a gc call in the outer loop solves the issue. Can probably close this; without digging into tolua's guts, there's no real fix except to avoid allocating huge chunks of objects at a time without interleaved gc calls.
