### ISSUE TITLE
Travis-CI: The dreaded process being killed during CI build

### ISSUE THREAD

**Issue by weitjong** [urho3d/Urho3D#651]
It is a known problem (See #430 and #536) that Travis-CI has a serious memory problem in their worker VM snapshots. Some worker snapshots come with a reduced memory to begin with even before CI build starts and some how the memory kept leaking while CI build is in progress. When the free memory is almost completely used up, to the point that the swap partition cannot help then process would get killed.

We have provided our analysis on this problem to upstream but so far there is still no resolution from upstream. We have also enhanced our CI build to be as memory efficient as possible, even with "build rule" to automatically switch build configuration and/or skip processes in the CI build (e.g. make test) when detected a "bad" VM snapshot being used.

However, despite our best effort to mitigate this problem, we have only delayed the inevitable from happening sooner, i.e. not  while our CI build still in progress. With more and more samples being included into our repository, the situation is becoming more difficult and we start to see the process being killed problem back again toward the end of our CI builds lately. Mostly while attempting to upload the build artifacts or to update the main website. Since those are not considered critical processes in our CI build, the overall build status remains green. But sooner or later the process getting killed will be from one of our critical processes when Urho3D code base keeps growing.

Proposed solution:
- Evaluate to switch to other CI solutions, like Jenkins.
- Stay on Travis CI but evaluate to switch to use Docker (http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/). The only caveat is, the Docker-container build infrastructure does not allow to use "sudo" command and currently our CI builds use this command in a few places.

We should all keep an eye on the number of samples in the project until the problem is fully resolved. Combining a few easier or related samples into one, if have to. Thanks for reading this.

**Comment by friesencr** [comment]
looks like most sudo is for updating packages which we would control with a custom container and could skip that all together?

**Comment by weitjong** [comment]
Still no go. Most of platform-specific packages are not in Travis CI whitelist (https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise) yet. Even the ```libasound2-dev``` is not in. Bummer.

**Comment by weitjong** [comment]
The APT whitelist request has been raised to Travis CI. See https://github.com/travis-ci/travis-ci/issues/3522. Now we wait.

**Comment by weitjong** [comment]
I reassigned this to me again now that all the prerequisite packages are whitelisted.

**Comment by friesencr** [comment]
I am curious to see how the container performs.  Looking forward to seeing the results!

**Comment by weitjong** [comment]
It should already in theory perform much better with ccache enabled. ccache is only available for their paying customers previously but now is also made available for container-based build infrastructure for free.

**Comment by weitjong** [comment]
I got careless and did not specify a few deps in my earlier request and so I had to re-request and waited for them. Finally yesterday we got all we need for the migration. In order not to spamming you guys, I have been doing my migration experiment using my own fork. Only those CI jobs on Linux build environment are migrated to the new container-based build infra now. Those CI jobs on OSX build environment (including Emscripten CI build) stay where they are because Travis CI does not have new infra for OSX yet. Emscripten CI build is still a pain caused by emrun intermittent timeout. The old build infra has 1.5 cores (with burst capacity) while new infra has 2 cores (dedicated). It explains why the old infra build much slower during peak hours and I think also the emrun intermittent timeout. On the flip side of the story, the dedicated 2 cores on the new infra actually runs slower for our CI builds out of the box. Probably our CI jobs burst to max capacity all these while (with make -j3) at the expense of others :smile:. With ccache enabled in the new build infra only then we can see the benefit of migrating to it. When the cache is properly configured, it could half the build time in some cases. The main benefit of migrating above all is no more "bad" VM snapshot problem. Finally!

In my experiment in order to minimize cache size (so the cache download/upload from/to S3 does not nullify the ccache benefit) I have to use the same build configuration (always Release mode now) when ccache is enabled. Previously we use Debug for "normal" CI build and only use Release for "packaging" CI build. I have also raised another [issue](https://github.com/travis-ci/travis-ci/issues/3699) to Travis CI upstream. Currently their default cache granularity for ccache is just unusable. I am forced to turn off the ccache for half the CI jobs in the Android build because I am running out of ways to coerce Travis CI to create separate cache for each job. In my experiment it shows it is better this way than to thrash the cache all together by sharing it for multiple jobs. Last but not the least, I have bumped the ```make``` concurrent build jobs to 4 since now the compilation is nothing more than fetching a cached object with a good cache hit/miss ratio, at least with dedicated cores we don't interfere with our neighbours now :smile:.

I will merge the relevant bits from my fork to the main Urho3D repo when I have time. Thanks for reading this again.

**Comment by weitjong** [comment]
It is done. We just have a successful run on the new Travis CI build infra. As mentioned earlier only jobs on Linux build environment (i.e. Linux, MinGW, Android, and RPI-CI) are actually migrated. OSX and Emscripten CI jobs are still on legacy infra. As it is the very first run, the cache is just getting warming up. We shall see the benefit of the cache in the subsequent runs.

One more thing, the cache used by ccache can be deleted on demand by having ```[ccache clear]``` in the commit message. We should only do that when the commit itself is a very major code refactoring (the cache won't be of any help to speed up) or when we suspect something is wrong with the caches. You can use ```travis cache``` CLI to maintain the caches too.

**Comment by weitjong** [comment]
It seems like we have our first successful run for "packaging build". The benefit of having the ccache enabled is definitely shown in the new build infra. The build is faster than legacy infra, however, the upload speed from new build infra to SF.net was less than 500 KB/s. This is a far cry from legacy build which has upload speed beyond 20MB/s. We used to take just seconds to upload the artifacts per build. Now it takes several minutes. To be monitor closely.
