### ISSUE TITLE
Events2D and documentation

### ISSUE THREAD

**Issue by Mike3D** [urho3d/Urho3D#652]
ScriptAPIDump.cpp scans for "Events.h" pattern to generate the 'Event List', so currently "Events2D.h" is skipped.
This can be fixed for example by including "Events2D.h" in the search pattern, or by renaming "Events2D" files to "2DEvents" (currently only PhysicsEvents2D.h is concerned).

Also, in PhysicsEvents2D.h, C++ and script event names are not "in sync" for pre-step event (we have E_PHYSICSPRESTEP2D and Physics2DPreStep2D), maybe we should rename "Physics2DPreStep2D" to "PhysicsPreStep2D".

**Comment by cadaver** [comment]
IMO it makes sense to treat Physics2D as a category of events, so I'd rename these to Physics2DEvents.h and Physics2DPreStep respectively.
