### ISSUE TITLE
IsNaN and GCC

### ISSUE THREAD

**Issue by reattiva** [urho3d/Urho3D#655]
Hello,
I'm using gcc version 4.9.2 (i686-win32-dwarf-rev1, MinGW-W64) and it seems to optimize out the function "bool IsNaN(float value)". In the disassembly there is a "mov $0x0,%eax" and infact it always returns false.
Looking around I've found that it is a common problem with GCC >=4.8.1 with the flag -ffast-math. Using a volatile variable doesn't solve the problem. Just for the record, testing the correct bits like this:
```
bool IsNaN(float value)
{
    unsigned u = *(unsigned*)(&value);
    return (u & 0x7fffffff) > 0x7f800000;
}
```
*seems* to work (and I'm good) but it is not portable at all for Urho.

**Comment by cadaver** [comment]
Actually this looks just as portable as, say, the fast sqrt trick, and Urho3D will only run properly on low-endian platforms where sizeof unsigned and float are equal, so this could well be committed in.

**Comment by rokups** [comment]
I bumped into `IsNaN` recently doing some work. Is there a reason for using a custom solution instead of using [isnan()](http://www.cplusplus.com/reference/cmath/isnan/) from c++ standard?

**Comment by cadaver** [comment]
Now when c++11 is mandatory, it could be used.
