### ISSUE TITLE
[Editor] String attributes not correct when default value is used

### ISSUE THREAD

**Issue by setzer22** [urho3d/Urho3D#662]
To illustrate my issue, assume there's an attribute like: 

ATTRIBUTE("Team", String,  _attr_unitTeam, "ALLY", AM_DEFAULT);

With this set up, typing "ALLY" in the editor to the attribute field, makes it not get saved in the XML (that's intended behaviour AFAIK, to save space), but then when actually parsing that attribute on ApplyAttributes, the value of _attr_unitTeam is not correct and is a blank String instead.

I assume is an issue with the editor.

**Comment by cadaver** [comment]
The default value also needs to be set in the component's constructor. Serializable loading does not work by filling missing attributes with default value, instead it expects them to already have that value.
