### ISSUE TITLE
selection of objects in the editor is uncomfortable

### ISSUE THREAD

**Issue by v0van1981** [urho3d/Urho3D#663]
When many objects in the scene is very uncomfortable to find for them in the list. I thing we need possibility to selection objects by mouse click in scene.

**Comment by cadaver** [comment]
This functionality already exists. The editor menu row contains icons to choose what will be selected by mouse (geometries, lights, physics objects, UI-elements) or you can use Ctrl-6 Ctrl-7 to also toggle the mode. However objects that don't contain any of the selectable components (such as one that only has a script) have to be picked from the list.

**Comment by v0van1981** [comment]
thank you
