### ISSUE TITLE
Android build failed

### ISSUE THREAD

**Issue by guijun** [urho3d/Urho3D#670]
host system:
mac book pro 16G RAM
Mac OSX 10.10
NDK R10d
xcode 6.1.1
steps to repoduce:

ANDROID_STANDALONE_TOOLCHAIN=~/Documents/app.sdk/arm-linux-androideabi-4.9/ ./cmake_android.sh  build_and -DURHO3D_LUAJIT=1 -DURHO3D_64BIT=0
cd build_and
make

......

error msg:
Linking CXX static library libBullet.a
[ 65%] Built target Bullet
[ 65%] [ 65%] [ 65%] [ 65%] [ 65%] [ 65%] Generating GIT revision number (tag + last commit SHA-1)
Precompiling header file 'Precompiled.h' for Release configuration
Generating tolua++ API binding on the fly for Audio
Generating tolua++ API binding on the fly for Urho2D
Generating tolua++ API binding on the fly for Core
Generating tolua++ API binding on the fly for Engine
[ 66%] [ 66%] Generating tolua++ API binding on the fly for Graphics
Generating tolua++ API binding on the fly for Input
/bin/sh: line 1: 25291 Segmentation fault: 11  /Users/kin/Documents/opensource/Urho3D/build_and/bin/tool/tolua++ -L ToCppHook.lua -o /Users/kin/Documents/opensource/Urho3D/build_and/Source/Urho3D/LuaScript/generated/InputLuaAPI.cpp InputLuaAPI.pkg
make[2]: *** [Source/Urho3D/LuaScript/generated/InputLuaAPI.cpp] Error 139
make[2]: *** Waiting for unfinished jobs....
/bin/sh: line 1: 25290 Segmentation fault: 11  /Users/kin/Documents/opensource/Urho3D/build_and/bin/tool/tolua++ -L ToCppHook.lua -o /Users/kin/Documents/opensource/Urho3D/build_and/Source/Urho3D/LuaScript/generated/GraphicsLuaAPI.cpp GraphicsLuaAPI.pkg
make[2]: *** [Source/Urho3D/LuaScript/generated/GraphicsLuaAPI.cpp] Error 139
/bin/sh: line 1: 25280 Segmentation fault: 11  /Users/kin/Documents/opensource/Urho3D/build_and/bin/tool/tolua++ -L ToCppHook.lua -o /Users/kin/Documents/opensource/Urho3D/build_and/Source/Urho3D/LuaScript/generated/Urho2DLuaAPI.cpp Urho2DLuaAPI.pkg
make[2]: *** [Source/Urho3D/LuaScript/generated/Urho2DLuaAPI.cpp] Error 139
/bin/sh: line 1: 25276 Segmentation fault: 11  /Users/kin/Documents/opensource/Urho3D/build_and/bin/tool/tolua++ -L ToCppHook.lua -o /Users/kin/Documents/opensource/Urho3D/build_and/Source/Urho3D/LuaScript/generated/AudioLuaAPI.cpp AudioLuaAPI.pkg
make[2]: *** [Source/Urho3D/LuaScript/generated/AudioLuaAPI.cpp] Error 139
/bin/sh: line 1: 25285 Segmentation fault: 11  /Users/kin/Documents/opensource/Urho3D/build_and/bin/tool/tolua++ -L ToCppHook.lua -o /Users/kin/Documents/opensource/Urho3D/build_and/Source/Urho3D/LuaScript/generated/EngineLuaAPI.cpp EngineLuaAPI.pkg
make[2]: *** [Source/Urho3D/LuaScript/generated/EngineLuaAPI.cpp] Error 139
/bin/sh: line 1: 25282 Segmentation fault: 11  /Users/kin/Documents/opensource/Urho3D/build_and/bin/tool/tolua++ -L ToCppHook.lua -o /Users/kin/Documents/opensource/Urho3D/build_and/Source/Urho3D/LuaScript/generated/CoreLuaAPI.cpp CoreLuaAPI.pkg
make[2]: *** [Source/Urho3D/LuaScript/generated/CoreLuaAPI.cpp] Error 139
make[1]: *** [Source/Urho3D/CMakeFiles/Urho3D.dir/all] Error 2
make: *** [all] Error 2

---------------------------------------------------------
/Users/kin/Documents/opensource/Urho3D/build_and/bin/tool/tolua++ 
Segmentation fault: 11

**Comment by guijun** [comment]
I updated and tried again, I found that the issue is still there,please find outputs and details of Urho3D/build_and/bin/tool below:
make -j8
......
Generating tolua++ API binding on the fly for Audio
Generating tolua++ API binding on the fly for Core
Generating tolua++ API binding on the fly for Engine
Generating tolua++ API binding on the fly for Graphics
Generating tolua++ API binding on the fly for Input
Generating tolua++ API binding on the fly for IO
Generating tolua++ API binding on the fly for LuaScript
/bin/sh: line 1: 19067 Segmentation fault: 11  /Users/kin/Documents/opensource/Urho3D/build_and/bin/tool/tolua++ -L ToCppHook.lua -o /Users/kin/Documents/opensource/Urho3D/build_and/Source/Urho3D/LuaScript/generated/LuaScriptLuaAPI.cpp LuaScriptLuaAPI.pkg
/bin/sh: line 1: 19066 Segmentation fault: 11  /Users/kin/Documents/opensource/Urho3D/build_and/bin/tool/tolua++ -L ToCppHook.lua -o /Users/kin/Documents/opensource/Urho3D/build_and/Source/Urho3D/LuaScript/generated/IOLuaAPI.cpp IOLuaAPI.pkg
/bin/sh: line 1: 19065 Segmentation fault: 11  /Users/kin/Documents/opensource/Urho3D/build_and/bin/tool/tolua++ -L ToCppHook.lua -o /Users/kin/Documents/opensource/Urho3D/build_and/Source/Urho3D/LuaScript/generated/InputLuaAPI.cpp InputLuaAPI.pkg
make[2]: *** [Source/Urho3D/LuaScript/generated/LuaScriptLuaAPI.cpp] Error 139
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [Source/Urho3D/LuaScript/generated/IOLuaAPI.cpp] Error 139
make[2]: *** [Source/Urho3D/LuaScript/generated/InputLuaAPI.cpp] Error 139
/bin/sh: line 1: 19058 Segmentation fault: 11  /Users/kin/Documents/opensource/Urho3D/build_and/bin/tool/tolua++ -L ToCppHook.lua -o /Users/kin/Documents/opensource/Urho3D/build_and/Source/Urho3D/LuaScript/generated/Urho2DLuaAPI.cpp Urho2DLuaAPI.pkg
make[2]: *** [Source/Urho3D/LuaScript/generated/Urho2DLuaAPI.cpp] Error 139
/bin/sh: line 1: 19060 Segmentation fault: 11  /Users/kin/Documents/opensource/Urho3D/build_and/bin/tool/tolua++ -L ToCppHook.lua -o /Users/kin/Documents/opensource/Urho3D/build_and/Source/Urho3D/LuaScript/generated/EngineLuaAPI.cpp EngineLuaAPI.pkg
make[2]: *** [Source/Urho3D/LuaScript/generated/EngineLuaAPI.cpp] Error 139
/bin/sh: line 1: 19063 Segmentation fault: 11  /Users/kin/Documents/opensource/Urho3D/build_and/bin/tool/tolua++ -L ToCppHook.lua -o /Users/kin/Documents/opensource/Urho3D/build_and/Source/Urho3D/LuaScript/generated/GraphicsLuaAPI.cpp GraphicsLuaAPI.pkg
make[2]: *** [Source/Urho3D/LuaScript/generated/GraphicsLuaAPI.cpp] Error 139
/bin/sh: line 1: 19056 Segmentation fault: 11  /Users/kin/Documents/opensource/Urho3D/build_and/bin/tool/tolua++ -L ToCppHook.lua -o /Users/kin/Documents/opensource/Urho3D/build_and/Source/Urho3D/LuaScript/generated/AudioLuaAPI.cpp AudioLuaAPI.pkg
make[2]: *** [Source/Urho3D/LuaScript/generated/AudioLuaAPI.cpp] Error 139
/bin/sh: line 1: 19057 Segmentation fault: 11  /Users/kin/Documents/opensource/Urho3D/build_and/bin/tool/tolua++ -L ToCppHook.lua -o /Users/kin/Documents/opensource/Urho3D/build_and/Source/Urho3D/LuaScript/generated/CoreLuaAPI.cpp CoreLuaAPI.pkg
make[2]: *** [Source/Urho3D/LuaScript/generated/CoreLuaAPI.cpp] Error 139
make[1]: *** [Source/Urho3D/CMakeFiles/Urho3D.dir/all] Error 2
......

AND:
kin$ ls -l /Users/kin/Documents/opensource/Urho3D/build_and/bin/tool
total 3096
-rwxr-xr-x   1 kin  staff   77336  2 25 19:35 buildvm
drwxr-xr-x  13 kin  staff     442  2 25 19:35 jit
-rwxr-xr-x   1 kin  staff  567516  2 25 19:35 luajit
-rwxr-xr-x   1 kin  staff  257620  2 25 19:35 minilua
-rwxr-xr-x   1 kin  staff  679516  2 25 19:35 tolua++

kin$ /Users/kin/Documents/opensource/Urho3D/build_and/bin/tool/luajit 
/Users/kin/Documents/opensource/Urho3D/build_and/bin/tool/luajit: cannot create state: not enough memory
kin$ /Users/kin/Documents/opensource/Urho3D/build_and/bin/tool/tolua++ 
Segmentation fault: 11

**Comment by weitjong** [comment]
I have actually never done Android build on Mac OS X host system before but the fix I just did should solve your problem. Have you tried to do a clean build? Or perhaps could you do a native/desktop build first on Mac OS X host with Lua/LuaJIT enabled. The native build should also generate the tolua++ host tool in the same way. See if you also encounter this segfault issue in this scenario. If it does then you may have to do a Debug configuration build and analyze the core dump to see what went wrong.

Also make sure you are using the latest CMake version, just in case it was caused by an outdated CMake installation.

**Comment by guijun** [comment]
Please find more info below:
PASS: ANDROID_NDK=~/Documents/app.sdk/android-ndk-r10d ./cmake_android.sh  build_and -DURHO3D_LUA=1 && cd build_and && make -j8
PASS: ANDROID_STANDALONE_TOOLCHAIN=~/Documents/app.sdk/arm-linux-androideabi-4.9/ ./cmake_android.sh  build_and -DURHO3D_LUA=1 && cd build_and && make -j8
FAIL: ANDROID_NDK=~/Documents/app.sdk/android-ndk-r10d ./cmake_android.sh  build_and -DURHO3D_LUAJIT=1 && cd build_and && make -j8
FAIL:  ANDROID_STANDALONE_TOOLCHAIN=~/Documents/app.sdk/arm-linux-androideabi-4.9/ ./cmake_android.sh  build_and -DURHO3D_LUAJIT=1 && cd build_and && make -j8

**Comment by weitjong** [comment]
Ah ok. It looks like it was caused by LuaJIT library and I might have an idea what the problem may be. I will attempt to commit another fix soon.
