### ISSUE TITLE
Examine converting terrain to btBvhTriangleMeshShape

### ISSUE THREAD

**Issue by cadaver** [urho3d/Urho3D#672]
Terrain collisions are jumpy at triangle edges due to using the heightfield shape. Check whether using the BVH triangle mesh shape instead (+ internal edge utility) solves this, and retains acceptable performance.

**Comment by OldSnake22** [comment]
Should definitely fix the jumpy collision issue yes.

**Comment by cadaver** [comment]
In my tests switching to a trianglemesh did not have a positive effect, and building the BVH for a 1025 x 1025 terrain took several seconds on a release build, which is not really acceptable compared to the heightfield initialization performance. It's possible I did something wrong, but closing this for now.
