### ISSUE TITLE
[Editor] (fix to camera in ortho view: change translation to zoom usage )

### ISSUE THREAD

**Issue by MonkeyFirst** [urho3d/Urho3D#677]
I guess that the camera translate from front or back  is not helpful in ortho view
in this case maybe it will be better if camera use the zoom and not translate ?

i'm change this and it now works well

FILE: EditorView.as 
PROC: void UpdateView(float timeStep)

LINE 1226                  if (mouseWheelCameraPosition && !camera.orthographic)

and i think that somehow needed to avoid transfer the zoom value from ortho view to perspective view 
mb reset it always in prespective view to = 1.0 :)

**Comment by friesencr** [comment]
There is an option in the preferences for this but it does not switch from zoom and translate per mode.  I think the best user expierence would be to switch between the 2 for the user without the option.  I wrote that code and don't think its a good user experience.

**Comment by MonkeyFirst** [comment]
you know I'll expect anything from camera in 2d, but not the translation through scene objects )
 usage of zoom in 2D by default it's more realistically I think.
 and more expected thing (event) by user from camera object. IMHO)

**Comment by MonkeyFirst** [comment]
It's solved in blender mode alt + wheel for zoom, by default wheel still doing translate to deep. close
