### ISSUE TITLE
Node->SetEnabled(false), Animated2DSprite Compoenent Still Visible

### ISSUE THREAD

**Issue by practicing01** [urho3d/Urho3D#678]
Disabling a node will not make it's Animated2DSprite component invisible.  The saved scene file even says that the node is disabled.

**Comment by cadaver** [comment]
This has been reported before and has already been fixed in the master branch.

**Comment by practicing01** [comment]
But I updated to the latest master yesterday 0.0

**Comment by cadaver** [comment]
Seems there is a bug that new StaticSprites are not marked disabled as appropriate, in the case where AnimatedSprite is disabled first and then the animation is switched. Thanks, this should be quite straightforward to fix.
