### ISSUE TITLE
[DebugRenderer] AddSphere with new sphere shape

### ISSUE THREAD

**Issue by MonkeyFirst** [urho3d/Urho3D#679]
I testing new shape for debug renderer light sphere in scene and i guess that this new shape more better looks in editor then old shape style with a lot lines. Maybe it's may add to light debug in master ?

http://www.youtube.com/watch?v=vNmyKawfjjQ

void DebugRenderer::AddSphere(const Sphere& sphere, const Color& color, bool depthTest)
{
    unsigned uintColor = color.ToUInt();
	unsigned step = 10;

	for (unsigned j = 0; j < 360; j += step) 
	{
		Vector3 p1 = PointOnSphere(sphere, 0, j);
		Vector3 p2 = PointOnSphere(sphere, 0, j+step);

		AddLine(p1, p2, uintColor, depthTest);

		Vector3 p3 = PointOnSphere(sphere, j, 90);
		Vector3 p4 = PointOnSphere(sphere, j+step, 90);
	
		AddLine(p3, p4, uintColor, depthTest);

		Vector3 p5 = PointOnSphere(sphere, 90, j);
		Vector3 p6 = PointOnSphere(sphere, 90, j+step);

		AddLine(p5, p6, uintColor, depthTest);

	}
}

also I just wanted to know is it possible to add an icon lamp (not in debug rendering) in place of the light source?

**Comment by cadaver** [comment]
This looks clean, and we actually used to draw the debug sphere like that. Bullet also used to draw it similarly. But since we updated Bullet it has adopted the current way of drawing the 3D shape of the sphere with lines, and we followed suit. So taking this would be returning to the old way, and would create a discrepancy with Bullet, unless we hacked it to draw the sphere in the old way too.

**Comment by MonkeyFirst** [comment]
I suggested the use of this sphere is only for light. not for bullet
Bullet might draw and the old sphere with many lines.
In debug rendering add two types of spheres, one for light second for bullet or something else..?

Is it possible for the light source. add sprite as the sun ico? not even in debug mode
To do this, perhaps need to mount a debugRenderer add the possibility of drawing sprites ?

**Comment by cadaver** [comment]
IMO it would be strange if light sphere and collision shape sphere would draw differently.

Yes, adding that functionality would require DebugRenderer to be able to draw UV mapped quads. It should be possible to add.

**Comment by MonkeyFirst** [comment]
how about debug icons in editor for lamps / cameras / origin of particle systems / maybe also for nodes local center... ect ? the node may have each of them (many components) therefore these icons also may have ability to auto arrange to line with common center of node.
