### ISSUE TITLE
Editor Copy/Paste CollisionShape Doesn't Update Transforms

### ISSUE THREAD

**Issue by practicing01** [urho3d/Urho3D#686]
Editor copy/paste of a CollisionShape doesn't update its transforms unless you move the parent node.

**Comment by cadaver** [comment]
Please explain the exact steps how you get this to happen, preferably starting from a blank scene.

A collision shape alone does not really have a transform, instead it uses the transform of the rigid body in the same node, plus the collisionshape offset parameters.
