### ISSUE TITLE
[Feature Request] Purge work queue by stringhash

### ISSUE THREAD

**Issue by friesencr** [urho3d/Urho3D#690]
Add the ability to purge selected items from a work queue.  A string hash came to mind as a natural fit.

**Comment by cadaver** [comment]
The work items do not have any identification tag at this point, so it would require adding one. How about purging work items simply by item pointer, meaning that if you want to be able to purge a item, you have to hold on to the pointer?

**Comment by friesencr** [comment]
By pointer is great too.  I think the queue wants the responsibility so it can put the mutex around the items list.

**Comment by friesencr** [comment]
Thank you Lasse.
