### ISSUE TITLE
table of contents for documentation

### ISSUE THREAD

**Issue by raould** [urho3d/Urho3D#694]
Pages like http://urho3d.github.io/documentation/HEAD/_building.html are long and have several sections. I think an improvement would be to have a table of contents at the top of the page, with links to the sections. This allows for (a) easier navigation and (b) easier deep linking.

(An alternative -- much like code -- is to break the long pages into smaller individual pages, one per sub-section, and link out to those from the 'master' page.)

**Comment by raould** [comment]
p.s. if there are docs explaining / teaching me re: doc generation, i can try to make a pull request for the ToCs everywhere.

**Comment by weitjong** [comment]
Our documentation is generated by using Doxygen tool. You should be able to find the *.dox files in the ```Docs``` subdir in our project root. A small portion of the documentation are generated on the fly when the doc is built using ```make doc``` or its equivalent command on other IDEs. You may want to refer to Doxygen own documentation on how to modify the *.dox file.

**Comment by raould** [comment]
submitted a p.r. for it.
