### ISSUE TITLE
feature: support typed lua

### ISSUE THREAD

**Issue by raould** [urho3d/Urho3D#699]
https://github.com/andremm/typedlua

It would be super keen to support Typed Lua.

**Comment by OvermindDL1** [comment]
For note, I'm not seeing any reason why Typed Lua would not already be supported, it is just an add-in module for lua and should be able to be loaded as any other normal lua file, or you could precompile those files to lua via cmake, either works.  What specifically are you wanting done @raould for this?

**Comment by raould** [comment]
A fine point, if it all works, that's cool!
