### ISSUE TITLE
Arbitrary vertex declarations

### ISSUE THREAD

**Issue by cadaver** [urho3d/Urho3D#707]
Port the vertex declaration code from Turso3D, which allows defining vertex elements by semantic, index and format; for example you can define an arbitrary number of texcoords.

Retain compatibility with the old "element mask" system to still allow defining predefined semantic+index+format combos easily.

The binary model format will need a compatibility mechanism, for example specifying a zero element mask, which means that arbitrary vertex declarations follow.

After this is done, AssetImporter (and possibly OgreImporter) can be made to handle source data vertex declarations more accurately.

**Comment by aster2013** [comment]
It is better add a version number into file format after file identity.

**Comment by weitjong** [comment]
Yes, I agree. In my ```animation-refactor``` branch, I have something like this for loading the animation file. We could do the same for the model file too.
```
bool Animation::Load(Deserializer& source)
{
    PROFILE(LoadAnimation);

    // Check ID
    if (source.ReadFileID() != "UANI")
    {
        LOGERROR(source.GetName() + " is not a valid animation file");
        return false;
    }

    unsigned memoryUse = sizeof(Animation);

    // Read the format version, if not available then fallback to version 1
    String versionString(source.ReadFileID());
    unsigned version = 1;
    if (versionString.StartsWith("v") && versionString.EndsWith("#"))
        version = ToUInt(versionString.Substring(1, 2));
    else
        source.Seek(4);     // Return the source position before the format version read

    // Read name and length
    animationName_ = source.ReadString();
    animationNameHash_ = animationName_;
    length_ = source.ReadFloat();
    tracks_.Clear();
```
Based on the version number that the code could handle both old format and new format.

**Comment by cadaver** [comment]
Yes, that looks rather clean, and it's extremely unlikely that the following binary data in an old format model would accidentally yield a version string. On Android, I believe seeking backward induces a reset of the compressed asset stream, requiring to read from the beginning, but since it's so close to the file start it should not be a big deal. And it will only happen for the legacy files.

**Comment by aster2013** [comment]
Change load function like this.
```
bool Model::BeginLoad(Deserializer& source)
{
    // Check ID
    if (source.ReadFileID() != "UMDL")
    {
        LOGERROR(source.GetName() + " is not a valid model file");
        return false;
    }
    
    geometries_.Clear();
    geometryBoneMappings_.Clear();
    geometryCenters_.Clear();
    morphs_.Clear();
    vertexBuffers_.Clear();
    indexBuffers_.Clear();
    
    // Version
    unsigned version = source.ReadUInt();
    
    bool result = false;
    switch (version)
    {
    case 0:
        result = BeginLoadVersion0(source);
        break;

    case 1:
        result = BeginLoadVersion1(source);
        break;

    default:
        break;
    }

    return result;
}
```

**Comment by cadaver** [comment]
@aster2013: if we add the version define directly (as it doesn't exist now), we make all current model files unloadable.

**Comment by aster2013** [comment]
@cadaver Yes, so another solution is change file identity, like this.
```
bool Model::BeginLoad(Deserializer& source)
{
    // Check ID
    String fileID(source.ReadFileID());
    
    if (fileID == "UMDL") // Old Urho3d model file
        return BeginLoadVersion0(source);
    else if (fileID == "UMDV") // UMDV = Urho3D model with version
    {
        // Version
        unsigned version = source.ReadUInt();
        switch (version)
        {
        case 1:
            return BeginLoadVersion1(source);

        case 2:
            return BeginLoadVersion2(source);

        default:
            LOGERROR(source.GetName() + " is not a valid version");
            return false;
        }
    }
    
    LOGERROR(source.GetName() + " is not a valid model file");
    return false;
}
```

**Comment by boberfly** [comment]
Just a lower-level API question, would this be defined as separate VAOs for the GL3.x path?

**Comment by cadaver** [comment]
It could be, but it's not that simple as there can be several vertex buffers in use, which means that Graphics must inspect the final vertex buffer combination and set the VAO as needed.

I did experiment with creating multiple VAO's in the GL3 code but at least on the machines I tested I didn't find appreciable performance gain, so I left it to use the single hardcoded VAO for now.

**Comment by boberfly** [comment]
This would be a really cool feature to have. With a bit of direction I could approach implementing this, as I have some potential uses for this.

**Comment by cadaver** [comment]
I did implement it in Turso3D, so you could look into it for reference. This is also on my list too, it just got extremely delayed due to my C64 game :) I will post here when/if I start working on this so that we avoid duplicate work.

Turso3D didn't implement partial vertex buffer binding though (see comment above). One way to do it would be with a simple bitmask, where bit 0 is first vertex element etc.

**Comment by cadaver** [comment]
I'm prepared to imminently start working on this. @boberfly Did you already start?

**Comment by cadaver** [comment]
Now being worked on in the vertexdeclaration branch. D3D9 implementation done, others to follow. I solved the "vertex buffer binding masks" issue by simply making higher index vertex buffer override whatever semantics defined by lower index buffer, so for example a morphable model can define a second vertex buffer which provides overridden positions, normals, tangents. Not requiring the binding masks should actually speed up rendering slightly, as there's less memory access needed.

**Comment by boberfly** [comment]
Hey @cadaver I didn't see this comment sorry, and no I didn't end up starting this (getting slammed at my day job right now for the next few weeks, damn deadlines...!)

Great to see progress though on this.
