### ISSUE TITLE
return value type mistake in "Variant.h" file, line 725

### ISSUE THREAD

**Issue by azzvx** [urho3d/Urho3D#710]
///Source/Urho3D/Core/Variant.h
 /// Return unsigned int or zero on type mismatch.
    int GetUInt() const { return type_ == VAR_INT ? (unsigned)value_.int_ : 0; }
it should be 'unsigned'

**Comment by cadaver** [comment]
Thanks for the heads-up. This should be a no-brainer to fix and break nothing.
