### ISSUE TITLE
WebP Textures

### ISSUE THREAD

**Issue by Skrylar** [urho3d/Urho3D#713]
How do we feel about supporting the loading of webp textures?

It seems possible to take just the decoding part of the reference implementation and hook it up to the existing image loading API, toss it in the third party source directory and hook up a "WANT_WEBP" flag in cmake.  I'll probably do this to my local copy regardless, but if we're okay merging this in to Urho I'll patch it in proper.

**Comment by cadaver** [comment]
I have no strong feelings for or against, if it integrates cleanly a pull request would be nice.

Our CMake build flags begin with URHO3D_ so it should be for example URHO3D_WEBP. Though we don't conditionally compile other image formats support, so if the reference decoder is small (comparable to stb_image) and does not pull in other dependencies, a flag would not even be strictly necessary.

**Comment by Skrylar** [comment]
Its a little bit bigger than stb_image (though stb_image is quite small, so that isn't saying much.)  I don't think it has any external dependencies, though.

**Comment by cadaver** [comment]
In that case you can add the build flag but set it enabled by default. People with interest in absolutely minimum runtime size can then disable it, similarly like physics or Urho2D can be disabled.

**Comment by carnalis** [comment]
This issue can be closed.
