### ISSUE TITLE
Shadow rendering problem in Android on one plus one phone

### ISSUE THREAD

**Issue by sinha-abhishek** [urho3d/Urho3D#717]
Hi,

I have two 3d models created and placed one above the other, however, when I set both to cast shadows the shadows are being rendered on top of the model rather than below. This is only being observer in one plus one phone but is working fine on nexus7 tablet. Following is scene xml
<?xml version="1.0"?>
<scene id="1">
	<attribute name="Name" value="" />
	<attribute name="Time Scale" value="1" />
	<attribute name="Smoothing Constant" value="50" />
	<attribute name="Snap Threshold" value="5" />
	<attribute name="Elapsed Time" value="108.377" />
	<attribute name="Next Replicated Node ID" value="13" />
	<attribute name="Next Replicated Component ID" value="71" />
	<attribute name="Next Local Node ID" value="16777279" />
	<attribute name="Next Local Component ID" value="16777295" />
	<attribute name="Variables" />
	<attribute name="Variable Names" value="" />
	<component type="Octree" id="1" />
	<component type="DebugRenderer" id="2" />
	<component type="PhysicsWorld" id="21" />
	<node id="16777216">
		<attribute name="Is Enabled" value="true" />
		<attribute name="Name" value="ground" />
		<attribute name="Position" value="0 0 0" />
		<attribute name="Rotation" value="1 0 0 0" />
		<attribute name="Scale" value="1 1 1" />
		<attribute name="Variables" />
		<component type="StaticModel" id="3">
			<attribute name="Model" value="Model;Models/ground.mdl" />
			<attribute name="Material" value="Material;Materials/grass_Shader.xml" />
		</component>
		<component type="RigidBody" id="16777220">
			<attribute name="Rolling Friction" value="0.5" />
			<attribute name="Restitution" value="0.23" />
		</component>
		<component type="CollisionShape" id="16777226">
			<attribute name="Shape Type" value="TriangleMesh" />
			<attribute name="Model" value="Model;Models/ground.mdl" />
		</component>
	</node>
	<node id="16777217">
		<attribute name="Is Enabled" value="true" />
		<attribute name="Name" value="" />
		<attribute name="Position" value="0 0 0" />
		<attribute name="Rotation" value="0.939693 0.34202 0 0" />
		<attribute name="Scale" value="1 1 1" />
		<attribute name="Variables" />
		<component type="Light" id="16777216">
			<attribute name="Light Type" value="Directional" />
			<attribute name="Specular Intensity" value="2" />
			<attribute name="Brightness Multiplier" value="1.5" />
			<attribute name="Cast Shadows" value="true" />
		</component>
	</node>
	<node id="16777239">
		<attribute name="Is Enabled" value="true" />
		<attribute name="Name" value="" />
		<attribute name="Position" value="0 0 0" />
		<attribute name="Rotation" value="1 0 0 0" />
		<attribute name="Scale" value="1 1 1" />
		<attribute name="Variables" />
		<component type="Zone" id="16777227">
			<attribute name="Bounding Box Min" value="-30 -30 -30" />
			<attribute name="Bounding Box Max" value="30 30 30" />
			<attribute name="Fog Color" value="0.3 0.5 1 1" />
			<attribute name="Fog Start" value="300" />
			<attribute name="Fog End" value="400" />
		</component>
	</node>
	<node id="16777272">
		<attribute name="Is Enabled" value="true" />
		<attribute name="Name" value="" />
		<attribute name="Position" value="0 0 0" />
		<attribute name="Rotation" value="0.996195 -0.087156 0 0" />
		<attribute name="Scale" value="1 1 1" />
		<attribute name="Variables" />
		<component type="Light" id="16777283">
			<attribute name="Light Type" value="Directional" />
			<attribute name="Specular Intensity" value="2" />
			<attribute name="Brightness Multiplier" value="1.75" />
			<attribute name="Cast Shadows" value="true" />
		</component>
	</node>
	<node id="16777273">
		<attribute name="Is Enabled" value="true" />
		<attribute name="Name" value="camNode" />
		<attribute name="Position" value="0 1.5 -13.7093" />
		<attribute name="Rotation" value="0.991445 0.130526 0 0" />
		<attribute name="Scale" value="1 1 1" />
		<attribute name="Variables" />
		<component type="Camera" id="16777284">
			<attribute name="Far Clip" value="3000" />
			<attribute name="Aspect Ratio" value="1.77778" />
			<attribute name="Zoom" value="1.3" />
		</component>
	</node>
	<node id="16777274">
		<attribute name="Is Enabled" value="true" />
		<attribute name="Name" value="" />
		<attribute name="Position" value="-0.099468 0 0" />
		<attribute name="Rotation" value="0.92122 0.24684 0.29046 0.0778284" />
		<attribute name="Scale" value="1 1 1" />
		<attribute name="Variables" />
		<component type="Light" id="16777285">
			<attribute name="Light Type" value="Directional" />
			<attribute name="Specular Intensity" value="2" />
			<attribute name="Brightness Multiplier" value="1.5" />
			<attribute name="Cast Shadows" value="true" />
		</component>
	</node>
	<node id="16777275">
		<attribute name="Is Enabled" value="true" />
		<attribute name="Name" value="" />
		<attribute name="Position" value="-0.099468 0 0" />
		<attribute name="Rotation" value="0.984808 0 0.173648 0" />
		<attribute name="Scale" value="1 1 1" />
		<attribute name="Variables" />
		<component type="Light" id="16777286">
			<attribute name="Light Type" value="Directional" />
			<attribute name="Specular Intensity" value="2" />
			<attribute name="Brightness Multiplier" value="1.5" />
			<attribute name="Cast Shadows" value="true" />
		</component>
	</node>
	<node id="16777278">
		<attribute name="Is Enabled" value="true" />
		<attribute name="Name" value="Patch" />
		<attribute name="Position" value="0 0.1 0" />
		<attribute name="Rotation" value="0.707107 0 0.707107 0" />
		<attribute name="Scale" value="1 1 1" />
		<attribute name="Variables" />
		<component type="StaticModel" id="16777292">
			<attribute name="Model" value="Model;Models/patch.mdl" />
			<attribute name="Material" value="Material;Materials/GreenTransparent.xml" />
			<attribute name="Cast Shadows" value="true" />
		</component>
		<component type="RigidBody" id="16777293">
			<attribute name="Physics Rotation" value="0.707107 0 0.707107 0" />
			<attribute name="Physics Position" value="0 0.1 0" />
			<attribute name="Rolling Friction" value="0.1" />
			<attribute name="Restitution" value="0.5" />
		</component>
		<component type="CollisionShape" id="16777294">
			<attribute name="Shape Type" value="TriangleMesh" />
			<attribute name="Model" value="Model;Models/patch.mdl" />
		</component>
	</node>
</scene>

Following is the screenshot being seen

![screenshot_2015-05-05-14-22-48](https://cloud.githubusercontent.com/assets/1322238/7469914/2cab22e6-f336-11e4-8417-8ad1965ebf57.png)

**Comment by sinha-abhishek** [comment]
<attribute name="Name" value="" />
	<attribute name="Time Scale" value="1" />
	<attribute name="Smoothing Constant" value="50" />
	<attribute name="Snap Threshold" value="5" />
	<attribute name="Elapsed Time" value="108.377" />
	<attribute name="Next Replicated Node ID" value="13" />
	<attribute name="Next Replicated Component ID" value="71" />
	<attribute name="Next Local Node ID" value="16777279" />
	<attribute name="Next Local Component ID" value="16777295" />
	<attribute name="Variables" />
	<attribute name="Variable Names" value="" />
	<component type="Octree" id="1" />
	<component type="DebugRenderer" id="2" />
	<component type="PhysicsWorld" id="21" />
	<node id="16777216">
		<attribute name="Is Enabled" value="true" />
		<attribute name="Name" value="ground" />
		<attribute name="Position" value="0 0 0" />
		<attribute name="Rotation" value="1 0 0 0" />
		<attribute name="Scale" value="1 1 1" />
		<attribute name="Variables" />
		<component type="StaticModel" id="3">
			<attribute name="Model" value="Model;Models/ground.mdl" />
			<attribute name="Material" value="Material;Materials/grass_Shader.xml" />
		</component>
		<component type="RigidBody" id="16777220">
			<attribute name="Rolling Friction" value="0.5" />
			<attribute name="Restitution" value="0.23" />
		</component>
		<component type="CollisionShape" id="16777226">
			<attribute name="Shape Type" value="TriangleMesh" />
			<attribute name="Model" value="Model;Models/ground.mdl" />
		</component>
	</node>
	<node id="16777217">
		<attribute name="Is Enabled" value="true" />
		<attribute name="Name" value="" />
		<attribute name="Position" value="0 0 0" />
		<attribute name="Rotation" value="0.939693 0.34202 0 0" />
		<attribute name="Scale" value="1 1 1" />
		<attribute name="Variables" />
		<component type="Light" id="16777216">
			<attribute name="Light Type" value="Directional" />
			<attribute name="Specular Intensity" value="2" />
			<attribute name="Brightness Multiplier" value="1.5" />
			<attribute name="Cast Shadows" value="true" />
		</component>
	</node>
	<node id="16777239">
		<attribute name="Is Enabled" value="true" />
		<attribute name="Name" value="" />
		<attribute name="Position" value="0 0 0" />
		<attribute name="Rotation" value="1 0 0 0" />
		<attribute name="Scale" value="1 1 1" />
		<attribute name="Variables" />
		<component type="Zone" id="16777227">
			<attribute name="Bounding Box Min" value="-30 -30 -30" />
			<attribute name="Bounding Box Max" value="30 30 30" />
			<attribute name="Fog Color" value="0.3 0.5 1 1" />
			<attribute name="Fog Start" value="300" />
			<attribute name="Fog End" value="400" />
		</component>
	</node>
	<node id="16777272">
		<attribute name="Is Enabled" value="true" />
		<attribute name="Name" value="" />
		<attribute name="Position" value="0 0 0" />
		<attribute name="Rotation" value="0.996195 -0.087156 0 0" />
		<attribute name="Scale" value="1 1 1" />
		<attribute name="Variables" />
		<component type="Light" id="16777283">
			<attribute name="Light Type" value="Directional" />
			<attribute name="Specular Intensity" value="2" />
			<attribute name="Brightness Multiplier" value="1.75" />
			<attribute name="Cast Shadows" value="true" />
		</component>
	</node>
	<node id="16777273">
		<attribute name="Is Enabled" value="true" />
		<attribute name="Name" value="camNode" />
		<attribute name="Position" value="0 1.5 -13.7093" />
		<attribute name="Rotation" value="0.991445 0.130526 0 0" />
		<attribute name="Scale" value="1 1 1" />
		<attribute name="Variables" />
		<component type="Camera" id="16777284">
			<attribute name="Far Clip" value="3000" />
			<attribute name="Aspect Ratio" value="1.77778" />
			<attribute name="Zoom" value="1.3" />
		</component>
	</node>
	<node id="16777274">
		<attribute name="Is Enabled" value="true" />
		<attribute name="Name" value="" />
		<attribute name="Position" value="-0.099468 0 0" />
		<attribute name="Rotation" value="0.92122 0.24684 0.29046 0.0778284" />
		<attribute name="Scale" value="1 1 1" />
		<attribute name="Variables" />
		<component type="Light" id="16777285">
			<attribute name="Light Type" value="Directional" />
			<attribute name="Specular Intensity" value="2" />
			<attribute name="Brightness Multiplier" value="1.5" />
			<attribute name="Cast Shadows" value="true" />
		</component>
	</node>
	<node id="16777275">
		<attribute name="Is Enabled" value="true" />
		<attribute name="Name" value="" />
		<attribute name="Position" value="-0.099468 0 0" />
		<attribute name="Rotation" value="0.984808 0 0.173648 0" />
		<attribute name="Scale" value="1 1 1" />
		<attribute name="Variables" />
		<component type="Light" id="16777286">
			<attribute name="Light Type" value="Directional" />
			<attribute name="Specular Intensity" value="2" />
			<attribute name="Brightness Multiplier" value="1.5" />
			<attribute name="Cast Shadows" value="true" />
		</component>
	</node>
	<node id="16777278">
		<attribute name="Is Enabled" value="true" />
		<attribute name="Name" value="Patch" />
		<attribute name="Position" value="0 0.1 0" />
		<attribute name="Rotation" value="0.707107 0 0.707107 0" />
		<attribute name="Scale" value="1 1 1" />
		<attribute name="Variables" />
		<component type="StaticModel" id="16777292">
			<attribute name="Model" value="Model;Models/patch.mdl" />
			<attribute name="Material" value="Material;Materials/GreenTransparent.xml" />
			<attribute name="Cast Shadows" value="true" />
		</component>
		<component type="RigidBody" id="16777293">
			<attribute name="Physics Rotation" value="0.707107 0 0.707107 0" />
			<attribute name="Physics Position" value="0 0.1 0" />
			<attribute name="Rolling Friction" value="0.1" />
			<attribute name="Restitution" value="0.5" />
		</component>
		<component type="CollisionShape" id="16777294">
			<attribute name="Shape Type" value="TriangleMesh" />
			<attribute name="Model" value="Model;Models/patch.mdl" />
		</component>
	</node>
</scene>

**Comment by cadaver** [comment]
We have no control to the shadow depth texture precision on mobile devices. You can try a more extreme constant depth bias to fight the self-shadowing, or to use backface rendering for shadows in the material. Other than that, these kinds of issues are expected.
