### ISSUE TITLE
Greyscale transparent png pictures not displaying as greyscale

### ISSUE THREAD

**Issue by friesencr** [urho3d/Urho3D#718]
This seems to be a result of the stb_image upgrade.

Input: 
![grey_scale_transparent_png](https://cloud.githubusercontent.com/assets/105460/7479337/9ef06060-f326-11e4-9392-0aaf9a23a905.png)

Output:
![urho_greyscale_transparent_png_screenshot](https://cloud.githubusercontent.com/assets/105460/7479339/a542ed48-f326-11e4-9416-4ea225ab2c10.png)

Files:
https://www.dropbox.com/s/gi48e6wjxsi2f49/grey_scale_transparent_png.png?dl=0
https://www.dropbox.com/s/eaugjpk58veg0lk/urho_greyscale_transparent_png_screenshot.png?dl=0

**Comment by cadaver** [comment]
I believe this is rather related to the deprecation of Luminance-Alpha format in D3D11 & OpenGL 3, as I cannot reproduce this on D3D9. A certain fix is to make STB_Image always return the loaded images as 4 components.
