### ISSUE TITLE
OpenGL3 float16 and float32 formats still to luminance

### ISSUE THREAD

**Issue by Amadeus-osa** [urho3d/Urho3D#722]
In OpenGL3 graphics subsystem, Graphics::GetFloat16Format() and Graphics::GetFloat32Format() functions still return deprecated GL_LUMINANCE format, should be GL_R16F and GL_R32F if gl3Support is on.

**Comment by cadaver** [comment]
It occurs to me that this should never have returned float luminance formats, as on D3D the corresponding format is R16F or R32F. Need just to check to which extension that belongs.
