### ISSUE TITLE
Very large triangle mesh collisionshape fails

### ISSUE THREAD

**Issue by gokr** [urho3d/Urho3D#730]
It took a while for us to figure it out, but if you load a very large model (say via AssetImporter to a single mdl file) with millions of polys, and then create a triangle mesh collisionshape using it - that will fail pretty hard.

The issue lies in the fact that Bullet's btBvhTriangleMeshShape evidently has a limit on how large mesh it can handle, we solved it by simply not enabling useQuantizedAabbCompression, using false on this line:
https://github.com/urho3d/Urho3D/blob/bb2ebf756838ae5512bbe624fd99161691da4695/Source/Urho3D/Physics/CollisionShape.cpp#L183

Not sure how to fix more properly, probably one would need to catch some kind of error or check size of mesh etc and only enable if mesh is small enough. Another "workaround" is to import big models as prefabs instead which means AssetImporter will break the model into MANY small models.

**Comment by cadaver** [comment]
Hi,
do you mean large as in the triangle count, or large as in the bounding box size? What would you recommend as the threshold? (does not matter if it's conservative)

**Comment by gokr** [comment]
I mean large as in triangle count, like say a couple of millions, don't know the exact limit. But yes, we are now using prefabs instead. I guess one can figure out the limit by reading Bullet code, IIRC there is some bit shifting etc going on there. I can take a look.

**Comment by Mike3D** [comment]
As triangle mesh are used for static geometries, I prefer to export/use a separate global decimated geometry for physics. Decimating 2 millions tris by 98% leaves a decent 40000 tris physics geometry. Creating too many separate physics geometries pollute the broadphase, as stated in Bullet user manual.
