### ISSUE TITLE
cmake_ios.sh /path/to/build-tree [build-options]

### ISSUE THREAD

**Issue by meiry** [urho3d/Urho3D#735]
1 . git clone https://github.com/urho3d/Urho3D.git
2.  cd /Users/meiryanovich/Documents/3d/Urho3D/git/Urho3D
3.  ./cmake_ios.sh -DURHO3D_SAMPLES=1 
the result is :
```
Usage: cmake_ios.sh /path/to/build-tree [build-options]
```

cmake version 3.1.0
mac-mini with OS 10.10.3 64bit 
latest xcode 

it can be related to the bug i had then: https://github.com/urho3d/Urho3D/issues/604
the script should work out or the box .

**Comment by Stinkfist0** [comment]
You seem to be missing the ` /path/to/build-tree` part: step 3 should be 'mkdir ios-build' and part 4 ` ./cmake_ios.sh ios-build -DURHO3D_SAMPLES=1`.

**Comment by cadaver** [comment]
Yes, it's mandatory to specify where Urho is to be built. Easiest is to do ./cmake_ios.sh .

**Comment by meiry** [comment]
thanks , its not clear in the documentation , the part of the ios .
