### ISSUE TITLE
d3dcompiler_47.dll not installed

### ISSUE THREAD

**Issue by bvanevery** [urho3d/Urho3D#738]
Urho3d samples all fail after installation on Windows 7.  Says D3DCOMPILER_47.dll is missing.  Samples run just fine from within VS2013, starting a debug with the various projects in the solution.  Selecting URHO3D_STATIC_RUNTIME in CMake and doing a clean build and install does not solve the problem.  Seems it isn't meant to eliminate all .dll dependencies.

Windows 7 and 8.0 do not ship with this dll for some reason.  Has to do with DirectX being folded into the Windows SDK and not existing separately anymore.  Apparently installing a DirectX redistributable isn't what one does anymore either.  http://blogs.msdn.com/b/chuckw/archive/2012/05/07/hlsl-fxc-and-d3dcompile.aspx says, "With the Windows 8.0 SDK, the D3DCompile DLL is never installed to the %WINDIR% folders. Instead, you should copy it into your applications folder and deploy it 'application local' with your Win32 desktop application."

**Comment by weitjong** [comment]
Before making any changes to the INSTALL step for the D3D code path, can someone confirm that the said DLL is now redistributable by application to its end users on Windows 7 and 8.0?

**Comment by cadaver** [comment]
The sdk_license.rtf that comes with the Windows Kit links to an online document

http://go.microsoft.com/fwlink/?LinkId=251953

which lists the d3dcompiler DLL as a file you can redistribute.

**Comment by weitjong** [comment]
Ok, but I have a few other questions. In Open Source software, we are permitted to redistribute (and other things) subjected to a condition where the corresponding OS license is being included as well. So, what else do we need to do in order to comply with MS EULA to distribute the D3DCompiler_47.dll? Or is it really just copy this one file?

On Travis CI side. How do we get just this file (and may be also D3DCompiler_46.dll) online? The Windows 8.1 SDK is being packaged as an .exe. We cannot execute it on Linux VM to extract the .dll out. If we cannot get it then the Windows D3D9 build artifacts will still be missing this D3DCompiler_46.dll. From memory, ```#46``` is the version being referenced by MinGW-W64 but even MinGW-W64 itself does not redistribute the D3DCompiler_46.dll. Hence my question above.

**Comment by cadaver** [comment]
I would recommend just using OpenGL for automated builds, in which case this is a non-issue. For CMake builds on the user's computer it could detect the Windows Kit location and copy the file.

**Comment by weitjong** [comment]
Ok. I see what I can do. The revised build system will just detect whether a copy of D3DCompiler_46.dll or newer is available in the Windows 8.x SDK redist directory. If it is found then make a copy of it to the bin directory where Urho3D binaries are located. If it is not found then skip this step all together. Let me know if there are other things that need to be copied along the step.

**Comment by cadaver** [comment]
That file should be all. 

The MSVC runtime is potentially also needed (if Urho is not built with static runtime flag) but it's not permitted to be filecopied in the same manner. Instead, the runtime installer should be invoked during the application's installation, but that is outside Urho build's scope.

**Comment by weitjong** [comment]
I plan to use this registry key "HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Microsoft SDKs\Windows\v8.1" and subkey "InstallationFolder" to find the value of the ```Microsoft SDKs``` base directory. It works fine on my Win7 VM. Could you verify if it works for your Windows system too.

**Comment by cadaver** [comment]
Yes, it is there. On systems with only VS2012 installed there might be only 8.0 SDK (HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Microsoft SDKs\Windows\v8.0)

**Comment by bvanevery** [comment]
Some licensing fine print.  "Windows Kits/8.1/Redist/sdk_license.rtf" says there's a "Build Server List", a bunch of components you're allowed to use in a build, if not necessarily redistribute them.  It's at go.microsoft.com/fwlink/?LinkId=294839 .  Perhaps that solves a Linux build server issue you mentioned earlier.

A REDIST.TXT is cited, it exists at go.microsoft.com/fwlink/?LinkId=294840 .  It says:
"These files may only be redistributed with your desktop apps.  They may not be redistributed with any Windows Store apps.

·	Program Files\Windows Kits\8.1\Redist\D3D\x64\d3dcompiler_47.dll
·	Program Files\Windows Kits\8.1\Redist\D3D\x64\d3dcsx_47.dll
·	Program Files\Windows Kits\8.1\Redist\D3D\x86\d3dcompiler_47.dll
·	Program Files\Windows Kits\8.1\Redist\D3D\x86\d3dcsx_47.dll
"
I don't know if that corner case affects the Urho3d binary SDK distibution.  I doubt it, but then I have no interest in any kind of Windows Store development.

The licensing also excludes viral source licenses, such as the GPL or LGPL.  Not an issue for Urho3d; could be an issue for someone making use of Urho3d.  Wouldn't worry about it; might be worth a sentence making note of it, in some kind of "licensing of underlying components" inventory if such you have.

Thanks for looking at this issue so promptly!  Regardless of when it gets done, I'm impressed that you actually care.  Means your project has more cross-platform build maturity than usual.

**Comment by weitjong** [comment]
As per discussed with Lasse, the revised build system only installs the d3dcompiler_xx.dll when it is found in the MS Windows SDK. It does not attempt to install the SDK on user behalf. It does not attempt to install the SDK on the Travis CI "build server". IANAL, although it seems to be perfectly legal to install the SDK or to have just the .dll required somewhere in our repositories (similar to how we pre-install Android SDK), it is still technically impossible to do so. Travis CI Linux VM cannot execute the downloaded SDK .exe. We also avoid the whole EULA thingy by not installing anything on our end.
