### ISSUE TITLE
the editor all too dark

### ISSUE THREAD

**Issue by warzes** [urho3d/Urho3D#739]
On some screens in the editor all too dark.

I have decided is to insert:
void Urho3DPlayer :: Start ()
{
GetSubsystem <Graphics> () -> SetSRGB (true);
...

Probably it is necessary to fix

**Comment by gcclua** [comment]
#include "/root/Downloads/Urho3D/Source/Urho3D/Graphics/Graphics.h"
void Urho3DPlayer::Start()
{
    //##kiler
    this->GetSubsystem<Graphics>()->SetSRGB(true);

**Comment by gcclua** [comment]
#include "/root/Downloads/Urho3D/Source/Urho3D/Graphics/Graphics.h"
void Urho3DPlayer::Start()
{
    //##kiler
    this->GetSubsystem\<Graphics\>()->SetSRGB(true);
