### ISSUE TITLE
DrawDebugGeometry() + FXAA2 issue

### ISSUE THREAD

**Issue by Mike3D** [urho3d/Urho3D#741]
When enabling FXAA2, debug geometry becomes weird (only a few pixels are drawn).

Steps to reproduce:
In sample 11_Physics - SetupViewport(), add FXAA2 (borrowing code from sample 09) and press space to toggle debug draw:

```lua
    local effectRenderPath = viewport:GetRenderPath():Clone()
    effectRenderPath:Append(cache:GetResource("XMLFile", "PostProcess/Bloom.xml"))
    effectRenderPath:Append(cache:GetResource("XMLFile", "PostProcess/FXAA2.xml"))
    effectRenderPath:SetEnabled("Bloom", true)
    effectRenderPath:SetEnabled("FXAA2", true)
    viewport:SetRenderPath(effectRenderPath)
```
Note that:
- it worked fine in 1.32
- tested with OpenGL only

**Comment by cadaver** [comment]
Reproduced. This is an issue with scene rendering and postprocessing not using the same depth buffer on OpenGL. Bugs related to this have been fixed before, but it's not foolproof yet.

**Comment by Mike3D** [comment]
Many thanks cadaver.
I have an unrelated remaining issue with 2D rendering, occuring with my 'Urho2DPlatformer demo'.
I'll open a new issue when the culprit will get identified.
