### ISSUE TITLE
Urho2D AnimatedSprite2D + ParticleEffect2D issue

### ISSUE THREAD

**Issue by Mike3D** [urho3d/Urho3D#742]
Adding a ParticleEffect2D wrecks rendering of AnimatedSprite2D (maybe blending?).

Steps to reproduce:
In sample 33_Urho2DSpriterAnimation.lua, add these lines at the end of CreateScene():
```lua
	local particleNode = scene_:CreateChild("Emitter")
	local particleEmitter = particleNode:CreateComponent("ParticleEmitter2D")
	particleEmitter.effect = cache:GetResource("ParticleEffect2D", "Urho2D/sun.pex")
	particleNode:Remove()
```
Note:
- worked fine with 1.32
- tested with OpenGL only

Not related, I also noticed that the looping animations no longer 'transition' smoothly ('transition' between end and start).

**Comment by cadaver** [comment]
Fixed the looped animation issue. The corrupt rendering looks like it leaves incorrect blend mode to the sprite. Would be nice to have @aster2013 's input on this, since it probably goes quite deep into the guts of the 2D rendering.

**Comment by Mike3D** [comment]
Works great, many thanks cadaver.
Hope to see @aster2013 here soon, I miss him.
