### ISSUE TITLE
Migrate Android build system to Gradle Kotlin DSL

### ISSUE THREAD

**Issue by weitjong** [urho3d/Urho3D#743]
The last Android CI build last night failed due to broken Ant build script. Our Android CI build was fine with SDK Tools version 24.0.2. The diff of `build.xml` between these two versions shows that a few Ant properties are not being defined anymore. One of them is for `aapk` which resulting in Ant build script to look for `aapk` in a wrong directory in the last CI build.

**Comment by weitjong** [comment]
Followed the recommendation found in https://code.google.com/p/android/issues/detail?id=176488. Still no working and reopen the issue again.

**Comment by weitjong** [comment]
The build failure has been workaround temporarily by retaining the preinstalled version of the SDK Tools (24.0.2). The issue will manifest itself again when Travis CI team preinstall the Android build environment with SDK Tools version 24.3.2 later. As such, I will keep this issue open for now. KIV.

Perhaps it would be better to take the opportunity to migrate the Ant build script to Gradle build script.

**Comment by weitjong** [comment]
I think it is time we revisit this. As mentioned in the forum before, I have an interest to migrate the Android build to Gradle Kotlin DSL (was Gradle Script Kotlin).

**Comment by rokups** [comment]
If anyone stumbles upon this issue here is how you downgrade your android SDK:

1. Delete `tools` and `platform-tools` folders from your android SDK folder.
2. Download older versions (replace `linux` with `windows` or `macosx` in the url if needed):
    * http://dl-ssl.google.com/android/repository/platform-tools_r24-linux.zip
    * http://dl-ssl.google.com/android/repository/tools_r24.4-linux.zip
3. Unpack downloaded archives to your android SDK folder.

**Comment by weitjong** [comment]
Wow, time flies! Finally, I have decided to assign this task to myself since I last conveyed my interest about a years ago. The `kotlin-dsl` has finally made it into the official releases of Gradle. So, it is not as bleeding edge anymore to try also now.

My work will be pushed to `gradle-kotlin-dsl` development branch when it is ready. I will log my progress here.

The initial Gradle build system integration has already taken shape. After trying with a few different setup, I have chosen one that I can live with. It will be a multi-modules setup. By default it will use `ndk-bundle` and `cmake` (including the android.toolchain.cmake file) provided by the Android SDK Manager. I have adapted one of our existing CMake module to work with the android.toolchain.cmake, so the native build tree generation and native build tree compilation are both successful now. I will continue to adapt the rest of our CMake modules as I go until the whole build process is fully automated, i.e. just work out of the box. One more thing. the adapted CMake build system should still work as before. Invocation via Gradle is only necessary when targeting Android platform.

Issue currently I face:  the Gradle Android plugin may have a bug. It does not handle symbolic links correctly.    As you know, our build system creates symbolic links to reference the 3rd-party headers in the build tree and this is good. The problem is, the Android plugin may clean the build tree before rerunning the CMake but instead of removing the symlink, it actually dereferencing the symlink and removing the actual target files, which is bad.

**Comment by weitjong** [comment]
Hack two of the Android plugin's Gradle tasks in order to workaround the problem with the symlink. Problem solved. Back on track again.

**Comment by weitjong** [comment]
Have a preliminary success in multi-modules build (one lib module + one app module) without any error.

**Comment by weitjong** [comment]
I didn't have much time to work on this these few days, but still I am making progress bit by bit. As they say, a picture means a thousand words. 

![screenshot from 2018-06-28 23-29-44](https://user-images.githubusercontent.com/5548048/42044657-22bc4a2c-7b2c-11e8-8341-b0dda238a919.png)

**Comment by weitjong** [comment]
Completed migrating the Java code for the launcher to Kotlin. Refactoring to fix the old known issues (like launcher without scripting support enabled) at the same time. Haven’t decided yet whether I should just stop there or migrate all the Java code from SDL to Kotlin as well. The latter would fix one or two NPE issue reported by user in the past.

**Comment by rokups** [comment]
My concern is that rewriting SDL initialization code will put maintenance burden on the project. Can project afford that?

**Comment by weitjong** [comment]
There are only about 4 Java classes and they seldom change. Also it is just one git diff command away to find what exactly change from version to version. So, it is not that much of concern.

**Comment by rokups** [comment]
Looks like a fair amount of changes in 8 months https://github.com/spurious/SDL-mirror/commits/master/android-project/app/src/main/java/org/libsdl/app

**Comment by eugeneko** [comment]
I remember complains from urhosharp guy about painful SDL migration...

2018-07-02 15:58 GMT+03:00 Rokas Kupstys <notifications@github.com>:

**Comment by weitjong** [comment]
Yup. That is one of the thing I plan to do next, upgrading to SDL 2.0.8. Perhaps it makes more sense to keep those SDL Java classes first and migrate them afterward.

**Comment by weitjong** [comment]
My PC back in business again with 16 GB on board :)
Will try to push whatever I have in the next few days for other to try out the new build system.

**Comment by weitjong** [comment]
Question: should we have a single "universal" CI build (and hence also a single universal build artifact) containing all the ABIs (armeabi-v7a, arm64-v8a, x86, and x86_64) for both Release and Debug build configs; or split them into individual ABI and build config combo as we have now? Either has pro and cons. Universal build takes much longer time build and may exceed the Travis CI job time limit or log size limit, but the universal artifact is more versatile Split ABI build can be built in parallel by Travis via separate VMs.

**Comment by sirop** [comment]
+ for splitting as time is money ;) .

**Comment by rokups** [comment]
Split build (separate jobs) for CI is fine as long as user has option to make universal build on their own. If you meant split build being separate branches - i always found this setup weird.

**Comment by weitjong** [comment]
The Gradle build system as it is now already supports both universal (by default) and split ABI (when optional “abi” property is passed to Gradle).

**Comment by weitjong** [comment]
For normal CI build I also believe the build speed is essential. So it is going to be “Split ABI” setup.

**Comment by weitjong** [comment]
I have tried a few attempts to get the Android CI working while commuting this morning. Finally got it to work. https://travis-ci.org/urho3d/Urho3D/builds/402927713

From my observation, the CI build has too much overhead, spending time to prepare the Android build environment. Also in the past there was no nice way to get the Android NDK, we have setup the urho3d/android-ndk repo for quick cloning. However, in my quick tests this morning, cloning from the "r17b-strip" took up about 1 minute, but direct downloading the ndk-bundle using SdkManager just took about 2 minutes. In other words, it does not worth the trouble to maintain the urho3d/android-ndk repo anymore.

I believe that moving those instructions to prepare the build environment to a Dockerfile to generate a docker image and have it stored in a public docker registry will remove the CI overhead. This could be done generally for all the platforms as well, not just Android. Even open up the possibility to remove our hack on Travis-build which actually does not support 'multiple doc' in .travis.yml. Any one wants to take this challenge?

**Comment by rokups** [comment]
Travis can use custom docker images? How? https://github.com/travis-ci/travis-ci/issues/7726 is still open so must be not supported.

**Comment by weitjong** [comment]
See this instead. https://docs.travis-ci.com/user/docker/

**Comment by rokups** [comment]
Oh that is cool! Im actually sort of half-way in this process here. I got crossbuild fork with urho3d dependencies [here](https://github.com/rokups/crossbuild/tree/Urho3D) and [some](https://github.com/rokups/Urho3D/blob/master/.crossbuild) [scripts](https://github.com/rokups/Urho3D/blob/master/Makefile) that build engine for linux/macos/windows(mingw) using docker container. This topic is definitely worth exploring.

**Comment by weitjong** [comment]
Successfully workaround the STATIC build config CI VM running out of disk space problem. With the Android CI properly in place now, I will be moving to the next step to properly segregate between  `urho3d-lib` module and `launcher-app` module. The former should produce a clean Urho AAR (Android Library) without *.so from samples or Urho3DPlayer. The AAR must include the "/include" directory containing our usual header files. Probably will try to publish the AAR to one of the public maven repository, so downstream can reference and add it as dependency in turn. Right. I guess I should stop planning too much ahead.

**Comment by weitjong** [comment]
It seems like there is no officially supported way for Android Library (AAR) to include the headers (and static lib, if any). At least I am not able find the documentation about it from Android Developer website. This means in order to achieve what I plan to do above, a custom Gradle task is required to "append" those extra bits into the AAR during its generation and another custom Gradle task on the dependent module is required to "extract" out those extra bits. Anyone knows better way, please let me know.

**Comment by weitjong** [comment]
Figure out how to write a custom task to append the "include" dir into the final AAR and hook it up nicely with existing tasks from Android plugin. The custom task for the extraction should not be difficult either. The difficulty, however, come from the fact that we have kind of cheating in the past, building samples at the same time when the library is being built, which does not play well with Gradle module segregation.

**Comment by weitjong** [comment]
About to experiment with moving the symlink "include" dir from CMake build tree to Gradle build tree.

**Comment by weitjong** [comment]
I believe the move pays off. With the symlink moved to Gradle build tree then the earlier hack workaround for the Android plugin is not required anymore and the "Gradle sync" on IntelliJ IDEA or Android-Studio should also just work. The new location in the Gradle build tree will also be used as the base directory for the static lib.

**Comment by weitjong** [comment]
Getting closer now to have a clean segregation. Will also try to split the assets dir two ways, "CoreData" will go to urho3d-lib (AAR), while "Data" & "Autoload" will go to launcher-app. However, I am having a little problem configuring that. Not sure it is yet another Android plugin bug that causes my "include" and "exclude" settings being ignored or that I have configured it wrongly. Other than that, the launcher-app module is able to pickup the "include" and the "lib" directory from the Gradle build tree as I want.

**Comment by weitjong** [comment]
Currently we have Rake “scaffolding” task which allows user to create a skeleton project using Urho3D as external library, however, it only does a partial job for Android platform. When the new AAR is completed as per plan, I can give the Android scaffolding another shot. The question is, should I keep using the Rake task or should I create a new Gradle “scaffolding” task just for Android platform? The latter sounds more interesting although it is more work.

**Comment by weitjong** [comment]
Commit what I have now to the branch. Forced to use asset symlink (checked in into git) because custom source set with filter does not work as expected in Android Plugin. Not sure how it would impact Windows users.

**Comment by weitjong** [comment]
I believe this `gradle-kotlin-dsl` dev branch is merge ready.
