### ISSUE TITLE
Inclusion conventions - match real filepaths?

### ISSUE THREAD

**Issue by trezanik** [urho3d/Urho3D#750]
Now, I have Urho3D building perfectly fine, no issues - but my project which uses it has issues with some of the inclusion layouts. As an example, my engine library indirectly includes inputevents.h, which has:
```
#include <SDL/SDL_joystick.h>
#include <SDL/SDL_gamecontroller.h>
// ... etc.
```
The trouble is, the folder layout is as such:
```
ThirdParty\SDL\include\xxx.h
```
There's also Connection.h, which has ```<kNet/kNetFwd.h>``` : ```kNet/include/kNetFwd.h``` - and ```<kNet/SharedPtr.h>``` : ```kNet/include/kNet/SharedPtr.h``` as an additional example. No doubt there's many others.
Because I'm using Visual Studio (linux ports kept in consideration), I'm unable to specify an 'additional include directory' because the folder path doesn't match a possible inclusion format. I see a couple of options, both with obvious drawbacks:

- Adjust all the source includes to specify ```<SDL_xxx.h>```
- symlink the headers inside the parent folder, so ```<SDL/xxx.h>``` resolves properly

Are there any plans to change the third-party inclusion names? I don't recall having this problem with 1.32, but have been away from it for a few months! I don't use CMake (I prefer to design the project files for Windows + Linux by hand, so I can learn the systems, and have non-hardcoded design), so for Visual Studio I specify my project paths inside property sheets like the below image, which enables me to switch/upgrade versions with one simple change:

![propsheet](https://cloud.githubusercontent.com/assets/7099124/8361094/ee322f60-1b25-11e5-9bd5-8b5bed0c20e0.png)

**Comment by friesencr** [comment]
CMake has a build step that copies all of the headers to the build folder.  That folder along with Urho3D/ThirdPart gets included.

**Comment by trezanik** [comment]
Ah, I see the include folder with the symlinks in there with the right design; that must be the difference from before!

Great thanks, will update my paths.
