### ISSUE TITLE
Refactor build system to support both PCH and non-PCH build

### ISSUE THREAD

**Issue by weitjong** [urho3d/Urho3D#752]
A new build option called "URHO3D_PCH" will be added. Defaulted to 1. When working with compiler that does not support PCH, the PCH build support can be disabled by setting this build option to 0.

**Comment by nemerle** [comment]
Maybe consider using cotire ? (https://github.com/sakra/cotire) It would save some work, and provide some additional features ( unity builds, automatically creating prefix header, etc )

**Comment by weitjong** [comment]
Thanks for your suggestion. I think I have come across this CMake module before but I have not used it in any of my projects, so what I am about to say next may not be accurate. IMHO, it is a little bit overkill to have dependency to other CMake modules for features that we already have or don't want to have. In my own fork, the build system already supports unity build to certain extent (and I don't believe it can be done without altering a single source code). Anyway, the unity build support is only available in my fork and not in the main repo exactly because the others don't want it to have it. It only marginally speed up the build because our build is already so fast to begin with. And that measurement was made before the PCH and ccache improvement that we made in the recent release. Going through their feature list, there is also no compelling reason why we should use it, at least to me.

**Comment by weitjong** [comment]
This branch is ready to be merged. I have taken the opportunity to reformat the code to get rid off the indents on empty lines (code convention in the docs modified accordingly), and also reorganize the includes. Also in the branch are changes for:

- Misc. fixes to perform explicit C-style cast on type mismatch.
- Misc. fixes on bugs identified by CLion's code inspection (static analyzer).

Due to the code formatting and code inspection can only be done on "compiled code", codes that are conditionally excluded (like those in Direct3D9 and Direct3D11, or platform specific ones) are being left as they are. Only the "Precompiled.h" is added to the C++ implementation file in this case.

I hope there are no regression being introduced by all these changes. I have only tested the changes on Linux platform. Let me know if there are any issues. I will probably wait to merge this branch until I got the go ahead from Lasse and probably after ```on-scene-set``` branch has been merged into ```master``` branch.

**Comment by cadaver** [comment]
On VS2013, I'm getting double definition errors:

5>d:\lasse\programs\urho3d\include\urho3d\container\../Container/Allocator.h(35): error C2011: 'Urho3D::AllocatorBlock' : 'struct' type redefinition
5>          d:\lasse\programs\urho3d\source\urho3d\container\../Container/Allocator.h(43) : see declaration of 'Urho3D::AllocatorBlock'
5>d:\lasse\programs\urho3d\include\urho3d\container\../Container/Allocator.h(49): error C2011: 'Urho3D::AllocatorNode' : 'struct' type redefinition
5>          d:\lasse\programs\urho3d\source\urho3d\container\../Container/Allocator.h(57) : see declaration of 'Urho3D::AllocatorNode'

I'll merge on-scene-set very soon.

**Comment by cadaver** [comment]
The build went further after making a clean checkout. However, on Windows the files in Graphics/Direct3D9, Direct3D11 & OpenGL subfolders need #include "../../Precompiled.h" and Revision.cpp needs #include "Precompiled.h". After these Urho3D library should build. Are these changes OK to make for Unix-like systems?

**Comment by weitjong** [comment]
These changes should be OK for Unix-like systems as well. I have also rebased the ```no-PCH-support``` branch to pull in changes from the latest master branch and force-push it to the remote branch for CI test as I speak.

Sorry that you need to perform a clean checkout again. You can also reset your existing local branch back to where it diverges and pull again as per normal. Due to the scope of the changes, it is easier for me to do a rebase then merging the changes from master branch into my branch now and then. But that would cause inconvenience to other contributors who happen to checkout the branch. In the past I would not make my local branch available in the remotely exactly for this reason. But you know the reason I am doing it like this now. It is better that than risk losing the work.

**Comment by cadaver** [comment]
Verified out-of-the-box compile of all rendering backends on Win + VS. I believe this is ready to merge. Thanks for the hard work!

**Comment by weitjong** [comment]
@cadaver I am having a little bit of problem to reproduce your success with VS and CLion on Windows host system. I can build with OpenGL just fine but not with Direct3D. Do you make other changes after you have checked out the branch? I am using VS2013 Express in a VM.

**Comment by cadaver** [comment]
You're right, debug build on VS is still broken.

The new() redefines from DebugNew.h were leaking into compilation units through an inclusion in Allocator.h and breaking placement new. DebugNew.h is "active" only in VS debug mode.

Removing the DebugNew.h include from Allocator.h should fix it.

**Comment by weitjong** [comment]
Thanks for that. I had time to boot into my actual Win7 boot partition earlier today and confirmed the build failure is not caused by my Win7 VM setup. I suspected it has something to do with DebugNew.h include statement that I removed. But I could not do much while I was there, not even a simple ```grep -P``` and so quickly shut my workstation down in disgust :smiley:.

**Comment by weitjong** [comment]
The branch is merged.
