### ISSUE TITLE
conflicted xml name for texture.

### ISSUE THREAD

**Issue by guijun** [urho3d/Urho3D#755]
steps to reproduce:
use spritepacker to generate a atlas texture,we will get: icons.png, icons.xml
the icons.xml is atlas info for icons.
try to create a xml for texture params(e.g. filter), you will find a xml with icons.xml there already.

**Comment by aster2013** [comment]
@cadaver
Because the sprite sheet file with .xml extension is generated by other tools, so it is better change the texture configuration file to another extension, like .cfg
