### ISSUE TITLE
btCompoundShape::recalculateLocalAabb() Crash

### ISSUE THREAD

**Issue by practicing01** [urho3d/Urho3D#757]
gdb backtrace:
#0  0x083d9061 in btCompoundShape::recalculateLocalAabb() ()
#1  0x0867e008 in btConvexShape::localGetSupportVertexWithoutMarginNonVirtual(btVector3 const&) const ()
#2  0x08835c65 in btGjkPairDetector::getClosestPointsNonVirtual(btDiscreteCollisionDetectorInterface::ClosestPointInput const&, btDiscreteCollisionDetectorInterface::Result&, btIDebugDraw*) ()
#3  0x0884aceb in btConvexConvexAlgorithm::processCollision(btCollisionObjectWrapper const_, btCollisionObjectWrapper const_, btDispatcherInfo const&, btManifoldResult*) ()
#4  0x08692bba in btCollisionDispatcher::defaultNearCallback(btBroadphasePair&, btCollisionDispatcher&, btDispatcherInfo const&) ()
#5  0x08692f5f in btCollisionPairCallback::processOverlap(btBroadphasePair&) ()
#6  0x0885553b in btHashedOverlappingPairCache::processAllOverlappingPairs(btOverlapCallback_, btDispatcher_) ()
#7  0x086925f7 in btCollisionDispatcher::dispatchAllCollisionPairs(btOverlappingPairCache_, btDispatcherInfo const&, btDispatcher_) ()
#8  0x0868a636 in btCollisionWorld::performDiscreteCollisionDetection() ()
#9  0x0865052b in btDiscreteDynamicsWorld::internalSingleStepSimulation(float)

```
()
```
#10 0x0864de5d in btDiscreteDynamicsWorld::stepSimulation(float, int, float) ()
#11 0x08604f04 in Urho3D::PhysicsWorld::Update(float) ()
#12 0x0860c5f8 in Urho3D::EventHandlerImplUrho3D::PhysicsWorld::Invoke(Urho3D::HashMap<Urho3D::StringHash, Urho3D::Variant>&) ()

---Type <return> to continue, or q <return> to quit---
#13 0x081e46c9 in Urho3D::Object::OnEvent(Urho3D::Object*, Urho3D::StringHash, Urho3D::HashMap<Urho3D::StringHash, Urho3D::Variant>&) ()
#14 0x081e54c0 in Urho3D::Object::SendEvent(Urho3D::StringHash, Urho3D::HashMap<Urho3D::StringHash, Urho3D::Variant>&) ()
#15 0x0838dae7 in Urho3D::Scene::Update(float) ()
#16 0x08390768 in Urho3D::EventHandlerImplUrho3D::Scene::Invoke(Urho3D::HashMap<Urho3D::StringHash, Urho3D::Variant>&) ()
#17 0x081e4692 in Urho3D::Object::OnEvent(Urho3D::Object*, Urho3D::StringHash, Urho3D::HashMap<Urho3D::StringHash, Urho3D::Variant>&) ()
#18 0x081e5d33 in Urho3D::Object::SendEvent(Urho3D::StringHash, Urho3D::HashMap<Urho3D::StringHash, Urho3D::Variant>&) ()
#19 0x083cef5d in Urho3D::Engine::Update() ()
#20 0x083cf3b3 in Urho3D::Engine::RunFrame() ()
#21 0x083c4390 in Urho3D::Application::Run() ()
#22 0x081e0cd5 in RunApplication() ()
#23 0x081aeaa0 in main ()

**Comment by cadaver** [comment]
Need information. Which kind of physics objects do you have in your scene when this happens?

**Comment by practicing01** [comment]
This happens in my game "Move: The Corridors".  When the player ( a ragdoll on a vehicle ) pushes the villain ( a capsule ) past a ramp ( box ) and the villain touches down to the floor ( box ), it crashes.  Not sure if it can happen in other instances but that one's the most easy to recreate.

**Comment by cadaver** [comment]
Ok. There are two options to realistically resolve this.

1) Make a crash reproduction project that doesn't expose any material you don't want public, upload it to dropbox etc. and link here.

2) Make a crash reproduction using your game's actual assets and send to loorni@gmail.com. Try to make it as userfriendly to run as possible (include clear instructions). This will be kept confidential.
