### ISSUE TITLE
[Editor] Lua numbers loosing precision after assigning

### ISSUE THREAD

**Issue by setzer22** [urho3d/Urho3D#758]
I'll illustrate the issue with a small example. Consider the following lua snippet in a ScriptObject that's attached to a scene node. 

function MyScript:ApplyAttributes() 
    --point_A_noideid is the node id for a node in the scene
    point_A = self.node:GetScene():GetNode(self.point_A_nodeid)
    print(self.point_A_nodeid)
    print(point_A)
end

When assigning the node id to 16777226, saving the scene and restaring, the printed value for self.point_A_nodeid is 16777200 instead (those numbers are just an example, the ones just giving me trouble actually).

Even though lua uses doubles for its internal representation to numbers, that's only half the problem. The real issue seems to be with how the editor is storing those values (which I'm guessing could be a 32 bit float?). Let me explain a bit further:

When loading the scene the following output appears in the console:

    16777200 
    nil

Also, the value displayed in the input field for the node id is 1.67772e+07.

But now comes the interesting part. If I manually drag and drop a node to the input field, the value 16777226 (the intended one) appears in the field, and the console shows:

    16777226
    userdata: 0x4011cbe0

If after that I close the scene, or just select another node in the hierarchy, the value is changed and the last two digits are lost, making the value nil in the process.

I think this is an editor bug, because information is lost somehow when de-selecting a scene node.

**Comment by cadaver** [comment]
This is not really an editor bug, but rather a poor fit of Lua and the Urho serialization system which is prepared for 32bit floats and 32bit integers. The LuaScriptInstance class (which is responsible for holding the created script object and enumerating its serializable variables) always treats Lua numbers as float type attributes.

**Comment by setzer22** [comment]
So there's no 64 bit float serialization? That explains my issue. 

Even if this is not a bug I think it limits some interesting possibilities. For example storing node ids are a great example to show the need for some fix.

**Comment by cadaver** [comment]
The proper way to fix this is to add double serialization to Variant, Serializer, XMLElement etc. I'm doing that at the moment.

**Comment by friesencr** [comment]
lua 5.3 and luajit support ints and bitwise ops.  to_lua++ is still at 5.2.

**Comment by setzer22** [comment]
Thank you for such a quick fix @cadaver!
