### ISSUE TITLE
Node::GetChildren is missing in the script API

### ISSUE THREAD

**Issue by setzer22** [urho3d/Urho3D#761]
The method Node::GetChildren seems to be not bound in the Lua API. Calling it results in a Lua runtime error and is also not on the generated documentation.

I've checked and the binding is done in Node.pkg.

**Comment by Mike3D** [comment]
It has been added recently (44d5d21bbe72fc867036bda1e39b9547784d7e0e), is used in sample [39_CrowdNavigation](https://github.com/urho3d/Urho3D/blob/master/bin/Data/LuaScripts/39_CrowdNavigation.lua) and is actually in the [LuaScriptAPI documentation](http://urho3d.github.io/documentation/HEAD/_lua_script_a_p_i.html#Class_Node).
Maybe you are using release 1.4?

**Comment by setzer22** [comment]
Oh, that's it, I was using 1.4. Sorry for the inconvenience
