### ISSUE TITLE
Terrain blend issue on Android

### ISSUE THREAD

**Issue by Mike3D** [urho3d/Urho3D#763]
Since 1.4, terrain blending seems to be broken on Android:
![device-2015-07-04-104122](https://cloud.githubusercontent.com/assets/6427048/8507270/138bf0ae-223b-11e5-93c1-c383ee9e0342.png)
![device-2015-07-04-104508](https://cloud.githubusercontent.com/assets/6427048/8507271/138e632a-223b-11e5-839a-e6d5df8f375c.png)
Top is current, bottom is before 1.4 (screenshots taken at init, top view, from sample 19_VehicleDemo).

**Comment by Mike3D** [comment]
Setting precision qualifier to mediump fixes this issue. Maybe lowp is not enough? (at least it fails on some devices).

**Comment by cadaver** [comment]
Feel free to make the change and close. I believe this was introduced because of terrain issues with Emscripten + Chrome, unless a precision was specified explicitly, but lowp certainly sounds too low for an interpolator.
