### ISSUE TITLE
No project generator for create game

### ISSUE THREAD

**Issue by yixiaoqingyuz** [urho3d/Urho3D#767]
Hi,i want to create a project with urho3d,but i found that there is no project generator to create universal project of cross-platform.

**Comment by weitjong** [comment]
I am not sure I understand your issue. We use the term 'generator' normally in the context of CMake generator. That is, we depend on CMake to configure and generate the project file(s). Most of the CMake generators (if not all) work for Urho3D. See [here](http://www.cmake.org/cmake/help/v3.2/manual/cmake-generators.7.html) for complete list of available generators.

If, however, you are asking more about "project template" then I am sorry to say we don't have any. Having said that, you may want to know that Urho3D source tree is in a way a "project template" where you can use to generate many build trees. One for each platform that you want to target.

**Comment by yixiaoqingyuz** [comment]
@weitjong 
For example,if i want to make a game run on android and ios use urho3d,now,i need to create a eclipse project for android and create a xcode project for ios,then,i need to import the urho3d library to both of the two projects by myself.

Could you offer a script to do this?because to a newcomers to urho3d this is a terrible thing to start make game use Urho3D 
Just like cocos2d-x or Gameplay3D do this.
https://github.com/gameplay3d/GamePlay
https://github.com/cocos2d/cocos2d-x

**Comment by weitjong** [comment]
I think I start to understand your issue. You are trying to create a new project to use Urho3D as external library and you want your new project to be cross-platform capable. If so then you have to read through this document [page](http://urho3d.github.io/documentation/HEAD/_using_library.html).

Basically, as part of the Urho3D project we have provided a set of CMake modules and CMake toolchains to support the cross-platform build. The Urho3D "library" uses these CMake modules and CMake toolchains so it supports the cross-platform build. So, does the Urho3D "samples". As such, your new project is no different. Just follows the steps outlined in the document page above and your project will support cross-platform build as well.

Note that, I am only referring to the build system of your project, i.e. what it capable of when it uses our CMake Modules and CMake Toolchains. Ultimately it is your own source code in your project that is really matter, i.e. your code must be portable as well. Unless you limit your project to use Lua or AngelScript only which is portable by nature.

As for the convenience script to do a new project scaffolding, we only have it in the form of rake task. It is described in the last chapter on a same document page.
