### ISSUE TITLE
[Editor] auto assign for the CollisionShape same model as StaticModel if it already exits in node

### ISSUE THREAD

**Issue by MonkeyFirst** [urho3d/Urho3D#769]
it might be usefull, less manual working
EditorScene.as
http://pastebin.com/tzbfHLLL

result
https://youtu.be/6zVl3edLtAU

**Comment by cadaver** [comment]
It's not a bad idea, but it's plausible that the user might not want this to happen automatically, so would need to be configurable. Also we need to be able to run the editor without physics compiled into Urho3D, so it should rather access the physics component via generic attribute access instead of casting as a CollisionShape.

**Comment by cadaver** [comment]
I believe the following behavior will be worth trying, as it preserves the user's agency to choose whatever shape type desired, and still avoids the need to select the model twice: when triangle or convex shape is selected from the dropdown, *and* the collision model has not been set yet, then the editor will look for a StaticModel in the same node and copy the model attribute.

**Comment by MonkeyFirst** [comment]
Yes, but it's still need to select collision shape and configure it with triangle or convex - manualy, it's not the same thing about automation on adding collisionShape to node, mb the be best solution for this will be to add editor setting(option) ?
let's say if "auto assign models to collisionShape from staticModel" will be checked (in editor preferences)- it works as I show before, and if it's no checked - it works as usual or as you say previously.

>so it should rather access the physics component via generic attribute access instead of casting as a CollisionShape.
I don't know how, my urho's scripts knowledge still bad

**Comment by cadaver** [comment]
To be honest, if your scene uses so many models where the visual and collision is the same, either they all better be very low-poly, or you're misusing the physics system. Efficiency-wise it would be preferable to use simple shapes like boxes / capsules / spheres, or compounds of them where necessary.

**Comment by MonkeyFirst** [comment]
You are right, but in most cases when i make some prototype i usual use expensive original triangulated collision mesh from static model, and only after that i make a decision to make new low-poly collider for prefab or use box collider or something else. You are also right that this might be personal preferences about  work in editor. That is a matter of taste. That why a think better way will be close this issue.

**Comment by cadaver** [comment]
Actually I'm working on the solution I proposed and will commit it soon and then close this; I don't think it will at least make matters worse, and doesn't require a separate configuration checkbox.

Another possibility would be to detect the null model on the CollisionShape C++ code level, and fetching it from the StaticModel, but that would require subscribing to the model attribute changes in case it changes later.
