### ISSUE TITLE
Starting Editor without an empty console window (enhancement)

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#771]
Editor.bat

if exist "%~dp0Urho3DPlayer.exe" (set "DEBUG=") else (set "DEBUG=_d")
if exist "%~dp0..\share\Urho3D\Resources" (set "OPT1=-pp ..\share\Urho3D\Resources") else (set "OPT1=")
if [%1] == [] (set "OPT2=-w -s") else (set "OPT2=")
start %~dp0Urho3DPlayer%DEBUG% Scripts/Editor.as %OPT1% %OPT2% %*

**Comment by MonkeyFirst** [comment]
is this only for fullscreen mode editor ?

**Comment by 1vanK** [comment]
sent pull request
