### ISSUE TITLE
[Feature request] Catmull–Rom spline path component where path lays through set of knots

### ISSUE THREAD

**Issue by MonkeyFirst** [urho3d/Urho3D#773]
Current SplinePath do not go through knots, that why I think that we need additional another component that do almost same but path lay through each knot. In future it may used by UI for animation curves in editor.

**Comment by szamq** [comment]
I'm still using my old implementation, also created pull request long time ago but it probably needs some update or polish. https://github.com/urho3d/Urho3D/pull/333

**Comment by MonkeyFirst** [comment]
Great ! I think what only I had such little problem with std Bezier spline )
it's will be great if this spline component your's or @weitjong version somehow will be introduce in urho at last :)

**Comment by weitjong** [comment]
The thing is I have lost all my local git stash and git branches in one of the late night 'rm -rf' a few months ago. I don't think my version of the Catmull-Rom implementation will see the light of the day anytime. I was too ambitious with my animation-refactoring branch then and I hesitated to push the WIP branch prematurely. Anyway, I reopen szamq's PR now. I think it needs to be rebased before Lasse could reconsider to merge it.
