### ISSUE TITLE
[Feature request] Real-Time Glow

### ISSUE THREAD

**Issue by MonkeyFirst** [urho3d/Urho3D#778]
I think this also will be a big deal if this feature will be implemented in urho

http://www.gamasutra.com/view/feature/2107/realtime_glow.php

or maybe i missed something and it already exist in engine ?

**Comment by 1vanK** [comment]
Similar postprocess effect for all screen:
RenderPath* effectRenderPath=viewport->GetRenderPath();
effectRenderPath->Append(cache->GetResource<XMLFile>("PostProcess/BloomHDR.xml"));

**Comment by MonkeyFirst** [comment]
I guess that this not the same (boom != glow). 
I already used this boom and it do some kind of overbright FX to whole rendered frame, and not for special part of image frame marked with special meshes or material.

**Comment by cadaver** [comment]
You should be able to implement the effect described in the article using the renderpath commands (e.g. making a separate RT for the glow effect, using a custom material pass to render to it, then sampling it in a shader).

Considering the small size of Urho team it may not be realistic to expect that effects such as this will have a ready-to-go implementation built-in.

**Comment by friesencr** [comment]
@MonkeyFirst I have seen your glow on the forums.  Should we put this ticket to rest?

**Comment by MonkeyFirst** [comment]
If only for a while)
Because I remember that I got some tech problems with adding glow-effect to alpha blended mats(DiffAlpha / Any transparent glow), I'm think it's probably need another additional pass to glow Render Path. And in last time I suppose what better way to solve this will be a "drop" all previously Glow based on post process and do Glow only with MRT + std shader fixes.
