### ISSUE TITLE
[Debug Render bug] Spline in Catmull-rom interpolation mode do not show full path only 2-middle points

### ISSUE THREAD

**Issue by MonkeyFirst** [urho3d/Urho3D#780]
http://savepic.su/5813792.png

**Comment by cadaver** [comment]
Maybe @szamq can clarify further, but I understood that the code uses the first and the last points for tangents, but doesn't actually move through them.

**Comment by szamq** [comment]
yes the first and last node are omitted in the path, they are used to shape the endings of the spline. If you want to have the endings in the positions of the first and the last node, you can duplicate the first and last node and add them to the spline path, or modify the code to duplicate them automatically.

**Comment by MonkeyFirst** [comment]
if spline component have all set of point maybe will be better to do copying of start and end points as internal in component ? the SplinePath are just "black box" and it must work fine without users fixes outside I guess.
