### ISSUE TITLE
FullScreen lost context bug

### ISSUE THREAD

**Issue by friesencr** [urho3d/Urho3D#782]
This is opengl / linux.
- I set the graphics on Start() to fullscreen.
- I create the scene, an get a context lost error
- The context recovers and sets the resolution to the max resolution (probably the first in the list)

The issue here is that the resolution gets forgotten and uses the default.

**Comment by cadaver** [comment]
In desktop OpenGL you can only get a context loss through your own actions, like screenmode change or fullscreen/windowed change. What are you doing when it happens? (just creating a scene shouldn't cause it, unless you have scene objects that actually call e.g. Graphics::SetMode)
