### ISSUE TITLE
Shadows are noticeably off

### ISSUE THREAD

**Issue by newbthenewbd** [urho3d/Urho3D#787]
Hi,

While testing out the engine I came across an issue with shadow mapping - the shadows are (very) noticeably off, giving a feeling the objects float on air.

This bug is exposed in every 3D C++ example of Urho3D which uses shadows, as well as my own code. I suppose it is caused by some sort of wrong handling of my totallynotancient NVIDIA GeForce 7600 GT (OpenGL 2.1.2) graphics card running on Fedora 22 with the proprietary NVIDIA 304.125 driver, and as so I attached some screenshots:
![screen1](https://cloud.githubusercontent.com/assets/1766353/8763931/f10ed5d8-2db5-11e5-8760-e117c5c533af.png)
![screen2](https://cloud.githubusercontent.com/assets/1766353/8763932/f10f8852-2db5-11e5-939e-5949063abd76.png)

Huge thanks for making and providing support for such awesome game engine!

**Comment by 1vanK** [comment]
light->SetShadowBias(BiasParameters(0.00001f, 0.5f));
(the first parameter is close to zero)
but this will cause other artifacts xD

**Comment by newbthenewbd** [comment]
Ooo, thanks! In that case I suppose it's a wontfix - have to "juggle" between better shadows and no unnecessary self-shadowing :-)
