### ISSUE TITLE
[Feature] Allow for multiple Script subsystems

### ISSUE THREAD

**Issue by setzer22** [urho3d/Urho3D#792]
EDIT: As @friesencr just pointed out, this issue only applies to Lua, as AngelScript has already a built-in better mechanism

I think the engine would benefit from separating the "Script" subsystem and the registration of the Urho3D functions. If we abstract the common behaviour from Script in a Base class (execute function, load file, ...) and then do the registration in a derived class the programmer can derive the base class with his own separate Script API sandboxed for mods. 

That way the programmer can instantiate both subsystems at the same time, one to run the game (if he choses to program the game with one of the Scripting languages) and another one to manage his custom mod API, which can be at a higher level of abstraction than the Urho engine.

What do you think of this refactor?

**Comment by friesencr** [comment]
Angelscript has an api mask. http://www.angelcode.com/angelscript/sdk/docs/manual/doc_adv_access_mask.html
My gut instinct says that multiple contexts could make things weird in cases.  The api mask keeps the context as a known singleton.  I prefer the mask approach.

**Comment by setzer22** [comment]
Then the issue becomes specific to Lua, as tolua++ has no such thing as an API mask.

 Sorry for not checking AngelScript before asking.

**Comment by cadaver** [comment]
If you plan to work on this, I recommend making it so that you can create and expose multiple Lua instances from the Lua scripting subsystem, and subclass / choose what API is exposed to them. Prefer to not actually make multiple copies of LuaScript subsystem, as Urho generally assumes that only one exists under each given Urho context.

**Comment by setzer22** [comment]
@cadaver Oh, that actually makes more sense. After looking at the code I feel comfortable enough with the Lua subsystem to implement that.

What do you suggest? Have all the functions from the script subsystem take a parameter specifying which API to use (probably defaulting to the Urho API, so compatibility with older versions is kept), or making it so the user can change the current API in use with a function call, and then all the other functions would use the "current" lua_State?

**Comment by cadaver** [comment]
I prefer the latter (though it makes LuaScript stateful, which is a bit unclean), so that existing LuaScript function signatures are changed as little as possible, and if the user does not need the feature, then nothing practically changes.

**Comment by weitjong** [comment]
@setzer22 Any update on this? I have been doing some Lua work recently and may wish to continue doing it for a while to tidy up the loose end. Hopefully my refactoring work would not affect your work by too much.

**Comment by setzer22** [comment]
Feel free to update any aspect of Lua. I started with the changes but I felt I was lacking some understanding of the Lua subsystem and left it for another day. Haven't really had much time since, so I don't think I'll be able to work on this soon.

Thanks for asking though!
