### ISSUE TITLE
EDITOR: node SCALE input make model disappear.

### ISSUE THREAD

**Issue by christianclavet** [urho3d/Urho3D#796]
While working with the editor, I've remarked this.
1. Loaded a model in the editor
2. Changed the scale values in the inspector window by inputting values directly.
3. The model disappear

If I save the scene and reload the scene the model is visible. If I slide the values using the mouse, the model doesn't disappear. It only happen when inputting values directly. If I input the values in the node scale BEFORE adding the model component, the model is visible.

Once the model have disappeared, there is no way to make it appear again, unless you reload the scene or you create another model.

**Comment by MonkeyFirst** [comment]
maybe you write step by step instruction for reproduce this ?
do you typing big negative values without changing cull mode?

**Comment by cadaver** [comment]
I suspect that at some point in the editing, the input is turned into illegal floats (NaN or infinity). Please give detailed instructions (keypress by keypress) on how to reproduce.

**Comment by christianclavet** [comment]
No. For example the default value is 1. I want to re-size smaller.
When I start typing 0.5 for example, the instant I type 0 the object dissapear, and it won't reappear when I have completed typing.

**Comment by 1vanK** [comment]
Some information from log? c:\Users\<USER NAME>\AppData\Roaming\urho3d\logs\Editor.as.log

**Comment by christianclavet** [comment]
Here is the content of the log: (After redoing it today)
[Tue Jul 28 15:56:22 2015] INFO: Opened log file C:/Users/Christian/AppData/Roaming/urho3d/logs/Editor.as.log
[Tue Jul 28 15:56:22 2015] INFO: Created 3 worker threads
[Tue Jul 28 15:56:22 2015] INFO: Added resource path C:/Users/Public/Projets/Urho3D-1.4/Sources/bin/Data/
[Tue Jul 28 15:56:22 2015] INFO: Added resource path C:/Users/Public/Projets/Urho3D-1.4/Sources/bin/CoreData/
[Tue Jul 28 15:56:22 2015] INFO: Set screen mode 1920x1018 windowed resizable
[Tue Jul 28 15:56:22 2015] INFO: Initialized input
[Tue Jul 28 15:56:22 2015] INFO: Initialized user interface
[Tue Jul 28 15:56:22 2015] INFO: Initialized renderer
[Tue Jul 28 15:56:22 2015] INFO: Set audio mode 44100 Hz stereo interpolated
[Tue Jul 28 15:56:22 2015] INFO: Initialized engine
[Tue Jul 28 15:56:23 2015] INFO: Scripts/Editor/AttributeEditor.as:301,1 Compiling UIElement@ CreateIntAttributeEditor(ListView@, Serializable@[]@, const AttributeInfo&in, uint, uint)
[Tue Jul 28 15:56:23 2015] WARNING: Scripts/Editor/AttributeEditor.as:317,48 Signed/Unsigned mismatch
[Tue Jul 28 15:56:23 2015] WARNING: Scripts/Editor/AttributeEditor.as:317,48 Implicit conversion changed sign of value
[Tue Jul 28 15:56:23 2015] INFO: Scripts/Editor/EditorResourceBrowser.as:226,1 Compiling void CreateResourceFilterUI()
[Tue Jul 28 15:56:23 2015] WARNING: Scripts/Editor/EditorResourceBrowser.as:248,23 Float value truncated in implicit conversion to integer
[Tue Jul 28 15:56:23 2015] WARNING: Scripts/Editor/EditorResourceBrowser.as:254,15 Signed/Unsigned mismatch
[Tue Jul 28 15:56:24 2015] INFO: Compiled script module Scripts/Editor.as

**Comment by cadaver** [comment]
My suspicion now is that when scale in any axis is momentarily 0, this will lead into potential troubles with the world transform matrix. Will verify shortly and possibly put an epsilon value there (ie. scale can never become exactly zero)

**Comment by cadaver** [comment]
I've pushed a check to master branch which prevents any of scale x,y,z being exactly zero, and instead forces M_EPSILON. Please check if this fixes the issue. (I've never seen the model disappearing, but I've seen Bullet complain of the AABB and removing the object from simulation)

**Comment by christianclavet** [comment]
Sorry, Took some time to figure out how to update my fork. 
Tested and now the model doesn't disappear anymore! Thanks Cadaver you fixed it!
