### ISSUE TITLE
[Feature request] EDITOR: checkbox for double sided materials

### ISSUE THREAD

**Issue by christianclavet** [urho3d/Urho3D#797]
Would be nice to be able to define a double sided material from the material editor in the URHO3D editor...

**Comment by MonkeyFirst** [comment]
try to set cull mode to none
option in material editor http://savepic.ru/7652023.png

**Comment by christianclavet** [comment]
Sorry. Culling will effectively hide back faces... Putting it to none will have back faces rendered. Just used to another term in other software...
