### ISSUE TITLE
[EDITOR] Icons alpha clipping issue

### ISSUE THREAD

**Issue by christianclavet** [urho3d/Urho3D#799]
Hi, I've just remarked that icons alpha transparency "work", but is not doing it smoothly. As it was "clipped" when there should be a gradation of transparency.

I've found the original PNG image and put a dark background to compare it to the icons in the runtime of the editor. If you look inside Photoshop, the icons borders are smooth, but they are not in the editor (pixelated borders). I think it's related on how the alpha channel is processed. Right now it's seem to clip (0/1) when it should put a transparency value of the alpha (0/255).

You might have to zoom in to view the difference...

![image](https://cloud.githubusercontent.com/assets/13395943/8897799/7007c294-33e9-11e5-997f-c5953bfd6894.jpg)

**Comment by MonkeyFirst** [comment]
Could you share this fixed UI texture, for test ?
Actually i don't see a difference on my monitor, i'm already have a smooth contours on icons. but on yours picture it's have weird crappy contours, yeah.

**Comment by 1vanK** [comment]
Same problem on my PC

**Comment by cadaver** [comment]
What render API are you compiling Urho3D with, and what is your GPU model? I don't think I've ever seen this issue, so it looks like the UI shader is sampling the texture incorrectly in your specific configuration.

**Comment by 1vanK** [comment]
This problem is for both API: OpengL and DirectX,

When I force BLEND_ALPHA for UI elements in constructor
```
UIBatch::UIBatch(UIElement* element, BlendMode blendMode, const IntRect& scissor, Texture* texture, PODVector<float>* vertexData) :
    element_(element),
    blendMode_(BLEND_ALPHA),
```
problem was resolved. So I think in some place blendMode_ is not assigned. But it is strange, that the problem does not exist on all configurations.

**Comment by cadaver** [comment]
Please test if that commit has any effect. I couldn't see uninitialized blendMode_ values, however there's floating point math related to whether BorderImage should automatically use alpha blend, it's safer to request it explicitly.

**Comment by 1vanK** [comment]
It works

**Comment by 1vanK** [comment]
It's late, but I found cause :) When "User Interface Maximum opacity" in settings == 1, then GetDerivedOpacity() == 1 in
```
    if (GetDerivedOpacity() < 1.0f || color_[C_TOPLEFT].a_ < 1.0f || color_[C_TOPRIGHT].a_ < 1.0f ||
        color_[C_BOTTOMLEFT].a_ < 1.0f || color_[C_BOTTOMRIGHT].a_ < 1.0f)
        allOpaque = false;
```

**Comment by christianclavet** [comment]
Yes. I have my panels opaque too (Maximum opacity = 1). How could this affect icons?

**Comment by 1vanK** [comment]
icons inherit the opacity of interface
