### ISSUE TITLE
Incorrect centering when used SDF font

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#801]
![incorrectcentring](https://cloud.githubusercontent.com/assets/13021826/8928788/dd63a22e-3531-11e5-9b1e-567e6b7814f5.jpg)

**Comment by 1vanK** [comment]
Another bug:
If change font from sdf to ttf or vice versa from ttf to sdf 

![incorrectcentring](https://cloud.githubusercontent.com/assets/13021826/8928955/f864784a-3532-11e5-8322-ab48f54f7675.jpg)

If clear text and input it again, the text will look normal

**Comment by cadaver** [comment]
This seems to be an error in the included sdf data files; the line height reported in the font files is much less than the character glyphs' heights. I'll push a fix.
