### ISSUE TITLE
Crash when SharedPtr in global space

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#802]
I'm not sure that this is a bug. Maybe it is an unacceptable use.
When SharedPtr declared in a global space
```
SharedPtr<Material> BlackBallMaterial;

static void CreateBallMaterials(ResourceCache* cache)
{
    Material* ballMaterial = cache->GetResource<Material>("Materials/Ball.xml");

    SharedPtr<Material> newMaterial(ballMaterial->Clone());
    newMaterial->SetName("BlackBall");
    newMaterial->SetShaderParameter("MatDiffColor", Color::BLACK);
    cache->AddManualResource(newMaterial);
    BlackBallMaterial = newMaterial;
}
```
it works normally as long as a application does not begin to close. But when I close the application arise a exception in string 
```
// HashBase.h

unsigned NumBuckets() const { return ptrs_ ? (reinterpret_cast<unsigned*>(ptrs_))[1] : 0; }
```

**Comment by 1vanK** [comment]
P.s. I know that here should be used
```
Material* BlackBallMaterial;
```
but maybe this bug requires fixes.

**Comment by cadaver** [comment]
Will verify this, but the requirements of Urho Object subclasses (like Material) is that the Context object should be first to be created and last to be destroyed. When a Material is left in the global scope after the destruction of the context, this rule is violated and the material (or some other objects it owns) likely tries to access the now nonexistent context as part of its own destruction.

**Comment by cadaver** [comment]
Verified that this is an attempted access to Context at the object's eventual destruction time.

The usual, proper way to safeguard access to objects that may be destroyed (in this case the Context) is to use a WeakPtr, however this would induce a reference counting overhead, and program operation would likely be screwed up anyway, so in this case it isn't used and it's up to the programmer to follow the "delete Context last" rule.
