### ISSUE TITLE
DiffUnlit & DiffUnlitAlpha strange behavior

### ISSUE THREAD

**Issue by MonkeyFirst** [urho3d/Urho3D#808]
this is just std scenes with cubes. DiffUnlit 
http://savepic.ru/7732554.png

DiffUnlitAlpha also have a strange object overlap or z-ordering switching during camera move

**Comment by 1vanK** [comment]
http://s017.radikal.ru/i409/1507/14/aefacdce2c1d.jpg

**Comment by MonkeyFirst** [comment]
DX11?

**Comment by 1vanK** [comment]
OpenGL

**Comment by cadaver** [comment]
I'm not seeing anything unusual with DiffUnlit technique on D3D11 (Nvidia GPU.) On transparent materials sorting problems can be expected depending on the geometry, as the sorting is per-object.

**Comment by MonkeyFirst** [comment]
it's must be some kind irregular bug i'm trying now again and i'm too not see this with DiffUnlit. (too Nvidia GPU)

>On transparent materials sorting problems can be expected depending on the geometry, as the sorting is per-object.

ok
