### ISSUE TITLE
Event handlers

### ISSUE THREAD

**Issue by MonkeyFirst** [urho3d/Urho3D#810]
I guess I found a bug 
if you try open color wheel(alt+w) and assign some color for object and then open the layer editor (m-key) do something with layers and when again open color wheel it would not be working because it lost handler assigning I guess. And that why I'm  just curious how many handlers may have one same global event?
 
layer use own handlers for catch global events
    SubscribeToEvent("MouseMove", "HandleHideLayerEditor");
    SubscribeToEvent("MouseButtonDown", "HandleHideLayerEditor");
    SubscribeToEvent("MouseWheel", "HandleMaskTypeScroll");

color wheel also use it's own handlers for it's own use
    SubscribeToEvent("MouseMove", "HandleMouseMove");
    SubscribeToEvent("MouseButtonDown", "HandleMouseButton");
    SubscribeToEvent("MouseWheel", "HandleMouseWheel");
    SubscribeToEvent("KeyDown", "HandleKeyDownWheel");

Actually i'm already solve this issue with produce second layer of global event (catch global events and send they as MouseMove2, MouseWheel2 and so on...) for both color wheel and layer editor. but it's no looking good i guess.

**Comment by cadaver** [comment]
Normally Urho events are always received by objects. The editor is mostly a procedural-style program which consists of a lot of free functions and very few objects. This is not ideal coding style, as in this case you need to understand that the script file itself is the event receiver object, and in this case you can only have only one free function from the script file bound to a specific event, at a time, and subscribing another free function handler overwrites the previous like you observed.

If the subscriber functions would be in different script objects then there would be no problem to have several handler functions at the same time, but note that the reception order is not well-defined (probably first subscribed receives event first) and depending on the exact use it can lead to convoluted program logic and UI interaction bugs.
