### ISSUE TITLE
uiRoot->SetVisible(false) don't works

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#811]
I try to hide all UI with 
```
UIElement* uiRoot = GetSubsystem<UI>()->GetRoot();
uiRoot->SetVisible(false);
```
but it don't works. It is some inner restriction?

**Comment by MonkeyFirst** [comment]
I remember what I have a same problem with hiding all UI at once.
but then I wrote this code : http://pastebin.com/syPj3tPc

**Comment by weitjong** [comment]
I could be wrong but the last time I check the UIElement's Visible property is not transitive from parent container to its children. So, setting it to false at the UI root has 0 effect on its children. You have go through the children list and set their visibility individually as pointed out by @MonkeyFirst. You can also look at how it is done in the Editor in [these lines](https://github.com/urho3d/Urho3D/blob/master/bin/Data/Scripts/Editor/EditorUI.as#L1551-L1575).

**Comment by cadaver** [comment]
It should be desirable to make it propagate. The editor is probably the biggest user of the UI so far so I can test if anything breaks, and whether it's easily fixable, or whether the lack of propagation is actually used as a critical "feature".

**Comment by OvermindDL1** [comment]
Could override it to add a two argument setVisible to pass in both isVisible as well as a doPropogate, defaulted to false.

**Comment by cadaver** [comment]
We may want to have some elements hidden e.g. in a window's hierarchy and not make them become visible when the whole window is shown, which would require tracking the self visibility and hierarchy visibility separately.

**Comment by cadaver** [comment]
Actually the visibility already propagates to children (wrote so long ago that didn't remember :)), this just doesn't extend to the root element, which is trivial to add. Will add a new IsVisibleEffective() function that will check the hierarchy visibility, and also need minor tweaks to ensure that the focus is disabled from a hidden element if it's deep in the child hierarchy.

**Comment by 1vanK** [comment]
Good news :)
