### ISSUE TITLE
Invisible controls receive keyboard events

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#819]
```
uiRoot->AddChild(window_);
window_->AddChild(button);
SubscribeToEvent(button, E_RELEASED, HANDLER(Game, HandleButtonPressed));

void Game::HandleButtonPressed(StringHash eventType, VariantMap& eventData)
{
    // some actions
    window_->SetVisible(false);
}
```

If you press the button, perform some action, and the window will by hidden. If you then press the spacebar, some actions are performed again, because button remains focused.

Example: https://github.com/1vanK/Urho3D-Color-Lines
Select game difficulty and press SPACE - game will be restarted.

**Comment by MonkeyFirst** [comment]
maybe this just pass for user control ?
I mean maybe you for some reason needed event from ghost control, and  if you don't need that you just making "barricades" with IF( visible && got event) { do something with event target }

**Comment by 1vanK** [comment]
may be event processing is needed, but, i think controls must lose focus when invisible

**Comment by Mike3D** [comment]
Maybe this is related to #523
