### ISSUE TITLE
Improve Lua binding for Variant and VariantMap classes

### ISSUE THREAD

**Issue by weitjong** [urho3d/Urho3D#820]
I am not an expert in Lua but it appears to me that there are code repetition in the bindings for these two classes. I suppose one could use Lua metamethod to handle ```__index``` event to return a Variant from a VariantMap and so those getter and setter bindings are only required for Variant class. Currently we have an incomplete bindings and yet those incomplete bindings are repeated in two places.

**Comment by cadaver** [comment]
The VariantMap different API in Lua has been a long-standing annoyance, so this would be great to fix.

**Comment by weitjong** [comment]
Finally I found a way to do it. I cannot find existing hook in tolua++ library to set this up, so I have to come up with some makeshift solution to register the custom metamethod to handle the index event as I proposed above. What makes this complicated is tolua++ library itself has also already registered that metamethod for its own use, so I am forced to overwrite it, but just for the VariantMap class.

It may be not the best solution as I am not the best person to do this, but I think it can be improved and corrected by the true expert later. I think I will just commit my changes into the ```database-connection``` branch as I need this change there now. However, be warned that the changes will break all the existing Lua samples.

Instead of (the old way)
```
local numCols = eventData:GetUInt("NumCols")
```
The new way will be (similar to how it is done in C++ and AS)
```
local numCols = eventData["NumCols"]:GetUInt()
```

**Comment by cadaver** [comment]
No problem, these can be fixed in time, and the new way looks much nicer.

**Comment by weitjong** [comment]
I am able to remove all of the Lua bindings for the VariantMap class in the Variant.pkg. The bindings are only exists in the Variant class as it should be. I am now attempting to remove all the binding for the setter methods in the Variant class by using a new metamethod to handle ```__newindex``` event. So, instead of
```
eventData["Filter"]:SetBool(true)
```
It will be just (again similar to how it is done in C++ and AS)
```
eventData["Filter"] = true
```
For this to work, I need to bind lua_Object (which is type less) to our Variant value in a generic manner. I think it can be done.

**Comment by weitjong** [comment]
@cadaver Is there any particular reason why Matrix classes are being stored differently in Variant class? The rest of the math classes pointer is stored in ```&value_```, while Matrix classes pointer is stored in ```value_.ptr_```.

**Comment by weitjong** [comment]
I am still attempting to implement the __newindex Lua event handler so it can map Lua usertype object back to Variant class. In the end of the day, we should be able to things like:
```
local vector2 = Vector2:new_local(3, 4)
eventData["test"] = vector2    -- the C++ event handler will infer the type automatically
print(eventData["test"].typeName)  -- output: Vector2
print(eventData["test"]:GetVector2():Length())  -- output: 5
```
I think I am able to do this for all the math classes without even have to know how the C++ Variant class stores them internally (so @cadaver, you can ignore my above question, am still wondering though :smiley:).

**Comment by cadaver** [comment]
@weitjong Variant tries to avoid heap allocation if it can. Quaternion & Vector2-4 can fit into the VariantValue, so they're stored directly. The matrices will need more space (9-16 floats), so they're necessarily heap allocated and the pointer stored.

**Comment by weitjong** [comment]
Thanks Lasse. I think I got it. So only those fit into the 16-bytes of VariantValue are stored directly.
