### ISSUE TITLE
SpritePacker Empty Space

### ISSUE THREAD

**Issue by practicing01** [urho3d/Urho3D#821]
Hello, I found this sprite sheet on opengameart.org http://img.ctrlv.in/img/15/08/03/55bfc9e6950e3.png and ran it through the SpritePacker tool and got this: http://img.ctrlv.in/img/15/08/03/55bfc9c70fa77.png The frames are 32x32 which is evenly divisible into 1024 so I don't think there should be an empty space at the far right.

Edit:  I didn't run the sheet, I ran the frames extracted from the sheet, using gimp.

**Comment by friesencr** [comment]
The Downloaded Image is 320x320.  The nearest power of 2 is 512x512 which is 262,144.  SpritePacker Image is 1024x128 which is 131,072.

**Comment by practicing01** [comment]
Oh I see, it wants resolutions by power of 2, my mistake.
