### ISSUE TITLE
Terrain Occlusion Culling Issue

### ISSUE THREAD

**Issue by OldSnake22** [urho3d/Urho3D#822]
Hello, 

Here is a video so you can see this issue. When the terrain slope is quite high you can observe those culling issues.

https://www.youtube.com/watch?v=RWc668dJf2o

Terrain is set to be occluder and occludee. The terrain patch size is 32. 

Do i need to change some parameters or is it a bug ? If yes i hope it can be fixed because it is quite important for an openworld game with terrain to have a working occlusion culling :)

**Comment by cadaver** [comment]
It is a bug related to optimization to reduce the triangle count. The terrain occlusion is drawn with the minimum terrain LOD to reduce the amount of rasterized triangles. There is some fiddling involved to correct the possible error that happens this way, but it appears to not be sufficient, or correct, in this case. It should be fixable.

**Comment by OldSnake22** [comment]
Thank you cadaver, it would be great to have a working culling on the terrain as it help the framerate a lot ! :)

**Comment by friesencr** [comment]
I think I noticed that this code wasn't threaded.  Would cutting up the occluders per thread and merging the occlusion buffer in the end be faster?

**Comment by cadaver** [comment]
That's a good idea, as the final result is not a lot of data (256x something) it shouldn't take a lot of time to simply merge the closest depth value of all.

**Comment by OldSnake22** [comment]
Oh nice ! Looks like we will have a bugfix and a new feature ;) 
Cadaver, do you think you will be able to push the fix this week ?

**Comment by cadaver** [comment]
I haven't looked into it yet seriously. No promises to timetable.

**Comment by cadaver** [comment]
This fix slows down the terrain geometry generation slightly (140ms vs 150ms for Water example on my test machine)
