### ISSUE TITLE
Terrain Occlusion Culling not working since #822 bugfix

### ISSUE THREAD

**Issue by OldSnake22** [urho3d/Urho3D#825]
It seem that the terrain culling bugfix pushed one hour ago has broken the system :)

I have set the fill mode to wireframe to see the culled objects and terrain patches and it behave strangely now. Most of the time depending on the camera position, it's not culling anything even if the objects are very clearly obstructed by the terrain.

**Comment by cadaver** [comment]
It is rather conservative now. Imagine you have 4 LOD levels in the terrain. This means at lowest it will render vertices 0, 8, 16... For occlusion, it takes the minimum height between all those points, so if you're using much LOD levels, the coarsest level will lose almost any detail and be very flat for occlusion, which means it will not occlude well.

I verified that in the Water scene the occlusion still works.

**Comment by OldSnake22** [comment]
What is the function to use for limiting the number of generated LODS please ?

**Comment by cadaver** [comment]
Sorry, forgot that it isn't configurable, but is clamped to max 4, which shouldn't be too bad for occlusion yet. Can you share heightmap data and terrain setup code for testing?

**Comment by OldSnake22** [comment]
Alright so i have made a video to show you the result on my machine: https://www.youtube.com/watch?v=ah9OkJfPPLY

As you can see i think that using the last LOD with such terrain relief is not good. Maybe the perfect solution would be to make the terrain LOD used for culling configurable with a function ? :)

Here is the heightmap image: http://i.imgur.com/KQ6hrPQ.png
The image size is 1025x1025

And my parameters: 
m_pTerrain->SetPatchSize(64);
m_pTerrain->SetSpacing(Vector3(4.0f, 1.0f, 4.0f));
m_pTerrain->SetOccluder(true);
m_pTerrain->SetOccludee(true);

**Comment by cadaver** [comment]
Thanks. Will investigate.

Setting a higher occlusion LOD level is a possibility (and it will effectively happen if you set a lower number of LODs total) but I imagine it will blow through the occluder triangle budget rapidly, so you have to increase it from the Renderer.

I'm probably being overconservative with the occlusion height reduction algorithm, it should actually be necessary to check only half of the vertex neighborhood I'm checking now.

**Comment by cadaver** [comment]
There were legitimate bugs (small holes) which would result in partially broken occlusion. You can also now change the occlusion LOD level.

**Comment by OldSnake22** [comment]
Working perfectly now ! Thanks for being so fast.
