### ISSUE TITLE
Texture Mipmap rendering bug (recently introduced bug)

### ISSUE THREAD

**Issue by OldSnake22** [urho3d/Urho3D#826]
I have a rendering problems with my texture since i am using the lastest revision of Urho.

http://i.imgur.com/48MDNXE.jpg

As you can see it seem that only the first mipmap is rendered on my DDS textures (DXT5) i need to get very close to those trees bark to see the texture.
Maybe this bug was introduced with Sinoid changes related to DDS textures ? 

Here is what the log say: 

[Wed Aug  5 18:55:16 2015] ERROR: Compressed level is outside image data. Offset: 524288 Size: 131072 Datasize: 611696
[Wed Aug  5 18:55:16 2015] ERROR: Null source for setting data
[Wed Aug  5 18:55:16 2015] ERROR: Compressed level is outside image data. Offset: 524288 Size: 131072 Datasize: 611696
[Wed Aug  5 18:55:16 2015] ERROR: Null source for setting data
[Wed Aug  5 18:55:16 2015] ERROR: Compressed level is outside image data. Offset: 524288 Size: 131072 Datasize: 611696
[Wed Aug  5 18:55:16 2015] ERROR: Null source for setting data
[Wed Aug  5 18:55:16 2015] ERROR: Compressed level is outside image data. Offset: 524288 Size: 131072 Datasize: 611696
[Wed Aug  5 18:55:16 2015] ERROR: Null source for setting data
[Wed Aug  5 18:55:16 2015] ERROR: Compressed level is outside image data. Offset: 524288 Size: 131072 Datasize: 611696
[Wed Aug  5 18:55:16 2015] ERROR: Null source for setting data
[Wed Aug  5 18:55:16 2015] ERROR: Compressed level is outside image data. Offset: 524288 Size: 131072 Datasize: 611696
[Wed Aug  5 18:55:16 2015] ERROR: Null source for setting data
[Wed Aug  5 18:55:16 2015] ERROR: Compressed level is outside image data. Offset: 524288 Size: 131072 Datasize: 611696
[Wed Aug  5 18:55:16 2015] ERROR: Null source for setting data
[Wed Aug  5 18:55:16 2015] ERROR: Compressed level is outside image data. Offset: 524288 Size: 131072 Datasize: 611696
[Wed Aug  5 18:55:16 2015] ERROR: Null source for setting data
[Wed Aug  5 18:55:16 2015] ERROR: Compressed level is outside image data. Offset: 524288 Size: 131072 Datasize: 611696

**Comment by cadaver** [comment]
That looks like something that shouldn't be ever happening with a valid DDS file. Can you share the image? (you can scramble the content, the important bit is that the header is similar and the bug happens)

**Comment by OldSnake22** [comment]
Here is the texture: https://mega.co.nz/#!S9QUAKxK!ZZtcB8pVCo9hmhu-4Xeu3S-g_gdiiyry9dqfcvjpRKE

Every texture have not been changed and were working perfectly before i compiled the latest revision of Urho. I am using visual studio 2015 RTM and compile in 64 bits.

**Comment by OldSnake22** [comment]
Also i can confirm that is it only affecting DDS textures

**Comment by cadaver** [comment]
Thanks, reproduced using the file.
