### ISSUE TITLE
Engine crashes on Intel HD Graphics/OpenGL build (Win 7 x64)

### ISSUE THREAD

**Issue by rasteron** [urho3d/Urho3D#827]
I got to compile this again with my Core i3 laptop with Intel HD on board. All went well and when I try to run snow war and Editor, I got a weird camera angle and blue background on snow war and the editor crashes after loading.

Compiled using MinGW/Codeblocks

I also got a copy of an older engine version and it works without any issues.

**Comment by cadaver** [comment]
Try -gl2 startup parameter to run with GL2 like before. It tries to default to GL3 but it's kind of hard to know if the driver will crash as a result of that, if it says that GL3 is supported, unless we setup blanket rules like "use GL2 for Intel" which would not be nice either.

**Comment by rasteron** [comment]
Same problem, it's really weird. I will try to update my driver and have a look-see..

**Comment by cadaver** [comment]
You may have to debug inside Urho to see the exact crash point / reason, since it's unlikely someone else can replicate your specific problem. I remember I had to update the Intel driver to get correct rendering on GL3, but don't remember crashes.

**Comment by cadaver** [comment]
One thing came to mind that has tripped some users: make sure you don't have .pak files or other data files from old versions lying around.

**Comment by friesencr** [comment]
I wonder if pak files with matching directories should generate a log warning.

**Comment by cadaver** [comment]
It would be printed during the startup (no console, no rendering yet) so I suppose people could still miss it. The directories and packages actually used by the engine are logged on startup.

**Comment by rasteron** [comment]
Yep, works great now after updating the driver! :blush:
