### ISSUE TITLE
Console/engine throwing XML parse errors, but can read Open Type Fonts (.otf)

### ISSUE THREAD

**Issue by rasteron** [urho3d/Urho3D#830]
I'm getting this error in the console when trying to load OTF fonts.

**Comment by cadaver** [comment]
This is the Resource Browser interpreting all file extensions it doesn't know (except those in an exclusion check) as xml, and failing. OTF are binary so this doesn't make sense. It probably would be better to check for the extensions that *are* supposed to be xml, as there's only a few of them, usually it's just ".xml".
