### ISSUE TITLE
Error with 64bit build on windows

### ISSUE THREAD

**Issue by dragonCASTjosh** [urho3d/Urho3D#831]
Not sure whats causing the issues. it looks to be LibCpuld that is causing the main problem.
as for my operating system I'm running 64bit windows 10.

![capture2](https://cloud.githubusercontent.com/assets/3044415/9231238/0f9555be-411f-11e5-90de-09d4764becf7.PNG)

**Comment by cadaver** [comment]
What Visual Studio version?

**Comment by dragonCASTjosh** [comment]
2015

**Comment by cadaver** [comment]
Thanks. We haven't done much testing on it, except for me preliminarily doing some AngelScript modifications to make it compile. Just for the moment I recommend to use 2013.

**Comment by dragonCASTjosh** [comment]
32bit build work fine on vs2015 so i guess i will stick to that until i get find other problems

**Comment by cadaver** [comment]
It is likely the assembler being more strict than before (there's no inline asm in 64bit VS, so it actually has to invoke the assembler). Might be an easy fix, but we'll see.

**Comment by dragonCASTjosh** [comment]
hopefully its nothing to bad. Ill keep my eye out for any other issues

**Comment by friesencr** [comment]
I had an intermittent build issue with LibCpuld a few years back.  I bumped the library and it helped.

https://github.com/anrieff/libcpuid/commit/2834683640a6c3d7c54010bbc1f00e46de794af3

**Comment by cadaver** [comment]
I could not reproduce the errors in Visual Studio 2015 Community, version 140.0.23107.0 D14REL, with x64 build (either debug or relwithdebinfo).

The error should be reported when the assembly code fails to specify the segment where the instructions should be placed. Both LibCpuId & AngelScript have a .code specifier in their asm files, so it looks like something odd is going on, and the libraries are not at fault.

**Comment by dragonCASTjosh** [comment]
ill investigate some more on my end

**Comment by dragonCASTjosh** [comment]
Found the problem to be with cmake, I had to use cmake_GUI to manually select visual studio 2015 64x build target. It looks like 32bit and 64bit builds are new separate build targets

**Comment by weitjong** [comment]
In that case then VS 2015 behaves the same as prior VS version in regards to 64-bit Windows build. CMake provides 64-bit and 32-bit generators separately and CMake-GUI user is the one supposed to choose which generator to use. If you look at the Urho3D provided CMake CLI batch file then you can see it is not much different there. You can have to specify URHO3D_64BIT=1 early on in order to generate a 64-bit solution.
