### ISSUE TITLE
Box2D in Editor: dynamic bodies don't work

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#837]
1) Create object with RigidBody2D with type Kinematik - it's falling.
2) Create object with RigidBody2D with type Dynamic - it's not falling.
3) Load this scene in program - object is not falling.
4) If after loading in porgram make:
```
Node* node = scene_->GetChild("ObjectName", true);
RigidBody2D* body = grenadeNode->GetComponent<RigidBody2D>();
body->SetBodyType(BT_DYNAMIC);
```
object is falling.

**Comment by cadaver** [comment]
Urho3D serializable enums must start from 0 and increment. RigidBody2D doesn't respect this, so you're actually setting dynamic when choosing kinematic in the editor, and vice versa. Fortunately this is an easy fix.

**Comment by 1vanK** [comment]
do you mean that?
```
enum b2BodyType
{
	b2_staticBody = 0,
	b2_kinematicBody,
	b2_dynamicBody

static const char* bodyTypeNames[] =
{
    "Static",
    "Dynamic",
    "Kinematic",
    0
};
```

**Comment by cadaver** [comment]
Yes, the Box2D define values don't match the enum strings currently in increasing fashion.

**Comment by 1vanK** [comment]
thank :)
