### ISSUE TITLE
Missing ViewMask for StaticSprite2D in the Editor

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#843]

**Comment by cadaver** [comment]
The 2D rendering system is somewhat of a different beast to regular scene rendering, in the interest of optimization and sprite batching the Renderer2D handles culling for the 2D objects in a centralized fashion, and seems it doesn't take into account the objects' viewmasks.

**Comment by 1vanK** [comment]
I need it for raycast :(  Also question: For whatever reason, it does not fall to the side? Just down

![1](https://cloud.githubusercontent.com/assets/13021826/9285244/038cce32-42f5-11e5-91de-22beeec57f95.jpg)
