### ISSUE TITLE
Fixed Rotation bug

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#844]
1) Create Node with RigidBody2D in Editor. Default Fixed Rotation is uncheked. But it's not working. (Objects do not rotate when falliing).
2) Check Fixed Rotation and unchek it again. All works normally.
3) Save scene and reload it. Again is the problem.

**Comment by 1vanK** [comment]
Node: this bug reproduced when "Use fixture mass" is unchecked and mass is set manually

**Comment by cadaver** [comment]
In case "Use fixture mass" is false, also the inertia is manually set. No rotation would point to inertia becoming very large or otherwise illegal so that the bodies don't get to rotate at all.

**Comment by 1vanK** [comment]
I think that the reason is different
1) I set inertia manually (same value as that of "Use fixture mass"), save and load scene - nothing has changed
2) Check / Uncheck "Fixed rotation" resolved problem and it working even inertia = 0

**Comment by 1vanK** [comment]
This is test scene:
http://pastebin.com/2uXS8WiM
1) Open and run - cube does not rotate
2) Open it again, check and unchek "Fixed rotation" and run - cube is rotating

**Comment by cadaver** [comment]
There are some Box2D behind the scenes operations going on, which desync the Urho rigidbody's state (as well as mistaken boolean logic in if statements in our code), it's actually resetting the custom mass at certain points, for example when adding or removing shapes.

**Comment by cadaver** [comment]
Note that your test scene will need adjusting inertia to non-zero before it works. Previously it was working by mistake.

**Comment by 1vanK** [comment]
Thank you!
