### ISSUE TITLE
[Feature] Unlit material with shadows

### ISSUE THREAD

**Issue by rasteron** [urho3d/Urho3D#845]
It's not common but still a good addition to the materials. Perhaps, something like this?

http://www.polycount.com/forum/showthread.php?p=2325341

**Comment by rasteron** [comment]
More reference here..

https://answers.unrealengine.com/questions/53579/possible-for-unlit-material-to-receive-shadows.html

**Comment by cadaver** [comment]
Urho3D has no modulative shadows, so doing "unlit shadows" by letting the diffuse term stay at 1 regardless of light direction or attenuation, then applying the shadow map, would cause over-illumination as soon as there would be multiple lights affecting the object.

**Comment by MonkeyFirst** [comment]
Is shader knows how many light around it ?
maybe devide diffColor and shadow factor by count of lights for additive light pass where sum of all divided are = 1
something like
diffStep = diff / lightCount
shadowStep = shadowPower / lightCount
diffStep *= shadowStep
finalColor += diffColor * diffStep

**Comment by cadaver** [comment]
Afraid it's not that simple, as there may or may not be optimization that disables lights (for example point lights) outside their range by stencil masking their volume. So you would need to know per-pixel whether a light is being applied, instead of just per-drawcall.

**Comment by cadaver** [comment]
Something that may be applicable is the LitParticle shader (see for example the DiffLitParticleAlpha technique, should be adaptable to also non-alpha materials), which is used in the decals sample. That's directionless lighting, not true unlit, which takes into account attenuation and shadows, so it should work with multiple lights.

**Comment by rasteron** [comment]
Ok, I now see that this is a bit of a stretch, particularly in my case. I did somehow manage to create a workaround by adjusting the ambient light and make the object more appealing on the darker side. Anyway, it would still be handy to have something like this on future setups. 

Thank you for this information Lasse, and thanks again MonkeyFirst for the shader code that you have provided. :smiley: cheers
