### ISSUE TITLE
Screen joystick KeyMap "UP DOWN LEFT RIGHT" mnemonics lead to 'RQPO' keys in KeyDown

### ISSUE THREAD

**Issue by carnalis** [urho3d/Urho3D#847]
Steps to reproduce:
In Data/UI/ScreenJoystick_Samples.xml, change "WSAD" to "UP DOWN LEFT RIGHT". Run a sample with -touch. Clicking UP results in input.keyDown[KEY_R], etc.

I took some time trying to hunt down the issue, and guess 'RQPO' could result from using the SDL scancodes (82,81,80,79) as keycodes.

This seems unrelated, but I was curious about the (char) cast from int here:
https://github.com/urho3d/Urho3D/blob/master/Source/Urho3D/Input/Input.cpp#L788

**Comment by weitjong** [comment]
I think it is a bug. The explicit cast to char is not directly related to this problem, but at least it already tells there is a problem of storing keybinding using String (array or char). It only works for "WSAD" but not "UP DOWN LEFT RIGHT" which get mapped to KEY_UP, KEY_DOWN, KEY_LEFT, KEY_RIGHT which does not fit into a char data type.
