### ISSUE TITLE
Variants set from a number in Lua default to VAR_DOUBLE

### ISSUE THREAD

**Issue by JTippetts** [urho3d/Urho3D#851]
If you, for instance, write the line of code vm["key"]=node:GetID() in Lua script as part of an event being sent, if the receiver of the event is C++ code, then the value of "key" must be read back using vm["key"]:GetDouble() then cast to unsigned int for use as a node ID. Similarly, any numbers set to a variant in Lua will default to a type of VAR_DOUBLE. If you try to read it back using GetUInt() the method returns 0.

I understand why this is (Lua only knows about doubles) but it's still kind of inconvenient and bug prone.

What about a change to the various GetDouble, GetFloat, GetInt, GetUInt methods of Variant that will perform appropriate casting as needed? ie, a Variant can be set to a VAR_DOUBLE type, but calling GetUInt() on it will perform a cast on the stored double value and return the casted value, rather than defaulting to returning 0 because it's not the right type?

I know this really isn't an optimal solution either (prone to all the possible errors that can be introduced from casting between types of different bit sizes) but it might be better than the current default of returning 0.

What think you all?

**Comment by cadaver** [comment]
I believe it's reasonable to make the conversions. Variant is not exactly meant for high-speed data passing so the overhead should not be a problem.
