### ISSUE TITLE
(FEATURE REQUEST) Using .asc file if .as is missing

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#864]
After compiling scripts
```
ScriptCompiler.exe GameData/Scripts/*.as
```
the user must rework all the scripts
```
node.CreateScriptObject("Scripts/MyScript.as", "MyScript"); -> node.CreateScriptObject("Scripts/MyScript.asc", "MyScript");
```
and all the scenes
```
<attribute name="Script File" value="ScriptFile;Scripts/Cannon.as" /> -> <attribute name="Script File" value="ScriptFile;Scripts/Cannon.asc" />
```
It is very inconveniently.

**Comment by cadaver** [comment]
There is nothing magic in .asc extension, so you could have prepared a build of your application by compiling the scripts and replacing the .as files with their compiled counterparts. However now the behavior you requested is implemented; .asc is automatically loaded if .as is missing.

**Comment by 1vanK** [comment]
Thank you!
