### ISSUE TITLE
Crash with ATI Radeon HD 5770

### ISSUE THREAD

**Issue by Enhex** [urho3d/Urho3D#867]
I gave some guy a build of my project to test, and it crashed on launch.
His graphics card is Radeon HD 5770.
Using "-gl2" solved the problem.

The card's spec says it supports openGL 3.2 here: http://www.amd.com/en-us/products/graphics/desktop/5000/5770

So I'm not sure why it crashes. Also I'm not sure if it's specific only to the guy that helped me test.

**Comment by Kiraffi** [comment]
I used to have 5870, and that one worked well. Some problems I had were MESA drivers with Linux for the opengl3, but after changing drivers I had no problem.

What OS is he using?

**Comment by cadaver** [comment]
Tested on Win7, HD 4800, GL3. No crash there. Possible driver bug; can you tell him to update and retest?

If running Direct3D is not an option, GL2 is arguably much more certain to work, since those are 10-year old APIs and the drivers have had time to mature.

**Comment by Enhex** [comment]
His OS is Windows 7 64bit.

His driver was outdated. When he updated the driver he panicked when the screen changed resolution and thought I broke his computer and now he won't talk with me.
I guess we'll have to assume it was an outdated driver.

If you want to attempt to ask him, his steam profile is http://steamcommunity.com/profiles/76561198043636554

**Comment by cadaver** [comment]
Sorry to hear that. I don't think it'd be proper for e.g. me to bother him.

Still, quite an illustrative example of what a developer of a Windows-based OpenGL application has to be prepared for.

**Comment by cadaver** [comment]
Closing this now. Can be reopened if more information (for example exact location in code where crash happens) surfaces, or is repeated by others.

**Comment by Enhex** [comment]
Just confirmed it was the outdated driver.
