### ISSUE TITLE
cmake vs2008 error

### ISSUE THREAD

**Issue by 299299** [urho3d/Urho3D#873]
reproduce steps:

1. cmd  cmake_vs2008.bat .build/vs2008
2. open the sln file generated by cmake
3. vs2008 tells me error when parsing  F:\Project\Urho3D\.build\vs2008\Source\Urho3D\Urho3D.vcproj

Looks like the AdditionalOptions is not right, here is what it looks like:

 AdditionalOptions=" "F:/Project/Urho3D/.build/vs2008/Source/ThirdParty/FreeType/$(ConfigurationName)/FreeType.lib" "F:/Project/Urho3D/.build/vs2008/Source/ThirdParty/JO/$(ConfigurationName)/JO.lib" "F:/Project/Urho3D/.build/vs2008/Source/ThirdParty/LZ4/$(ConfigurationName)/LZ4.lib" "F:/Project/Urho3D/.build/vs2008/Source/ThirdParty/PugiXml/$(ConfigurationName)/PugiXml.lib" "F:/Project/Urho3D/.build/vs2008/Source/ThirdParty/SDL/$(ConfigurationName)/SDL.lib" "F:/Project/Urho3D/.build/vs2008/Source/ThirdParty/StanHull/$(ConfigurationName)/StanHull.lib" "F:/Project/Urho3D/.build/vs2008/Source/ThirdParty/STB/$(ConfigurationName)/STB.lib" "F:/Project/Urho3D/.build/vs2008/Source/ThirdParty/AngelScript/$(ConfigurationName)/AngelScript.lib" "F:/Project/Urho3D/.build/vs2008/Source/ThirdParty/Civetweb/$(ConfigurationName)/Civetweb.lib" "F:/Project/Urho3D/.build/vs2008/Source/ThirdParty/kNet/$(ConfigurationName)/kNet.lib" "F:/Project/Urho3D/.build/vs2008/Source/ThirdParty/Detour/$(ConfigurationName)/Detour.lib" "F:/Project/Urho3D/.build/vs2008/Source/ThirdParty/DetourCrowd/$(ConfigurationName)/DetourCrowd.lib" "F:/Project/Urho3D/.build/vs2008/Source/ThirdParty/DetourTileCache/$(ConfigurationName)/DetourTileCache.lib" "F:/Project/Urho3D/.build/vs2008/Source/ThirdParty/Recast/$(ConfigurationName)/Recast.lib" "F:/Project/Urho3D/.build/vs2008/Source/ThirdParty/Bullet/$(ConfigurationName)/Bullet.lib" "F:/Project/Urho3D/.build/vs2008/Source/ThirdParty/LibCpuId/$(ConfigurationName)/LibCpuId.lib""

**Comment by weitjong** [comment]
Not too familiar with Windows nowadays. I have never seen such usage of relative path. Have you tried using the well tested relative path format using two dots followed by a backward slash? Or using an absolute path instead?

**Comment by cadaver** [comment]
This happens from https://github.com/urho3d/Urho3D/commit/05e40016974c470057aa68a7fca6cc0ecf9cea04 onward due to the quotes, which VS2008 doesn't seem to tolerate. I can add a version-based fallback.

**Comment by weitjong** [comment]
Hah! I thought I have missed a new way of specifying path in Windows.  It appears to be a typo though.
```F:\Project\Urho3D.build\vs2008\Source\Urho3D\Urho3D.vcproj```. I thought the dot somehow append itself. Stupid me.
