### ISSUE TITLE
Animation freezes when AnimatedModel's "update when invisible" is false

### ISSUE THREAD

**Issue by Enhex** [urho3d/Urho3D#875]
I'm using Urho3D 1.4

It seems AnimatedModel freezes when the model is out of the view and non-looping animation has ended. (didn't test the non-looping part, only out of view)

Freezes means when the model goes back into the view and the animation is already over(not confirmed) it won't update to the end of the animation.

For example, in the following image all the monsters should lay dead but some of them are frozen (they can kill each other by infighting while the player looks away):
![ss 2015-09-04 at 04 58 57](https://cloud.githubusercontent.com/assets/7088062/9675483/abfbd1fe-52c6-11e5-9b63-9390f60fa6e5.jpg)

Setting "update when invisible" to true fixes this problem, but the behavior is still undesirable, and updating once when the model becomes visible again might solve this so the optimization can still be used.

**Comment by cadaver** [comment]
Thanks, should be reproducible with e.g. the ninja dying animation, and fixable by ensuring that the blending & skinning is updated next time the model comes into view (there already is a "dirty" flag)

**Comment by cadaver** [comment]
It's a tricky bug; managed to reproduce it once in NinjaSnowWar. Probably some kind of corner case.

**Comment by cadaver** [comment]
Please check the master branch if the commit in question fixed your issue.

**Comment by Enhex** [comment]
Tested it and didn't have any animation freezes.
