### ISSUE TITLE
expose AnimationKeyFrame to the script level

### ISSUE THREAD

**Issue by 299299** [urho3d/Urho3D#878]
with this feature, animation authoring can done by script or editor, and some post process fix like asset post process can be done in script level.

**Comment by cadaver** [comment]
Should be possible to do by adding functions to add / remove tracks, and then add / remove / insert keyframes. These would also be convenient to C++ use, as Animation's public API is currently somewhat lacking.

**Comment by cadaver** [comment]
AngelScript use example:

```
        Animation@ newAnimation = Animation();
        newAnimation.length = 1.0;
        AnimationTrack@ track = newAnimation.CreateTrack("Bip01_Head");
        track.channelMask = CHANNEL_POSITION;
        AnimationKeyFrame kf;
        kf.time = 0.0;
        kf.position = Vector3(0,0,0);
        track.AddKeyFrame(kf);
        kf.time = 0.5;
        kf.position = Vector3(0,0.2,0);
        track.AddKeyFrame(kf);
        kf.time = 1.0;
        kf.position = Vector3(0,0,0);
        track.AddKeyFrame(kf);
```

**Comment by 299299** [comment]
is it possible that we can also create or modified the bone of skeleton in script ?
 I want to try something like:
   skel.GetBone("RotateBone").initialRotation = Quaternion(0, -180, 0); 
 but failed, seems like bone is read only reference in script.

**Comment by cadaver** [comment]
Changing the bindings to allow modifying the bone initial transform is doable.

Creating new bones would need to be done in the Model resource, and that is a lot of internal data structures to expose to script. I recommend using C++ in that case.
