### ISSUE TITLE
Animations cause asserts on exit

### ISSUE THREAD

**Issue by Enhex** [urho3d/Urho3D#885]
Original forum thread: http://urho3d.prophpbb.com/post8147.html

You can download a replication project from here:
https://www.dropbox.com/s/l4nhwaqxeu3xbuv/animation_bug.7z?dl=0
It's a modified "04_StaticScene.as".
Most of the bug code is in lines 69-89.

**How to replicate:**
Use the debug version "start_d.bat"
After the first animation ends and the second animation starts, exit the program by pressing ESC, and you should get asserts.

When playing the second animation, if it's the same as the first one it won't assert.
Maybe it has something to do with AnimationController's AnimationStates?

In my game it happens when I restart the level, which includes removing the scene's script instance.
In Urho3DPlayer it happens when you exit the program.
So maybe it has something to do with the script system?

**Comment by cadaver** [comment]
In the end this was an unsafe iteration of animations in AnimationController::Update(). Adding animation during the trigger event response caused invalid memory to be accessed. Fix will be coming soon.
