### ISSUE TITLE
Editor loading simple model cause: Failed to execute AssetImporter to import model 

### ISSUE THREAD

**Issue by meiry** [urho3d/Urho3D#886]
trying to import simple model that was imported from blender into the editor cause error that comes from void ImportModel(const String&in fileName) function in EditorImport.as 
i run the editor from :  
d:\dev\cpp\3d\Urho3d\git\Urho3D\build\bin\  
where all the executables was compiled , in the tool directory i have AssetImporter.exe compiled successfully .

the model is in different directory
![imporet](https://cloud.githubusercontent.com/assets/1107316/9811654/393b7b68-5881-11e5-8625-935844fc8a52.png)

 UPDATE , 

after reading this forum comment [http://urho3d.prophpbb.com/topic1143.html](http://urho3d.prophpbb.com/topic1143.html)
i tried to move the model to the Root 
d:\dev\cpp\3d\Urho3d\git\Urho3D\build\bin\Data\
it does show me the model and the map , but it doesn't  load the model into the Editor .
![editor2](https://cloud.githubusercontent.com/assets/1107316/9813073/1d748d16-588b-11e5-9aab-069581317162.png)

this is my Material.xml 

```
<material>
    <technique name="Diff.xml"/>
    <texture name="Base.png" unit="diffuse"/>
    <parameter name="MatDiffColor" value="0.64 0.64 0.64 1"/>
    <parameter name="MatSpecColor" value="0.5 0.5 0.5 50"/>
</material>
```

where Diff.xml didnt not created from the blender exporter 

my bin dir looks like this :

```
D:\dev\cpp\3d\Urho3d\git\Urho3D\build\bin>pwd
/d/dev/cpp/3d/Urho3d/git/Urho3D/build/bin


D:\dev\cpp\3d\Urho3d\git\Urho3D\build\bin>ls -l *.exe
-rwxr-xr-x 1 meirmaya Administrators 11783168 Sep 11 12:12 01_HelloWorld_d.exe
-rwxr-xr-x 1 meirmaya Administrators 11805184 Sep 11 12:12 02_HelloGUI_d.exe
-rwxr-xr-x 1 meirmaya Administrators 11786240 Sep 11 12:12 03_Sprites_d.exe
-rwxr-xr-x 1 meirmaya Administrators 11786240 Sep 11 12:12 04_StaticScene_d.exe
-rwxr-xr-x 1 meirmaya Administrators 11804160 Sep 11 12:12 05_AnimatingScene_d.exe
-rwxr-xr-x 1 meirmaya Administrators 11808256 Sep 11 12:12 06_SkeletalAnimation_d.exe
-rwxr-xr-x 1 meirmaya Administrators 11793408 Sep 11 12:12 07_Billboards_d.exe
-rwxr-xr-x 1 meirmaya Administrators 11793920 Sep 11 12:12 08_Decals_d.exe
-rwxr-xr-x 1 meirmaya Administrators 11794944 Sep 11 12:12 09_MultipleViewports_d.exe
-rwxr-xr-x 1 meirmaya Administrators 11809792 Sep 11 12:12 10_RenderToTexture_d.exe
-rwxr-xr-x 1 meirmaya Administrators 11793408 Sep 11 12:12 11_Physics_d.exe
-rwxr-xr-x 1 meirmaya Administrators 11793920 Sep 11 12:12 12_PhysicsStressTest_d.exe
-rwxr-xr-x 1 meirmaya Administrators 11810304 Sep 11 12:12 13_Ragdolls_d.exe
-rwxr-xr-x 1 meirmaya Administrators 11802112 Sep 11 12:12 14_SoundEffects_d.exe
-rwxr-xr-x 1 meirmaya Administrators 11800576 Sep 11 12:13 15_Navigation_d.exe
-rwxr-xr-x 1 meirmaya Administrators 11807744 Sep 11 12:13 16_Chat_d.exe
-rwxr-xr-x 1 meirmaya Administrators 11825152 Sep 11 12:13 17_SceneReplication_d.exe
-rwxr-xr-x 1 meirmaya Administrators 11842560 Sep 11 12:12 18_CharacterDemo_d.exe
-rwxr-xr-x 1 meirmaya Administrators 11824128 Sep 11 12:13 19_VehicleDemo_d.exe
-rwxr-xr-x 1 meirmaya Administrators 11790848 Sep 11 12:13 20_HugeObjectCount_d.exe
-rwxr-xr-x 1 meirmaya Administrators 16988160 Sep 11 12:11 21_AngelScriptIntegration_d.exe
-rwxr-xr-x 1 meirmaya Administrators 11792384 Sep 11 12:11 23_Water_d.exe
-rwxr-xr-x 1 meirmaya Administrators 11790336 Sep 11 12:11 24_Urho2DSprite_d.exe
-rwxr-xr-x 1 meirmaya Administrators 11786240 Sep 11 12:11 25_Urho2DParticle_d.exe
-rwxr-xr-x 1 meirmaya Administrators 11791872 Sep 11 12:11 26_ConsoleInput_d.exe
-rwxr-xr-x 1 meirmaya Administrators 11788800 Sep 11 12:12 27_Urho2DPhysics_d.exe
-rwxr-xr-x 1 meirmaya Administrators 11788800 Sep 11 12:12 28_Urho2DPhysicsRope_d.exe
-rwxr-xr-x 1 meirmaya Administrators 11799040 Sep 11 12:12 29_SoundSynthesis_d.exe
-rwxr-xr-x 1 meirmaya Administrators 11791872 Sep 11 12:12 30_LightAnimation_d.exe
-rwxr-xr-x 1 meirmaya Administrators 11787776 Sep 11 12:12 31_MaterialAnimation_d.exe
-rwxr-xr-x 1 meirmaya Administrators 11806208 Sep 11 12:12 32_Urho2DConstraints_d.exe
-rwxr-xr-x 1 meirmaya Administrators 11788288 Sep 11 12:12 33_Urho2DSpriterAnimation_d.exe
-rwxr-xr-x 1 meirmaya Administrators 11796992 Sep 11 12:12 34_DynamicGeometry_d.exe
-rwxr-xr-x 1 meirmaya Administrators 11787776 Sep 11 12:12 35_SignedDistanceFieldText_d.exe
-rwxr-xr-x 1 meirmaya Administrators 11787264 Sep 11 12:12 36_Urho2DTileMap_d.exe
-rwxr-xr-x 1 meirmaya Administrators 11805696 Sep 11 12:12 37_UIDrag_d.exe
-rwxr-xr-x 1 meirmaya Administrators 11801088 Sep 11 12:12 38_SceneAndUILoad_d.exe
-rwxr-xr-x 1 meirmaya Administrators 11811328 Sep 11 12:12 39_CrowdNavigation_d.exe
-rwxr-xr-x 1 meirmaya Administrators 11808256 Sep 11 12:12 40_Localization_d.exe
-rwxr-xr-x 1 meirmaya Administrators 20574720 Sep 11 12:13 AssetImporter.exe
-rwxr-xr-x 1 meirmaya Administrators 16963584 Sep 11 12:13 Urho3DPlayer_d.exe


ls -l  
....
drwxr-xr-x  7 meirmaya Administrators     4096 Sep 11 12:18 CoreData
drwxr-xr-x 17 meirmaya Administrators     4096 Sep 11 13:34 Data
-rwxr-xr-x  1 meirmaya Administrators      312 Sep 10 23:20 Editor.bat
.....
```

**Comment by cadaver** [comment]
Do you have the AssetImporter tool next to Urho3DPlayer in the "tool" subdirectory?

Eg. in a typical build 
bin/Urho3DPlayer
bin/tool/AssetImporter

**Comment by meiry** [comment]
yes it is near the Urho3DPlayer

**Comment by cadaver** [comment]
I suggest to delete the orho3d_test1 directory, and reset the resource path in the editor to point to just bin/Data (File -> Set Resource Path), then try reimporting the model.

Resource paths elsewhere on the harddisk should work, but I don't recommend using a subdirectory of Data as the editor resource path.

**Comment by meiry** [comment]
Hey i tried that but still getting this error 
![res](https://cloud.githubusercontent.com/assets/1107316/9814783/6996c124-5899-11e5-854c-e502b98b4dff.png)

is there any angel script debugger so i could debug the thing ?

**Comment by cadaver** [comment]
Not as such, but you can debug the ImportModel function in bin/Data/Scripts/Editor/EditorImport.as by simply adding Print() functions to know what it's doing (assetimporter command line parameters, the resource path it's using for the new object created in the scene..)

**Comment by Kiraffi** [comment]
The Diff.xml should at least be Techniques/Diff.xml. The file is in CoreData-folder.
I cant remember if it was assetimporter.exe or the reattivas blender exporter, but one of them doesn't add the folder name to the materials technique, and you have to manually add it on every object that you import from blender to urho.

Although I am not sure if this is really the issue, but changing the material file should at least fix the missing technique-file.
