### ISSUE TITLE
Urho2DSpriterAnimation

### ISSUE THREAD

**Issue by fil-in** [urho3d/Urho3D#888]
"Example 33_Urho2DSpriterAnimation is a good demonstration of this feature (scml file and xml spritesheet are both named 'imp' to instruct Urho2D to use the atlas instead of the individual files). You could remove every image files in the 'imp' folder and just keep 'imp_all.png' to test it out."

It does not work anymore. Will the new way to use packaged sprite sheets?

**Comment by aster2013** [comment]
you dont need create a spritesheet any more. it will create by urho3d at runtime.

**Comment by JoshEngebretson** [comment]
This will incur runtime overhead of loading every individual image and packing them (how efficiently?).  Texture Packer etc have highly optimized packing where you may pack more than a single animation's sprites.  It will also make using PVR and other compressed mobile image formats difficult.

**Comment by JoshEngebretson** [comment]
BTW, I was able to restore the texture atlas and plist support for spritesheets in the new Spriter code.  However, had to revert back to previous 2D system as under some time constraints and was running into issues.

The auto created spritesheet for single images is cool if a spritesheet doesn't exist, though when shipping a game likely you'll want spritesheets that pack a fair amount of content and for download size and load times may want compressed textures.

**Comment by fil-in** [comment]
"it will create by urho3d at runtime" At the app runtime or Editor runtime or PackageTool runtime? How it can help make lightweight app for mobile platform. How urho3d can organise which image needs to be place in exactly that sheetpack exactly for that game scene. Can it be optional?
