### ISSUE TITLE
navigation samples bugs

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#889]
Urho3DPlayer_d.exe Scripts/39_CrowdNavigation.as
crash on start

Urho3DPlayer_d.exe Scripts/15_Navigation.as
crash when click

15_Navigation_d.exe
Character flies above the ground

![1](https://cloud.githubusercontent.com/assets/13021826/9840046/e8e3d184-5a9b-11e5-9fb9-4f518d9895a0.jpg)

**Comment by 1vanK** [comment]
Crash when call navMesh.FindNearestPoint() in scripts

**Comment by cadaver** [comment]
It seems the crashes are caused by added C++ NavigationMesh function parameters in c9bc4cbae380092b4ddc08270ab93951c99da562. Will likely have to make wrapper functions that include the proper default values (null) for these, as the parameters cannot be used from script.

**Comment by weitjong** [comment]
That's too bad cause it works as expected using GCC compiler.

**Comment by cadaver** [comment]
Will commit the wrappers in. As for the character levitating, that has been there ages, it seems to be an artifact of the navmesh generation (if you look with debug geometry, the debug geometry is off the ground)
