### ISSUE TITLE
script doc enhancement 

### ISSUE THREAD

**Issue by 299299** [urho3d/Urho3D#890]
Is it possible to add parameter name in the function description?
When I was digging around in AngelScriptAPI.h, I see a lot of functions, I can get the meaning from the function name, but I was confused with the parameters.

  For example:
  "Array<String> ScanDir(const String&, const String&, uint, bool) const;", what does the second and the third parameter supposed to be ?
  I have to check the source code in the IOAPI.cpp to see how to fill the parameters.

**Comment by cadaver** [comment]
The script documentation is dumped directly from the AngelScript registered runtime API which doesn't retain the variable names, unfortunately.

**Comment by weitjong** [comment]
Clang produces AST that does not just contain the parameter names but also the function/method comments. When a Clang-tool to auto-generate the AngelScript binding could be developed in the future then it is not too far fetched to imagine that another similar tool to produce the accompanying *.dox file could also be made.

**Comment by cadaver** [comment]
Certainly, that would be the proper way once we're at that point.

I have some ideas for a quick and dirty way doing usual string manipulation and ad-hoc parsing :)

**Comment by cadaver** [comment]
Ok, tested the "hack" method. It worked quite good for most of the API, but it still leaves holes due to some functions not having C++ counterparts, having totally different parameters in the binding, or being registered as free function as opposed to class function etc. Therefore I don't think I'll pursue it to the finish.
