### ISSUE TITLE
Attribute inspector should not reset name

### ISSUE THREAD

**Issue by ucupumar** [urho3d/Urho3D#891]
I think reset button on attribute inspector should not reset the name too. I can't think single use case someone will reset node transformation along with it's name to empty.
![reset_rant](https://cloud.githubusercontent.com/assets/5253453/9851724/690ed362-5b24-11e5-8369-667be2434e0e.png)
Anyway, it's been a while since I use Urho. Nice to see you again guys! :smile_cat:

**Comment by cadaver** [comment]
It's a generic reset of attributes using Serializable::ResetToDefaults(). It just happens so that name is an attribute of Node and it doesn't get special treatment.

**Comment by ucupumar** [comment]
![okay-guy-meme-face](https://cloud.githubusercontent.com/assets/5253453/9854688/3ed3b1d4-5b34-11e5-941f-f5d5da8254da.jpg)

**Comment by MonkeyFirst** [comment]
It may before reseting save Node name to temp variable and then do std Reset and after that set saved variable to Node name.

**Comment by cadaver** [comment]
No need to do that, we could create a "protected" class of attributes (with a flag) that is unaffected by ResetToDefault() if we wanted. However then I could see someone equally submitting a bug of "why name isn't cleared"? Ie. it's largely a matter of opinion. Strictly from a technical perspective it seems like ResetToDefault() isn't doing its job, if some attributes are preserved.

**Comment by 1vanK** [comment]
Personally, I have never used the button :) I just set "New node mode" to "In center".

**Comment by ucupumar** [comment]
Sorry for commenting old closed issue, so how about another button to reset only transformation of the node? I think it's still more reasonable for usability standpoint. To prevent bug report, maybe we can just use MonkeyFirst solution and not changing the class attributes itself.

**Comment by cadaver** [comment]
Buttons are a bit of a pain, since the inspector is supposed to be generic (and would need descriptive graphics) but a menu item Edit -> Reset Transform should be easy to add. There are already individual Reset pos/rot/scale items.

**Comment by ucupumar** [comment]
I see. Silly me, I just notice Urho editor already had reset position, rotation, and scale. Maybe I didn't know that because they don't have hotkeys. A bit out of track from the original issue, but for more easier access I think they should have their own hotkeys. If not really a problem, I propose these hotkeys:
Alt+1 : reset location
Alt+2 : reset rotation
Alt+3 : reset scale
If reset transform will be added, then it would be Alt+Q (or any other alphabet/number)
What do you think?

**Comment by cadaver** [comment]
Sounds good, will just have to doublecheck they're not used already, for example in the Blender mode.

**Comment by ucupumar** [comment]
Then again, I didn't know Urho editor had Blender mode :D 
In blender mode Alt+g is works to reset location, so I think it's reasonable to set alt+1 to reset location on default urho mode
