### ISSUE TITLE
Network Host Migration Support

### ISSUE THREAD

**Issue by rasteron** [urho3d/Urho3D#893]
I have seen this used with other popular multiplayer games so aside from Client Side Prediction, I think transferring 'Host' status/mode during an active session to another 'Candidate' player with an acceptable ping rate (depending on the game) seems to be a good addition. This is particularly essential when the current host suddenly rage quits, drops out of the game or has some form of problem with his/her connection. The network session would run smoothly and avoid critical game play disruption.

**Comment by cadaver** [comment]
In terms of kNet (and Urho networking), there are only clients and servers, instead of a P2P topology. Not sure this is applicable or possible when using kNet; if the server quits, how will the clients transmit information for host migration?

**Comment by rasteron** [comment]
Hey Lasse,

Yes this is some form of p2p but I found some docs and guide from other engines on how this is achieved:

Host Migration:
http://answers.unity3d.com/answers/208217/view.html
http://docs.cryengine.com/display/SDKDOC4/Host+Migration

Is this still a possibility with kNet? Looks like Raknet has this built-in among other features.

**Comment by cadaver** [comment]
Unity networking functions as client-server too. What the first paper describes sounds doable in Urho application code as well. It has steps that are somewhat vague and possibly game-specific (like "wait 1 second", "keep ordered list of peers") so I don't think it should be part of the engine, just like it isn't in Unity either.

**Comment by rasteron** [comment]
Ok good to hear there is a possibility. Thanks.

**Comment by cadaver** [comment]
Closing this for now.
