### ISSUE TITLE
Compile Errors with MinGW and DirectX 9

### ISSUE THREAD

**Issue by rasteron** [urho3d/Urho3D#898]
Downloaded the latest build and I got these errors..

```
...

[ 52%] Built target LibCpuId
Scanning dependencies of target Urho3D
[ 52%] Building CXX object Source/Urho3D/CMakeFiles/Urho3D.dir/Graphics/Direct3D9/D3D9Graphics.cpp.obj
C:\Urho3D\Source\Urho3D\Graphics\Direct3D9\D3D9Graphics.cpp: In member function 'void Urho3D::Graphics::DrawInstanced(Urho3D::PrimitiveType, unsigned
int, unsigned int, unsigned int, unsigned int, unsigned int)':
C:\Urho3D\Source\Urho3D\Graphics\Direct3D9\D3D9Graphics.cpp:918:39: error: 'D3DSTREAMSOURCE_INSTANCEDATA' was not declared in this scope
                 SetStreamFrequency(i, D3DSTREAMSOURCE_INSTANCEDATA | 1u);
                                       ^
C:\Urho3D\Source\Urho3D\Graphics\Direct3D9\D3D9Graphics.cpp:920:39: error: 'D3DSTREAMSOURCE_INDEXEDDATA' was not declared in this scope
                 SetStreamFrequency(i, D3DSTREAMSOURCE_INDEXEDDATA | instanceCount);
                                       ^
Source\Urho3D\CMakeFiles\Urho3D.dir\build.make:1107: recipe for target 'Source/Urho3D/CMakeFiles/Urho3D.dir/Graphics/Direct3D9/D3D9Graphics.cpp.obj' f
ailed
mingw32-make[2]: *** [Source/Urho3D/CMakeFiles/Urho3D.dir/Graphics/Direct3D9/D3D9Graphics.cpp.obj] Error 1
CMakeFiles\Makefile2:1120: recipe for target 'Source/Urho3D/CMakeFiles/Urho3D.dir/all' failed
mingw32-make[1]: *** [Source/Urho3D/CMakeFiles/Urho3D.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
mingw32-make: *** [all] Error 2
```

I have no problems with v1.4 Release..

gcc version 4.8.1

**Comment by cadaver** [comment]
Nothing should have changed; these should be in d3d9types.h, which should be included by d3d9.h. I can add manual definitions for these however.

**Comment by cadaver** [comment]
Please check if this fixes the issue. Generally, it sucks to support a compiler which may or may not have correct headers.

**Comment by rasteron** [comment]
Thanks Lasse and agreed. The fix now solved the error but I'm getting this similar issue:

http://urho3d.prophpbb.com/topic504-10.html#p2964

I'll stick with Visual Studio for DX Builds and need to do some MinGW upgrades..

**Comment by Stinkfist0** [comment]
@rasteron Have you tried MinGW-w64? That seemed to work flawlessly for me earlier this year when I did Emscripten Windows build. I tried regular MinGW before that, but it gave some DX related errors so I switched to MinGW-w64 instead.

**Comment by rasteron** [comment]
Yes, that was the plan and I remember that I already have MinGW-w64 installed. Thanks.
