### ISSUE TITLE
Scripts/33_Urho2DSpriterAnimation.as does not work

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#900]
Urho3DPlayer_d.exe Scripts/33_Urho2DSpriterAnimation.as -w -x 800 -y 600

[Thu Sep 17 00:59:14 2015] DEBUG: Loading resource Urho2D/imp/imp.xml
[Thu Sep 17 00:59:14 2015] ERROR: Could not find resource Urho2D/imp/imp_all.png
[Thu Sep 17 00:59:14 2015] ERROR: Could not load texture Urho2D/imp/imp_all.png

[Thu Sep 17 00:59:22 2015] ERROR: Scripts/33_Urho2DSpriterAnimation.as:137,5 - Exception 'Null pointer access' in 'void HandleMouseButtonDown(StringHash, VariantMap&inout)'
AngelScript callstack:
	Scripts/33_Urho2DSpriterAnimation.as:void HandleMouseButtonDown(StringHash, VariantMap&inout):137,5

**Comment by aster2013** [comment]
I have remove the imp.xml sprite sheet file.
