### ISSUE TITLE
scene_->SetScale() does not work?

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#902]
I use the orthographic camera and I need to scale each object in scene to 32
```
mushroomNode->SetScale(32.0f);
```
I tried to use
```
scene_->SetScale(32);
```
but it does not work.
Scale compensation for camera
````
cameraNode_->SetScale(1.0f / 32.0f);
```
also does not work.
Manipulation with the camera->SetZoom() and camera->SetOrthoSize() does not suit me, since I combine 3D scene with SpriteBatch http://urho3d.prophpbb.com/topic596.html in which 1 screen pixel = 1 3D unit

**Comment by cadaver** [comment]
The scene is meant to be in an identity transform, its transform is purposefully disregarded to optimize for performance.

You could create a root node for your objects which you can scale.

**Comment by 1vanK** [comment]
Thank you
