### ISSUE TITLE
input->GetMousePosition() don't change when input->SetMouseVisible(false)

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#904]
It is SDL specific problem?

**Comment by cadaver** [comment]
Hiding the mouse activates the "centering" behavior to allow indefinite motion (FPS camera and such) so it's expected. Use the mouse move values instead.

**Comment by 1vanK** [comment]
I want the cursor could leave the window, but inside window draw the cursor by himself (i am using http://urho3d.prophpbb.com/topic596.html)

**Comment by cadaver** [comment]
We'll need an additional mouse mode for this, shouldn't be hard to do.

**Comment by 1vanK** [comment]
thank you
