### ISSUE TITLE
Emscripten build attempts a call to nonfunctional popen.

### ISSUE THREAD

**Issue by juj** [urho3d/Urho3D#905]
Running an Emscripten build with current Emscripten incoming, I am seeing that Urho3D has code that calls to `popen`. In Emscripten that function is not supported (there is no multiprocess capabilities). Current Emscripten had a bug that calls to that function would cause a call to unresolved symbol `posix_spawn` to be attempted. That will be fixed in https://github.com/kripken/emscripten/pull/3819 . After that, calls to `popen` will be no-ops that just return 0 and set errno.

Perhaps Urho3D should #ifdef out its code paths that lead to calling `popen` on Emscripten?

**Comment by dahliaT** [comment]
Here are some builds which illustrate the issue.

http://di01.wwweb3d.net/emscripten_test.tgz

**Comment by friesencr** [comment]
There was a commit to fix this a few days ago.  @dahliaT  Pull master and see if you still have the problem.

**Comment by dahliaT** [comment]
Oops I posted to the wrong forum/issue. I should have posted to the emscripten bug tracker. Please disregard :)
