### ISSUE TITLE
ConvexCast doesn't take into account Urho3D::CollisionShape position

### ISSUE THREAD

**Issue by Enhex** [urho3d/Urho3D#906]
ConvexCast() doesn't take into account Urho3D::CollisionShape position.
That causes the shape to be cast not from where you'd expect it to.
The user can't really tell what's going on without inspecting and understanding the source code of ConvexCast().
By simply adding the shape's position to that start & end position the problem is solved.
The problem with this solution is that it will be a bit more expensive, and in most cases the position is zero, so it's wasteful.
To solve that we could have a version of the function that takes a shape's position into account. This way when the user will look at the documentation of ConvexCast he'll be able to find out  why things fail without having to figure out the source code. Maybe name it ConvexCastWithPosition().

**Comment by cadaver** [comment]
I thought you submitted this issue already before and it was addressed in master branch commit e0ce3e4ad0fdeb963d0f5940534fec3eedf80fb2

Does the modification in the commit in fact not fix the issue, ie. have you tested with and without it?

**Comment by Enhex** [comment]
Oh sorry, I forgot about it and was still using custom version of the ConvexCast function.

**Comment by cadaver** [comment]
Accounting for the shape offset is a few matrix multiplies, which shouldn't cause noticeable performance difference unless you're doing hundreds of casts per frame, in which case Bullet's collision detection work to execute the actual cast would dominate anyway.

**Comment by cadaver** [comment]
The accurate cast distance was straightforward to add. If for some reason someone wants the distance to hit position from start position (earlier behavior) that can be calculated manually.
