### ISSUE TITLE
CMake user should be told dot / Graphviz is required for doc generation

### ISSUE THREAD

**Issue by bvanevery** [urho3d/Urho3D#909]
Doxygen does not ship with "dot" nowadays.  It is contained in Graphviz.  "dot" is searched for by the CMake build, but when it is not found, that information is not passed along to the user.  This results in a spectacular failure later if the user tries to build the docs, where "dot" actually seems to be present and working for up to 150 lines of output, followed by a similarly large number of barfs.  Abbreviated example, please extrapolate:

3>  Running dot for graph 515/957
...
3>  Running dot for graph 651/957
3>CUSTOMBUILD : error : Problems running dot: exit code=-1, command='dot', arguments='"C:/Users/bvanevery/devel/build/Urho3D/Docs/html/struct_urho3_d_1_1_spriter_1_1_timeline_key__inherit__graph.dot" -Tpng -o "C:/Users/bvanevery/devel/build/Urho3D/Docs/html/struct_urho3_d_1_1_spriter_1_1_timeline_key__inherit__graph.png"'
[similar repeated lots of times]

Don't have a fix but here are principles of how it should behave:
- when "dot" is missing, user should be informed that "dot" is required to build docs, that it is usually available in Graphviz, and a link given to Graphviz website.
- if user doesn't say they want to build docs, then failure to find "dot" should be a warning
- if user explicitly says they want to build docs, then failure to find "dot" should be an error
- doc generation should never be QUIET.  It should either happen or not happen.  If the user doesn't like piles of doc messages or extra build time during routine builds then they should just not routinely build the docs.  Some dependency issues could be exacerbating the noisiness here.

**Comment by weitjong** [comment]
At the very beginning there was a time where our build did not even have a 'doc' target. In our documentation the Doxygen and Graphviz were never listed as a prerequisite. In the interest of building speed, we have purposely decouple the normal build and doc build, although we do provide option to add the 'doc' target into the 'all' target. We have time constraint and number of log entries constraint on our build server (Travis-CI). This is the reason why we strive to have faster build and quieter log.

So, I could agree on your first and third points, but not the second and fourth ones.

**Comment by bvanevery** [comment]
You have no reason to disagree with the 2nd point.  Issuing a warning to a CMake user does no harm and consumes no extra processing time.

As for the 4th point, let's say you or users have decided docs should be built.  How can you possibly benefit from errors in the build being obscured?  It just slows down the amount of time it takes for someone like me to come along and figure out a half-solution for whatever the problem is.

**Comment by weitjong** [comment]
> You have no reason to disagree with the 2nd point. Issuing a warning to a CMake user does no harm and consumes no extra processing time.

If all I want is to just do a normal build without any doc then why should I need to be concerned with missing Dot?  

> As for the 4th point, let's say you or users have decided docs should be built. How can you possibly benefit from errors in the build being obscured? It just slows down the amount of time it takes for someone like me to come along and figure out a half-solution for whatever the problem is.

I think we may have misunderstood each other on this one. I just want to clarify that we have a URHO3D_DOC_QUIET build option for a good reason. When you need all the verboseness for troubleshooting then don't use that option. If your last point was suggesting us to remove this quiet option then I have to disagree. If not then please elaborate more on what exactly you think that need to be improved. Thanks.

**Comment by bvanevery** [comment]
"If all I want is to just do a normal build without any doc then why should I need to be concerned with missing Dot?"  Most people are not concerned about a WARNING.  Why are you?  The user can still proceed, the user is not prevented from anything, there's only an extra sentence in the log output.  The benefit is the user is educated about what dependencies are needed to build the docs.  First time users are going to need docs, they're likely to try to build them soon enough.  Especially on Windows, as your doc generation seems to be system specific and you don't ship premade Windows docs for a DX11 + Visual Studio environment, last I was told.  But benefit aside, the cost is nothing, there is no impact for giving a WARNING.

As for URHO3D_DOC_QUIET, I thought I found a place in the code where the QUIET behavior was actually hardwired and not subject to user selection, but I could be mistaken.  I'll need to look again.

I definitely think URHO3D_DOC_QUIET should be FALSE by default.  I also think allowing users to set such a thing to TRUE Is seriously misguided; why, in general, suppress build errors?  But if it's not default behavior, at least it's the user's own choice, problem, and consequences.

Having a Travis-Cl "log entries constraint" sounds like a serious automated build issue.  I think you are saying you are suppressing doc build errors simply because Travis-Cl cannot handle a lot of output.  If I were in charge of an automated build I wouldn't find that acceptable, as it means errors propagated to users unknowingly.  But I'm not in charge of that, and don't plan to be presently.  I hope you realize such a problem is seriously misfeatured / not normal as far as automated builds go.

**Comment by weitjong** [comment]
You did not actually answer my question. Why should one see a warning on missing dot.exe when it is not a prerequisite or required for a particular build tree configuration? We have many type of builds and there are no one canonical way to configure our build tree. Doc build requires dot.exe but others builds may require other software components. And it could be safely assumed not all the users have all of those installed, so should we warn them as well about those missing components? I still don't see any reason why we should treat dot.exe any difference. I could agree on this tough. When the prerequisite for doc build is not met and when URHO3D_DOCS is on (doc target is part of all target) then raise a fatal error immediately (your point 1 and 3). As for the quiet option. It is just an option. use it or don't use it. Both URHO3D_DOCS and URHO3D_DOCS_QUIET are not defaulted to true.

As for Travis-CI. We don't control how Travis-CI operates. Those constraints are forced upon us. They have a good reason to impose those constraints, if you think that all the logs generated by all the CI builds by all the projects that their support are ended up somewhere in the cloud taking some spaces. Please do not confuse between not logging the build process output with not detecting the exit status of our build process in our CI-build. Any errors from any of our build process will cause an abort signal to be sent.

**Comment by bvanevery** [comment]
Because you aren't shipping prebuilt docs for all platforms, and they are an essential that will soon be needed.  Because educating users on what they need to do to actually get up and running with Urho3d, is wise.  You don't need to educate users on *things they don't need*.  But this is needed.

**Comment by weitjong** [comment]
> Also, occurs to me as odd why we're even arguing this... why can't I build docs AT ALL TIMES?  

err, because we like to have option?

**Comment by bvanevery** [comment]
How does setting it so I *can't* do something, give me an option?

**Comment by weitjong** [comment]
I close this issue as the discussion is getting nowhere.
