### ISSUE TITLE
FindDirect3D.cmake needs more SDK paths

### ISSUE THREAD

**Issue by bvanevery** [urho3d/Urho3D#911]
It looks for DirectX redistributables.  It searches some registry paths to locate Windows Kits / SDKs:

find_file (DIRECT3D_DLL NAMES ${DLL_NAMES} PATHS
    "[HKEY_LOCAL_MACHINE\\SOFTWARE\\Wow6432Node\\Microsoft\\Microsoft SDKs\\Windows\\v8.1;InstallationFolder]/Redist/D3D/${PATH_SUFFIX}"
    "[HKEY_LOCAL_MACHINE\\SOFTWARE\\Wow6432Node\\Microsoft\\Microsoft SDKs\\Windows\\v8.0;InstallationFolder]/Redist/D3D/${PATH_SUFFIX}"
    NO_DEFAULT_PATH)

However on one of my Windows 10 machines, that started life as a Vista machine and went through a few generations of upgrades of OS and Visual Studio compilers, I have far more than just these 2 kits.  It's got v10.0, v8.1A, v8.1, v8.0A, v8.0, and v7.1A.  They've all got the same path structure, just need more paths.  I would suggest highest number first. 

I have also found v10.0A and v7.0A directories for some binaries, but these aren't listed in the Wow6432Node as part of the SDKs.  Could be a version "gotcha", if directories exist somewhere that don't actually correspond to SDKs.  Just saying, a proper search would have to be careful.

Technically a build should match the Kit actually chosen for the build.  A CMake user has a choice of generators and could have multiple compiler installations living side by side, with different Kits for each.  If such Kits are not being detected though, then figuring this out could get dicey and complicated. I'm not up on CMake methods for detecting "the Kit in use".

 I'm not even sure if these redistributables are actually different from Kit to Kit.  Haven't checked that.

**Comment by cadaver** [comment]
I don't have SDKs installed past 8.1, so I can't test reliably. Please do contribute a fix if you can.

**Comment by bvanevery** [comment]
I have determined that the D3DCompiler_47.dll available for redist in these various SDKs, has a different size and Product version for each one of them.  I don't know whether interchanging them can make things explode.

**Comment by cadaver** [comment]
Preferably the DLL should always come from the same kit as the DX includes dir (which is setup automatically by VS). However the API is the same and the major version is the same, so I don't think there would be actual trouble.

**Comment by bvanevery** [comment]
CMake determines what Windows SDK it's using somewhere in its C++ source code.  That determination does not appear to be exposed in any CMake scripting command or variable though.  MSVC compiler info is exposed, for instance by variables like MSVC14.  However that's just the compiler, and you can't be sure what OS or Windows SDK is being used in conjunction with it.  Additionally, we don't really care about the compiler so much as we could be using mingw32, mingw64, cygwin, or something even more exotic.  I'll keep looking for someone's wisdom on the internet for how to do this, but it hasn't yielded to easy search.  Instead I've tended to find CMake bug tracking entries that point at various C++ source sections where the determination is implemented.
