### ISSUE TITLE
[AngelScript] Please expose BorderImage to Window

### ISSUE THREAD

**Issue by Mike3D** [urho3d/Urho3D#912]
Window derives from BorderImage, but currently BorderImage methods and properties are not exposed to Window AngelScript API.

I've tried to do this in UIAPI.cpp, but to no avail:
```angelscript
static void RegisterWindow(asIScriptEngine* engine)
{
    RegisterBorderImage<Window>(engine, "Window"); //=========
    RegisterWindow<Window>(engine, "Window");
}
```

**Comment by cadaver** [comment]
The trick is that RegisterWindow should do RegisterBorderImage instead of RegisterUIElement. Tested this and there should be no ill effects. Commit coming soon.

**Comment by Mike3D** [comment]
Many thanks cadaver.
