### ISSUE TITLE
Use emscripten_get_now() instead of gettimeofday() for high-resolution timing.

### ISSUE THREAD

**Issue by juj** [urho3d/Urho3D#916]
The C function `gettimeofday()` is troublesome in JavaScript since it needs to resort to the function `Date.now()`. That function only has millisecond precision, and it is not optimized for high performance tasks, so there is a asm.js <-> non-asm.js boundary transition which impacts performance.

It is difficult to optimize `gettimeofday()` in Emscripten side, since we must return the current time of day, and can't return an arbitrary wallclock time. High-precision timers don't actually care about the time of day, so in Emscripten, for fastest and most precise high performance wallclock timing, it is advisable to use the `double emscripten_get_now();` function, which returns a wallclock time in milliseconds  with submillisecond precision. It is practically a call to https://developer.mozilla.org/en-US/docs/Web/API/Performance/now .

Therefore the implementation of `HiresTimer::GetUSec()` could be

    #ifdef __EMSCRIPTEN__ // +
    #include <emscripten/emscripten.h> // +
    #endif // +

    long long HiresTimer::GetUSec(bool reset)
    {
        long long currentTime;

    #ifdef WIN32
        if (supported)
        {
            LARGE_INTEGER counter;
            QueryPerformanceCounter(&counter);
            currentTime = counter.QuadPart;
        }
        else
            currentTime = timeGetTime();
    #elif defined(__EMSCRIPTEN__) // +
        currentTime = (long long)(emscripten_get_now() * 1000.0); // +
    #else
        struct timeval time;
        gettimeofday(&time, NULL);
        currentTime = time.tv_sec * 1000000LL + time.tv_usec;
    #endif

        long long elapsedTime = currentTime - startTime_;

        // Correct for possible weirdness with changing internal frequency
        if (elapsedTime < 0)
            elapsedTime = 0;

        if (reset)
            startTime_ = currentTime;

        return (elapsedTime * 1000000LL) / frequency;
    }

lines marked with (+) were added.

As a sidenote, I see that the file Timer.cpp actually repeats the implementation of obtaining a wallclock time five times almost identically in the following functions

    unsigned Time::GetSystemTime()
    unsigned Timer::GetMSec(bool reset)
    void Timer::Reset()
    long long HiresTimer::GetUSec(bool reset)
    void HiresTimer::Reset()

which each call to `gettimeofday()`. The note to use the Emscripten-specific `emscripten_get_now()` instead of `gettimeofday()` would apply to each of these, since none of the functions seem like they need the actual time of day.

**Comment by davehayes** [comment]
Just a comment about high res timing and browsers. Most browsers disable high res timing due to Spectre concerns. There's a little red note in this link:  https://developer.mozilla.org/en-US/docs/Web/API/Performance/now

Thus it's highly likely that, should you find a way to actually do microsecond precision timing, browser devs will nerf you. :)
