### ISSUE TITLE
The default behavior of hiding mouse cursor in windowed mode in Emscripten builds is troublesome.

### ISSUE THREAD

**Issue by juj** [urho3d/Urho3D#917]
In several samples built for Emscripten, the mouse behavior is a bit quirky. 

What currently happens:
    - mouse cursor is hidden when mouse is moved over the canvas.
    - mouse cursor is restored to be visible again when mouse exits the canvas.
    - moving the mouse over the canvas generates camera mouselook rotate events.
    - moving the mouse outside the canvas does not rotate the camera.
    - mouse cursor is not constrained to stay inside the canvas rectangle, but the mouse cursor is able to freely exit the canvas rectangle.
    - when mouse enters/exits the canvas rectangle, there is an abrupt "discontinuous" snap of the camera lookat direction.

The combination of these behaviors makes looking around the scene by rotating the camera with mouse move a bit difficult, and one can't easily do e.g. a 360 rotation of the . In fullscreen mode, this problem does not occur since the mouse cursor is not able to exit the canvas.

In the 08_decals sample, there is an additional issue that the software mouse cursor rendered by the engine does not match with the location of the actual mouse cursor.

If I might suggest, some ways to come out of the issues:
   - remove the behavior of hiding the mouse cursor by default and moving the camera by default, and make it e.g. a "hold down right mouse button to drag" type of gesture.
   - In 08_decals sample, one could avoid hiding the mouse cursor over the canvas, but instead let the real mouse cursor stay visible, and not render a software mouse cursor in Urho3D. Then use absolute mouse cursor positions provided by the input api to mark the mouse cursor location instead of calculating them incrementally/relative inside the engine.
   - an alternative could be to use the pointer lock api (`emscripten_request_pointerlock()`) when the user clicks on the canvas. Pointer lock hides the mouse cursor on the web page altogether, and changes it to a relative movement mode. See here for a demo http://mdn.github.io/pointer-lock-demo/

**Comment by hdunderscore** [comment]
Most of the main issues should be addressed with the recent pull request. The online samples aren't updated yet though.
