### ISSUE TITLE
Building a single sample in a clean build tree fails with a missing .h file error.

### ISSUE THREAD

**Issue by juj** [urho3d/Urho3D#918]
It looks like building individual subprojects is not supported, and CMake does not know about some dependency between different targets in the build. This means if one wants to build only a single sample in a clean tree, there is a failure. STR:

	git clone https://github.com/urho3d/Urho3D.git
	cd Urho3D
	mkdir build_emscripten
	cmake_emscripten.bat build_emscripten -DURHO3D_SAMPLES=1
	cd build_emscripten
	mingw32-make 12_PhysicsStressTest

This prints the following:

	C:\code\Urho3D>mkdir build_emscripten

	C:\code\Urho3D>cmake_emscripten.bat build_emscripten -DURHO3D_SAMPLES=1
	-- Check for working C compiler: C:/code/emsdk/emscripten/incoming/emcc.bat
	-- Check for working C compiler: C:/code/emsdk/emscripten/incoming/emcc.bat -- works
	-- Detecting C compiler ABI info
	-- Detecting C compiler ABI info - done
	-- Detecting C compile features
	-- Detecting C compile features - done
	-- Check for working CXX compiler: C:/code/emsdk/emscripten/incoming/em++.bat
	-- Check for working CXX compiler: C:/code/emsdk/emscripten/incoming/em++.bat -- works
	-- Detecting CXX compiler ABI info
	-- Detecting CXX compiler ABI info - done
	-- Detecting CXX compile features
	-- Detecting CXX compile features - done
	-- Looking for include file stdint.h
	-- Looking for include file stdint.h - found
	-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
	-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
	-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
	-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
	-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
	-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
	-- Found Urho3D: as CMake target
	-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)
	-- Could NOT find Dot (missing:  DOXYGEN_DOT_EXECUTABLE)
	-- Configuring done
	-- Generating done
	-- Build files have been written to: C:/code/Urho3D/build_emscripten

	C:\code\Urho3D>cd build_emscripten

	C:\code\Urho3D\build_emscripten>mingw32-make 12_PhysicsStressTest
	Scanning dependencies of target PackageTool
	[  0%] Creating directories for 'PackageTool'
	[  0%] No download step for 'PackageTool'
	[  0%] No patch step for 'PackageTool'
	[  0%] No update step for 'PackageTool'
	[  1%] Performing configure step for 'PackageTool'
	-- The C compiler identification is GNU 5.2.0
	-- The CXX compiler identification is GNU 5.2.0
	-- Check for working C compiler: C:/Program Files/mingw-w64/x86_64-5.2.0-posix-seh-rt_v4-rev0/mingw64/bin/gcc.exe
	-- Check for working C compiler: C:/Program Files/mingw-w64/x86_64-5.2.0-posix-seh-rt_v4-rev0/mingw64/bin/gcc.exe -- works
	-- Detecting C compiler ABI info
	-- Detecting C compiler ABI info - done
	-- Detecting C compile features
	-- Detecting C compile features - done
	-- Check for working CXX compiler: C:/Program Files/mingw-w64/x86_64-5.2.0-posix-seh-rt_v4-rev0/mingw64/bin/g++.exe
	-- Check for working CXX compiler: C:/Program Files/mingw-w64/x86_64-5.2.0-posix-seh-rt_v4-rev0/mingw64/bin/g++.exe -- works
	-- Detecting CXX compiler ABI info
	-- Detecting CXX compiler ABI info - done
	-- Detecting CXX compile features
	-- Detecting CXX compile features - done
	-- Looking for include file stdint.h
	-- Looking for include file stdint.h - found
	-- Looking for include file wbemcli.h
	-- Looking for include file wbemcli.h - found
	-- Configuring done
	-- Generating done
	-- Build files have been written to: C:/code/Urho3D/build_emscripten/Source/Tools/PackageTool-prefix/src/PackageTool-build
	[  1%] Performing build step for 'PackageTool'
	Scanning dependencies of target LibCpuId
	[  0%] Building C object host/LibCpuId/CMakeFiles/LibCpuId.dir/src/asm-bits.c.ob
	...
	[  4%] Linking C static library libLibCpuId.a
	[  4%] Built target LibCpuId
	Scanning dependencies of target SDL
	[  5%] Building C object host/SDL/CMakeFiles/SDL.dir/src/SDL.c.obj
	...
	[ 75%] Linking C static library libSDL.a
	[ 75%] Built target SDL
	Scanning dependencies of target LZ4
	[ 75%] Building C object host/LZ4/CMakeFiles/LZ4.dir/lz4.c.obj
	[ 76%] Building C object host/LZ4/CMakeFiles/LZ4.dir/lz4hc.c.obj
	[ 77%] Linking C static library libLZ4.a
	[ 77%] Built target LZ4
	Scanning dependencies of target PackageTool
	[ 78%] Building CXX object CMakeFiles/PackageTool.dir/PackageTool.cpp.obj
	C:\code\Urho3D\Source\Tools\PackageTool\PackageTool.cpp:23:33: fatal error: Urho3D/Core/Context.h: No such file or directory
	compilation terminated.
	CMakeFiles\PackageTool.dir\build.make:62: recipe for target 'CMakeFiles/PackageTool.dir/PackageTool.cpp.obj' failed
	mingw32-make[6]: *** [CMakeFiles/PackageTool.dir/PackageTool.cpp.obj] Error 1
	CMakeFiles\Makefile2:68: recipe for target 'CMakeFiles/PackageTool.dir/all' failed
	mingw32-make[5]: *** [CMakeFiles/PackageTool.dir/all] Error 2
	makefile:126: recipe for target 'all' failed
	mingw32-make[4]: *** [all] Error 2
	Source\Tools\CMakeFiles\PackageTool.dir\build.make:109: recipe for target 'Source/Tools/PackageTool-prefix/src/PackageTool-stamp/PackageTool-build' failed
	mingw32-make[3]: *** [Source/Tools/PackageTool-prefix/src/PackageTool-stamp/PackageTool-build] Error 2
	CMakeFiles\Makefile2:988: recipe for target 'Source/Tools/CMakeFiles/PackageTool.dir/all' failed
	mingw32-make[2]: *** [Source/Tools/CMakeFiles/PackageTool.dir/all] Error 2
	CMakeFiles\Makefile2:2450: recipe for target 'Source/Samples/12_PhysicsStressTest/CMakeFiles/12_PhysicsStressTest.dir/rule' failed
	mingw32-make[1]: *** [Source/Samples/12_PhysicsStressTest/CMakeFiles/12_PhysicsStressTest.dir/rule] Error 2
	makefile:690: recipe for target '12_PhysicsStressTest' failed
	mingw32-make: *** [12_PhysicsStressTest] Error 2

**Comment by weitjong** [comment]
This is related to issue #913. When in fallback mode to setup the SDK-like include dirs, our build system does a directory/file copy at the post-build step of each library including Urho3D library. This issue is again only unique to Windows host system without MKLINK. However, for this issue I do see a quick and easy solution to workaround it.

**Comment by juj** [comment]
Very nice, confirmed it to work. Thanks for the speedy fix!
