### ISSUE TITLE
reload script resource dependency not working 

### ISSUE THREAD

**Issue by 299299** [urho3d/Urho3D#919]
how to reproduce:

 1. using anglescript, the main script file include some other script file,  and assign autoReloadResources=true in script start function.
 2. edit and save included script file.
 3. game script is not reloaded.

 root cause:
  when the main script file is loaded, the autoReloadResources is not assigned yet, so the resource dependency (the include script file) is not added to the dependency map in resource cache.

 add a commnd line option to set autoReloadResources flag can solve this problem.

**Comment by cadaver** [comment]
The proper fix will be to track resource dependencies all the time. Only few resources use them (scripts, shaders, multi-image textures, XMLs with include files) so the overhead is not large.
