### ISSUE TITLE
Use __EMSCRIPTEN__ throughout the codebase instead of EMSCRIPTEN.

### ISSUE THREAD

**Issue by juj** [urho3d/Urho3D#921]
Historically Emscripten had the `EMSCRIPTEN` #define to signal that the compiler is Emscripten. This was however deemed bad form, since it is outside the namespace of reserved words for compilers according to ISO C standard, so the official predefine has since become `__EMSCRIPTEN__`. It would be better to use that instead of `EMSCRIPTEN` (though I expect `EMSCRIPTEN` will be supported for a long time to come still). To avoid potential breakages in the future, consider using `__EMSCRIPTEN__` instead of `EMSCRIPTEN`.

Also, in a similar fashion, using

    #include <emscripten/emscripten.h>

is considered better form than

    #include <emscripten.h>

to be clear about the include namespace.

**Comment by weitjong** [comment]
Confirmed the ```__EMSCRIPTEN__``` is detected. These are the defined macros that matches EMSCRIPTEN grep keyword.
```
#define EMSCRIPTEN 1
#define __EMSCRIPTEN__ 1
#define __EMSCRIPTEN_major__ 1
#define __EMSCRIPTEN_minor__ 34
#define __EMSCRIPTEN_tiny__ 10
```
