### ISSUE TITLE
Emscripten Release build passes both -Oz and -O3 linker flags to final link.

### ISSUE THREAD

**Issue by juj** [urho3d/Urho3D#925]
Building with

	git clone https://github.com/urho3d/Urho3D.git
	cd Urho3D
	mkdir build_emscripten
	cmake_emscripten.bat build_emscripten -DURHO3D_SAMPLES=1 -DCMAKE_BUILD_TYPE=Release
	cd build_emscripten
	mingw32-make 12_PhysicsStressTest VERBOSE=1

it looks like the final link step comes out as follows:

	C:\code\emsdk\emscripten\incoming\em++.bat
	       -Wno-invalid-offsetof
	       -ffast-math
	       -m32
	       -Wno-warn-absolute-paths
	       -Wno-unknown-warning-option
	       -Oz
	       -DNDEBUG
	       -s TOTAL_MEMORY=33554432
	       -s USE_SDL=2
	       -s NO_EXIT_RUNTIME=1
	       -s ERROR_ON_UNDEFINED_SYMBOLS=1
	       --shell-file C:/code/Urho3D/build_incoming/Source/shell.html
	       --preload-file C:/code/Urho3D/build_incoming/bin/CoreData.pak@/CoreData.pak
	       --use-preload-cache
	       --preload-file C:/code/Urho3D/build_incoming/bin/Data.pak@/Data.pak
	       --use-preload-cache
	       -O3
	       -s AGGRESSIVE_VARIABLE_ELIMINATION=1
	       @CMakeFiles\12_PhysicsStressTest.dir\objects1.rsp
	       -o ..\..\..\bin\12_PhysicsStressTest.html
	       @CMakeFiles\12_PhysicsStressTest.dir\linklibs.rsp

which specifies the two incompatible options `-Oz` and `-O3`. I believe the spec says that the last one takes effect, so the builds come out `-O3` (as desired?). It looks like `-Oz` can be removed. Or was the intent to build with `-Oz`? Generally `-O3` is preferred, so I'm assuming that's the intended one.

**Comment by juj** [comment]
Also looks like that in compile steps to build .cpp files, only `-Oz` is passed. Unless there is a special detected cause to do so, we generally recommend that Emscripten developers match the compiler and linker flags with the same optimization flags, so perhaps at compile step `-Oz` would like to be `-O3` instead?

**Comment by weitjong** [comment]
It is intentional. It has been configured as so after I read this: https://groups.google.com/forum/#!searchin/emscripten-discuss/Oz$20O3/emscripten-discuss/18sek9KX5tw/7P2pjjjOJ_sJ. As pointed out by Boris' post, it relies on linker to use the last one specified.

However, I have not followed all the discussion in the Emscripten Google Discussion. So, what we have configured may probably be already superseded by any improvement made in Emscripten compiler.

**Comment by juj** [comment]
Thanks, interesting - it looks like after locally changing `-Oz` to `-O3`, the final JS code size increased by about 1MB from ~10MB to ~11MB, so I did not feel a big pressure to optimize for size. In `-Oz` I see that Bullet fails to inline a 3D dot product function, which shows up as hot in the profile, but I don't have any numbers to report yet how big the difference is with both. I'll experiment more on the effect of `-Oz` vs `-O3` in compile step, but in any case, passing *both* `-Oz` and `-O3` to link step is redundant.

**Comment by weitjong** [comment]
>  but in any case, passing both -Oz and -O3 to link step is redundant.

Yes, I agree. Perhaps there is a better way that I do not know yet, but there is no way to tell CMake to use one flag for compiling phase and another for linking phase. Whatever is set in the compiling phase will carry over to linking phase, which is expected. We could inject another flag just for the linker though and linker just takes the last one specified.

**Comment by juj** [comment]
Oh, thanks, re-reading again your comments, I now understand the original point you made. Let's close this as known-and-not-a-concern.
