### ISSUE TITLE
Removing ObjectAnimation and ValueAnimation

### ISSUE THREAD

**Issue by Mike3D** [urho3d/Urho3D#928]
Currently we can remove a ValueAnimation from an ObjectAnimation using RemoveAttributeAnimation(), or toggle it on/off.
But there is no way to actually remove the ObjectAnimation/ValueAnimation itself or remove a single ValueAnimation created 'outside' of an ObjectAnimation.

**Comment by cadaver** [comment]
It seems that you can set a null ObjectAnimation, which should in effect remove all the attribute animation tracks contained within the previous animation, or assign a null attribute animation to an attribute name, which will remove the existing one.

Can you test that these work as expected?

However, it should be documented that this is the way to remove, or alternatively/better, add explicit Remove() functions.

**Comment by Mike3D** [comment]
Thanks for the commits, they will make life easier.
Documentation now needs some improvements, I'll try to do this soon.
