### ISSUE TITLE
Consider upgrading to Bullet 2.83.6?

### ISSUE THREAD

**Issue by juj** [urho3d/Urho3D#929]
As part of investigating https://github.com/bulletphysics/bullet3/issues/482 , I upgraded Urho3D Bullet from 2.82 to 2.83.6. I could submit that as a pull request, but before I do so, has there been some specific reason to stick to Bullet 2.82? (it's from October 2013) Would a PR to upgrade to Bullet 2.83.6 be desirable?

**Comment by cadaver** [comment]
There is no other specific reason than lack of time, and not noticing significant behavior improvements (e.g. in internal edge collision), as far as I remember. If you submit a PR, make sure you retain all the Urho-specific hacks and modifications. We'll probably update it too at some point, even if you don't submit one.

**Comment by juj** [comment]
Yeah, I was careful to preserve all the Urho3D localmods, and looked through git history to spot where those have been done and searched for "Urho3D" notes in the source, and reapplied them. Also kept the custom CMakeLists.txt version.

**Comment by juj** [comment]
Thanks for the help here!
