### ISSUE TITLE
possible bug in urho3d spine skeleton animation

### ISSUE THREAD

**Issue by yushli** [urho3d/Urho3D#932]
Use spine-c's test data spineboy.json in sample 33, If the mouse click happens during the gun firing, the firing will not be destroyed in next animation 
![screenshot from 2015-10-09 19 48 06](https://cloud.githubusercontent.com/assets/1681453/10393075/350bb586-6ebf-11e5-984d-05b1d52344d4.png)
![screenshot from 2015-10-09 19 48 34](https://cloud.githubusercontent.com/assets/1681453/10393080/3ea0c4d8-6ebf-11e5-865f-6ed61091d234.png)

**Comment by yushli** [comment]
any feedback on this issue?

**Comment by aster2013** [comment]
Can you post your code here?

**Comment by yushli** [comment]
using sample 33's c++ source code. and change line 86 into
AnimationSet2D* spriterAnimationSet = cache->GetResource<AnimationSet2D>("Urho2D/imp/spineboy.json");

spineboy.json is from 
https://github.com/EsotericSoftware/spine-runtimes/tree/master/spine-c/data
