### ISSUE TITLE
Emscripten link warning on file merge.bat in static library.

### ISSUE THREAD

**Issue by juj** [urho3d/Urho3D#937]
CMake builds for Emscripten are giving this message

	[ 99%] Linking CXX executable ..\..\..\bin\06_SkeletalAnimation.html
	WARNING:root:loading from archive C:\code\Urho3D\build_emcc_sse2\lib\libUrho3D.a
	, which has duplicate entries (files with identical base names). this is dangero
	us as only the last will be taken into account, and you may see surprising undef
	ined symbols later. you should rename source files to avoid this problem (or avo
	id .a archives, and just link bitcode together to form libraries for later linki
	ng)
	WARNING:root:   duplicate: merge.bat
	[ 99%] Built target 06_SkeletalAnimation
	[100%] Linking CXX executable ..\..\..\bin\12_PhysicsStressTest.html
	WARNING:root:loading from archive C:\code\Urho3D\build_emcc_sse2\lib\libUrho3D.a
	, which has duplicate entries (files with identical base names). this is dangero
	us as only the last will be taken into account, and you may see surprising undef
	ined symbols later. you should rename source files to avoid this problem (or avo
	id .a archives, and just link bitcode together to form libraries for later linki
	ng)
	WARNING:root:   duplicate: merge.bat
	[100%] Built target 12_PhysicsStressTest

That looks like a temporary work file, and it is being put into the generated .a files by accident? (There won't be any problem in the build with this since .bat files don't contain program code, so this is just silly noise)

**Comment by weitjong** [comment]
Thanks for reporting this.
