### ISSUE TITLE
Feature request: Add URHO3D_THREADING CMake option?

### ISSUE THREAD

**Issue by juj** [urho3d/Urho3D#939]
Currently threading is hardcoded to be enabled on all other platforms than Emscripten. It would be useful to have a `URHO3D_THREADING` option, which could be enabled or disabled on all operating systems from the command line (including Emscripten). The default could be to enable on all other platforms than Emscripten. After that one could forcibly disable threading with `URHO3D_THREADING=0` in CMake, for debugging and profiling purposes. I believe the Urho3D task architecture should allow for this kind of scheme?

**Comment by cadaver** [comment]
This is in fact necessary to guarantee correct operation anyway. The resource background loading code currently assumes that threading is supported so it would fail if attempted on Emscripten.

Note that once the support is in, when you enable threading for experimental Emscripten, you'll have to supply the amount of worker threads manually to the engine initialization, as GetNumPhysicalCPUs ( = default number of worker threads) always returns 1 on Emscripten.

**Comment by juj** [comment]
Thanks for taking this on so quickly!
