### ISSUE TITLE
URHO3D_SSE build option targets SSE1 or SSE2?

### ISSUE THREAD

**Issue by juj** [urho3d/Urho3D#941]
It's slightly unclear whether `URHO3D_SSE` is meant to target SSE1 or SSE2. In one hand it apparently looks like it's SSE1, since it is configured to pass `/arch:SSE` and `-msse` to the build in CMake, but on the other hand, Bullet is configured to build with SIMD enabled if `URHO3D_SSE` is set, and since Bullet SIMD support requires SSE2, currently enabling `URHO3D_SSE` requires SSE2 support to exist.

The Travis CI check in PR https://github.com/urho3d/Urho3D/pull/940 fails, because it adds new SSE2 code, but only `-msse` is passed when `URHO3D_SSE` is set, which fails the build.

To fix this discrepancy, would you prefer that

a) `URHO3D_SSE` is taken to mean SSE2 support, so CMake should update to use `/arch:SSE2` and `-msse2`, or
b) add a separate `URHO3D_SSE2=1` CMake option and compile-time #define, and only enable Bullet to build with SIMD enabled if `URHO3D_SSE2=1` is specified.

I'd favor option a), since there is extremely few hardware out there that would only have SSE1.

**Comment by cadaver** [comment]
It's supposed to target SSE1, but it's an oversight to not have noticed that Bullet actually uses SSE2.

Since SSE can be disabled in any case, and SSE1 only support is rare as you said, I wouldn't mind bumping it to SSE2 support.

**Comment by juj** [comment]
Ok, sounds good. Also noticed that stb_image uses SSE2 in its SIMD level when `URHO3D_SSE` is enabled, i.e. it has the following code:

    #ifndef URHO3D_SSE
    #define STBI_NO_SIMD
    #endif
    ....
    #if !defined(STBI_NO_SIMD) && defined(STBI__X86_TARGET)
    #define STBI_SSE2
    #include <emmintrin.h>

I'll update `URHO3D_SSE` to mean SSE2 in my PR.
