### ISSUE TITLE
Add type info for object, make type info more general.

### ISSUE THREAD

**Issue by aster2013** [urho3d/Urho3D#943]
Current Urho3D's object type system is very simple, but missing some information for type checking, for example, Is Button class is type of BorderImage etc.
Add type info will make it more general for type checking, for detail information, please view the 'type-info' branch.

**Comment by cadaver** [comment]
That branch looks nice. There was a more extreme reflection refactoring proposed on the forum but this is something I'd have no problem merging into master.
