### ISSUE TITLE
BoundingBox::Clip() logic?

### ISSUE THREAD

**Issue by juj** [urho3d/Urho3D#944]
The swap test in https://github.com/urho3d/Urho3D/blob/3dcab4c039374515ac3d5e66621c7e17aff25dde/Source/Urho3D/Math/BoundingBox.cpp#L108 looks a bit fishy. Isn't the intent of `BoundingBox::Clip(box)` to discard/cut off the parts of `this` box that lie outside the given box `box`? In that case, if the first tests make the result degenerate, shouldn't the degeneracy test set `defined_ = false;` instead of swapping `min_` and `max_`?

**Comment by cadaver** [comment]
Yes, that logic looks wrong. It appears that the function is not even used in the engine / rendering code, and it's from the earliest post-V1.0 commit (2011). Will correct.
