### ISSUE TITLE
Suspicious implicit Quaternion constructors

### ISSUE THREAD

**Issue by juj** [urho3d/Urho3D#947]
The class `Quaternion` has the following two implicit constructors:

    /// Construct from an angle (in degrees, for Urho2D).
    Quaternion(float angle)
    {
        FromAngleAxis(angle, Vector3::FORWARD);
    }

    /// Construct from a rotation matrix.
    Quaternion(const Matrix3& matrix)
    {
        FromRotationMatrix(matrix);
    }

which both serve as implicit conversion operators, e.g. in assignments, like `someQuat = someFloat;` or `someQuat = someMatrix;` or function calls, `someFunctionTakingQuaternion(someFloat);`. This could lead to not catching odd bugs. Implicitly converting a float to a quat feels bad, but also implicitly converting a matrix to a quat, because not all matrix->quat conversions succeed, if the matrix is of bad form and not a rotation matrix. Perhaps both these constructors should be `explicit`?

Also, several classes have an implicit conversion from a `float *` to the appropriate type:

	Find all "(const float* data)", Subfolders, Find Results 1, Entire Solution, ""
	  C:\code\Urho3D\Source\Urho3D\Math\Color.h(85):    Color(const float* data) :
	  C:\code\Urho3D\Source\Urho3D\Math\Matrix3.h(79):    Matrix3(const float* data) :
	  C:\code\Urho3D\Source\Urho3D\Math\Matrix3x4.h(147):    Matrix3x4(const float* data)
	  C:\code\Urho3D\Source\Urho3D\Math\Matrix4.h(145):    Matrix4(const float* data)
	  C:\code\Urho3D\Source\Urho3D\Math\Quaternion.h(81):    Quaternion(const float* data)
	  C:\code\Urho3D\Source\Urho3D\Math\Rect.h(67):    Rect(const float* data) :
	  C:\code\Urho3D\Source\Urho3D\Math\Vector2.h(57):    Vector2(const float* data) :
	  C:\code\Urho3D\Source\Urho3D\Math\Vector3.h(83):    Vector3(const float* data) :
	  C:\code\Urho3D\Source\Urho3D\Math\Vector4.h(71):    Vector4(const float* data) :

Perhaps it would be safest to make all of these `explicit` as well?

**Comment by cadaver** [comment]
Thanks, good finds. I don't think none of these should or need to be implicit.
