### ISSUE TITLE
SSE2NEON

### ISSUE THREAD

**Issue by weitjong** [urho3d/Urho3D#958]
This is follow up discussion from https://github.com/urho3d/Urho3D/pull/950#issuecomment-148293525.

Need proper instrumentation tool to measure if this approach is beneficial at all.

**Comment by weitjong** [comment]
The code can be found in this new topic branch: https://github.com/urho3d/Urho3D/tree/sse2neon

**Comment by boberfly** [comment]
Feel free to use this also:
https://github.com/boberfly/Urho3D/tree/ispc_texcomp

Writing some stuff in ISPC might be more fun.
