### ISSUE TITLE
Fluctuating transforms/math with URHO3D_SSE codepath

### ISSUE THREAD

**Issue by carnalis** [urho3d/Urho3D#959]
node->Rotate(Quaternion(0,0,0)); // or any value
node->GetWorldDirection() then fluctuates between two values, frame-by-frame.

**Comment by MonkeyFirst** [comment]
Maybe need to force alignment for wxyz floats ? 

Also I know in times of Pentiume 1/2 then you start using of MMX operation you was needed use the emms asm operation to keep MMX with clear behavior to avoid various bugs. Maybe for SSE will need use something like this?

**Comment by juj** [comment]
What are the two values it fluctuates between? Do they represent the same orientation? I tried to reproduce the problem but failed. Can you make a demo showing the problem?

**Comment by carnalis** [comment]
I reproduced the behavior with modified 04_StaticScene.cpp (debug-print, F2)
```C++
void StaticScene::HandleUpdate(StringHash eventType, VariantMap& eventData)
{
    using namespace Update;

    // Take the frame time step, which is stored as a float
    float timeStep = eventData[P_TIMESTEP].GetFloat();

    // Move the camera, scale movement with time step
    MoveCamera(timeStep);

Node* planeNode(scene_->GetChild("Plane"));
planeNode->Rotate(Quaternion(0,0,0));
GetSubsystem<DebugHud>()->SetAppStats("worldRot", planeNode->GetWorldRotation());
}
```
When studying the behavior in my own application, I determined it's not strictly two values:
Node's initial rotation "1 0 0 0"
0.999878 0 0 0
1.00012 0 0 0
0.999898 0 0 0
1.00015 0 0 0
0.999879 0 0 0

Node's initial rotation "0.707107 0 0.707107 0"  (in this case the rotation diff was actually visible)
0.707107 0 0.707107 0
0.706934 0 0.706934 0

I guess this could be arch-related and will follow up with further info if it will help.

**Comment by juj** [comment]
Above PR improves the precision of the SSE math, and in the proposed test case, I no longer saw such fluctuation; however, given the nature of floating point arithmetic, there is no hard guarantee that for some orientation values such fluctuation would be absent.
