### ISSUE TITLE
Sample 33 Urho2DSpriterAnimation is broken in master branch

### ISSUE THREAD

**Issue by yushli** [urho3d/Urho3D#963]
In windows vs2015 64 bit, using the latest master branch, sample 33 is built and run successfully, but the animation doesn't show at all. the screen is black.

**Comment by weitjong** [comment]
It happens on Linux platform as well. Most likely it happens to all platforms. You can help to use the git bisect to find the commit that started this issue.

**Comment by ijsonlin** [comment]
Well, I found that the issue is caused by this commit: fbd07ac but I have no idea to handle it.
Details:
    The reason is that, the BoundingBox undefined values are M_INFINITY, if I change it to ZERO, it would be works well.
