### ISSUE TITLE
Alt+Enter Bug

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#967]
1) Run Game.exe - menu is visible
2) Press Alt+Enter - screen is empty
3) Press Alt+Enter - menu is visible
4) Press Alt+Enter - menu is visible

https://drive.google.com/open?id=0B_XuF2wRVpw4X183MEJLdld3R1U

Also, how to deprecate toggling to fullscreen? I need only window mode.

**Comment by cadaver** [comment]
Input::SetToggleFullscreen(false)

**Comment by 1vanK** [comment]
Thank you

**Comment by cadaver** [comment]
Looks like Text3D not handling the texture data loss similarly as the actual Text UI element.
