### ISSUE TITLE
F12 Exception

### ISSUE THREAD

**Issue by cosmy1** [urho3d/Urho3D#971]
A strange exception is thrown when hitting F12 while debugging in Visual Studio 2013
![f12_exception](https://cloud.githubusercontent.com/assets/1329119/10623721/cfac0cdc-7791-11e5-8eff-56bcf376d100.jpg)

Happens in all C++ demos.

**Comment by cadaver** [comment]
What is supposed to happen from F12? The only use I see in the C++ samples themselves is that CrowdNavigation hides/shows instructions.

**Comment by cosmy1** [comment]
Ah, I disabled CrowdNavigation from compilation and this key shouldn't do anything.

**Comment by cosmy1** [comment]
Wel I want to dig into SDL since its like a black-box for all Windows related code, but I want to be sure this exception happens not just to me...
Anyone have the same problem? I'm running Windows 10 and I tried both Visual Studio 2013 & 2015.

**Comment by 1vanK** [comment]
Win7, VS2015 Community, no any problems

**Comment by cosmy1** [comment]
I forgot to mention Direct3D 11.

**Comment by cadaver** [comment]
No exception on VS 2013 Express + D3D11. Will still check community edition at home, which has the graphics debugger. Do you have programs such as Fraps running?

**Comment by cosmy1** [comment]
No I'm not running anything which can interacts with Urho3D. Did you run it on Windows 10?

**Comment by cadaver** [comment]
No, Windows 7. Does it happen only when running inside debugger? If yes it's not important for end users in any case; can be some sort of forced breakpoint which would point it to not being an issue in Urho3D itself.

**Comment by cosmy1** [comment]
Yes happens only when debugging and only on Windows 10. (I tested on Windows 7 and works perfectly). I tested other software with Visual C++ on Windows 10 and F12 works.

**Comment by cadaver** [comment]
Seems to happen in Win8 and newer. Confirmed to happen to others and is not Urho3D specific.

http://www.gamedev.net/topic/561537-disabling-f12-in-visual-studio/
http://stackoverflow.com/questions/18997754/how-to-disable-f12-to-debug-application-in-visual-studio-2012
https://msdn.microsoft.com/en-us/library/ms646309%28VS.85%29.aspx
