### ISSUE TITLE
Black water

### ISSUE THREAD

**Issue by 1vanK** [urho3d/Urho3D#974]
In sample "23_Water" water is black. It is a bug or a feature? :) Previously the water was transparent.

**Comment by friesencr** [comment]
What platform? What graphics stack Gl or dx?

**Comment by 1vanK** [comment]
![1](https://cloud.githubusercontent.com/assets/13021826/10652825/b9798000-786a-11e5-80e2-64455f8611f8.jpg)

Win7 OpenGL
