### ISSUE TITLE
Box2D assert

### ISSUE THREAD

**Issue by cosmy1** [urho3d/Urho3D#978]
```Urho3D::CollisionChain2D* shape = node_->CreateComponent<Urho3D::CollisionChain2D>();```

This line cause an assert inside Box2D

![immagine](https://cloud.githubusercontent.com/assets/1329119/10713352/9f746600-7aba-11e5-9013-cbeb46018774.png)

**Comment by 1vanK** [comment]
by the way CollisionChain2D missing in the editor

**Comment by cosmy1** [comment]
I added a PR for the fix hope is the best way to deal with

**Comment by cadaver** [comment]
Merged the PR. Did a bit of cleanup / simplification but otherwise it was OK.
