### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by silverkorn** [urho3d/Urho3D#984]
I think it would be suitable to follow the [semantic versioning 2.0.0](http://semver.org/) (MAJOR __.__ MINOR __.__ PATCH) since the current logic can be confusing (e.g.: 1.4 > 1.31) and libraries under many languages exist to parse this versioning pattern.

That's just a suggestion and I'm aware that it may break your current format.
If it's too much trouble under any circumstance (e.g.: @weitjong's hard work on Travis-CI), feel free to close this issue.

Thanks!

**Comment by weitjong** [comment]
This has been discussed here. http://urho3d.prophpbb.com/topic723.html

I would like to think that our build system including its extension on Travis-CI has already designed to support the MAJOR.MINOR.PATCH format. However, it is solely at the discretion of Lasse on when he thinks it is time to create a git release tag and what the release tag should be. As Urho3D project development is quite active and for all the practicality sake, IMHO, we don't need to burden him to make releases more frequently than he is comfortable with. I do agree with you that semantically that release 1.4 should have been tagged as 1.32 instead.

**Comment by cadaver** [comment]
From purely a number formatting perspective it's fine by me to move to the semantic versioning. However, we practically break the API in a backward-incompatible way in every release, so we likely can't follow it to the letter.

**Comment by silverkorn** [comment]
I see your points.

Actually, you could always dismiss the PATCH version in most if not all the releases. Maybe just keep it in case of a release that has a destructive behavior and needs a hotfix.

So next release could be 1.5.0, then 1.6.0 and so on.
Let say that 1.7.0 has a major problem you could create 1.7.1 just to make everyone knows that it's actually 1.7.0 with a critical fix, no special feature added. Or just ask them to use the master or the future 1.8.0 for a fix.

All development flow is at your discretion and I just thought that it was a smart way to fit in most projects, no matter the release frequency and development speed/methods.

Curiously, do you feel bad about giving major version increment on most/every release?
Personally, I think it would fit better because most of your new releases have __a lot__ of features + API incompatibilities, which make sense in both semantic versioning and my personal perspective _(around 1 or 2 major version(s) per year)_.

**Comment by cadaver** [comment]
I would like to keep continuity of the previous versioning to some degree, therefore I'd increment the major version in the case of a major API upheaval (e.g. changing the engine to a data-driven approach, similar to the scope of what Ogre 1.x -> 2.x did) So far e.g. Direct3D11 support did only warrant bumping the minor number, because the API for the most part stayed the same, though minor incompatibilities (which require fixing your program) or things to take note of did appear.

**Comment by silverkorn** [comment]
Alright!
Should I close this issue or you prefer to keep it open until next release?

**Comment by cadaver** [comment]
Good to keep it open.

**Comment by cadaver** [comment]
Release tagged; new version scheme not visible yet but next patch release will be 1.5.1 if necessary.
