### ISSUE TITLE
SpriteSheet2D issue when scaling

### ISSUE THREAD

**Issue by cosmy1** [urho3d/Urho3D#985]
```node->Scale2D(...)``` have different behaviour in ```StaticSprite2D``` using ```Sprite2D``` and ```SpriteSheet2D```.

Using ```Sprite2D```, scale function works correctly.
Using ```SpriteSheet2D```, scale function does its job but add additional translation to the node.

Seems an issue with the center: 
While ```Sprite2D``` have the right center, ```SpriteSheet2D``` take the center to the entire texture not the sprite region.

**Comment by aster2013** [comment]
hi, @cosmy1, Can you send your test code and assets to me? 
My email is: asterjian at qq dot com.

**Comment by cosmy1** [comment]
@aster2013, I sent you the code. Let me know.

**Comment by aster2013** [comment]
hi, do you have sent the code to me?

**Comment by cosmy1** [comment]
Sent you an email, didn't receive it?

**Comment by cosmy1** [comment]
Definitely center issue because happens also if you rotate it.

**Comment by aster2013** [comment]
I have tested, SpriteSheet scaling work well on my local.

**Comment by cosmy1** [comment]
Did you test the the code I sent you?

**Comment by aster2013** [comment]
I did not received your code, please resend again. Thanks.

**Comment by cosmy1** [comment]
Mmh probably some issues with your/mine email provider. Do you have Skype?

**Comment by cadaver** [comment]
The spritesheet sprite has a hotspot outside the sprite, due to the calculation of hotspot from frameWidth & frameHeight in SpriteSheet2D::EndLoadFromXMLFile(). Is that formula correct? What is the purpose of having set frameWidth & frameHeight 500 in the spritesheet xml?

**Comment by cosmy1** [comment]
Oh yes, closing this since is not Urho3D but a wrong value in the xml file.
