### ISSUE TITLE
Finding HashMap Node while it is being cleared returns incorrect result

### ISSUE THREAD

**Issue by weitjong** [urho3d/Urho3D#988]
When shutting down the engine, Context destructor attempts to clear all the registered subsystems (calling ```subystems_.Clear()```) which in turns trigger each subsystem to clean after itself in its destructor. The problem arises when one of the subsystem, Script, attempt to find an already destroyed subsystem (calling ```GetSubsystem<ResourceCache>()```) in its destructor. In a nutshell, the HashMap::Find() call is done inside the HashMap::Clear(). In Debug build configuration, the Find() returns null. In non-Debug build configuration, it returns non-null value. In MinGW build, this non-null value crashes the app later (https://github.com/urho3d/Urho3D/blob/master/Source/Urho3D/AngelScript/Script.cpp#L163).

I am not sure how to fix this. Is it a generic HashMap class issue that needs to be fixed at this class? Or  it is a specific issue with Script class that can be dealt with by checking if the engine is exiting?

**Comment by cadaver** [comment]
Preferably HashMap should be resilient to Find() while clearing. I can take a look.

**Comment by cadaver** [comment]
Please check if the commit in question fixes the issue. Now the bucket pointers are nulled at the begin of Clear().

**Comment by weitjong** [comment]
Checked and confirm that Find() consistently return null now. Thanks for the quick fix.
