### ISSUE TITLE
Huge batches issue

### ISSUE THREAD

**Issue by azzvx** [urho3d/Urho3D#990]
I recompiled Urho3D library today and I found something was wrong with Urho3D.
I found the "Batches" count become a very huge number in sample 20_HugeObjectCount.The number is 62k+ now, and it was only 4 before. 
The newest version:
https://www.dropbox.com/s/24vrpx4boprfgy6/QQ%E6%88%AA%E5%9B%BE20151028105602.png?dl=0
The older version:
https://www.dropbox.com/s/bcaju0d3gxarswu/QQ%E6%88%AA%E5%9B%BE20151028113031.png?dl=0

**Comment by xiliu98** [comment]
any one knows how this is happening?
I have the same issue on android device.

**Comment by cadaver** [comment]
If it cannot instance due to lack of support from OpenGL extensions on the device, the batch count will be large, as it uses individual draw calls instead.
