### ISSUE TITLE
ParticleEmitter->GetEffect() incorrectly returns null

### ISSUE THREAD

**Issue by Modanung** [urho3d/Urho3D#993]
The effects are visible, but GetEffect() returns null. This is causing trouble in several LucKey projects after recently checking out Urho3D. In heXon for instance explosions get removed based on ParticleEffect::GetMaxTimeToLive().

**Comment by cadaver** [comment]
Can't reproduce this at least in NinjaSnowWar. If the effect was null, the emitter would not be able to update at all. Maybe you have some library mismatch going on? In any case, I will move the GetEffect() to the .cpp file instead of being inlined, as it involves shared pointer access, for which merely forward-declaring ParticleEffect is not sufficient.

**Comment by Modanung** [comment]
Moving the definition to the .cpp file did solve the problem. Thanks!

**Comment by Modanung** [comment]
That's not all though: Mist is having drawing problems (flickering or absent) and MonkeyFirst's TailGenerator causes a crash when resizing the Drawable Vector<SourceBatch> batches_.

**Comment by cadaver** [comment]
That seriously sounds like you have a library / header mismatch. Check that you cleanly recompile Urho, and that you use the same compiler settings for anything that might affect the ABI.

**Comment by Modanung** [comment]
I recently switched to proprietary video card drivers (NVidia 352, tested), could this be causing all these problems? They do seem Drawable related.
I'm having trouble switching back to the (free) Xorg video drivers properly; I'll investigate more later.

**Comment by Modanung** [comment]
...nope. That's not it.
After a fresh install of Xubuntu it turned out the NVidia drivers were not causing any trouble.
I've checked out the latest version of Urho3D, cleaned both Urho3D and all my projects. But the problems remain. The flickering of the mist differs per run, not per build.
I don't know where to look and would rather not commit changes to heXon without the TailGenerator for instance.

**Comment by Modanung** [comment]
Solved.
