### ISSUE TITLE
Short/small sound instances played concurrently are rendered sequentially, not simultaneously

### ISSUE THREAD

**Issue by carnalis** [urho3d/Urho3D#996]
Known platforms: Linux, MSWin

Play a short sample rapidly over one or more updates - SoundSource or SoundSource3D.

e.g., code like this executed in rapid succession (on same or different updates):
```C++
String soundResourceName("Sounds/UI/switch_on.wav");
Node* soundNode(scene->CreateChild(soundResourceName));
SoundSource* soundSource(soundNode->CreateComponent<SoundSource>());
soundSource->SetSoundType(SOUND_MASTER);
soundSource->SetGain(1.0f);
soundSource->Play(GetSubsystem<ResourceCache>()->GetResource<Sound>(soundResourceName));
soundSource->SetAutoRemove(true);
```
* Does not occur between different sound resources.
* Occurs with a variety of file and sample formats.
* Issue was noticed at least as far back as 1.4

One suggestion was a possible mutex lock..

**Comment by cadaver** [comment]
You are hitting the granularity of the audio mixing fragment / buffer size. The default is 100ms, which is quite large, but is a safe value to prevent dropouts. You could configure it smaller in the engine startup parameters, for example 50ms. Note that the actual buffer size that will be used depends on SDL and the platform.

If you want to guarantee sounds starting exactly simultaneously, you can hold on to the audio mutex while initiating playback. See Audio::GetMutex().

**Comment by cadaver** [comment]
Note that generally much better responsivity would be achieved by having the audio thread poll the sound output device for free space in the output buffer, for example at 60Hz rate. On each run it would mix as much audio as required to fill this space. However, when using SDL, we're rather at the "mercy" of its audio callback, which tells how much we must mix.

**Comment by friesencr** [comment]
Sdl 2.04 has a new audio api that is not callback based.
