### ISSUE TITLE
UIDrag sample: multi-button drag either doesn't work or isn't meaningful

### ISSUE THREAD

**Issue by bvanevery** [urho3d/Urho3D#997]
The sample gives the following directions on the screen: "Drag on the buttons to move them around.  Multi-button drag also supported."  On Windows nothing like I'd imagine a "multi-button drag" behavior to be, actually seems to happen.  I would expect to be able to SHIFT-click or CTRL-click multiple buttons to select them as per Windows UI conventions, but this does not work.  I thought I might be able to click to drag a selection rectangle around multiple buttons, but this is not implemented.  Mouse hovering will select a button, and for some reason, hovering to a 2nd button will select the 2nd button as well.  But not a 3rd; the 2nd button will deselect and the 3rd will select.  Only 2 buttons at a time are ever selected.  Also when the mouse is clicked down, the selection goes back to only 1 button, so it is impossible to drag 2 buttons.  Either the sample is supposed to do some kind of multi-button selection on Windows and it's bugged, or it's not and the instructional text is not meaningful.

**Comment by cadaver** [comment]
This sample is intended to demonstrate multi-touch input. Probably the instructions could be worded better.
