### ISSUE TITLE
Urho2DPhysics sample could use a simulation reset button

### ISSUE THREAD

**Issue by bvanevery** [urho3d/Urho3D#998]
When this sample begins, 2D blocks fall onto a 2D shelf.  The following instructions are given: "Use WASD keys to move, use PageUp PageDown keys to zoom."  The 2D blocks fall very quickly and most are at rest within 3 seconds.  All are at rest within 6 seconds.  I'm not seeing a lot of point in using the movement and zoom keys, as whatever sim is to be looked at, is over.  The falling of the blocks is the primary thing of interest.  The only way to see them fall again, is to close and restart the sample.  So, one cannot set up the WASD and zoom keys to get the view one might want, one is stuck with the default view.  Or, one has to be exceedingly exceedingly fast to maneuver in the fractions of seconds before the simulation is underway.

If the simulation has a "reset / drop blocks" button, then the user can line up the view and zoom as they wish, and see what's going on.  Bonus points if the user had a way of slowing down the sim, but at least resetting it is the path of least resistance and advisable.

**Comment by yushli** [comment]
second that. And also some interaction with the scene should be added to show more results, etc, click and drag to move the objects, click on the empty space to spawn new objects.
